# 03 · Join Sofascore + Capology — England Premier League 20/21

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2020/21 de Premier League inglesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_england_2021.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_england_2021.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  524 jugadores | 116 columnas
Capology:   593 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   brighton hove albion
   leeds united
   leicester city
   newcastle united
   tottenham hotspur
   west bromwich albion
   west ham united

En Capology pero no en Sofascore:
   brighton
   leeds
   leicester
   newcastle
   tottenham
   west bromwich
   west ham

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brighton':'brighton hove albion',
            'leeds':'leeds united',
            'leicester':'leicester city',
            'newcastle':'newcastle united',
            'tottenham':'tottenham hotspur',
            'west bromwich':'west bromwich albion',
            'west ham':'west ham united'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 478/525 (91.0%)
Sin emparejar: 47

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          5
Revisión media    (0.75 ≤ score < 0.90):   3
Revisión estricta (0.50 ≤ score < 0.75):   22
Revisión muy est. (score < 0.50):           17

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf               team               cg_match  score
1   Pierre-Emile Højbjerg  Tottenham Hotspur  pierre emile hojbjerg  0.976
5        Gylfi Sigurðsson            Everton       gylfi sigurdsson  0.968
7        Łukasz Fabiański    West Ham United       lukasz fabianski  0.968
17      Andriy Yarmolenko    West Ham United      andrii yarmolenko  0.941
26          Joshua Onomah             Fulham            josh onomah  0.917

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf          team                 cg_match  score
11  Jóhann Guðmundsson       Burnley  johann berg gudmundsson  0.850
8       Edward Nketiah       Arsenal            eddie nketiah  0.815
12    Ian Carlo Poveda  Leeds United               ian poveda  0.769

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 3 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf               team              cg_match  score
33            Moise Kean            Everton         michael keane  0.696
9      Mahmoud Trézéguet        Aston Villa             trezeguet  0.692
2         Anthony Elanga  Manchester United       anthony martial  0.690
32         Rúben Vinagre      Wolverhampton           ruben neves  0.667
10  Bobby Decordova-Reid             Fulham            bobby reid  0.667
4         Frank Anguissa             Fulham  andre zambo anguissa  0.647
35           Josh Benson            Burnley        josh brownhill  0.640
31         Wesley Moraes        Aston Villa                wesley  0.632
19      Emerson Palmieri            Chelsea               emerson  0.609
42          William Fish  Manchester United      brandon williams  0.571
16        Sidnei Tavares     Leicester City        daniel amartey  0.571
3         Fabio Carvalho             Fulham        ivan cavaleiro  0.571
0       Thiago Alcântara          Liverpool                thiago  0.545
46      Lewis Richardson            Burnley        richard nartey  0.533
21           Caleb Watts        Southampton          theo walcott  0.522
41         Dane Scarlett  Tottenham Hotspur            danny rose  0.522
28       Hannibal Mejbri  Manchester United          daniel james  0.519
20       Patrick Cutrone      Wolverhampton          rui patricio  0.519
34       Tyrese Francois             Fulham      antonee robinson  0.516
18    Carney Chukwuemeka        Aston Villa         kortney hause  0.516
39       Elliot Anderson   Newcastle United             joelinton  0.500
13       Daniel Jebbison   Sheffield United         jack robinson  0.500

In [19]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mahmoud trezeguet',
                    'bobby decordova reid',
                    'frank anguissa',
                    'wesley moraes',
                    'emerson palmieri',
                    'thiago alcantara'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 6

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [20]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
45,Felipe Anderson,West Ham United,frederik alves,0.483
36,Allan Tchaptchet,Southampton,alex mccarthy,0.483
37,Kayne Ramsay,Southampton,alex mccarthy,0.480
23,Liam Delap,Manchester City,aymeric laporte,0.480
43,Nathan Broadhead,Everton,jarrad branthwaite,0.471
24,Niall Huggins,Leeds United,conor shaughnessy,0.467
29,Reda Khadra,Brighton & Hove Albion,alireza jahanbakhsh,0.467
44,Femi Seriki,Sheffield United,michael verrips,0.462
15,Antwoine Hackford,Sheffield United,oliver norwood,0.452
27,Joel Mumbongo,Burnley,josh brownhill,0.444
14,Iliman Ndiaye,Sheffield United,aaron ramsdale,0.444
38,Alexandre Jankewitz,Southampton,alex mccarthy,0.438
22,Kepa Arrizabalaga,Chelsea,kai havertz,0.429
25,Shola Shoretire,Manchester United,harry maguire,0.429
6,Theo Corbeanu,Wolverhampton,conor coady,0.417
30,Thakgalo Khanya Leshabela,Leicester City,timothy castagne,0.390
40,Jaden Philogene-Bidace,Aston Villa,conor hourihane,0.378

In [21]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [22]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 494/527 (93.7%)
Sin salario:     33

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [23]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 33

,player,team,minutesPlayed,appearances,goals,assists
0,Carney Chukwuemeka,Aston Villa,25,2,0,0
1,Jaden Philogene-Bidace,Aston Villa,1,1,0,0
2,Reda Khadra,Brighton & Hove Albion,8,1,0,0
3,Josh Benson,Burnley,272,6,0,0
4,Joel Mumbongo,Burnley,37,4,0,0
5,Lewis Richardson,Burnley,3,2,0,0
6,Kepa Arrizabalaga,Chelsea,585,7,0,0
7,Moise Kean,Everton,13,2,0,0
8,Nathan Broadhead,Everton,2,1,0,0
9,Fabio Carvalho,Fulham,255,4,1,0
10,Tyrese Francois,Fulham,14,1,0,0
11,Niall Huggins,Leeds United,37,1,0,0
12,Sidnei Tavares,Leicester City,85,2,0,0
13,Thakgalo Khanya Leshabela,Leicester City,9,1,0,0
14,Liam Delap,Manchester City,39,1,0,0
15,Anthony Elanga,Manchester United,156,2,1,0
16,Shola Shoretire,Manchester United,9,2,0,0
17,Hannibal Mejbri,Manchester United,8,1,0,0
18,William Fish,Manchester United,1,1,0,0
19,Elliot Anderson,Newcastle United,3,1,0,0
20,Daniel Jebbison,Sheffield United,284,4,1,0
21,Iliman Ndiaye,Sheffield United,11,1,0,0
22,Antwoine Hackford,Sheffield United,10,1,0,0
23,Femi Seriki,Sheffield United,1,1,0,0
24,Kayne Ramsay,Southampton,90,1,0,0
25,Caleb Watts,Southampton,42,3,0,0
26,Allan Tchaptchet,Southampton,12,1,0,0
27,Alexandre Jankewitz,Southampton,11,2,0,0
28,Dane Scarlett,Tottenham Hotspur,1,1,0,0
29,Felipe Anderson,West Ham United,2,2,0,0
30,Rúben Vinagre,Wolverhampton,172,2,0,0
31,Patrick Cutrone,Wolverhampton,23,2,0,0
32,Theo Corbeanu,Wolverhampton,8,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [24]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Aston Villa  —  SF sin salario:

                   player  minutesPlayed
0      Carney Chukwuemeka             25
1  Jaden Philogene-Bidace              1

  CG plantilla completa:

               player        player_norm
0    Ahmed Elmohamady   ahmed elmohamady
1      Anwar El Ghazi     anwar el ghazi
2     Bertrand Traoré    bertrand traore
3        Björn Engels       bjorn engels
4     Conor Hourihane    conor hourihane
5        Douglas Luiz       douglas luiz
6   Emiliano Martínez  emiliano martinez
7          Ezri Konsa         ezri konsa
8   Frédéric Guilbert  frederic guilbert
9      Henri Lansbury     henri lansbury
10      Jack Grealish      jack grealish
11       Jacob Ramsey       jacob ramsey
12          Jed Steer          jed steer
13        John McGinn        john mcginn
14       Keinan Davis       keinan davis
15      Kortney Hause      kortney hause
16      Lovre Kalinic      lovre kalinic
17  Marvelous Nakamba  marvelous nakamba
18       Matt Targett       matt targett
19         Matty Cash         matty cash
20      Morgan Sanson      morgan sanson
21        Neil Taylor        neil taylor
22      Ollie Watkins      ollie watkins
23       Ross Barkley       ross barkley
24         Tom Heaton         tom heaton
25          Trezeguet          trezeguet
26       Tyrone Mings       tyrone mings
27             Wesley             wesley

============================================================
  Brighton & Hove Albion  —  SF sin salario:

        player  minutesPlayed
0  Reda Khadra              8

  CG plantilla completa:

                 player          player_norm
0        Aaron Connolly       aaron connolly
1          Adam Lallana         adam lallana
2          Adam Webster         adam webster
3   Alexis Mac Allister  alexis mac allister
4   Alireza Jahanbakhsh  alireza jahanbakhsh
5           Andi Zeqiri          andi zeqiri
6             Ben White            ben white
7              Bernardo             bernardo
8      Christian Walton     christian walton
9              Dan Burn             dan burn
10        Danny Welbeck        danny welbeck
11         Davy Pröpper         davy propper
12        Florin Andone        florin andone
13          Jakub Moder          jakub moder
14         Jason Steele         jason steele
15       Jayson Molumby       jayson molumby
16         Joël Veltman         joel veltman
17       José Izquierdo       jose izquierdo
18     Leandro Trossard     leandro trossard
19           Lewis Dunk           lewis dunk
20          Mathew Ryan          mathew ryan
21          Max Sanders          max sanders
22     Michal Karbownik     michal karbownik
23       Moisés Caicedo       moises caicedo
24          Neal Maupay          neal maupay
25          Pascal Groß           pascal gro
26            Percy Tau            percy tau
27       Robert Sánchez       robert sanchez
28          Solly March          solly march
29        Steven Alzate        steven alzate
30        Tariq Lamptey        tariq lamptey
31        Yves Bissouma        yves bissouma

============================================================
  Burnley  —  SF sin salario:

             player  minutesPlayed
0     Joel Mumbongo             37
1       Josh Benson            272
2  Lewis Richardson              3

  CG plantilla completa:

                     player              player_norm
0             Ashley Barnes            ashley barnes
1           Ashley Westwood          ashley westwood
2    Bailey Peacock-Farrell   bailey peacock farrell
3                   Ben Mee                  ben mee
4              Bobby Thomas             bobby thomas
5            Charlie Taylor           charlie taylor
6                Chris Wood               chris wood
7             Dale Stephens            dale stephens
8             Dwight McNeil            dwight mcneil
9              Erik Pieters             erik pieters
10                Jack Cork                jack cork
11          James Tarkowski          james tarkowski
12            Jay Rodríguez            jay rodriguez
13              Jimmy Dunne              jimmy dunne
14  Jóhann Berg Gudmundsson  johann berg gudmundsson
15           Josh Brownhill           josh brownhill
16               Kevin Long               kevin long
17             Lukas Jensen             lukas jensen
18           Mace Goodridge           mace goodridge
19              Matej Vydra              matej vydra
20           Matthew Lowton           matthew lowton
21                Nick Pope                nick pope
22            Phil Bardsley            phil bardsley
23           Richard Nartey           richard nartey
24             Robbie Brady             robbie brady
25              Will Norris              will norris

============================================================
  Chelsea  —  SF sin salario:

              player  minutesPlayed
0  Kepa Arrizabalaga            585

  CG plantilla completa:

                 player          player_norm
0     Abdul Rahman Baba    abdul rahman baba
1   Andreas Christensen  andreas christensen
2       Antonio Rüdiger      antonio rudiger
3          Ben Chilwell         ben chilwell
4         Billy Gilmour        billy gilmour
5    Callum Hudson-Odoi   callum hudson odoi
6     César Azpilicueta    cesar azpilicueta
7     Charly Musonda Jr    charly musonda jr
8     Christian Pulisic    christian pulisic
9      Danny Drinkwater     danny drinkwater
10        Edouard Mendy        edouard mendy
11              Emerson              emerson
12        Fikayo Tomori        fikayo tomori
13         Hakim Ziyech         hakim ziyech
14             Jorginho             jorginho
15          Kai Havertz          kai havertz
16          Karlo Ziger          karlo ziger
17                 Kepa                 kepa
18           Kurt Zouma           kurt zouma
19        Marcos Alonso        marcos alonso
20          Mason Mount          mason mount
21        Mateo Kovacic        mateo kovacic
22         N'Golo Kanté         n golo kante
23       Olivier Giroud       olivier giroud
24          Reece James          reece james
25        Tammy Abraham        tammy abraham
26         Thiago Silva         thiago silva
27          Timo Werner          timo werner
28      Willy Caballero      willy caballero

============================================================
  Everton  —  SF sin salario:

             player  minutesPlayed
0        Moise Kean             13
1  Nathan Broadhead              2

  CG plantilla completa:

                   player            player_norm
0      Abdoulaye Doucouré     abdoulaye doucoure
1              Alex Iwobi             alex iwobi
2                   Allan                  allan
3             André Gomes            andre gomes
4          Anthony Gordon         anthony gordon
5             Ben Godfrey            ben godfrey
6          Beni Baningime         beni baningime
7                 Bernard                bernard
8              Cenk Tosun             cenk tosun
9   Dominic Calvert-Lewin  dominic calvert lewin
10           Fabian Delph           fabian delph
11       Gylfi Sigurdsson       gylfi sigurdsson
12        James Rodríguez        james rodriguez
13     Jarrad Branthwaite     jarrad branthwaite
14   Jean-Philippe Gbamin   jean philippe gbamin
15          João Virgínia          joao virginia
16            Jonas Lössl            jonas lossl
17           Jonjoe Kenny           jonjoe kenny
18        Jordan Pickford        jordan pickford
19            Joshua King            joshua king
20            Lucas Digne            lucas digne
21          Mason Holgate          mason holgate
22     Matthew Pennington     matthew pennington
23          Michael Keane          michael keane
24          Muhamed Besic          muhamed besic
25         Niels Nkounkou         niels nkounkou
26            Richarlison            richarlison
27            Robin Olsen            robin olsen
28         Seamus Coleman         seamus coleman
29             Tom Davies             tom davies
30        Yannick Bolasie        yannick bolasie
31             Yerry Mina             yerry mina

============================================================
  Fulham  —  SF sin salario:

            player  minutesPlayed
0   Fabio Carvalho            255
1  Tyrese Francois             14

  CG plantilla completa:

                  player           player_norm
0       Aboubakar Kamara      aboubakar kamara
1        Ademola Lookman       ademola lookman
2    Aleksandar Mitrovic   aleksandar mitrovic
3        Alphonse Areola       alphonse areola
4   André Zambo Anguissa  andre zambo anguissa
5       Antonee Robinson      antonee robinson
6             Bobby Reid            bobby reid
7             Denis Odoi            denis odoi
8                  Fabri                 fabri
9         George Wickens        george wickens
10         Harrison Reed         harrison reed
11        Ivan Cavaleiro        ivan cavaleiro
12        Jay Stansfield        jay stansfield
13     Jean Michaël Seri     jean michael seri
14      Joachim Andersen      joachim andersen
15             Joe Bryan             joe bryan
16             Josh Maja             josh maja
17           Josh Onomah           josh onomah
18            Kenny Tete            kenny tete
19        Kevin McDonald        kevin mcdonald
20           Marek Rodak           marek rodak
21          Mario Lemina          mario lemina
22    Maxime Le Marchand    maxime le marchand
23        Michael Hector        michael hector
24       Neeskens Kebano       neeskens kebano
25              Ola Aina              ola aina
26    Ruben Loftus-Cheek    ruben loftus cheek
27       Stefan Johansen       stefan johansen
28      Sylvester Jasper      sylvester jasper
29       Terence Kongolo       terence kongolo
30              Tim Ream              tim ream
31           Tom Cairney           tom cairney
32      Tosin Adarabioyo      tosin adarabioyo

============================================================
  Leeds United  —  SF sin salario:

          player  minutesPlayed
0  Niall Huggins             37

  CG plantilla completa:

               player        player_norm
0        Adam Forshaw       adam forshaw
1   Conor Shaughnessy  conor shaughnessy
2      Diego Llorente     diego llorente
3        Elia Caprile       elia caprile
4      Ezgjan Alioski     ezgjan alioski
5     Gaetano Berardi    gaetano berardi
6        Hélder Costa       helder costa
7          Ian Poveda         ian poveda
8       Illan Meslier      illan meslier
9       Jack Harrison      jack harrison
10   Jamie Shackleton   jamie shackleton
11       Joe Gelhardt       joe gelhardt
12    Kalvin Phillips    kalvin phillips
13       Kiko Casilla       kiko casilla
14         Leif Davis         leif davis
15        Liam Cooper        liam cooper
16        Luke Ayling        luke ayling
17      Mateusz Klich      mateusz klich
18       Oliver Casey       oliver casey
19        Ouasim Bouy        ouasim bouy
20    Pablo Hernández    pablo hernandez
21     Pascal Struijk     pascal struijk
22    Patrick Bamford    patrick bamford
23           Raphinha           raphinha
24         Robin Koch         robin koch
25            Rodrigo            rodrigo
26      Stuart Dallas      stuart dallas
27      Tyler Roberts      tyler roberts

============================================================
  Leicester City  —  SF sin salario:

                      player  minutesPlayed
0             Sidnei Tavares             85
1  Thakgalo Khanya Leshabela              9

  CG plantilla completa:

               player        player_norm
0         Ayoze Pérez        ayoze perez
1      Caglar Söyüncü     caglar soyuncu
2        Cengiz Ünder       cengiz under
3     Christian Fuchs    christian fuchs
4      Daniel Amartey     daniel amartey
5          Danny Ward         danny ward
6        Demarai Gray       demarai gray
7        Dennis Praet       dennis praet
8     Eldin Jakupovic    eldin jakupovic
9     Hamza Choudhury    hamza choudhury
10      Harvey Barnes      harvey barnes
11      Islam Slimani      islam slimani
12       James Justin       james justin
13     James Maddison     james maddison
14        Jamie Vardy        jamie vardy
15        Jonny Evans        jonny evans
16  Kasper Schmeichel  kasper schmeichel
17  Kelechi Iheanacho  kelechi iheanacho
18        Luke Thomas        luke thomas
19    Marc Albrighton    marc albrighton
20     Nampalys Mendy     nampalys mendy
21    Ricardo Pereira    ricardo pereira
22   Timothy Castagne   timothy castagne
23         Wes Morgan         wes morgan
24      Wesley Fofana      wesley fofana
25      Wilfred Ndidi      wilfred ndidi
26    Youri Tielemans    youri tielemans

============================================================
  Manchester City  —  SF sin salario:

       player  minutesPlayed
0  Liam Delap             39

  CG plantilla completa:

                   player            player_norm
0         Aymeric Laporte        aymeric laporte
1          Benjamin Mendy         benjamin mendy
2          Bernardo Silva         bernardo silva
3                 Ederson                ederson
4             Eric García            eric garcia
5             Fernandinho            fernandinho
6           Ferran Torres          ferran torres
7           Gabriel Jesus          gabriel jesus
8          Ilkay Gündogan         ilkay gundogan
9            João Cancelo           joao cancelo
10            John Stones            john stones
11        Kevin De Bruyne        kevin de bruyne
12            Kyle Walker            kyle walker
13             Nathan Aké             nathan ake
14    Oleksandr Zinchenko    oleksandr zinchenko
15             Phil Foden             phil foden
16       Philippe Sandler       philippe sandler
17        Raheem Sterling        raheem sterling
18           Riyad Mahrez           riyad mahrez
19                  Rodri                  rodri
20             Rúben Dias             ruben dias
21           Scott Carson           scott carson
22          Sergio Agüero          sergio aguero
23  Taylor Harwood-Bellis  taylor harwood bellis
24            Tommy Doyle            tommy doyle
25           Zack Steffen           zack steffen

============================================================
  Manchester United  —  SF sin salario:

            player  minutesPlayed
0   Anthony Elanga            156
1  Hannibal Mejbri              8
2  Shola Shoretire              9
3     William Fish              1

  CG plantilla completa:

                 player          player_norm
0     Aaron Wan-Bissaka    aaron wan bissaka
1           Alex Telles          alex telles
2           Amad Diallo          amad diallo
3       Anthony Martial      anthony martial
4         Axel Tuanzebe        axel tuanzebe
5      Brandon Williams     brandon williams
6       Bruno Fernandes      bruno fernandes
7          Daniel James         daniel james
8          David de Gea         david de gea
9        Dean Henderson       dean henderson
10    Donny van de Beek    donny van de beek
11       Edinson Cavani       edinson cavani
12          Eric Bailly          eric bailly
13    Facundo Pellistri    facundo pellistri
14                 Fred                 fred
15        Harry Maguire        harry maguire
16        Jesse Lingard        jesse lingard
17            Juan Mata            juan mata
18            Lee Grant            lee grant
19            Luke Shaw            luke shaw
20          Marcos Rojo          marcos rojo
21      Marcus Rashford      marcus rashford
22      Mason Greenwood      mason greenwood
23        Nathan Bishop        nathan bishop
24        Nemanja Matic        nemanja matic
25         Odion Ighalo         odion ighalo
26           Paul Pogba           paul pogba
27           Phil Jones           phil jones
28      Scott McTominay      scott mctominay
29        Sergio Romero        sergio romero
30  Timothy Fosu-Mensah  timothy fosu mensah
31      Victor Lindelöf      victor lindelof

============================================================
  Newcastle United  —  SF sin salario:

            player  minutesPlayed
0  Elliot Anderson              3

  CG plantilla completa:

                 player          player_norm
0         Achraf Lazaar        achraf lazaar
1   Allan Saint-Maximin  allan saint maximin
2          Andy Carroll         andy carroll
3         Callum Wilson        callum wilson
4        Christian Atsu       christian atsu
5          Ciaran Clark         ciaran clark
6           Dan Langley          dan langley
7        DeAndre Yedlin       deandre yedlin
8          Dwight Gayle         dwight gayle
9           Emil Krafth          emil krafth
10         Fabian Schär         fabian schar
11   Federico Fernández   federico fernandez
12         Henri Saivet         henri saivet
13         Isaac Hayden         isaac hayden
14         Jacob Murphy         jacob murphy
15     Jamaal Lascelles     jamaal lascelles
16          Jamal Lewis          jamal lewis
17     Javier Manquillo     javier manquillo
18        Jeff Hendrick        jeff hendrick
19          Joe Willock          joe willock
20            Joelinton            joelinton
21        Jonjo Shelvey        jonjo shelvey
22          Karl Darlow          karl darlow
23       Mark Gillespie       mark gillespie
24      Martin Dubravka      martin dubravka
25         Matt Ritchie         matt ritchie
26    Matthew Longstaff    matthew longstaff
27       Miguel Almirón       miguel almiron
28         Paul Dummett         paul dummett
29       Rolando Aarons       rolando aarons
30          Ryan Fraser          ryan fraser
31       Sean Longstaff       sean longstaff

============================================================
  Sheffield United  —  SF sin salario:

              player  minutesPlayed
0  Antwoine Hackford             10
1    Daniel Jebbison            284
2        Femi Seriki              1
3      Iliman Ndiaye             11

  CG plantilla completa:

              player       player_norm
0     Aaron Ramsdale    aaron ramsdale
1         Ben Osborn        ben osborn
2        Billy Sharp       billy sharp
3       Chris Basham      chris basham
4   David McGoldrick  david mcgoldrick
5       Enda Stevens      enda stevens
6       Ethan Ampadu      ethan ampadu
7     George Baldock    george baldock
8   George Broadbent  george broadbent
9     Jack O'Connell    jack o connell
10     Jack Robinson     jack robinson
11      Jack Rodwell      jack rodwell
12      Jayden Bogle      jayden bogle
13         John Egan         john egan
14        John Fleck        john fleck
15    John Lundstram    john lundstram
16        Kean Bryan        kean bryan
17      Kyron Gordon      kyron gordon
18       Lys Mousset       lys mousset
19       Lys Mousset       lys mousset
20          Max Lowe          max lowe
21   Michael Verrips   michael verrips
22      Oliver Burke      oliver burke
23   Oliver McBurnie   oliver mcburnie
24    Oliver Norwood    oliver norwood
25     Phil Jagielka     phil jagielka
26    Rhian Brewster    rhian brewster
27      Sander Berge      sander berge
28       Simon Moore       simon moore
29   Wes Foderingham   wes foderingham
30         Zak Brunt         zak brunt

============================================================
  Southampton  —  SF sin salario:

                player  minutesPlayed
0  Alexandre Jankewitz             11
1     Allan Tchaptchet             12
2          Caleb Watts             42
3         Kayne Ramsay             90

  CG plantilla completa:

                player         player_norm
0        Alex McCarthy       alex mccarthy
1            Che Adams           che adams
2        Dan N'Lundulu       dan n lundulu
3           Danny Ings          danny ings
4       Fraser Forster      fraser forster
5          Harry Lewis         harry lewis
6      Ibrahima Diallo     ibrahima diallo
7        Jack Stephens       jack stephens
8          Jake Vokins         jake vokins
9    James Ward-Prowse   james ward prowse
10        Jan Bednarek        jan bednarek
11  Jannik Vestergaard  jannik vestergaard
12  Kyle Walker-Peters  kyle walker peters
13     Michael Obafemi     michael obafemi
14     Mohammed Salisu     mohammed salisu
15      Moussa Djenepo      moussa djenepo
16      Nathan Redmond      nathan redmond
17        Nathan Tella        nathan tella
18         Oriol Romeu         oriol romeu
19       Ryan Bertrand       ryan bertrand
20         Sam McQueen         sam mcqueen
21          Shane Long          shane long
22    Stuart Armstrong    stuart armstrong
23     Takumi Minamino     takumi minamino
24        Theo Walcott        theo walcott
25      Will Smallbone      will smallbone
26          Yan Valery          yan valery

============================================================
  Tottenham Hotspur  —  SF sin salario:

          player  minutesPlayed
0  Dane Scarlett              1

  CG plantilla completa:

                   player            player_norm
0          Alfie Whiteman         alfie whiteman
1              Ben Davies             ben davies
2         Carlos Vinícius        carlos vinicius
3              Danny Rose             danny rose
4        Davinson Sánchez       davinson sanchez
5               Dele Alli              dele alli
6               Eric Dier              eric dier
7             Erik Lamela            erik lamela
8             Gareth Bale            gareth bale
9        Gedson Fernandes       gedson fernandes
10       Giovani Lo Celso       giovani lo celso
11             Harry Kane             harry kane
12            Harry Winks            harry winks
13          Heung-min Son          heung min son
14            Hugo Lloris            hugo lloris
15            Jack Clarke            jack clarke
16        Japhet Tanganga        japhet tanganga
17               Joe Hart               joe hart
18              Joe Rodon              joe rodon
19            Lucas Moura            lucas moura
20           Matt Doherty           matt doherty
21         Moussa Sissoko         moussa sissoko
22        Paulo Gazzaniga        paulo gazzaniga
23  Pierre-Emile Höjbjerg  pierre emile hojbjerg
24           Serge Aurier           serge aurier
25        Sergio Reguilón        sergio reguilon
26        Steven Bergwijn        steven bergwijn
27        Tanguy Ndombélé        tanguy ndombele
28      Toby Alderweireld      toby alderweireld

============================================================
  West Ham United  —  SF sin salario:

            player  minutesPlayed
0  Felipe Anderson              2

  CG plantilla completa:

               player        player_norm
0     Aaron Cresswell    aaron cresswell
1   Andrii Yarmolenko  andrii yarmolenko
2      Angelo Ogbonna     angelo ogbonna
3      Arthur Masuaku     arthur masuaku
4         Ben Johnson        ben johnson
5        Craig Dawson       craig dawson
6     Darren Randolph    darren randolph
7        David Martin       david martin
8         Declan Rice        declan rice
9     Fabián Balbuena    fabian balbuena
10     Frederik Alves     frederik alves
11          Issa Diop          issa diop
12       Jarrod Bowen       jarrod bowen
13      Jesse Lingard      jesse lingard
14   Lukasz Fabianski   lukasz fabianski
15     Manuel Lanzini     manuel lanzini
16         Mark Noble         mark noble
17    Michail Antonio    michail antonio
18      Pablo Fornals      pablo fornals
19   Robert Snodgrass   robert snodgrass
20    Ryan Fredericks    ryan fredericks
21      Saïd Benrahma      said benrahma
22   Sébastien Haller   sebastien haller
23       Tomas Soucek       tomas soucek
24    Vladimir Coufal    vladimir coufal

============================================================
  Wolverhampton  —  SF sin salario:

            player  minutesPlayed
0  Patrick Cutrone             23
1    Rúben Vinagre            172
2    Theo Corbeanu              8

  CG plantilla completa:

                player         player_norm
0         Adama Traoré        adama traore
1          Conor Coady         conor coady
2       Daniel Podence      daniel podence
3          Fábio Silva         fabio silva
4        João Moutinho       joao moutinho
5           John Ruddy          john ruddy
6           Jonny Otto          jonny otto
7       Ki-Jana Hoever      ki jana hoever
8   Leander Dendoncker  leander dendoncker
9        Luke Matheson       luke matheson
10              Marçal              marcal
11          Max Kilman          max kilman
12  Morgan Gibbs-White  morgan gibbs white
13       Nélson Semedo       nelson semedo
14          Oskar Buur          oskar buur
15       Owen Otasowie       owen otasowie
16          Pedro Neto          pedro neto
17        Raúl Jiménez        raul jimenez
18     Rayan Aït Nouri     rayan ait nouri
19    Roderick Miranda    roderick miranda
20        Romain Saïss        romain saiss
21         Rúben Neves         ruben neves
22        Rui Patrício        rui patricio
23             Vitinha             vitinha
24        Willian José        willian jose
25          Willy Boly          willy boly

In [27]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('kepa arrizabalaga', 'chelsea'): ('kepa', 'chelsea'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [28]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: kepa arrizabalaga (chelsea) → kepa (chelsea)

Tras matches manuales: 495/527 (93.9%)

In [29]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [30]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_england_2021.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_england_2021.csv
   Jugadores totales:  527
   Con salario:        495
   Sin salario (NaN):  32
   Columnas:           121