# 03 · Join Sofascore + Capology — England Premier League 25/26 (snapshot 20260428)

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2025/26 de la Premier League inglesa**.

⚠️ **Nota sobre el snapshot:** la temporada 25/26 está aún en curso. Se trabaja con
una foto fija de Sofascore (`df_england_2526_snapshot_20260428.csv`). Este notebook
deberá reejecutarse con los datos definitivos cuando finalice la liga, generando
entonces el master sin sufijo de fecha (`master_england_2526.csv`).

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_england_2526_snapshot_20260428.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_england_2526.csv').copy()

print(f'Sofascore (snapshot):  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:              {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore (snapshot):  525 jugadores | 117 columnas
Capology:              706 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   brighton hove albion
   leeds united
   newcastle united
   tottenham hotspur
   west ham united

En Capology pero no en Sofascore:
   brighton
   leeds
   newcastle
   tottenham
   west ham

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brighton':'brighton hove albion',
            'leeds':'leeds united',
            'newcastle':'newcastle united',
            'tottenham':'tottenham hotspur',
            'west ham':'west ham united'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 471/525 (89.7%)
Sin emparejar: 54

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          7
Revisión media    (0.75 ≤ score < 0.90):   10
Revisión estricta (0.50 ≤ score < 0.75):   25
Revisión muy est. (score < 0.50):           12

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf               team           cg_match  score
33         Romain Esse     Crystal Palace        romain esse  1.000
24          Jota Silva  Nottingham Forest         jota silva  1.000
20  David Möller Wolfe      Wolverhampton  david mller wolfe  0.971
29  Christian Norgaard            Arsenal  christian nrgaard  0.971
2      Martin Odegaard            Arsenal     martin degaard  0.966
7          Yéremy Pino     Crystal Palace        yeremi pino  0.909
32         Joshua King             Fulham          josh king  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf               team              cg_match  score
14     Yehor Yarmoliuk          Brentford       yegor yarmolyuk  0.867
11      Andy Robertson          Liverpool      andrew robertson  0.867
5       Đorđe Petrović        Bournemouth      djordje petrovic  0.857
9   Idrissa Gana Gueye            Everton         idrissa gueye  0.839
16             Savinho    Manchester City                 savio  0.833
19       Jamie Gittens            Chelsea   jamie bynoe gittens  0.812
17     Florentino Luís            Burnley            florentino  0.800
37       Divine Mukasa    Manchester City          divin mubama  0.800
1        Stefan Ortega  Nottingham Forest  stefan ortega moreno  0.788
8      Pape Matar Sarr  Tottenham Hotspur             pape sarr  0.750

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['divine mukasa'

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 9 | Excluidos: 1

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf                    team           cg_match  score
12      Hannibal Mejbri                 Burnley           hannibal  0.696
0            Tom Edozie           Wolverhampton        tommy doyle  0.667
35  Hamed Junior Traorè             Bournemouth  eli junior kroupi  0.611
50       Tyler Fletcher       Manchester United   tyler fredricson  0.600
22      Guido Rodríguez         West Ham United       gideon kodua  0.593
30      George Hemmings             Aston Villa       tyrone mings  0.593
41         Pablo Felipe         West Ham United              pablo  0.588
31       Hwang Hee-chan           Wolverhampton     hee chan hwang  0.571
46           Igor Júlio  Brighton & Hove Albion               igor  0.571
47      Callum Marshall         West Ham United      callum wilson  0.571
21                 Jair       Nottingham Forest         jair cunha  0.571
43         Kaden Rodney          Crystal Palace     dean henderson  0.538
45      Patrick Roberts              Sunderland        robin roefs  0.538
51       James Rowswell       Tottenham Hotspur       jamie donley  0.538
26       Callum Olusesi       Tottenham Hotspur   dejan kulusevski  0.533
48          John Victor       Nottingham Forest               john  0.533
6                 André           Wolverhampton     andre trindade  0.526
28           Shea Lacey       Manchester United      senne lammens  0.522
3          Jenson Seelt              Sunderland        enzo le fee  0.522
34        Jack Fletcher       Manchester United     jack moorhouse  0.519
52      Nehemiah Oriola  Brighton & Hove Albion       matt o riley  0.519
15         Oliver Sonne                 Burnley       owen dodgson  0.500
38       Luis Guilherme         West Ham United     mads hermansen  0.500
36      Bendito Mantato       Manchester United      kobbie mainoo  0.500
10  Oleksandr Zinchenko       Nottingham Forest  nikola milenkovic  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['hannibal mejbri',
                    'pablo felipe',
                    'hwang hee chan',
                    'igor julio',
                    'jair',
                    'john victor',
                    'andre'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 7

### 7.4 Revisión muy estricta (score < 0.50)

Candidatos con muy baja similitud. Por defecto ninguno se acepta.
Añadir a `ACCEPT_VERY_LOW_FUZZY` los que se confirmen manualmente.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf                    team             cg_match  score
4        Lucas Paquetá         West Ham United     lukasz fabianski  0.483
18     Mohamadou Kanté         West Ham United       mads hermansen  0.483
42    Bradley Burrowes             Aston Villa        morgan rogers  0.483
40        Harry Howell  Brighton & Hove Albion        danny welbeck  0.480
25     Jamaldeen Jimoh             Aston Villa  samuel iling junior  0.471
44    Jamaal Lascelles        Newcastle United       aaron ramsdale  0.467
39  Joel Drakes-Thomas          Crystal Palace    jesurun rak sakyi  0.457
53          Joe Knight  Brighton & Hove Albion         joel veltman  0.455
49        Nayef Aguerd         West Ham United          ezra mayers  0.435
13      Jun'ai Byfield       Tottenham Hotspur       lucas bergvall  0.429
27         Andy Irving         West Ham United    jean clair todibo  0.429
23     Odsonne Édouard          Crystal Palace       dean henderson  0.414

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 492/525 (93.7%)
Sin salario:     33

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 33

,player,team,minutesPlayed,appearances,goals,assists
0,George Hemmings,Aston Villa,25,2,0,0
1,Bradley Burrowes,Aston Villa,16,1,0,0
2,Jamaldeen Jimoh,Aston Villa,8,1,0,0
3,Hamed Junior Traorè,Bournemouth,16,1,0,1
4,Harry Howell,Brighton & Hove Albion,93,3,0,0
5,Nehemiah Oriola,Brighton & Hove Albion,1,1,0,0
6,Joe Knight,Brighton & Hove Albion,1,1,0,0
7,Oliver Sonne,Burnley,165,7,1,0
8,Romain Esse,Crystal Palace,54,4,0,0
9,Joel Drakes-Thomas,Crystal Palace,25,2,0,0
10,Kaden Rodney,Crystal Palace,9,1,0,0
11,Odsonne Édouard,Crystal Palace,8,1,0,0
12,Divine Mukasa,Manchester City,25,2,0,0
13,Jack Fletcher,Manchester United,107,3,0,0
14,Shea Lacey,Manchester United,23,2,0,0
15,Bendito Mantato,Manchester United,15,1,0,0
16,Tyler Fletcher,Manchester United,1,1,0,0
17,Jamaal Lascelles,Newcastle United,25,2,0,0
18,Oleksandr Zinchenko,Nottingham Forest,353,5,0,0
19,Jota Silva,Nottingham Forest,11,1,0,0
20,Jenson Seelt,Sunderland,134,2,0,0
21,Patrick Roberts,Sunderland,27,1,0,0
22,Callum Olusesi,Tottenham Hotspur,14,1,0,0
23,Jun'ai Byfield,Tottenham Hotspur,10,1,0,0
24,James Rowswell,Tottenham Hotspur,1,1,0,0
25,Lucas Paquetá,West Ham United,1521,18,4,1
26,Nayef Aguerd,West Ham United,180,2,0,0
27,Guido Rodríguez,West Ham United,177,6,0,0
28,Andy Irving,West Ham United,163,7,0,0
29,Luis Guilherme,West Ham United,121,5,0,0
30,Mohamadou Kanté,West Ham United,82,9,0,0
31,Callum Marshall,West Ham United,58,2,0,0
32,Tom Edozie,Wolverhampton,25,2,1,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Aston Villa  —  SF sin salario:

             player  minutesPlayed
0  Bradley Burrowes             16
1   George Hemmings             25
2   Jamaldeen Jimoh              8

  CG plantilla completa:

                 player          player_norm
0               Alysson              alysson
1          Amadou Onana         amadou onana
2         Andrés García        andres garcia
3           Ben Broggio          ben broggio
4       Boubacar Kamara      boubacar kamara
5         Donyell Malen        donyell malen
6          Douglas Luiz         douglas luiz
7      Emiliano Buendía     emiliano buendia
8     Emiliano Martínez    emiliano martinez
9        Evann Guessand       evann guessand
10           Ezri Konsa           ezri konsa
11       Harvey Elliott       harvey elliott
12          Ian Maatsen          ian maatsen
13         Jadon Sancho         jadon sancho
14            Joe Gauci            joe gauci
15          John McGinn          john mcginn
16          Josh Feeney          josh feeney
17          Kane Taylor          kane taylor
18           Kerr Smith           kerr smith
19    Kosta Nedeljkovic    kosta nedeljkovic
20       Lamare Bogarde       lamare bogarde
21          Leon Bailey          leon bailey
22         Lewis Dobbin         lewis dobbin
23           Lino Sousa           lino sousa
24          Louie Barry          louie barry
25          Lucas Digne          lucas digne
26          Marco Bizot          marco bizot
27           Matty Cash           matty cash
28        Morgan Rogers        morgan rogers
29        Ollie Watkins        ollie watkins
30           Pau Torres           pau torres
31         Ross Barkley         ross barkley
32  Samuel Iling-Junior  samuel iling junior
33         Sil Swinkels         sil swinkels
34        Tammy Abraham        tammy abraham
35       Tommi O'Reilly       tommi o reilly
36         Tyrone Mings         tyrone mings
37      Victor Lindelöf      victor lindelof
38      Youri Tielemans      youri tielemans
39    Zepiqueno Redmond    zepiqueno redmond

============================================================
  Bournemouth  —  SF sin salario:

                player  minutesPlayed
0  Hamed Junior Traorè             16

  CG plantilla completa:

                  player           player_norm
0             Adam Smith            adam smith
1        Adrien Truffert       adrien truffert
2           Álex Jiménez          alex jimenez
3             Alex Scott            alex scott
4              Alex Tóth             alex toth
5             Amine Adli            amine adli
6         Bafodé Diakité        bafode diakite
7        Ben Gannon-Doak       ben gannon doak
8         Ben Winterburn        ben winterburn
9        Christos Mandas       christos mandas
10       Daniel Jebbison       daniel jebbison
11          David Brooks          david brooks
12      Djordje Petrovic      djordje petrovic
13     Eli Junior Kroupi     eli junior kroupi
14             Enes Ünal             enes unal
15             Evanilson             evanilson
16        Fraser Forster        fraser forster
17            James Hill            james hill
18         Julián Araujo         julian araujo
19           Julio Soler           julio soler
20       Justin Kluivert       justin kluivert
21            Lewis Cook            lewis cook
22       Luis Sinisterra       luis sinisterra
23         Marcos Senesi         marcos senesi
24      Marcus Tavernier      marcus tavernier
25       Matai Akinmboni       matai akinmboni
26            Max Aarons            max aarons
27                 Rayan                 rayan
28         Romain Faivre         romain faivre
29         Ryan Christie         ryan christie
30           Tyler Adams           tyler adams
31  Veljko Milosavljevic  veljko milosavljevic
32           Will Dennis           will dennis

============================================================
  Brighton & Hove Albion  —  SF sin salario:

            player  minutesPlayed
0     Harry Howell             93
1       Joe Knight              1
2  Nehemiah Oriola              1

  CG plantilla completa:

                   player            player_norm
0            Adam Webster           adam webster
1   Amario Cozier-Duberry  amario cozier duberry
2         Bart Verbruggen        bart verbruggen
3            Brajan Gruda           brajan gruda
4          Carl Rushworth         carl rushworth
5           Carlos Baleba          carlos baleba
6          Caylan Vickers         caylan vickers
7   Charalampos Kostoulas  charalampos kostoulas
8           Danny Welbeck          danny welbeck
9           Diego Coppola          diego coppola
10            Diego Gómez            diego gomez
11           Eiran Cashin           eiran cashin
12          Evan Ferguson          evan ferguson
13     Facundo Buonanotte     facundo buonanotte
14         Ferdi Kadıoğlu          ferdi kadoglu
15       Georginio Rutter       georginio rutter
16                   Igor                   igor
17       Jack Hinshelwood       jack hinshelwood
18           Jacob Slater           jacob slater
19           James Beadle           james beadle
20           James Milner           james milner
21     Jan Paul van Hecke     jan paul van hecke
22           Jason Steele           jason steele
23           Joël Veltman           joel veltman
24           Kamari Doyle           kamari doyle
25           Kaoru Mitoma           kaoru mitoma
26             Lewis Dunk             lewis dunk
27        Malick Yalcouyé        malick yalcouye
28          Mark O'Mahony          mark o mahony
29           Mats Wieffer           mats wieffer
30           Matt O'Riley           matt o riley
31        Maxim De Cuyper        maxim de cuyper
32       Olivier Boscagli       olivier boscagli
33            Pascal Groß             pascal gro
34            Solly March            solly march
35        Stefanos Tzimas        stefanos tzimas
36             Tom McGill             tom mcgill
37             Tom Watson             tom watson
38         Yankuba Minteh         yankuba minteh
39            Yasin Ayari            yasin ayari

============================================================
  Burnley  —  SF sin salario:

         player  minutesPlayed
0  Oliver Sonne            165

  CG plantilla completa:

                 player          player_norm
0          Aaron Ramsey         aaron ramsey
1         Armando Broja        armando broja
2         Ashley Barnes        ashley barnes
3         Axel Tuanzebe        axel tuanzebe
4      Bashir Humphreys     bashir humphreys
5         Benson Manuel        benson manuel
6        Connor Roberts       connor roberts
7            Florentino           florentino
8              Hannibal             hannibal
9         Hjalmar Ekdal        hjalmar ekdal
10   Jacob Bruun Larsen   jacob bruun larsen
11       Jaidon Anthony       jaidon anthony
12    James Ward-Prowse    james ward prowse
13         Jaydon Banel         jaydon banel
14          Joe Bauress          joe bauress
15          Joe Worrall          joe worrall
16         Jordan Beyer         jordan beyer
17          Josh Cullen          josh cullen
18         Josh Laurent         josh laurent
19          Kyle Walker          kyle walker
20     Lesley Ugochukwu     lesley ugochukwu
21            Logan Pye            logan pye
22        Loum Tchaouna        loum tchaouna
23          Lucas Pires          lucas pires
24          Lyle Foster          lyle foster
25       Marcus Edwards       marcus edwards
26      Martin Dubravka      martin dubravka
27             Max Weiß              max wei
28        Maxime Estève        maxime esteve
29       Michael Mellon       michael mellon
30          Mike Tresor          mike tresor
31         Owen Dodgson         owen dodgson
32  Quilindschy Hartman  quilindschy hartman
33           Sam Waller           sam waller
34      Tommy McDermott      tommy mcdermott
35        Václav Hladký        vaclav hladky
36         Zeki Amdouni         zeki amdouni
37        Zian Flemming        zian flemming

============================================================
  Crystal Palace  —  SF sin salario:

               player  minutesPlayed
0  Joel Drakes-Thomas             25
1        Kaden Rodney              9
2     Odsonne Édouard              8
3         Romain Esse             54

  CG plantilla completa:

                  player           player_norm
0           Adam Wharton          adam wharton
1             Borna Sosa            borna sosa
2        Brennan Johnson       brennan johnson
3           Caleb Kporha          caleb kporha
4             Chadi Riad            chadi riad
5        Cheick Doucouré       cheick doucoure
6         Chris Richards        chris richards
7       Christantus Uche      christantus uche
8          Daichi Kamada         daichi kamada
9           Daniel Muñoz          daniel munoz
10           Danny Imray           danny imray
11            David Ozoh            david ozoh
12        Dean Henderson        dean henderson
13         Eddie Nketiah         eddie nketiah
14        Evann Guessand        evann guessand
15          Ismaïla Sarr          ismaila sarr
16         Jaydee Canvot         jaydee canvot
17  Jean-Philippe Mateta  jean philippe mateta
18       Jefferson Lerma       jefferson lerma
19          Jemiah Umolu          jemiah umolu
20     Jesurun Rak-Sakyi     jesurun rak sakyi
21         Joe Whitworth         joe whitworth
22  Jørgen Strand Larsen   jrgen strand larsen
23        Justin Devenny        justin devenny
24        Matheus França        matheus franca
25       Maxence Lacroix       maxence lacroix
26       Nathaniel Clyne       nathaniel clyne
27          Owen Goodman          owen goodman
28         Remi Matthews         remi matthews
29          Rio Cardines          rio cardines
30           Romain Esse           romain esse
31        Tayo Adaramola        tayo adaramola
32       Tyrick Mitchell       tyrick mitchell
33        Walter Benítez        walter benitez
34           Will Hughes           will hughes
35           Yeremi Pino           yeremi pino

============================================================
  Manchester City  —  SF sin salario:

          player  minutesPlayed
0  Divine Mukasa             25

  CG plantilla completa:

                  player           player_norm
0     Abdukodir Khusanov    abdukodir khusanov
1        Antoine Semenyo       antoine semenyo
2         Bernardo Silva        bernardo silva
3      Claudio Echeverri     claudio echeverri
4           Divin Mubama          divin mubama
5         Erling Haaland        erling haaland
6           Finley Burns          finley burns
7   Gianluigi Donnarumma  gianluigi donnarumma
8            Issa Kabore           issa kabore
9          Jack Grealish         jack grealish
10  Jahmai Simpson-Pusey  jahmai simpson pusey
11        James Trafford        james trafford
12           Jérémy Doku           jeremy doku
13            Joel Ndala            joel ndala
14           John Stones           john stones
15   Josh Wilson-Esbrand   josh wilson esbrand
16        Josko Gvardiol        josko gvardiol
17       Kalvin Phillips       kalvin phillips
18         Lakyle Samuel         lakyle samuel
19      Mahamadou Susoho      mahamadou susoho
20            Marc Guéhi            marc guehi
21     Marcus Bettinelli     marcus bettinelli
22         Mateo Kovacic         mateo kovacic
23         Matheus Nunes         matheus nunes
24           Max Alleyne           max alleyne
25            Nathan Aké            nathan ake
26         Nico González         nico gonzalez
27         Nico O'Reilly         nico o reilly
28         Omar Marmoush         omar marmoush
29            Phil Foden            phil foden
30       Rayan Aït-Nouri       rayan ait nouri
31          Rayan Cherki          rayan cherki
32            Rico Lewis            rico lewis
33                 Rodri                 rodri
34            Rúben Dias            ruben dias
35                 Sávio                 savio
36          Sverre Nypan          sverre nypan
37     Tijjani Reijnders     tijjani reijnders
38          Will Dickson          will dickson

============================================================
  Manchester United  —  SF sin salario:

            player  minutesPlayed
0  Bendito Mantato             15
1    Jack Fletcher            107
2       Shea Lacey             23
3   Tyler Fletcher              1

  CG plantilla completa:

               player        player_norm
0      Altay Bayındır       altay bayndr
1         Amad Diallo        amad diallo
2         André Onana        andre onana
3        Ayden Heaven       ayden heaven
4      Benjamin Sesko     benjamin sesko
5     Bruno Fernandes    bruno fernandes
6        Bryan Mbeumo       bryan mbeumo
7            Casemiro           casemiro
8           Chido Obi          chido obi
9            Dan Gore           dan gore
10         Diego León         diego leon
11        Diogo Dalot        diogo dalot
12      Elyh Harrison      elyh harrison
13        Ethan Ennis        ethan ennis
14     Ethan Wheatley     ethan wheatley
15     Ethan Williams     ethan williams
16    Habeeb Ogunneye    habeeb ogunneye
17        Harry Amass        harry amass
18      Harry Maguire      harry maguire
19     Jack Moorhouse     jack moorhouse
20       Jadon Sancho       jadon sancho
21         Joe Hugill         joe hugill
22     Joshua Zirkzee     joshua zirkzee
23      Kobbie Mainoo      kobbie mainoo
24          Leny Yoro          leny yoro
25  Lisandro Martínez  lisandro martinez
26          Luke Shaw          luke shaw
27      Manuel Ugarte      manuel ugarte
28    Marcus Rashford    marcus rashford
29        Mason Mount        mason mount
30      Matheus Cunha      matheus cunha
31   Matthijs de Ligt   matthijs de ligt
32  Noussair Mazraoui  noussair mazraoui
33      Patrick Dorgu      patrick dorgu
34        Radek Vítek        radek vitek
35      Senne Lammens      senne lammens
36     Sonny Aljofree     sonny aljofree
37       Toby Collyer       toby collyer
38         Tom Heaton         tom heaton
39   Tyler Fredricson   tyler fredricson
40     Tyrell Malacia     tyrell malacia

============================================================
  Newcastle United  —  SF sin salario:

             player  minutesPlayed
0  Jamaal Lascelles             25

  CG plantilla completa:

             player      player_norm
0    Aaron Ramsdale   aaron ramsdale
1       Alex Murphy      alex murphy
2    Anthony Elanga   anthony elanga
3    Anthony Gordon   anthony gordon
4   Bruno Guimarães  bruno guimaraes
5          Dan Burn         dan burn
6       Emil Krafth      emil krafth
7      Fabian Schär     fabian schar
8    Harrison Ashby   harrison ashby
9     Harvey Barnes    harvey barnes
10     Jacob Murphy     jacob murphy
11     Jacob Ramsey     jacob ramsey
12        Joe White        joe white
13      Joe Willock      joe willock
14        Joelinton        joelinton
15       John Ruddy       john ruddy
16  Kieran Trippier  kieran trippier
17       Lewis Hall       lewis hall
18      Lewis Miley      lewis miley
19     Malick Thiaw     malick thiaw
20   Mark Gillespie   mark gillespie
21     Matt Targett     matt targett
22        Nick Pope        nick pope
23   Nick Woltemade   nick woltemade
24    Sandro Tonali    sandro tonali
25      Sven Botman      sven botman
26  Tino Livramento  tino livramento
27    William Osula    william osula
28      Yoane Wissa      yoane wissa

============================================================
  Nottingham Forest  —  SF sin salario:

                player  minutesPlayed
0           Jota Silva             11
1  Oleksandr Zinchenko            353

  CG plantilla completa:

                   player            player_norm
0              Angus Gunn             angus gunn
1       Arnaud Kalimuendo      arnaud kalimuendo
2      Callum Hudson-Odoi     callum hudson odoi
3              Chris Wood             chris wood
4                Cuiabano               cuiabano
5               Dan Ndoye              dan ndoye
6      Detlef Esapa Osong     detlef esapa osong
7            Dilane Bakwa           dilane bakwa
8        Donnell McNeilly       donnell mcneilly
9            Douglas Luiz           douglas luiz
10        Elliot Anderson        elliot anderson
11  Eric da Silva Moreira  eric da silva moreira
12        Ibrahim Sangaré        ibrahim sangare
13             Igor Jesus             igor jesus
14             Jair Cunha             jair cunha
15           James McAtee           james mcatee
16            Joe Gardner            joe gardner
17                   John                   john
18            Josh Powell            josh powell
19             Jota Silva             jota silva
20            Kyle McAdam            kyle mcadam
21          Lorenzo Lucca          lorenzo lucca
22              Luca Netz              luca netz
23              Matz Sels              matz sels
24                 Morato                 morato
25     Morgan Gibbs-White     morgan gibbs white
26                Murillo                murillo
27          Neco Williams          neco williams
28      Nicolás Domínguez      nicolas dominguez
29          Nicolò Savona          nicolo savona
30      Nikola Milenković      nikola milenkovic
31               Ola Aina               ola aina
32          Omar Richards          omar richards
33       Omari Hutchinson       omari hutchinson
34             Ryan Yates             ryan yates
35   Stefan Ortega Moreno   stefan ortega moreno
36          Taiwo Awoniyi          taiwo awoniyi
37           Tyler Bindon           tyler bindon
38             Willy Boly             willy boly
39            Zach Abbott            zach abbott

============================================================
  Sunderland  —  SF sin salario:

            player  minutesPlayed
0     Jenson Seelt            134
1  Patrick Roberts             27

  CG plantilla completa:

                  player           player_norm
0           Abdoullah Ba          abdoullah ba
1        Ahmed Abdullahi       ahmed abdullahi
2              Aji Alese             aji alese
3            Alan Browne           alan browne
4      Anthony Patterson     anthony patterson
5         Arthur Masuaku        arthur masuaku
6        Bertrand Traoré       bertrand traore
7          Brian Brobbey         brian brobbey
8        Chemsdine Talbi       chemsdine talbi
9             Chris Rigg            chris rigg
10              Dan Neil              dan neil
11        Daniel Ballard        daniel ballard
12         Dennis Cirkin         dennis cirkin
13       Eliezer Mayenda       eliezer mayenda
14           Enzo Le Fée           enzo le fee
15          Granit Xhaka          granit xhaka
16          Habib Diarra          habib diarra
17        Harrison Jones        harrison jones
18            Ian Poveda            ian poveda
19         Jocelin Ta Bi         jocelin ta bi
20       Leo Fuhr Hjelde       leo fuhr hjelde
21           Luke O'Nien           luke o nien
22  Lutsharel Geertruida  lutsharel geertruida
23         Matthew Young         matthew young
24        Melker Ellborg        melker ellborg
25         Milan Aleksic         milan aleksic
26         Nazarii Rusyn         nazarii rusyn
27         Niall Huggins         niall huggins
28         Nilson Angulo         nilson angulo
29           Noah Sadiki           noah sadiki
30         Nordi Mukiele         nordi mukiele
31         Omar Alderete         omar alderete
32      Reinildo Mandava      reinildo mandava
33           Robin Roefs           robin roefs
34        Romaine Mundle        romaine mundle
35         Simon Adingra         simon adingra
36           Simon Moore           simon moore
37             Trai Hume             trai hume
38  Trey Samuel-Ogunsuyi  trey samuel ogunsuyi
39         Wilson Isidor         wilson isidor

============================================================
  Tottenham Hotspur  —  SF sin salario:

           player  minutesPlayed
0  Callum Olusesi             14
1  James Rowswell              1
2  Jun'ai Byfield             10

  CG plantilla completa:

               player        player_norm
0        Alfie Devine       alfie devine
1    Alfie Dorrington   alfie dorrington
2      Antonín Kinský     antonin kinsky
3         Archie Gray        archie gray
4     Ashley Phillips    ashley phillips
5          Ben Davies         ben davies
6      Brandon Austin     brandon austin
7     Conor Gallagher    conor gallagher
8     Cristian Romero    cristian romero
9        Damola Ajayi       damola ajayi
10      Dane Scarlett      dane scarlett
11   Dejan Kulusevski   dejan kulusevski
12     Destiny Udogie     destiny udogie
13        Djed Spence        djed spence
14    Dominic Solanke    dominic solanke
15      George Abbott      george abbott
16  Guglielmo Vicario  guglielmo vicario
17     James Maddison     james maddison
18       Jamie Donley       jamie donley
19      João Palhinha      joao palhinha
20        Kevin Danso        kevin danso
21         Kota Takai         kota takai
22      Kyrell Wilson      kyrell wilson
23     Lucas Bergvall     lucas bergvall
24         Mathys Tel         mathys tel
25   Micky van de Ven   micky van de ven
26        Mikey Moore        mikey moore
27     Min-hyeok Yang     min hyeok yang
28     Mohammed Kudus     mohammed kudus
29        Oliver Irow        oliver irow
30          Pape Sarr          pape sarr
31        Pedro Porro        pedro porro
32      Radu Drăgușin      radu dragusin
33  Randal Kolo Muani  randal kolo muani
34        Richarlison        richarlison
35  Rodrigo Bentancur  rodrigo bentancur
36              Souza              souza
37        Tyrese Hall        tyrese hall
38     Will Lankshear     will lankshear
39     Wilson Odobert     wilson odobert
40        Xavi Simons        xavi simons
41    Yusuf Akhamrich    yusuf akhamrich
42      Yves Bissouma      yves bissouma

============================================================
  West Ham United  —  SF sin salario:

            player  minutesPlayed
0      Andy Irving            163
1  Callum Marshall             58
2  Guido Rodríguez            177
3    Lucas Paquetá           1521
4   Luis Guilherme            121
5  Mohamadou Kanté             82
6     Nayef Aguerd            180

  CG plantilla completa:

                     player              player_norm
0         Aaron Wan-Bissaka        aaron wan bissaka
1              Adama Traoré             adama traore
2           Alphonse Areola          alphonse areola
3               Axel Disasi              axel disasi
4             Callum Wilson            callum wilson
5     Crysencio Summerville    crysencio summerville
6             Edson Álvarez            edson alvarez
7     El Hadji Malick Diouf    el hadji malick diouf
8               Ezra Mayers              ezra mayers
9             Freddie Potts            freddie potts
10            George Earthy            george earthy
11             Gideon Kodua             gideon kodua
12        James Ward-Prowse        james ward prowse
13             Jarrod Bowen             jarrod bowen
14        Jean-Clair Todibo        jean clair todibo
15          Junior Robinson          junior robinson
16             Kaelan Casey             kaelan casey
17          Keiber Lamadrid          keiber lamadrid
18  Konstantinos Mavropanos  konstantinos mavropanos
19       Kyle Walker-Peters       kyle walker peters
20             Lewis Orford             lewis orford
21         Lukasz Fabianski         lukasz fabianski
22           Mads Hermansen           mads hermansen
23         Mateus Fernandes         mateus fernandes
24               Max Kilman               max kilman
25           Michael Forbes           michael forbes
26          Niclas Füllkrug          niclas fullkrug
27           Oliver Scarles           oliver scarles
28                    Pablo                    pablo
29       Soungoutou Magassa       soungoutou magassa
30             Tomáš Souček             tomas soucek
31     Valentín Castellanos     valentin castellanos

============================================================
  Wolverhampton  —  SF sin salario:

       player  minutesPlayed
0  Tom Edozie             25

  CG plantilla completa:

                    player             player_norm
0           Adam Armstrong          adam armstrong
1           André Trindade          andre trindade
2              Angel Gomes             angel gomes
3          Boubacar Traoré         boubacar traore
4           Daniel Bentley          daniel bentley
5       David Møller Wolfe       david mller wolfe
6         Dexter Lembikisa        dexter lembikisa
7         Emmanuel Agbadou        emmanuel agbadou
8            Enso González           enso gonzalez
9                Fer López               fer lopez
10          Hee-chan Hwang          hee chan hwang
11              Hugo Bueno              hugo bueno
12      Jackson Tchatchoua      jackson tchatchoua
13  Jean-Ricner Bellegarde  jean ricner bellegarde
14              Jhon Arias              jhon arias
15              João Gomes              joao gomes
16                 José Sá                 jose sa
17          Ki-Jana Hoever          ki jana hoever
18         Ladislav Krejci         ladislav krejci
19        Marshall Munetsi        marshall munetsi
20             Mateus Mané             mateus mane
21            Matt Doherty            matt doherty
22            Nasser Djiga            nasser djiga
23           Nathan Fraser           nathan fraser
24           Nigel Lonwijk           nigel lonwijk
25              Pedro Lima              pedro lima
26           Rodrigo Gomes           rodrigo gomes
27           Sam Johnstone           sam johnstone
28          Santiago Bueno          santiago bueno
29          Sasa Kalajdzic          sasa kalajdzic
30         Tawanda Chirewa         tawanda chirewa
31          Tolu Arokodare          tolu arokodare
32             Tommy Doyle             tommy doyle
33              Toti Gomes              toti gomes
34         Yerson Mosquera         yerson mosquera

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 492/525 (93.7%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

⚠️ Nombre con sufijo `_snapshot_20260428` para diferenciar del master definitivo
que se generará al cierre de la temporada (`master_england_2526.csv`).

In [21]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_england_2526_snapshot_20260428.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_england_2526_snapshot_20260428.csv
   Jugadores totales:  525
   Con salario:        492
   Sin salario (NaN):  33
   Columnas:           122