# 03 · Join Sofascore + Capology — England Premier League 24/25

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2024/25 de Premier League inglesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_england_2425.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_england_2425.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  562 jugadores | 116 columnas
Capology:   770 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   brighton hove albion
   leicester city
   newcastle united
   tottenham hotspur
   west ham united

En Capology pero no en Sofascore:
   brighton
   leicester
   newcastle
   tottenham
   west ham

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [7]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brighton':'brighton hove albion',
            'leicester':'leicester city',
            'newcastle':'newcastle united',
            'tottenham':'tottenham hotspur',
            'west ham':'west ham united'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [8]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 516/562 (91.8%)
Sin emparejar: 46

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [9]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          6
Revisión media    (0.75 ≤ score < 0.90):   8
Revisión estricta (0.50 ≤ score < 0.75):   18
Revisión muy est. (score < 0.50):           14

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [10]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

           player_sf             team          cg_match  score
1   Łukasz Fabiański  West Ham United  lukasz fabianski  0.968
11         Sam Morsy     Ipswich Town        samy morsy  0.947
9    Yehor Yarmolyuk        Brentford   yegor yarmolyuk  0.933
23   Mykhaylo Mudryk          Chelsea   mykhailo mudryk  0.933
36    Albert Grønbæk      Southampton    albert grnbaek  0.923
13       Joshua King           Fulham         josh king  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [11]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf               team              cg_match  score
5   Valentino Livramento   Newcastle United       tino livramento  0.857
0                Savinho    Manchester City                 savio  0.833
27     Ben Brereton Díaz        Southampton          ben brereton  0.828
14        Edward Nketiah     Crystal Palace         eddie nketiah  0.815
33           Yunus Konak          Brentford      yunus emre konak  0.815
6          Stefan Ortega    Manchester City  stefan ortega moreno  0.788
20  Edmond-Paris Maghoma          Brentford         paris maghoma  0.788
8        Pape Matar Sarr  Tottenham Hotspur             pape sarr  0.750

In [12]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 8 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [13]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
12,Mads Roerslev,Brentford,mads roerslev rasmussen,0.722
25,Chido Obi-Martin,Manchester United,chido obi,0.720
24,Daniel Podence,Wolverhampton,daniel bentley,0.714
28,Bobby Decordova-Reid,Leicester City,bobby reid,0.667
38,Mateus Mané,Wolverhampton,matheus cunha,0.667
10,Emerson Palmieri,West Ham United,emerson,0.609
30,Kim Ji-Soo,Brentford,ji soo kim,0.600
43,George Edmundson,Ipswich Town,george hirst,0.571
32,Jake Evans,Leicester City,jamie vardy,0.571
21,Igor Júlio,Brighton & Hove Albion,igor,0.571
35,Jayden Danns,Liverpool,jarell quansah,0.538
3,Nico O'Reilly,Manchester City,nico gonzalez,0.538
4,André,Wolverhampton,andre trindade,0.526
22,Jay Robinson,Southampton,juan larios,0.522
45,Shumaira Mheuka,Chelsea,bashir humphreys,0.516
2,Abdul Fatawu Issahaku,Leicester City,issahaku fatawu,0.500
7,Billy Gilmour,Brighton & Hove Albion,solly march,0.500
37,Roman Dixon,Everton,iliman ndiaye,0.500

In [16]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mads roerslev',
                    'chido obi martin',
                    'bobby decordova reid',
                    'emerson palmieri',
                    'kim ji soo',
                    'igor julio',
                    'andre',
                    'abdul fatawu issahaku'
                    


]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 8

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [17]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf                    team             cg_match  score
15         Oliver Scarles         West Ham United      vladimir coufal  0.483
42       Remy Rees-Dottin             Bournemouth        ryan christie  0.483
17         Ben Winterburn             Bournemouth      luis sinisterra  0.483
16           Harry Howell  Brighton & Hove Albion        danny welbeck  0.480
44             Alfie Pond           Wolverhampton          luke cundle  0.476
18  Nathan Butler-Oyedeji                 Arsenal        ethan nwaneri  0.471
40   Zain Silcott-Duberry             Bournemouth           alex scott  0.467
39         Jay Stansfield                  Fulham     joachim andersen  0.467
34        Scott McTominay       Manchester United          mason mount  0.462
31           Divin Mubama         Manchester City  christian mcfarlane  0.452
19           Lewis Orford         West Ham United      wes foderingham  0.444
29         Mathis Amougou                 Chelsea            marc guiu  0.435
41          Olabade Aluko          Leicester City           ben nelson  0.435
26           Jeremy Monga          Leicester City        harry souttar  0.400

In [18]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [19]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 538/562 (95.7%)
Sin salario:     24

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [20]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 24

,player,team,minutesPlayed,appearances,goals,assists
0,Nathan Butler-Oyedeji,Arsenal,11,1,0,0
1,Ben Winterburn,Bournemouth,22,4,0,0
2,Zain Silcott-Duberry,Bournemouth,1,1,0,0
3,Remy Rees-Dottin,Bournemouth,1,1,0,0
4,Billy Gilmour,Brighton & Hove Albion,97,2,0,0
5,Harry Howell,Brighton & Hove Albion,14,1,0,0
6,Mathis Amougou,Chelsea,12,1,0,0
7,Shumaira Mheuka,Chelsea,1,1,0,0
8,Roman Dixon,Everton,90,1,0,0
9,Jay Stansfield,Fulham,1,1,0,0
10,George Edmundson,Ipswich Town,1,1,0,0
11,Jeremy Monga,Leicester City,118,7,0,0
12,Jake Evans,Leicester City,31,4,0,0
13,Olabade Aluko,Leicester City,1,1,0,0
14,Jayden Danns,Liverpool,10,1,0,0
15,Nico O'Reilly,Manchester City,532,9,2,0
16,Divin Mubama,Manchester City,27,1,0,0
17,Scott McTominay,Manchester United,22,2,0,0
18,Jay Robinson,Southampton,143,4,0,0
19,Oliver Scarles,West Ham United,662,15,0,0
20,Lewis Orford,West Ham United,47,2,0,0
21,Daniel Podence,Wolverhampton,46,2,0,0
22,Mateus Mané,Wolverhampton,1,1,0,0
23,Alfie Pond,Wolverhampton,1,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [21]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Arsenal  —  SF sin salario:

                  player  minutesPlayed
0  Nathan Butler-Oyedeji             11

  CG plantilla completa:

                  player           player_norm
0   Albert Sambi Lokonga  albert sambi lokonga
1              Ben White             ben white
2            Bukayo Saka           bukayo saka
3             David Raya            david raya
4            Declan Rice           declan rice
5          Ethan Nwaneri         ethan nwaneri
6           Fábio Vieira          fabio vieira
7          Gabriel Jesus         gabriel jesus
8      Gabriel Magalhães     gabriel magalhaes
9     Gabriel Martinelli    gabriel martinelli
10          Jakub Kiwior          jakub kiwior
11              Jorginho              jorginho
12        Jurrien Timber        jurrien timber
13           Kai Havertz           kai havertz
14             Karl Hein             karl hein
15        Kieran Tierney        kieran tierney
16      Leandro Trossard      leandro trossard
17       Maldini Kacurri       maldini kacurri
18       Martin Ødegaard        martin degaard
19          Mikel Merino          mikel merino
20    Myles Lewis-Skelly    myles lewis skelly
21                  Neto                  neto
22          Nuno Tavares          nuno tavares
23   Oleksandr Zinchenko   oleksandr zinchenko
24       Raheem Sterling       raheem sterling
25    Riccardo Calafiori    riccardo calafiori
26     Takehiro Tomiyasu     takehiro tomiyasu
27         Thomas Partey         thomas partey
28        William Saliba        william saliba

============================================================
  Bournemouth  —  SF sin salario:

                 player  minutesPlayed
0        Ben Winterburn             22
1      Remy Rees-Dottin              1
2  Zain Silcott-Duberry              1

  CG plantilla completa:

                 player          player_norm
0            Adam Smith           adam smith
1            Alex Scott           alex scott
2       Antoine Semenyo      antoine semenyo
3          Chris Mepham         chris mepham
4        Dango Ouattara       dango ouattara
5       Daniel Jebbison      daniel jebbison
6          David Brooks         david brooks
7          Dean Huijsen         dean huijsen
8             Enes Ünal            enes unal
9             Evanilson            evanilson
10  Hamed Junior Traoré  hamed junior traore
11        Ilya Zabarnyi        ilya zabarnyi
12       Jaidon Anthony       jaidon anthony
13           James Hill           james hill
14         Joe Rothwell         joe rothwell
15        Julián Araujo        julian araujo
16          Julio Soler          julio soler
17      Justin Kluivert      justin kluivert
18    Kepa Arrizabalaga    kepa arrizabalaga
19           Lewis Cook           lewis cook
20      Luis Sinisterra      luis sinisterra
21        Marcos Senesi        marcos senesi
22     Marcus Tavernier     marcus tavernier
23         Mark Travers         mark travers
24      Matai Akinmboni      matai akinmboni
25           Max Aarons           max aarons
26           Max Kinsey           max kinsey
27         Milos Kerkez         milos kerkez
28       Philip Billing       philip billing
29        Romain Faivre        romain faivre
30        Ryan Christie        ryan christie
31          Tyler Adams          tyler adams
32          Will Dennis          will dennis

============================================================
  Brighton & Hove Albion  —  SF sin salario:

          player  minutesPlayed
0  Billy Gilmour             97
1   Harry Howell             14

  CG plantilla completa:

                   player            player_norm
0           Abdallah Sima          abdallah sima
1            Adam Webster           adam webster
2   Amario Cozier-Duberry  amario cozier duberry
3            Andrew Moran           andrew moran
4         Bart Verbruggen        bart verbruggen
5            Brajan Gruda           brajan gruda
6          Carl Rushworth         carl rushworth
7           Carlos Baleba          carlos baleba
8          Caylan Vickers         caylan vickers
9           Danny Welbeck          danny welbeck
10            Diego Gómez            diego gomez
11               Ed Turns               ed turns
12           Eiran Cashin           eiran cashin
13          Evan Ferguson          evan ferguson
14         Ferdi Kadıoğlu          ferdi kadoglu
15       Georginio Rutter       georginio rutter
16          Ibrahim Osman          ibrahim osman
17                   Igor                   igor
18          Imari Samuels          imari samuels
19       Jack Hinshelwood       jack hinshelwood
20            Jakub Moder            jakub moder
21           James Beadle           james beadle
22           James Milner           james milner
23     Jan Paul van Hecke     jan paul van hecke
24           Jason Steele           jason steele
25       Jeremy Sarmiento       jeremy sarmiento
26             João Pedro             joao pedro
27           Joël Veltman           joel veltman
28           Julio Enciso           julio enciso
29           Kamari Doyle           kamari doyle
30           Kaoru Mitoma           kaoru mitoma
31         Killian Cahill         killian cahill
32             Lewis Dunk             lewis dunk
33        Luca Barrington        luca barrington
34          Mark O'Mahony          mark o mahony
35           Mats Wieffer           mats wieffer
36           Matt O'Riley           matt o riley
37         Odeluga Offiah         odeluga offiah
38       Pervis Estupiñán       pervis estupinan
39         Samy Chouchane         samy chouchane
40          Simon Adingra          simon adingra
41            Solly March            solly march
42        Stefanos Tzimas        stefanos tzimas
43          Tariq Lamptey          tariq lamptey
44             Tom McGill             tom mcgill
45         Valentín Barco         valentin barco
46         Yankuba Minteh         yankuba minteh
47            Yasin Ayari            yasin ayari

============================================================
  Chelsea  —  SF sin salario:

            player  minutesPlayed
0   Mathis Amougou             12
1  Shumaira Mheuka              1

  CG plantilla completa:

                   player            player_norm
0         Aarón Anselmino        aaron anselmino
1              Alex Matos             alex matos
2         Alfie Gilchrist        alfie gilchrist
3           Andrey Santos          andrey santos
4             Axel Disasi            axel disasi
5        Bashir Humphreys       bashir humphreys
6            Ben Chilwell           ben chilwell
7       Benoît Badiashile      benoit badiashile
8             Caleb Wiley            caleb wiley
9      Carney Chukwuemeka     carney chukwuemeka
10         Cesare Casadei         cesare casadei
11     Christopher Nkunku     christopher nkunku
12            Cole Palmer            cole palmer
13     David Datro Fofana     david datro fofana
14      Deivid Washington      deivid washington
15       Djordje Petrovic       djordje petrovic
16         Dylan Williams         dylan williams
17         Enzo Fernández         enzo fernandez
18        Filip Jørgensen         filip jrgensen
19        Gabriel Slonina        gabriel slonina
20           Jadon Sancho           jadon sancho
21       Jimmy-Jay Morgan       jimmy jay morgan
22             João Félix             joao felix
23        Josh Acheampong        josh acheampong
24      Kepa Arrizabalaga      kepa arrizabalaga
25  Kiernan Dewsbury-Hall  kiernan dewsbury hall
26         Leo Castledine         leo castledine
27           Levi Colwill           levi colwill
28        Lucas Bergström        lucas bergstrom
29             Malo Gusto             malo gusto
30         Marc Cucurella         marc cucurella
31              Marc Guiu              marc guiu
32      Marcus Bettinelli      marcus bettinelli
33         Moisés Caicedo         moises caicedo
34        Mykhailo Mudryk        mykhailo mudryk
35        Nicolas Jackson        nicolas jackson
36           Noni Madueke           noni madueke
37             Pedro Neto             pedro neto
38        Raheem Sterling        raheem sterling
39            Reece James            reece james
40           Renato Veiga           renato veiga
41         Robert Sánchez         robert sanchez
42            Roméo Lavia            romeo lavia
43     Teddy Sharman-Lowe     teddy sharman lowe
44       Tosin Adarabioyo       tosin adarabioyo
45        Trevoh Chalobah        trevoh chalobah
46         Tyrique George         tyrique george
47          Wesley Fofana          wesley fofana
48             Zak Sturge             zak sturge

============================================================
  Everton  —  SF sin salario:

        player  minutesPlayed
0  Roman Dixon             90

  CG plantilla completa:

                   player            player_norm
0      Abdoulaye Doucouré     abdoulaye doucoure
1           Armando Broja          armando broja
2            Ashley Young           ashley young
3           Asmir Begovic          asmir begovic
4                    Beto                   beto
5           Billy Crellin          billy crellin
6          Carlos Alcaraz         carlos alcaraz
7   Dominic Calvert-Lewin  dominic calvert lewin
8           Dwight McNeil          dwight mcneil
9         Elijah Campbell        elijah campbell
10      Francis Okoronkwo      francis okoronkwo
11     Harrison Armstrong     harrison armstrong
12            Harry Tyrer            harry tyrer
13          Idrissa Gueye          idrissa gueye
14          Iliman Ndiaye          iliman ndiaye
15          Jack Harrison          jack harrison
16           Jake O'Brien           jake o brien
17           James Garner           james garner
18        James Tarkowski        james tarkowski
19     Jarrad Branthwaite     jarrad branthwaite
20        Jenson Metcalfe        jenson metcalfe
21       Jesper Lindstrøm        jesper lindstrm
22          João Virgínia          joao virginia
23        Jordan Pickford        jordan pickford
24          Mason Holgate          mason holgate
25          Michael Keane          michael keane
26       Nathan Patterson       nathan patterson
27            Neal Maupay            neal maupay
28           Orel Mangala           orel mangala
29         Séamus Coleman         seamus coleman
30         Tim Iroegbunam         tim iroegbunam
31      Vitaliy Mykolenko      vitaliy mykolenko
32       Youssef Chermiti       youssef chermiti

============================================================
  Fulham  —  SF sin salario:

           player  minutesPlayed
0  Jay Stansfield              1

  CG plantilla completa:

              player       player_norm
0       Adama Traoré      adama traore
1         Alex Iwobi        alex iwobi
2    Andreas Pereira   andreas pereira
3   Antonee Robinson  antonee robinson
4         Bernd Leno        bernd leno
5      Calvin Bassey     calvin bassey
6    Carlos Vinícius   carlos vinicius
7   Emile Smith Rowe  emile smith rowe
8      Harrison Reed     harrison reed
9       Harry Wilson      harry wilson
10     Harvey Araujo     harvey araujo
11         Issa Diop         issa diop
12  Joachim Andersen  joachim andersen
13      Jorge Cuenca      jorge cuenca
14         Josh King         josh king
15        Kenny Tete        kenny tete
16       Luke Harris       luke harris
17      Martial Godo      martial godo
18  Oliver Sanderson  oliver sanderson
19      Raúl Jiménez      raul jimenez
20      Reiss Nelson      reiss nelson
21     Rodrigo Muniz     rodrigo muniz
22    Ryan Sessegnon    ryan sessegnon
23      Sander Berge      sander berge
24        Saša Lukić        sasa lukic
25      Steven Benda      steven benda
26  Timothy Castagne  timothy castagne
27       Tom Cairney       tom cairney
28           Willian           willian

============================================================
  Ipswich Town  —  SF sin salario:

             player  minutesPlayed
0  George Edmundson              1

  CG plantilla completa:

                    player             player_norm
0              Alex Palmer             alex palmer
1            Ali Al-Hamadi           ali al hamadi
2           Arijanet Muric          arijanet muric
3            Axel Tuanzebe           axel tuanzebe
4              Ben Godfrey             ben godfrey
5              Ben Johnson             ben johnson
6          Cameron Burgess         cameron burgess
7        Cameron Humphreys       cameron humphreys
8         Chiedozie Ogbene        chiedozie ogbene
9         Christian Walton        christian walton
10          Cieran Slicker          cieran slicker
11           Conor Chaplin           conor chaplin
12          Conor Townsend          conor townsend
13             Dara O'Shea             dara o shea
14           Elkan Baggott           elkan baggott
15            George Hirst            george hirst
16            Harry Clarke            harry clarke
17             Jack Clarke             jack clarke
18             Jack Taylor             jack taylor
19           Jacob Greaves           jacob greaves
20  Jaden Philogene-Bidace  jaden philogene bidace
21            Jens Cajuste            jens cajuste
22            Julio Enciso            julio enciso
23         Kalvin Phillips         kalvin phillips
24              Leif Davis              leif davis
25              Liam Delap              liam delap
26         Luke Woolfenden         luke woolfenden
27          Marcus Harness          marcus harness
28          Massimo Luongo          massimo luongo
29        Nathan Broadhead        nathan broadhead
30        Omari Hutchinson        omari hutchinson
31         Sammie Szmodics         sammie szmodics
32              Samy Morsy              samy morsy
33               Wes Burns               wes burns

============================================================
  Leicester City  —  SF sin salario:

          player  minutesPlayed
0     Jake Evans             31
1   Jeremy Monga            118
2  Olabade Aluko              1

  CG plantilla completa:

                player         player_norm
0           Ben Nelson          ben nelson
1   Bilal El Khannouss  bilal el khannouss
2           Bobby Reid          bobby reid
3    Boubakary Soumaré   boubakary soumare
4        Brandon Cover       brandon cover
5          Caleb Okoli         caleb okoli
6          Chris Popov         chris popov
7          Conor Coady         conor coady
8       Daniel Iversen      daniel iversen
9           Danny Ward          danny ward
10  Facundo Buonanotte  facundo buonanotte
11     Hamza Choudhury     hamza choudhury
12       Harry Souttar       harry souttar
13         Harry Winks         harry winks
14     Issahaku Fatawu     issahaku fatawu
15    Jakub Stolarczyk    jakub stolarczyk
16        James Justin        james justin
17         Jamie Vardy         jamie vardy
18  Jannik Vestergaard  jannik vestergaard
19         Jordan Ayew         jordan ayew
20       Kasey McAteer       kasey mcateer
21         Luke Thomas         luke thomas
22      Mads Hermansen      mads hermansen
23     Michael Golding     michael golding
24     Odsonne Edouard     odsonne edouard
25        Oliver Skipp        oliver skipp
26         Patson Daka         patson daka
27     Ricardo Pereira     ricardo pereira
28        Silko Thomas        silko thomas
29     Stephy Mavididi     stephy mavididi
30  Victor Kristiansen  victor kristiansen
31       Wilfred Ndidi       wilfred ndidi
32          Will Alves          will alves
33           Wout Faes           wout faes
34      Woyo Coulibaly      woyo coulibaly

============================================================
  Liverpool  —  SF sin salario:

         player  minutesPlayed
0  Jayden Danns             10

  CG plantilla completa:

                    player             player_norm
0      Alexis Mac Allister     alexis mac allister
1                  Alisson                 alisson
2         Andrew Robertson        andrew robertson
3          Ben Gannon-Doak         ben gannon doak
4            Calum Scanlon           calum scanlon
5            Calvin Ramsay           calvin ramsay
6        Caoimhín Kelleher       caoimhin kelleher
7               Cody Gakpo              cody gakpo
8            Conor Bradley           conor bradley
9             Curtis Jones            curtis jones
10            Darwin Núñez            darwin nunez
11              Diogo Jota              diogo jota
12         Dominic Corness         dominic corness
13      Dominik Szoboszlai      dominik szoboszlai
14         Federico Chiesa         federico chiesa
15    Giorgi Mamardashvili    giorgi mamardashvili
16           Harvey Davies           harvey davies
17          Harvey Elliott          harvey elliott
18         Ibrahima Konaté         ibrahima konate
19          Jarell Quansah          jarell quansah
20               Joe Gomez               joe gomez
21            Kaide Gordon            kaide gordon
22   Konstantinos Tsimikas   konstantinos tsimikas
23            Lewis Koumas            lewis koumas
24         Luca Stephenson         luca stephenson
25               Luis Díaz               luis diaz
26           Luke Chambers           luke chambers
27           Mohamed Salah           mohamed salah
28      Nathaniel Phillips      nathaniel phillips
29           Rhys Williams           rhys williams
30        Ryan Gravenberch        ryan gravenberch
31         Stefan Bajcetic         stefan bajcetic
32  Trent Alexander-Arnold  trent alexander arnold
33            Tyler Morton            tyler morton
34         Virgil van Dijk         virgil van dijk
35         Vitezslav Jaros         vitezslav jaros
36             Wataru Endo             wataru endo

============================================================
  Manchester City  —  SF sin salario:

          player  minutesPlayed
0   Divin Mubama             27
1  Nico O'Reilly            532

  CG plantilla completa:

                  player           player_norm
0     Abdukodir Khusanov    abdukodir khusanov
1         Bernardo Silva        bernardo silva
2           Callum Doyle          callum doyle
3    Christian McFarlane   christian mcfarlane
4      Claudio Echeverri     claudio echeverri
5                Ederson               ederson
6         Erling Haaland        erling haaland
7           Finley Burns          finley burns
8         İlkay Gündoğan        ilkay gundogan
9            Issa Kabore           issa kabore
10         Jack Grealish         jack grealish
11         Jadel Katongo         jadel katongo
12  Jahmai Simpson-Pusey  jahmai simpson pusey
13          James McAtee          james mcatee
14           Jérémy Doku           jeremy doku
15           John Stones           john stones
16   Josh Wilson-Esbrand   josh wilson esbrand
17        Josko Gvardiol        josko gvardiol
18              Juma Bah              juma bah
19       Kalvin Phillips       kalvin phillips
20       Kevin De Bruyne       kevin de bruyne
21           Kyle Walker           kyle walker
22            Luke Mbete            luke mbete
23      Mahamadou Susoho      mahamadou susoho
24         Manuel Akanji         manuel akanji
25         Mateo Kovacic         mateo kovacic
26         Matheus Nunes         matheus nunes
27        Máximo Perrone        maximo perrone
28            Nathan Aké            nathan ake
29         Nico González         nico gonzalez
30         Omar Marmoush         omar marmoush
31            Oscar Bobb            oscar bobb
32            Phil Foden            phil foden
33            Rico Lewis            rico lewis
34                 Rodri                 rodri
35            Rúben Dias            ruben dias
36                 Sávio                 savio
37          Scott Carson          scott carson
38  Stefan Ortega Moreno  stefan ortega moreno
39            Vitor Reis            vitor reis
40          Will Dickson          will dickson

============================================================
  Manchester United  —  SF sin salario:

            player  minutesPlayed
0  Scott McTominay             22

  CG plantilla completa:

                player         player_norm
0   Alejandro Garnacho  alejandro garnacho
1       Altay Bayındır        altay bayndr
2          Amad Diallo         amad diallo
3          André Onana         andre onana
4               Antony              antony
5         Ayden Heaven        ayden heaven
6      Bruno Fernandes     bruno fernandes
7             Casemiro            casemiro
8            Chido Obi           chido obi
9    Christian Eriksen   christian eriksen
10         Daniel Gore         daniel gore
11         Diogo Dalot         diogo dalot
12         Ethan Ennis         ethan ennis
13      Ethan Wheatley      ethan wheatley
14      Ethan Williams      ethan williams
15         Harry Amass         harry amass
16       Harry Maguire       harry maguire
17        Jadon Sancho        jadon sancho
18          Joe Hugill          joe hugill
19         Jonny Evans         jonny evans
20      Joshua Zirkzee      joshua zirkzee
21       Kobbie Mainoo       kobbie mainoo
22           Leny Yoro           leny yoro
23   Lisandro Martínez   lisandro martinez
24       Louis Jackson       louis jackson
25           Luke Shaw           luke shaw
26       Manuel Ugarte       manuel ugarte
27     Marcus Rashford     marcus rashford
28         Mason Mount         mason mount
29    Matthijs de Ligt    matthijs de ligt
30   Noussair Mazraoui   noussair mazraoui
31       Patrick Dorgu       patrick dorgu
32      Rasmus Højlund       rasmus hjlund
33        Rhys Bennett        rhys bennett
34          Sam Mather          sam mather
35      Sonny Aljofree      sonny aljofree
36        Toby Collyer        toby collyer
37          Tom Heaton          tom heaton
38    Tyler Fredricson    tyler fredricson
39      Tyrell Malacia      tyrell malacia
40     Victor Lindelöf     victor lindelof

============================================================
  Southampton  —  SF sin salario:

         player  minutesPlayed
0  Jay Robinson            143

  CG plantilla completa:

                   player            player_norm
0          Aaron Ramsdale         aaron ramsdale
1          Adam Armstrong         adam armstrong
2            Adam Lallana           adam lallana
3         Albert Grønbaek         albert grnbaek
4           Alex McCarthy          alex mccarthy
5     Armel Bella-Kotchap    armel bella kotchap
6            Ben Brereton           ben brereton
7          Cameron Archer         cameron archer
8          Charlie Taylor         charlie taylor
9             Dom Ballard            dom ballard
10           Flynn Downes           flynn downes
11           Gavin Bazunu           gavin bazunu
12          Jack Stephens          jack stephens
13             James Bree             james bree
14           Jan Bednarek           jan bednarek
15     Joachim Kayi Sanda     joachim kayi sanda
16              Joe Aribo              joe aribo
17             Joe Lumley             joe lumley
18  Joe O'Brien-Whitmarsh  joe o brien whitmarsh
19                   Juan                   juan
20            Juan Larios            juan larios
21     Kamaldeen Sulemana     kamaldeen sulemana
22          Kuryu Matsuki          kuryu matsuki
23     Kyle Walker-Peters     kyle walker peters
24       Lesley Ugochukwu       lesley ugochukwu
25       Mateus Fernandes       mateus fernandes
26          Maxwel Cornet          maxwel cornet
27            Nathan Wood            nathan wood
28          Nico Lawrence          nico lawrence
29           Paul Onuachu           paul onuachu
30         Ronnie Edwards         ronnie edwards
31           Ross Stewart           ross stewart
32            Ryan Fraser            ryan fraser
33           Ryan Manning           ryan manning
34      Samuel Amo-Ameyaw      samuel amo ameyaw
35          Samuel Edozie          samuel edozie
36           Shea Charles           shea charles
37  Taylor Harwood-Bellis  taylor harwood bellis
38          Tyler Dibling          tyler dibling
39              Welington              welington
40         Will Smallbone         will smallbone
41      Yukinari Sugawara      yukinari sugawara

============================================================
  West Ham United  —  SF sin salario:

           player  minutesPlayed
0    Lewis Orford             47
1  Oliver Scarles            662

  CG plantilla completa:

                     player              player_norm
0           Aaron Cresswell          aaron cresswell
1         Aaron Wan-Bissaka        aaron wan bissaka
2           Alphonse Areola          alphonse areola
3               Andy Irving              andy irving
4           Callum Marshall          callum marshall
5              Carlos Soler             carlos soler
6     Crysencio Summerville    crysencio summerville
7                Danny Ings               danny ings
8             Edson Álvarez            edson alvarez
9                   Emerson                  emerson
10            Evan Ferguson            evan ferguson
11            Freddie Potts            freddie potts
12            George Earthy            george earthy
13             Gideon Kodua             gideon kodua
14          Guido Rodríguez          guido rodriguez
15        James Ward-Prowse        james ward prowse
16             Jarrod Bowen             jarrod bowen
17        Jean-Clair Todibo        jean clair todibo
18             Kaelan Casey             kaelan casey
19  Konstantinos Mavropanos  konstantinos mavropanos
20            Lucas Paquetá            lucas paqueta
21           Luis Guilherme           luis guilherme
22         Lukasz Fabianski         lukasz fabianski
23               Max Kilman               max kilman
24            Maxwel Cornet            maxwel cornet
25          Michail Antonio          michail antonio
26          Mohamadou Kanté          mohamadou kante
27           Mohammed Kudus           mohammed kudus
28             Nayef Aguerd             nayef aguerd
29          Niclas Füllkrug          niclas fullkrug
30            Patrick Kelly            patrick kelly
31             Tomas Soucek             tomas soucek
32          Vladimír Coufal          vladimir coufal
33          Wes Foderingham          wes foderingham

============================================================
  Wolverhampton  —  SF sin salario:

           player  minutesPlayed
0      Alfie Pond              1
1  Daniel Podence             46
2     Mateus Mané              1

  CG plantilla completa:

                    player             player_norm
0           André Trindade          andre trindade
1         Bastien Meupiyou        bastien meupiyou
2          Boubacar Traoré         boubacar traore
3             Carlos Forbs            carlos forbs
4            Chem Campbell           chem campbell
5                Chiquinho               chiquinho
6             Craig Dawson            craig dawson
7           Daniel Bentley          daniel bentley
8         Dexter Lembikisa        dexter lembikisa
9         Emmanuel Agbadou        emmanuel agbadou
10           Enso González           enso gonzalez
11             Fábio Silva             fabio silva
12           Finn Ashworth           finn ashworth
13          Gonçalo Guedes          goncalo guedes
14          Hee-chan Hwang          hee chan hwang
15              Hugo Bueno              hugo bueno
16  Jean-Ricner Bellegarde  jean ricner bellegarde
17              João Gomes              joao gomes
18               Joe Hodge               joe hodge
19                 José Sá                 jose sa
20    Jørgen Strand Larsen     jrgen strand larsen
21          Ki-Jana Hoever          ki jana hoever
22             Luke Cundle             luke cundle
23            Mario Lemina            mario lemina
24        Marshall Munetsi        marshall munetsi
25           Marvin Kaleta           marvin kaleta
26           Matheus Cunha           matheus cunha
27            Matt Doherty            matt doherty
28            Nasser Djiga            nasser djiga
29           Nathan Fraser           nathan fraser
30           Nélson Semedo           nelson semedo
31           Nigel Lonwijk           nigel lonwijk
32           Pablo Sarabia           pablo sarabia
33              Pedro Lima              pedro lima
34         Rayan Aït-Nouri         rayan ait nouri
35           Rodrigo Gomes           rodrigo gomes
36           Sam Johnstone           sam johnstone
37          Santiago Bueno          santiago bueno
38          Sasa Kalajdzic          sasa kalajdzic
39         Tawanda Chirewa         tawanda chirewa
40                Tom King                tom king
41             Tommy Doyle             tommy doyle
42              Toti Gomes              toti gomes
43         Yerson Mosquera         yerson mosquera

In [22]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [23]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 538/562 (95.7%)

In [25]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [24]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_england_2425.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_england_2425.csv
   Jugadores totales:  562
   Con salario:        538
   Sin salario (NaN):  24
   Columnas:           121