# 03 · Join Sofascore + Capology — England Premier League 23/24

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2023/24 de Premier League inglesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_england_2324.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_england_2324.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  570 jugadores | 116 columnas
Capology:   610 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   brighton hove albion
   newcastle united
   tottenham hotspur
   west ham united

En Capology pero no en Sofascore:
   brighton
   newcastle
   tottenham
   west ham

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brighton':'brighton hove albion',
            'newcastle':'newcastle united',
            'tottenham':'tottenham hotspur',
            'west ham':'west ham united'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 500/570 (87.7%)
Sin emparejar: 70

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          5
Revisión media    (0.75 ≤ score < 0.90):   7
Revisión estricta (0.50 ≤ score < 0.75):   33
Revisión muy est. (score < 0.50):           25

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf              team          cg_match  score
2     Łukasz Fabiański   West Ham United  lukasz fabianski  0.968
46      Joshua Dasilva         Brentford   joshua da silva  0.966
11     Mykhaylo Mudryk           Chelsea   mykhailo mudryk  0.933
22     Yehor Yarmolyuk         Brentford   yegor yarmolyuk  0.933
6   Wesley Foderingham  Sheffield United   wes foderingham  0.909

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf               team                 cg_match  score
20  Valentino Livramento   Newcastle United          tino livramento  0.857
9         Đorđe Petrović            Chelsea         djordje petrovic  0.857
16    Jóhann Guðmundsson            Burnley  johann berg gudmundsson  0.850
1      Ben Brereton Díaz   Sheffield United             ben brereton  0.828
13        Edward Nketiah            Arsenal            eddie nketiah  0.815
8          Stefan Ortega    Manchester City     stefan ortega moreno  0.788
7        Pape Matar Sarr  Tottenham Hotspur                pape sarr  0.750

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 7 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
63,Dominic Sadi,Bournemouth,dominic solanke,0.741
24,Mads Roerslev,Brentford,mads roerslev rasmussen,0.722
18,Emerson Royal,Tottenham Hotspur,emerson,0.700
45,Mason Burstow,Chelsea,malo gusto,0.696
28,Alex Murphy,Newcastle United,jacob murphy,0.696
14,Hannibal Mejbri,Manchester United,hannibal,0.696
19,Bobby Decordova-Reid,Fulham,bobby reid,0.667
53,Omari Kellyman,Aston Villa,youri tielemans,0.621
67,Jamie Donley,Tottenham Hotspur,james maddison,0.615
68,Alex Matos,Chelsea,andrey santos,0.609
10,Emerson Palmieri,West Ham United,emerson,0.609
33,Joe White,Newcastle United,joe willock,0.600
17,Oliver Arblaster,Sheffield United,oliver mcburnie,0.581
15,Igor Júlio,Brighton & Hove Albion,igor,0.571
66,Lewis Warrington,Everton,lewis dobbin,0.571
60,Kaide Gordon,Liverpool,andrew robertson,0.571
64,Amadou Diallo,Newcastle United,javier manquillo,0.552
37,David Ozoh,Crystal Palace,daniel munoz,0.545
49,Thiago Alcântara,Liverpool,thiago,0.545
47,Dane Scarlett,Tottenham Hotspur,pape sarr,0.545
32,Jayden Danns,Liverpool,jarell quansah,0.538
36,Mark O'Mahony,Brighton & Hove Albion,mahmoud dahoud,0.519
65,Michael Ndiweni,Newcastle United,isaac hayden,0.519
62,Kaelan Casey,West Ham United,aaron cresswell,0.519
25,Omari Forson,Manchester United,marcus rashford,0.519
56,Jaidon Anthony,Bournemouth,gavin kilkenny,0.500
12,Ethan Nwaneri,Arsenal,declan rice,0.500
27,Owen Beck,Liverpool,stefan bajcetic,0.500
40,Finley Munroe,Aston Villa,alex moreno,0.500
29,Manuel Benson,Burnley,johann berg gudmundsson,0.500
57,Ryan One,Sheffield United,jayden bogle,0.500
41,Ben Parkinson,Newcastle United,elliot anderson,0.500
43,Ethan Wheatley,Manchester United,tom heaton,0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mads roerslev',
                    'emerson royal',
                    'hannibal mejbri',
                    'bobby decordova reid',
                    'emerson palmieri',
                    'igor julio',
                    'thiago alcantara'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 7

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf                    team             cg_match  score
34         Benicio Boaitey  Brighton & Hove Albion   facundo buonanotte  0.485
69           Thomas Cannon                 Everton     nathan patterson  0.483
38        Michael Olakigbe               Brentford        charlie goode  0.483
3          Josh Acheampong                 Chelsea       moises caicedo  0.483
0      Aleksandar Mitrović                  Fulham           alex iwobi  0.483
55       Antwoine Hackford        Sheffield United         benie traore  0.483
58          Joseph Johnson              Luton Town      andros townsend  0.483
23         Alfie Gilchrist                 Chelsea           malo gusto  0.480
5          Aymeric Laporte         Manchester City           rico lewis  0.480
59             Daniel Gore       Manchester United       raphael varane  0.480
31            Leon Chiwome           Wolverhampton        nelson semedo  0.480
50              Sam Curtis        Sheffield United          adam davies  0.476
48             Bobby Clark               Liverpool           cody gakpo  0.476
44         James McConnell               Liverpool  alexis mac allister  0.471
4         Davinson Sánchez       Tottenham Hotspur       brandon austin  0.467
61         Jimi Tauriainen                 Chelsea          ian maatsen  0.462
42             Zack Nelson              Luton Town          jacob brown  0.455
39              Sydie Peck        Sheffield United         jayden bogle  0.455
51             Mikey Moore       Tottenham Hotspur          timo werner  0.455
54  Jaden Philogene-Bidace             Aston Villa   leander dendoncker  0.450
21           George Earthy         West Ham United       conor coventry  0.444
52     Kaine Kesler-Hayden             Aston Villa        kortney hause  0.438
26           Nathan Fraser           Wolverhampton      boubacar traore  0.429
35         Tawanda Chirewa           Wolverhampton       hee chan hwang  0.414
30          Odeluga Offiah  Brighton & Hove Albion          solly march  0.400

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 519/570 (91.1%)
Sin salario:     51

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 51

,player,team,minutesPlayed,appearances,goals,assists
0,Ethan Nwaneri,Arsenal,13,1,0,0
1,Omari Kellyman,Aston Villa,35,2,0,0
2,Kaine Kesler-Hayden,Aston Villa,10,3,0,0
3,Jaden Philogene-Bidace,Aston Villa,10,1,0,0
4,Finley Munroe,Aston Villa,8,1,0,0
5,Jaidon Anthony,Bournemouth,153,3,0,0
6,Dominic Sadi,Bournemouth,1,1,0,0
7,Michael Olakigbe,Brentford,100,8,0,0
8,Odeluga Offiah,Brighton & Hove Albion,146,4,0,0
9,Mark O'Mahony,Brighton & Hove Albion,69,3,0,0
10,Benicio Boaitey,Brighton & Hove Albion,65,5,0,0
11,Manuel Benson,Burnley,133,8,0,0
12,Alfie Gilchrist,Chelsea,223,11,1,0
13,Mason Burstow,Chelsea,16,2,0,0
14,Josh Acheampong,Chelsea,12,1,0,0
15,Jimi Tauriainen,Chelsea,1,1,0,0
16,Alex Matos,Chelsea,1,1,0,0
17,David Ozoh,Crystal Palace,168,9,0,0
18,Lewis Warrington,Everton,1,1,0,0
19,Thomas Cannon,Everton,1,1,0,0
20,Aleksandar Mitrović,Fulham,32,1,0,0
21,Bobby Clark,Liverpool,103,5,0,0
22,Jayden Danns,Liverpool,26,2,0,0
23,Owen Beck,Liverpool,16,1,0,0
24,James McConnell,Liverpool,11,3,0,0
25,Kaide Gordon,Liverpool,1,1,0,0
26,Joseph Johnson,Luton Town,75,2,0,0
27,Zack Nelson,Luton Town,12,2,0,0
28,Aymeric Laporte,Manchester City,11,1,0,0
29,Omari Forson,Manchester United,87,4,0,1
30,Ethan Wheatley,Manchester United,28,3,0,0
31,Daniel Gore,Manchester United,1,1,0,0
32,Ben Parkinson,Newcastle United,24,1,0,0
33,Joe White,Newcastle United,21,4,0,0
34,Alex Murphy,Newcastle United,16,2,0,0
35,Amadou Diallo,Newcastle United,1,1,0,0
36,Michael Ndiweni,Newcastle United,1,1,0,0
37,Oliver Arblaster,Sheffield United,946,12,0,0
38,Sam Curtis,Sheffield United,27,1,0,0
39,Ryan One,Sheffield United,18,1,0,0
40,Antwoine Hackford,Sheffield United,17,2,0,0
41,Sydie Peck,Sheffield United,9,1,0,0
42,Davinson Sánchez,Tottenham Hotspur,76,1,0,0
43,Dane Scarlett,Tottenham Hotspur,42,4,0,0
44,Mikey Moore,Tottenham Hotspur,20,2,0,0
45,Jamie Donley,Tottenham Hotspur,3,3,0,0
46,George Earthy,West Ham United,33,3,1,0
47,Kaelan Casey,West Ham United,1,1,0,0
48,Nathan Fraser,Wolverhampton,210,7,0,0
49,Leon Chiwome,Wolverhampton,175,3,0,0
50,Tawanda Chirewa,Wolverhampton,165,8,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Arsenal  —  SF sin salario:

          player  minutesPlayed
0  Ethan Nwaneri             13

  CG plantilla completa:

                 player          player_norm
0        Aaron Ramsdale       aaron ramsdale
1             Ben White            ben white
2           Bukayo Saka          bukayo saka
3         Cédric Soares        cedric soares
4            David Raya           david raya
5           Declan Rice          declan rice
6         Eddie Nketiah        eddie nketiah
7      Emile Smith Rowe     emile smith rowe
8          Fábio Vieira         fabio vieira
9         Gabriel Jesus        gabriel jesus
10    Gabriel Magalhães    gabriel magalhaes
11   Gabriel Martinelli   gabriel martinelli
12         Jakub Kiwior         jakub kiwior
13             Jorginho             jorginho
14       Jurrien Timber       jurrien timber
15          Kai Havertz          kai havertz
16            Karl Hein            karl hein
17       Kieran Tierney       kieran tierney
18     Leandro Trossard     leandro trossard
19           Marquinhos           marquinhos
20      Martin Ødegaard       martin degaard
21       Mohamed Elneny       mohamed elneny
22  Oleksandr Zinchenko  oleksandr zinchenko
23         Reiss Nelson         reiss nelson
24    Takehiro Tomiyasu    takehiro tomiyasu
25        Thomas Partey        thomas partey
26       William Saliba       william saliba

============================================================
  Aston Villa  —  SF sin salario:

                   player  minutesPlayed
0           Finley Munroe              8
1  Jaden Philogene-Bidace             10
2     Kaine Kesler-Hayden             10
3          Omari Kellyman             35

  CG plantilla completa:

                player         player_norm
0          Álex Moreno         alex moreno
1      Bertrand Traoré     bertrand traore
2      Boubacar Kamara     boubacar kamara
3       Calum Chambers      calum chambers
4      Clément Lenglet     clement lenglet
5         Diego Carlos        diego carlos
6         Douglas Luiz        douglas luiz
7     Emiliano Buendía    emiliano buendia
8    Emiliano Martínez   emiliano martinez
9           Ezri Konsa          ezri konsa
10        Jacob Ramsey        jacob ramsey
11          Jhon Durán          jhon duran
12           Joe Gauci           joe gauci
13         John McGinn         john mcginn
14       Kortney Hause       kortney hause
15  Leander Dendoncker  leander dendoncker
16         Leon Bailey         leon bailey
17         Lucas Digne         lucas digne
18          Matty Cash          matty cash
19       Morgan Rogers       morgan rogers
20        Moussa Diaby        moussa diaby
21      Nicolò Zaniolo      nicolo zaniolo
22       Ollie Watkins       ollie watkins
23          Pau Torres          pau torres
24   Philippe Coutinho   philippe coutinho
25         Robin Olsen         robin olsen
26      Tim Iroegbunam      tim iroegbunam
27        Tyrone Mings        tyrone mings
28     Youri Tielemans     youri tielemans

============================================================
  Bournemouth  —  SF sin salario:

           player  minutesPlayed
0    Dominic Sadi              1
1  Jaidon Anthony            153

  CG plantilla completa:

                 player          player_norm
0            Adam Smith           adam smith
1            Alex Scott           alex scott
2       Antoine Semenyo      antoine semenyo
3          Chris Mepham         chris mepham
4        Dango Ouattara       dango ouattara
5       Darren Randolph      darren randolph
6          David Brooks         david brooks
7       Dominic Solanke      dominic solanke
8    Emiliano Marcondes   emiliano marcondes
9             Enes Ünal            enes unal
10       Gavin Kilkenny       gavin kilkenny
11  Hamed Junior Traorè  hamed junior traore
12        Ilya Zabarnyi        ilya zabarnyi
13           Ionut Radu           ionut radu
14           James Hill           james hill
15         Joe Rothwell         joe rothwell
16      Justin Kluivert      justin kluivert
17        Kieffer Moore        kieffer moore
18           Lewis Cook           lewis cook
19          Lloyd Kelly          lloyd kelly
20      Luis Sinisterra      luis sinisterra
21        Marcos Senesi        marcos senesi
22     Marcus Tavernier     marcus tavernier
23         Mark Travers         mark travers
24           Max Aarons           max aarons
25         Milos Kerkez         milos kerkez
26                 Neto                 neto
27       Philip Billing       philip billing
28        Romain Faivre        romain faivre
29        Ryan Christie        ryan christie
30      Ryan Fredericks      ryan fredericks
31          Tyler Adams          tyler adams

============================================================
  Brentford  —  SF sin salario:

             player  minutesPlayed
0  Michael Olakigbe            100

  CG plantilla completa:

                     player              player_norm
0              Aaron Hickey             aaron hickey
1                   Ben Mee                  ben mee
2              Bryan Mbeumo             bryan mbeumo
3             Charlie Goode            charlie goode
4        Christian Nørgaard        christian nrgaard
5           Ellery Balcombe          ellery balcombe
6             Ethan Pinnock            ethan pinnock
7              Frank Onyeka             frank onyeka
8   Hákon Rafn Valdimarsson  hakon rafn valdimarsson
9                Ivan Toney               ivan toney
10          Joshua Da Silva          joshua da silva
11       Keane Lewis-Potter       keane lewis potter
12             Kevin Schade             kevin schade
13          Kristoffer Ajer          kristoffer ajer
14  Mads Roerslev Rasmussen  mads roerslev rasmussen
15             Mark Flekken             mark flekken
16           Mathias Jensen           mathias jensen
17         Mikkel Damsgaard         mikkel damsgaard
18       Myles Peart-Harris       myles peart harris
19           Nathan Collins           nathan collins
20              Neal Maupay              neal maupay
21               Rico Henry               rico henry
22             Ryan Trevitt             ryan trevitt
23            Saman Ghoddos            saman ghoddos
24          Sergio Reguilón          sergio reguilon
25         Shandon Baptiste         shandon baptiste
26         Thomas Strakosha         thomas strakosha
27            Vitaly Janelt            vitaly janelt
28          Yegor Yarmolyuk          yegor yarmolyuk
29              Yoane Wissa              yoane wissa
30         Yunus Emre Konak         yunus emre konak
31                    Zanka                    zanka

============================================================
  Brighton & Hove Albion  —  SF sin salario:

            player  minutesPlayed
0  Benicio Boaitey             65
1    Mark O'Mahony             69
2   Odeluga Offiah            146

  CG plantilla completa:

                player         player_norm
0         Adam Lallana        adam lallana
1         Adam Webster        adam webster
2            Ansu Fati           ansu fati
3      Bart Verbruggen     bart verbruggen
4        Billy Gilmour       billy gilmour
5        Carlos Baleba       carlos baleba
6        Danny Welbeck       danny welbeck
7        Evan Ferguson       evan ferguson
8   Facundo Buonanotte  facundo buonanotte
9                 Igor                igor
10    Jack Hinshelwood    jack hinshelwood
11         Jakub Moder         jakub moder
12        James Milner        james milner
13  Jan Paul van Hecke  jan paul van hecke
14        Jason Steele        jason steele
15          João Pedro          joao pedro
16        Joël Veltman        joel veltman
17        Julio Enciso        julio enciso
18    Kacper Kozlowski    kacper kozlowski
19        Kaoru Mitoma        kaoru mitoma
20          Lewis Dunk          lewis dunk
21      Mahmoud Dahoud      mahmoud dahoud
22         Pascal Groß          pascal gro
23    Pervis Estupiñán    pervis estupinan
24       Simon Adingra       simon adingra
25         Solly March         solly march
26       Steven Alzate       steven alzate
27       Tariq Lamptey       tariq lamptey
28          Tom McGill          tom mcgill
29      Valentín Barco      valentin barco

============================================================
  Burnley  —  SF sin salario:

          player  minutesPlayed
0  Manuel Benson            133

  CG plantilla completa:

                     player              player_norm
0              Aaron Ramsey             aaron ramsey
1           Ameen Al-Dakhil          ameen al dakhil
2             Anass Zaroury            anass zaroury
3            Arijanet Muric           arijanet muric
4             Benson Manuel            benson manuel
5            Charlie Taylor           charlie taylor
6             CJ Egan-Riley            cj egan riley
7            Connor Roberts           connor roberts
8               Dara O'Shea              dara o shea
9           Darko Churlinov          darko churlinov
10       David Datro Fofana       david datro fofana
11            Denis Franchi            denis franchi
12              Enock Agyei              enock agyei
13        Han-Noah Massengo        han noah massengo
14          Hannes Delcroix          hannes delcroix
15            Hjalmar Ekdal            hjalmar ekdal
16                Jack Cork                jack cork
17       Jacob Bruun Larsen       jacob bruun larsen
18           James Trafford           james trafford
19            Jay Rodríguez            jay rodriguez
20  Jóhann Berg Gudmundsson  johann berg gudmundsson
21             Jordan Beyer             jordan beyer
22           Josh Brownhill           josh brownhill
23              Josh Cullen              josh cullen
24       Lawrence Vigouroux       lawrence vigouroux
25          Lorenz Assignon          lorenz assignon
26            Luca Koleosho            luca koleosho
27              Lyle Foster              lyle foster
28            Maxime Estève            maxime esteve
29          Michael Obafemi          michael obafemi
30              Mike Trésor              mike tresor
31           Nathan Redmond           nathan redmond
32             Sander Berge             sander berge
33                  Vitinho                  vitinho
34           Wilson Odobert           wilson odobert
35             Zeki Amdouni             zeki amdouni

============================================================
  Chelsea  —  SF sin salario:

            player  minutesPlayed
0       Alex Matos              1
1  Alfie Gilchrist            223
2  Jimi Tauriainen              1
3  Josh Acheampong             12
4    Mason Burstow             16

  CG plantilla completa:

                player         player_norm
0        Andrey Santos       andrey santos
1        Armando Broja       armando broja
2          Axel Disasi         axel disasi
3         Ben Chilwell        ben chilwell
4    Benoît Badiashile   benoit badiashile
5   Carney Chukwuemeka  carney chukwuemeka
6       Cesare Casadei      cesare casadei
7   Christopher Nkunku  christopher nkunku
8          Cole Palmer         cole palmer
9      Conor Gallagher     conor gallagher
10   Deivid Washington   deivid washington
11       Diego Moreira       diego moreira
12    Djordje Petrovic    djordje petrovic
13      Enzo Fernández      enzo fernandez
14        Hakim Ziyech        hakim ziyech
15         Ian Maatsen         ian maatsen
16    Lesley Ugochukwu    lesley ugochukwu
17        Levi Colwill        levi colwill
18     Lucas Bergström     lucas bergstrom
19         Malang Sarr         malang sarr
20          Malo Gusto          malo gusto
21      Marc Cucurella      marc cucurella
22   Marcus Bettinelli   marcus bettinelli
23      Moisés Caicedo      moises caicedo
24     Mykhailo Mudryk     mykhailo mudryk
25     Nicolas Jackson     nicolas jackson
26        Noni Madueke        noni madueke
27     Raheem Sterling     raheem sterling
28         Reece James         reece james
29      Robert Sánchez      robert sanchez
30       Romelu Lukaku       romelu lukaku
31         Roméo Lavia         romeo lavia
32        Thiago Silva        thiago silva
33     Trevoh Chalobah     trevoh chalobah
34       Wesley Fofana       wesley fofana

============================================================
  Crystal Palace  —  SF sin salario:

       player  minutesPlayed
0  David Ozoh            168

  CG plantilla completa:

                  player           player_norm
0           Adam Wharton          adam wharton
1        Cheick Doucouré       cheick doucoure
2         Chris Richards        chris richards
3           Daniel Muñoz          daniel munoz
4         Dean Henderson        dean henderson
5           Eberechi Eze          eberechi eze
6        Jairo Riedewald       jairo riedewald
7          James Tomkins         james tomkins
8   Jean-Philippe Mateta  jean philippe mateta
9        Jefferson Lerma       jefferson lerma
10       Jeffrey Schlupp       jeffrey schlupp
11     Jesurun Rak-Sakyi     jesurun rak sakyi
12      Joachim Andersen      joachim andersen
13         Joe Whitworth         joe whitworth
14             Joel Ward             joel ward
15           Jordan Ayew           jordan ayew
16       Malcolm Ebiowei       malcolm ebiowei
17            Marc Guéhi            marc guehi
18        Matheus França        matheus franca
19         Michael Olise         michael olise
20      Naouirou Ahamada      naouirou ahamada
21       Nathan Ferguson       nathan ferguson
22       Nathaniel Clyne       nathaniel clyne
23       Odsonne Edouard       odsonne edouard
24         Remi Matthews         remi matthews
25           Rob Holding           rob holding
26         Sam Johnstone         sam johnstone
27       Tyrick Mitchell       tyrick mitchell
28           Will Hughes           will hughes

============================================================
  Everton  —  SF sin salario:

             player  minutesPlayed
0  Lewis Warrington              1
1     Thomas Cannon              1

  CG plantilla completa:

                   player            player_norm
0      Abdoulaye Doucouré     abdoulaye doucoure
1            Amadou Onana           amadou onana
2             André Gomes            andre gomes
3           Andy Lonergan          andy lonergan
4          Arnaut Danjuma         arnaut danjuma
5            Ashley Young           ashley young
6             Ben Godfrey            ben godfrey
7                    Beto                   beto
8               Dele Alli              dele alli
9   Dominic Calvert-Lewin  dominic calvert lewin
10          Dwight McNeil          dwight mcneil
11          Idrissa Gueye          idrissa gueye
12          Jack Harrison          jack harrison
13           James Garner           james garner
14        James Tarkowski        james tarkowski
15     Jarrad Branthwaite     jarrad branthwaite
16          João Virgínia          joao virginia
17        Jordan Pickford        jordan pickford
18           Lewis Dobbin           lewis dobbin
19          Michael Keane          michael keane
20       Nathan Patterson       nathan patterson
21         Seamus Coleman         seamus coleman
22          Tyler Onyango          tyler onyango
23      Vitaliy Mykolenko      vitaliy mykolenko
24       Youssef Chermiti       youssef chermiti

============================================================
  Fulham  —  SF sin salario:

                player  minutesPlayed
0  Aleksandar Mitrović             32

  CG plantilla completa:

              player       player_norm
0       Adama Traoré      adama traore
1         Alex Iwobi        alex iwobi
2    Andreas Pereira   andreas pereira
3   Antonee Robinson  antonee robinson
4      Armando Broja     armando broja
5         Bernd Leno        bernd leno
6         Bobby Reid        bobby reid
7      Calvin Bassey     calvin bassey
8    Carlos Vinícius   carlos vinicius
9   Fodé Ballo-Touré  fode ballo toure
10     Harrison Reed     harrison reed
11      Harry Wilson      harry wilson
12         Issa Diop         issa diop
13     João Palhinha     joao palhinha
14        Kenny Tete        kenny tete
15       Luke Harris       luke harris
16       Marek Rodak       marek rodak
17      Raúl Jiménez      raul jimenez
18     Rodrigo Muniz     rodrigo muniz
19        Sasa Lukic        sasa lukic
20      Steven Benda      steven benda
21          Tim Ream          tim ream
22  Timothy Castagne  timothy castagne
23       Tom Cairney       tom cairney
24  Tosin Adarabioyo  tosin adarabioyo
25   Tyrese Francois   tyrese francois
26           Willian           willian

============================================================
  Liverpool  —  SF sin salario:

            player  minutesPlayed
0      Bobby Clark            103
1  James McConnell             11
2     Jayden Danns             26
3     Kaide Gordon              1
4        Owen Beck             16

  CG plantilla completa:

                    player             player_norm
0                   Adrián                  adrian
1      Alexis Mac Allister     alexis mac allister
2                  Alisson                 alisson
3         Andrew Robertson        andrew robertson
4          Ben Gannon-Doak         ben gannon doak
5        Caoimhín Kelleher       caoimhin kelleher
6               Cody Gakpo              cody gakpo
7            Conor Bradley           conor bradley
8             Curtis Jones            curtis jones
9             Darwin Núñez            darwin nunez
10              Diogo Jota              diogo jota
11      Dominik Szoboszlai      dominik szoboszlai
12          Harvey Elliott          harvey elliott
13         Ibrahima Konaté         ibrahima konate
14          Jarell Quansah          jarell quansah
15               Joe Gomez               joe gomez
16              Joel Matip              joel matip
17   Konstantinos Tsimikas   konstantinos tsimikas
18               Luis Díaz               luis diaz
19           Mohamed Salah           mohamed salah
20           Rhys Williams           rhys williams
21        Ryan Gravenberch        ryan gravenberch
22         Stefan Bajcetic         stefan bajcetic
23                  Thiago                  thiago
24  Trent Alexander-Arnold  trent alexander arnold
25         Virgil van Dijk         virgil van dijk
26             Wataru Endo             wataru endo

============================================================
  Luton Town  —  SF sin salario:

           player  minutesPlayed
0  Joseph Johnson             75
1     Zack Nelson             12

  CG plantilla completa:

                  player           player_norm
0   Albert Sambi Lokonga  albert sambi lokonga
1          Alfie Doughty         alfie doughty
2           Amari'i Bell          amari i bell
3        Andros Townsend       andros townsend
4         Carlton Morris        carlton morris
5         Cauley Woodrow        cauley woodrow
6       Chiedozie Ogbene      chiedozie ogbene
7         Daiki Hashioka        daiki hashioka
8              Dan Potts             dan potts
9         Elijah Adebayo        elijah adebayo
10         Elliot Thorpe         elliot thorpe
11        Fred Onyedinma        fred onyedinma
12          Gabriel Osho          gabriel osho
13           Issa Kabore           issa kabore
14           Jacob Brown           jacob brown
15            James Shea            james shea
16          Jordan Clark          jordan clark
17            Luke Berry            luke berry
18    Mads Juel Andersen    mads juel andersen
19     Marvelous Nakamba     marvelous nakamba
20  Pelly Ruddock Mpanzu  pelly ruddock mpanzu
21           Reece Burke           reece burke
22          Ross Barkley          ross barkley
23            Ryan Giles            ryan giles
24          Tahith Chong          tahith chong
25           Teden Mengi           teden mengi
26       Thomas Kaminski       thomas kaminski
27              Tim Krul              tim krul
28           Tom Lockyer           tom lockyer

============================================================
  Manchester City  —  SF sin salario:

            player  minutesPlayed
0  Aymeric Laporte             11

  CG plantilla completa:

                  player           player_norm
0         Bernardo Silva        bernardo silva
1                Ederson               ederson
2         Erling Haaland        erling haaland
3          Jack Grealish         jack grealish
4            Jérémy Doku           jeremy doku
5           João Cancelo          joao cancelo
6            John Stones           john stones
7         Josko Gvardiol        josko gvardiol
8         Julián Álvarez        julian alvarez
9        Kalvin Phillips       kalvin phillips
10       Kevin De Bruyne       kevin de bruyne
11           Kyle Walker           kyle walker
12         Manuel Akanji         manuel akanji
13         Mateo Kovacic         mateo kovacic
14         Matheus Nunes         matheus nunes
15        Máximo Perrone        maximo perrone
16            Nathan Aké            nathan ake
17            Oscar Bobb            oscar bobb
18            Phil Foden            phil foden
19            Rico Lewis            rico lewis
20                 Rodri                 rodri
21            Rúben Dias            ruben dias
22          Scott Carson          scott carson
23          Sergio Gómez          sergio gomez
24  Stefan Ortega Moreno  stefan ortega moreno
25          Zack Steffen          zack steffen

============================================================
  Manchester United  —  SF sin salario:

           player  minutesPlayed
0     Daniel Gore              1
1  Ethan Wheatley             28
2    Omari Forson             87

  CG plantilla completa:

                player         player_norm
0    Aaron Wan-Bissaka   aaron wan bissaka
1   Alejandro Garnacho  alejandro garnacho
2       Altay Bayındır        altay bayndr
3          Amad Diallo         amad diallo
4          André Onana         andre onana
5      Anthony Martial     anthony martial
6               Antony              antony
7      Bruno Fernandes     bruno fernandes
8             Casemiro            casemiro
9    Christian Eriksen   christian eriksen
10         Diogo Dalot         diogo dalot
11   Donny van de Beek   donny van de beek
12   Facundo Pellistri   facundo pellistri
13            Hannibal            hannibal
14       Harry Maguire       harry maguire
15        Jadon Sancho        jadon sancho
16         Jonny Evans         jonny evans
17       Kobbie Mainoo       kobbie mainoo
18   Lisandro Martínez   lisandro martinez
19           Luke Shaw           luke shaw
20     Marcus Rashford     marcus rashford
21     Mason Greenwood     mason greenwood
22         Mason Mount         mason mount
23      Raphaël Varane      raphael varane
24      Rasmus Højlund       rasmus hjlund
25     Scott McTominay     scott mctominay
26     Sergio Reguilón     sergio reguilon
27     Shola Shoretire     shola shoretire
28      Sofyan Amrabat      sofyan amrabat
29          Tom Heaton          tom heaton
30      Tyrell Malacia      tyrell malacia
31     Victor Lindelöf     victor lindelof
32      Willy Kambwala      willy kambwala

============================================================
  Newcastle United  —  SF sin salario:

            player  minutesPlayed
0      Alex Murphy             16
1    Amadou Diallo              1
2    Ben Parkinson             24
3        Joe White             21
4  Michael Ndiweni              1

  CG plantilla completa:

              player       player_norm
0     Alexander Isak    alexander isak
1     Anthony Gordon    anthony gordon
2    Bruno Guimarães   bruno guimaraes
3      Callum Wilson     callum wilson
4           Dan Burn          dan burn
5    Elliot Anderson   elliot anderson
6        Emil Krafth       emil krafth
7       Fabian Schär      fabian schar
8      Harvey Barnes     harvey barnes
9       Isaac Hayden      isaac hayden
10      Jacob Murphy      jacob murphy
11  Jamaal Lascelles  jamaal lascelles
12  Javier Manquillo  javier manquillo
13       Joe Willock       joe willock
14         Joelinton         joelinton
15   Kieran Trippier   kieran trippier
16        Lewis Hall        lewis hall
17       Lewis Miley       lewis miley
18      Loris Karius      loris karius
19    Mark Gillespie    mark gillespie
20   Martin Dubravka   martin dubravka
21      Matt Ritchie      matt ritchie
22      Matt Targett      matt targett
23    Miguel Almirón    miguel almiron
24         Nick Pope         nick pope
25      Paul Dummett      paul dummett
26     Sandro Tonali     sandro tonali
27    Sean Longstaff    sean longstaff
28       Sven Botman       sven botman
29   Tino Livramento   tino livramento

============================================================
  Sheffield United  —  SF sin salario:

              player  minutesPlayed
0  Antwoine Hackford             17
1   Oliver Arblaster            946
2           Ryan One             18
3         Sam Curtis             27
4         Sydie Peck              9

  CG plantilla completa:

                    player             player_norm
0              Adam Davies             adam davies
1             Andre Brooks            andre brooks
2         Anel Ahmedhodzic        anel ahmedhodzic
3         Anis Ben Slimane        anis ben slimane
4            Auston Trusty           auston trusty
5             Ben Brereton            ben brereton
6               Ben Osborn              ben osborn
7             Bénie Traoré            benie traore
8           Cameron Archer          cameron archer
9             Chris Basham            chris basham
10         Daniel Jebbison         daniel jebbison
11             Femi Seriki             femi seriki
12          George Baldock          george baldock
13           Gustavo Hamer           gustavo hamer
14       Ismaila Coulibaly       ismaila coulibaly
15               Ivo Grbic               ivo grbic
16           Jack Robinson           jack robinson
17            James McAtee            james mcatee
18            Jayden Bogle            jayden bogle
19               John Egan               john egan
20              John Fleck              john fleck
21          Jordan Amissah          jordan amissah
22             Louie Marsh             louie marsh
23             Luke Thomas             luke thomas
24           Mason Holgate           mason holgate
25                Max Lowe                max lowe
26         Oliver McBurnie         oliver mcburnie
27          Oliver Norwood          oliver norwood
28          Rhian Brewster          rhian brewster
29  Rhys Norrington-Davies  rhys norrington davies
30              Tom Davies              tom davies
31          Vinicius Souza          vinicius souza
32         Wes Foderingham         wes foderingham
33           William Osula           william osula
34          Yasser Larouci          yasser larouci

============================================================
  Tottenham Hotspur  —  SF sin salario:

             player  minutesPlayed
0     Dane Scarlett             42
1  Davinson Sánchez             76
2      Jamie Donley              3
3       Mikey Moore             20

  CG plantilla completa:

                   player           player_norm
0             Alejo Véliz           alejo veliz
1          Alfie Whiteman        alfie whiteman
2         Ashley Phillips       ashley phillips
3              Ben Davies            ben davies
4          Brandon Austin        brandon austin
5         Brennan Johnson       brennan johnson
6               Bryan Gil             bryan gil
7         Cristian Romero       cristian romero
8        Dejan Kulusevski      dejan kulusevski
9          Destiny Udogie        destiny udogie
10            Djed Spence           djed spence
11                Emerson               emerson
12              Eric Dier             eric dier
13         Fraser Forster        fraser forster
14       Giovani Lo Celso      giovani lo celso
15      Guglielmo Vicario     guglielmo vicario
16          Heung-min Son         heung min son
17            Hugo Lloris           hugo lloris
18           Ivan Perisic          ivan perisic
19         James Maddison        james maddison
20          Manor Solomon         manor solomon
21       Micky van de Ven      micky van de ven
22           Oliver Skipp          oliver skipp
23              Pape Sarr             pape sarr
24            Pedro Porro           pedro porro
25  Pierre-Emile Højbjerg  pierre emile hjbjerg
26          Radu Drăgușin         radu dragusin
27            Richarlison           richarlison
28      Rodrigo Bentancur     rodrigo bentancur
29         Ryan Sessegnon        ryan sessegnon
30        Sergio Reguilón       sergio reguilon
31        Tanguy Ndombélé       tanguy ndombele
32            Timo Werner           timo werner
33          Yves Bissouma         yves bissouma

============================================================
  West Ham United  —  SF sin salario:

          player  minutesPlayed
0  George Earthy             33
1   Kaelan Casey              1

  CG plantilla completa:

                     player              player_norm
0           Aaron Cresswell          aaron cresswell
1           Alphonse Areola          alphonse areola
2            Angelo Ogbonna           angelo ogbonna
3               Ben Johnson              ben johnson
4            Conor Coventry           conor coventry
5                Danny Ings               danny ings
6              Divin Mubama             divin mubama
7             Edson Álvarez            edson alvarez
8                   Emerson                  emerson
9         James Ward-Prowse        james ward prowse
10             Jarrod Bowen             jarrod bowen
11             Joseph Anang             joseph anang
12          Kalvin Phillips          kalvin phillips
13  Konstantinos Mavropanos  konstantinos mavropanos
14               Kurt Zouma               kurt zouma
15            Lucas Paquetá            lucas paqueta
16         Lukasz Fabianski         lukasz fabianski
17            Maxwel Cornet            maxwel cornet
18          Michail Antonio          michail antonio
19           Mohammed Kudus           mohammed kudus
20             Nayef Aguerd             nayef aguerd
21            Pablo Fornals            pablo fornals
22            Saïd Benrahma            said benrahma
23             Thilo Kehrer             thilo kehrer
24             Tomas Soucek             tomas soucek
25          Vladimir Coufal          vladimir coufal

============================================================
  Wolverhampton  —  SF sin salario:

            player  minutesPlayed
0     Leon Chiwome            175
1    Nathan Fraser            210
2  Tawanda Chirewa            165

  CG plantilla completa:

                    player             player_norm
0          Boubacar Traoré         boubacar traore
1             Bruno Jordão            bruno jordao
2             Craig Dawson            craig dawson
3           Daniel Bentley          daniel bentley
4           Daniel Podence          daniel podence
5            Enso González           enso gonzalez
6              Fábio Silva             fabio silva
7           Hee-chan Hwang          hee chan hwang
8               Hugo Bueno              hugo bueno
9   Jean-Ricner Bellegarde  jean ricner bellegarde
10              João Gomes              joao gomes
11               Joe Hodge               joe hodge
12              Jonny Otto              jonny otto
13                 José Sá                 jose sa
14            Mario Lemina            mario lemina
15           Matheus Cunha           matheus cunha
16            Matt Doherty            matt doherty
17              Max Kilman              max kilman
18           Nélson Semedo           nelson semedo
19             Noha Lemina             noha lemina
20           Pablo Sarabia           pablo sarabia
21              Pedro Neto              pedro neto
22         Rayan Aït-Nouri         rayan ait nouri
23          Santiago Bueno          santiago bueno
24          Sasa Kalajdzic          sasa kalajdzic
25                Tom King                tom king
26             Tommy Doyle             tommy doyle
27              Toti Gomes              toti gomes

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 519/570 (91.1%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_england_2324.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_england_2324.csv
   Jugadores totales:  570
   Con salario:        519
   Sin salario (NaN):  51
   Columnas:           121