# 03 · Join Sofascore + Capology — England Premier League 22/23

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2022/23 de Premier League inglesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_england_2223.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_england_2223.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  554 jugadores | 116 columnas
Capology:   593 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   brighton hove albion
   leeds united
   leicester city
   newcastle united
   tottenham hotspur
   west ham united

En Capology pero no en Sofascore:
   brighton
   leeds
   leicester
   newcastle
   tottenham
   west ham

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brighton':'brighton hove albion',
            'leeds':'leeds united',
            'leicester':'leicester city',
            'newcastle':'newcastle united',
            'tottenham':'tottenham hotspur',
            'west ham':'west ham united'


}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 504/554 (91.0%)
Sin emparejar: 50

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          6
Revisión media    (0.75 ≤ score < 0.90):   4
Revisión estricta (0.50 ≤ score < 0.75):   19
Revisión muy est. (score < 0.50):           21

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf               team               cg_match  score
1   Pierre-Emile Højbjerg  Tottenham Hotspur  pierre emile hojbjerg  0.976
4      Christian Nørgaard          Brentford     christian norgaard  0.971
8        Łukasz Fabiański    West Ham United       lukasz fabianski  0.968
14         Joshua Dasilva          Brentford        joshua da silva  0.966
23        Mykhaylo Mudryk            Chelsea        mykhailo mudryk  0.933
41          Joshua Onomah             Fulham            josh onomah  0.917

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf               team              cg_match  score
6   Valentino Livramento        Southampton       tino livramento  0.857
19        Edward Nketiah            Arsenal         eddie nketiah  0.815
0          Stefan Ortega    Manchester City  stefan ortega moreno  0.788
24       Pape Matar Sarr  Tottenham Hotspur             pape sarr  0.750

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 4 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
16,Mads Roerslev,Brentford,mads roerslev rasmussen,0.722
7,Emerson Royal,Tottenham Hotspur,emerson,0.700
18,Bobby Decordova-Reid,Fulham,bobby reid,0.667
49,Harvey White,Tottenham Hotspur,alfie whiteman,0.615
15,Emerson Palmieri,West Ham United,emerson,0.609
11,Samuel Amo-Ameyaw,Southampton,samuel edozie,0.600
22,Mads Bech Sørensen,Brentford,mathias jensen,0.581
39,Owen Bevan,Bournemouth,ben pearson,0.571
5,Matthew Craig,Tottenham Hotspur,matt doherty,0.560
40,Joe Whitworth,Crystal Palace,joel ward,0.545
2,Thiago Alcântara,Liverpool,thiago,0.545
32,Lewis Brunt,Leicester City,dennis praet,0.522
34,Luke Harris,Fulham,harry wilson,0.522
42,Kami Doyle,Southampton,samuel edozie,0.522
37,Cameron Peupion,Brighton & Hove Albion,pervis estupinan,0.516
3,Shea Charles,Manchester City,scott carson,0.500
31,Andrew Moran,Brighton & Hove Albion,leandro trossard,0.500
38,Dexter Lembikisa,Wolverhampton,mario lemina,0.500
47,Nathan Redmond,Southampton,adam armstrong,0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mads roerslev',
                    'emerson royal',
                    'bobby decordova reid',
                    'emerson palmieri',
                    'thiago alcantara'
]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 5

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

           player_sf                    team                cg_match  score
28  Halil Dervişoğlu               Brentford           charlie goode  0.483
12     Thomas Cannon                 Everton        nathan patterson  0.483
36   Dominic Ballard             Southampton          romain perraud  0.483
44        Yan Valery             Southampton         willy caballero  0.480
21      Divin Mubama         West Ham United           said benrahma  0.480
25      Mateo Joseph            Leeds United           mateusz klich  0.480
30       Bobby Clark               Liverpool          fabio carvalho  0.480
45     Ethan Nwaneri                 Arsenal           thomas partey  0.462
10       Oriol Romeu             Southampton         tino livramento  0.462
9        Lewis Miley        Newcastle United             jamal lewis  0.455
29  Omari Hutchinson                 Chelsea         gabriel slonina  0.452
20  Jack Hinshelwood  Brighton & Hove Albion             jakub moder  0.444
27    Jay Stansfield                  Fulham      nathaniel chalobah  0.438
48        David Ozoh          Crystal Palace           wilfried zaha  0.435
33   Ben Gannon-Doak               Liverpool  trent alexander arnold  0.432
35         Dele Alli                 Everton              alex iwobi  0.421
13       Isaac Price                 Everton           idrissa gueye  0.417
17       Enock Mwepu  Brighton & Hove Albion           evan ferguson  0.417
26     Kobbie Mainoo       Manchester United            jadon sancho  0.400
43    Odeluga Offiah  Brighton & Hove Albion             solly march  0.400
46     George Abbott       Tottenham Hotspur       rodrigo bentancur  0.400

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 519/554 (93.7%)
Sin salario:     35

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 35

,player,team,minutesPlayed,appearances,goals,assists
0,Ethan Nwaneri,Arsenal,1,1,0,0
1,Owen Bevan,Bournemouth,8,1,0,0
2,Mads Bech Sørensen,Brentford,22,4,0,0
3,Halil Dervişoğlu,Brentford,10,1,0,0
4,Enock Mwepu,Brighton & Hove Albion,216,6,0,1
5,Odeluga Offiah,Brighton & Hove Albion,38,2,0,0
6,Cameron Peupion,Brighton & Hove Albion,14,1,0,0
7,Andrew Moran,Brighton & Hove Albion,11,1,0,0
8,Jack Hinshelwood,Brighton & Hove Albion,8,1,0,0
9,Omari Hutchinson,Chelsea,22,1,0,0
10,Joe Whitworth,Crystal Palace,180,2,0,0
11,David Ozoh,Crystal Palace,1,1,0,0
12,Dele Alli,Everton,38,2,0,0
13,Isaac Price,Everton,32,1,0,0
14,Thomas Cannon,Everton,30,2,0,0
15,Jay Stansfield,Fulham,104,3,0,0
16,Luke Harris,Fulham,23,3,0,0
17,Mateo Joseph,Leeds United,24,3,0,0
18,Lewis Brunt,Leicester City,22,1,0,0
19,Ben Gannon-Doak,Liverpool,24,2,0,0
20,Bobby Clark,Liverpool,12,1,0,0
21,Shea Charles,Manchester City,27,1,0,0
22,Kobbie Mainoo,Manchester United,10,1,0,0
23,Lewis Miley,Newcastle United,14,1,0,0
24,Oriol Romeu,Southampton,75,1,0,0
25,Yan Valery,Southampton,45,1,0,0
26,Dominic Ballard,Southampton,32,2,0,0
27,Kami Doyle,Southampton,14,1,0,0
28,Samuel Amo-Ameyaw,Southampton,11,1,0,0
29,Nathan Redmond,Southampton,1,1,0,0
30,Matthew Craig,Tottenham Hotspur,13,1,0,0
31,Harvey White,Tottenham Hotspur,4,1,0,0
32,George Abbott,Tottenham Hotspur,1,1,0,0
33,Divin Mubama,West Ham United,41,3,0,0
34,Dexter Lembikisa,Wolverhampton,22,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Arsenal  —  SF sin salario:

          player  minutesPlayed
0  Ethan Nwaneri              1

  CG plantilla completa:

                  player           player_norm
0         Aaron Ramsdale        aaron ramsdale
1   Albert Sambi Lokonga  albert sambi lokonga
2              Ben White             ben white
3            Bukayo Saka           bukayo saka
4          Cédric Soares         cedric soares
5          Eddie Nketiah         eddie nketiah
6       Emile Smith Rowe      emile smith rowe
7           Fábio Vieira          fabio vieira
8          Gabriel Jesus         gabriel jesus
9      Gabriel Magalhães     gabriel magalhaes
10    Gabriel Martinelli    gabriel martinelli
11          Granit Xhaka          granit xhaka
12          Jakub Kiwior          jakub kiwior
13              Jorginho              jorginho
14        Kieran Tierney        kieran tierney
15      Leandro Trossard      leandro trossard
16            Marquinhos            marquinhos
17       Martin Ødegaard        martin degaard
18           Matt Turner           matt turner
19        Mohamed Elneny        mohamed elneny
20   Oleksandr Zinchenko   oleksandr zinchenko
21          Reiss Nelson          reiss nelson
22           Rob Holding           rob holding
23     Takehiro Tomiyasu     takehiro tomiyasu
24         Thomas Partey         thomas partey
25        William Saliba        william saliba

============================================================
  Bournemouth  —  SF sin salario:

       player  minutesPlayed
0  Owen Bevan              8

  CG plantilla completa:

                 player          player_norm
0            Adam Smith           adam smith
1       Antoine Semenyo      antoine semenyo
2           Ben Pearson          ben pearson
3          Chris Mepham         chris mepham
4        Dango Ouattara       dango ouattara
5       Darren Randolph      darren randolph
6          David Brooks         david brooks
7       Dominic Solanke      dominic solanke
8    Emiliano Marcondes   emiliano marcondes
9   Hamed Junior Traorè  hamed junior traore
10        Ilya Zabarnyi        ilya zabarnyi
11          Jack Stacey          jack stacey
12        Jack Stephens        jack stephens
13       Jaidon Anthony       jaidon anthony
14           Jamal Lowe           jamal lowe
15           James Hill           james hill
16      Jefferson Lerma      jefferson lerma
17         Joe Rothwell         joe rothwell
18        Jordan Zemura        jordan zemura
19     Junior Stanislas     junior stanislas
20        Kieffer Moore        kieffer moore
21           Lewis Cook           lewis cook
22          Lloyd Kelly          lloyd kelly
23        Marcos Senesi        marcos senesi
24     Marcus Tavernier     marcus tavernier
25         Mark Travers         mark travers
26          Matías Viña          matias vina
27                 Neto                 neto
28       Philip Billing       philip billing
29        Ryan Christie        ryan christie
30      Ryan Fredericks      ryan fredericks
31       Siriki Dembélé       siriki dembele
32          Will Dennis          will dennis

============================================================
  Brentford  —  SF sin salario:

               player  minutesPlayed
0    Halil Dervişoğlu             10
1  Mads Bech Sørensen             22

  CG plantilla completa:

                     player              player_norm
0              Aaron Hickey             aaron hickey
1                   Ben Mee                  ben mee
2              Bryan Mbeumo             bryan mbeumo
3             Charlie Goode            charlie goode
4        Christian Nörgaard       christian norgaard
5                David Raya               david raya
6             Ethan Pinnock            ethan pinnock
7               Fin Stevens              fin stevens
8              Frank Onyeka             frank onyeka
9                Ivan Toney               ivan toney
10          Joshua Da Silva          joshua da silva
11       Keane Lewis-Potter       keane lewis potter
12             Kevin Schade             kevin schade
13          Kristoffer Ajer          kristoffer ajer
14  Mads Roerslev Rasmussen  mads roerslev rasmussen
15           Mathias Jensen           mathias jensen
16         Mikkel Damsgaard         mikkel damsgaard
17           Pontus Jansson           pontus jansson
18               Rico Henry               rico henry
19            Saman Ghoddos            saman ghoddos
20              Sergi Canós              sergi canos
21         Shandon Baptiste         shandon baptiste
22         Thomas Strakosha         thomas strakosha
23            Vitaly Janelt            vitaly janelt
24              Yoane Wissa              yoane wissa
25                    Zanka                    zanka

============================================================
  Brighton & Hove Albion  —  SF sin salario:

             player  minutesPlayed
0      Andrew Moran             11
1   Cameron Peupion             14
2       Enock Mwepu            216
3  Jack Hinshelwood              8
4    Odeluga Offiah             38

  CG plantilla completa:

                 player          player_norm
0          Adam Lallana         adam lallana
1          Adam Webster         adam webster
2   Alexis Mac Allister  alexis mac allister
3         Billy Gilmour        billy gilmour
4         Danny Welbeck        danny welbeck
5           Deniz Undav          deniz undav
6         Evan Ferguson        evan ferguson
7    Facundo Buonanotte   facundo buonanotte
8           Jakub Moder          jakub moder
9    Jan Paul van Hecke   jan paul van hecke
10         Jason Steele         jason steele
11     Jeremy Sarmiento     jeremy sarmiento
12         Joël Veltman         joel veltman
13         Julio Enciso         julio enciso
14         Kaoru Mitoma         kaoru mitoma
15     Leandro Trossard     leandro trossard
16         Levi Colwill         levi colwill
17           Lewis Dunk           lewis dunk
18       Moisés Caicedo       moises caicedo
19          Pascal Groß           pascal gro
20     Pervis Estupiñán     pervis estupinan
21       Robert Sánchez       robert sanchez
22          Solly March          solly march
23        Tariq Lamptey        tariq lamptey
24           Tom McGill           tom mcgill
25          Yasin Ayari          yasin ayari

============================================================
  Chelsea  —  SF sin salario:

             player  minutesPlayed
0  Omari Hutchinson             22

  CG plantilla completa:

                       player                player_norm
0               Armando Broja              armando broja
1                Ben Chilwell               ben chilwell
2           Benoît Badiashile          benoit badiashile
3          Carney Chukwuemeka         carney chukwuemeka
4           César Azpilicueta          cesar azpilicueta
5           Christian Pulisic          christian pulisic
6             Conor Gallagher            conor gallagher
7          David Datro Fofana         david datro fofana
8               Denis Zakaria              denis zakaria
9               Edouard Mendy              edouard mendy
10             Enzo Fernández             enzo fernandez
11            Gabriel Slonina            gabriel slonina
12               Hakim Ziyech               hakim ziyech
13                 João Félix                 joao felix
14                   Jorginho                   jorginho
15                Kai Havertz                kai havertz
16          Kalidou Koulibaly          kalidou koulibaly
17          Kepa Arrizabalaga          kepa arrizabalaga
18                 Lewis Hall                 lewis hall
19             Marc Cucurella             marc cucurella
20          Marcus Bettinelli          marcus bettinelli
21                Mason Mount                mason mount
22              Mateo Kovacic              mateo kovacic
23            Mykhailo Mudryk            mykhailo mudryk
24               N'Golo Kanté               n golo kante
25               Noni Madueke               noni madueke
26  Pierre-Emerick Aubameyang  pierre emerick aubameyang
27            Raheem Sterling            raheem sterling
28                Reece James                reece james
29         Ruben Loftus-Cheek         ruben loftus cheek
30               Thiago Silva               thiago silva
31            Trevoh Chalobah            trevoh chalobah
32              Wesley Fofana              wesley fofana

============================================================
  Crystal Palace  —  SF sin salario:

          player  minutesPlayed
0     David Ozoh              1
1  Joe Whitworth            180

  CG plantilla completa:

                  player           player_norm
0   Albert Sambi Lokonga  albert sambi lokonga
1        Cheick Doucouré       cheick doucoure
2         Chris Richards        chris richards
3           Eberechi Eze          eberechi eze
4           Jack Butland          jack butland
5        Jairo Riedewald       jairo riedewald
6         James McArthur        james mcarthur
7          James Tomkins         james tomkins
8   Jean-Philippe Mateta  jean philippe mateta
9        Jeffrey Schlupp       jeffrey schlupp
10      Joachim Andersen      joachim andersen
11             Joel Ward             joel ward
12           Jordan Ayew           jordan ayew
13      Luka Milivojevic      luka milivojevic
14       Malcolm Ebiowei       malcolm ebiowei
15            Marc Guéhi            marc guehi
16         Michael Olise         michael olise
17      Naouirou Ahamada      naouirou ahamada
18       Nathan Ferguson       nathan ferguson
19       Nathaniel Clyne       nathaniel clyne
20       Odsonne Edouard       odsonne edouard
21         Sam Johnstone         sam johnstone
22       Tyrick Mitchell       tyrick mitchell
23        Vicente Guaita        vicente guaita
24         Wilfried Zaha         wilfried zaha
25           Will Hughes           will hughes

============================================================
  Everton  —  SF sin salario:

          player  minutesPlayed
0      Dele Alli             38
1    Isaac Price             32
2  Thomas Cannon             30

  CG plantilla completa:

                   player            player_norm
0      Abdoulaye Doucouré     abdoulaye doucoure
1              Alex Iwobi             alex iwobi
2            Amadou Onana           amadou onana
3         Andros Townsend        andros townsend
4           Andy Lonergan          andy lonergan
5          Anthony Gordon         anthony gordon
6           Asmir Begovic          asmir begovic
7             Ben Godfrey            ben godfrey
8             Conor Coady            conor coady
9            Demarai Gray           demarai gray
10  Dominic Calvert-Lewin  dominic calvert lewin
11          Dwight McNeil          dwight mcneil
12        Eldin Jakupovic        eldin jakupovic
13            Ellis Simms            ellis simms
14          Idrissa Gueye          idrissa gueye
15           James Garner           james garner
16        James Tarkowski        james tarkowski
17        Jordan Pickford        jordan pickford
18          Mason Holgate          mason holgate
19          Michael Keane          michael keane
20       Nathan Patterson       nathan patterson
21            Neal Maupay            neal maupay
22          Rúben Vinagre          ruben vinagre
23         Salomón Rondón         salomon rondon
24         Seamus Coleman         seamus coleman
25             Tom Davies             tom davies
26      Vitaliy Mykolenko      vitaliy mykolenko
27             Yerry Mina             yerry mina

============================================================
  Fulham  —  SF sin salario:

           player  minutesPlayed
0  Jay Stansfield            104
1     Luke Harris             23

  CG plantilla completa:

                 player          player_norm
0   Aleksandar Mitrovic  aleksandar mitrovic
1       Andreas Pereira      andreas pereira
2      Antonee Robinson     antonee robinson
3            Bernd Leno           bernd leno
4            Bobby Reid           bobby reid
5       Carlos Vinícius      carlos vinicius
6         Cédric Soares        cedric soares
7          Daniel James         daniel james
8         Harrison Reed        harrison reed
9          Harry Wilson         harry wilson
10            Issa Diop            issa diop
11        João Palhinha        joao palhinha
12          Josh Onomah          josh onomah
13           Kenny Tete           kenny tete
14          Kevin Mbabu          kevin mbabu
15       Layvin Kurzawa       layvin kurzawa
16        Manor Solomon        manor solomon
17          Marek Rodak          marek rodak
18   Nathaniel Chalobah   nathaniel chalobah
19      Neeskens Kebano      neeskens kebano
20           Sasa Lukic           sasa lukic
21          Shane Duffy          shane duffy
22             Tim Ream             tim ream
23          Tom Cairney          tom cairney
24     Tosin Adarabioyo     tosin adarabioyo
25      Tyrese Francois      tyrese francois
26              Willian              willian

============================================================
  Leeds United  —  SF sin salario:

         player  minutesPlayed
0  Mateo Joseph             24

  CG plantilla completa:

                   player            player_norm
0            Adam Forshaw           adam forshaw
1        Brenden Aaronson       brenden aaronson
2             Cody Drameh            cody drameh
3   Crysencio Summerville  crysencio summerville
4             Darko Gyabi            darko gyabi
5          Diego Llorente         diego llorente
6        Georginio Rutter       georginio rutter
7           Illan Meslier          illan meslier
8           Jack Harrison          jack harrison
9            Joe Gelhardt           joe gelhardt
10            Joel Robles            joel robles
11           Junior Firpo           junior firpo
12    Kristoffer Klaesson    kristoffer klaesson
13        Leo Fuhr Hjelde        leo fuhr hjelde
14            Liam Cooper            liam cooper
15        Luis Sinisterra        luis sinisterra
16            Luke Ayling            luke ayling
17              Marc Roca              marc roca
18          Mateusz Klich          mateusz klich
19       Maximilian Wöber       maximilian wober
20         Pascal Struijk         pascal struijk
21        Patrick Bamford        patrick bamford
22      Rasmus Kristensen      rasmus kristensen
23             Robin Koch             robin koch
24                Rodrigo                rodrigo
25          Sam Greenwood          sam greenwood
26          Stuart Dallas          stuart dallas
27            Tyler Adams            tyler adams
28        Weston McKennie        weston mckennie
29        Wilfried Gnonto        wilfried gnonto

============================================================
  Leicester City  —  SF sin salario:

        player  minutesPlayed
0  Lewis Brunt             22

  CG plantilla completa:

                   player            player_norm
0           Alex Smithies          alex smithies
1             Ayoze Pérez            ayoze perez
2       Boubakary Soumaré      boubakary soumare
3          Caglar Söyüncü         caglar soyuncu
4          Daniel Amartey         daniel amartey
5          Daniel Iversen         daniel iversen
6              Danny Ward             danny ward
7            Dennis Praet           dennis praet
8           Harry Souttar          harry souttar
9           Harvey Barnes          harvey barnes
10           James Justin           james justin
11         James Maddison         james maddison
12            Jamie Vardy            jamie vardy
13     Jannik Vestergaard     jannik vestergaard
14            Jonny Evans            jonny evans
15      Kelechi Iheanacho      kelechi iheanacho
16  Kiernan Dewsbury-Hall  kiernan dewsbury hall
17            Luke Thomas            luke thomas
18        Marc Albrighton        marc albrighton
19         Nampalys Mendy         nampalys mendy
20            Patson Daka            patson daka
21        Ricardo Pereira        ricardo pereira
22          Ryan Bertrand          ryan bertrand
23                   Tetê                   tete
24       Timothy Castagne       timothy castagne
25     Victor Kristiansen     victor kristiansen
26          Wilfred Ndidi          wilfred ndidi
27              Wout Faes              wout faes
28        Youri Tielemans        youri tielemans

============================================================
  Liverpool  —  SF sin salario:

            player  minutesPlayed
0  Ben Gannon-Doak             24
1      Bobby Clark             12

  CG plantilla completa:

                     player              player_norm
0                    Adrián                   adrian
1   Alex Oxlade-Chamberlain  alex oxlade chamberlain
2                   Alisson                  alisson
3          Andrew Robertson         andrew robertson
4                    Arthur                   arthur
5             Calvin Ramsay            calvin ramsay
6         Caoimhín Kelleher        caoimhin kelleher
7                Cody Gakpo               cody gakpo
8              Curtis Jones             curtis jones
9              Darwin Núñez             darwin nunez
10               Diogo Jota               diogo jota
11                  Fabinho                  fabinho
12           Fábio Carvalho           fabio carvalho
13           Harvey Elliott           harvey elliott
14          Ibrahima Konaté          ibrahima konate
15             James Milner             james milner
16                Joe Gomez                joe gomez
17               Joel Matip               joel matip
18         Jordan Henderson         jordan henderson
19    Konstantinos Tsimikas    konstantinos tsimikas
20                Luis Díaz                luis diaz
21            Mohamed Salah            mohamed salah
22               Naby Keïta               naby keita
23       Nathaniel Phillips       nathaniel phillips
24            Rhys Williams            rhys williams
25          Roberto Firmino          roberto firmino
26          Stefan Bajcetic          stefan bajcetic
27                   Thiago                   thiago
28   Trent Alexander-Arnold   trent alexander arnold
29          Virgil van Dijk          virgil van dijk

============================================================
  Manchester City  —  SF sin salario:

         player  minutesPlayed
0  Shea Charles             27

  CG plantilla completa:

                  player           player_norm
0        Aymeric Laporte       aymeric laporte
1         Benjamin Mendy        benjamin mendy
2         Bernardo Silva        bernardo silva
3            Cole Palmer           cole palmer
4                Ederson               ederson
5         Erling Haaland        erling haaland
6         Ilkay Gündogan        ilkay gundogan
7          Jack Grealish         jack grealish
8           João Cancelo          joao cancelo
9            John Stones           john stones
10        Julián Álvarez        julian alvarez
11       Kalvin Phillips       kalvin phillips
12       Kevin De Bruyne       kevin de bruyne
13           Kyle Walker           kyle walker
14         Manuel Akanji         manuel akanji
15        Máximo Perrone        maximo perrone
16            Nathan Aké            nathan ake
17            Phil Foden            phil foden
18            Rico Lewis            rico lewis
19          Riyad Mahrez          riyad mahrez
20                 Rodri                 rodri
21            Rúben Dias            ruben dias
22          Scott Carson          scott carson
23          Sergio Gómez          sergio gomez
24  Stefan Ortega Moreno  stefan ortega moreno

============================================================
  Manchester United  —  SF sin salario:

          player  minutesPlayed
0  Kobbie Mainoo             10

  CG plantilla completa:

                player         player_norm
0    Aaron Wan-Bissaka   aaron wan bissaka
1   Alejandro Garnacho  alejandro garnacho
2          Alex Telles         alex telles
3       Anthony Elanga      anthony elanga
4      Anthony Martial     anthony martial
5               Antony              antony
6        Axel Tuanzebe       axel tuanzebe
7     Brandon Williams    brandon williams
8      Bruno Fernandes     bruno fernandes
9             Casemiro            casemiro
10   Christian Eriksen   christian eriksen
11   Cristiano Ronaldo   cristiano ronaldo
12        David de Gea        david de gea
13         Diogo Dalot         diogo dalot
14   Donny van de Beek   donny van de beek
15   Facundo Pellistri   facundo pellistri
16                Fred                fred
17       Harry Maguire       harry maguire
18        Jack Butland        jack butland
19        Jadon Sancho        jadon sancho
20   Lisandro Martínez   lisandro martinez
21           Luke Shaw           luke shaw
22     Marcel Sabitzer     marcel sabitzer
23     Marcus Rashford     marcus rashford
24     Martin Dubravka     martin dubravka
25     Mason Greenwood     mason greenwood
26          Phil Jones          phil jones
27      Raphaël Varane      raphael varane
28     Scott McTominay     scott mctominay
29     Shola Shoretire     shola shoretire
30         Teden Mengi         teden mengi
31          Tom Heaton          tom heaton
32      Tyrell Malacia      tyrell malacia
33     Victor Lindelöf     victor lindelof
34       Wout Weghorst       wout weghorst

============================================================
  Newcastle United  —  SF sin salario:

        player  minutesPlayed
0  Lewis Miley             14

  CG plantilla completa:

                 player          player_norm
0        Alexander Isak       alexander isak
1   Allan Saint-Maximin  allan saint maximin
2        Anthony Gordon       anthony gordon
3       Bruno Guimarães      bruno guimaraes
4         Callum Wilson        callum wilson
5            Chris Wood           chris wood
6              Dan Burn             dan burn
7       Elliot Anderson      elliot anderson
8           Emil Krafth          emil krafth
9          Fabian Schär         fabian schar
10       Harrison Ashby       harrison ashby
11         Jacob Murphy         jacob murphy
12     Jamaal Lascelles     jamaal lascelles
13          Jamal Lewis          jamal lewis
14     Javier Manquillo     javier manquillo
15          Joe Willock          joe willock
16            Joelinton            joelinton
17        Jonjo Shelvey        jonjo shelvey
18          Karl Darlow          karl darlow
19      Kieran Trippier      kieran trippier
20         Loris Karius         loris karius
21       Mark Gillespie       mark gillespie
22      Martin Dubravka      martin dubravka
23         Matt Ritchie         matt ritchie
24         Matt Targett         matt targett
25    Matthew Longstaff    matthew longstaff
26       Miguel Almirón       miguel almiron
27            Nick Pope            nick pope
28         Paul Dummett         paul dummett
29          Ryan Fraser          ryan fraser
30       Sean Longstaff       sean longstaff
31          Sven Botman          sven botman

============================================================
  Southampton  —  SF sin salario:

              player  minutesPlayed
0    Dominic Ballard             32
1         Kami Doyle             14
2     Nathan Redmond              1
3        Oriol Romeu             75
4  Samuel Amo-Ameyaw             11
5         Yan Valery             45

  CG plantilla completa:

                    player             player_norm
0           Adam Armstrong          adam armstrong
1   Ainsley Maitland-Niles  ainsley maitland niles
2            Alex McCarthy           alex mccarthy
3      Armel Bella-Kotchap     armel bella kotchap
4           Carlos Alcaraz          carlos alcaraz
5                Ché Adams               che adams
6          Duje Caleta-Car         duje caleta car
7             Gavin Bazunu            gavin bazunu
8          Ibrahima Diallo         ibrahima diallo
9               James Bree              james bree
10       James Ward-Prowse       james ward prowse
11            Jan Bednarek            jan bednarek
12               Joe Aribo               joe aribo
13             Juan Larios             juan larios
14      Kamaldeen Sulemana      kamaldeen sulemana
15      Kyle Walker-Peters      kyle walker peters
16                  Lyanco                  lyanco
17            Mislav Orsic            mislav orsic
18     Mohamed Elyounoussi     mohamed elyounoussi
19         Mohammed Salisu         mohammed salisu
20          Moussa Djenepo          moussa djenepo
21            Paul Onuachu            paul onuachu
22          Romain Perraud          romain perraud
23             Roméo Lavia             romeo lavia
24           Samuel Edozie           samuel edozie
25              Sékou Mara              sekou mara
26        Stuart Armstrong        stuart armstrong
27            Theo Walcott            theo walcott
28         Tino Livramento         tino livramento
29         Willy Caballero         willy caballero

============================================================
  Tottenham Hotspur  —  SF sin salario:

          player  minutesPlayed
0  George Abbott              1
1   Harvey White              4
2  Matthew Craig             13

  CG plantilla completa:

                   player            player_norm
0          Alfie Whiteman         alfie whiteman
1          Arnaut Danjuma         arnaut danjuma
2              Ben Davies             ben davies
3          Brandon Austin         brandon austin
4               Bryan Gil              bryan gil
5         Clément Lenglet        clement lenglet
6         Cristian Romero        cristian romero
7        Davinson Sánchez       davinson sanchez
8        Dejan Kulusevski       dejan kulusevski
9             Djed Spence            djed spence
10                Emerson                emerson
11              Eric Dier              eric dier
12         Fraser Forster         fraser forster
13             Harry Kane             harry kane
14          Heung-min Son          heung min son
15            Hugo Lloris            hugo lloris
16           Ivan Perisic           ivan perisic
17        Japhet Tanganga        japhet tanganga
18            Lucas Moura            lucas moura
19           Matt Doherty           matt doherty
20           Oliver Skipp           oliver skipp
21              Pape Sarr              pape sarr
22            Pedro Porro            pedro porro
23  Pierre-Emile Höjbjerg  pierre emile hojbjerg
24            Richarlison            richarlison
25      Rodrigo Bentancur      rodrigo bentancur
26         Ryan Sessegnon         ryan sessegnon
27        Sergio Reguilón        sergio reguilon
28          Yves Bissouma          yves bissouma

============================================================
  West Ham United  —  SF sin salario:

         player  minutesPlayed
0  Divin Mubama             41

  CG plantilla completa:

               player        player_norm
0     Aaron Cresswell    aaron cresswell
1     Alphonse Areola    alphonse areola
2      Angelo Ogbonna     angelo ogbonna
3         Ben Johnson        ben johnson
4      Conor Coventry     conor coventry
5        Craig Dawson       craig dawson
6          Danny Ings         danny ings
7     Darren Randolph    darren randolph
8         Declan Rice        declan rice
9             Emerson            emerson
10       Flynn Downes       flynn downes
11  Gianluca Scamacca  gianluca scamacca
12       Jarrod Bowen       jarrod bowen
13         Kurt Zouma         kurt zouma
14      Lucas Paquetá      lucas paqueta
15   Lukasz Fabianski   lukasz fabianski
16     Manuel Lanzini     manuel lanzini
17      Maxwel Cornet      maxwel cornet
18    Michail Antonio    michail antonio
19       Nayef Aguerd       nayef aguerd
20      Pablo Fornals      pablo fornals
21      Saïd Benrahma      said benrahma
22       Thilo Kehrer       thilo kehrer
23       Tomas Soucek       tomas soucek
24    Vladimir Coufal    vladimir coufal

============================================================
  Wolverhampton  —  SF sin salario:

             player  minutesPlayed
0  Dexter Lembikisa             22

  CG plantilla completa:

             player      player_norm
0      Adama Traoré     adama traore
1   Boubacar Traoré  boubacar traore
2     Chem Campbell    chem campbell
3         Chiquinho        chiquinho
4      Connor Ronan     connor ronan
5      Craig Dawson     craig dawson
6    Daniel Bentley   daniel bentley
7    Daniel Podence   daniel podence
8       Diego Costa      diego costa
9    Gonçalo Guedes   goncalo guedes
10   Hee-chan Hwang   hee chan hwang
11       Hugo Bueno       hugo bueno
12       João Gomes       joao gomes
13    João Moutinho    joao moutinho
14        Joe Hodge        joe hodge
15       Jonny Otto       jonny otto
16          José Sá          jose sa
17     Léo Bonatini     leo bonatini
18    Louie Moulden    louie moulden
19     Mario Lemina     mario lemina
20    Matheus Cunha    matheus cunha
21    Matheus Nunes    matheus nunes
22    Matija Sarkic    matija sarkic
23       Max Kilman       max kilman
24   Nathan Collins   nathan collins
25    Nélson Semedo    nelson semedo
26    Pablo Sarabia    pablo sarabia
27       Pedro Neto       pedro neto
28     Raúl Jiménez     raul jimenez
29  Rayan Aït-Nouri  rayan ait nouri
30      Rúben Neves      ruben neves
31   Sasa Kalajdzic   sasa kalajdzic
32       Toti Gomes       toti gomes
33  Yerson Mosquera  yerson mosquera

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 519/554 (93.7%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_england_2223.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_england_2223.csv
   Jugadores totales:  554
   Con salario:        519
   Sin salario (NaN):  35
   Columnas:           121