# 03 · Join Sofascore + Capology — England Premier League 21/22

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2021/22 de Premier League inglesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_england_2122.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_england_2122.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  538 jugadores | 116 columnas
Capology:   562 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   brighton hove albion
   leeds united
   leicester city
   newcastle united
   norwich city
   tottenham hotspur
   west ham united

En Capology pero no en Sofascore:
   brighton
   leeds
   leicester
   newcastle
   norwich
   tottenham
   west ham

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brighton':'brighton hove albion',
            'leeds':'leeds united',
            'leicester':'leicester city',
            'newcastle':'newcastle united',
            'norwich':'norwich city',
            'tottenham':'tottenham hotspur',
            'west ham':'west ham united'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 480/538 (89.2%)
Sin emparejar: 58

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          8
Revisión media    (0.75 ≤ score < 0.90):   4
Revisión estricta (0.50 ≤ score < 0.75):   20
Revisión muy est. (score < 0.50):           26

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf               team               cg_match  score
0   Pierre-Emile Højbjerg  Tottenham Hotspur  pierre emile hojbjerg  0.976
17   Jacob Lungi Sørensen       Norwich City   jacob lungi sorensen  0.974
14     Mads Bech Sørensen          Brentford     mads bech sorensen  0.971
2      Christian Nørgaard          Brentford     christian norgaard  0.971
4        Łukasz Fabiański    West Ham United       lukasz fabianski  0.968
44         Joshua Dasilva          Brentford        joshua da silva  0.966
24    Przemysław Płacheta       Norwich City    przemyslaw placheta  0.944
16      Andriy Yarmolenko    West Ham United      andrii yarmolenko  0.941

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf         team                 cg_match  score
6   Valentino Livramento  Southampton          tino livramento  0.857
18    Jóhann Guðmundsson      Burnley  johann berg gudmundsson  0.850
7         Edward Nketiah      Arsenal            eddie nketiah  0.815
8      Tariqe Fosu-Henry    Brentford              tariqe fosu  0.786

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 4 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf               team                 cg_match  score
25       Mads Roerslev          Brentford  mads roerslev rasmussen  0.722
5        Emerson Royal  Tottenham Hotspur                  emerson  0.700
50          Moise Kean            Everton            michael keane  0.696
27   Mahmoud Trézéguet        Aston Villa                trezeguet  0.692
38  Alejandro Garnacho  Manchester United             jadon sancho  0.667
12         Troy Deeney            Watford            tom cleverley  0.583
11   Francisco Trincão      Wolverhampton                  trincao  0.583
40      Cameron Archer        Aston Villa           calum chambers  0.571
46        Kaide Gordon          Liverpool         andrew robertson  0.571
15       Samir Caetano            Watford                    samir  0.556
30    Stuart McKinstry       Leeds United            stuart dallas  0.552
41        Lewis Dobbin            Everton               alex iwobi  0.545
1     Thiago Alcântara          Liverpool                   thiago  0.545
42      Tony Springett       Norwich City             josh sargent  0.538
55       Kasey McAteer     Leicester City        kasper schmeichel  0.533
57        Dan Chesters    West Ham United              declan rice  0.522
37       Tyler Onyango            Everton               yerry mina  0.522
39        James McAtee    Manchester City          aymeric laporte  0.519
32        Tyler Morton          Liverpool         andrew robertson  0.500
51       Dane Scarlett  Tottenham Hotspur              jack clarke  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mads roerslev',
                    'emerson royal',
                    'mahmoud trezeguet',
                    'francisco trincao',
                    'samir caetano',
                    'thiago alcantara'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 6

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                  player_sf                    team            cg_match  score
52         Emerson Palmieri                 Chelsea   christian pulisic  0.485
56     Nathan Young-Coombes               Brentford       saman ghoddos  0.485
22           Harrison Ashby         West Ham United     darren randolph  0.483
53            Wesley Moraes             Aston Villa        ashley young  0.480
29            Sonny Perkins         West Ham United        winston reid  0.480
26            Jonathan Rowe            Norwich City        grant hanley  0.480
3                Liam Delap         Manchester City     aymeric laporte  0.480
13             Hélder Costa            Leeds United       tyler roberts  0.480
28            Evan Ferguson  Brighton & Hove Albion            dan burn  0.476
10           Tim Iroegbunam             Aston Villa    emiliano buendia  0.467
35          Hannibal Mejbri       Manchester United     anthony martial  0.467
33         Jeremy Sarmiento  Brighton & Hove Albion      kjell scherpen  0.467
49             Nohan Kenneh            Leeds United          robin koch  0.455
19             Reiss Nelson                 Arsenal     folarin balogun  0.444
21              Ellis Simms                 Everton    gylfi sigurdsson  0.444
43              Cody Drameh            Leeds United        daniel james  0.435
34              Lewis Brunt          Leicester City        james justin  0.435
47               Lewis Bate            Leeds United       tyler roberts  0.435
54  Conrad Jaden Egan-Riley         Manchester City      benjamin mendy  0.432
36        Jesurun Rak-Sakyi          Crystal Palace         jordan ayew  0.429
20          Shola Shoretire       Manchester United       harry maguire  0.429
31       Morgan Gibbs-White           Wolverhampton     rayan ait nouri  0.424
45   Jaden Philogene-Bidace             Aston Villa         leon bailey  0.424
23            Chem Campbell           Wolverhampton              marcal  0.421
9           Leo Fuhr Hjelde            Leeds United      diego llorente  0.414
48              Isaac Price                 Everton  jarrad branthwaite  0.414

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 498/538 (92.6%)
Sin salario:     40

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 40

,player,team,minutesPlayed,appearances,goals,assists
0,Reiss Nelson,Arsenal,19,1,0,0
1,Tim Iroegbunam,Aston Villa,95,3,0,0
2,Cameron Archer,Aston Villa,30,3,0,0
3,Jaden Philogene-Bidace,Aston Villa,11,1,0,0
4,Wesley Moraes,Aston Villa,1,1,0,0
5,Nathan Young-Coombes,Brentford,3,1,0,0
6,Jeremy Sarmiento,Brighton & Hove Albion,56,5,0,0
7,Evan Ferguson,Brighton & Hove Albion,22,1,0,0
8,Emerson Palmieri,Chelsea,4,1,0,0
9,Jesurun Rak-Sakyi,Crystal Palace,81,2,0,0
10,Ellis Simms,Everton,62,1,0,0
11,Lewis Dobbin,Everton,30,3,0,0
12,Tyler Onyango,Everton,27,3,0,0
13,Isaac Price,Everton,12,1,0,0
14,Moise Kean,Everton,1,1,0,0
15,Leo Fuhr Hjelde,Leeds United,148,2,0,0
16,Lewis Bate,Leeds United,147,3,0,0
17,Cody Drameh,Leeds United,126,3,0,0
18,Hélder Costa,Leeds United,20,1,0,0
19,Stuart McKinstry,Leeds United,8,1,0,0
20,Nohan Kenneh,Leeds United,0,0,0,0
21,Lewis Brunt,Leicester City,23,1,0,0
22,Kasey McAteer,Leicester City,2,1,0,0
23,Tyler Morton,Liverpool,70,2,0,0
24,Kaide Gordon,Liverpool,8,1,0,0
25,James McAtee,Manchester City,18,2,0,0
26,Liam Delap,Manchester City,9,1,0,0
27,Conrad Jaden Egan-Riley,Manchester City,3,1,0,0
28,Hannibal Mejbri,Manchester United,72,2,0,0
29,Shola Shoretire,Manchester United,15,1,0,0
30,Alejandro Garnacho,Manchester United,12,2,0,0
31,Jonathan Rowe,Norwich City,226,13,0,1
32,Tony Springett,Norwich City,141,3,0,0
33,Dane Scarlett,Tottenham Hotspur,3,1,0,0
34,Troy Deeney,Watford,23,2,0,0
35,Harrison Ashby,West Ham United,12,1,0,0
36,Sonny Perkins,West Ham United,8,1,0,0
37,Dan Chesters,West Ham United,1,1,0,0
38,Morgan Gibbs-White,Wolverhampton,18,2,0,0
39,Chem Campbell,Wolverhampton,12,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Arsenal  —  SF sin salario:

         player  minutesPlayed
0  Reiss Nelson             19

  CG plantilla completa:

                       player                player_norm
0              Aaron Ramsdale             aaron ramsdale
1      Ainsley Maitland-Niles     ainsley maitland niles
2        Albert Sambi Lokonga       albert sambi lokonga
3         Alexandre Lacazette        alexandre lacazette
4              Arthur Okonkwo             arthur okonkwo
5                   Ben White                  ben white
6                  Bernd Leno                 bernd leno
7                 Bukayo Saka                bukayo saka
8              Calum Chambers             calum chambers
9               Cédric Soares              cedric soares
10              Eddie Nketiah              eddie nketiah
11           Emile Smith Rowe           emile smith rowe
12            Folarin Balogun            folarin balogun
13          Gabriel Magalhães          gabriel magalhaes
14         Gabriel Martinelli         gabriel martinelli
15               Granit Xhaka               granit xhaka
16             Kieran Tierney             kieran tierney
17            Martin Ødegaard             martin degaard
18             Mohamed Elneny             mohamed elneny
19               Nicolas Pépé               nicolas pepe
20               Nuno Tavares               nuno tavares
21                 Pablo Marí                 pablo mari
22  Pierre-Emerick Aubameyang  pierre emerick aubameyang
23                Rob Holding                rob holding
24             Sead Kolasinac             sead kolasinac
25          Takehiro Tomiyasu          takehiro tomiyasu
26              Thomas Partey              thomas partey

============================================================
  Aston Villa  —  SF sin salario:

                   player  minutesPlayed
0          Cameron Archer             30
1  Jaden Philogene-Bidace             11
2          Tim Iroegbunam             95
3           Wesley Moraes              1

  CG plantilla completa:

                player         player_norm
0       Anwar El Ghazi      anwar el ghazi
1         Ashley Young        ashley young
2        Axel Tuanzebe       axel tuanzebe
3      Bertrand Traoré     bertrand traore
4       Calum Chambers      calum chambers
5   Carney Chukwuemeka  carney chukwuemeka
6           Danny Ings          danny ings
7         Douglas Luiz        douglas luiz
8     Emiliano Buendía    emiliano buendia
9    Emiliano Martínez   emiliano martinez
10          Ezri Konsa          ezri konsa
11        Jacob Ramsey        jacob ramsey
12           Jed Steer           jed steer
13         John McGinn         john mcginn
14        Keinan Davis        keinan davis
15       Kortney Hause       kortney hause
16         Leon Bailey         leon bailey
17         Lucas Digne         lucas digne
18   Marvelous Nakamba   marvelous nakamba
19        Matt Targett        matt targett
20          Matty Cash          matty cash
21       Morgan Sanson       morgan sanson
22       Ollie Watkins       ollie watkins
23   Philippe Coutinho   philippe coutinho
24         Robin Olsen         robin olsen
25           Trezeguet           trezeguet
26        Tyrone Mings        tyrone mings

============================================================
  Brentford  —  SF sin salario:

                 player  minutesPlayed
0  Nathan Young-Coombes              3

  CG plantilla completa:

                     player              player_norm
0          Álvaro Fernández         alvaro fernandez
1              Bryan Mbeumo             bryan mbeumo
2             Charlie Goode            charlie goode
3         Christian Eriksen        christian eriksen
4        Christian Nörgaard       christian norgaard
5                David Raya               david raya
6          Dominic Thompson         dominic thompson
7           Ellery Balcombe          ellery balcombe
8             Ethan Pinnock            ethan pinnock
9               Fin Stevens              fin stevens
10             Frank Onyeka             frank onyeka
11               Ivan Toney               ivan toney
12             Jan Zamburek             jan zamburek
13            Joel Valencia            joel valencia
14              Jonas Lössl              jonas lossl
15          Joshua Da Silva          joshua da silva
16          Julian Jeanvier          julian jeanvier
17          Kristoffer Ajer          kristoffer ajer
18               Luka Racic               luka racic
19       Mads Bech Sörensen       mads bech sorensen
20            Mads Bidstrup            mads bidstrup
21  Mads Roerslev Rasmussen  mads roerslev rasmussen
22             Marcus Forss             marcus forss
23           Mathias Jensen           mathias jensen
24       Myles Peart-Harris       myles peart harris
25           Pontus Jansson           pontus jansson
26               Rico Henry               rico henry
27            Saman Ghoddos            saman ghoddos
28              Sergi Canós              sergi canos
29         Shandon Baptiste         shandon baptiste
30              Tariqe Fosu              tariqe fosu
31            Vitaly Janelt            vitaly janelt
32              Yoane Wissa              yoane wissa
33                    Zanka                    zanka

============================================================
  Brighton & Hove Albion  —  SF sin salario:

             player  minutesPlayed
0     Evan Ferguson             22
1  Jeremy Sarmiento             56

  CG plantilla completa:

                 player          player_norm
0        Aaron Connolly       aaron connolly
1          Adam Lallana         adam lallana
2          Adam Webster         adam webster
3   Alexis Mac Allister  alexis mac allister
4            Billy Arce           billy arce
5              Dan Burn             dan burn
6         Danny Welbeck        danny welbeck
7           Enock Mwepu          enock mwepu
8        Haydon Roberts       haydon roberts
9           Jakub Moder          jakub moder
10         Jason Steele         jason steele
11         Joël Veltman         joel veltman
12       Jürgen Locadia       jurgen locadia
13       Kjell Scherpen       kjell scherpen
14     Leandro Trossard     leandro trossard
15           Lewis Dunk           lewis dunk
16       Marc Cucurella       marc cucurella
17       Moisés Caicedo       moises caicedo
18          Neal Maupay          neal maupay
19          Pascal Groß           pascal gro
20       Robert Sánchez       robert sanchez
21          Shane Duffy          shane duffy
22          Solly March          solly march
23        Steven Alzate        steven alzate
24        Tariq Lamptey        tariq lamptey
25      Taylor Richards      taylor richards
26         Tudor Baluta         tudor baluta
27        Yves Bissouma        yves bissouma

============================================================
  Chelsea  —  SF sin salario:

             player  minutesPlayed
0  Emerson Palmieri              4

  CG plantilla completa:

                 player          player_norm
0   Andreas Christensen  andreas christensen
1       Antonio Rüdiger      antonio rudiger
2          Ben Chilwell         ben chilwell
3    Callum Hudson-Odoi   callum hudson odoi
4     César Azpilicueta    cesar azpilicueta
5     Charly Musonda Jr    charly musonda jr
6     Christian Pulisic    christian pulisic
7         Edouard Mendy        edouard mendy
8          Hakim Ziyech         hakim ziyech
9              Jorginho             jorginho
10          Kai Havertz          kai havertz
11               Kenedy               kenedy
12    Kepa Arrizabalaga    kepa arrizabalaga
13          Lewis Baker          lewis baker
14          Malang Sarr          malang sarr
15        Marcos Alonso        marcos alonso
16    Marcus Bettinelli    marcus bettinelli
17          Mason Mount          mason mount
18        Mateo Kovacic        mateo kovacic
19         N'Golo Kanté         n golo kante
20          Reece James          reece james
21        Romelu Lukaku        romelu lukaku
22         Ross Barkley         ross barkley
23   Ruben Loftus-Cheek   ruben loftus cheek
24          Saúl Ñíguez          saul niguez
25         Thiago Silva         thiago silva
26          Timo Werner          timo werner
27      Trevoh Chalobah      trevoh chalobah

============================================================
  Crystal Palace  —  SF sin salario:

              player  minutesPlayed
0  Jesurun Rak-Sakyi             81

  CG plantilla completa:

                  player           player_norm
0       Cheikhou Kouyaté      cheikhou kouyate
1      Christian Benteke     christian benteke
2        Conor Gallagher       conor gallagher
3           Eberechi Eze          eberechi eze
4           Jack Butland          jack butland
5        Jairo Riedewald       jairo riedewald
6         James McArthur        james mcarthur
7          James Tomkins         james tomkins
8          Jaroslaw Jach         jaroslaw jach
9   Jean-Philippe Mateta  jean philippe mateta
10       Jeffrey Schlupp       jeffrey schlupp
11      Joachim Andersen      joachim andersen
12             Joel Ward             joel ward
13           Jordan Ayew           jordan ayew
14      Luka Milivojevic      luka milivojevic
15            Marc Guehi            marc guehi
16          Martin Kelly          martin kelly
17         Michael Olise         michael olise
18       Nathan Ferguson       nathan ferguson
19       Nathaniel Clyne       nathaniel clyne
20       Odsonne Edouard       odsonne edouard
21         Remi Matthews         remi matthews
22       Tyrick Mitchell       tyrick mitchell
23        Vicente Guaita        vicente guaita
24         Wilfried Zaha         wilfried zaha
25           Will Hughes           will hughes

============================================================
  Everton  —  SF sin salario:

          player  minutesPlayed
0    Ellis Simms             62
1    Isaac Price             12
2   Lewis Dobbin             30
3     Moise Kean              1
4  Tyler Onyango             27

  CG plantilla completa:

                   player            player_norm
0      Abdoulaye Doucouré     abdoulaye doucoure
1              Alex Iwobi             alex iwobi
2                   Allan                  allan
3             André Gomes            andre gomes
4         Andros Townsend        andros townsend
5           Andy Lonergan          andy lonergan
6          Anthony Gordon         anthony gordon
7          Anwar El Ghazi         anwar el ghazi
8           Asmir Begovic          asmir begovic
9             Ben Godfrey            ben godfrey
10             Cenk Tosun             cenk tosun
11              Dele Alli              dele alli
12           Demarai Gray           demarai gray
13  Dominic Calvert-Lewin  dominic calvert lewin
14      Donny van de Beek      donny van de beek
15           Fabian Delph           fabian delph
16       Gylfi Sigurdsson       gylfi sigurdsson
17     Jarrad Branthwaite     jarrad branthwaite
18   Jean-Philippe Gbamin   jean philippe gbamin
19           Jonjoe Kenny           jonjoe kenny
20        Jordan Pickford        jordan pickford
21            Lucas Digne            lucas digne
22          Mason Holgate          mason holgate
23          Michael Keane          michael keane
24       Nathan Patterson       nathan patterson
25            Richarlison            richarlison
26         Salomón Rondón         salomon rondon
27         Seamus Coleman         seamus coleman
28             Tom Davies             tom davies
29      Vitaliy Mykolenko      vitaliy mykolenko
30             Yerry Mina             yerry mina

============================================================
  Leeds United  —  SF sin salario:

             player  minutesPlayed
0       Cody Drameh            126
1      Hélder Costa             20
2   Leo Fuhr Hjelde            148
3        Lewis Bate            147
4      Nohan Kenneh              0
5  Stuart McKinstry              8

  CG plantilla completa:

                   player            player_norm
0            Adam Forshaw           adam forshaw
1       Charlie Cresswell      charlie cresswell
2   Crysencio Summerville  crysencio summerville
3            Daniel James           daniel james
4          Diego Llorente         diego llorente
5           Illan Meslier          illan meslier
6           Jack Harrison          jack harrison
7        Jamie Shackleton       jamie shackleton
8            Joe Gelhardt           joe gelhardt
9            Junior Firpo           junior firpo
10        Kalvin Phillips        kalvin phillips
11    Kristoffer Klaesson    kristoffer klaesson
12            Liam Cooper            liam cooper
13          Liam McCarron          liam mccarron
14            Luke Ayling            luke ayling
15          Mateusz Klich          mateusz klich
16         Pascal Struijk         pascal struijk
17        Patrick Bamford        patrick bamford
18               Raphinha               raphinha
19             Robin Koch             robin koch
20                Rodrigo                rodrigo
21          Sam Greenwood          sam greenwood
22          Stuart Dallas          stuart dallas
23          Tyler Roberts          tyler roberts

============================================================
  Leicester City  —  SF sin salario:

          player  minutesPlayed
0  Kasey McAteer              2
1    Lewis Brunt             23

  CG plantilla completa:

                   player            player_norm
0         Ademola Lookman        ademola lookman
1             Ayoze Pérez            ayoze perez
2       Boubakary Soumaré      boubakary soumare
3          Caglar Söyüncü         caglar soyuncu
4          Daniel Amartey         daniel amartey
5              Danny Ward             danny ward
6         Eldin Jakupovic        eldin jakupovic
7          Filip Benkovic         filip benkovic
8         Hamza Choudhury        hamza choudhury
9           Harvey Barnes          harvey barnes
10           James Justin           james justin
11         James Maddison         james maddison
12            Jamie Vardy            jamie vardy
13     Jannik Vestergaard     jannik vestergaard
14            Jonny Evans            jonny evans
15      Kasper Schmeichel      kasper schmeichel
16      Kelechi Iheanacho      kelechi iheanacho
17  Kiernan Dewsbury-Hall  kiernan dewsbury hall
18            Luke Thomas            luke thomas
19        Marc Albrighton        marc albrighton
20         Nampalys Mendy         nampalys mendy
21            Patson Daka            patson daka
22        Ricardo Pereira        ricardo pereira
23          Ryan Bertrand          ryan bertrand
24       Timothy Castagne       timothy castagne
25          Wesley Fofana          wesley fofana
26          Wilfred Ndidi          wilfred ndidi
27        Youri Tielemans        youri tielemans

============================================================
  Liverpool  —  SF sin salario:

         player  minutesPlayed
0  Kaide Gordon              8
1  Tyler Morton             70

  CG plantilla completa:

                     player              player_norm
0                    Adrián                   adrian
1   Alex Oxlade-Chamberlain  alex oxlade chamberlain
2                   Alisson                  alisson
3          Andrew Robertson         andrew robertson
4         Caoimhin Kelleher        caoimhin kelleher
5              Curtis Jones             curtis jones
6                Diogo Jota               diogo jota
7              Divock Origi             divock origi
8                   Fabinho                  fabinho
9            Harvey Elliott           harvey elliott
10          Ibrahima Konaté          ibrahima konate
11             James Milner             james milner
12                Joe Gomez                joe gomez
13               Joel Matip               joel matip
14         Jordan Henderson         jordan henderson
15    Konstantinos Tsimikas    konstantinos tsimikas
16             Loris Karius             loris karius
17                Luis Díaz                luis diaz
18            Mohamed Salah            mohamed salah
19               Naby Keïta               naby keita
20       Nathaniel Phillips       nathaniel phillips
21            Neco Williams            neco williams
22            Rhys Williams            rhys williams
23          Roberto Firmino          roberto firmino
24               Sadio Mané               sadio mane
25          Takumi Minamino          takumi minamino
26                   Thiago                   thiago
27   Trent Alexander-Arnold   trent alexander arnold
28          Virgil van Dijk          virgil van dijk

============================================================
  Manchester City  —  SF sin salario:

                    player  minutesPlayed
0  Conrad Jaden Egan-Riley              3
1             James McAtee             18
2               Liam Delap              9

  CG plantilla completa:

                 player          player_norm
0       Aymeric Laporte      aymeric laporte
1        Benjamin Mendy       benjamin mendy
2        Bernardo Silva       bernardo silva
3           Cole Palmer          cole palmer
4               Ederson              ederson
5           Fernandinho          fernandinho
6         Ferran Torres        ferran torres
7         Gabriel Jesus        gabriel jesus
8        Ilkay Gündogan       ilkay gundogan
9         Jack Grealish        jack grealish
10         João Cancelo         joao cancelo
11          John Stones          john stones
12                Kayky                kayky
13      Kevin De Bruyne      kevin de bruyne
14          Kyle Walker          kyle walker
15           Nathan Aké           nathan ake
16  Oleksandr Zinchenko  oleksandr zinchenko
17           Phil Foden           phil foden
18      Raheem Sterling      raheem sterling
19         Riyad Mahrez         riyad mahrez
20                Rodri                rodri
21           Rúben Dias           ruben dias
22         Scott Carson         scott carson
23         Zack Steffen         zack steffen

============================================================
  Manchester United  —  SF sin salario:

               player  minutesPlayed
0  Alejandro Garnacho             12
1     Hannibal Mejbri             72
2     Shola Shoretire             15

  CG plantilla completa:

               player        player_norm
0   Aaron Wan-Bissaka  aaron wan bissaka
1         Alex Telles        alex telles
2         Amad Diallo        amad diallo
3      Anthony Elanga     anthony elanga
4     Anthony Martial    anthony martial
5     Bruno Fernandes    bruno fernandes
6   Cristiano Ronaldo  cristiano ronaldo
7        David de Gea       david de gea
8      Dean Henderson     dean henderson
9         Diogo Dalot        diogo dalot
10  Donny van de Beek  donny van de beek
11     Edinson Cavani     edinson cavani
12        Eric Bailly        eric bailly
13               Fred               fred
14      Harry Maguire      harry maguire
15       Jadon Sancho       jadon sancho
16      Jesse Lingard      jesse lingard
17          Juan Mata          juan mata
18          Lee Grant          lee grant
19          Luke Shaw          luke shaw
20    Marcus Rashford    marcus rashford
21    Mason Greenwood    mason greenwood
22      Nemanja Matic      nemanja matic
23         Paul Pogba         paul pogba
24         Phil Jones         phil jones
25     Raphaël Varane     raphael varane
26    Scott McTominay    scott mctominay
27       Tahith Chong       tahith chong
28         Tom Heaton         tom heaton
29    Victor Lindelöf    victor lindelof

============================================================
  Norwich City  —  SF sin salario:

           player  minutesPlayed
0   Jonathan Rowe            226
1  Tony Springett            141

  CG plantilla completa:

                  player           player_norm
0              Adam Idah             adam idah
1     Andrew Omobamidele    andrew omobamidele
2             Angus Gunn            angus gunn
3             Bali Mumba            bali mumba
4             Ben Gibson            ben gibson
5          Billy Gilmour         billy gilmour
6       Brandon Williams      brandon williams
7   Christoph Zimmermann  christoph zimmermann
8        Christos Tzolis       christos tzolis
9   Dimitrios Giannoulis  dimitrios giannoulis
10          Flynn Clarke          flynn clarke
11          Grant Hanley          grant hanley
12  Jacob Lungi Sörensen  jacob lungi sorensen
13          Josh Sargent          josh sargent
14          Kenny McLean          kenny mclean
15         Kieran Dowell         kieran dowell
16            Lukas Rupp            lukas rupp
17       Mathias Normann       mathias normann
18            Max Aarons            max aarons
19      Michael McGovern      michael mcgovern
20         Milot Rashica         milot rashica
21            Ozan Kabak            ozan kabak
22     Pierre Lees-Melou     pierre lees melou
23   Przemyslaw Placheta   przemyslaw placheta
24         Rocky Bushiri         rocky bushiri
25             Sam Byram             sam byram
26           Teemu Pukki           teemu pukki
27              Tim Krul              tim krul
28         Todd Cantwell         todd cantwell

============================================================
  Tottenham Hotspur  —  SF sin salario:

          player  minutesPlayed
0  Dane Scarlett              3

  CG plantilla completa:

                   player            player_norm
0              Ben Davies             ben davies
1          Brandon Austin         brandon austin
2               Bryan Gil              bryan gil
3         Cristian Romero        cristian romero
4        Davinson Sánchez       davinson sanchez
5        Dejan Kulusevski       dejan kulusevski
6               Dele Alli              dele alli
7                 Emerson                emerson
8               Eric Dier              eric dier
9        Giovani Lo Celso       giovani lo celso
10             Harry Kane             harry kane
11            Harry Winks            harry winks
12          Heung-min Son          heung min son
13            Hugo Lloris            hugo lloris
14            Jack Clarke            jack clarke
15        Japhet Tanganga        japhet tanganga
16              Joe Rodon              joe rodon
17            Lucas Moura            lucas moura
18           Matt Doherty           matt doherty
19           Oliver Skipp           oliver skipp
20      Pierluigi Gollini      pierluigi gollini
21  Pierre-Emile Höjbjerg  pierre emile hojbjerg
22      Rodrigo Bentancur      rodrigo bentancur
23         Ryan Sessegnon         ryan sessegnon
24        Sergio Reguilón        sergio reguilon
25        Steven Bergwijn        steven bergwijn
26        Tanguy Ndombélé        tanguy ndombele

============================================================
  Watford  —  SF sin salario:

        player  minutesPlayed
0  Troy Deeney             23

  CG plantilla completa:

                  player           player_norm
0            Adam Masina           adam masina
1        Ashley Fletcher       ashley fletcher
2             Ben Foster            ben foster
3     Christian Kabasele    christian kabasele
4         Craig Cathcart        craig cathcart
5        Cucho Hernández       cucho hernandez
6            Dan Gosling           dan gosling
7        Daniel Bachmann       daniel bachmann
8             Danny Rose            danny rose
9            Edo Kayembe           edo kayembe
10       Emmanuel Dennis       emmanuel dennis
11   Francisco Sierralta   francisco sierralta
12        Hassane Kamara        hassane kamara
13           Imrân Louza           imran louza
14          Ismaïla Sarr          ismaila sarr
15         Jeremy Ngakia         jeremy ngakia
16            João Pedro            joao pedro
17           Joshua King           joshua king
18           Juraj Kucka           juraj kucka
19              Ken Sema              ken sema
20          Kiko Femenía          kiko femenia
21           Kwadwo Baah           kwadwo baah
22          Marc Navarro          marc navarro
23        Moussa Sissoko        moussa sissoko
24      Nicolas N'Koulou      nicolas n koulou
25      Oghenekaro Etebo      oghenekaro etebo
26            Ozan Tufan            ozan tufan
27            Rob Elliot            rob elliot
28                 Samir                 samir
29           Samuel Kalu           samuel kalu
30         Tom Cleverley         tom cleverley
31  William Troost-Ekong  william troost ekong
32        Yaser Asprilla        yaser asprilla

============================================================
  West Ham United  —  SF sin salario:

           player  minutesPlayed
0    Dan Chesters              1
1  Harrison Ashby             12
2   Sonny Perkins              8

  CG plantilla completa:

               player        player_norm
0     Aaron Cresswell    aaron cresswell
1           Alex Kral          alex kral
2     Alphonse Areola    alphonse areola
3   Andrii Yarmolenko  andrii yarmolenko
4      Angelo Ogbonna     angelo ogbonna
5      Arthur Masuaku     arthur masuaku
6         Ben Johnson        ben johnson
7        Craig Dawson       craig dawson
8     Darren Randolph    darren randolph
9        David Martin       david martin
10        Declan Rice        declan rice
11          Issa Diop          issa diop
12       Jarrod Bowen       jarrod bowen
13         Kurt Zouma         kurt zouma
14   Lukasz Fabianski   lukasz fabianski
15     Manuel Lanzini     manuel lanzini
16         Mark Noble         mark noble
17    Michail Antonio    michail antonio
18      Nikola Vlasic      nikola vlasic
19      Pablo Fornals      pablo fornals
20    Ryan Fredericks    ryan fredericks
21      Saïd Benrahma      said benrahma
22       Tomas Soucek       tomas soucek
23    Vladimir Coufal    vladimir coufal
24       Winston Reid       winston reid

============================================================
  Wolverhampton  —  SF sin salario:

               player  minutesPlayed
0       Chem Campbell             12
1  Morgan Gibbs-White             18

  CG plantilla completa:

                player         player_norm
0         Adama Traoré        adama traore
1         Bruno Jordão        bruno jordao
2            Chiquinho           chiquinho
3          Conor Coady         conor coady
4       Daniel Podence      daniel podence
5          Fábio Silva         fabio silva
6       Hee-chan Hwang      hee chan hwang
7        João Moutinho       joao moutinho
8           John Ruddy          john ruddy
9           Jonny Otto          jonny otto
10             José Sá             jose sa
11      Ki-Jana Hoever      ki jana hoever
12  Leander Dendoncker  leander dendoncker
13         Luke Cundle         luke cundle
14              Marçal              marcal
15       Matija Sarkic       matija sarkic
16          Max Kilman          max kilman
17       Nélson Semedo       nelson semedo
18          Oskar Buur          oskar buur
19          Pedro Neto          pedro neto
20        Raúl Jiménez        raul jimenez
21     Rayan Aït-Nouri     rayan ait nouri
22        Romain Saïss        romain saiss
23         Rúben Neves         ruben neves
24          Toti Gomes          toti gomes
25             Trincão             trincao
26          Willy Boly          willy boly
27     Yerson Mosquera     yerson mosquera

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 498/538 (92.6%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_england_2122.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_england_2122.csv
   Jugadores totales:  538
   Con salario:        498
   Sin salario (NaN):  40
   Columnas:           121