# 03 · Join Sofascore + Capology — France Ligue 1 23/24

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2023/24 de Ligue 1 francesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_france_2324.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_france_2324.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  525 jugadores | 116 columnas
Capology:   550 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   as monaco
   clermont foot
   olympique de marseille
   olympique lyonnais
   paris fc
   paris saint germain
   rc lens
   rc strasbourg
   rodez af
   stade brestois
   stade de reims
   stade rennais

En Capology pero no en Sofascore:
   brest
   clermont
   lens
   lyon
   marseille
   monaco
   psg
   reims
   rennes
   strasbourg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brest':'stade brestois',
            'clermont':'clermont foot',
            'lens':'rc lens',
            'lyon':'olympique lyonnais',
            'marseille':'olympique de marseille',
            'monaco':'as monaco',
            'psg':'paris saint germain',
            'reims':'stade de reims',
            'rennes':'stade rennais',
            'strasbourg':'rc strasbourg'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 441/525 (84.0%)
Sin emparejar: 84

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          8
Revisión media    (0.75 ≤ score < 0.90):   8
Revisión estricta (0.50 ≤ score < 0.75):   35
Revisión muy est. (score < 0.50):           31

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf            team               cg_match  score
13  Przemysław Frankowski         RC Lens  przemyslaw frankowski  0.976
1         Massamba Ndiaye   Clermont Foot       massamba n diaye  0.968
3        Radosław Majecki       AS Monaco       radoslaw majecki  0.968
54       Joseph N'Duquidi            Metz        joseph nduquidi  0.968
40        Emmanuel Emegha   RC Strasbourg         emanuel emegha  0.966
23          Darlin Yongwa         Lorient         darline yongwa  0.963
10           Marcin Bułka            Nice           marcin bulka  0.957
71              Luc Zogbé  Stade Brestois             luck zogbe  0.947

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
14,Mousa Tamari,Montpellier,mousa al tamari,0.889
43,Valentin Atangana Edoa,Stade de Reims,valentin atangana,0.872
48,François Régis Mughe,Olympique de Marseille,francois mughe,0.824
11,Abdoul Kone,Stade de Reims,amadou kone,0.818
34,Cheick Konaté,Clermont Foot,cheick oumar konate,0.812
42,Shavy Warren Babicka,Toulouse,shavy babicka,0.788
32,Enzo Tchato Mbiayi,Montpellier,enzo tchato,0.759
4,Wilfried Singo,AS Monaco,wilfried stephane singo,0.757

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['abdoul kone'

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 7 | Excluidos: 1

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
15,Amir Murillo,Olympique de Marseille,michael murillo,0.741
52,Kévin Keben Biakolo,Toulouse,kevin keben,0.733
21,Ahmadou Bamba Dieng,Lorient,bamba dieng,0.733
7,Muhammed-Cham Saračević,Clermont Foot,muhammed cham,0.722
47,Ethan Mbappé,Paris Saint-Germain,kylian mbappe,0.720
61,Joel Mugisha Mvuka,Lorient,joel mvuka,0.714
18,Alexsandro Ribeiro,Lille,alexsandro,0.714
39,Cheick Tidiane Sabaly,Metz,cheikh sabaly,0.706
44,Gift Orban,Olympique Lyonnais,gift emmanuel orban,0.690
33,Dion Moise Sahi,RC Strasbourg,moise sahi dion,0.667
8,David Pereira da Costa,RC Lens,david costa,0.667
36,Amin Sarr,Olympique Lyonnais,mamadou sarr,0.667
19,Boubakar Kouyaté,Montpellier,kiki kouyate,0.643
64,Aurelien Pelon,Lorient,julien ponceau,0.643
55,Andy Logbo,Le Havre,elysee logbo,0.636
0,Jérémy Doku,Stade Rennais,desire doue,0.636
26,Ângelo,RC Strasbourg,angelo gabriel,0.600
68,Yanis Issoufou,Montpellier,yanis guermouche,0.600
28,Carlos Baleba,Lille,nabil bentaleb,0.593
67,Royce Openda,Lorient,formose mendy,0.560
27,Saimon Bouabre,AS Monaco,myron boadu,0.560
29,Jeremy Sebas,RC Strasbourg,andrey santos,0.560
74,Raimane Daou,Olympique de Marseille,iliman ndiaye,0.560
49,Mohamed-Amine Bouchenna,Clermont Foot,muhammed cham,0.556
73,Ivan M'Bahia,Clermont Foot,chrislain matsima,0.552
17,Trévis Dago,Lille,tiago djalo,0.545
62,Karamoko Dembélé,Stade Brestois,kamory doumbia,0.533
41,Aboubacar Ali Abdallah,RC Strasbourg,abakar sylla,0.529
30,Yaya Fofana,Stade de Reims,adama bojang,0.522
78,Aaron Malouda,Lille,adam ounas,0.522
60,Adel Mahamoud,Nantes,mostafa mohamed,0.500
2,Jean-Ricner Bellegarde,RC Strasbourg,emanuel emegha,0.500
63,Ibrahima Kone,Lorient,bamba dieng,0.500
45,Simon Ebonog,Le Havre,mokrane bentoumi,0.500
53,Steve Ngoura,Le Havre,elysee logbo,0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['amir murillo',
                    'kevin keben biakolo',
                    'ahmadou bamba dieng',
                    'muhammed cham saracevic',
                    'joel mugisha mvuka',
                    'alexsandro ribeiro',
                    'cheick tidiane sabaly',
                    'gift orban',
                    'dion moise sahi',
                    'david pereira da costa',
                    'boubakar kouyate',
                    'andy logbo',
                    'angelo'
]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 13

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf                    team            cg_match  score
72        Chaim El Djebali      Olympique Lyonnais   mohamed el arouch  0.485
66            Ilhan Fakili           Clermont Foot   chrislain matsima  0.483
70        Sofiane Sidi Ali  Olympique de Marseille       iliman ndiaye  0.483
6           Othmane Maamma             Montpellier     mousa al tamari  0.483
69         Mohamed Bechikh           RC Strasbourg      maxime bastian  0.483
51              Enzo Mongo                  Nantes         moses simon  0.476
58       Keyliane Abdallah  Olympique de Marseille       iliman ndiaye  0.467
65        Bassirou N'Diaye                 Lorient      benjamin mendy  0.467
31            Farès Chaïbi                Toulouse      niklas schmidt  0.462
46        Mattéo Guendouzi  Olympique de Marseille          pape gueye  0.462
5            Saïd Benrahma      Olympique Lyonnais       ernest nuamah  0.462
76              Gino Caoki                 Lorient    tiemoue bakayoko  0.462
35  Lucas Mincarelli Davin             Montpellier   belmin dizdarevic  0.462
75       Hugo Boutsingkham                  Nantes  samuel moutoussamy  0.457
56       Mamadou Coulibaly               AS Monaco      mohamed camara  0.452
25         Rabby Nzingoula           RC Strasbourg        habib diarra  0.444
22             Yoram Zague     Paris Saint-Germain        keylor navas  0.435
12             Lovro Majer           Stade Rennais        ludovic blas  0.435
77            Djaoui Cissé           Stade Rennais         alidu seidu  0.435
81           Christ Letono          Stade de Reims     amir richardson  0.429
79            Ichem Ferrah                   Lille    rafael fernandes  0.429
20           Birger Meling           Stade Rennais     gauthier gallon  0.429
38            Axel Gueguin             Montpellier    yanis guermouche  0.429
80        Noam Mayoka-Tika  Olympique de Marseille        jordan amavi  0.429
59          Patrick Ouotro           RC Strasbourg          saidou sow  0.417
57            Lucas Michal               AS Monaco   chrislain matsima  0.414
24            Senny Mayulu     Paris Saint-Germain       nordi mukiele  0.400
50        Abdellah Baallal           Clermont Foot      bilal boutobba  0.400
16           Youssef Maziz                    Metz  georges mikautadze  0.387
9         Mateusz Wieteska           Clermont Foot    massamba n diaye  0.375
37         Hianga'a M'Bock          Stade Brestois        jordan amavi  0.370

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 469/525 (89.3%)
Sin salario:     56

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 56

,player,team,minutesPlayed,appearances,goals,assists
0,Mamadou Coulibaly,AS Monaco,121,5,0,0
1,Saimon Bouabre,AS Monaco,45,1,0,0
2,Lucas Michal,AS Monaco,9,1,0,0
3,Mateusz Wieteska,Clermont Foot,175,2,1,0
4,Ilhan Fakili,Clermont Foot,99,3,0,0
5,Mohamed-Amine Bouchenna,Clermont Foot,27,2,0,0
6,Ivan M'Bahia,Clermont Foot,13,1,0,0
7,Abdellah Baallal,Clermont Foot,11,1,0,0
8,Steve Ngoura,Le Havre,247,12,0,1
9,Simon Ebonog,Le Havre,34,4,0,0
10,Carlos Baleba,Lille,62,2,0,0
11,Trévis Dago,Lille,27,4,0,1
12,Ichem Ferrah,Lille,2,1,0,0
13,Aaron Malouda,Lille,1,1,0,0
14,Bassirou N'Diaye,Lorient,150,5,0,0
15,Aurelien Pelon,Lorient,90,1,0,0
16,Ibrahima Kone,Lorient,31,1,0,0
17,Royce Openda,Lorient,15,1,0,0
18,Gino Caoki,Lorient,10,1,0,0
19,Youssef Maziz,Metz,126,2,1,0
20,Lucas Mincarelli Davin,Montpellier,992,13,1,1
21,Axel Gueguin,Montpellier,130,3,0,0
22,Othmane Maamma,Montpellier,88,2,1,0
23,Yanis Issoufou,Montpellier,12,1,0,0
24,Hugo Boutsingkham,Nantes,10,2,0,0
25,Enzo Mongo,Nantes,9,1,0,0
26,Adel Mahamoud,Nantes,9,1,0,0
27,Saïd Benrahma,Olympique Lyonnais,778,12,3,3
28,Amin Sarr,Olympique Lyonnais,105,3,0,0
29,Chaim El Djebali,Olympique Lyonnais,11,1,0,0
30,Mattéo Guendouzi,Olympique de Marseille,26,2,0,0
31,Raimane Daou,Olympique de Marseille,24,1,0,0
32,Sofiane Sidi Ali,Olympique de Marseille,21,2,0,0
33,Keyliane Abdallah,Olympique de Marseille,10,1,0,0
34,Noam Mayoka-Tika,Olympique de Marseille,1,1,0,0
35,Rémy Riou,Paris FC,270,3,0,0
36,Yoram Zague,Paris Saint-Germain,372,5,1,0
37,Senny Mayulu,Paris Saint-Germain,323,8,0,1
38,Ethan Mbappé,Paris Saint-Germain,46,3,0,0
39,Jeremy Sebas,RC Strasbourg,398,14,2,0
40,Jean-Ricner Bellegarde,RC Strasbourg,269,3,2,2
41,Aboubacar Ali Abdallah,RC Strasbourg,142,9,0,1
42,Rabby Nzingoula,RC Strasbourg,131,6,0,1
43,Mohamed Bechikh,RC Strasbourg,19,2,0,0
44,Patrick Ouotro,RC Strasbourg,17,1,0,0
45,Dembo Sylla,Rodez AF,45,1,0,0
46,Hianga'a M'Bock,Stade Brestois,21,2,0,0
47,Karamoko Dembélé,Stade Brestois,16,1,0,0
48,Jérémy Doku,Stade Rennais,111,2,1,0
49,Lovro Majer,Stade Rennais,16,1,0,0
50,Birger Meling,Stade Rennais,16,1,0,0
51,Djaoui Cissé,Stade Rennais,3,2,0,0
52,Abdoul Kone,Stade de Reims,196,3,0,0
53,Yaya Fofana,Stade de Reims,28,4,0,0
54,Christ Letono,Stade de Reims,1,1,0,0
55,Farès Chaïbi,Toulouse,56,2,0,1

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  AS Monaco  —  SF sin salario:

              player  minutesPlayed
0       Lucas Michal              9
1  Mamadou Coulibaly            121
2     Saimon Bouabre             45

  CG plantilla completa:

                     player              player_norm
0         Aleksandr Golovin        aleksandr golovin
1              Breel Embolo             breel embolo
2             Caio Henrique            caio henrique
3         Chrislain Matsima        chrislain matsima
4             Denis Zakaria            denis zakaria
5                 Edan Diop                edan diop
6        Eliesse Ben Seghir       eliesse ben seghir
7              Eliot Matazo             eliot matazo
8           Folarin Balogun          folarin balogun
9            Gelson Martins           gelson martins
10        Guillermo Maripán        guillermo maripan
11            Ismail Jakobs            ismail jakobs
12         Kassoum Ouattara         kassoum ouattara
13            Krépin Diatta            krepin diatta
14        Maghnes Akliouche        maghnes akliouche
15           Mohamed Camara           mohamed camara
16          Mohammed Salisu          mohammed salisu
17              Myron Boadu              myron boadu
18             Philipp Köhn             philipp kohn
19         Radoslaw Majecki         radoslaw majecki
20       Soungoutou Magassa       soungoutou magassa
21          Takumi Minamino          takumi minamino
22             Thilo Kehrer             thilo kehrer
23                Vanderson                vanderson
24  Wilfried Stephane Singo  wilfried stephane singo
25        Wissam Ben Yedder        wissam ben yedder
26             Yann Lienard             yann lienard
27               Yllan Okou               yllan okou
28          Youssouf Fofana          youssouf fofana

============================================================
  Clermont Foot  —  SF sin salario:

                    player  minutesPlayed
0         Abdellah Baallal             11
1             Ilhan Fakili             99
2             Ivan M'Bahia             13
3         Mateusz Wieteska            175
4  Mohamed-Amine Bouchenna             27

  CG plantilla completa:

                  player           player_norm
0           Aïman Maurer          aiman maurer
1         Alan Virginius        alan virginius
2            Alidu Seidu           alidu seidu
3           Andy Pelmard          andy pelmard
4         Bilal Boutobba        bilal boutobba
5    Cheick Oumar Konaté   cheick oumar konate
6      Chrislain Matsima     chrislain matsima
7        Elbasan Rashani       elbasan rashani
8          Florent Ogier         florent ogier
9           Grejohn Kyei          grejohn kyei
10           Habib Keïta           habib keita
11          Jérémie Bela          jeremie bela
12        Jérémy Jacquet        jeremy jacquet
13         Jim Allevinah         jim allevinah
14         Johan Gastien         johan gastien
15         Komnen Andric         komnen andric
16      Massamba N'Diaye      massamba n diaye
17       Maxime Gonalons       maxime gonalons
18  Maximiliano Caufriez  maximiliano caufriez
19         Mehdi Zeffane         mehdi zeffane
20             Mory Diaw             mory diaw
21         Muhammed Cham         muhammed cham
22           Neto Borges           neto borges
23      Shamar Nicholson      shamar nicholson
24            Théo Borne            theo borne
25          Yadaly Diaby          yadaly diaby
26        Yanis Massolin        yanis massolin
27         Yoël Armougom         yoel armougom
28         Yohann Magnin         yohann magnin

============================================================
  Le Havre  —  SF sin salario:

         player  minutesPlayed
0  Simon Ebonog             34
1  Steve Ngoura            247

  CG plantilla completa:

                   player            player_norm
0         Abdoulaye Touré        abdoulaye toure
1           Aloïs Confais          alois confais
2              André Ayew             andre ayew
3          Antoine Joujou         antoine joujou
4         Arouna Sangante        arouna sangante
5           Arthur Desmas          arthur desmas
6          Cheick Doumbia         cheick doumbia
7       Christopher Operi      christopher operi
8           Daler Kuzyaev          daler kuzyaev
9            Elysée Logbo           elysee logbo
10         Emmanuel Sabbi         emmanuel sabbi
11  Étienne Youté Kinkoué  etienne youte kinkoue
12         Gautier Lloris         gautier lloris
13           Issa Soumaré           issa soumare
14          Josué Casimir          josue casimir
15         Kandet Diawara         kandet diawara
16              Loïc Nego              loic nego
17       Mathieu Gorgelin       mathieu gorgelin
18           Mohamed Bayo           mohamed bayo
19           Mohamed Koné           mohamed kone
20       Mokrane Bentoumi       mokrane bentoumi
21           Nabil Alioui           nabil alioui
22           Nolan Mbemba           nolan mbemba
23       Oualid El Hajjam       oualid el hajjam
24    Oussama Targhalline    oussama targhalline
25         Rassoul Ndiaye         rassoul ndiaye
26        Samuel Grandsir        samuel grandsir
27         Yassine Kechta         yassine kechta
28          Yoann Salmier          yoann salmier
29             Yoni Gomis             yoni gomis

============================================================
  Lille  —  SF sin salario:

          player  minutesPlayed
0  Aaron Malouda              1
1  Carlos Baleba             62
2   Ichem Ferrah              2
3    Trévis Dago             27

  CG plantilla completa:

                    player             player_norm
0            Adam Jakubech           adam jakubech
1               Adam Ounas              adam ounas
2             Akim Zedadka            akim zedadka
3           Alan Virginius          alan virginius
4               Alexsandro              alexsandro
5              Andrej Ilic             andrej ilic
6              Angel Gomes             angel gomes
7           Ayyoub Bouaddi          ayyoub bouaddi
8           Bafodé Diakité          bafode diakite
9           Benjamin André          benjamin andre
10           Edon Zhegrova           edon zhegrova
11     Gabriel Gudmundsson     gabriel gudmundsson
12  Hákon Arnar Haraldsson  hakon arnar haraldsson
13         Ignacio Miramón         ignacio miramon
14                 Ismaily                 ismaily
15          Ivan Cavaleiro          ivan cavaleiro
16          Jonathan David          jonathan david
17               Leny Yoro               leny yoro
18         Lucas Chevalier         lucas chevalier
19          Nabil Bentaleb          nabil bentaleb
20        Rafael Fernandes        rafael fernandes
21            Rémy Cabella            remy cabella
22           Samuel Umtiti           samuel umtiti
23             Tiago Djaló             tiago djalo
24            Tiago Morais            tiago morais
25            Tiago Santos            tiago santos
26            Vito Mannone            vito mannone
27            Yusuf Yazıcı              yusuf yazc

============================================================
  Lorient  —  SF sin salario:

             player  minutesPlayed
0    Aurelien Pelon             90
1  Bassirou N'Diaye            150
2        Gino Caoki             10
3     Ibrahima Kone             31
4      Royce Openda             15

  CG plantilla completa:

                    player             player_norm
0             Adrian Grbic            adrian grbic
1            Aiyegun Tosin           aiyegun tosin
2             Alfred Gomis            alfred gomis
3               Ayman Kari              ayman kari
4       Badredine Bouanani      badredine bouanani
5              Bamba Dieng             bamba dieng
6           Benjamin Mendy          benjamin mendy
7           Bonke Innocent          bonke innocent
8           Darline Yongwa          darline yongwa
9              Dembo Sylla             dembo sylla
10    Dominique Youfeigane    dominique youfeigane
11       Eli Junior Kroupi       eli junior kroupi
12           Formose Mendy           formose mendy
13           Gédéon Kalulu           gedeon kalulu
14              Igor Silva              igor silva
15             Imrân Louza             imran louza
16     Jean-Victor Makengo     jean victor makengo
17              Joel Mvuka              joel mvuka
18          Julien Laporte          julien laporte
19          Julien Ponceau          julien ponceau
20         Laurent Abergel         laurent abergel
21         Loris Mouyokolo         loris mouyokolo
22           Mohamed Bamba           mohamed bamba
23         Montassar Talbi         montassar talbi
24         Nathaniel Adjei         nathaniel adjei
25             Pablo Pagis             pablo pagis
26          Panos Katseris          panos katseris
27        Quentin Boisgard        quentin boisgard
28           Romain Faivre           romain faivre
29         Siriné Doucouré         sirine doucoure
30  Souleymane Isaak Touré  souleymane isaak toure
31            Théo Le Bris            theo le bris
32        Tiemoué Bakayoko        tiemoue bakayoko
33         Vincent Le Goff         vincent le goff
34              Yvon Mvogo              yvon mvogo

============================================================
  Metz  —  SF sin salario:

          player  minutesPlayed
0  Youssef Maziz            126

  CG plantilla completa:

                   player            player_norm
0            Ablie Jallow           ablie jallow
1            Aboubacar Lô           aboubacar lo
2       Alexandre Oukidja      alexandre oukidja
3             Arthur Atta            arthur atta
4         Benjamin Tetteh        benjamin tetteh
5           Cheikh Sabaly          cheikh sabaly
6      Christophe Hérelle     christophe herelle
7     Danley Jean Jacques    danley jean jacques
8        Didier Lamkel Zé       didier lamkel ze
9              Fali Candé             fali cande
10     Georges Mikautadze     georges mikautadze
11      Guillaume Dietsch      guillaume dietsch
12            Habib Maïga            habib maiga
13              Ibou Sané              ibou sane
14          Ismaël Traoré          ismael traore
15         Jean N'Guessan         jean n guessan
16             Joel Asoro             joel asoro
17        Joseph Nduquidi        joseph nduquidi
18          Kévin N'Doram          kevin n doram
19  Kevin Van Den Kerkhof  kevin van den kerkhof
20            Koffi Kouao            koffi kouao
21          Lamine Camara          lamine camara
22           Malick Mbaye           malick mbaye
23   Marc-Aurèle Caillard   marc aurele caillard
24          Matthieu Udol          matthieu udol
25           Maxime Colin           maxime colin
26        Óscar Estupiñán        oscar estupinan
27     Papa Amadou Diallo     papa amadou diallo
28           Sadibou Sané           sadibou sane
29         Sami Lahssaini         sami lahssaini
30           Simon Elisor           simon elisor
31      Warren Tchimbembé      warren tchimbembe

============================================================
  Montpellier  —  SF sin salario:

                   player  minutesPlayed
0            Axel Gueguin            130
1  Lucas Mincarelli Davin            992
2          Othmane Maamma             88
3          Yanis Issoufou             12

  CG plantilla completa:

                 player          player_norm
0            Akor Adams           akor adams
1         Arnaud Nordin        arnaud nordin
2        Becir Omeragic       becir omeragic
3     Belmin Dizdarevic    belmin dizdarevic
4      Benjamin Lecomte     benjamin lecomte
5   Christopher Jullien  christopher jullien
6       Dimitry Bertaud      dimitry bertaud
7           Enzo Tchato          enzo tchato
8          Falaye Sacko         falaye sacko
9         Issiaga Sylla        issiaga sylla
10         Jordan Ferri         jordan ferri
11        Joris Chotard        joris chotard
12        Kelvin Yeboah        kelvin yeboah
13         Khalil Fayad         khalil fayad
14         Kiki Kouyaté         kiki kouyate
15            Léo Leroy            leo leroy
16        Mamadou Sakho        mamadou sakho
17        Maxime Estève        maxime esteve
18        Modibo Sagnan        modibo sagnan
19      Mousa Al-Tamari      mousa al tamari
20         Sacha Delaye         sacha delaye
21         Silvan Hefti         silvan hefti
22     Tanguy Coulibaly     tanguy coulibaly
23        Téji Savanier        teji savanier
24     Théo Sainte-Luce     theo sainte luce
25         Wahbi Khazri         wahbi khazri
26     Yanis Guermouche     yanis guermouche
27         Yann Karamoh         yann karamoh

============================================================
  Nantes  —  SF sin salario:

              player  minutesPlayed
0      Adel Mahamoud              9
1         Enzo Mongo              9
2  Hugo Boutsingkham             10

  CG plantilla completa:

                      player               player_norm
0         Abdoul Kader Bamba        abdoul kader bamba
1                      Adson                     adson
2               Alban Lafont              alban lafont
3           Bastien Meupiyou          bastien meupiyou
4               Bénie Traoré              benie traore
5               Denis Petric              denis petric
6            Douglas Augusto           douglas augusto
7                Eray Cömert               eray comert
8            Fabien Centonze           fabien centonze
9             Florent Mollet            florent mollet
10             Gor Manvelyan             gor manvelyan
11           Ignatius Ganago           ignatius ganago
12             Jaouen Hadjam             jaouen hadjam
13  Jean-Charles Castelletto  jean charles castelletto
14        Jean-Kévin Duverne        jean kevin duverne
15              Kelvin Amian              kelvin amian
16              Lamine Diack              lamine diack
17               Marcus Coco               marcus coco
18                Marquinhos                marquinhos
19            Matthis Abline            matthis abline
20              Mohamed Achi              mohamed achi
21               Moses Simon               moses simon
22           Mostafa Mohamed           mostafa mohamed
23            Moussa Sissoko            moussa sissoko
24               Nathan Zeze               nathan zeze
25             Nicolas Cozza             nicolas cozza
26           Nicolas Pallois           nicolas pallois
27          Pedro Chirivella          pedro chirivella
28            Quentin Merlin            quentin merlin
29             Rémy Descamps             remy descamps
30     Ronaël Pierre-Gabriel     ronael pierre gabriel
31        Samuel Moutoussamy        samuel moutoussamy
32           Stredair Appuah           stredair appuah
33             Tino Kadewere             tino kadewere
34            Yannis M'Bemba            yannis m bemba

============================================================
  Olympique Lyonnais  —  SF sin salario:

             player  minutesPlayed
0         Amin Sarr            105
1  Chaim El Djebali             11
2     Saïd Benrahma            778

  CG plantilla completa:

                    player             player_norm
0           Achraf Laâziri          achraf laaziri
1                Adryelson               adryelson
2   Ainsley Maitland-Niles  ainsley maitland niles
3      Alexandre Lacazette     alexandre lacazette
4            Anthony Lopes           anthony lopes
5             Clinton Mata            clinton mata
6         Corentin Tolisso        corentin tolisso
7             Dejan Lovren            dejan lovren
8            Diego Moreira           diego moreira
9          Duje Caleta-Car         duje caleta car
10           Ernest Nuamah           ernest nuamah
11     Gift Emmanuel Orban     gift emmanuel orban
12                Henrique                henrique
13            Jake O'Brien            jake o brien
14     Jeff Reine-Adélaïde     jeff reine adelaide
15                Jeffinho                jeffinho
16         Johann Lepenant         johann lepenant
17           Justin Bengui           justin bengui
18             Lucas Perri             lucas perri
19       Mahamadou Diawara       mahamadou diawara
20           Malick Fofana           malick fofana
21              Mama Baldé              mama balde
22            Mamadou Sarr            mamadou sarr
23        Maxence Caqueret        maxence caqueret
24       Mohamed El Arouch       mohamed el arouch
25           Nemanja Matic           nemanja matic
26      Nicolás Tagliafico      nicolas tagliafico
27            Orel Mangala            orel mangala
28           Paul Akouokou           paul akouokou
29            Rayan Cherki            rayan cherki
30               Rémy Riou               remy riou
31            Saël Kumbedi            sael kumbedi
32         Sinaly Diomandé         sinaly diomande
33           Skelly Alvero           skelly alvero
34           Tino Kadewere           tino kadewere

============================================================
  Olympique de Marseille  —  SF sin salario:

              player  minutesPlayed
0  Keyliane Abdallah             10
1   Mattéo Guendouzi             26
2   Noam Mayoka-Tika              1
3       Raimane Daou             24
4   Sofiane Sidi Ali             21

  CG plantilla completa:

                       player                player_norm
0                 Amine Harit                amine harit
1             Azzedine Ounahi            azzedine ounahi
2                  Bamo Meïté                 bamo meite
3                 Bilal Nadir                bilal nadir
4              Chancel Mbemba             chancel mbemba
5                 Emran Soglo                emran soglo
6             Faris Moumbagna            faris moumbagna
7              François Mughe             francois mughe
8          Geoffrey Kondogbia         geoffrey kondogbia
9               Iliman Ndiaye              iliman ndiaye
10               Ismaïla Sarr               ismaila sarr
11                 Jean Onana                 jean onana
12             Jelle Van Neck             jelle van neck
13             Joaquín Correa             joaquin correa
14            Jonathan Clauss            jonathan clauss
15               Jordan Amavi               jordan amavi
16            Jordan Veretout            jordan veretout
17           Leonardo Balerdi           leonardo balerdi
18              Luis Henrique              luis henrique
19            Michael Murillo            michael murillo
20                 Pape Gueye                 pape gueye
21                  Pau López                  pau lopez
22  Pierre-Emerick Aubameyang  pierre emerick aubameyang
23             Quentin Merlin             quentin merlin
24                 Renan Lodi                 renan lodi
25               Rubén Blanco               ruben blanco
26               Samuel Gigot               samuel gigot
27       Simon Ngapandouetnbu       simon ngapandouetnbu
28             Ulisses Garcia             ulisses garcia
29           Valentin Rongier           valentin rongier
30                    Vitinha                    vitinha

============================================================
  Paris FC  —  SF sin salario:

      player  minutesPlayed
0  Rémy Riou            270

  CG plantilla completa:

Empty DataFrame
Columns: [player, player_norm]
Index: []

============================================================
  Paris Saint-Germain  —  SF sin salario:

         player  minutesPlayed
0  Ethan Mbappé             46
1  Senny Mayulu            323
2   Yoram Zague            372

  CG plantilla completa:

                  player           player_norm
0          Achraf Hakimi         achraf hakimi
1    Alexandre Letellier   alexandre letellier
2            Arnau Tenas           arnau tenas
3        Bradley Barcola       bradley barcola
4           Carlos Soler          carlos soler
5             Cher Ndour            cher ndour
6         Danilo Pereira        danilo pereira
7         Edouard Michut        edouard michut
8            Fabián Ruiz           fabian ruiz
9   Gianluigi Donnarumma  gianluigi donnarumma
10         Gonçalo Ramos         goncalo ramos
11          Hugo Ekitiké          hugo ekitike
12           Kang-in Lee           kang in lee
13          Keylor Navas          keylor navas
14         Kylian Mbappé         kylian mbappe
15        Layvin Kurzawa        layvin kurzawa
16         Lucas Beraldo         lucas beraldo
17       Lucas Hernández       lucas hernandez
18         Manuel Ugarte         manuel ugarte
19         Marco Asensio         marco asensio
20            Marquinhos            marquinhos
21        Milan Skriniar        milan skriniar
22         Nordi Mukiele         nordi mukiele
23           Nuno Mendes           nuno mendes
24       Ousmane Dembélé       ousmane dembele
25      Presnel Kimpembe      presnel kimpembe
26     Randal Kolo Muani     randal kolo muani
27        Renato Sanches        renato sanches
28           Sergio Rico           sergio rico
29               Vitinha               vitinha
30    Warren Zaïre-Emery    warren zaire emery

============================================================
  RC Strasbourg  —  SF sin salario:

                   player  minutesPlayed
0  Aboubacar Ali Abdallah            142
1  Jean-Ricner Bellegarde            269
2            Jeremy Sebas            398
3         Mohamed Bechikh             19
4          Patrick Ouotro             17
5         Rabby Nzingoula            131

  CG plantilla completa:

               player        player_norm
0        Abakar Sylla       abakar sylla
1    Alaa Bellaarouch   alaa bellaarouch
2    Alexandre Pierre   alexandre pierre
3       Andrey Santos      andrey santos
4      Ângelo Gabriel     angelo gabriel
5        Dilane Bakwa       dilane bakwa
6        Eduard Sobol       eduard sobol
7      Emanuel Emegha     emanuel emegha
8   Frédéric Guilbert  frederic guilbert
9      Gerzino Nyamsi     gerzino nyamsi
10       Habib Diarra       habib diarra
11   Ibrahima Sissoko   ibrahima sissoko
12    Ismaël Doukouré    ismael doukoure
13  Jean-Eudes Aholou  jean eudes aholou
14    Jessy Deminguet    jessy deminguet
15      Junior Mwanga      junior mwanga
16         Karol Fila         karol fila
17      Kévin Gameiro      kevin gameiro
18       Lebo Mothiba       lebo mothiba
19       Lucas Perrin       lucas perrin
20      Marvin Senaya      marvin senaya
21    Matthieu Dreyer    matthieu dreyer
22          Matz Sels          matz sels
23     Maxime Bastian     maxime bastian
24    Moïse Sahi Dion    moise sahi dion
25         Saïdou Sow         saidou sow
26       Sanjin Prcic       sanjin prcic
27      Steven Baseya      steven baseya
28     Thomas Delaine     thomas delaine

============================================================
  Rodez AF  —  SF sin salario:

        player  minutesPlayed
0  Dembo Sylla             45

  CG plantilla completa:

Empty DataFrame
Columns: [player, player_norm]
Index: []

============================================================
  Stade Brestois  —  SF sin salario:

             player  minutesPlayed
0   Hianga'a M'Bock             21
1  Karamoko Dembélé             16

  CG plantilla completa:

                  player           player_norm
0            Achraf Dari           achraf dari
1          Adrien Lebeau         adrien lebeau
2     Antonin Cartillier    antonin cartillier
3           Axel Camblan          axel camblan
4         Billal Brahimi        billal brahimi
5          Bradley Locko         bradley locko
6     Brendan Chardonnet    brendan chardonnet
7       Grégoire Coudert      gregoire coudert
8          Hugo Magnetti         hugo magnetti
9      Jérémy Le Douaron     jeremy le douaron
10          Jonas Martin          jonas martin
11          Jordan Amavi          jordan amavi
12        Josué Escartin        josue escartin
13    Julien Le Cardinal    julien le cardinal
14        Kamory Doumbia        kamory doumbia
15            Kenny Lala            kenny lala
16       Lilian Brassier       lilian brassier
17            Luck Zogbé            luck zogbe
18          Mahdi Camara          mahdi camara
19           Marco Bizot           marco bizot
20       Martín Satriano       martin satriano
21  Mathias Pereira Lage  mathias pereira lage
22     Pierre Lees-Melou     pierre lees melou
23   Romain Del Castillo   romain del castillo
24          Steve Mounié          steve mounie
25          Yan Marillat          yan marillat

============================================================
  Stade Rennais  —  SF sin salario:

          player  minutesPlayed
0  Birger Meling             16
1   Djaoui Cissé              3
2    Jérémy Doku            111
3    Lovro Majer             16

  CG plantilla completa:

                 player          player_norm
0       Adrien Truffert      adrien truffert
1           Alidu Seidu          alidu seidu
2          Amine Gouiri         amine gouiri
3     Arnaud Kalimuendo    arnaud kalimuendo
4         Arthur Theate        arthur theate
5         Azor Matusiwa        azor matusiwa
6   Baptiste Santamaria  baptiste santamaria
7   Benjamin Bourigeaud  benjamin bourigeaud
8       Bertuğ Yıldırım         bertug yldrm
9      Christopher Wooh     christopher wooh
10          Désiré Doué          desire doue
11          Enzo Le Fée          enzo le fee
12        Fabian Rieder        fabian rieder
13      Gauthier Gallon      gauthier gallon
14      Geoffrey Lembet      geoffrey lembet
15           Guéla Doué           guela doue
16        Ibrahim Salah        ibrahim salah
17     Jeanuël Belocian     jeanuel belocian
18      Lorenz Assignon      lorenz assignon
19         Ludovic Blas         ludovic blas
20     Mahamadou Nagida     mahamadou nagida
21       Martin Terrier       martin terrier
22     Mathis Lambourde     mathis lambourde
23        Nemanja Matic        nemanja matic
24       Steve Mandanda       steve mandanda
25         Warmed Omari         warmed omari

============================================================
  Stade de Reims  —  SF sin salario:

          player  minutesPlayed
0    Abdoul Kone            196
1  Christ Letono              1
2    Yaya Fofana             28

  CG plantilla completa:

                 player          player_norm
0          Adama Bojang         adama bojang
1     Alexandre Olliero    alexandre olliero
2           Amadou Koné          amadou kone
3          Amine Salama         amine salama
4       Amir Richardson      amir richardson
5         Azor Matusiwa        azor matusiwa
6    Benjamin Stambouli   benjamin stambouli
7      Emmanuel Agbadou     emmanuel agbadou
8       Ibrahim Diakité      ibrahim diakite
9          Joseph Okumu         joseph okumu
10  Josh Wilson-Esbrand  josh wilson esbrand
11            Junya Ito            junya ito
12       Keito Nakamura       keito nakamura
13      Ludovic Butelle      ludovic butelle
14      Mamadou Diakhon      mamadou diakhon
15     Marshall Munetsi     marshall munetsi
16          Maxime Busi          maxime busi
17       Mohamed Daramy       mohamed daramy
18        Oumar Diakité        oumar diakite
19          Reda Khadra          reda khadra
20      Samuel Koeberlé      samuel koeberle
21        Sergio Akieme        sergio akieme
22          Teddy Teuma          teddy teuma
23      Thérence Koudou      therence koudou
24     Thibault De Smet     thibault de smet
25         Thomas Foket         thomas foket
26    Valentin Atangana    valentin atangana
27        Yehvann Diouf        yehvann diouf
28     Yunis Abdelhamid     yunis abdelhamid

============================================================
  Toulouse  —  SF sin salario:

         player  minutesPlayed
0  Farès Chaïbi             56

  CG plantilla completa:

                  player           player_norm
0         Álex Domínguez        alex dominguez
1            Aron Dønnum            aron dnnum
2          Bonota Traoré         bonota traore
3         César Gelabert        cesar gelabert
4      Christian Mawissa     christian mawissa
5   Cristian Cásseres Jr  cristian casseres jr
6          Denis Genreau         denis genreau
7            Frank Magri           frank magri
8          Gabriel Suazo         gabriel suazo
9       Guillaume Restes      guillaume restes
10       Ibrahim Cissoko       ibrahim cissoko
11      Junior Flemmings      junior flemmings
12        Justin Lacombe        justin lacombe
13           Kévin Keben           kevin keben
14          Kléri Serber          kleri serber
15           Logan Costa           logan costa
16         Mamady Bangré         mamady bangre
17         Mikkel Desler         mikkel desler
18         Moussa Diarra         moussa diarra
19         Naatan Skyttä         naatan skytta
20        Niklas Schmidt        niklas schmidt
21          Noah Edjouma          noah edjouma
22          Noah Lahmadi          noah lahmadi
23         Oliver Zandén         oliver zanden
24     Rasmus Nicolaisen     rasmus nicolaisen
25         Shavy Babicka         shavy babicka
26       Stijn Spierings       stijn spierings
27        Thijs Dallinga        thijs dallinga
28         Thomas Himeur         thomas himeur
29        Vincent Sierro        vincent sierro
30        Warren Kamanzi        warren kamanzi
31        Yanis Begraoui        yanis begraoui
32            Yann Gboho            yann gboho
33           Ylies Aradj           ylies aradj
34     Zakaria Aboukhlal     zakaria aboukhlal

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 469/525 (89.3%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_france_2324.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_france_2324.csv
   Jugadores totales:  525
   Con salario:        469
   Sin salario (NaN):  56
   Columnas:           121