# 03 · Join Sofascore + Capology — France Ligue 1 20/21

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2020/21 de Ligue 1 francesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_france_2021.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_france_2021.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  573 jugadores | 116 columnas
Capology:   586 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   as monaco
   nimes olympique
   olympique de marseille
   olympique lyonnais
   paris saint germain
   rc lens
   rc strasbourg
   saint etienne
   stade brestois
   stade de reims
   stade rennais

En Capology pero no en Sofascore:
   brest
   lens
   lyon
   marseille
   monaco
   nimes
   psg
   reims
   rennes
   st etienne
   strasbourg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brest':'stade brestois',
            'lens':'rc lens',
            'lyon':'olympique lyonnais',
            'marseille':'olympique de marseille',
            'monaco':'as monaco',
            'nimes':'nimes olympique',
            'psg':'paris saint germain',
            'reims':'stade de reims',
            'rennes':'stade rennais',
            'st etienne':'saint etienne',
            'strasbourg':'rc strasbourg'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 479/573 (83.6%)
Sin emparejar: 94

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          10
Revisión media    (0.75 ≤ score < 0.90):   5
Revisión estricta (0.50 ≤ score < 0.75):   43
Revisión muy est. (score < 0.50):           36

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

           player_sf                team          cg_match  score
50  Billal Benkhedim       Saint-Étienne   bilal benkhedim  0.968
44  Radosław Majecki           AS Monaco  radoslaw majecki  0.968
54   Hianga'a M'Bock      Stade Brestois    hianga a mbock  0.966
67     Samy Benchama         Montpellier    samy benchamma  0.963
23    Stanley N'Soki                Nice     stanley nsoki  0.963
14   Steven​ N'Zonzi       Stade Rennais     steven nzonzi  0.963
21     Didier N'Dong               Dijon      didier ndong  0.960
93      Yaya Soumare  Olympique Lyonnais     yahya soumare  0.960
1       Burak Yılmaz               Lille      burak yilmaz  0.957
9       Yusuf Yazıcı               Lille      yusuf yazici  0.909

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf                team                cg_match  score
69  Ahmad Toure Ngouyamsa               Dijon         ahmad ngouyamsa  0.833
17        Djamel Benlamri  Olympique Lyonnais  djamel eddine benlamri  0.811
41        Florentino Luís           AS Monaco              florentino  0.800
0                  Marçal  Olympique Lyonnais                 marcelo  0.769
8         Pape Matar Sarr                Metz               pape sarr  0.750

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['marcal'

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 4 | Excluidos: 1

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf                    team           cg_match  score
64            Hicham Mahou                    Nice    hicham boudaoui  0.741
34             Vagner Dias                    Metz             vagner  0.706
25  David Pereira da Costa                 RC Lens        david costa  0.667
30         Abdoulaye Sylla                  Nantes    abdoulaye toure  0.667
4         Boubakar Kouyaté                    Metz    boubacar traore  0.645
76             Yann M'Vila           Saint-Étienne        yvann macon  0.636
33             Edson Mexer                Bordeaux              mexer  0.625
40      Junior Dina Ebimbe                   Dijon        eric ebimbe  0.621
85          Matthis Abline           Stade Rennais       romain salin  0.615
35     Ahmadou Bamba Dieng  Olympique de Marseille     aaron kamardin  0.606
71           Edouard Mendy           Stade Rennais  eduardo camavinga  0.600
68          Danilo Barbosa                    Nice             danilo  0.600
12         Ibrahima Diallo          Stade Brestois       idrissa dioh  0.593
75           Rachid Alioui                  Angers     ibrahim amadou  0.593
5        Rafinha Alcântara     Paris Saint-Germain            rafinha  0.583
89            Kenny Nagera     Paris Saint-Germain       keylor navas  0.583
45       Marvin Tshibuabua           Saint-Étienne     romain hamouma  0.581
13          Erwan Belhadji                   Dijon     bersant celina  0.571
29             Yanis Lhéry           Saint-Étienne         yvan neyou  0.571
81            Marcin Bułka     Paris Saint-Germain         maxen kapo  0.571
27         Vitorino Hilton             Montpellier             hilton  0.571
56              Bouna Sarr  Olympique de Marseille    boubacar kamara  0.560
70            Tyron Tormin           Saint-Étienne      arnaud nordin  0.560
87          Assane Dioussé           Saint-Étienne    pape abou cisse  0.552
63          Adrien Louveau                 RC Lens    jean louis leca  0.552
46            Rayan Souici           Saint-Étienne         yvan neyou  0.545
48            Moise Sakava          Stade de Reims     moreto cassama  0.538
6            Wesley Fofana           Saint-Étienne      denis bouanga  0.538
11        Lesley Ugochukwu           Stade Rennais        jeremy doku  0.519
15         Dion Moise Sahi           RC Strasbourg       idriss saadi  0.519
37          Malik Sellouki                    Nice      stanley nsoki  0.519
49           Yoann Etienne                 Lorient     fabien lemoine  0.519
91          Charles Costes                   Dijon         sacha boey  0.500
92              Malo Gusto      Olympique Lyonnais         leo dubois  0.500
77            Manuel Perez                 RC Lens       ismael boura  0.500
79            Mathys Saban           Saint-Étienne       mahdi camara  0.500
58           Nassim Chadli         Nîmes Olympique        karim aribi  0.500
47            Sacha Delaye             Montpellier       keagan dolly  0.500
42         Rayan Aït-Nouri                  Angers  lassana coulibaly  0.500
62        Salim Ben Seghir                    Nice       amine gouiri  0.500
2                 Raphinha           Stade Rennais       romain salin  0.500
7         Giulian Biancone               AS Monaco       vito mannone  0.500
18            Wahbi Khazri           Saint-Étienne       mahdi camara  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['vagner dias',
                    'david pereira da costa',
                    'edson mexer',
                    'junior dina ebimbe',
                    'danilo barbosa',
                    'rafinha alcantara',
                    'vitorino hilton'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 7

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                   player_sf                    team           cg_match  score
73     Cheick Tidiane Sabaly                    Metz   victorien angban  0.486
31          Joachim Andersen      Olympique Lyonnais      thiago mendes  0.483
59            Eddy Sylvestre                    Nice    teddy boulhendi  0.483
60        Aurélien Scheidler                   Dijon        pape cheikh  0.483
52           Anthony Modeste           Saint-Étienne     aimen moueffek  0.483
16                Sékou Mara                Bordeaux    youssouf sabaly  0.480
80            Jesé Rodríguez     Paris Saint-Germain        sergio rico  0.480
65               Rubén Pardo                Bordeaux     hatem ben arfa  0.480
72                Andy Diouf           Stade Rennais        jeremy doku  0.476
24           Issouf Sissokho                Bordeaux    youssouf sabaly  0.467
20            Evann Guessand                    Nice       andy pelmard  0.462
36              Dilane Bakwa                Bordeaux     hatem ben arfa  0.462
61            Rayan Philippe                   Dijon       jordan marie  0.462
74            Yassin Fortune                  Angers       thomas toure  0.462
38              Maxime López  Olympique de Marseille         marley ake  0.455
22                 Josh Maja                Bordeaux      over mandanda  0.455
3        Baptiste Santamaria                  Angers       waniss taibi  0.452
78           Tristan Dingomé          Stade de Reims   thibault de smet  0.452
57           Baptiste Gabard           Saint-Étienne       mahdi camara  0.444
28             Casimir Ninga                  Angers     thomas mangani  0.444
83            Wilfried Kanga                  Angers      kevin bemanga  0.444
90                 Ansou Sow                 RC Lens     florian sotoca  0.435
10                Kenny Tete      Olympique Lyonnais      anthony lopes  0.435
51      Jean-Philippe Krasso           Saint-Étienne  panagiotis retsos  0.432
53          Aboubakar Kamara                   Dijon       jordan marie  0.429
26              Alexis Flips          Stade de Reims   anastasios donis  0.429
43        Samuel Moutoussamy                  Nantes    abdoulaye toure  0.424
82              Hugo Ekitiké          Stade de Reims       thomas foket  0.417
32              Jacques Siwe                   Dijon       jordan marie  0.417
84               Habib Keita      Olympique Lyonnais      memphis depay  0.417
86            Édouard Michut     Paris Saint-Germain    leandro paredes  0.414
66        Mahamadou Doucouré         Nîmes Olympique        moussa kone  0.414
39              Jimmy Briand                Bordeaux      mehdi zerkane  0.400
88  Florent Sanchez Da Silva      Olympique Lyonnais  mattia de sciglio  0.390
55                Umut Bozok                 Lorient   quentin boisgard  0.385
19                 Dion Lopy          Stade de Reims       dialy ndiaye  0.381

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 500/573 (87.3%)
Sin salario:     73

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 73

,player,team,minutesPlayed,appearances,goals,assists
0,Giulian Biancone,AS Monaco,92,2,0,0
1,Baptiste Santamaria,Angers,270,3,0,0
2,Rayan Aït-Nouri,Angers,187,3,0,1
3,Wilfried Kanga,Angers,134,2,0,0
4,Casimir Ninga,Angers,22,1,0,0
5,Yassin Fortune,Angers,14,1,0,0
6,Rachid Alioui,Angers,14,1,0,0
7,Josh Maja,Bordeaux,815,17,2,0
8,Jimmy Briand,Bordeaux,557,24,1,2
9,Sékou Mara,Bordeaux,232,8,1,2
10,Issouf Sissokho,Bordeaux,75,6,1,0
11,Dilane Bakwa,Bordeaux,67,7,0,0
12,Rubén Pardo,Bordeaux,21,2,0,0
13,Aboubakar Kamara,Dijon,560,10,1,0
14,Aurélien Scheidler,Dijon,345,10,1,0
15,Jacques Siwe,Dijon,167,5,0,0
16,Rayan Philippe,Dijon,98,4,0,0
17,Erwan Belhadji,Dijon,29,1,0,0
18,Charles Costes,Dijon,1,1,0,0
19,Yoann Etienne,Lorient,90,1,0,0
20,Umut Bozok,Lorient,58,5,0,0
21,Boubakar Kouyaté,Metz,1966,25,1,0
22,Cheick Tidiane Sabaly,Metz,11,1,0,0
23,Sacha Delaye,Montpellier,12,1,0,0
24,Samuel Moutoussamy,Nantes,83,1,0,0
25,Abdoulaye Sylla,Nantes,12,2,0,0
26,Eddy Sylvestre,Nice,96,4,0,0
27,Malik Sellouki,Nice,66,4,1,0
28,Hicham Mahou,Nice,32,2,0,0
29,Evann Guessand,Nice,27,3,0,0
30,Salim Ben Seghir,Nice,13,1,0,0
31,Mahamadou Doucouré,Nîmes Olympique,46,3,0,0
32,Nassim Chadli,Nîmes Olympique,28,3,0,0
33,Joachim Andersen,Olympique Lyonnais,191,3,0,0
34,Marçal,Olympique Lyonnais,79,1,0,0
35,Kenny Tete,Olympique Lyonnais,20,1,0,0
36,Habib Keita,Olympique Lyonnais,8,1,0,0
37,Florent Sanchez Da Silva,Olympique Lyonnais,2,1,0,0
38,Malo Gusto,Olympique Lyonnais,2,2,0,0
39,Ahmadou Bamba Dieng,Olympique de Marseille,149,5,0,0
40,Maxime López,Olympique de Marseille,139,4,0,0
41,Bouna Sarr,Olympique de Marseille,75,2,0,0
42,Marcin Bułka,Paris Saint-Germain,90,1,0,0
43,Jesé Rodríguez,Paris Saint-Germain,22,2,0,0
44,Édouard Michut,Paris Saint-Germain,1,1,0,0
45,Kenny Nagera,Paris Saint-Germain,1,1,0,0
46,Manuel Perez,RC Lens,127,4,0,0
47,Adrien Louveau,RC Lens,11,1,0,0
48,Ansou Sow,RC Lens,5,1,0,0
49,Dion Moise Sahi,RC Strasbourg,91,6,1,0
50,Wahbi Khazri,Saint-Étienne,1191,22,7,1
51,Wesley Fofana,Saint-Étienne,315,4,0,0
52,Anthony Modeste,Saint-Étienne,294,7,0,0
53,Jean-Philippe Krasso,Saint-Étienne,220,6,0,0
54,Baptiste Gabard,Saint-Étienne,134,2,0,0
55,Marvin Tshibuabua,Saint-Étienne,42,1,0,0
56,Yanis Lhéry,Saint-Étienne,29,1,0,0
57,Yann M'Vila,Saint-Étienne,19,1,0,0
58,Tyron Tormin,Saint-Étienne,18,3,0,0
59,Mathys Saban,Saint-Étienne,12,1,0,0
60,Rayan Souici,Saint-Étienne,9,1,0,0
61,Assane Dioussé,Saint-Étienne,1,1,0,0
62,Ibrahima Diallo,Stade Brestois,442,5,0,0
63,Raphinha,Stade Rennais,407,6,1,2
64,Edouard Mendy,Stade Rennais,90,1,0,0
65,Lesley Ugochukwu,Stade Rennais,64,3,0,0
66,Andy Diouf,Stade Rennais,11,1,0,0
67,Matthis Abline,Stade Rennais,1,1,0,0
68,Dion Lopy,Stade de Reims,256,4,0,0
69,Hugo Ekitiké,Stade de Reims,86,2,0,0
70,Alexis Flips,Stade de Reims,41,2,1,0
71,Tristan Dingomé,Stade de Reims,14,1,0,0
72,Moise Sakava,Stade de Reims,8,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  AS Monaco  —  SF sin salario:

             player  minutesPlayed
0  Giulian Biancone             92

  CG plantilla completa:

                   player            player_norm
0       Aleksandr Golovin      aleksandr golovin
1     Aurélien Tchouaméni    aurelien tchouameni
2             Axel Disasi            axel disasi
3        Benjamin Lecomte       benjamin lecomte
4       Benoît Badiashile      benoit badiashile
5           Caio Henrique          caio henrique
6           Cesc Fàbregas          cesc fabregas
7       Chrislain Matsima      chrislain matsima
8          Djibril Sidibé         djibril sidibe
9            Eliot Matazo           eliot matazo
10            Enzo Millot            enzo millot
11             Florentino             florentino
12       Fodé Ballo-Touré       fode ballo toure
13         Gelson Martins         gelson martins
14      Guillermo Maripán      guillermo maripan
15         Henry Onyekuru         henry onyekuru
16               Jemerson               jemerson
17          Kevin Volland          kevin volland
18          Krépin Diatta          krepin diatta
19        Pietro Pellegri        pietro pellegri
20       Radoslaw Majecki       radoslaw majecki
21          Ruben Aguilar          ruben aguilar
22        Samuel Grandsir        samuel grandsir
23           Sofiane Diop           sofiane diop
24         Stevan Jovetic         stevan jovetic
25     Strahinja Pavlovic     strahinja pavlovic
26           Vito Mannone           vito mannone
27        Willem Geubbels        willem geubbels
28      Wissam Ben Yedder      wissam ben yedder
29  Youssef Aït Bennasser  youssef ait bennasser
30        Youssouf Fofana        youssouf fofana

============================================================
  Angers  —  SF sin salario:

                player  minutesPlayed
0  Baptiste Santamaria            270
1        Casimir Ninga             22
2        Rachid Alioui             14
3      Rayan Aït-Nouri            187
4       Wilfried Kanga            134
5       Yassin Fortune             14

  CG plantilla completa:

                  player           player_norm
0        Abdoulaye Bamba       abdoulaye bamba
1         Angelo Fulgini        angelo fulgini
2       Antonin Bobichon      antonin bobichon
3       Danijel Petkovic      danijel petkovic
4      Elhadji Pape Diaw     elhadji pape diaw
5            Enzo Ebosse           enzo ebosse
6        Farid El Melali       farid el melali
7         Haithem Loucif        haithem loucif
8         Ibrahim Amadou        ibrahim amadou
9          Ismaël Traoré         ismael traore
10           Jimmy Cabot           jimmy cabot
11         Kevin Bemanga         kevin bemanga
12            Kévin Boma            kevin boma
13     Lassana Coulibaly     lassana coulibaly
14            Loïs Diony            lois diony
15       Ludovic Butelle       ludovic butelle
16        Mateo Pavlovic        mateo pavlovic
17  Mathias Pereira Lage  mathias pereira lage
18       Mohamed-Ali Cho       mohamed ali cho
19            Noah Fatar            noah fatar
20       Paul Bernardoni       paul bernardoni
21      Pierrick Capelle      pierrick capelle
22         Romain Thomas         romain thomas
23           Sada Thioub           sada thioub
24        Sofiane Boufal        sofiane boufal
25     Souleyman Doumbia     souleyman doumbia
26      Stéphane Bahoken      stephane bahoken
27        Thomas Mangani        thomas mangani
28          Thomas Touré          thomas toure
29       Vincent Manceau       vincent manceau
30          Waniss Taïbi          waniss taibi
31  Zinédine Ould Khaled  zinedine ould khaled

============================================================
  Bordeaux  —  SF sin salario:

            player  minutesPlayed
0     Dilane Bakwa             67
1  Issouf Sissokho             75
2     Jimmy Briand            557
3        Josh Maja            815
4      Rubén Pardo             21
5       Sékou Mara            232

  CG plantilla completa:

                     player              player_norm
0             Amadou Traoré            amadou traore
1             Benoît Costil            benoit costil
2                David Kong               david kong
3             Enock Kwateng            enock kwateng
4            Gaëtan Poussin           gaetan poussin
5            Hatem Ben Arfa           hatem ben arfa
6            Ibrahim Diarra           ibrahim diarra
7                Ismaël Sow               ismael sow
8         Jean Michaël Seri        jean michael seri
9         Laurent Koscielny        laurent koscielny
10  Logan Delaurier-Chaubet  logan delaurier chaubet
11             Loïc Bessile             loic bessile
12             Loris Benito             loris benito
13           Maxime Poundjé           maxime poundje
14            Mehdi Zerkane            mehdi zerkane
15                    Mexer                    mexer
16      Nicolas de Préville      nicolas de preville
17                   Otávio                   otavio
18            Over Mandanda            over mandanda
19                    Pablo                    pablo
20              Paul Baysse              paul baysse
21               Rémi Oudin               remi oudin
22              Samuel Kalu              samuel kalu
23               Tom Lacoux               tom lacoux
24               Toma Basic               toma basic
25              Ui-jo Hwang              ui jo hwang
26        Vukasin Jovanovic        vukasin jovanovic
27              Yacine Adli              yacine adli
28          Youssouf Sabaly          youssouf sabaly

============================================================
  Dijon  —  SF sin salario:

               player  minutesPlayed
0    Aboubakar Kamara            560
1  Aurélien Scheidler            345
2      Charles Costes              1
3      Erwan Belhadji             29
4        Jacques Siwe            167
5      Rayan Philippe             98

  CG plantilla completa:

                  player           player_norm
0        Ahmad Ngouyamsa       ahmad ngouyamsa
1        Alexandru Dobre       alexandru dobre
2              Amir Arli             amir arli
3           Aníbal Chalá          anibal chala
4       Anthony Racioppi      anthony racioppi
5           Arthur Zagre          arthur zagre
6         Bersant Celina        bersant celina
7     Bruno Ecuele Manga    bruno ecuele manga
8           Didier Ndong          didier ndong
9            Éric Ebimbe           eric ebimbe
10          Fouad Chafik          fouad chafik
11  Frédéric Sammaritano  frederic sammaritano
12        Jonathan Panzo        jonathan panzo
13          Jordan Marié          jordan marie
14           Lévi Ntumba           levi ntumba
15            Mama Baldé            mama balde
16        Mounir Chouiar        mounir chouiar
17         Moussa Konaté         moussa konate
18        Ngonda Muzinga        ngonda muzinga
19           Pape Cheikh           pape cheikh
20          Roger Assalé          roger assale
21     Romain Amalfitano     romain amalfitano
22            Sacha Boey            sacha boey
23      Saturnin Allagbé      saturnin allagbe
24       Senou Coulibaly       senou coulibaly
25         Wesley Lautoa         wesley lautoa
26     Wilitty Younoussa     wilitty younoussa
27        Yassine Benzia        yassine benzia

============================================================
  Lorient  —  SF sin salario:

          player  minutesPlayed
0     Umut Bozok             58
1  Yoann Etienne             90

  CG plantilla completa:

                player         player_norm
0         Adrian Grbic        adrian grbic
1    Andreaw Gravillon   andreaw gravillon
2     Armand Laurienté    armand lauriente
3          Enzo Le Fée         enzo le fee
4       Fabien Lemoine      fabien lemoine
5       Franklin Wadja      franklin wadja
6    Houboulang Mendes   houboulang mendes
7         Jérémy Morel        jeremy morel
8      Jérôme Hergault     jerome hergault
9   Jonathan Delaplace  jonathan delaplace
10      Julien Laporte      julien laporte
11     Laurent Abergel     laurent abergel
12  Malamine Doumbouya  malamine doumbouya
13     Matthieu Dreyer     matthieu dreyer
14    Matthieu Saunier    matthieu saunier
15          Paul Nardi          paul nardi
16   Pierre-Yves Hamel   pierre yves hamel
17    Quentin Boisgard    quentin boisgard
18     Stéphane Diarra     stephane diarra
19    Sylvain Marveaux    sylvain marveaux
20     Teddy Bartouche     teddy bartouche
21         Terem Moffi         terem moffi
22      Thomas Callens      thomas callens
23     Thomas Fontaine     thomas fontaine
24   Thomas Monconduit   thomas monconduit
25         Tiago Ilori         tiago ilori
26     Trevoh Chalobah     trevoh chalobah
27     Vincent Le Goff     vincent le goff
28         Yoane Wissa         yoane wissa

============================================================
  Metz  —  SF sin salario:

                  player  minutesPlayed
0       Boubakar Kouyaté           1966
1  Cheick Tidiane Sabaly             11

  CG plantilla completa:

                  player           player_norm
0       Aaron Leya Iseka      aaron leya iseka
1           Adama Traoré          adama traore
2      Alexandre Oukidja     alexandre oukidja
3        Boubacar Traoré       boubacar traore
4            Dylan Bronn           dylan bronn
5         Ernest Boahene        ernest boahene
6        Fabien Centonze       fabien centonze
7          Farid Boulaya         farid boulaya
8            Habib Maïga           habib maiga
9         Ibrahima Niane        ibrahima niane
10             John Boye             john boye
11         Kévin N'Doram         kevin n doram
12          Kiki Kouyaté          kiki kouyate
13          Lamine Gueye          lamine gueye
14         Lenny Lacroix         lenny lacroix
15        Mamadou Fofana        mamadou fofana
16          Manuel Cabit          manuel cabit
17  Marc-Aurèle Caillard  marc aurele caillard
18         Matthieu Udol         matthieu udol
19           Opa Nguette           opa nguette
20      Papa Ndiaga Yade      papa ndiaga yade
21             Pape Sarr             pape sarr
22        Paul Delecroix        paul delecroix
23       Thierry Ambrose       thierry ambrose
24        Thomas Delaine        thomas delaine
25                Vagner                vagner
26      Victorien Angban      victorien angban
27         Vincent Pajot         vincent pajot
28     Warren Tchimbembé     warren tchimbembe
29         Youssef Maziz         youssef maziz

============================================================
  Montpellier  —  SF sin salario:

         player  minutesPlayed
0  Sacha Delaye             12

  CG plantilla completa:

              player       player_norm
0    Ambroise Oyongo   ambroise oyongo
1        Andy Delort       andy delort
2     Arnaud Souquet    arnaud souquet
3      Béni Makouana     beni makouana
4      Clément Vidal     clement vidal
5   Damien Le Tallec  damien le tallec
6      Daniel Congré     daniel congre
7    Dimitry Bertaud   dimitry bertaud
8          Elye Wahi         elye wahi
9     Florent Mollet    florent mollet
10    Gaëtan Laborde    gaetan laborde
11            Hilton            hilton
12        Il-lok Yun        il lok yun
13       Jonas Omlin       jonas omlin
14      Jordan Ferri      jordan ferri
15     Joris Chotard     joris chotard
16     Junior Sambia     junior sambia
17      Keagan Dolly      keagan dolly
18    Mathías Suárez    mathias suarez
19    Matis Carvalho    matis carvalho
20    Mihailo Ristic    mihailo ristic
21     Nicolas Cozza     nicolas cozza
22      Pedro Mendes      pedro mendes
23    Petar Skuletic    petar skuletic
24    Samy Benchamma    samy benchamma
25   Stephy Mavididi   stephy mavididi
26     Téji Savanier     teji savanier
27    Thibault Tamas    thibault tamas
28    Thibaut Vargas    thibaut vargas
29      Yanis Ammour      yanis ammour

============================================================
  Nantes  —  SF sin salario:

               player  minutesPlayed
0     Abdoulaye Sylla             12
1  Samuel Moutoussamy             83

  CG plantilla completa:

                      player               player_norm
0         Abdoul Kader Bamba        abdoul kader bamba
1            Abdoulaye Touré           abdoulaye toure
2               Alban Lafont              alban lafont
3             Andrei Girotto            andrei girotto
4           Anthony Limbombe          anthony limbombe
5              Batista Mendy             batista mendy
6               Bridge Ndilu              bridge ndilu
7             Charles Traoré            charles traore
8                 Charly Jan                charly jan
9               Denis Petric              denis petric
10             Dennis Appiah             dennis appiah
11                     Fábio                     fabio
12               Imran Louza               imran louza
13  Jean-Charles Castelletto  jean charles castelletto
14       Jean-Kévin Augustin       jean kevin augustin
15          Kalifa Coulibaly          kalifa coulibaly
16              Ludovic Blas              ludovic blas
17               Marcus Coco               marcus coco
18               Mehdi Abeid               mehdi abeid
19               Moses Simon               moses simon
20           Nicolas Pallois           nicolas pallois
21          Pedro Chirivella          pedro chirivella
22         Randal Kolo Muani         randal kolo muani
23              Renaud Emond              renaud emond
24        Roli Pereira de Sa        roli pereira de sa
25         Sébastien Corchia         sebastien corchia
26             Thomas Basila             thomas basila

============================================================
  Nice  —  SF sin salario:

             player  minutesPlayed
0    Eddy Sylvestre             96
1    Evann Guessand             27
2      Hicham Mahou             32
3    Malik Sellouki             66
4  Salim Ben Seghir             13

  CG plantilla completa:

                   player            player_norm
0   Alexis Claude-Maurice  alexis claude maurice
1        Alexis Trouillet       alexis trouillet
2            Amine Gouiri           amine gouiri
3            Andy Pelmard           andy pelmard
4               Dan Ndoye              dan ndoye
5                  Danilo                 danilo
6                   Dante                  dante
7             Deji Sotona            deji sotona
8        Flavius Daniliuc       flavius daniliuc
9          Hassane Kamara         hassane kamara
10        Hicham Boudaoui        hicham boudaoui
11      Jean-Clair Todibo      jean clair todibo
12    Jeff Reine-Adélaïde    jeff reine adelaide
13         Jordan Lotomba         jordan lotomba
14         Kasper Dolberg         kasper dolberg
15        Khéphren Thuram        khephren thuram
16    Morgan Schneiderlin    morgan schneiderlin
17        Myziane Maolida        myziane maolida
18      Pierre Lees Melou      pierre lees melou
19            Racine Coly            racine coly
20           Robson Bambu           robson bambu
21             Rony Lopes             rony lopes
22          Stanley Nsoki          stanley nsoki
23        Teddy Boulhendi        teddy boulhendi
24         Walter Benítez         walter benitez
25         William Saliba         william saliba
26         Yoan Cardinale         yoan cardinale
27            Youcef Atal            youcef atal

============================================================
  Nîmes Olympique  —  SF sin salario:

               player  minutesPlayed
0  Mahamadou Doucouré             46
1       Nassim Chadli             28

  CG plantilla completa:

              player       player_norm
0       Andrés Cubas      andres cubas
1   Anthony Briancon  anthony briancon
2    Antoine Valerio   antoine valerio
3    Baptiste Reynet   baptiste reynet
4      Birger Meling     birger meling
5     Clément Depres    clement depres
6     Florian Miguel    florian miguel
7     Gaëtan Paquiez    gaetan paquiez
8     Haris Duljevic    haris duljevic
9        Karim Aribi       karim aribi
10   Kelyan Guessoum   kelyan guessoum
11      Kévin Denkey      kevin denkey
12      Lamine Fomba      lamine fomba
13      Loïck Landre      loick landre
14      Lucas Buades      lucas buades
15       Lucas Deaux       lucas deaux
16        Lucas Dias        lucas dias
17     Marco Majouga     marco majouga
18    Mattéo Ahlinvi    matteo ahlinvi
19       Moussa Koné       moussa kone
20     Naomichi Ueda     naomichi ueda
21   Niclas Eliasson   niclas eliasson
22        Nolan Roux        nolan roux
23    Pablo Martinez    pablo martinez
24    Patrick Burner    patrick burner
25     Renaud Ripart     renaud ripart
26     Sami Ben Amar     sami ben amar
27         Sidy Sarr         sidy sarr
28  Sofiane Alakouch  sofiane alakouch
29  Yassine Benrahou  yassine benrahou
30   Zinedine Ferhat   zinedine ferhat

============================================================
  Olympique Lyonnais  —  SF sin salario:

                     player  minutesPlayed
0  Florent Sanchez Da Silva              2
1               Habib Keita              8
2          Joachim Andersen            191
3                Kenny Tete             20
4                Malo Gusto              2
5                    Marçal             79

  CG plantilla completa:

                    player             player_norm
0            Anthony Lopes           anthony lopes
1          Bruno Guimarães         bruno guimaraes
2                   Camilo                  camilo
3             Cenk Özkacar            cenk ozkacar
4   Djamel Eddine Benlamri  djamel eddine benlamri
5            Houssem Aouar           houssem aouar
6            Islam Slimani           islam slimani
7            Jason Denayer           jason denayer
8               Jean Lucas              jean lucas
9       Julian Pollersbeck      julian pollersbeck
10        Karl Toko Ekambi        karl toko ekambi
11              Léo Dubois              leo dubois
12           Lucas Paquetá           lucas paqueta
13         Malcolm Barcola         malcolm barcola
14                 Marcelo                 marcelo
15       Mattia De Sciglio       mattia de sciglio
16        Maxence Caqueret        maxence caqueret
17           Maxwel Cornet           maxwel cornet
18             Melvin Bard             melvin bard
19           Memphis Depay           memphis depay
20          Moussa Dembélé          moussa dembele
21            Rayan Cherki            rayan cherki
22         Sinaly Diomandé         sinaly diomande
23           Thiago Mendes           thiago mendes
24           Tino Kadewere           tino kadewere
25           Yahya Soumaré           yahya soumare

============================================================
  Olympique de Marseille  —  SF sin salario:

                player  minutesPlayed
0  Ahmadou Bamba Dieng            149
1           Bouna Sarr             75
2         Maxime López            139

  CG plantilla completa:

                    player             player_norm
0           Aaron Kamardin          aaron kamardin
1     Alexandre Phliponeau    alexandre phliponeau
2          Álvaro González         alvaro gonzalez
3          Arkadiusz Milik         arkadiusz milik
4          Boubacar Kamara         boubacar kamara
5            Cheick Souaré           cheick souare
6      Christopher Rocchia     christopher rocchia
7          Darío Benedetto         dario benedetto
8            Dimitri Payet           dimitri payet
9          Duje Caleta-Car         duje caleta car
10       Florian Chabrolle       florian chabrolle
11         Florian Thauvin         florian thauvin
12           Franco Tongya           franco tongya
13            Hiroki Sakai            hiroki sakai
14            Jordan Amavi            jordan amavi
15             Jorès Rahou             jores rahou
16         Kevin Strootman         kevin strootman
17  Konstantinos Mitroglou  konstantinos mitroglou
18        Leonardo Balerdi        leonardo balerdi
19            Lucas Perrin            lucas perrin
20           Luis Henrique           luis henrique
21              Marley Aké              marley ake
22        Michaël Cuisance        michael cuisance
23           Morgan Sanson           morgan sanson
24            Nassim Ahmed            nassim ahmed
25        Nemanja Radonjic        nemanja radonjic
26          Olivier Ntcham          olivier ntcham
27              Pape Gueye              pape gueye
28              Pol Lirola              pol lirola
29       Richecard Richard       richecard richard
30      Saîf-Eddine Khaoui      saif eddine khaoui
31    Simon Ngapandouetnbu    simon ngapandouetnbu
32          Steve Mandanda          steve mandanda
33            Ugo Bertelli            ugo bertelli
34        Valentin Rongier        valentin rongier
35          Valère Germain          valere germain
36             Yohann Pelé             yohann pele
37           Yuto Nagatomo           yuto nagatomo

============================================================
  Paris Saint-Germain  —  SF sin salario:

           player  minutesPlayed
0  Jesé Rodríguez             22
1    Kenny Nagera              1
2    Marcin Bułka             90
3  Édouard Michut              1

  CG plantilla completa:

                 player          player_norm
0          Abdou Diallo         abdou diallo
1   Alessandro Florenzi  alessandro florenzi
2   Alexandre Letellier  alexandre letellier
3         Ander Herrera        ander herrera
4        Ángel Di María       angel di maria
5     Bandiougou Fadiga    bandiougou fadiga
6           Colin Dagba          colin dagba
7        Danilo Pereira       danilo pereira
8         Denis Franchi        denis franchi
9         Idrissa Gueye        idrissa gueye
10                 Jesé                 jese
11          Juan Bernat          juan bernat
12       Julian Draxler       julian draxler
13       Kays Ruiz-Atil       kays ruiz atil
14         Keylor Navas         keylor navas
15        Kylian Mbappé        kylian mbappe
16       Layvin Kurzawa       layvin kurzawa
17      Leandro Paredes      leandro paredes
18       Marco Verratti       marco verratti
19           Marquinhos           marquinhos
20  Mathyas Randriamamy  mathyas randriamamy
21         Mauro Icardi         mauro icardi
22           Maxen Kapo           maxen kapo
23       Mitchel Bakker       mitchel bakker
24           Moise Kean           moise kean
25               Neymar               neymar
26        Pablo Sarabia        pablo sarabia
27     Presnel Kimpembe     presnel kimpembe
28              Rafinha              rafinha
29          Sergio Rico          sergio rico
30         Thilo Kehrer         thilo kehrer
31     Timothée Pembélé     timothee pembele
32          Xavi Simons          xavi simons
33        Yanis Saidani        yanis saidani

============================================================
  RC Lens  —  SF sin salario:

           player  minutesPlayed
0  Adrien Louveau             11
1       Ansou Sow              5
2    Manuel Perez            127

  CG plantilla completa:

                    player             player_norm
0             Adam Oudjani            adam oudjani
1   Aleksandar Radovanovic  aleksandar radovanovic
2        Arnaud Kalimuendo       arnaud kalimuendo
3             Charles Boli            charles boli
4          Cheick Doucouré         cheick doucoure
5            Cheick Traoré           cheick traore
6         Clément Michelin        clement michelin
7            Corentin Jean           corentin jean
8           Cyrille Bayala          cyrille bayala
9              David Costa             david costa
10          Didier Desprez          didier desprez
11          Facundo Medina          facundo medina
12          Florian Sotoca          florian sotoca
13             Gaël Kakuta             gael kakuta
14         Ignatius Ganago         ignatius ganago
15            Ismaël Boura            ismael boura
16           Issiaga Sylla           issiaga sylla
17         Jean-Louis Leca         jean louis leca
18         Jonathan Clauss         jonathan clauss
19         Jonathan Gradit         jonathan gradit
20               Loïc Badé               loic bade
21        Massadio Haidara        massadio haidara
22             Seko Fofana             seko fofana
23             Simon Banza             simon banza
24           Steven Fortes           steven fortes
25           Tony Mauricio           tony mauricio
26         Wuilker Fariñez         wuilker farinez
27         Yannick Cahuzac         yannick cahuzac
28          Zakaria Diallo          zakaria diallo

============================================================
  RC Strasbourg  —  SF sin salario:

            player  minutesPlayed
0  Dion Moise Sahi             91

  CG plantilla completa:

                    player             player_norm
0         Adrien Thomasson        adrien thomasson
1          Alexander Djiku         alexander djiku
2             Anthony Caci            anthony caci
3         Bingourou Kamara        bingourou kamara
4          Dimitri Liénard         dimitri lienard
5           Eiji Kawashima          eiji kawashima
6        Frédéric Guilbert       frederic guilbert
7             Habib Diallo            habib diallo
8         Ibrahima Sissoko        ibrahima sissoko
9             Idriss Saadi            idriss saadi
10           Ismaël Aaneba           ismael aaneba
11       Jean-Eudes Aholou       jean eudes aholou
12  Jean-Ricner Bellegarde  jean ricner bellegarde
13              Kenny Lala              kenny lala
14              Kévin Zohi              kevin zohi
15             Lamine Koné             lamine kone
16            Lebo Mothiba            lebo mothiba
17           Lionel Carole           lionel carole
18         Ludovic Ajorque         ludovic ajorque
19             Mahame Siby             mahame siby
20            Majeed Waris            majeed waris
21               Matz Sels               matz sels
22           Mehdi Chahiri           mehdi chahiri
23         Mohamed Simakan         mohamed simakan
24            Sanjin Prcic            sanjin prcic
25         Stefan Mitrovic         stefan mitrovic

============================================================
  Saint-Étienne  —  SF sin salario:

                  player  minutesPlayed
0        Anthony Modeste            294
1         Assane Dioussé              1
2        Baptiste Gabard            134
3   Jean-Philippe Krasso            220
4      Marvin Tshibuabua             42
5           Mathys Saban             12
6           Rayan Souici              9
7           Tyron Tormin             18
8           Wahbi Khazri           1191
9          Wesley Fofana            315
10           Yanis Lhéry             29
11           Yann M'Vila             19

  CG plantilla completa:

                    player             player_norm
0         Abdoulaye Sidibé        abdoulaye sidibe
1           Adil Aouchiche          adil aouchiche
2           Aimen Moueffek          aimen moueffek
3            Alpha Sissoko           alpha sissoko
4            Arnaud Nordin           arnaud nordin
5          Bilal Benkhedim         bilal benkhedim
6            Boubacar Fall           boubacar fall
7              Charles Abi             charles abi
8            Denis Bouanga           denis bouanga
9            Etienne Green           etienne green
10           Gabriel Silva           gabriel silva
11         Harold Moukoudi         harold moukoudi
12            Jessy Moulin            jessy moulin
13     Kévin Monnet-Paquet     kevin monnet paquet
14     Lucas Gourna-Douath     lucas gourna douath
15            Mahdi Camara            mahdi camara
16         Mathieu Debuchy         mathieu debuchy
17          Maxence Rivera          maxence rivera
18           Miguel Trauco           miguel trauco
19       Panagiotis Retsos       panagiotis retsos
20         Pape Abou Cissé         pape abou cisse
21          Romain Hamouma          romain hamouma
22          Ryad Boudebouz          ryad boudebouz
23              Saïdou Sow              saidou sow
24            Stefan Bajic            stefan bajic
25        Stéphane Ruffier        stephane ruffier
26  Timothée Kolodziejczak  timothee kolodziejczak
27              Yvan Neyou              yvan neyou
28             Yvann Maçon             yvann macon
29         Zaydou Youssouf         zaydou youssouf

============================================================
  Stade Brestois  —  SF sin salario:

            player  minutesPlayed
0  Ibrahima Diallo            442

  CG plantilla completa:

                   player            player_norm
0       Bandiougou Fadiga      bandiougou fadiga
1      Brendan Chardonnet     brendan chardonnet
2      Christophe Hérelle     christophe herelle
3     Cristian Battocchio    cristian battocchio
4              Denys Bain             denys bain
5           Ferris N'Goma          ferris n goma
6          Franck Honorat         franck honorat
7      Gaëtan Charbonnier     gaetan charbonnier
8      Gautier Larsonneur     gautier larsonneur
9          Haris Belkebla         haris belkebla
10      Heriberto Tavares      heriberto tavares
11         Hianga'a MBock         hianga a mbock
12          Hugo Magnetti          hugo magnetti
13           Idrissa Dioh           idrissa dioh
14          Irvin Cardona          irvin cardona
15     Jean-Kevin Duverne     jean kevin duverne
16             Jean Lucas             jean lucas
17      Jérémy Le Douaron      jeremy le douaron
18      Julien Faussurier      julien faussurier
19        Lilian Brassier        lilian brassier
20           Ludovic Baal           ludovic baal
21           Mouez Hassen           mouez hassen
22             Paul Lasne             paul lasne
23            Rafiki Saïd            rafiki said
24          Romain Faivre          romain faivre
25         Romain Perraud         romain perraud
26   Romain Philippoteaux   romain philippoteaux
27  Ronaël Pierre-Gabriel  ronael pierre gabriel
28       Sébastien Cibois       sebastien cibois
29           Steve Mounié           steve mounie

============================================================
  Stade Rennais  —  SF sin salario:

             player  minutesPlayed
0        Andy Diouf             11
1     Edouard Mendy             90
2  Lesley Ugochukwu             64
3    Matthis Abline              1
4          Raphinha            407

  CG plantilla completa:

                 player          player_norm
0          Adrien Hunou         adrien hunou
1       Adrien Truffert      adrien truffert
2          Alfred Gomis         alfred gomis
3   Benjamin Bourigeaud  benjamin bourigeaud
4         Brandon Soppy        brandon soppy
5       Clément Grenier      clement grenier
6               Dalbert              dalbert
7       Damien Da Silva      damien da silva
8        Daniele Rugani       daniele rugani
9     Eduardo Camavinga    eduardo camavinga
10     Faitout Maouassa     faitout maouassa
11         Flavien Tait         flavien tait
12     Georginio Rutter     georginio rutter
13       Gerzino Nyamsi       gerzino nyamsi
14        Hamari Traoré        hamari traore
15     James Léa Siliki     james lea siliki
16          Jérémy Doku          jeremy doku
17         Jonas Martin         jonas martin
18         M'Baye Niang         m baye niang
19       Martin Terrier       martin terrier
20         Nayef Aguerd         nayef aguerd
21           Pépé Bonet           pepe bonet
22  Romain Del Castillo  romain del castillo
23         Romain Salin         romain salin
24      Serhou Guirassy      serhou guirassy
25        Steven Nzonzi        steven nzonzi
26           Yann Gboho           yann gboho

============================================================
  Stade de Reims  —  SF sin salario:

            player  minutesPlayed
0     Alexis Flips             41
1        Dion Lopy            256
2     Hugo Ekitiké             86
3     Moise Sakava              8
4  Tristan Dingomé             14

  CG plantilla completa:

                player         player_norm
0     Anastasios Donis    anastasios donis
1         Arbër Zeneli        arber zeneli
2          Boulaye Dia         boulaye dia
3        Dario Maresic       dario maresic
4        Dereck Kutesa       dereck kutesa
5         Dialy Ndiaye        dialy ndiaye
6       El Bilal Touré      el bilal toure
7        Fodé Doucouré       fode doucoure
8        Fraser Hornby       fraser hornby
9       Ghislain Konan      ghislain konan
10        Kaj Sierhuis        kaj sierhuis
11    Marshall Munetsi    marshall munetsi
12      Mathieu Cafaro      mathieu cafaro
13      Moreto Cassamá      moreto cassama
14  Mouhamadou Drammeh  mouhamadou drammeh
15      Moussa Doumbia      moussa doumbia
16     Nathanaël Mbuku     nathanael mbuku
17    Predrag Rajkovic    predrag rajkovic
18    Thibault De Smet    thibault de smet
19        Thomas Foket        thomas foket
20       Valon Berisha       valon berisha
21           Wout Faes           wout faes
22   Xavier Chavalerin   xavier chavalerin
23       Yehvann Diouf       yehvann diouf
24    Yunis Abdelhamid    yunis abdelhamid

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('boubakar kouyate', 'metz'): ('kiki kouyate', 'metz'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: boubakar kouyate (metz) → kiki kouyate (metz)

Tras matches manuales: 501/573 (87.4%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_france_2021.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_france_2021.csv
   Jugadores totales:  573
   Con salario:        501
   Sin salario (NaN):  72
   Columnas:           121