# 03 · Join Sofascore + Capology — France Ligue 1 25/26 (snapshot 20260428)

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2025/26 de la Ligue 1 francesa**.

⚠️ **Nota sobre el snapshot:** la temporada 25/26 está aún en curso. Se trabaja con
una foto fija de Sofascore (`df_france_2526_snapshot_20260428.csv`). Este notebook
deberá reejecutarse con los datos definitivos cuando finalice la liga, generando
entonces el master sin sufijo de fecha (`master_france_2526.csv`).

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_france_2526_snapshot_20260428.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_france_2526.csv').copy()

print(f'Sofascore (snapshot):  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:              {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore (snapshot):  537 jugadores | 117 columnas
Capology:              501 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   as monaco
   olympique de marseille
   olympique lyonnais
   paris saint germain
   rc lens
   rc strasbourg
   stade brestois
   stade rennais

En Capology pero no en Sofascore:
   brest
   lens
   lyon
   marseille
   monaco
   psg
   rennes
   strasbourg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [9]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brest':'stade brestois',
            'lens':'rc lens',
            'lyon':'olympique lyonnais',
            'olympique marseille':'olympique de marseille',
            'monaco':'as monaco',
            'psg':'paris saint germain',
            'rennes':'stade rennais',
            'strasbourg':'rc strasbourg'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [10]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 412/537 (76.7%)
Sin emparejar: 125

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [11]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          9
Revisión media    (0.75 ≤ score < 0.90):   13
Revisión estricta (0.50 ≤ score < 0.75):   55
Revisión muy est. (score < 0.50):           48

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [12]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
51,Radosław Majecki,Stade Brestois,radoslaw majecki,0.968
9,Emmanuel Emegha,RC Strasbourg,emanuel emegha,0.966
52,Waren Kamanzi,Toulouse,warren kamanzi,0.963
80,Darlin Yongwa,Lorient,darline yongwa,0.963
45,Luc Zogbé,Stade Brestois,luck zogbe,0.947
32,Habibou Diallo,Metz,habib diallo,0.923
96,Elias Legendre Quiñonez Zae,Stade Rennais,elias legendre quinonez,0.920
16,Ali Youssef,Nantes,ali youssif,0.909
54,Bahereba Guirassy,Nantes,herba guirassy,0.903

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [13]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
13,Mousa Tamari,Stade Rennais,mousa al tamari,0.889
35,Ibou Sane,Metz,sadibou sane,0.857
4,Matías Fernández,Lille,matias fernandez pardo,0.842
28,Urie-Michel Mboula,Metz,michel mboula,0.839
27,Ignatius Kpene Ganago,Nantes,ignatius ganago,0.833
53,Morgan Bokele Mputu,Metz,morgan bokele,0.812
34,Tim Weah,Olympique de Marseille,timothy weah,0.800
5,Arthur Avom Ebong,Lorient,arthur avom,0.786
33,Stanis Idumbo Muzambo,AS Monaco,stanis idumbo,0.765
94,Samir Sophian Chergui,Paris FC,samir chergui,0.765
17,Noam Obougou Jacquet,Le Havre,noam obougou,0.750
8,Pape Diop,Toulouse,pape demba diop,0.750
105,Kevin Carlos Omoruyi,Nice,kevin carlos,0.750

In [14]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['ibou sane'

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 12 | Excluidos: 1

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [15]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                   player_sf                    team           cg_match  score
56    Daren Nbenbege Mosengo                Le Havre      daren mosengo  0.743
39              Amir Murillo  Olympique de Marseille    michael murillo  0.741
18       Ahmadou Bamba Dieng                 Lorient        bamba dieng  0.733
49   Conrad Jaden Egan-Riley  Olympique de Marseille      cj egan riley  0.722
47        Alexsandro Ribeiro                   Lille         alexsandro  0.714
74        Joel Mugisha Mvuka                 Lorient         joel mvuka  0.714
73     Cheick Tidiane Sabaly                    Metz      cheikh sabaly  0.706
93              Ally Samatta                Le Havre     mbwana samatta  0.692
26          Abdulay Juma Bah                    Nice           juma bah  0.667
12            Moustapha Mbow                Paris FC       mamadou mbow  0.615
76              Serigne Diop          Stade Brestois        saliou diop  0.609
124             Lucas Rosier           Stade Rennais    lilian brassier  0.593
48              Danny Namaso                 Auxerre       danny loader  0.583
92             Adrien Rabiot  Olympique de Marseille        amine harit  0.583
64             Ibrahim Salah           Stade Rennais        brice samba  0.583
60               Pape Cabral               AS Monaco      lamine camara  0.583
97          Joseph N'Duquidi                    Metz    joseph mangondo  0.581
112        Mathieu Acapandié                  Nantes     matthis abline  0.581
104            Fabian Rieder           Stade Rennais    lilian brassier  0.571
44               Bané Diatta                  Angers         dan sinate  0.571
70             Mayckel Lahdo                  Nantes       remy cabella  0.560
30              Matt O'Riley  Olympique de Marseille      cj egan riley  0.560
119              Martin Bley                 Lorient     benjamin leroy  0.560
62              Malick Mbaye                    Metz      michel mboula  0.560
42            Erawan Garnier                 RC Lens        malang sarr  0.560
118           Hamza Koutoune                    Nice    hicham boudaoui  0.552
10               Michel Diaz          Stade Brestois        junior diaz  0.545
86              Amadou Cissé           RC Strasbourg         saidou sow  0.545
87               Mathis Saka                Toulouse        mario sauer  0.545
22              Mamadou Sarr           RC Strasbourg         saidou sow  0.545
36             Karim Dermane                 Lorient      dermane karim  0.538
88            Zoumana Diallo                    Nice       sofiane diop  0.538
90             Idrissa Gueye                    Metz      ismael guerti  0.538
108            Jonathan Rowe  Olympique de Marseille      ethan nwaneri  0.538
109          Tadjidine Mmadi  Olympique de Marseille        amine harit  0.538
25              Rémi Himbert      Olympique Lyonnais     ruben kluivert  0.538
19           Jahyann Pandore                    Metz        alpha toure  0.538
24         Morgan Guilavogui                 RC Lens      ruben aguilar  0.533
63        Badredine Bouanani                    Nice       jeremie boga  0.533
68          Félix Lemaréchal           RC Strasbourg     emanuel emegha  0.533
78            Bernard Nguene                    Nice   gabin bernardeau  0.533
122     Henrick Do Marcolino           Stade Rennais     quentin merlin  0.529
15            Abner Vinícius      Olympique Lyonnais              abner  0.526
75                 Theo Bair                 Auxerre         sekou mara  0.526
81               Terem Moffi                    Nice       jeremie boga  0.522
58          Tyrese Noubissie           RC Strasbourg    gessime yassine  0.516
46          Djibirin Harouna                  Angers   harouna djibirin  0.500
121               Yvan Zaddy                 Auxerre         ryan rodin  0.500
120           Samuel Nibombe               AS Monaco         paul pogba  0.500
107    Ugo Lamare El Kadmiri  Olympique de Marseille        bilal nadir  0.500
99             Daniel Semedo                 Lorient    nathaniel adjei  0.500
65       Justin-Noel Kalumba                  Angers  goduine koyalipou  0.500
14              Nathan Mbala                    Metz   jonathan fischer  0.500
69             Kaïl Boudache                    Nice    hicham boudaoui  0.500
83                Noah Nsoki     Paris Saint-Germain         joao neves  0.500

In [19]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['daren nbenbege mosengo',
                    'amir murillo',
                    'ahmadou bamba dieng',
                    'conrad jaden egan riley',
                    'alexsandro ribeiro',
                    'joel mugisha mvuka',
                    'cheick tidiane sabaly',
                    'ally samatta',
                    'abdulay juma bah',
                    'moustapha mbow',
                    'serigne diop',
                    'danny namaso',
                    'joseph n duquidi',
                    'michel diaz',
                    'karim dermane',
                    'abner vinicius',
                    'djibirin harouna'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 17

### 7.4 Revisión muy estricta (score < 0.50)

Candidatos con muy baja similitud. Por defecto ninguno se acepta.
Añadir a `ACCEPT_VERY_LOW_FUZZY` los que se confirmen manualmente.

In [20]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
6,Brad-Hamilton Mantsounga,Nice,morgan sanson,0.486
7,Julien Le Cardinal,Stade Brestois,romain del castillo,0.486
3,Georges Mikautadze,Olympique Lyonnais,moussa niakhate,0.485
114,Justin Bourgault,Stade Brestois,lucas tousart,0.483
67,Younes Namli,Le Havre,lionel mpasi nzau,0.483
29,Robinio Vaz,Olympique de Marseille,geronimo rulli,0.480
50,Gabriel Osho,Auxerre,gideon mensah,0.480
106,Enzo Molebe,Olympique Lyonnais,afonso moreira,0.480
59,Ilyas Azizi,Toulouse,niklas schmidt,0.480
21,Pablo Rosario,Nice,ali abdi,0.476
79,Adil Hamdani,Olympique Lyonnais,ainsley maitland niles,0.471
37,Mohamed Kader Meite,Stade Rennais,mousa al tamari,0.471
72,Believe Munongo,Metz,joseph mangondo,0.467
89,Mohamed Benoit-Dao,Paris FC,mamadou mbow,0.467
55,Soriba Diaoune,Lille,noah edjouma,0.462
41,Billal Brahimi,Nice,ali abdi,0.455
103,Saël Kumbedi,Olympique Lyonnais,pavel sulc,0.455
98,Axel Camblan,Stade Brestois,kenny lala,0.455
1,Andy Diouf,RC Lens,rayan fofana,0.455
101,Eliesse Ben Seghir,AS Monaco,paris brunner,0.452
95,Damián Pizarro,Le Havre,lionel mpasi nzau,0.452
61,Hong Hyun-seok,Nantes,anthony lopes,0.444
84,Mathis Jangeal,Paris Saint-Germain,lucas beraldo,0.444
85,Ugo Raghouber,Lille,osame sahraoui,0.444
111,Vincent Burlet,Lille,ousmane toure,0.444
11,Formose Mendy,Lorient,bamo meite,0.435
43,Maxima Goffi,Lille,aissa mandi,0.435
71,Brian Madjo,Metz,habib diallo,0.435
82,Kendry Páez,RC Strasbourg,mike penders,0.435
57,Enzo Koffi,Le Havre,yanis zouaoui,0.435
40,Mikayil Faye,Stade Rennais,mathys silistrie,0.429
38,Thomas Delaine,Le Havre,rassoul ndiaye,0.429
0,Dilane Bakwa,RC Strasbourg,sebastian nanasi,0.429
113,Everton Pereira,Nice,tiago gouveia,0.429
123,Mamoudou Cissokho,Auxerre,naouirou ahamada,0.424
20,Derek Cornelius,Olympique de Marseille,geoffrey kondogbia,0.424
31,Steeve Kango,Olympique Lyonnais,orel mangala,0.417
91,Darryl Bakola,Olympique de Marseille,neal maupay,0.417
77,George Ilenikhena,AS Monaco,philipp kohn,0.414
66,Sidiki Cherif,Angers,pierrick capelle,0.414
110,Rabby Nzingoula,RC Strasbourg,aaron anselmino,0.400
115,Idrissa Sabaly,RC Strasbourg,sebastian nanasi,0.400
102,Nouhoum Kamissoko,Olympique de Marseille,tochukwu nnadi,0.387
2,Jaydee Canvot,Toulouse,jacen russell rowe,0.387
100,Pol Lirola,Olympique de Marseille,igor paixao,0.381
23,Hyeok-kyu Kwon,Nantes,anthony lopes,0.370
116,Christopher Wooh,Stade Rennais,breel embolo,0.357
117,Bertuğ Yıldırım,Stade Rennais,brice samba,0.348

In [21]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [22]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 450/537 (83.8%)
Sin salario:     87

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [23]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 87

,player,team,minutesPlayed,appearances,goals,assists
0,George Ilenikhena,AS Monaco,386,15,2,0
1,Pape Cabral,AS Monaco,73,4,0,0
2,Eliesse Ben Seghir,AS Monaco,43,2,0,0
3,Samuel Nibombe,AS Monaco,1,1,0,0
4,Sidiki Cherif,Angers,1164,19,4,0
5,Justin-Noel Kalumba,Angers,225,4,0,0
6,Bané Diatta,Angers,9,1,0,0
7,Gabriel Osho,Auxerre,134,2,0,0
8,Theo Bair,Auxerre,23,2,0,0
9,Yvan Zaddy,Auxerre,1,1,0,0
10,Mamoudou Cissokho,Auxerre,1,1,0,0
11,Younes Namli,Le Havre,340,12,0,1
12,Enzo Koffi,Le Havre,317,11,0,0
13,Thomas Delaine,Le Havre,200,5,0,0
14,Damián Pizarro,Le Havre,26,2,0,0
15,Soriba Diaoune,Lille,202,10,1,1
16,Maxima Goffi,Lille,38,1,0,0
17,Vincent Burlet,Lille,18,1,0,0
18,Ugo Raghouber,Lille,10,1,0,0
19,Formose Mendy,Lorient,135,2,0,0
20,Daniel Semedo,Lorient,10,1,0,0
21,Martin Bley,Lorient,1,1,0,0
22,Ibou Sane,Metz,555,16,1,1
23,Nathan Mbala,Metz,334,11,2,2
24,Believe Munongo,Metz,332,8,0,0
25,Malick Mbaye,Metz,299,5,0,0
26,Brian Madjo,Metz,162,5,0,0
27,Idrissa Gueye,Metz,130,3,0,0
28,Jahyann Pandore,Metz,61,2,1,0
29,Hyeok-kyu Kwon,Nantes,764,12,0,0
30,Mayckel Lahdo,Nantes,418,8,1,1
31,Hong Hyun-seok,Nantes,284,6,0,0
32,Mathieu Acapandié,Nantes,113,4,0,0
33,Terem Moffi,Nice,489,10,2,0
34,Kaïl Boudache,Nice,419,11,1,0
35,Everton Pereira,Nice,137,3,0,0
36,Bernard Nguene,Nice,133,6,0,0
37,Badredine Bouanani,Nice,93,2,0,0
38,Brad-Hamilton Mantsounga,Nice,90,1,0,0
39,Pablo Rosario,Nice,27,1,0,0
40,Zoumana Diallo,Nice,9,1,0,0
41,Billal Brahimi,Nice,8,1,0,0
42,Hamza Koutoune,Nice,1,1,0,0
43,Georges Mikautadze,Olympique Lyonnais,179,2,1,0
44,Rémi Himbert,Olympique Lyonnais,139,6,1,0
45,Steeve Kango,Olympique Lyonnais,86,4,0,0
46,Saël Kumbedi,Olympique Lyonnais,66,1,0,0
47,Adil Hamdani,Olympique Lyonnais,28,4,0,0
48,Enzo Molebe,Olympique Lyonnais,9,1,0,0
49,Matt O'Riley,Olympique de Marseille,739,15,1,2
50,Robinio Vaz,Olympique de Marseille,393,14,4,2
51,Darryl Bakola,Olympique de Marseille,90,8,0,0
52,Adrien Rabiot,Olympique de Marseille,90,1,0,0
53,Jonathan Rowe,Olympique de Marseille,63,1,0,0
54,Derek Cornelius,Olympique de Marseille,57,2,0,0
55,Tadjidine Mmadi,Olympique de Marseille,46,3,0,0
56,Pol Lirola,Olympique de Marseille,42,3,0,0
57,Ugo Lamare El Kadmiri,Olympique de Marseille,14,1,0,0
58,Nouhoum Kamissoko,Olympique de Marseille,10,1,0,0
59,Mohamed Benoit-Dao,Paris FC,9,1,0,0
60,Noah Nsoki,Paris Saint-Germain,15,1,0,0
61,Mathis Jangeal,Paris Saint-Germain,10,1,0,0
62,Morgan Guilavogui,RC Lens,485,16,1,0
63,Andy Diouf,RC Lens,90,1,0,0
64,Erawan Garnier,RC Lens,14,1,0,0
65,Mamadou Sarr,RC Strasbourg,1305,15,0,0
66,Félix Lemaréchal,RC Strasbourg,554,11,0,2
67,Kendry Páez,RC Strasbourg,431,15,1,0
68,Dilane Bakwa,RC Strasbourg,105,3,1,2
69,Amadou Cissé,RC Strasbourg,90,1,0,0
70,Rabby Nzingoula,RC Strasbourg,62,4,0,0
71,Idrissa Sabaly,RC Strasbourg,57,1,0,0
72,Tyrese Noubissie,RC Strasbourg,8,1,0,0
73,Julien Le Cardinal,Stade Brestois,327,5,1,0
74,Justin Bourgault,Stade Brestois,15,1,0,0
75,Axel Camblan,Stade Brestois,11,1,0,0
76,Mohamed Kader Meite,Stade Rennais,530,17,3,2
77,Fabian Rieder,Stade Rennais,139,3,0,0
78,Christopher Wooh,Stade Rennais,64,2,0,0
79,Ibrahim Salah,Stade Rennais,40,2,0,0
80,Mikayil Faye,Stade Rennais,12,1,0,0
81,Bertuğ Yıldırım,Stade Rennais,2,1,0,0
82,Henrick Do Marcolino,Stade Rennais,2,1,0,0
83,Lucas Rosier,Stade Rennais,2,2,0,0
84,Jaydee Canvot,Toulouse,180,2,0,0
85,Ilyas Azizi,Toulouse,22,2,0,0
86,Mathis Saka,Toulouse,8,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [24]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  AS Monaco  —  SF sin salario:

               player  minutesPlayed
0  Eliesse Ben Seghir             43
1   George Ilenikhena            386
2         Pape Cabral             73
3      Samuel Nibombe              1

  CG plantilla completa:

               player        player_norm
0        Aladji Bamba       aladji bamba
1   Aleksandr Golovin  aleksandr golovin
2           Ansu Fati          ansu fati
3       Caio Henrique      caio henrique
4   Christian Mawissa  christian mawissa
5       Denis Zakaria      denis zakaria
6           Edan Diop          edan diop
7           Eric Dier          eric dier
8     Folarin Balogun    folarin balogun
9         Jordan Teze        jordan teze
10    Jules Stawiecki    jules stawiecki
11   Kassoum Ouattara   kassoum ouattara
12      Krépin Diatta      krepin diatta
13      Lamine Camara      lamine camara
14       Lucas Michal       lucas michal
15     Lukas Hradecky     lukas hradecky
16  Maghnes Akliouche  maghnes akliouche
17  Mamadou Coulibaly  mamadou coulibaly
18       Mika Biereth       mika biereth
19    Mohammed Salisu    mohammed salisu
20      Paris Brunner      paris brunner
21         Paul Pogba         paul pogba
22       Philipp Köhn       philipp kohn
23      Simon Adingra      simon adingra
24      Stanis Idumbo      stanis idumbo
25    Takumi Minamino    takumi minamino
26       Thilo Kehrer       thilo kehrer
27          Vanderson          vanderson
28          Wout Faes          wout faes
29       Yann Lienard       yann lienard

============================================================
  Angers  —  SF sin salario:

                player  minutesPlayed
0          Bané Diatta              9
1  Justin-Noel Kalumba            225
2        Sidiki Cherif           1164

  CG plantilla completa:

                   player            player_norm
0         Abdoulaye Bamba        abdoulaye bamba
1              Amine Sbaï             amine sbai
2   Branco van den Boomen  branco van den boomen
3           Carlens Arcus          carlens arcus
4              Dan Sinaté             dan sinate
5         Emmanuel Biumla        emmanuel biumla
6           Florent Hanin          florent hanin
7       Goduine Koyalipou      goduine koyalipou
8          Haris Belkebla         haris belkebla
9        Harouna Djibirin       harouna djibirin
10            Hervé Koffi            herve koffi
11         Jacques Ekomié         jacques ekomie
12          Jim Allevinah          jim allevinah
13          Jordan Lefort          jordan lefort
14         Lanroy Machine         lanroy machine
15        Lilian Raolisoa        lilian raolisoa
16           Louis Mouton           louis mouton
17        Marius Courcoul        marius courcoul
18           Marius Louër           marius louer
19           Melvin Zinga           melvin zinga
20             Oumar Pona             oumar pona
21         Ousmane Camara         ousmane camara
22       Pierrick Capelle       pierrick capelle
23          Prosper Peter          prosper peter
24        Yassin Belkhdim        yassin belkhdim

============================================================
  Auxerre  —  SF sin salario:

              player  minutesPlayed
0       Gabriel Osho            134
1  Mamoudou Cissokho              1
2          Theo Bair             23
3         Yvan Zaddy              1

  CG plantilla completa:

                 player          player_norm
0       Alvin Petit Dol      alvin petit dol
1        Assane Dioussé       assane diousse
2            Bryan Okoh           bryan okoh
3          Clément Akpa         clement akpa
4          Danny Loader         danny loader
5          Donovan Léon         donovan leon
6         Elikya Legros        elikya legros
7          Elisha Owusu         elisha owusu
8   Francisco Sierralta  francisco sierralta
9      Fredrik Oppegård     fredrik oppegard
10        Gideon Mensah        gideon mensah
11        Ibrahim Osman        ibrahim osman
12        Josué Casimir        josue casimir
13         Kévin Danois         kevin danois
14            Lamine Sy            lamine sy
15     Lassine Sinayoko     lassine sinayoko
16      Lasso Coulibaly      lasso coulibaly
17      Louis Mezerette      louis mezerette
18        Marvin Senaya        marvin senaya
19     Naouirou Ahamada     naouirou ahamada
20   Nathan Buayi-Kiala   nathan buayi kiala
21   Oussama El Azzouzi   oussama el azzouzi
22        Romain Faivre        romain faivre
23           Ryan Rodin           ryan rodin
24           Sékou Mara           sekou mara
25      Sinaly Diomandé      sinaly diomande
26           Telli Siwe           telli siwe
27       Théo De Percin       theo de percin
28    Tidiane Devernois    tidiane devernois
29           Tom Negrel           tom negrel

============================================================
  Le Havre  —  SF sin salario:

           player  minutesPlayed
0  Damián Pizarro             26
1      Enzo Koffi            317
2  Thomas Delaine            200
3    Younes Namli            340

  CG plantilla completa:

                   player            player_norm
0         Abdoulaye Touré        abdoulaye toure
1         Arouna Sangante        arouna sangante
2              Ayumu Seko             ayumu seko
3           Daren Mosengo          daren mosengo
4   Étienne Youté Kinkoué  etienne youte kinkoue
5          Felix Mambimbi         felix mambimbi
6           Fodé Doucouré          fode doucoure
7          Gautier Lloris         gautier lloris
8         Godson Kyeremeh        godson kyeremeh
9        Guy-Noël Zohouri       guy noel zohouri
10           Issa Soumaré           issa soumare
11          Kenny Quetant          kenny quetant
12      Lionel Mpasi-Nzau      lionel mpasi nzau
13              Loïc Nego              loic nego
14    Lucas Gourna-Douath    lucas gourna douath
15         Mbwana Samatta         mbwana samatta
16              Mory Diaw              mory diaw
17           Noam Obougou           noam obougou
18            Paul Argney            paul argney
19         Rassoul Ndiaye         rassoul ndiaye
20            Reda Khadra            reda khadra
21           Simon Ebonog           simon ebonog
22         Sofiane Boufal         sofiane boufal
23        Stephan Zagadou        stephan zagadou
24       Timothée Pembélé       timothee pembele
25          Yanis Zouaoui          yanis zouaoui
26         Yassine Kechta         yassine kechta

============================================================
  Lille  —  SF sin salario:

           player  minutesPlayed
0    Maxima Goffi             38
1  Soriba Diaoune            202
2   Ugo Raghouber             10
3  Vincent Burlet             18

  CG plantilla completa:

                    player             player_norm
0              Aïssa Mandi             aissa mandi
1               Alexsandro              alexsandro
2              André Gomes             andre gomes
3            Arnaud Bodart           arnaud bodart
4           Ayyoub Bouaddi          ayyoub bouaddi
5           Benjamin André          benjamin andre
6               Berke Özer              berke ozer
7           Calvin Verdonk          calvin verdonk
8           Chancel Mbemba          chancel mbemba
9             Ethan Mbappé            ethan mbappe
10           Félix Correia           felix correia
11           Gaëtan Perrin           gaetan perrin
12  Hákon Arnar Haraldsson  hakon arnar haraldsson
13           Hamza Igamane           hamza igamane
14    Marc-Aurèle Caillard    marc aurele caillard
15          Marius Broholm          marius broholm
16  Matías Fernández-Pardo  matias fernandez pardo
17            Mohamed Bayo            mohamed bayo
18          Nabil Bentaleb          nabil bentaleb
19             Nathan Ngoy             nathan ngoy
20         Ngal'ayel Mukau         ngal ayel mukau
21            Noah Edjouma            noah edjouma
22          Olivier Giroud          olivier giroud
23          Osame Sahraoui          osame sahraoui
24           Ousmane Touré           ousmane toure
25        Rafael Fernandes        rafael fernandes
26          Romain Perraud          romain perraud
27          Thomas Meunier          thomas meunier
28            Tiago Santos            tiago santos

============================================================
  Lorient  —  SF sin salario:

          player  minutesPlayed
0  Daniel Semedo             10
1  Formose Mendy            135
2    Martin Bley              1

  CG plantilla completa:

                    player             player_norm
0           Abdoulaye Faye          abdoulaye faye
1            Aiyegun Tosin           aiyegun tosin
2           Arsène Kouassi          arsene kouassi
3              Arthur Avom             arthur avom
4              Bamba Dieng             bamba dieng
5               Bamo Meïté              bamo meite
6        Bandiougou Fadiga       bandiougou fadiga
7           Benjamin Leroy          benjamin leroy
8         Bingourou Kamara        bingourou kamara
9           Darline Yongwa          darline yongwa
10           Dermane Karim           dermane karim
11              Igor Silva              igor silva
12     Jean-Victor Makengo     jean victor makengo
13              Joel Mvuka              joel mvuka
14         Laurent Abergel         laurent abergel
15           Mohamed Bamba           mohamed bamba
16         Montassar Talbi         montassar talbi
17         Nathaniel Adjei         nathaniel adjei
18             Noah Cadiou             noah cadiou
19             Pablo Pagis             pablo pagis
20          Panos Katseris          panos katseris
21          Sambou Soumano          sambou soumano
22  Souleymane Isaak Touré  souleymane isaak toure
23            Théo Le Bris            theo le bris
24           Trevan Sanusi           trevan sanusi
25              Yvon Mvogo              yvon mvogo

============================================================
  Metz  —  SF sin salario:

            player  minutesPlayed
0  Believe Munongo            332
1      Brian Madjo            162
2        Ibou Sane            555
3    Idrissa Gueye            130
4  Jahyann Pandore             61
5     Malick Mbaye            299
6     Nathan Mbala            334

  CG plantilla completa:

                  player           player_norm
0            Alpha Touré           alpha toure
1     Benjamin Stambouli    benjamin stambouli
2        Boubacar Traoré       boubacar traore
3             Bouna Sarr            bouna sarr
4          Cheikh Sabaly         cheikh sabaly
5          Cléo Mélières         cleo melieres
6       Fodé Ballo-Touré      fode ballo toure
7          Gauthier Hein         gauthier hein
8      Giorgi Abuashvili     giorgi abuashvili
9       Giorgi Kvilitaia      giorgi kvilitaia
10   Giorgi Tsitaishvili   giorgi tsitaishvili
11          Habib Diallo          habib diallo
12         Ismaël Guerti         ismael guerti
13  Jean-Philippe Gbamin  jean philippe gbamin
14       Jessy Deminguet       jessy deminguet
15            Joel Asoro            joel asoro
16      Jonathan Fischer      jonathan fischer
17       Joseph Mangondo       joseph mangondo
18           Koffi Kouao           koffi kouao
19          Lucas Michal          lucas michal
20          Maxime Colin          maxime colin
21         Michel Mboula         michel mboula
22         Morgan Bokele         morgan bokele
23            Ousmane Ba            ousmane ba
24               Pape Sy               pape sy
25          Sadibou Sané          sadibou sane
26           Terry Yegbe           terry yegbe
27         Yannis Lawson         yannis lawson

============================================================
  Nantes  —  SF sin salario:

              player  minutesPlayed
0     Hong Hyun-seok            284
1     Hyeok-kyu Kwon            764
2  Mathieu Acapandié            113
3      Mayckel Lahdo            418

  CG plantilla completa:

               player        player_norm
0        Abakar Sylla       abakar sylla
1       Adel Mahamoud      adel mahamoud
2      Alexis Mirbach     alexis mirbach
3         Ali Youssif        ali youssif
4        Amady Camara       amady camara
5       Anthony Lopes      anthony lopes
6        Bahmed Deuff       bahmed deuff
7    Chidozie Awaziem   chidozie awaziem
8    Dehmaine Tabibou   dehmaine tabibou
9      Deiver Machado     deiver machado
10    Fabien Centonze    fabien centonze
11   Francis Coquelin   francis coquelin
12  Frédéric Guilbert  frederic guilbert
13     Herba Guirassy     herba guirassy
14   Ibrahima Sissoko   ibrahima sissoko
15    Ignatius Ganago    ignatius ganago
16    Johann Lepenant    johann lepenant
17       Kelvin Amian       kelvin amian
18       Louis Leroux       louis leroux
19     Matthis Abline     matthis abline
20       Mohamed Kaba       mohamed kaba
21    Mostafa Mohamed    mostafa mohamed
22      Nicolas Cozza      nicolas cozza
23    Patrik Carlgren    patrik carlgren
24       Rémy Cabella       remy cabella
25     Sékou Doucouré     sekou doucoure
26         Tylel Tati         tylel tati
27     Uros Radakovic     uros radakovic
28  Yassine Benhattab  yassine benhattab
29   Youssef El Arabi   youssef el arabi

============================================================
  Nice  —  SF sin salario:

                     player  minutesPlayed
0        Badredine Bouanani             93
1            Bernard Nguene            133
2            Billal Brahimi              8
3  Brad-Hamilton Mantsounga             90
4           Everton Pereira            137
5            Hamza Koutoune              1
6             Kaïl Boudache            419
7             Pablo Rosario             27
8               Terem Moffi            489
9            Zoumana Diallo              9

  CG plantilla completa:

                   player            player_norm
0                Ali Abdi               ali abdi
1           Antoine Mendy          antoine mendy
2      Bartosz Zelazowski     bartosz zelazowski
3       Charles Vanhoutte      charles vanhoutte
4                   Dante                  dante
5       Djibril Coulibaly      djibril coulibaly
6               Elye Wahi              elye wahi
7        Gabin Bernardeau       gabin bernardeau
8         Hicham Boudaoui        hicham boudaoui
9            Isak Jansson           isak jansson
10           Jérémie Boga           jeremie boga
11        Jonathan Clauss        jonathan clauss
12               Juma Bah               juma bah
13           Kevin Carlos           kevin carlos
14     Kojo Peprah Oppong     kojo peprah oppong
15            Maxime Dupé            maxime dupe
16            Melvin Bard            melvin bard
17     Mohamed Abdelmonem     mohamed abdelmonem
18        Mohamed-Ali Cho        mohamed ali cho
19          Moïse Bombito          moise bombito
20          Morgan Sanson          morgan sanson
21      Salis Abdul Samed      salis abdul samed
22           Sofiane Diop           sofiane diop
23        Tanguy Ndombélé        tanguy ndombele
24          Tiago Gouveia          tiago gouveia
25            Tom Louchet            tom louchet
26          Yehvann Diouf          yehvann diouf
27  Youssouf Ndayishimiye  youssouf ndayishimiye

============================================================
  Olympique Lyonnais  —  SF sin salario:

               player  minutesPlayed
0        Adil Hamdani             28
1         Enzo Molebe              9
2  Georges Mikautadze            179
3        Rémi Himbert            139
4        Saël Kumbedi             66
5        Steeve Kango             86

  CG plantilla completa:

                    player             player_norm
0                    Abner                   abner
1           Achraf Laâziri          achraf laaziri
2             Adam Karabec            adam karabec
3           Afonso Moreira          afonso moreira
4   Ainsley Maitland-Niles  ainsley maitland niles
5             Clinton Mata            clinton mata
6         Corentin Tolisso        corentin tolisso
7            Dominik Greif           dominik greif
8          Duje Caleta-Car         duje caleta car
9                  Endrick                 endrick
10           Ernest Nuamah           ernest nuamah
11           Hans Hateboer           hans hateboer
12            Khalis Merah            khalis merah
13          Lassine Diarra          lassine diarra
14       Mahamadou Diawara       mahamadou diawara
15           Malick Fofana           malick fofana
16         Martín Satriano         martin satriano
17      Mathys De Carvalho      mathys de carvalho
18         Moussa Niakhaté         moussa niakhate
19      Nicolás Tagliafico      nicolas tagliafico
20             Noah Nartey             noah nartey
21            Noham Kamara            noham kamara
22            Orel Mangala            orel mangala
23              Pavel Sulc              pavel sulc
24          Rachid Ghezzal          rachid ghezzal
25           Rémy Descamps           remy descamps
26         Roman Yaremchuk         roman yaremchuk
27          Ruben Kluivert          ruben kluivert
28         Tanner Tessmann         tanner tessmann
29            Tyler Morton            tyler morton

============================================================
  Olympique de Marseille  —  SF sin salario:

                  player  minutesPlayed
0          Adrien Rabiot             90
1          Darryl Bakola             90
2        Derek Cornelius             57
3          Jonathan Rowe             63
4           Matt O'Riley            739
5      Nouhoum Kamissoko             10
6             Pol Lirola             42
7            Robinio Vaz            393
8        Tadjidine Mmadi             46
9  Ugo Lamare El Kadmiri             14

  CG plantilla completa:

                       player                player_norm
0                Amine Gouiri               amine gouiri
1                 Amine Harit                amine harit
2                 Angel Gomes                angel gomes
3            Arthur Vermeeren           arthur vermeeren
4             Benjamin Pavard            benjamin pavard
5                 Bilal Nadir                bilal nadir
6               CJ Egan-Riley              cj egan riley
7                     Emerson                    emerson
8               Ethan Nwaneri              ethan nwaneri
9              Facundo Medina             facundo medina
10         Geoffrey Kondogbia         geoffrey kondogbia
11             Gerónimo Rulli             geronimo rulli
12        Hamed Junior Traorè        hamed junior traore
13              Himad Abdelli              himad abdelli
14                Igor Paixão                igor paixao
15           Jeffrey de Lange           jeffrey de lange
16             Jelle Van Neck             jelle van neck
17           Leonardo Balerdi           leonardo balerdi
18            Mason Greenwood            mason greenwood
19            Michael Murillo            michael murillo
20               Nayef Aguerd               nayef aguerd
21                Neal Maupay                neal maupay
22  Pierre-Emerick Aubameyang  pierre emerick aubameyang
23      Pierre-Emile Højbjerg       pierre emile hjbjerg
24             Quinten Timber             quinten timber
25                Théo Vermot                theo vermot
26               Timothy Weah               timothy weah
27             Tochukwu Nnadi             tochukwu nnadi
28             Ulisses Garcia             ulisses garcia

============================================================
  Paris FC  —  SF sin salario:

               player  minutesPlayed
0  Mohamed Benoit-Dao              9

  CG plantilla completa:

                    player             player_norm
0             Adama Camara            adama camara
1             Alimami Gory            alimami gory
2            Ciro Immobile           ciro immobile
3            Diego Coppola           diego coppola
4            Hamari Traoré           hamari traore
5              Ilan Kebbal             ilan kebbal
6     Jean-Philippe Krasso    jean philippe krasso
7           Jonathan Ikoné          jonathan ikone
8             Julien Lopez            julien lopez
9              Kevin Trapp             kevin trapp
10            Lamine Gueye            lamine gueye
11           Lohann Doucet           lohann doucet
12           Luca Koleosho           luca koleosho
13            Mamadou Mbow            mamadou mbow
14        Marshall Munetsi        marshall munetsi
15          Mathieu Cafaro          mathieu cafaro
16        Mathys Tourraine        mathys tourraine
17            Maxime Lopez            maxime lopez
18             Moses Simon             moses simon
19             Nhoa Sangui             nhoa sangui
20             Nouha Dicko             nouha dicko
21          Obed Nkambadio          obed nkambadio
22                  Otávio                  otavio
23       Pierre Lees-Melou       pierre lees melou
24       Pierre-Yves Hamel       pierre yves hamel
25               Rémy Riou               remy riou
26            Rudy Matondo            rudy matondo
27           Samir Chergui           samir chergui
28        Sofiane Alakouch        sofiane alakouch
29        Thibault De Smet        thibault de smet
30  Timothée Kolodziejczak  timothee kolodziejczak
31           Tuomas Ollila           tuomas ollila
32       Vincent Marchetti       vincent marchetti
33         Willem Geubbels         willem geubbels

============================================================
  Paris Saint-Germain  —  SF sin salario:

           player  minutesPlayed
0  Mathis Jangeal             10
1      Noah Nsoki             15

  CG plantilla completa:

                   player            player_norm
0           Achraf Hakimi          achraf hakimi
1         Bradley Barcola        bradley barcola
2             Désiré Doué            desire doue
3           Dro Fernández          dro fernandez
4             Fabián Ruiz            fabian ruiz
5           Gonçalo Ramos          goncalo ramos
6           Ibrahim Mbaye          ibrahim mbaye
7           Ilya Zabarnyi          ilya zabarnyi
8              João Neves             joao neves
9             Kang-in Lee            kang in lee
10  Khvicha Kvaratskhelia  khvicha kvaratskhelia
11          Lucas Beraldo          lucas beraldo
12        Lucas Chevalier        lucas chevalier
13        Lucas Hernández        lucas hernandez
14             Marquinhos             marquinhos
15         Matvey Safonov         matvey safonov
16            Nuno Mendes            nuno mendes
17        Ousmane Dembélé        ousmane dembele
18       Quentin Ndjantou       quentin ndjantou
19      Randal Kolo Muani      randal kolo muani
20           Renato Marin           renato marin
21         Renato Sanches         renato sanches
22           Senny Mayulu           senny mayulu
23                Vitinha                vitinha
24     Warren Zaïre-Emery     warren zaire emery
25          Willian Pacho          willian pacho

============================================================
  RC Lens  —  SF sin salario:

              player  minutesPlayed
0         Andy Diouf             90
1     Erawan Garnier             14
2  Morgan Guilavogui            485

  CG plantilla completa:

                 player          player_norm
0         Abdallah Sima        abdallah sima
1      Adrien Thomasson     adrien thomasson
2   Allan Saint-Maximin  allan saint maximin
3          Alpha Diallo         alpha diallo
4        Amadou Haidara       amadou haidara
5     Andrija Bulatovic    andrija bulatovic
6       Anthony Bermont      anthony bermont
7        Arthur Masuaku       arthur masuaku
8        Florian Sotoca       florian sotoca
9       Florian Thauvin      florian thauvin
10           Fodé Sylla           fode sylla
11        Ilan Jourdren        ilan jourdren
12       Ismaëlo Ganiou       ismaelo ganiou
13      Jhoanner Chávez      jhoanner chavez
14      Jonathan Gradit      jonathan gradit
15      Kyllian Antonio      kyllian antonio
16          Malang Sarr          malang sarr
17      Mamadou Sangaré      mamadou sangare
18     Mathieu Gorgelin     mathieu gorgelin
19        Matthieu Udol        matthieu udol
20          Nidal Celik          nidal celik
21      Odsonne Édouard      odsonne edouard
22         Rayan Fofana         rayan fofana
23        Régis Gurtner        regis gurtner
24         Robin Risser         robin risser
25        Ruben Aguilar        ruben aguilar
26        Samson Baidoo        samson baidoo
27      Saud Abdulhamid      saud abdulhamid
28          Wesley Saïd          wesley said

============================================================
  RC Strasbourg  —  SF sin salario:

             player  minutesPlayed
0      Amadou Cissé             90
1      Dilane Bakwa            105
2  Félix Lemaréchal            554
3    Idrissa Sabaly             57
4       Kendry Páez            431
5      Mamadou Sarr           1305
6   Rabby Nzingoula             62
7  Tyrese Noubissie              8

  CG plantilla completa:

                 player          player_norm
0       Aarón Anselmino      aaron anselmino
1          Abakar Sylla         abakar sylla
2       Abdoul Ouattara      abdoul ouattara
3    Andrew Omobamidele   andrew omobamidele
4          Ben Chilwell         ben chilwell
5    David Datro Fofana   david datro fofana
6         Diego Moreira        diego moreira
7        Emanuel Emegha       emanuel emegha
8       Gessime Yassine      gessime yassine
9            Guela Doué           guela doue
10      Ismaël Doukouré      ismael doukoure
11   Joaquín Panichelli   joaquin panichelli
12         Julio Enciso         julio enciso
13        Junior Mwanga        junior mwanga
14  Karl-Johan Johnsson  karl johan johnsson
15       Lucas Høgsberg        lucas hgsberg
16         Martial Godo         martial godo
17       Mathis Amougou       mathis amougou
18         Maxi Oyedele         maxi oyedele
19         Mike Penders         mike penders
20          Rafael Luís          rafael luis
21         Rayane Messi         rayane messi
22           Saïdou Sow           saidou sow
23    Samir El Mourabet    samir el mourabet
24    Samuel Amo-Ameyaw    samuel amo ameyaw
25     Sebastian Nanasi     sebastian nanasi
26         Stefan Bajic         stefan bajic
27       Valentín Barco       valentin barco

============================================================
  Stade Brestois  —  SF sin salario:

               player  minutesPlayed
0        Axel Camblan             11
1  Julien Le Cardinal            327
2    Justin Bourgault             15

  CG plantilla completa:

                 player          player_norm
0         Bradley Locko        bradley locko
1    Brendan Chardonnet   brendan chardonnet
2         Daouda Guindo        daouda guindo
3           Éric Ebimbe          eric ebimbe
4      Grégoire Coudert     gregoire coudert
5       Hamidou Makalou      hamidou makalou
6         Hugo Magnetti        hugo magnetti
7         Joris Chotard        joris chotard
8           Junior Diaz          junior diaz
9        Kamory Doumbia       kamory doumbia
10           Kenny Lala           kenny lala
11        Lucas Tousart        lucas tousart
12           Luck Zogbé           luck zogbe
13      Ludovic Ajorque      ludovic ajorque
14           Mama Baldé           mama balde
15           Noah Jauny           noah jauny
16          Pathé Mboup          pathe mboup
17     Radoslaw Majecki     radoslaw majecki
18      Raphaël Le Guen      raphael le guen
19  Rémy Labeau Lascary  remy labeau lascary
20  Romain Del Castillo  romain del castillo
21          Saliou Diop          saliou diop
22   Soumaïla Coulibaly   soumaila coulibaly

============================================================
  Stade Rennais  —  SF sin salario:

                 player  minutesPlayed
0       Bertuğ Yıldırım              2
1      Christopher Wooh             64
2         Fabian Rieder            139
3  Henrick Do Marcolino              2
4         Ibrahim Salah             40
5          Lucas Rosier              2
6          Mikayil Faye             12
7   Mohamed Kader Meite            530

  CG plantilla completa:

                     player              player_norm
0    Abdelhamid Ait Boudlal   abdelhamid ait boudlal
1               Alidu Seidu              alidu seidu
2           Anthony Rouault          anthony rouault
3             Arnaud Nordin            arnaud nordin
4              Breel Embolo             breel embolo
5               Brice Samba              brice samba
6              Djaoui Cissé             djaoui cisse
7   Elías Legendre Quiñónez  elias legendre quinonez
8            Estéban Lepaul           esteban lepaul
9               Glen Kamara              glen kamara
10           Jérémy Jacquet           jeremy jacquet
11          Lilian Brassier          lilian brassier
12             Ludovic Blas             ludovic blas
13         Mahamadou Nagida         mahamadou nagida
14             Mahdi Camara             mahdi camara
15         Mathys Silistrie         mathys silistrie
16          Mousa Al-Tamari          mousa al tamari
17           Nordan Mukiele           nordan mukiele
18    Przemyslaw Frankowski    przemyslaw frankowski
19           Quentin Merlin           quentin merlin
20      Sebastian Szymanski      sebastian szymanski
21              Seko Fofana              seko fofana
22         Valentin Rongier         valentin rongier
23            Yassir Zabiri            yassir zabiri

============================================================
  Toulouse  —  SF sin salario:

          player  minutesPlayed
0    Ilyas Azizi             22
1  Jaydee Canvot            180
2    Mathis Saka              8

  CG plantilla completa:

                  player           player_norm
0            Abu Francis           abu francis
1         Álex Domínguez        alex dominguez
2          Alexis Vossah         alexis vossah
3            Aron Dønnum            aron dnnum
4      Charlie Cresswell     charlie cresswell
5   Cristian Cásseres Jr  cristian casseres jr
6        Dayann Methalie       dayann methalie
7         Djibril Sidibé        djibril sidibe
8               Emersonn              emersonn
9              Enzo Faty             enzo faty
10           Frank Magri           frank magri
11      Guillaume Restes      guillaume restes
12    Jacen Russell-Rowe    jacen russell rowe
13        Julián Vignolo        julian vignolo
14           Kjetil Haug           kjetil haug
15           Mario Sauer           mario sauer
16         Mark McKenzie         mark mckenzie
17        Niklas Schmidt        niklas schmidt
18       Pape Demba Diop       pape demba diop
19         Rafik Messali         rafik messali
20     Rasmus Nicolaisen     rasmus nicolaisen
21      Santiago Hidalgo      santiago hidalgo
22        Seny Koumbassa        seny koumbassa
23        Warren Kamanzi        warren kamanzi
24            Yann Gboho            yann gboho

In [25]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [26]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 450/537 (83.8%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

⚠️ Nombre con sufijo `_snapshot_20260428` para diferenciar del master definitivo
que se generará al cierre de la temporada (`master_france_2526.csv`).

In [27]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_france_2526_snapshot_20260428.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_france_2526_snapshot_20260428.csv
   Jugadores totales:  537
   Con salario:        450
   Sin salario (NaN):  87
   Columnas:           122