# 03 · Join Sofascore + Capology — France Ligue 1 24/25

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2024/25 de Ligue 1 francesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_france_2425.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_france_2425.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  542 jugadores | 116 columnas
Capology:   561 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   as monaco
   olympique de marseille
   olympique lyonnais
   paris saint germain
   rc lens
   rc strasbourg
   saint etienne
   stade brestois
   stade de reims
   stade rennais
   usl dunkerque

En Capology pero no en Sofascore:
   brest
   lens
   lyon
   marseille
   monaco
   psg
   reims
   rennes
   st etienne
   strasbourg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brest':'stade brestois',
            'lens':'rc lens',
            'lyon':'olympique lyonnais',
            'marseille':'olympique de marseille',
            'monaco':'as monaco',
            'psg':'paris saint germain',
            'reims':'stade de reims',
            'rennes':'stade rennais',
            'st etienne':'saint etienne',
            'strasbourg':'rc strasbourg'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 445/542 (82.1%)
Sin emparejar: 97

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          7
Revisión media    (0.75 ≤ score < 0.90):   12
Revisión estricta (0.50 ≤ score < 0.75):   39
Revisión muy est. (score < 0.50):           38

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf            team               cg_match  score
4   Przemysław Frankowski         RC Lens  przemyslaw frankowski  0.976
18       Radosław Majecki       AS Monaco       radoslaw majecki  0.968
13        Emmanuel Emegha   RC Strasbourg         emanuel emegha  0.966
5            Marcin Bułka            Nice           marcin bulka  0.957
23              Luc Zogbé  Stade Brestois             luck zogbe  0.947
25         Albert Grønbæk   Stade Rennais         albert grnbaek  0.923
30      Bahereba Guirassy          Nantes         herba guirassy  0.903

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf            team                 cg_match  score
19            Mousa Tamari   Stade Rennais          mousa al tamari  0.889
16  Valentin Atangana Edoa  Stade de Reims        valentin atangana  0.872
3           Đorđe Petrović   RC Strasbourg         djordje petrovic  0.857
70     Justin-Noel Kalumba          Angers           justin kalumba  0.848
17        Matías Fernández           Lille   matias fernandez pardo  0.842
39  Lucas Mincarelli Davin     Montpellier         lucas mincarelli  0.842
15   Henrik Wendel Meister   Stade Rennais           henrik meister  0.800
31    Shavy Warren Babicka        Toulouse            shavy babicka  0.788
29          Thelonius Bair         Auxerre                theo bair  0.783
40            Andrés Gómez   Stade Rennais      carlos andres gomez  0.774
28      Enzo Tchato Mbiayi     Montpellier              enzo tchato  0.759
11          Wilfried Singo       AS Monaco  wilfried stephane singo  0.757

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 12 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf                    team             cg_match  score
12            Amir Murillo  Olympique de Marseille      michael murillo  0.741
50           Mohamed Bamba          Stade de Reims       mohamed daramy  0.741
46            Benjamin Old           Saint-Étienne              ben old  0.737
45     Ahmadou Bamba Dieng                  Angers          bamba dieng  0.733
7       Alexsandro Ribeiro                   Lille           alexsandro  0.714
10              Gift Orban      Olympique Lyonnais  gift emmanuel orban  0.690
9      Mutassim Al-Musrati               AS Monaco           al musrati  0.690
8         Abdulay Juma Bah                 RC Lens             juma bah  0.667
71  David Pereira da Costa                 RC Lens          david costa  0.667
77          Kandet Diawara                Le Havre    mahamadou diawara  0.645
27        Boubakar Kouyaté             Montpellier         kiki kouyate  0.643
93              Andy Logbo                Le Havre         elysee logbo  0.636
20           Rafik Messali                Toulouse          frank magri  0.583
2      Benjamin Bourigeaud           Stade Rennais         amine gouiri  0.581
62          Nordine Kandil           RC Strasbourg       tidiane diallo  0.571
66           Gabin Capuano                 RC Lens      martin satriano  0.571
21             Kevin Pedro           Saint-Étienne           leo petrot  0.571
68             Yoann Cissé                 Auxerre       assane diousse  0.560
86           Mathéo Bodmer                Le Havre     mathieu gorgelin  0.552
22            Noham Kamara     Paris Saint-Germain           ayman kari  0.545
53            Birama Touré             Montpellier           bamo meite  0.545
43     Mohamed Kader Meite           Stade Rennais       henrik meister  0.545
58          Issiaga Camara                    Nice  baptiste santamaria  0.545
57         Kyllian Antonio                 RC Lens          kevin danso  0.538
91           Stefan Džodić             Montpellier    belmin dizdarevic  0.533
59       Djylian N'Guessan           Saint-Étienne    dylan batubinsika  0.529
84       Jérémy Le Douaron          Stade Brestois    pierre lees melou  0.529
14          Abner Vinícius      Olympique Lyonnais                abner  0.526
82              Ayman Aiki           Saint-Étienne    dylan batubinsika  0.519
64          Martin Adeline          Stade de Reims        oumar diakite  0.519
65           Ousmane Touré                   Lille       osame sahraoui  0.519
60      Hafiz Umar Ibrahim          Stade de Reims        oumar diakite  0.516
69            Yaël Nandjou                    Nice             ali abdi  0.500
6              Beres Owusu           Saint-Étienne        pierre cornud  0.500
90           Theo Chennahi             Montpellier          enzo tchato  0.500
73                Ange Tia          Stade de Reims         aurelio buta  0.500
76           Aaron Malouda                   Lille          aissa mandi  0.500
85          Bernard Nguene                    Nice       evann guessand  0.500
87            Orel Mangala      Olympique Lyonnais     florent da silva  0.500

In [14]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['amir murillo',
                    'benjamin old',
                    'ahmadou bamba dieng',
                    'alexsandro ribeiro',
                    'gift orban',
                    'mutassim al musrati',
                    'abdulay juma bah',
                    'david pereira da costa',
                    'boubakar kouyate',
                    'andy logbo',
                    'abner vinicius'
                    
                    
                    
                    

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 11

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [15]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
89,Jordan Lotomba,Nice,jonathan clauss,0.483
88,Saimon Bouabre,AS Monaco,folarin balogun,0.483
74,Hamidou Makalou,Stade Brestois,kamory doumbia,0.483
67,Prosper Peter,Angers,pierrick capelle,0.483
35,Plamedi Nsingi,Nantes,moses simon,0.480
54,Lucas Michal,AS Monaco,lamine camara,0.480
55,Junior Ndiaye,Montpellier,jordan ferri,0.480
34,Robinio Vaz,Olympique de Marseille,geronimo rulli,0.480
78,Alexi Koum,Olympique de Marseille,azzedine ounahi,0.480
75,Simon Cara,Montpellier,lucas mincarelli,0.462
63,Jibril Othman,Saint-Étienne,irvin cardona,0.462
48,Rayan Fofana,RC Lens,florian sotoca,0.462
44,Yael Mouanga,Montpellier,othmane maamma,0.462
83,Rudy Matondo,Auxerre,eros maddy,0.455
61,Alejandro Gomes Rodriguez,Olympique Lyonnais,alexandre lacazette,0.455
72,Noah Edjouma,Toulouse,aron dnnum,0.455
41,Enzo Caumont,Angers,oumar pona,0.455
49,Serigne Diop,Stade Brestois,romain del castillo,0.452
52,Lanroy Machine,Angers,florent hanin,0.444
33,Sékou Doucoure,Nantes,jean kevin duverne,0.438
51,Mamadou Coulibaly,AS Monaco,mohammed salisu,0.438
94,Téo Barišić,Olympique Lyonnais,warmed omari,0.435
79,Kembo Diliwidi,RC Lens,angelo fulgini,0.429
24,Younes Lachaab,Lille,jonathan david,0.429
81,Niama Pape Sissoko,Stade de Reims,mamadou diakhon,0.424
0,Logan Costa,Toulouse,gabriel suazo,0.417
36,Marwann Nzuzi,Saint-Étienne,yvann macon,0.417
32,Adryelson,Olympique Lyonnais,tanner tessmann,0.417
95,Ikechukwu Orazi,Stade de Reims,keito nakamura,0.414
56,Wilfried Ndollo Bille,Montpellier,gabriel bares,0.412
80,Axel Gueguin,Montpellier,gabriel bares,0.400
1,Ismail Jakobs,AS Monaco,maghnes akliouche,0.400
47,Edhy Zuliani,Toulouse,shavy babicka,0.400
37,Axel Tape,Paris Saint-Germain,presnel kimpembe,0.400
92,Zabi,Stade de Reims,maxime busi,0.400
26,Jaydee Canvot,Toulouse,gabriel suazo,0.385
42,Yanis Issoufou,Montpellier,nicolas pays,0.385
38,Hianga'a M'Bock,Stade Brestois,jordan amavi,0.370

In [16]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [17]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 475/542 (87.6%)
Sin salario:     67

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [18]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 67

,player,team,minutesPlayed,appearances,goals,assists
0,Ismail Jakobs,AS Monaco,180,2,0,0
1,Lucas Michal,AS Monaco,114,8,0,0
2,Saimon Bouabre,AS Monaco,96,3,0,0
3,Mamadou Coulibaly,AS Monaco,13,1,0,0
4,Enzo Caumont,Angers,37,2,0,0
5,Prosper Peter,Angers,27,2,0,0
6,Lanroy Machine,Angers,9,2,0,0
7,Rudy Matondo,Auxerre,62,5,0,0
8,Yoann Cissé,Auxerre,14,2,0,0
9,Mathéo Bodmer,Le Havre,14,1,0,0
10,Kandet Diawara,Le Havre,9,1,0,0
11,Ousmane Touré,Lille,14,1,0,0
12,Younes Lachaab,Lille,13,2,0,0
13,Aaron Malouda,Lille,9,1,0,0
14,Yael Mouanga,Montpellier,946,14,0,0
15,Junior Ndiaye,Montpellier,455,15,0,0
16,Wilfried Ndollo Bille,Montpellier,402,8,0,0
17,Birama Touré,Montpellier,296,8,0,0
18,Stefan Džodić,Montpellier,249,7,0,0
19,Theo Chennahi,Montpellier,184,4,0,0
20,Yanis Issoufou,Montpellier,82,4,0,0
21,Axel Gueguin,Montpellier,22,1,0,0
22,Simon Cara,Montpellier,19,2,0,0
23,Plamedi Nsingi,Nantes,16,1,0,0
24,Sékou Doucoure,Nantes,11,2,0,0
25,Yaël Nandjou,Nice,155,3,0,0
26,Issiaga Camara,Nice,44,4,0,0
27,Jordan Lotomba,Nice,40,2,0,0
28,Bernard Nguene,Nice,13,1,0,0
29,Orel Mangala,Olympique Lyonnais,68,1,0,0
30,Alejandro Gomes Rodriguez,Olympique Lyonnais,19,1,0,0
31,Adryelson,Olympique Lyonnais,10,1,0,0
32,Téo Barišić,Olympique Lyonnais,1,1,0,0
33,Robinio Vaz,Olympique de Marseille,74,2,0,0
34,Alexi Koum,Olympique de Marseille,11,1,0,0
35,Axel Tape,Paris Saint-Germain,180,2,0,0
36,Noham Kamara,Paris Saint-Germain,75,2,0,0
37,Kyllian Antonio,RC Lens,139,3,0,0
38,Rayan Fofana,RC Lens,24,2,0,0
39,Kembo Diliwidi,RC Lens,12,1,0,0
40,Gabin Capuano,RC Lens,10,1,0,0
41,Nordine Kandil,RC Strasbourg,9,1,0,0
42,Djylian N'Guessan,Saint-Étienne,191,8,0,0
43,Ayman Aiki,Saint-Étienne,131,5,0,0
44,Marwann Nzuzi,Saint-Étienne,126,2,0,0
45,Beres Owusu,Saint-Étienne,90,1,0,0
46,Jibril Othman,Saint-Étienne,11,1,0,0
47,Kevin Pedro,Saint-Étienne,9,1,0,0
48,Jérémy Le Douaron,Stade Brestois,101,2,0,0
49,Hamidou Makalou,Stade Brestois,40,4,0,0
50,Hianga'a M'Bock,Stade Brestois,20,1,0,0
51,Serigne Diop,Stade Brestois,10,2,0,0
52,Mohamed Kader Meite,Stade Rennais,551,12,2,0
53,Benjamin Bourigeaud,Stade Rennais,81,1,1,0
54,Hafiz Umar Ibrahim,Stade de Reims,386,11,0,1
55,Ange Tia,Stade de Reims,170,6,0,0
56,Niama Pape Sissoko,Stade de Reims,44,4,0,0
57,Martin Adeline,Stade de Reims,25,1,0,0
58,Zabi,Stade de Reims,22,2,0,0
59,Mohamed Bamba,Stade de Reims,9,2,0,0
60,Ikechukwu Orazi,Stade de Reims,2,1,0,0
61,Jaydee Canvot,Toulouse,1116,18,0,0
62,Rafik Messali,Toulouse,457,13,0,1
63,Noah Edjouma,Toulouse,170,10,2,0
64,Logan Costa,Toulouse,90,1,0,0
65,Edhy Zuliani,Toulouse,8,1,0,0
66,Naatan Skyttä,USL Dunkerque,9,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [19]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  AS Monaco  —  SF sin salario:

              player  minutesPlayed
0      Ismail Jakobs            180
1       Lucas Michal            114
2  Mamadou Coulibaly             13
3     Saimon Bouabre             96

  CG plantilla completa:

                     player              player_norm
0                Al Musrati               al musrati
1         Aleksandr Golovin        aleksandr golovin
2              Breel Embolo             breel embolo
3             Caio Henrique            caio henrique
4         Christian Mawissa        christian mawissa
5             Denis Zakaria            denis zakaria
6                 Edan Diop                edan diop
7        Eliesse Ben Seghir       eliesse ben seghir
8              Eliot Matazo             eliot matazo
9           Folarin Balogun          folarin balogun
10        George Ilenikhena        george ilenikhena
11              Jordan Teze              jordan teze
12         Kassoum Ouattara         kassoum ouattara
13            Krépin Diatta            krepin diatta
14            Lamine Camara            lamine camara
15        Maghnes Akliouche        maghnes akliouche
16             Mika Biereth             mika biereth
17          Mohammed Salisu          mohammed salisu
18             Philipp Köhn             philipp kohn
19         Radoslaw Majecki         radoslaw majecki
20       Soungoutou Magassa       soungoutou magassa
21          Takumi Minamino          takumi minamino
22             Thilo Kehrer             thilo kehrer
23                Vanderson                vanderson
24  Wilfried Stephane Singo  wilfried stephane singo
25             Yann Lienard             yann lienard

============================================================
  Angers  —  SF sin salario:

           player  minutesPlayed
0    Enzo Caumont             37
1  Lanroy Machine              9
2   Prosper Peter             27

  CG plantilla completa:

                  player           player_norm
0        Abdoulaye Bamba       abdoulaye bamba
1           Adrien Hunou          adrien hunou
2            Bamba Dieng           bamba dieng
3          Carlens Arcus         carlens arcus
4      Cédric Hountondji     cedric hountondji
5        Emmanuel Biumla       emmanuel biumla
6         Estéban Lepaul        esteban lepaul
7        Farid El Melali       farid el melali
8          Florent Hanin         florent hanin
9            Guédé Nadje           guede nadje
10       Halid Sabanovic       halid sabanovic
11        Haris Belkebla        haris belkebla
12         Himad Abdelli         himad abdelli
13        Ibrahima Niane        ibrahima niane
14        Jacques Ekomié        jacques ekomie
15     Jean-Eudes Aholou     jean eudes aholou
16         Jim Allevinah         jim allevinah
17         Jordan Lefort         jordan lefort
18           Joseph Lopy           joseph lopy
19        Justin Kalumba        justin kalumba
20       Lilian Raolisoa       lilian raolisoa
21            Loïs Diony            lois diony
22       Marius Courcoul       marius courcoul
23          Melvin Zinga          melvin zinga
24            Oumar Pona            oumar pona
25        Ousmane Camara        ousmane camara
26      Pierrick Capelle      pierrick capelle
27         Sidiki Chérif         sidiki cherif
28          Yahia Fofana          yahia fofana
29       Yassin Belkhdim       yassin belkhdim
30       Zinedine Ferhat       zinedine ferhat
31  Zinédine Ould Khaled  zinedine ould khaled

============================================================
  Auxerre  —  SF sin salario:

         player  minutesPlayed
0  Rudy Matondo             62
1   Yoann Cissé             14

  CG plantilla completa:

                 player          player_norm
0            Ado Onaiwu           ado onaiwu
1     Ange Loic N'Gatta    ange loic n gatta
2       Aristide Zossou      aristide zossou
3        Assane Dioussé       assane diousse
4           Ben Viadere          ben viadere
5          Clément Akpa         clement akpa
6          Donovan Léon         donovan leon
7          Elisha Owusu         elisha owusu
8            Eros Maddy           eros maddy
9           Florian Ayé          florian aye
10     Fredrik Oppegård     fredrik oppegard
11         Gabriel Osho         gabriel osho
12        Gaëtan Perrin        gaetan perrin
13        Gideon Mensah        gideon mensah
14  Hamed Junior Traoré  hamed junior traore
15    Han-Noah Massengo    han noah massengo
16                Jubal                jubal
17         Kévin Danois         kevin danois
18       Ki-Jana Hoever       ki jana hoever
19     Lassine Sinayoko     lassine sinayoko
20      Lasso Coulibaly      lasso coulibaly
21   Nathan Buayi-Kiala   nathan buayi kiala
22      Nicolas Mercier      nicolas mercier
23            Paul Joly            paul joly
24      Raphaël Adiceam      raphael adiceam
25      Rayan Raveloson      rayan raveloson
26        Saad Agouzoul        saad agouzoul
27      Sinaly Diomandé      sinaly diomande
28            Theo Bair            theo bair
29       Théo De Percin       theo de percin
30       Théo Pellenard       theo pellenard
31           Tom Negrel           tom negrel

============================================================
  Le Havre  —  SF sin salario:

           player  minutesPlayed
0  Kandet Diawara              9
1   Mathéo Bodmer             14

  CG plantilla completa:

                   player            player_norm
0         Abdoulaye Touré        abdoulaye toure
1            Ahmed Hassan           ahmed hassan
2           Aloïs Confais          alois confais
3              André Ayew             andre ayew
4          Antoine Joujou         antoine joujou
5         Arouna Sangante        arouna sangante
6           Arthur Desmas          arthur desmas
7       Christopher Operi      christopher operi
8           Daler Kuzyaev          daler kuzyaev
9            Elysée Logbo           elysee logbo
10         Emmanuel Sabbi         emmanuel sabbi
11  Étienne Youté Kinkoué  etienne youte kinkoue
12       Fodé Ballo-Touré       fode ballo toure
13         Gautier Lloris         gautier lloris
14           Ilyes Housni           ilyes housni
15          Ismaïl Bouneb          ismail bouneb
16           Issa Soumaré           issa soumare
17          Josué Casimir          josue casimir
18          Junior Mwanga          junior mwanga
19              Loïc Nego              loic nego
20      Mahamadou Diawara      mahamadou diawara
21       Mathieu Gorgelin       mathieu gorgelin
22       Oualid El Hajjam       oualid el hajjam
23    Oussama Targhalline    oussama targhalline
24            Paul Argney            paul argney
25         Rassoul Ndiaye         rassoul ndiaye
26           Ruben Londja           ruben londja
27        Samuel Grandsir        samuel grandsir
28           Steve Ngoura           steve ngoura
29       Timothée Pembélé       timothee pembele
30          Yanis Zouaoui          yanis zouaoui
31            Yann Kitala            yann kitala
32         Yassine Kechta         yassine kechta
33          Yoann Salmier          yoann salmier

============================================================
  Lille  —  SF sin salario:

           player  minutesPlayed
0   Aaron Malouda              9
1   Ousmane Touré             14
2  Younes Lachaab             13

  CG plantilla completa:

                    player             player_norm
0              Aïssa Mandi             aissa mandi
1             Akim Zedadka            akim zedadka
2               Alexsandro              alexsandro
3              André Gomes             andre gomes
4              Angel Gomes             angel gomes
5           Ayyoub Bouaddi          ayyoub bouaddi
6           Bafodé Diakité          bafode diakite
7           Benjamin André          benjamin andre
8              Chuba Akpom             chuba akpom
9            Edon Zhegrova           edon zhegrova
10            Ethan Mbappé            ethan mbappe
11     Gabriel Gudmundsson     gabriel gudmundsson
12  Hákon Arnar Haraldsson  hakon arnar haraldsson
13                 Ismaily                 ismaily
14          Jonathan David          jonathan david
15         Lisandru Olmeta         lisandru olmeta
16         Lucas Chevalier         lucas chevalier
17    Marc-Aurèle Caillard    marc aurele caillard
18  Matias Fernandez-Pardo  matias fernandez pardo
19          Mitchel Bakker          mitchel bakker
20            Mohamed Bayo            mohamed bayo
21          Nabil Bentaleb          nabil bentaleb
22         Ngal'ayel Mukau         ngal ayel mukau
23          Osame Sahraoui          osame sahraoui
24        Rafael Fernandes        rafael fernandes
25            Rémy Cabella            remy cabella
26           Samuel Umtiti           samuel umtiti
27          Thomas Meunier          thomas meunier
28            Tiago Santos            tiago santos
29            Vito Mannone            vito mannone

============================================================
  Montpellier  —  SF sin salario:

                  player  minutesPlayed
0           Axel Gueguin             22
1           Birama Touré            296
2          Junior Ndiaye            455
3             Simon Cara             19
4          Stefan Džodić            249
5          Theo Chennahi            184
6  Wilfried Ndollo Bille            402
7           Yael Mouanga            946
8         Yanis Issoufou             82

  CG plantilla completa:

                 player          player_norm
0            Akor Adams           akor adams
1           Andy Delort          andy delort
2         Arnaud Nordin        arnaud nordin
3            Bamo Meïté           bamo meite
4        Becir Omeragic       becir omeragic
5     Belmin Dizdarevic    belmin dizdarevic
6      Benjamin Lecomte     benjamin lecomte
7   Christopher Jullien  christopher jullien
8       Dimitry Bertaud      dimitry bertaud
9           Enzo Tchato          enzo tchato
10         Falaye Sacko         falaye sacko
11        Gabriel Barès        gabriel bares
12         Glenn Ngosso         glenn ngosso
13        Issiaga Sylla        issiaga sylla
14         Jordan Ferri         jordan ferri
15        Joris Chotard        joris chotard
16         Khalil Fayad         khalil fayad
17         Kiki Kouyaté         kiki kouyate
18     Lucas Mincarelli     lucas mincarelli
19        Modibo Sagnan        modibo sagnan
20      Mousa Al-Tamari      mousa al tamari
21         Nicolas Pays         nicolas pays
22    Nikola Maksimović    nikola maksimovic
23       Othmane Maamma       othmane maamma
24      Rabby Nzingoula      rabby nzingoula
25     Tanguy Coulibaly     tanguy coulibaly
26        Téji Savanier        teji savanier
27     Théo Sainte-Luce     theo sainte luce
28         Wahbi Khazri         wahbi khazri

============================================================
  Nantes  —  SF sin salario:

           player  minutesPlayed
0  Plamedi Nsingi             16
1  Sékou Doucoure             11

  CG plantilla completa:

                      player               player_norm
0               Alban Lafont              alban lafont
1              Anthony Lopes             anthony lopes
2           Dehmaine Tabibou          dehmaine tabibou
3            Douglas Augusto           douglas augusto
4            Fabien Centonze           fabien centonze
5             Florent Mollet            florent mollet
6           Francis Coquelin          francis coquelin
7             Herba Guirassy            herba guirassy
8                Hugo Barbet               hugo barbet
9            Ignatius Ganago           ignatius ganago
10  Jean-Charles Castelletto  jean charles castelletto
11        Jean-Kévin Duverne        jean kevin duverne
12      Jean-Philippe Gbamin      jean philippe gbamin
13           Johann Lepenant           johann lepenant
14              Kelvin Amian              kelvin amian
15              Louis Leroux              louis leroux
16               Marcus Coco               marcus coco
17            Matthis Abline            matthis abline
18             Meschack Elia             meschack elia
19               Moses Simon               moses simon
20           Mostafa Mohamed           mostafa mohamed
21               Nathan Zézé               nathan zeze
22             Nicolas Cozza             nicolas cozza
23           Nicolas Pallois           nicolas pallois
24           Patrik Carlgren           patrik carlgren
25          Pedro Chirivella          pedro chirivella
26                Saïdou Sow                saidou sow
27              Sorba Thomas              sorba thomas
28             Tino Kadewere             tino kadewere

============================================================
  Nice  —  SF sin salario:

           player  minutesPlayed
0  Bernard Nguene             13
1  Issiaga Camara             44
2  Jordan Lotomba             40
3    Yaël Nandjou            155

  CG plantilla completa:

                   player            player_norm
0                Ali Abdi               ali abdi
1        Amidou Doumbouya       amidou doumbouya
2           Antoine Mendy          antoine mendy
3      Badredine Bouanani     badredine bouanani
4     Baptiste Santamaria    baptiste santamaria
5          Billal Brahimi         billal brahimi
6                   Dante                  dante
7          Evann Guessand         evann guessand
8          Gaëtan Laborde         gaetan laborde
9         Hicham Boudaoui        hicham boudaoui
10           Jérémie Boga           jeremie boga
11        Jonathan Clauss        jonathan clauss
12           Marcin Bulka           marcin bulka
13            Maxime Dupé            maxime dupe
14            Melvin Bard            melvin bard
15     Mohamed Abdelmonem     mohamed abdelmonem
16        Mohamed-Ali Cho        mohamed ali cho
17          Moïse Bombito          moise bombito
18          Morgan Sanson          morgan sanson
19          Pablo Rosario          pablo rosario
20             Rareș Ilie             rares ilie
21           Sofiane Diop           sofiane diop
22        Tanguy Ndombélé        tanguy ndombele
23        Teddy Boulhendi        teddy boulhendi
24            Terem Moffi            terem moffi
25            Tom Louchet            tom louchet
26          Victor Orakpo          victor orakpo
27  Youssouf Ndayishimiye  youssouf ndayishimiye
28      Youssoufa Moukoko      youssoufa moukoko

============================================================
  Olympique Lyonnais  —  SF sin salario:

                      player  minutesPlayed
0                  Adryelson             10
1  Alejandro Gomes Rodriguez             19
2               Orel Mangala             68
3                Téo Barišić              1

  CG plantilla completa:

                    player             player_norm
0                    Abner                   abner
1   Ainsley Maitland-Niles  ainsley maitland niles
2      Alexandre Lacazette     alexandre lacazette
3            Anthony Lopes           anthony lopes
4             Clinton Mata            clinton mata
5         Corentin Tolisso        corentin tolisso
6          Duje Caleta-Car         duje caleta car
7            Ernest Nuamah           ernest nuamah
8         Florent Da Silva        florent da silva
9       Georges Mikautadze      georges mikautadze
10     Gift Emmanuel Orban     gift emmanuel orban
11            Irvyn Lomami            irvyn lomami
12         Jordan Veretout         jordan veretout
13           Justin Bengui           justin bengui
14             Lucas Perri             lucas perri
15       Mahamadou Diawara       mahamadou diawara
16           Malick Fofana           malick fofana
17        Maxence Caqueret        maxence caqueret
18         Moussa Niakhaté         moussa niakhate
19           Nemanja Matic           nemanja matic
20      Nicolás Tagliafico      nicolas tagliafico
21           Paul Akouokou           paul akouokou
22            Rayan Cherki            rayan cherki
23           Rémy Descamps           remy descamps
24            Saël Kumbedi            sael kumbedi
25           Saïd Benrahma           said benrahma
26         Tanner Tessmann         tanner tessmann
27           Thiago Almada           thiago almada
28            Warmed Omari            warmed omari
29           Wilfried Zaha           wilfried zaha

============================================================
  Olympique de Marseille  —  SF sin salario:

        player  minutesPlayed
0   Alexi Koum             11
1  Robinio Vaz             74

  CG plantilla completa:

                   player           player_norm
0           Adrien Rabiot         adrien rabiot
1              Amar Dedic            amar dedic
2            Amine Gouiri          amine gouiri
3             Amine Harit           amine harit
4         Azzedine Ounahi       azzedine ounahi
5              Bamo Meïté            bamo meite
6             Bilal Nadir           bilal nadir
7          Chancel Mbemba        chancel mbemba
8           Darryl Bakola         darryl bakola
9         Derek Cornelius       derek cornelius
10              Elye Wahi             elye wahi
11            Emran Soglo           emran soglo
12           Enzo Sternal          enzo sternal
13        Faris Moumbagna       faris moumbagna
14         François Mughe        francois mughe
15            Gaël Lafont           gael lafont
16     Geoffrey Kondogbia    geoffrey kondogbia
17         Gerónimo Rulli        geronimo rulli
18        Ismaël Bennacer       ismael bennacer
19            Ismaël Koné           ismael kone
20       Jeffrey de Lange      jeffrey de lange
21         Jelle Van Neck        jelle van neck
22          Jonathan Rowe         jonathan rowe
23      Keyliane Abdallah     keyliane abdallah
24       Leonardo Balerdi      leonardo balerdi
25        Lilian Brassier       lilian brassier
26          Luis Henrique         luis henrique
27            Luiz Felipe           luiz felipe
28        Mason Greenwood       mason greenwood
29        Michael Murillo       michael murillo
30            Neal Maupay           neal maupay
31  Pierre-Emile Højbjerg  pierre emile hjbjerg
32             Pol Lirola            pol lirola
33         Quentin Merlin        quentin merlin
34           Rubén Blanco          ruben blanco
35         Ulisses Garcia        ulisses garcia
36       Valentín Carboni      valentin carboni
37       Valentin Rongier      valentin rongier

============================================================
  Paris Saint-Germain  —  SF sin salario:

         player  minutesPlayed
0     Axel Tape            180
1  Noham Kamara             75

  CG plantilla completa:

                   player            player_norm
0           Achraf Hakimi          achraf hakimi
1             Arnau Tenas            arnau tenas
2              Ayman Kari             ayman kari
3         Bradley Barcola        bradley barcola
4            Carlos Soler           carlos soler
5             Colin Dagba            colin dagba
6             Désiré Doué            desire doue
7             Fabián Ruiz            fabian ruiz
8        Gabriel Moscardo       gabriel moscardo
9    Gianluigi Donnarumma   gianluigi donnarumma
10          Gonçalo Ramos          goncalo ramos
11          Ibrahim Mbaye          ibrahim mbaye
12             João Neves             joao neves
13            Juan Bernat            juan bernat
14            Kang-in Lee            kang in lee
15  Khvicha Kvaratskhelia  khvicha kvaratskhelia
16          Lucas Beraldo          lucas beraldo
17        Lucas Hernández        lucas hernandez
18          Marco Asensio          marco asensio
19             Marquinhos             marquinhos
20         Matvey Safonov         matvey safonov
21         Milan Skriniar         milan skriniar
22          Nordi Mukiele          nordi mukiele
23            Nuno Mendes            nuno mendes
24        Ousmane Dembélé        ousmane dembele
25       Presnel Kimpembe       presnel kimpembe
26      Randal Kolo Muani      randal kolo muani
27           Senny Mayulu           senny mayulu
28                Vitinha                vitinha
29     Warren Zaïre-Emery     warren zaire emery
30          Willian Pacho          willian pacho
31            Xavi Simons            xavi simons
32            Yoram Zague            yoram zague

============================================================
  RC Lens  —  SF sin salario:

            player  minutesPlayed
0    Gabin Capuano             10
1   Kembo Diliwidi             12
2  Kyllian Antonio            139
3     Rayan Fofana             24

  CG plantilla completa:

                   player            player_norm
0      Abdukodir Khusanov     abdukodir khusanov
1        Adrien Thomasson       adrien thomasson
2           Anass Zaroury          anass zaroury
3              Andy Diouf             andy diouf
4          Angelo Fulgini         angelo fulgini
5             Brice Samba            brice samba
6             David Costa            david costa
7          Deiver Machado         deiver machado
8            Denis Petric           denis petric
9          Facundo Medina         facundo medina
10         Florian Sotoca         florian sotoca
11      Goduine Koyalipou      goduine koyalipou
12        Hamzat Ojediran        hamzat ojediran
13            Hervé Koffi            herve koffi
14         Ismaëlo Ganiou         ismaelo ganiou
15        Jeremy Agbonifo        jeremy agbonifo
16        Jhoanner Chávez        jhoanner chavez
17            Jimmy Cabot            jimmy cabot
18        Jonathan Gradit        jonathan gradit
19               Juma Bah               juma bah
20            Kevin Danso            kevin danso
21           M'Bala Nzola           m bala nzola
22            Malang Sarr            malang sarr
23        Martín Satriano        martin satriano
24            Mathew Ryan            mathew ryan
25         Nampalys Mendy         nampalys mendy
26        Neil El Aynaoui        neil el aynaoui
27            Nidal Celik            nidal celik
28  Przemyslaw Frankowski  przemyslaw frankowski
29    Rémy Labeau Lascary    remy labeau lascary
30          Ruben Aguilar          ruben aguilar
31              Sidi Bane              sidi bane
32            Tom Pouilly            tom pouilly
33            Wesley Saïd            wesley said

============================================================
  RC Strasbourg  —  SF sin salario:

           player  minutesPlayed
0  Nordine Kandil              9

  CG plantilla completa:

                 player          player_norm
0          Abakar Sylla         abakar sylla
1       Abdoul Ouattara      abdoul ouattara
2      Alaa Bellaarouch     alaa bellaarouch
3    Andrew Omobamidele   andrew omobamidele
4         Andrey Santos        andrey santos
5           Caleb Wiley          caleb wiley
6         Diego Moreira        diego moreira
7          Dilane Bakwa         dilane bakwa
8      Djordje Petrovic     djordje petrovic
9          Eduard Sobol         eduard sobol
10       Emanuel Emegha       emanuel emegha
11     Félix Lemaréchal     felix lemarechal
12           Guéla Doué           guela doue
13         Habib Diarra         habib diarra
14      Ismaël Doukouré      ismael doukoure
15         Jérémy Sebas         jeremy sebas
16        Junior Mwanga        junior mwanga
17  Karl-Johan Johnsson  karl johan johnsson
18           Karol Fila           karol fila
19         Mamadou Sarr         mamadou sarr
20        Marvin Senaya        marvin senaya
21      Matthieu Dreyer      matthieu dreyer
22        Milos Lukovic        milos lukovic
23      Mohamed Bechikh      mohamed bechikh
24      Moïse Sahi Dion      moise sahi dion
25          Nolan Ferro          nolan ferro
26          Óscar Perea          oscar perea
27           Pape Diong           pape diong
28         Robin Risser         robin risser
29           Saïdou Sow           saidou sow
30    Samuel Amo-Ameyaw    samuel amo ameyaw
31     Sebastian Nanasi     sebastian nanasi
32           Sékou Mara           sekou mara
33       Thomas Delaine       thomas delaine
34       Tidiane Diallo       tidiane diallo
35       Valentín Barco       valentin barco
36          Walid Hasbi          walid hasbi
37           Yoni Gomis           yoni gomis

============================================================
  Saint-Étienne  —  SF sin salario:

              player  minutesPlayed
0         Ayman Aiki            131
1        Beres Owusu             90
2  Djylian N'Guessan            191
3      Jibril Othman             11
4        Kevin Pedro              9
5      Marwann Nzuzi            126

  CG plantilla completa:

                 player          player_norm
0        Aïmen Moueffek       aimen moueffek
1      Anthony Briançon     anthony briancon
2      Augustine Boakye     augustine boakye
3               Ben Old              ben old
4   Benjamin Bouchouari  benjamin bouchouari
5         Boubacar Fall        boubacar fall
6         Brice Maubleu        brice maubleu
7         Dennis Appiah        dennis appiah
8     Dylan Batubinsika    dylan batubinsika
9       Florian Tardieu      florian tardieu
10   Gautier Larsonneur   gautier larsonneur
11      Ibrahim Sissoko      ibrahim sissoko
12       Ibrahima Wadji       ibrahima wadji
13     Igor Miladinovic     igor miladinovic
14        Irvin Cardona        irvin cardona
15         Lamine Fomba         lamine fomba
16           Léo Pétrot           leo petrot
17         Louis Mouton         louis mouton
18        Lucas Stassin        lucas stassin
19       Mathieu Cafaro       mathieu cafaro
20       Mathis Amougou       mathis amougou
21      Maxime Bernauer      maxime bernauer
22         Mickaël Nade         mickael nade
23        Pierre Cornud        pierre cornud
24         Pierre Ekwah         pierre ekwah
25    Thomas Monconduit    thomas monconduit
26     Yunis Abdelhamid     yunis abdelhamid
27          Yvann Maçon          yvann macon
28  Zuriko Davitashvili  zuriko davitashvili

============================================================
  Stade Brestois  —  SF sin salario:

              player  minutesPlayed
0    Hamidou Makalou             40
1    Hianga'a M'Bock             20
2  Jérémy Le Douaron            101
3       Serigne Diop             10

  CG plantilla completa:

                  player           player_norm
0          Abdallah Sima         abdallah sima
1       Abdoulaye Ndiaye      abdoulaye ndiaye
2           Axel Camblan          axel camblan
3          Bradley Locko         bradley locko
4     Brendan Chardonnet    brendan chardonnet
5    Edimilson Fernandes   edimilson fernandes
6       Grégoire Coudert      gregoire coudert
7          Hugo Magnetti         hugo magnetti
8          Ibrahim Salah         ibrahim salah
9           Jonas Martin          jonas martin
10          Jordan Amavi          jordan amavi
11    Julien Le Cardinal    julien le cardinal
12      Justin Bourgault      justin bourgault
13        Kamory Doumbia        kamory doumbia
14            Kenny Lala            kenny lala
15            Luck Zogbé            luck zogbe
16       Ludovic Ajorque       ludovic ajorque
17          Mahdi Camara          mahdi camara
18            Mama Baldé            mama balde
19           Marco Bizot           marco bizot
20      Massadio Haidara      massadio haidara
21  Mathias Pereira Lage  mathias pereira lage
22            Noah Jauny            noah jauny
23     Pierre Lees-Melou     pierre lees melou
24   Romain Del Castillo   romain del castillo
25         Romain Faivre         romain faivre
26    Soumaïla Coulibaly    soumaila coulibaly

============================================================
  Stade Rennais  —  SF sin salario:

                player  minutesPlayed
0  Benjamin Bourigeaud             81
1  Mohamed Kader Meite            551

  CG plantilla completa:

                 player          player_norm
0       Adrien Truffert      adrien truffert
1     Alan Do Marcolino    alan do marcolino
2       Albert Grønbaek       albert grnbaek
3           Alidu Seidu          alidu seidu
4          Amine Gouiri         amine gouiri
5       Anthony Rouault      anthony rouault
6     Arnaud Kalimuendo    arnaud kalimuendo
7        Ayanda Sishuba       ayanda sishuba
8         Azor Matusiwa        azor matusiwa
9   Baptiste Santamaria  baptiste santamaria
10          Brice Samba          brice samba
11  Carlos Andrés Gómez  carlos andres gomez
12     Christopher Wooh     christopher wooh
13         Djaoui Cissé         djaoui cisse
14        Doğan Alemdar        dogan alemdar
15      Gauthier Gallon      gauthier gallon
16      Geoffrey Lembet      geoffrey lembet
17          Glen Kamara          glen kamara
18        Hans Hateboer        hans hateboer
19       Henrik Meister       henrik meister
20          Ismaël Koné          ismael kone
21       Jérémy Jacquet       jeremy jacquet
22         Jordan James         jordan james
23                 Jota                 jota
24       Kazeem Olaigbe       kazeem olaigbe
25      Kyogo Furuhashi      kyogo furuhashi
26         Leo Østigård          leo stigard
27      Lilian Brassier      lilian brassier
28      Lorenz Assignon      lorenz assignon
29         Ludovic Blas         ludovic blas
30     Mahamadou Nagida     mahamadou nagida
31         Mikayil Faye         mikayil faye
32      Mousa Al-Tamari      mousa al tamari
33     Naouirou Ahamada     naouirou ahamada
34          Seko Fofana          seko fofana
35       Steve Mandanda       steve mandanda
36        Wilson Samaké        wilson samake

============================================================
  Stade de Reims  —  SF sin salario:

               player  minutesPlayed
0            Ange Tia            170
1  Hafiz Umar Ibrahim            386
2     Ikechukwu Orazi              2
3      Martin Adeline             25
4       Mohamed Bamba              9
5  Niama Pape Sissoko             44
6                Zabi             22

  CG plantilla completa:

               player        player_norm
0         Abdoul Koné        abdoul kone
1        Adama Bojang       adama bojang
2   Alexandre Olliero  alexandre olliero
3         Amadou Koné        amadou kone
4        Amine Salama       amine salama
5        Aurélio Buta       aurelio buta
6        Cédric Kipré       cedric kipre
7    Emmanuel Agbadou   emmanuel agbadou
8    Gabriel Moscardo   gabriel moscardo
9       Hiroki Sekine      hiroki sekine
10       John Patrick       john patrick
11  Jordan Siebatcheu  jordan siebatcheu
12       Joseph Okumu       joseph okumu
13          Junya Ito          junya ito
14     Keito Nakamura     keito nakamura
15    Ludovic Butelle    ludovic butelle
16       Malcolm Jeng       malcolm jeng
17    Mamadou Diakhon    mamadou diakhon
18   Marshall Munetsi   marshall munetsi
19        Maxime Busi        maxime busi
20     Mohamed Daramy     mohamed daramy
21         Mory Gbane         mory gbane
22        Nhoa Sangui        nhoa sangui
23      Oumar Diakité      oumar diakite
24        Reda Khadra        reda khadra
25      Sergio Akieme      sergio akieme
26        Teddy Teuma        teddy teuma
27   Thibault De Smet   thibault de smet
28  Valentin Atangana  valentin atangana
29        Yaya Fofana        yaya fofana
30      Yehvann Diouf      yehvann diouf

============================================================
  Toulouse  —  SF sin salario:

          player  minutesPlayed
0   Edhy Zuliani              8
1  Jaydee Canvot           1116
2    Logan Costa             90
3   Noah Edjouma            170
4  Rafik Messali            457

  CG plantilla completa:

                  player           player_norm
0         Álex Domínguez        alex dominguez
1            Aron Dønnum            aron dnnum
2      Charlie Cresswell     charlie cresswell
3   Cristian Cásseres Jr  cristian casseres jr
4          Denis Genreau         denis genreau
5         Djibril Sidibé        djibril sidibe
6            Frank Magri           frank magri
7          Gabriel Suazo         gabriel suazo
8       Guillaume Restes      guillaume restes
9            Joshua King           joshua king
10        Justin Lacombe        justin lacombe
11           Kjetil Haug           kjetil haug
12         Mark McKenzie         mark mckenzie
13             Miha Zajc             miha zajc
14        Niklas Schmidt        niklas schmidt
15     Rasmus Nicolaisen     rasmus nicolaisen
16         Shavy Babicka         shavy babicka
17            Ümit Akdağ            umit akdag
18        Vincent Sierro        vincent sierro
19        Warren Kamanzi        warren kamanzi
20            Yann Gboho            yann gboho
21           Ylies Aradj           ylies aradj
22     Zakaria Aboukhlal     zakaria aboukhlal

============================================================
  USL Dunkerque  —  SF sin salario:

          player  minutesPlayed
0  Naatan Skyttä              9

  CG plantilla completa:

Empty DataFrame
Columns: [player, player_norm]
Index: []

In [20]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [21]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 475/542 (87.6%)

In [22]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [23]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_france_2425.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_france_2425.csv
   Jugadores totales:  542
   Con salario:        475
   Sin salario (NaN):  67
   Columnas:           121