# 03 · Join Sofascore + Capology — France Ligue 1 21/22

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2021/22 de Ligue 1 francesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_france_2122.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_france_2122.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  591 jugadores | 116 columnas
Capology:   631 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   as monaco
   clermont foot
   olympique de marseille
   olympique lyonnais
   paris fc
   paris saint germain
   rc lens
   rc strasbourg
   saint etienne
   stade brestois
   stade de reims
   stade rennais

En Capology pero no en Sofascore:
   brest
   clermont
   lens
   lyon
   marseille
   monaco
   psg
   reims
   rennes
   st etienne
   strasbourg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brest':'stade brestois',
            'clermont':'clermont foot',
            'lens':'rc lens',
            'lyon':'olympique lyonnais',
            'marseille':'olympique de marseille',
            'monaco':'as monaco',
            'psg':'paris saint germain',
            'reims':'stade de reims',
            'rennes':'stade rennais',
            'st etienne':'saint etienne',
            'strasbourg':'rc strasbourg'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 511/591 (86.5%)
Sin emparejar: 80

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          6
Revisión media    (0.75 ≤ score < 0.90):   3
Revisión estricta (0.50 ≤ score < 0.75):   39
Revisión muy est. (score < 0.50):           29

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf            team               cg_match  score
11  Przemysław Frankowski         RC Lens  przemyslaw frankowski  0.976
44        Hianga'a M'Bock  Stade Brestois         hianga a mbock  0.966
17           Vital Nsimba   Clermont Foot          vital n simba  0.960
6            Marcin Bułka            Nice           marcin bulka  0.957
28           Burak Yılmaz           Lille           burak yilmaz  0.957
14           Yusuf Yazıcı           Lille           yusuf yazici  0.909

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf           team         cg_match  score
48  Juan Ignacio Ramírez  Saint-Étienne  ignacio ramirez  0.857
40    Abduljalil Medioub       Bordeaux    abdel medioub  0.774
21       Pape Matar Sarr           Metz        pape sarr  0.750

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 3 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
16,Ahmadou Bamba Dieng,Olympique de Marseille,bamba dieng,0.733
15,Kamory Doumbia,Stade de Reims,moussa doumbia,0.714
32,Cheick Tidiane Sabaly,Metz,cheikh sabaly,0.706
7,Junior Mwanga,Bordeaux,ui jo hwang,0.667
55,Dion Moise Sahi,RC Strasbourg,moise sahi dion,0.667
13,David Pereira da Costa,RC Lens,david costa,0.667
47,Bradley Barcola,Olympique Lyonnais,malcolm barcola,0.667
4,Boubakar Kouyaté,Metz,boubacar traore,0.645
38,Bryan Nokoue,Saint-Étienne,yvan neyou,0.636
72,Lucas Calodat,Saint-Étienne,lucas gourna douath,0.625
43,Edson Mexer,Bordeaux,mexer,0.625
23,Junior Dina Ebimbe,Paris Saint-Germain,eric ebimbe,0.621
66,Maxwel Cornet,Olympique Lyonnais,maxence caqueret,0.621
0,Moustapha Mbow,Stade de Reims,mamadou mbow,0.615
9,Emerson Palmieri,Olympique Lyonnais,emerson,0.609
18,Toma Bašić,Bordeaux,tom lacoux,0.600
8,Abdoulaye Bakayoko,Saint-Étienne,falaye sacko,0.600
1,Rafinha Alcântara,Paris Saint-Germain,rafinha,0.583
45,Yanis Lhéry,Saint-Étienne,yvan neyou,0.571
64,Yadaly Diaby,Clermont Foot,nael jaby,0.571
25,Dan Ndoye,Nice,dante,0.571
60,Jeanuël Belocian,Stade Rennais,jeremy gelin,0.571
63,Mehdi Chahiri,RC Strasbourg,majeed waris,0.560
29,Vagner Dias,Metz,amine bassi,0.545
5,Simon Banza,RC Lens,seko fofana,0.545
2,Pablo Sarabia,Paris Saint-Germain,ismael gharbi,0.538
75,Yannis M'Bemba,Nantes,anthony limbombe,0.533
49,Mamadou Fofana,Metz,amadou salif mbengue,0.529
52,Jason Mbock,Angers,antonin bobichon,0.519
35,Myziane Maolida,Nice,amine gouiri,0.519
69,Enzo Tchato Mbiayi,Montpellier,junior sambia,0.516
76,Derek Mazou-Sacko,Troyes,eden massouema,0.516
67,Georges Mikautadze,Metz,louis mafouta,0.516
62,Johaneko Louis Jean,Bordeaux,josuha guilavogui,0.500
37,Eric N'jo,Troyes,metinho,0.500
54,Mykola Kukharevych,Troyes,yoann touzghar,0.500
31,N'Dri Koffi,Stade de Reims,yehvann diouf,0.500
42,Mamadou Camara,Troyes,mama balde,0.500
59,Mathys Saban,Saint-Étienne,mahdi camara,0.500

In [15]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['ahmadou bamba dieng',
                    'cheick tidiane sabaly',
                    'dion moise sahi',
                    'david pereira da costa',
                    'edson mexer',
                    'junior dina ebimbe',
                    'moustapha mbow',
                    'emerson palmieri',
                    'rafinha alcantara'
                    

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 9

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [16]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf                    team              cg_match  score
74      Samuel Koeberle          Stade de Reims        sambou sissoko  0.483
33       Nordine Kandil           RC Strasbourg       moise sahi dion  0.483
39    Eduardo Camavinga           Stade Rennais          romain salin  0.483
27        Lohann Doucet                  Nantes          alban lafont  0.480
41         Kaj Sierhuis          Stade de Reims         valon berisha  0.480
61         Loris Benito                Bordeaux         benoit costil  0.480
46     Baptiste Mouazan                 Lorient    malamine doumbouya  0.471
22       Martin Adeline          Stade de Reims      yunis abdelhamid  0.467
70       Lamine Ghezali           Saint-Étienne      eliaquim mangala  0.467
73          Guédé Nadje                  Angers       azzedine ounahi  0.462
34         Sacha Delaye             Montpellier        mathias suarez  0.462
12      Thibault Klidjé                Bordeaux           samuel kalu  0.462
30       Dieye El Hadji           Saint-Étienne          mickael nade  0.462
71        Tiago Ribeiro               AS Monaco         caio henrique  0.462
50          Charles Abi           Saint-Étienne       harold moukoudi  0.462
26            Leny Yoro                   Lille         edon zhegrova  0.455
58      Darío Benedetto  Olympique de Marseille      matteo guendouzi  0.452
57  Sekou Oumar Yansane     Paris Saint-Germain          sergio ramos  0.452
65      Ibrahim Diakité          Stade de Reims          hugo ekitike  0.444
68       Djeidi Gassama     Paris Saint-Germain         idrissa gueye  0.444
20         Rémy Cabella             Montpellier       dimitry bertaud  0.444
24     Didier Lamkel Zé                    Metz  william mikelbrencis  0.444
53     Aboubakar Sidibe           Clermont Foot           alidu seidu  0.444
56     Nemanja Radonjić  Olympique de Marseille      valentin rongier  0.438
19      Brayann Pereira                 RC Lens     valentino lesieur  0.438
36         Mohamed Achi                  Nantes           moses simon  0.435
51          Rubén Pardo                Bordeaux          davy rouyard  0.435
10        Steven Fortes                 RC Lens           seko fofana  0.417
3                  Tetê      Olympique Lyonnais               emerson  0.364

In [17]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [18]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 529/591 (89.5%)
Sin salario:     62

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [19]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 62

,player,team,minutesPlayed,appearances,goals,assists
0,Tiago Ribeiro,AS Monaco,1,1,0,0
1,Jason Mbock,Angers,16,1,0,0
2,Guédé Nadje,Angers,2,1,0,0
3,Toma Bašić,Bordeaux,212,3,0,1
4,Junior Mwanga,Bordeaux,90,1,0,0
5,Thibault Klidjé,Bordeaux,81,5,0,0
6,Loris Benito,Bordeaux,62,1,0,0
7,Rubén Pardo,Bordeaux,11,1,0,0
8,Johaneko Louis Jean,Bordeaux,11,1,0,0
9,Yadaly Diaby,Clermont Foot,64,5,0,0
10,Aboubakar Sidibe,Clermont Foot,9,1,0,0
11,Leny Yoro,Lille,12,1,0,0
12,Baptiste Mouazan,Lorient,95,3,0,0
13,Boubakar Kouyaté,Metz,2666,30,1,0
14,Didier Lamkel Zé,Metz,609,9,3,0
15,Vagner Dias,Metz,83,3,0,0
16,Mamadou Fofana,Metz,32,1,0,0
17,Georges Mikautadze,Metz,1,1,0,0
18,Rémy Cabella,Montpellier,313,5,0,0
19,Sacha Delaye,Montpellier,255,10,0,1
20,Enzo Tchato Mbiayi,Montpellier,7,1,0,0
21,Lohann Doucet,Nantes,11,2,0,0
22,Mohamed Achi,Nantes,9,1,0,0
23,Yannis M'Bemba,Nantes,4,2,0,0
24,Dan Ndoye,Nice,204,3,0,1
25,Myziane Maolida,Nice,33,1,0,0
26,Tetê,Olympique Lyonnais,585,9,2,5
27,Bradley Barcola,Olympique Lyonnais,275,11,0,1
28,Maxwel Cornet,Olympique Lyonnais,65,1,0,0
29,Darío Benedetto,Olympique de Marseille,52,2,0,0
30,Nemanja Radonjić,Olympique de Marseille,17,1,0,0
31,Jonathan Iglesias,Paris FC,584,15,0,0
32,Lamine Gueye,Paris FC,565,14,0,3
33,Mahamé Siby,Paris FC,15,2,0,0
34,Pablo Sarabia,Paris Saint-Germain,21,2,1,0
35,Sekou Oumar Yansane,Paris Saint-Germain,15,1,0,0
36,Djeidi Gassama,Paris Saint-Germain,1,1,0,0
37,Simon Banza,RC Lens,122,4,1,1
38,Steven Fortes,RC Lens,90,1,0,0
39,Brayann Pereira,RC Lens,21,2,0,0
40,Nordine Kandil,RC Strasbourg,90,5,0,1
41,Mehdi Chahiri,RC Strasbourg,15,1,0,0
42,Abdoulaye Bakayoko,Saint-Étienne,308,4,0,0
43,Yanis Lhéry,Saint-Étienne,73,5,0,0
44,Mathys Saban,Saint-Étienne,70,3,0,0
45,Bryan Nokoue,Saint-Étienne,56,2,0,0
46,Charles Abi,Saint-Étienne,45,1,0,0
47,Dieye El Hadji,Saint-Étienne,38,5,0,0
48,Lucas Calodat,Saint-Étienne,4,1,0,0
49,Lamine Ghezali,Saint-Étienne,1,1,0,0
50,Eduardo Camavinga,Stade Rennais,142,4,0,0
51,Jeanuël Belocian,Stade Rennais,11,1,0,0
52,N'Dri Koffi,Stade de Reims,384,10,1,0
53,Kamory Doumbia,Stade de Reims,348,8,2,1
54,Martin Adeline,Stade de Reims,347,8,0,0
55,Kaj Sierhuis,Stade de Reims,80,2,0,0
56,Ibrahim Diakité,Stade de Reims,14,1,0,0
57,Samuel Koeberle,Stade de Reims,1,1,0,0
58,Eric N'jo,Troyes,96,2,0,0
59,Mamadou Camara,Troyes,38,3,0,0
60,Mykola Kukharevych,Troyes,22,2,0,0
61,Derek Mazou-Sacko,Troyes,2,2,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [20]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  AS Monaco  —  SF sin salario:

          player  minutesPlayed
0  Tiago Ribeiro              1

  CG plantilla completa:

                   player            player_norm
0       Aleksandr Golovin      aleksandr golovin
1         Alexander Nübel        alexander nubel
2     Aurélien Tchouaméni    aurelien tchouameni
3             Axel Disasi            axel disasi
4       Benoît Badiashile      benoit badiashile
5           Caio Henrique          caio henrique
6           Cesc Fàbregas          cesc fabregas
7       Chrislain Matsima      chrislain matsima
8          Djibril Sidibé         djibril sidibe
9            Eliot Matazo           eliot matazo
10       Félix Lemaréchal       felix lemarechal
11         Gelson Martins         gelson martins
12      Guillermo Maripán      guillermo maripan
13          Ismail Jakobs          ismail jakobs
14             Jean Lucas             jean lucas
15          Jean Marcelin          jean marcelin
16          Kevin Volland          kevin volland
17          Krépin Diatta          krepin diatta
18      Maghnes Akliouche      maghnes akliouche
19            Myron Boadu            myron boadu
20                   Pelé                   pele
21       Radoslaw Majecki       radoslaw majecki
22          Ruben Aguilar          ruben aguilar
23           Sofiane Diop           sofiane diop
24     Strahinja Pavlovic     strahinja pavlovic
25  Valentin Decarpentrie  valentin decarpentrie
26              Vanderson              vanderson
27           Vito Mannone           vito mannone
28          Wilson Isidor          wilson isidor
29      Wissam Ben Yedder      wissam ben yedder
30        Youssouf Fofana        youssouf fofana

============================================================
  Angers  —  SF sin salario:

        player  minutesPlayed
0  Guédé Nadje              2
1  Jason Mbock             16

  CG plantilla completa:

                  player           player_norm
0        Abdoulaye Bamba       abdoulaye bamba
1         Angelo Fulgini        angelo fulgini
2        Anthony Mandréa       anthony mandrea
3       Antonin Bobichon      antonin bobichon
4        Azzedine Ounahi       azzedine ounahi
5          Batista Mendy         batista mendy
6          Casimir Ninga         casimir ninga
7       Danijel Petkovic      danijel petkovic
8            Enzo Ebosse           enzo ebosse
9        Farid El Melali       farid el melali
10         Ismaël Traoré         ismael traore
11           Jimmy Cabot           jimmy cabot
12            Kévin Boma            kevin boma
13         Marin Jakolis         marin jakolis
14  Mathias Pereira Lage  mathias pereira lage
15       Mohamed-Ali Cho       mohamed ali cho
16        Nabil Bentaleb        nabil bentaleb
17            Noah Fatar            noah fatar
18       Paul Bernardoni       paul bernardoni
19      Pierrick Capelle      pierrick capelle
20         Romain Thomas         romain thomas
21           Sada Thioub           sada thioub
22        Sofiane Boufal        sofiane boufal
23     Souleyman Doumbia     souleyman doumbia
24      Stéphane Bahoken      stephane bahoken
25        Thomas Mangani        thomas mangani
26       Vincent Manceau       vincent manceau
27          Waniss Taïbi          waniss taibi
28  Zinédine Ould Khaled  zinedine ould khaled

============================================================
  Bordeaux  —  SF sin salario:

                player  minutesPlayed
0  Johaneko Louis Jean             11
1        Junior Mwanga             90
2         Loris Benito             62
3          Rubén Pardo             11
4      Thibault Klidjé             81
5           Toma Bašić            212

  CG plantilla completa:

               player        player_norm
0       Abdel Medioub      abdel medioub
1        Alberth Elis       alberth elis
2       Amadou Traoré      amadou traore
3    Anel Ahmedhodzic   anel ahmedhodzic
4       Benoît Costil      benoit costil
5    Danylo Ignatenko   danylo ignatenko
6        Davy Rouyard       davy rouyard
7        Dilane Bakwa       dilane bakwa
8       Enock Kwateng      enock kwateng
9          Fransérgio         fransergio
10     Gaëtan Poussin     gaetan poussin
11      Gideon Mensah      gideon mensah
12    Issouf Sissokho    issouf sissokho
13   Javairô Dilrosun   javairo dilrosun
14         Jean Onana         jean onana
15       Jimmy Briand       jimmy briand
16          Josh Maja          josh maja
17  Josuha Guilavogui  josuha guilavogui
18  Laurent Koscielny  laurent koscielny
19       M'Baye Niang       m baye niang
20            Marcelo            marcelo
21      Mehdi Zerkane      mehdi zerkane
22              Mexer              mexer
23             Otávio             otavio
24        Paul Baysse        paul baysse
25         Rémi Oudin         remi oudin
26     Ricardo Mangas     ricardo mangas
27        Samuel Kalu        samuel kalu
28         Sékou Mara         sekou mara
29    Stian Gregersen    stian gregersen
30   Timothée Pembélé   timothee pembele
31         Tom Lacoux         tom lacoux
32        Ui-jo Hwang        ui jo hwang
33        Yacine Adli        yacine adli

============================================================
  Clermont Foot  —  SF sin salario:

             player  minutesPlayed
0  Aboubakar Sidibe              9
1      Yadaly Diaby             64

  CG plantilla completa:

                  player           player_norm
0           Akim Zedadka          akim zedadka
1            Alidu Seidu           alidu seidu
2            Arial Mendy           arial mendy
3          Arthur Desmas         arthur desmas
4          Brandon Baiye         brandon baiye
5   Bryan Silva Teixeira  bryan silva teixeira
6      Cédric Hountondji     cedric hountondji
7        Elbasan Rashani       elbasan rashani
8          Florent Ogier         florent ogier
9           Fred Gnalega          fred gnalega
10          Grejohn Kyei          grejohn kyei
11      Jason Berthomier      jason berthomier
12   Jean-Claude Billong   jean claude billong
13          Jérôme Phojo          jerome phojo
14         Jim Allevinah         jim allevinah
15          Jodel Dossou          jodel dossou
16         Johan Gastien         johan gastien
17     Jonathan Iglesias     jonathan iglesias
18           Jordan Tell           jordan tell
19          Josué Albert          josue albert
20          Julien Boyer          julien boyer
21        Lucas Da Cunha        lucas da cunha
22       Lucas Margueron       lucas margueron
23          Mohamed Bayo          mohamed bayo
24             Naël Jaby             nael jaby
25        Oriol Busquets        oriol busquets
26        Ouparine Djoco        ouparine djoco
27     Pierre-Yves Hamel     pierre yves hamel
28    Saîf-Eddine Khaoui    saif eddine khaoui
29     Salis Abdul Samed     salis abdul samed
30         Vital N'Simba         vital n simba
31         Yohann Magnin         yohann magnin

============================================================
  Lille  —  SF sin salario:

      player  minutesPlayed
0  Leny Yoro             12

  CG plantilla completa:

                 player          player_norm
0         Adam Jakubech        adam jakubech
1          Amadou Onana         amadou onana
2           Angel Gomes          angel gomes
3        Benjamin André       benjamin andre
4          Burak Yilmaz         burak yilmaz
5         Cheikh Niasse        cheikh niasse
6      Domagoj Bradaric     domagoj bradaric
7         Edon Zhegrova        edon zhegrova
8       Eugenio Pizzuto      eugenio pizzuto
9   Gabriel Gudmundsson  gabriel gudmundsson
10       Hatem Ben Arfa       hatem ben arfa
11        Isaac Lihadji        isaac lihadji
12            Ivo Grbic            ivo grbic
13          Jérémy Pied          jeremy pied
14       Jonathan Bamba       jonathan bamba
15       Jonathan David       jonathan david
16       Jonathan Ikoné       jonathan ikone
17           José Fonte           jose fonte
18           Jules Raux           jules raux
19           Léo Jardim           leo jardim
20     Orestis Karnezis     orestis karnezis
21     Reinildo Mandava     reinildo mandava
22       Renato Sanches       renato sanches
23          Sven Botman          sven botman
24          Tiago Djaló          tiago djalo
25         Timothy Weah         timothy weah
26                 Xeka                 xeka
27         Yusuf Yazici         yusuf yazici
28           Zeki Celik           zeki celik

============================================================
  Lorient  —  SF sin salario:

             player  minutesPlayed
0  Baptiste Mouazan             95

  CG plantilla completa:

                player         player_norm
0         Adrian Grbic        adrian grbic
1     Armand Laurienté    armand lauriente
2       Bonke Innocent      bonke innocent
3       Dango Ouattara      dango ouattara
4          Enzo Le Fée         enzo le fee
5       Fabien Lemoine      fabien lemoine
6    Houboulang Mendes   houboulang mendes
7        Ibrahima Koné       ibrahima kone
8           Igor Silva          igor silva
9         Jérémy Morel        jeremy morel
10     Jérôme Hergault     jerome hergault
11      Julien Laporte      julien laporte
12     Laurent Abergel     laurent abergel
13          Léo Pétrot          leo petrot
14     Loris Mouyokolo     loris mouyokolo
15  Malamine Doumbouya  malamine doumbouya
16     Matthieu Dreyer     matthieu dreyer
17         Moritz Jenz         moritz jenz
18          Paul Nardi          paul nardi
19    Quentin Boisgard    quentin boisgard
20      Redwan Bourlès      redwan bourles
21      Sambou Soumano      sambou soumano
22        Samuel Loric        samuel loric
23     Stéphane Diarra     stephane diarra
24    Taofeek Ismaheel    taofeek ismaheel
25     Teddy Bartouche     teddy bartouche
26         Terem Moffi         terem moffi
27        Théo Le Bris        theo le bris
28      Thomas Callens      thomas callens
29     Thomas Fontaine     thomas fontaine
30   Thomas Monconduit   thomas monconduit
31     Vincent Le Goff     vincent le goff

============================================================
  Metz  —  SF sin salario:

               player  minutesPlayed
0    Boubakar Kouyaté           2666
1    Didier Lamkel Zé            609
2  Georges Mikautadze              1
3      Mamadou Fofana             32
4         Vagner Dias             83

  CG plantilla completa:

                   player            player_norm
0       Alexandre Oukidja      alexandre oukidja
1    Amadou Salif Mbengue   amadou salif mbengue
2             Amine Bassi            amine bassi
3         Boubacar Traoré        boubacar traore
4           Cheikh Sabaly          cheikh sabaly
5        David Oberhauser       david oberhauser
6             Dylan Bronn            dylan bronn
7         Fabien Centonze        fabien centonze
8              Fali Candé             fali cande
9           Farid Boulaya          farid boulaya
10            Habib Maïga            habib maiga
11         Ibrahim Amadou         ibrahim amadou
12         Ibrahima Niane         ibrahima niane
13  Jean-Armel Kana-Biyik  jean armel kana biyik
14               Jemerson               jemerson
15          Kévin N'Doram          kevin n doram
16           Kiki Kouyaté           kiki kouyate
17           Lamine Gueye           lamine gueye
18           Lenny Joseph           lenny joseph
19          Lenny Lacroix          lenny lacroix
20          Louis Mafouta          louis mafouta
21           Manuel Cabit           manuel cabit
22   Marc-Aurèle Caillard   marc aurele caillard
23          Matthieu Udol          matthieu udol
24    Nicolas de Préville    nicolas de preville
25            Opa Nguette            opa nguette
26             Ousmane Ba             ousmane ba
27       Papa Ndiaga Yade       papa ndiaga yade
28              Pape Sarr              pape sarr
29          Sikou Niakaté          sikou niakate
30       Sofiane Alakouch       sofiane alakouch
31         Thomas Delaine         thomas delaine
32          Vincent Pajot          vincent pajot
33      Warren Tchimbembé      warren tchimbembe
34   William Mikelbrencis   william mikelbrencis

============================================================
  Montpellier  —  SF sin salario:

               player  minutesPlayed
0  Enzo Tchato Mbiayi              7
1        Rémy Cabella            313
2        Sacha Delaye            255

  CG plantilla completa:

                 player          player_norm
0       Ambroise Oyongo      ambroise oyongo
1        Arnaud Souquet       arnaud souquet
2         Béni Makouana        beni makouana
3       Dimitry Bertaud      dimitry bertaud
4             Elye Wahi            elye wahi
5        Florent Mollet       florent mollet
6         Gabriel Barès        gabriel bares
7           Jonas Omlin          jonas omlin
8          Jordan Ferri         jordan ferri
9         Joris Chotard        joris chotard
10        Junior Sambia        junior sambia
11            Léo Leroy            leo leroy
12        Mamadou Sakho        mamadou sakho
13       Mathías Suárez       mathias suarez
14       Matis Carvalho       matis carvalho
15        Maxime Estève        maxime esteve
16       Mihailo Ristic       mihailo ristic
17  Nicholas Gioacchini  nicholas gioacchini
18        Nicolas Cozza        nicolas cozza
19         Pedro Mendes         pedro mendes
20      Stephy Mavididi      stephy mavididi
21        Téji Savanier        teji savanier
22       Thibault Tamas       thibault tamas
23               Thuler               thuler
24       Valère Germain       valere germain
25     Yanis Guermouche     yanis guermouche

============================================================
  Nantes  —  SF sin salario:

           player  minutesPlayed
0   Lohann Doucet             11
1    Mohamed Achi              9
2  Yannis M'Bemba              4

  CG plantilla completa:

                      player               player_norm
0            Abdoulaye Sylla           abdoulaye sylla
1               Alban Lafont              alban lafont
2             Andrei Girotto            andrei girotto
3           Anthony Limbombe          anthony limbombe
4             Charles Traoré            charles traore
5                 Charly Jan                charly jan
6               Denis Petric              denis petric
7              Dennis Appiah             dennis appiah
8                      Fábio                     fabio
9              Gor Manvelyan             gor manvelyan
10  Jean-Charles Castelletto  jean charles castelletto
11       Jean-Kévin Augustin       jean kevin augustin
12          Kalifa Coulibaly          kalifa coulibaly
13              Ludovic Blas              ludovic blas
14               Marcus Coco               marcus coco
15               Molla Wagué               molla wague
16               Moses Simon               moses simon
17           Nicolas Pallois           nicolas pallois
18              Osman Bukari              osman bukari
19          Pedro Chirivella          pedro chirivella
20            Quentin Merlin            quentin merlin
21         Randal Kolo Muani         randal kolo muani
22             Rémy Descamps             remy descamps
23              Renaud Emond              renaud emond
24        Roli Pereira de Sa        roli pereira de sa
25        Samuel Moutoussamy        samuel moutoussamy
26         Sébastien Corchia         sebastien corchia
27           Willem Geubbels           willem geubbels
28             Wylan Cyprien             wylan cyprien

============================================================
  Nice  —  SF sin salario:

            player  minutesPlayed
0        Dan Ndoye            204
1  Myziane Maolida             33

  CG plantilla completa:

                   player            player_norm
0   Alexis Claude-Maurice  alexis claude maurice
1            Amine Gouiri           amine gouiri
2             Andy Delort            andy delort
3           Ange Ahoussou          ange ahoussou
4          Billal Brahimi         billal brahimi
5           Calvin Stengs          calvin stengs
6          Danilo Barbosa         danilo barbosa
7                   Dante                  dante
8             Deji Sotona            deji sotona
9          Evann Guessand         evann guessand
10       Flavius Daniliuc       flavius daniliuc
11         Hassane Kamara         hassane kamara
12        Hicham Boudaoui        hicham boudaoui
13            Ihsan Sacko            ihsan sacko
14      Jean-Clair Todibo      jean clair todibo
15           Jordan Amavi           jordan amavi
16         Jordan Lotomba         jordan lotomba
17        Justin Kluivert        justin kluivert
18           Justin Smith           justin smith
19         Kasper Dolberg         kasper dolberg
20        Khéphren Thuram        khephren thuram
21         Lucas Da Cunha         lucas da cunha
22           Marcin Bulka           marcin bulka
23           Mario Lemina           mario lemina
24            Melvin Bard            melvin bard
25    Morgan Schneiderlin    morgan schneiderlin
26          Pablo Rosario          pablo rosario
27           Robson Bambu           robson bambu
28        Teddy Boulhendi        teddy boulhendi
29         Walter Benítez         walter benitez
30            Youcef Atal            youcef atal

============================================================
  Olympique Lyonnais  —  SF sin salario:

            player  minutesPlayed
0  Bradley Barcola            275
1    Maxwel Cornet             65
2             Tetê            585

  CG plantilla completa:

                 player          player_norm
0         Anthony Lopes        anthony lopes
1       Bruno Guimarães      bruno guimaraes
2       Castello Lukeba      castello lukeba
3       Damien Da Silva      damien da silva
4               Emerson              emerson
5      Florent Da Silva     florent da silva
6           Gaël Nsombi          gael nsombi
7           Habib Keïta          habib keita
8              Henrique             henrique
9         Houssem Aouar        houssem aouar
10        Islam Slimani        islam slimani
11        Jason Denayer        jason denayer
12  Jeff Reine-Adélaïde  jeff reine adelaide
13       Jérôme Boateng       jerome boateng
14   Julian Pollersbeck   julian pollersbeck
15     Karl Toko Ekambi     karl toko ekambi
16         Lenny Pintor         lenny pintor
17           Léo Dubois           leo dubois
18        Lucas Paquetá        lucas paqueta
19      Malcolm Barcola      malcolm barcola
20           Malo Gusto           malo gusto
21              Marcelo              marcelo
22     Maxence Caqueret     maxence caqueret
23       Moussa Dembélé       moussa dembele
24          Pape Cheikh          pape cheikh
25         Rayan Cherki         rayan cherki
26        Romain Faivre        romain faivre
27      Sinaly Diomandé      sinaly diomande
28      Tanguy Ndombélé      tanguy ndombele
29        Thiago Mendes        thiago mendes
30        Tino Kadewere        tino kadewere
31      Xherdan Shaqiri      xherdan shaqiri

============================================================
  Olympique de Marseille  —  SF sin salario:

             player  minutesPlayed
0   Darío Benedetto             52
1  Nemanja Radonjić             17

  CG plantilla completa:

                  player           player_norm
0         Aaron Kamardin        aaron kamardin
1        Álvaro González       alvaro gonzalez
2            Amine Harit           amine harit
3        Arkadiusz Milik       arkadiusz milik
4            Bamba Dieng           bamba dieng
5            Bilal Nadir           bilal nadir
6        Boubacar Kamara       boubacar kamara
7         Cédric Bakambu        cedric bakambu
8           Cengiz Ünder          cengiz under
9          Dimitri Payet         dimitri payet
10       Duje Caleta-Car       duje caleta car
11         Franco Tongya         franco tongya
12                Gerson                gerson
13           Joakim Kada           joakim kada
14          Jordan Amavi          jordan amavi
15   Konrad de la Fuente   konrad de la fuente
16      Leonardo Balerdi      leonardo balerdi
17            Luan Peres            luan peres
18         Luis Henrique         luis henrique
19     Manuel Nazaretian     manuel nazaretian
20      Mattéo Guendouzi      matteo guendouzi
21   Oussama Targhalline   oussama targhalline
22       Paolo Sciortino       paolo sciortino
23            Pape Gueye            pape gueye
24             Pau López             pau lopez
25            Pol Lirola            pol lirola
26      Salim Ben Seghir      salim ben seghir
27        Sead Kolasinac        sead kolasinac
28  Simon Ngapandouetnbu  simon ngapandouetnbu
29        Steve Mandanda        steve mandanda
30          Ugo Bertelli          ugo bertelli
31      Valentin Rongier      valentin rongier
32        William Saliba        william saliba

============================================================
  Paris FC  —  SF sin salario:

              player  minutesPlayed
0  Jonathan Iglesias            584
1       Lamine Gueye            565
2        Mahamé Siby             15

  CG plantilla completa:

Empty DataFrame
Columns: [player, player_norm]
Index: []

============================================================
  Paris Saint-Germain  —  SF sin salario:

                player  minutesPlayed
0       Djeidi Gassama              1
1        Pablo Sarabia             21
2  Sekou Oumar Yansane             15

  CG plantilla completa:

                    player             player_norm
0             Abdou Diallo            abdou diallo
1            Achraf Hakimi           achraf hakimi
2      Alexandre Letellier     alexandre letellier
3            Ander Herrera           ander herrera
4           Anfane Ahamada          anfane ahamada
5           Ángel Di María          angel di maria
6        Bandiougou Fadiga       bandiougou fadiga
7              Colin Dagba             colin dagba
8           Danilo Pereira          danilo pereira
9            Denis Franchi           denis franchi
10          Edouard Michut          edouard michut
11  El Chadaille Bitshiabu  el chadaille bitshiabu
12             Éric Ebimbe             eric ebimbe
13      Garissone Innocent      garissone innocent
14     Georginio Wijnaldum     georginio wijnaldum
15    Gianluigi Donnarumma    gianluigi donnarumma
16           Idrissa Gueye           idrissa gueye
17           Ismaël Gharbi           ismael gharbi
18             Juan Bernat             juan bernat
19          Julian Draxler          julian draxler
20            Keylor Navas            keylor navas
21           Kylian Mbappé           kylian mbappe
22          Layvin Kurzawa          layvin kurzawa
23         Leandro Paredes         leandro paredes
24            Lionel Messi            lionel messi
25          Lucas Lavallée          lucas lavallee
26          Marco Verratti          marco verratti
27              Marquinhos              marquinhos
28            Mauro Icardi            mauro icardi
29       Nathan Bitumazala       nathan bitumazala
30                  Neymar                  neymar
31             Nuno Mendes             nuno mendes
32        Presnel Kimpembe        presnel kimpembe
33                 Rafinha                 rafinha
34            Sergio Ramos            sergio ramos
35             Sergio Rico             sergio rico
36             Teddy Alloh             teddy alloh
37            Thilo Kehrer            thilo kehrer
38           Tidjany Touré           tidjany toure
39             Xavi Simons             xavi simons

============================================================
  RC Lens  —  SF sin salario:

            player  minutesPlayed
0  Brayann Pereira             21
1      Simon Banza            122
2    Steven Fortes             90

  CG plantilla completa:

                   player            player_norm
0       Arnaud Kalimuendo      arnaud kalimuendo
1            Charles Boli           charles boli
2         Cheick Doucouré        cheick doucoure
3        Christopher Wooh       christopher wooh
4           Corentin Jean          corentin jean
5             David Costa            david costa
6          Deiver Machado         deiver machado
7          Facundo Medina         facundo medina
8          Florian Sotoca         florian sotoca
9             Gaël Kakuta            gael kakuta
10         Ibrahima Baldé         ibrahima balde
11        Ignatius Ganago        ignatius ganago
12           Ismaël Boura           ismael boura
13        Jean-Louis Leca        jean louis leca
14        Jonathan Clauss        jonathan clauss
15        Jonathan Gradit        jonathan gradit
16        Jonathan Varane        jonathan varane
17            Jules Keita            jules keita
18            Kevin Danso            kevin danso
19         Mamadou Camara         mamadou camara
20       Massadio Haidara       massadio haidara
21           Patrick Berg           patrick berg
22  Przemyslaw Frankowski  przemyslaw frankowski
23            Seko Fofana            seko fofana
24      Valentino Lesieur      valentino lesieur
25            Wesley Saïd            wesley said
26        Wuilker Fariñez        wuilker farinez
27        Yannick Cahuzac        yannick cahuzac

============================================================
  RC Strasbourg  —  SF sin salario:

           player  minutesPlayed
0   Mehdi Chahiri             15
1  Nordine Kandil             90

  CG plantilla completa:

                    player             player_norm
0         Adrien Thomasson        adrien thomasson
1         Alaa Bellaarouch        alaa bellaarouch
2          Alexander Djiku         alexander djiku
3         Alexandre Pierre        alexandre pierre
4             Anthony Caci            anthony caci
5            Aymeric Ahmed           aymeric ahmed
6         Bingourou Kamara        bingourou kamara
7          Dimitri Liénard         dimitri lienard
8           Eiji Kawashima          eiji kawashima
9        Frédéric Guilbert       frederic guilbert
10          Gerzino Nyamsi          gerzino nyamsi
11            Habib Diallo            habib diallo
12            Habib Diarra            habib diarra
13        Ibrahima Sissoko        ibrahima sissoko
14         Ismaël Doukouré         ismael doukoure
15       Jean-Eudes Aholou       jean eudes aholou
16  Jean-Ricner Bellegarde  jean ricner bellegarde
17              Karol Fila              karol fila
18           Kévin Gameiro           kevin gameiro
19            Lebo Mothiba            lebo mothiba
20            Lucas Perrin            lucas perrin
21         Ludovic Ajorque         ludovic ajorque
22             Mahamé Siby             mahame siby
23            Majeed Waris            majeed waris
24               Matz Sels               matz sels
25      Maxime Le Marchand      maxime le marchand
26         Moïse Sahi Dion         moise sahi dion
27            Sanjin Prcic            sanjin prcic

============================================================
  Saint-Étienne  —  SF sin salario:

               player  minutesPlayed
0  Abdoulaye Bakayoko            308
1        Bryan Nokoue             56
2         Charles Abi             45
3      Dieye El Hadji             38
4      Lamine Ghezali              1
5       Lucas Calodat              4
6        Mathys Saban             70
7         Yanis Lhéry             73

  CG plantilla completa:

                    player             player_norm
0           Adil Aouchiche          adil aouchiche
1           Aimen Moueffek          aimen moueffek
2            Alpha Sissoko           alpha sissoko
3            Arnaud Nordin           arnaud nordin
4           Assane Dioussé          assane diousse
5              Bakary Sako             bakary sako
6          Bilal Benkhedim         bilal benkhedim
7            Boubacar Fall           boubacar fall
8            Denis Bouanga           denis bouanga
9         Eliaquim Mangala        eliaquim mangala
10           Enzo Crivelli           enzo crivelli
11           Etienne Green           etienne green
12            Falaye Sacko            falaye sacko
13           Gabriel Silva           gabriel silva
14         Harold Moukoudi         harold moukoudi
15         Ignacio Ramírez         ignacio ramirez
16    Jean-Philippe Krasso    jean philippe krasso
17           Joris Gnagnon           joris gnagnon
18     Lucas Gourna-Douath     lucas gourna douath
19            Mahdi Camara            mahdi camara
20          Maxence Rivera          maxence rivera
21            Mickaël Nade            mickael nade
22           Miguel Trauco           miguel trauco
23           Nabil Ouennas           nabil ouennas
24         Paul Bernardoni         paul bernardoni
25          Romain Hamouma          romain hamouma
26          Ryad Boudebouz          ryad boudebouz
27             Sada Thioub             sada thioub
28              Saïdou Sow              saidou sow
29            Stefan Bajic            stefan bajic
30  Timothée Kolodziejczak  timothee kolodziejczak
31            Wahbi Khazri            wahbi khazri
32              Yvan Neyou              yvan neyou
33             Yvann Maçon             yvann macon
34         Zaydou Youssouf         zaydou youssouf

============================================================
  Stade Rennais  —  SF sin salario:

              player  minutesPlayed
0  Eduardo Camavinga            142
1   Jeanuël Belocian             11

  CG plantilla completa:

                 player          player_norm
0       Adrien Truffert      adrien truffert
1          Alfred Gomis         alfred gomis
2            Andy Diouf           andy diouf
3   Baptiste Santamaria  baptiste santamaria
4   Benjamin Bourigeaud  benjamin bourigeaud
5         Birger Meling        birger meling
6         Dogan Alemdar        dogan alemdar
7          Flavien Tait         flavien tait
8        Gaëtan Laborde       gaetan laborde
9         Hamari Traoré        hamari traore
10          Jérémy Doku          jeremy doku
11         Jérémy Gélin         jeremy gelin
12         Jonas Martin         jonas martin
13   Kamaldeen Sulemana   kamaldeen sulemana
14     Lesley Ugochukwu     lesley ugochukwu
15            Loïc Badé            loic bade
16      Lorenz Assignon      lorenz assignon
17        Loum Tchaouna        loum tchaouna
18          Lovro Majer          lovro majer
19         M'Baye Niang         m baye niang
20       Martin Terrier       martin terrier
21           Mathys Tel           mathys tel
22       Matthis Abline       matthis abline
23        Metehan Güçlü        metehan guclu
24         Nayef Aguerd         nayef aguerd
25           Pépé Bonet           pepe bonet
26         Romain Salin         romain salin
27      Serhou Guirassy      serhou guirassy
28         Warmed Omari         warmed omari

============================================================
  Stade de Reims  —  SF sin salario:

            player  minutesPlayed
0  Ibrahim Diakité             14
1     Kaj Sierhuis             80
2   Kamory Doumbia            348
3   Martin Adeline            347
4      N'Dri Koffi            384
5  Samuel Koeberle              1

  CG plantilla completa:

                 player          player_norm
0          Alexis Flips         alexis flips
1      Anastasios Donis     anastasios donis
2     Andreaw Gravillon    andreaw gravillon
3          Arbër Zeneli         arber zeneli
4         Azor Matusiwa        azor matusiwa
5         Bradley Locko        bradley locko
6             Dion Lopy            dion lopy
7        El Bilal Touré       el bilal toure
8         Fodé Doucouré        fode doucoure
9         Fraser Hornby        fraser hornby
10       Ghislain Konan       ghislain konan
11         Hugo Ekitike         hugo ekitike
12          Ilan Kebbal          ilan kebbal
13         Jens Cajuste         jens cajuste
14         Mamadou Mbow         mamadou mbow
15     Marshall Munetsi     marshall munetsi
16       Mathieu Cafaro       mathieu cafaro
17          Maxime Busi          maxime busi
18  Mitchell van Bergen  mitchell van bergen
19       Moreto Cassamá       moreto cassama
20       Moussa Doumbia       moussa doumbia
21      Nathanaël Mbuku      nathanael mbuku
22    Nicolas Penneteau    nicolas penneteau
23     Predrag Rajkovic     predrag rajkovic
24       Sambou Sissoko       sambou sissoko
25         Thomas Foket         thomas foket
26        Valon Berisha        valon berisha
27            Wout Faes            wout faes
28        Yehvann Diouf        yehvann diouf
29     Yunis Abdelhamid     yunis abdelhamid

============================================================
  Troyes  —  SF sin salario:

               player  minutesPlayed
0   Derek Mazou-Sacko              2
1           Eric N'jo             96
2      Mamadou Camara             38
3  Mykola Kukharevych             22

  CG plantilla completa:

               player        player_norm
0          Abdu Conté         abdu conte
1           Adil Rami          adil rami
2   Benrandy Abdallah  benrandy abdallah
3   Brandon Dominguès  brandon domingues
4        Calvin Bombo       calvin bombo
5      Dylan Chambost     dylan chambost
6      Eden Massouema     eden massouema
7   Erik Palmer-Brown  erik palmer brown
8     Florian Tardieu    florian tardieu
9     Gabriel Mutombo    gabriel mutombo
10    Gauthier Gallon    gauthier gallon
11   Gerson Rodrigues   gerson rodrigues
12   Giulian Biancone   giulian biancone
13       Hyun-jun Suk       hyun jun suk
14           Iké Ugbo           ike ugbo
15        Issa Kaboré        issa kabore
16       Jessy Moulin       jessy moulin
17     Jimmy Giraudon     jimmy giraudon
18      Karim Azamoum      karim azamoum
19       Lebo Mothiba       lebo mothiba
20        Levi Lumeka        levi lumeka
21          Luka Ilic          luka ilic
22         Mama Baldé         mama balde
23            Metinho            metinho
24      Nassim Chadli      nassim chadli
25   Oualid El Hajjam   oualid el hajjam
26    Patrick Roberts    patrick roberts
27   Philippe Sandler   philippe sandler
28      Renaud Ripart      renaud ripart
29   Rominigue Kouamé   rominigue kouame
30      Ryan Bouallak      ryan bouallak
31    Sébastien Renot    sebastien renot
32     Tanguy Zoukrou     tanguy zoukrou
33    Tristan Dingomé    tristan dingome
34  Xavier Chavalerin  xavier chavalerin
35     Yasser Larouci     yasser larouci
36      Yoann Salmier      yoann salmier
37     Yoann Touzghar     yoann touzghar
38      Youssouf Koné      youssouf kone

In [21]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('boubakar kouyate', 'metz'): ('kiki kouyate', 'metz'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [22]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: boubakar kouyate (metz) → kiki kouyate (metz)

Tras matches manuales: 530/591 (89.7%)

In [23]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [24]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_france_2122.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_france_2122.csv
   Jugadores totales:  591
   Con salario:        530
   Sin salario (NaN):  61
   Columnas:           121