# 03 · Join Sofascore + Capology — France Ligue 1 22/23

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2022/23 de Ligue 1 francesa**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_france_2223.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_france_2223.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  586 jugadores | 116 columnas
Capology:   629 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   as monaco
   clermont foot
   olympique de marseille
   olympique lyonnais
   paris saint germain
   rc lens
   rc strasbourg
   stade brestois
   stade de reims
   stade rennais

En Capology pero no en Sofascore:
   brest
   clermont
   lens
   lyon
   marseille
   monaco
   psg
   reims
   rennes
   strasbourg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'brest':'stade brestois',
            'clermont':'clermont foot',
            'lens':'rc lens',
            'lyon':'olympique lyonnais',
            'marseille':'olympique de marseille',
            'monaco':'as monaco',
            'psg':'paris saint germain',
            'reims':'stade de reims',
            'rennes':'stade rennais',
            'strasbourg':'rc strasbourg'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 514/586 (87.7%)
Sin emparejar: 72

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          4
Revisión media    (0.75 ≤ score < 0.90):   2
Revisión estricta (0.50 ≤ score < 0.75):   35
Revisión muy est. (score < 0.50):           31

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf     team               cg_match  score
2   Przemysław Frankowski  RC Lens  przemyslaw frankowski  0.976
56          Darlin Yongwa  Lorient         darline yongwa  0.963
26          Łukasz Poręba  RC Lens          lukasz poreba  0.960
41           Marcin Bułka     Nice           marcin bulka  0.957

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf                    team     cg_match  score
40  Enzo Tchato Mbiayi             Montpellier  enzo tchato  0.759
4   Luis Javier Suárez  Olympique de Marseille  luis suarez  0.759

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 2 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
27,Ahmadou Bamba Dieng,Lorient,bamba dieng,0.733
57,Kévin Keben Biakolo,Toulouse,kevin keben,0.733
8,Muhammed-Cham Saračević,Clermont Foot,muhammed cham,0.722
6,Alexsandro Ribeiro,Lille,alexsandro,0.714
31,Mamadou Sarr,Olympique Lyonnais,amin sarr,0.667
12,David Pereira da Costa,RC Lens,david costa,0.667
5,Boubakar Kouyaté,Montpellier,kiki kouyate,0.643
69,Andrea Dacourt,Nice,andy delort,0.640
20,Aïman Maurer,Clermont Foot,maximiliano caufriez,0.625
0,Armand Laurienté,Lorient,ayman kari,0.615
54,Victor Lebas,Ajaccio,paolo lebas,0.609
42,Jean Fiacre Kouamé Botué,Ajaccio,jean botue,0.588
7,Lilian Raolisoa,Angers,marin jakolis,0.571
65,Mathis Hamdi,Troyes,adil rami,0.571
24,Stredair Appuah,Nantes,dennis appiah,0.571
18,Cédric Bakambu,Olympique de Marseille,eric bailly,0.560
66,Christian Mawissa,Toulouse,theocharis tsingaras,0.541
36,Ayoub Amraoui,Nice,daouda traore,0.538
48,Axel Gueguin,Montpellier,valere germain,0.538
67,Amine Messoussa,Lille,andre gomes,0.538
3,Nathan N'Goumou,Toulouse,anthony rouault,0.533
47,Alan Do Marcolino,Stade Rennais,arnaud kalimuendo,0.529
9,Ruan Potó,Ajaccio,jean botue,0.526
29,Gaël Kakuta,RC Lens,ismael boura,0.522
62,Danel Dongmo,Troyes,tristan dingome,0.519
44,Marvin Senaya,RC Strasbourg,gerzino nyamsi,0.519
39,Kyliane Dong,Troyes,tristan dingome,0.519
10,Jean Claude Billong,Clermont Foot,baila diallo,0.516
50,Ben Hamed Toure,Ajaccio,mohamed youssouf,0.516
64,Justin-Noel Kalumba,Angers,amine salama,0.516
1,Lucas Paquetá,Olympique Lyonnais,castello lukeba,0.500
28,Naatan Skyttä,Toulouse,logan costa,0.500
14,Loïc Badé,Stade Rennais,lovro majer,0.500
38,Ibrahim Diakité,Stade de Reims,rafik guitane,0.500
45,Mohamed Touré,Stade de Reims,maxime busi,0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['ahmadou bamba dieng',
                    'kevin keben biakolo',
                    'muhammed cham saracevic',
                    'alexsandro ribeiro',
                    'david pereira da costa',
                    'boubakar kouyate',
                    'jean fiacre kouame botue',
                    
                    
                    
                    
                    

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 7

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf                    team             cg_match  score
49            Ivane Chegra                 Ajaccio    vincent marchetti  0.483
52          El Bilal Touré          Stade de Reims      folarin balogun  0.483
34        Jason Berthomier           Clermont Foot        johan gastien  0.483
30         Mamadou Diakhon          Stade de Reims       kamory doumbia  0.483
32         Duje Ćaleta-Car  Olympique de Marseille       jelle van neck  0.483
13            Cheick Keita          Stade de Reims        patrick pentz  0.480
68         Samuel Koeberle          Stade de Reims  mitchell van bergen  0.471
11        Flavius Daniliuc                    Nice       lucas da cunha  0.467
58            Patrick Berg                 RC Lens       yannick pandor  0.462
22           Calvin Stengs                    Nice        antoine mendy  0.462
16             Nathan Zeze                  Nantes      fabien centonze  0.462
23               Edan Diop               AS Monaco        krepin diatta  0.455
60               Dany Jean           RC Strasbourg        morgan sanson  0.455
59       Derek Mazou-Sacko                  Troyes       yasser larouci  0.452
15       Eli Junior Kroupi                 Lorient  jean victor makengo  0.444
63         Franci Bouebari           RC Strasbourg         sanjin prcic  0.444
53    François Régis Mughe  Olympique de Marseille     valentin rongier  0.444
51         Serhou Guirassy           Stade Rennais         amine gouiri  0.444
43  Valentin Atangana Edoa          Stade de Reims       martin adeline  0.444
35     Mehdi Puch-Herrantz                 Ajaccio        cedric avinel  0.438
17             Fallou Fall          Stade de Reims         alexis flips  0.435
70             Simon Ramet                   Lille         mohamed bayo  0.435
61         Anthony Khelifa                 Ajaccio        sacha contena  0.429
55            Serigne Faye             Montpellier     theo sainte luce  0.429
25              Rudy Kohon                  Troyes       tanguy zoukrou  0.417
71            Théo Trinker                    Nice         ross barkley  0.417
19               Wout Faes          Stade de Reims     thibault de smet  0.400
46             Tony Strata                 Ajaccio       romain hamouma  0.400
37           Cheick Konaté           Clermont Foot        johan gastien  0.385
33         Hianga'a M'Bock          Stade Brestois         mahdi camara  0.370
21            Yusuf Yazıcı                   Lille      lucas chevalier  0.320

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 527/586 (89.9%)
Sin salario:     59

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 59

,player,team,minutesPlayed,appearances,goals,assists
0,Edan Diop,AS Monaco,219,7,1,0
1,Ben Hamed Toure,Ajaccio,210,4,0,0
2,Ivane Chegra,Ajaccio,189,6,0,0
3,Tony Strata,Ajaccio,136,3,0,0
4,Victor Lebas,Ajaccio,55,1,0,0
5,Mehdi Puch-Herrantz,Ajaccio,44,4,0,0
6,Ruan Potó,Ajaccio,23,3,0,0
7,Anthony Khelifa,Ajaccio,9,2,0,0
8,Justin-Noel Kalumba,Angers,550,7,0,0
9,Lilian Raolisoa,Angers,167,7,1,0
10,Cheick Konaté,Clermont Foot,579,9,0,0
11,Aïman Maurer,Clermont Foot,504,10,0,1
12,Jean Claude Billong,Clermont Foot,22,1,0,0
13,Jason Berthomier,Clermont Foot,21,2,0,0
14,Yusuf Yazıcı,Lille,205,4,1,1
15,Amine Messoussa,Lille,1,1,0,0
16,Simon Ramet,Lille,1,1,0,0
17,Armand Laurienté,Lorient,267,3,1,0
18,Eli Junior Kroupi,Lorient,13,1,0,0
19,Serigne Faye,Montpellier,40,2,0,0
20,Axel Gueguin,Montpellier,29,5,0,0
21,Stredair Appuah,Nantes,75,5,0,0
22,Nathan Zeze,Nantes,60,1,0,0
23,Ayoub Amraoui,Nice,297,7,0,0
24,Calvin Stengs,Nice,214,4,0,0
25,Flavius Daniliuc,Nice,91,2,0,0
26,Andrea Dacourt,Nice,1,1,0,0
27,Théo Trinker,Nice,1,1,0,0
28,Lucas Paquetá,Olympique Lyonnais,161,2,0,0
29,Mamadou Sarr,Olympique Lyonnais,11,1,0,0
30,Cédric Bakambu,Olympique de Marseille,56,3,0,1
31,Duje Ćaleta-Car,Olympique de Marseille,12,1,0,0
32,François Régis Mughe,Olympique de Marseille,10,1,0,0
33,Patrick Berg,RC Lens,27,3,0,0
34,Gaël Kakuta,RC Lens,20,2,0,0
35,Franci Bouebari,RC Strasbourg,74,2,0,0
36,Dany Jean,RC Strasbourg,16,2,0,0
37,Marvin Senaya,RC Strasbourg,8,1,0,0
38,Hianga'a M'Bock,Stade Brestois,14,2,0,0
39,Loïc Badé,Stade Rennais,90,1,0,1
40,Serhou Guirassy,Stade Rennais,22,1,0,0
41,Alan Do Marcolino,Stade Rennais,20,3,0,0
42,Cheick Keita,Stade de Reims,687,9,0,0
43,Wout Faes,Stade de Reims,270,3,0,0
44,Valentin Atangana Edoa,Stade de Reims,175,7,0,0
45,Ibrahim Diakité,Stade de Reims,132,3,0,0
46,El Bilal Touré,Stade de Reims,91,3,0,0
47,Fallou Fall,Stade de Reims,31,1,0,0
48,Mohamed Touré,Stade de Reims,31,3,0,0
49,Mamadou Diakhon,Stade de Reims,20,2,0,0
50,Samuel Koeberle,Stade de Reims,2,1,0,0
51,Christian Mawissa,Toulouse,102,2,0,0
52,Nathan N'Goumou,Toulouse,90,1,0,0
53,Naatan Skyttä,Toulouse,21,2,0,0
54,Kyliane Dong,Troyes,217,6,0,0
55,Mathis Hamdi,Troyes,70,2,0,0
56,Rudy Kohon,Troyes,63,1,0,0
57,Danel Dongmo,Troyes,19,2,0,0
58,Derek Mazou-Sacko,Troyes,15,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  AS Monaco  —  SF sin salario:

      player  minutesPlayed
0  Edan Diop            219

  CG plantilla completa:

                player         player_norm
0    Aleksandr Golovin   aleksandr golovin
1      Alexander Nübel     alexander nubel
2          Axel Disasi         axel disasi
3    Benoît Badiashile   benoit badiashile
4         Breel Embolo        breel embolo
5        Caio Henrique       caio henrique
6    Chrislain Matsima   chrislain matsima
7   Eliesse Ben Seghir  eliesse ben seghir
8         Eliot Matazo        eliot matazo
9     Félix Lemaréchal    felix lemarechal
10      Gelson Martins      gelson martins
11   Guillermo Maripán   guillermo maripan
12       Ismail Jakobs       ismail jakobs
13          Jean Lucas          jean lucas
14       Kevin Volland       kevin volland
15       Krépin Diatta       krepin diatta
16   Maghnes Akliouche   maghnes akliouche
17         Malang Sarr         malang sarr
18      Mohamed Camara      mohamed camara
19         Myron Boadu         myron boadu
20       Ruben Aguilar       ruben aguilar
21  Soungoutou Magassa  soungoutou magassa
22     Takumi Minamino     takumi minamino
23     Thomas Didillon     thomas didillon
24           Vanderson           vanderson
25     Willem Geubbels     willem geubbels
26   Wissam Ben Yedder   wissam ben yedder
27        Yann Lienard        yann lienard
28          Yllan Okou          yllan okou
29     Youssouf Fofana     youssouf fofana

============================================================
  Ajaccio  —  SF sin salario:

                player  minutesPlayed
0      Anthony Khelifa              9
1      Ben Hamed Toure            210
2         Ivane Chegra            189
3  Mehdi Puch-Herrantz             44
4            Ruan Potó             23
5          Tony Strata            136
6         Victor Lebas             55

  CG plantilla completa:

                       player                player_norm
0            Alassane N'Diaye           alassane n diaye
1              Benjamin Leroy             benjamin leroy
2          Bevic Moussiti-Oko         bevic moussiti oko
3               Cédric Avinel              cedric avinel
4             Chaker Alhadhur            chaker alhadhur
5               Clément Vidal              clement vidal
6              Cyrille Bayala             cyrille bayala
7             Fernand Mayembo            fernand mayembo
8           Florian Chabrolle          florian chabrolle
9   François-Joseph Sollacaro  francois joseph sollacaro
10       Ghjuvanni Quilichini       ghjuvanni quilichini
11              Ismaël Diallo              ismael diallo
12                 Jean Botué                 jean botue
13        Jean-Dominique Leca        jean dominique leca
14            Kevin Spadanuda            kevin spadanuda
15          Mathieu Coutadeur          mathieu coutadeur
16           Mickaël Alphonse           mickael alphonse
17            Mickaël Barreto            mickael barreto
18           Mohamed Youssouf           mohamed youssouf
19         Mounaïm El Idrissy         mounaim el idrissy
20              Moussa Djitté              moussa djitte
21             Moussa Soumano             moussa soumano
22             Oumar Gonzalez             oumar gonzalez
23                Paolo Lebas                paolo lebas
24                 Qazim Laçi                 qazim laci
25                 Riad Nouri                 riad nouri
26             Romain Hamouma             romain hamouma
27                Ruan Levine                ruan levine
28              Sacha Contena              sacha contena
29             Thomas Mangani             thomas mangani
30          Vincent Marchetti          vincent marchetti
31            Yanis Cimignani            yanis cimignani
32             Yoann Touzghar             yoann touzghar
33             Youcef Belaïli             youcef belaili
34              Youssouf Koné              youssouf kone

============================================================
  Angers  —  SF sin salario:

                player  minutesPlayed
0  Justin-Noel Kalumba            550
1      Lilian Raolisoa            167

  CG plantilla completa:

                  player           player_norm
0          Abdallah Sima         abdallah sima
1        Abdoulaye Bamba       abdoulaye bamba
2           Adrien Hunou          adrien hunou
3              Ali Kalla             ali kalla
4           Amine Salama          amine salama
5       Antonin Bobichon      antonin bobichon
6        Azzedine Ounahi       azzedine ounahi
7          Batista Mendy         batista mendy
8      Cédric Hountondji     cedric hountondji
9         Faouzi Ghoulam        faouzi ghoulam
10       Farid El Melali       farid el melali
11       Halid Sabanovic       halid sabanovic
12         Himad Abdelli         himad abdelli
13        Ibrahim Amadou        ibrahim amadou
14        Ibrahima Niane        ibrahima niane
15          Ilyes Chetti          ilyes chetti
16           Jason Mbock           jason mbock
17    Jean-Mattéo Bahoya    jean matteo bahoya
18            Loïs Diony            lois diony
19         Marin Jakolis         marin jakolis
20          Melvin Zinga          melvin zinga
21           Miha Blazic           miha blazic
22        Nabil Bentaleb        nabil bentaleb
23        Ousmane Camara        ousmane camara
24       Paul Bernardoni       paul bernardoni
25      Pierrick Capelle      pierrick capelle
26           Sada Thioub           sada thioub
27        Sofiane Boufal        sofiane boufal
28     Souleyman Doumbia     souleyman doumbia
29            Théo Borne            theo borne
30     Ulrick Eneme-Ella     ulrick eneme ella
31          Waniss Taïbi          waniss taibi
32          Yahia Fofana          yahia fofana
33            Yan Valery            yan valery
34       Yassin Belkhdim       yassin belkhdim
35  Zinédine Ould Khaled  zinedine ould khaled

============================================================
  Clermont Foot  —  SF sin salario:

                player  minutesPlayed
0         Aïman Maurer            504
1        Cheick Konaté            579
2     Jason Berthomier             21
3  Jean Claude Billong             22

  CG plantilla completa:

                  player           player_norm
0            Alidu Seidu           alidu seidu
1            Arial Mendy           arial mendy
2           Baïla Diallo          baila diallo
3          Brandon Baiye         brandon baiye
4        Elbasan Rashani       elbasan rashani
5          Florent Ogier         florent ogier
6           Grejohn Kyei          grejohn kyei
7           Jérémie Bela          jeremie bela
8          Jim Allevinah         jim allevinah
9           Jodel Dossou          jodel dossou
10         Johan Gastien         johan gastien
11         Komnen Andric         komnen andric
12       Lucas Margueron       lucas margueron
13      Mateusz Wieteska      mateusz wieteska
14       Maxime Gonalons       maxime gonalons
15  Maximiliano Caufriez  maximiliano caufriez
16         Mehdi Zeffane         mehdi zeffane
17             Mory Diaw             mory diaw
18         Muhammed Cham         muhammed cham
19           Neto Borges           neto borges
20         Oliver Kamdem         oliver kamdem
21        Ouparine Djoco        ouparine djoco
22    Saîf-Eddine Khaoui    saif eddine khaoui
23      Souleymane Cissé      souleymane cisse
24        Yanis Massolin        yanis massolin
25         Yohann Magnin         yohann magnin

============================================================
  Lille  —  SF sin salario:

            player  minutesPlayed
0  Amine Messoussa              1
1      Simon Ramet              1
2     Yusuf Yazıcı            205

  CG plantilla completa:

                 player          player_norm
0         Adam Jakubech        adam jakubech
1            Adam Ounas           adam ounas
2          Akim Zedadka         akim zedadka
3        Alan Virginius       alan virginius
4            Alexsandro           alexsandro
5           André Gomes          andre gomes
6           Angel Gomes          angel gomes
7        Bafodé Diakité       bafode diakite
8        Benjamin André       benjamin andre
9         Benoît Costil        benoit costil
10        Carlos Baleba        carlos baleba
11        Edon Zhegrova        edon zhegrova
12  Gabriel Gudmundsson  gabriel gudmundsson
13        Isaac Lihadji        isaac lihadji
14              Ismaily              ismaily
15         Jonas Martin         jonas martin
16       Jonathan Bamba       jonathan bamba
17       Jonathan David       jonathan david
18           José Fonte           jose fonte
19            Leny Yoro            leny yoro
20           Léo Jardim           leo jardim
21      Lucas Chevalier      lucas chevalier
22         Mohamed Bayo         mohamed bayo
23         Rémy Cabella         remy cabella
24          Tiago Djaló          tiago djalo
25         Timothy Weah         timothy weah

============================================================
  Lorient  —  SF sin salario:

              player  minutesPlayed
0   Armand Laurienté            267
1  Eli Junior Kroupi             13

  CG plantilla completa:

                 player          player_norm
0        Adil Aouchiche       adil aouchiche
1          Adrian Grbic         adrian grbic
2            Ayman Kari           ayman kari
3           Bamba Dieng          bamba dieng
4            Bamo Meïté           bamo meite
5        Bonke Innocent       bonke innocent
6     Chrislain Matsima    chrislain matsima
7        Dango Ouattara       dango ouattara
8        Darline Yongwa       darline yongwa
9           Enzo Le Fée          enzo le fee
10        Gédéon Kalulu        gedeon kalulu
11        Ibrahima Koné        ibrahima kone
12           Igor Silva           igor silva
13  Jean-Victor Makengo  jean victor makengo
14   Julian Pollersbeck   julian pollersbeck
15       Julien Laporte       julien laporte
16       Julien Ponceau       julien ponceau
17      Laurent Abergel      laurent abergel
18       Maxime Wackers       maxime wackers
19      Montassar Talbi      montassar talbi
20     Quentin Boisgard     quentin boisgard
21        Romain Faivre        romain faivre
22         Samuel Loric         samuel loric
23      Siriné Doucouré      sirine doucoure
24      Stéphane Diarra      stephane diarra
25      Teddy Bartouche      teddy bartouche
26          Terem Moffi          terem moffi
27         Théo Le Bris         theo le bris
28      Vincent Le Goff      vincent le goff
29         Vito Mannone         vito mannone
30       Yoann Cathline       yoann cathline
31           Yvon Mvogo           yvon mvogo

============================================================
  Montpellier  —  SF sin salario:

         player  minutesPlayed
0  Axel Gueguin             29
1  Serigne Faye             40

  CG plantilla completa:

                 player          player_norm
0         Arnaud Nordin        arnaud nordin
1        Arnaud Souquet       arnaud souquet
2         Béni Makouana        beni makouana
3      Benjamin Lecomte     benjamin lecomte
4      Bingourou Kamara     bingourou kamara
5   Christopher Jullien  christopher jullien
6       Dimitry Bertaud      dimitry bertaud
7             Elye Wahi            elye wahi
8           Enzo Tchato          enzo tchato
9      Faitout Maouassa     faitout maouassa
10         Falaye Sacko         falaye sacko
11        Issiaga Sylla        issiaga sylla
12          Jonas Omlin          jonas omlin
13         Jordan Ferri         jordan ferri
14        Joris Chotard        joris chotard
15         Khalil Fayad         khalil fayad
16         Kiki Kouyaté         kiki kouyate
17            Léo Leroy            leo leroy
18        Mamadou Sakho        mamadou sakho
19       Mathías Suárez       mathias suarez
20       Matis Carvalho       matis carvalho
21        Maxime Estève        maxime esteve
22        Nicolas Cozza        nicolas cozza
23         Pedro Mendes         pedro mendes
24         Sacha Delaye         sacha delaye
25      Stephy Mavididi      stephy mavididi
26        Téji Savanier        teji savanier
27     Théo Sainte-Luce     theo sainte luce
28       Thibault Tamas       thibault tamas
29       Valère Germain       valere germain
30         Wahbi Khazri         wahbi khazri
31     Yanis Guermouche     yanis guermouche

============================================================
  Nantes  —  SF sin salario:

            player  minutesPlayed
0      Nathan Zeze             60
1  Stredair Appuah             75

  CG plantilla completa:

                      player               player_norm
0         Abdoul Kader Bamba        abdoul kader bamba
1               Alban Lafont              alban lafont
2             Andrei Girotto            andrei girotto
3                Andy Delort               andy delort
4             Charles Traoré            charles traore
5               Denis Petric              denis petric
6              Dennis Appiah             dennis appiah
7             Evann Guessand            evann guessand
8            Fabien Centonze           fabien centonze
9                      Fábio                     fabio
10            Florent Mollet            florent mollet
11             Gor Manvelyan             gor manvelyan
12           Ignatius Ganago           ignatius ganago
13             Jaouen Hadjam             jaouen hadjam
14  Jean-Charles Castelletto  jean charles castelletto
15               João Victor               joao victor
16          Joe-Loic Affamah          joe loic affamah
17             Lohann Doucet             lohann doucet
18              Ludovic Blas              ludovic blas
19               Marcus Coco               marcus coco
20              Mohamed Achi              mohamed achi
21               Moses Simon               moses simon
22           Mostafa Mohamed           mostafa mohamed
23            Moussa Sissoko            moussa sissoko
24           Nicolas Pallois           nicolas pallois
25          Pedro Chirivella          pedro chirivella
26            Quentin Merlin            quentin merlin
27             Rémy Descamps             remy descamps
28             Robin Voisine             robin voisine
29        Samuel Moutoussamy        samuel moutoussamy
30        Samuel Yépié Yépié        samuel yepie yepie
31         Sébastien Corchia         sebastien corchia

============================================================
  Nice  —  SF sin salario:

             player  minutesPlayed
0    Andrea Dacourt              1
1     Ayoub Amraoui            297
2     Calvin Stengs            214
3  Flavius Daniliuc             91
4      Théo Trinker              1

  CG plantilla completa:

                   player            player_norm
0            Aaron Ramsey           aaron ramsey
1        Alexis Beka Beka       alexis beka beka
2             Andy Delort            andy delort
3           Antoine Mendy          antoine mendy
4      Badredine Bouanani     badredine bouanani
5          Billal Brahimi         billal brahimi
6                   Dante                  dante
7           Daouda Traoré          daouda traore
8          Gaëtan Laborde         gaetan laborde
9         Hicham Boudaoui        hicham boudaoui
10      Jean-Clair Todibo      jean clair todibo
11              Joe Bryan              joe bryan
12         Jordan Lotomba         jordan lotomba
13      Kasper Schmeichel      kasper schmeichel
14        Khéphren Thuram        khephren thuram
15         Lucas Da Cunha         lucas da cunha
16     Mads Bech Sörensen     mads bech sorensen
17           Marcin Bulka           marcin bulka
18           Mario Lemina           mario lemina
19            Mattia Viti            mattia viti
20            Melvin Bard            melvin bard
21    Morgan Schneiderlin    morgan schneiderlin
22           Nicolas Pépé           nicolas pepe
23          Pablo Rosario          pablo rosario
24             Rares Ilie             rares ilie
25         Reda Belahyane         reda belahyane
26           Ross Barkley           ross barkley
27           Sofiane Diop           sofiane diop
28        Teddy Boulhendi        teddy boulhendi
29            Terem Moffi            terem moffi
30            Youcef Atal            youcef atal
31  Youssouf Ndayishimiye  youssouf ndayishimiye

============================================================
  Olympique Lyonnais  —  SF sin salario:

          player  minutesPlayed
0  Lucas Paquetá            161
1   Mamadou Sarr             11

  CG plantilla completa:

                 player          player_norm
0   Alexandre Lacazette  alexandre lacazette
1             Amin Sarr            amin sarr
2         Anthony Lopes        anthony lopes
3       Bradley Barcola      bradley barcola
4       Castello Lukeba      castello lukeba
5      Corentin Tolisso     corentin tolisso
6       Damien Da Silva      damien da silva
7          Dejan Lovren         dejan lovren
8      Florent Da Silva     florent da silva
9              Henrique             henrique
10        Houssem Aouar        houssem aouar
11  Jeff Reine-Adélaïde  jeff reine adelaide
12             Jeffinho             jeffinho
13       Jérôme Boateng       jerome boateng
14      Johann Lepenant      johann lepenant
15   Julian Pollersbeck   julian pollersbeck
16     Karl Toko Ekambi     karl toko ekambi
17       Kayne Bonnevie       kayne bonnevie
18           Malo Gusto           malo gusto
19     Maxence Caqueret     maxence caqueret
20    Mohamed El Arouch    mohamed el arouch
21       Moussa Dembélé       moussa dembele
22   Nicolás Tagliafico   nicolas tagliafico
23         Rayan Cherki         rayan cherki
24            Rémy Riou            remy riou
25        Romain Faivre        romain faivre
26         Saël Kumbedi         sael kumbedi
27      Sinaly Diomandé      sinaly diomande
28                 Tetê                 tete
29        Thiago Mendes        thiago mendes

============================================================
  Olympique de Marseille  —  SF sin salario:

                 player  minutesPlayed
0        Cédric Bakambu             56
1       Duje Ćaleta-Car             12
2  François Régis Mughe             10

  CG plantilla completa:

                    player             player_norm
0           Alexis Sánchez          alexis sanchez
1              Amine Harit             amine harit
2          Arkadiusz Milik         arkadiusz milik
3      Aylan Benyahia-Tani     aylan benyahia tani
4          Azzedine Ounahi         azzedine ounahi
5              Bamba Dieng             bamba dieng
6             Bartug Elmaz            bartug elmaz
7             Cengiz Ünder            cengiz under
8           Chancel Mbemba          chancel mbemba
9            Dimitri Payet           dimitri payet
10             Eric Bailly             eric bailly
11                  Gerson                  gerson
12             Issa Kabore             issa kabore
13          Jelle Van Neck          jelle van neck
14         Jonathan Clauss         jonathan clauss
15         Jordan Veretout         jordan veretout
16        Leonardo Balerdi        leonardo balerdi
17             Luis Suárez             luis suarez
18        Mattéo Guendouzi        matteo guendouzi
19            Nuno Tavares            nuno tavares
20              Pape Gueye              pape gueye
21               Pau López               pau lopez
22            Rubén Blanco            ruben blanco
23      Ruslan Malinovskyi      ruslan malinovskyi
24        Salim Ben Seghir        salim ben seghir
25            Samuel Gigot            samuel gigot
26          Sead Kolasinac          sead kolasinac
27    Simon Ngapandouetnbu    simon ngapandouetnbu
28  Souleymane Isaak Touré  souleymane isaak toure
29        Valentin Rongier        valentin rongier
30                 Vitinha                 vitinha

============================================================
  RC Lens  —  SF sin salario:

         player  minutesPlayed
0   Gaël Kakuta             20
1  Patrick Berg             27

  CG plantilla completa:

                   player            player_norm
0              Adam Buksa             adam buksa
1            Adam Oudjani           adam oudjani
2          Adrien Louveau         adrien louveau
3        Adrien Thomasson       adrien thomasson
4   Alexis Claude-Maurice  alexis claude maurice
5          Angelo Fulgini         angelo fulgini
6             Brice Samba            brice samba
7             David Costa            david costa
8          Deiver Machado         deiver machado
9          Facundo Medina         facundo medina
10         Florian Sotoca         florian sotoca
11           Ismaël Boura           ismael boura
12        Jean-Louis Leca        jean louis leca
13             Jean Onana             jean onana
14            Jimmy Cabot            jimmy cabot
15        Jonathan Gradit        jonathan gradit
16     Julien Le Cardinal     julien le cardinal
17            Kevin Danso            kevin danso
18            Loïs Openda            lois openda
19          Lukasz Poreba          lukasz poreba
20         Mamadou Camara         mamadou camara
21       Massadio Haidara       massadio haidara
22  Przemyslaw Frankowski  przemyslaw frankowski
23    Rémy Labeau Lascary    remy labeau lascary
24      Salis Abdul Samed      salis abdul samed
25            Seko Fofana            seko fofana
26          Steven Fortes          steven fortes
27            Wesley Saïd            wesley said
28        Wuilker Fariñez        wuilker farinez
29         Yannick Pandor         yannick pandor
30            Yaya Fofana            yaya fofana

============================================================
  RC Strasbourg  —  SF sin salario:

            player  minutesPlayed
0        Dany Jean             16
1  Franci Bouebari             74
2    Marvin Senaya              8

  CG plantilla completa:

                    player             player_norm
0         Adrien Thomasson        adrien thomasson
1          Alexander Djiku         alexander djiku
2         Alexandre Pierre        alexandre pierre
3            Aymeric Ahmed           aymeric ahmed
4           Benjamin Besic          benjamin besic
5              Colin Dagba             colin dagba
6          Dimitri Liénard         dimitri lienard
7             Eduard Sobol            eduard sobol
8           Eiji Kawashima          eiji kawashima
9        Frédéric Guilbert       frederic guilbert
10          Gerzino Nyamsi          gerzino nyamsi
11            Habib Diallo            habib diallo
12            Habib Diarra            habib diarra
13        Ibrahima Sissoko        ibrahima sissoko
14         Ismaël Doukouré         ismael doukoure
15       Jean-Eudes Aholou       jean eudes aholou
16  Jean-Ricner Bellegarde  jean ricner bellegarde
17              Karol Fila              karol fila
18           Kévin Gameiro           kevin gameiro
19            Lebo Mothiba            lebo mothiba
20            Lucas Perrin            lucas perrin
21         Ludovic Ajorque         ludovic ajorque
22               Matz Sels               matz sels
23      Maxime Le Marchand      maxime le marchand
24           Morgan Sanson           morgan sanson
25          Nordine Kandil          nordine kandil
26            Robin Risser            robin risser
27   Ronaël Pierre-Gabriel   ronael pierre gabriel
28            Sanjin Prcic            sanjin prcic
29          Thomas Delaine          thomas delaine
30            Yuito Suzuki            yuito suzuki

============================================================
  Stade Brestois  —  SF sin salario:

            player  minutesPlayed
0  Hianga'a M'Bock             14

  CG plantilla completa:

                  player           player_norm
0            Achraf Dari           achraf dari
1           Alberth Elis          alberth elis
2           Axel Camblan          axel camblan
3          Bradley Locko         bradley locko
4     Brendan Chardonnet    brendan chardonnet
5     Christophe Hérelle    christophe herelle
6       Félix Lemaréchal      felix lemarechal
7         Franck Honorat        franck honorat
8       Grégoire Coudert      gregoire coudert
9         Haris Belkebla        haris belkebla
10         Hugo Magnetti         hugo magnetti
11         Irvin Cardona         irvin cardona
12         Islam Slimani         islam slimani
13    Jean-Kévin Duverne    jean kevin duverne
14           Jere Uronen           jere uronen
15     Jérémy Le Douaron     jeremy le douaron
16      Joaquín Blázquez      joaquin blazquez
17        Josué Escartin        josue escartin
18      Karamoko Dembélé      karamoko dembele
19            Kenny Lala            kenny lala
20       Lilian Brassier       lilian brassier
21             Loïc Rémy             loic remy
22          Mahdi Camara          mahdi camara
23           Marco Bizot           marco bizot
24  Mathias Pereira Lage  mathias pereira lage
25           Noah Fadiga           noah fadiga
26     Pierre Lees-Melou     pierre lees melou
27   Romain Del Castillo   romain del castillo
28          Steve Mounié          steve mounie
29        Taïryk Arconte        tairyk arconte
30        Youcef Belaïli        youcef belaili

============================================================
  Stade Rennais  —  SF sin salario:

              player  minutesPlayed
0  Alan Do Marcolino             20
1          Loïc Badé             90
2    Serhou Guirassy             22

  CG plantilla completa:

                 player          player_norm
0       Adrien Truffert      adrien truffert
1          Alfred Gomis         alfred gomis
2          Amine Gouiri         amine gouiri
3     Arnaud Kalimuendo    arnaud kalimuendo
4         Arthur Theate        arthur theate
5   Baptiste Santamaria  baptiste santamaria
6   Benjamin Bourigeaud  benjamin bourigeaud
7         Birger Meling        birger meling
8      Christopher Wooh     christopher wooh
9           Désiré Doué          desire doue
10          Djed Spence          djed spence
11        Dogan Alemdar        dogan alemdar
12        Elias Damergy        elias damergy
13         Flavien Tait         flavien tait
14           Guéla Doué           guela doue
15        Hamari Traoré        hamari traore
16        Ibrahim Salah        ibrahim salah
17     Jeanuël Belocian     jeanuel belocian
18          Jérémy Doku          jeremy doku
19            Joe Rodon            joe rodon
20   Kamaldeen Sulemana   kamaldeen sulemana
21     Karl Toko Ekambi     karl toko ekambi
22     Lesley Ugochukwu     lesley ugochukwu
23      Lorenz Assignon      lorenz assignon
24          Lovro Majer          lovro majer
25       Martin Terrier       martin terrier
26       Matthis Abline       matthis abline
27       Noah Françoise       noah francoise
28         Romain Salin         romain salin
29       Steve Mandanda       steve mandanda
30         Warmed Omari         warmed omari
31                 Xeka                 xeka

============================================================
  Stade de Reims  —  SF sin salario:

                   player  minutesPlayed
0            Cheick Keita            687
1          El Bilal Touré             91
2             Fallou Fall             31
3         Ibrahim Diakité            132
4         Mamadou Diakhon             20
5           Mohamed Touré             31
6         Samuel Koeberle              2
7  Valentin Atangana Edoa            175
8               Wout Faes            270

  CG plantilla completa:

                 player          player_norm
0          Alexis Flips         alexis flips
1     Andreaw Gravillon    andreaw gravillon
2          Arbër Zeneli         arber zeneli
3         Azor Matusiwa        azor matusiwa
4         Bradley Locko        bradley locko
5             Dion Lopy            dion lopy
6      Emmanuel Agbadou     emmanuel agbadou
7      Florent Duparchy     florent duparchy
8       Folarin Balogun      folarin balogun
9          Jens Cajuste         jens cajuste
10            Junya Ito            junya ito
11         Kaj Sierhuis         kaj sierhuis
12       Kamory Doumbia       kamory doumbia
13     Marshall Munetsi     marshall munetsi
14       Martin Adeline       martin adeline
15          Maxime Busi          maxime busi
16  Mitchell van Bergen  mitchell van bergen
17      Myziane Maolida      myziane maolida
18      Nathanaël Mbuku      nathanael mbuku
19    Nicolas Penneteau    nicolas penneteau
20       Noah Jean Holm       noah jean holm
21        Patrick Pentz        patrick pentz
22        Rafik Guitane        rafik guitane
23     Thibault De Smet     thibault de smet
24         Thomas Foket         thomas foket
25        Timothé Nkada        timothe nkada
26        Yehvann Diouf        yehvann diouf
27     Yunis Abdelhamid     yunis abdelhamid

============================================================
  Toulouse  —  SF sin salario:

              player  minutesPlayed
0  Christian Mawissa            102
1      Naatan Skyttä             21
2    Nathan N'Goumou             90

  CG plantilla completa:

                   player            player_norm
0              Ado Onaiwu             ado onaiwu
1         Anthony Rouault        anthony rouault
2   Branco van den Boomen  branco van den boomen
3        Brecht Dejaegere       brecht dejaegere
4           Denis Genreau          denis genreau
5            Farès Chaïbi           fares chaibi
6           Gabriel Suazo          gabriel suazo
7         Isak Pettersson        isak pettersson
8           Issiaga Sylla          issiaga sylla
9        Junior Flemmings       junior flemmings
10            Kévin Keben            kevin keben
11            Kjetil Haug            kjetil haug
12            Logan Costa            logan costa
13            Maxime Dupé            maxime dupe
14          Mikkel Desler          mikkel desler
15          Moussa Diarra          moussa diarra
16          Oliver Zandén          oliver zanden
17           Rafael Ratão           rafael ratao
18      Rasmus Nicolaisen      rasmus nicolaisen
19            Rhys Healey            rhys healey
20           Saïd Hamulic           said hamulic
21        Stijn Spierings        stijn spierings
22   Theocharis Tsingaras   theocharis tsingaras
23         Thijs Dallinga         thijs dallinga
24          Thomas Himeur          thomas himeur
25     Veljko Birmancevic     veljko birmancevic
26         Vincent Sierro         vincent sierro
27         Warren Kamanzi         warren kamanzi
28         Yanis Begraoui         yanis begraoui
29      Zakaria Aboukhlal      zakaria aboukhlal

============================================================
  Troyes  —  SF sin salario:

              player  minutesPlayed
0       Danel Dongmo             19
1  Derek Mazou-Sacko             15
2       Kyliane Dong            217
3       Mathis Hamdi             70
4         Rudy Kohon             63

  CG plantilla completa:

                 player          player_norm
0            Abdu Conté           abdu conte
1             Adil Rami            adil rami
2         Alexis Tibidi        alexis tibidi
3            Amar Fatah           amar fatah
4         Andreas Bruus        andreas bruus
5        Ante Palaversa       ante palaversa
6             Eric N'Jo            eric n jo
7     Erik Palmer-Brown    erik palmer brown
8       Florian Tardieu      florian tardieu
9       Gabriel Mutombo      gabriel mutombo
10      Gauthier Gallon      gauthier gallon
11             Iké Ugbo             ike ugbo
12       Jackson Porozo       jackson porozo
13  Jeff Reine-Adélaïde  jeff reine adelaide
14         Jessy Moulin         jessy moulin
15          Levi Lumeka          levi lumeka
16        Lucien Agoume        lucien agoume
17           Mama Baldé           mama balde
18        Marlos Moreno        marlos moreno
19          Mateusz Lis          mateusz lis
20     Papa Ndiaga Yade     papa ndiaga yade
21        Renaud Ripart        renaud ripart
22     Rominigue Kouamé     rominigue kouame
23           Rony Lopes           rony lopes
24       Tanguy Zoukrou       tanguy zoukrou
25        Thierno Baldé        thierno balde
26      Tristan Dingomé      tristan dingome
27       Wilson Odobert       wilson odobert
28    Xavier Chavalerin    xavier chavalerin
29       Yasser Larouci       yasser larouci
30        Yoann Salmier        yoann salmier

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 527/586 (89.9%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_france_2223.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_france_2223.csv
   Jugadores totales:  586
   Con salario:        527
   Sin salario (NaN):  59
   Columnas:           121