# 03 · Join Sofascore + Capology — Germany Bundesliga 22/23

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2022/23 de Bundesliga alemana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_germany_2223.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_germany_2223.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  506 jugadores | 116 columnas
Capology:   571 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   1 fc koln
   1 fc union berlin
   1 fsv mainz 05
   bayer 04 leverkusen
   borussia m gladbach
   fc augsburg
   fc bayern munchen
   fc schalke 04
   hertha bsc
   rb leipzig
   sc freiburg
   sv werder bremen
   tsg hoffenheim
   vfb stuttgart
   vfl bochum 1848
   vfl wolfsburg

En Capology pero no en Sofascore:
   augsburg
   bayer leverkusen
   bayern munich
   bochum
   freiburg
   hertha berlin
   hoffenheim
   koln
   leipzig
   mainz
   monchengladbach
   schalke 04
   stuttgart
   union berlin
   werder bremen
   wolfsburg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'augsburg':'fc augsburg',
            'bayer leverkusen':'bayer 04 leverkusen',
            'bayern munich':'fc bayern munchen',
            'bochum':'vfl bochum 1848',
            'freiburg':'sc freiburg',
            'hertha berlin':'hertha bsc',
            'hoffenheim':'tsg hoffenheim',
            'koln':'1 fc koln',
            'leipzig':'rb leipzig',
            'mainz':'1 fsv mainz 05',
            'monchengladbach':'borussia m gladbach',
            'schalke 04':'fc schalke 04',
            'stuttgart':'vfb stuttgart',
            'union berlin':'1 fc union berlin',
            'werder bremen':'sv werder bremen',
            'wolfsburg':'vfl wolfsburg'                          
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 457/506 (90.3%)
Sin emparejar: 49

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          11
Revisión media    (0.75 ≤ score < 0.90):   6
Revisión estricta (0.50 ≤ score < 0.75):   21
Revisión muy est. (score < 0.50):           11

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf                 team               cg_match  score
34  Vasilis Lampropoulos      VfL Bochum 1848  vasilios lampropoulos  0.976
17      Dimitris Limnios           1. FC Köln      dimitrios limnios  0.970
15      Jesper Lindstrøm  Eintracht Frankfurt       jesper lindstrom  0.968
5        Rafał Gikiewicz          FC Augsburg        rafal gikiewicz  0.966
4        Frederik Rønnow   1. FC Union Berlin        frederik ronnow  0.966
0         Levin Öztunalı   1. FC Union Berlin         levin oztunali  0.963
35        Stanley N'Soki       TSG Hoffenheim          stanley nsoki  0.963
11           Evan Ndicka  Eintracht Frankfurt           evan n dicka  0.957
2           Ørjan Nyland           RB Leipzig           orjan nyland  0.957
26          Mehmet Aydın        FC Schalke 04           mehmet aydin  0.957
10      Niko Giesselmann   1. FC Union Berlin         niko gieelmann  0.933

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
38,Noah Joel Sarenren Bazee,FC Augsburg,noah sarenren bazee,0.884
23,Joseph Scally,Borussia M'gladbach,joe scally,0.870
20,Jamie Gittens,Borussia Dortmund,jamie bynoe gittens,0.812
8,Leandro Barreiro,1. FSV Mainz 05,leandro barreiro martins,0.800
22,Pierre Kunde,VfL Bochum 1848,pierre kunde malong,0.774
18,Dion Drena Beljo,FC Augsburg,dion beljo,0.769

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 6 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf                 team             cg_match  score
14         John Brooks       TSG Hoffenheim  john anthony brooks  0.733
44   Kingsley Ehizibue           1. FC Köln   kingsley schindler  0.686
6          Jeff Chabot           1. FC Köln        julian chabot  0.667
16  Junior Dina Ebimbe  Eintracht Frankfurt          eric ebimbe  0.621
25               Silas        VfB Stuttgart             gil dias  0.615
42        Dario Gebuhr  Eintracht Frankfurt          mario gotze  0.609
43       Marco Pašalić    Borussia Dortmund           marco reus  0.609
46        Lukáš Ambros        VfL Wolfsburg         lukas nmecha  0.583
21        Rafael Borré  Eintracht Frankfurt         santos borre  0.583
9            Manu Koné  Borussia M'gladbach         kouadio kone  0.571
24        Ricardo Pepi          FC Augsburg        irvin cardona  0.560
47        Stefan Posch       TSG Hoffenheim           justin che  0.545
7      Gabriel Vidović    FC Bayern München   arijon ibrahimovic  0.545
27       Iago Borduchi          FC Augsburg        niklas dorsch  0.538
31           Sidi Sané        FC Schalke 04           tim skarke  0.526
33          Tony Rölke           Hertha BSC        agustin rogel  0.522
29       Aster Vranckx        VfL Wolfsburg       bartol franjic  0.519
45   Alexander Sørloth           RB Leipzig          andre silva  0.519
48     Joshua Quarshie       TSG Hoffenheim     eduardo quaresma  0.516
3       Saša Kalajdžić        VfB Stuttgart       atakan karazor  0.500
19        Malick Thiaw        FC Schalke 04         maya yoshida  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['john brooks',
                    'jeff chabot',
                    'junior dina ebimbe',
                    'rafael borre',
                    'manu kone'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 5

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

            player_sf                 team            cg_match  score
13        Veit Stange           Hertha BSC  oliver christensen  0.483
1        Clinton Mola        VfB Stuttgart           alou kuol  0.476
12       Ibrahim Maza           Hertha BSC      wilfried kanga  0.462
28    Semir Telalović  Borussia M'gladbach         nico elvedi  0.462
32     Pascal Klemens           Hertha BSC   marc oliver kempf  0.452
41     Justin Njinmah    Borussia Dortmund   julien duranville  0.452
40       Filip Kostić  Eintracht Frankfurt     kristijan jakic  0.444
36    Joel Pohjanpalo  Bayer 04 Leverkusen        jonathan tah  0.444
37  Diadié Samassékou       TSG Hoffenheim     andrej kramaric  0.438
30    Darko Churlinov        VfB Stuttgart       laurin ulrich  0.429
39          Keke Topp        FC Schalke 04         jere uronen  0.400

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 479/506 (94.7%)
Sin salario:     27

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 27

,player,team,minutesPlayed,appearances,goals,assists
0,Kingsley Ehizibue,1. FC Köln,62,1,0,0
1,Joel Pohjanpalo,Bayer 04 Leverkusen,11,1,0,0
2,Justin Njinmah,Borussia Dortmund,21,1,0,0
3,Marco Pašalić,Borussia Dortmund,10,1,0,0
4,Semir Telalović,Borussia M'gladbach,21,3,0,0
5,Filip Kostić,Eintracht Frankfurt,74,1,0,0
6,Dario Gebuhr,Eintracht Frankfurt,20,1,0,0
7,Iago Borduchi,FC Augsburg,1606,22,0,2
8,Ricardo Pepi,FC Augsburg,94,4,0,0
9,Gabriel Vidović,FC Bayern München,18,1,0,1
10,Malick Thiaw,FC Schalke 04,270,3,0,0
11,Sidi Sané,FC Schalke 04,24,1,0,0
12,Keke Topp,FC Schalke 04,19,1,0,0
13,Pascal Klemens,Hertha BSC,90,1,0,0
14,Ibrahim Maza,Hertha BSC,70,2,1,0
15,Tony Rölke,Hertha BSC,19,1,0,0
16,Veit Stange,Hertha BSC,11,1,0,0
17,Alexander Sørloth,RB Leipzig,13,1,0,0
18,Diadié Samassékou,TSG Hoffenheim,34,2,0,0
19,Stefan Posch,TSG Hoffenheim,19,1,0,0
20,Joshua Quarshie,TSG Hoffenheim,1,1,0,0
21,Silas,VfB Stuttgart,2010,30,5,2
22,Saša Kalajdžić,VfB Stuttgart,235,3,0,3
23,Darko Churlinov,VfB Stuttgart,26,1,0,0
24,Clinton Mola,VfB Stuttgart,14,1,0,0
25,Lukáš Ambros,VfL Wolfsburg,16,1,0,0
26,Aster Vranckx,VfL Wolfsburg,13,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  1. FC Köln  —  SF sin salario:

              player  minutesPlayed
0  Kingsley Ehizibue             62

  CG plantilla completa:

                 player          player_norm
0         Benno Schmitz        benno schmitz
1           Davie Selke          davie selke
2        Dejan Ljubicic       dejan ljubicic
3     Denis Huseinbasic    denis huseinbasic
4     Dimitrios Limnios    dimitrios limnios
5         Ellyes Skhiri        ellyes skhiri
6           Eric Martel          eric martel
7         Florian Dietz        florian dietz
8         Florian Kainz        florian kainz
9         Georg Strauch        georg strauch
10        Jan Thielmann        jan thielmann
11         Jonas Hector         jonas hector
12          Jonas Urbig          jonas urbig
13     Joshua Schwirten     joshua schwirten
14        Julian Chabot        julian chabot
15        Julian Roloff        julian roloff
16         Justin Diehl         justin diehl
17   Kingsley Schindler   kingsley schindler
18    Kristian Pedersen    kristian pedersen
19         Linton Maina         linton maina
20          Luca Kilian          luca kilian
21             Mark Uth             mark uth
22       Marvin Schwäbe       marvin schwabe
23       Mathias Olesen       mathias olesen
24     Matthias Köbbing     matthias kobbing
25    Maximilian Schmid    maximilian schmid
26         Nikola Soldo         nikola soldo
27          Ondrej Duda          ondrej duda
28         Rijad Smajic         rijad smajic
29       Sargis Adamyan       sargis adamyan
30  Sebastian Andersson  sebastian andersson
31       Steffen Tigges       steffen tigges
32         Tim Lemperle         tim lemperle
33            Timo Horn            timo horn
34          Timo Hübers          timo hubers

============================================================
  Bayer 04 Leverkusen  —  SF sin salario:

            player  minutesPlayed
0  Joel Pohjanpalo             11

  CG plantilla completa:

                 player          player_norm
0           Adam Hlozek          adam hlozek
1            Amine Adli           amine adli
2          Andrey Lunev         andrey lunev
3                Arthur               arthur
4           Ayman Azhil          ayman azhil
5    Callum Hudson-Odoi   callum hudson odoi
6      Charles Aránguiz     charles aranguiz
7      Daley Sinkgraven     daley sinkgraven
8        Edmond Tapsoba       edmond tapsoba
9     Exequiel Palacios    exequiel palacios
10        Florian Wirtz        florian wirtz
11     Jeremie Frimpong     jeremie frimpong
12         Jonathan Tah         jonathan tah
13           Joshua Eze           joshua eze
14      Karim Bellarabi      karim bellarabi
15       Kerem Demirbay       kerem demirbay
16       Lukas Hradecky       lukas hradecky
17       Mitchel Bakker       mitchel bakker
18         Moussa Diaby         moussa diaby
19         Nadiem Amiri         nadiem amiri
20          Niklas Lomb          niklas lomb
21          Noah Mbamba          noah mbamba
22     Odilon Kossounou     odilon kossounou
23        Patrick Pentz        patrick pentz
24        Patrik Schick        patrik schick
25             Paulinho             paulinho
26       Piero Hincapié       piero hincapie
27       Robert Andrich       robert andrich
28        Sardar Azmoun        sardar azmoun
29  Timothy Fosu-Mensah  timothy fosu mensah
30      Zidan Sertdemir      zidan sertdemir

============================================================
  Borussia Dortmund  —  SF sin salario:

           player  minutesPlayed
0  Justin Njinmah             21
1   Marco Pašalić             10

  CG plantilla completa:

                   player            player_norm
0        Abdoulaye Kamara       abdoulaye kamara
1         Alexander Meyer        alexander meyer
2         Anthony Modeste        anthony modeste
3   Antonios Papadopoulos  antonios papadopoulos
4           Donyell Malen          donyell malen
5                Emre Can               emre can
6          Felix Passlack         felix passlack
7          Giovanni Reyna         giovanni reyna
8           Göktan Gürpüz          goktan gurpuz
9            Gregor Kobel           gregor kobel
10    Jamie Bynoe-Gittens    jamie bynoe gittens
11        Jude Bellingham        jude bellingham
12          Julian Brandt          julian brandt
13         Julian Ryerson         julian ryerson
14      Julien Duranville      julien duranville
15          Karim Adeyemi          karim adeyemi
16          Luca Unbehaun          luca unbehaun
17         Mahmoud Dahoud         mahmoud dahoud
18           Marcel Lotka           marcel lotka
19             Marco Reus             marco reus
20            Marius Wolf            marius wolf
21      Mateu Morey Bauzà      mateu morey bauza
22           Mats Hummels           mats hummels
23     Nico Schlotterbeck     nico schlotterbeck
24            Nico Schulz            nico schulz
25            Niklas Süle            niklas sule
26      Raphaël Guerreiro      raphael guerreiro
27            Salih Özcan            salih ozcan
28       Sébastien Haller       sebastien haller
29     Soumaïla Coulibaly     soumaila coulibaly
30         Thomas Meunier         thomas meunier
31         Thorgan Hazard         thorgan hazard
32              Tom Rothe              tom rothe
33      Youssoufa Moukoko      youssoufa moukoko

============================================================
  Borussia M'gladbach  —  SF sin salario:

            player  minutesPlayed
0  Semir Telalović             21

  CG plantilla completa:

                    player             player_norm
0            Alassane Plea           alassane plea
1         Christoph Kramer        christoph kramer
2                Conor Noß                conor no
3          Florian Neuhaus         florian neuhaus
4              Hannes Wolf             hannes wolf
5           Jan Olschowsky          jan olschowsky
6               Joe Scally              joe scally
7            Jonas Hofmann           jonas hofmann
8              Jonas Omlin             jonas omlin
9             Julian Weigl            julian weigl
10              Ko Itakura              ko itakura
11            Kouadio Koné            kouadio kone
12             Lars Stindl             lars stindl
13               Luca Netz               luca netz
14        Mamadou Doucouré        mamadou doucoure
15           Marcus Thuram           marcus thuram
16        Marvin Friedrich        marvin friedrich
17         Nathan N'Goumou         nathan n goumou
18             Nico Elvedi             nico elvedi
19            Oscar Fraulo            oscar fraulo
20        Patrick Herrmann        patrick herrmann
21         Ramy Bensebaini         ramy bensebaini
22             Rocco Reitz             rocco reitz
23             Simon Walde             simon walde
24           Stefan Lainer           stefan lainer
25           Tobias Sippel           tobias sippel
26          Tony Jantschke          tony jantschke
27            Torben Müsel            torben musel
28             Yann Sommer             yann sommer
29  Yvandro Borges Sanches  yvandro borges sanches

============================================================
  Eintracht Frankfurt  —  SF sin salario:

         player  minutesPlayed
0  Dario Gebuhr             20
1  Filip Kostić             74

  CG plantilla completa:

               player        player_norm
0        Almamy Touré       almamy toure
1       Ansgar Knauff      ansgar knauff
2        Aurélio Buta       aurelio buta
3    Christopher Lenz   christopher lenz
4       Daichi Kamada      daichi kamada
5         Diant Ramaj        diant ramaj
6         Djibril Sow        djibril sow
7         Éric Ebimbe        eric ebimbe
8        Evan N'Dicka       evan n dicka
9       Faride Alidou      faride alidou
10     Hrvoje Smolcic     hrvoje smolcic
11       Jan Schröder       jan schroder
12         Jens Grahl         jens grahl
13     Jérôme Onguéné     jerome onguene
14   Jesper Lindström   jesper lindstrom
15        Kevin Trapp        kevin trapp
16    Kristijan Jakic    kristijan jakic
17    Luca Pellegrini    luca pellegrini
18       Lucas Alario       lucas alario
19      Makoto Hasebe      makoto hasebe
20       Marcel Wenig       marcel wenig
21        Mario Götze        mario gotze
22    Matteo Bignetti    matteo bignetti
23        Mehdi Loune        mehdi loune
24        Nacho Ferri        nacho ferri
25    Paxten Aaronson    paxten aaronson
26        Philipp Max        philipp max
27  Randal Kolo Muani  randal kolo muani
28       Santos Borré       santos borre
29     Sebastian Rode     sebastian rode
30       Simon Simoni       simon simoni
31   Timothy Chandler   timothy chandler
32               Tuta               tuta

============================================================
  FC Augsburg  —  SF sin salario:

          player  minutesPlayed
0  Iago Borduchi           1606
1   Ricardo Pepi             94

  CG plantilla completa:

                   player            player_norm
0           Aaron Zehnter          aaron zehnter
1              André Hahn             andre hahn
2             Arne Engels            arne engels
3              Arne Maier             arne maier
4         Benjamin Leneis        benjamin leneis
5           Carlos Gruezo          carlos gruezo
6        Daniel Caligiuri       daniel caligiuri
7            Daniel Klein           daniel klein
8            David Colina           david colina
9              Dion Beljo             dion beljo
10        Elvis Rexhbecaj        elvis rexhbecaj
11      Ermedin Demirovic      ermedin demirovic
12         Felix Uduokhai         felix uduokhai
13  Florian Niederlechner  florian niederlechner
14       Frederik Winther       frederik winther
15         Fredrik Jensen         fredrik jensen
16                   Iago                   iago
17          Irvin Cardona          irvin cardona
18     Jeffrey Gouweleeuw     jeffrey gouweleeuw
19  Julian Baumgartlinger  julian baumgartlinger
20          Kelvin Yeboah          kelvin yeboah
21           Lukas Petkov           lukas petkov
22          Mads Pedersen          mads pedersen
23       Maximilian Bauer       maximilian bauer
24         Mergim Berisha         mergim berisha
25        Nathanaël Mbuku        nathanael mbuku
26          Niklas Dorsch          niklas dorsch
27    Noah Sarenren Bazee    noah sarenren bazee
28        Rafal Gikiewicz        rafal gikiewicz
29     Raphael Framberger     raphael framberger
30           Reece Oxford           reece oxford
31           Renato Veiga           renato veiga
32           Robert Gumny           robert gumny
33           Rubén Vargas           ruben vargas
34         Sergio Córdova         sergio cordova
35          Tobias Strobl          tobias strobl
36           Tomas Koubek           tomas koubek

============================================================
  FC Bayern München  —  SF sin salario:

            player  minutesPlayed
0  Gabriel Vidović             18

  CG plantilla completa:

                      player               player_norm
0            Alphonso Davies           alphonso davies
1         Arijon Ibrahimovic        arijon ibrahimovic
2            Benjamin Pavard           benjamin pavard
3                 Bouna Sarr                bouna sarr
4                Daley Blind               daley blind
5            Dayot Upamecano           dayot upamecano
6   Eric Maxim Choupo-Moting  eric maxim choupo moting
7              Jamal Musiala             jamal musiala
8               João Cancelo              joao cancelo
9            Johannes Schenk           johannes schenk
10            Joshua Kimmich            joshua kimmich
11            Josip Stanisic            josip stanisic
12            Kingsley Coman            kingsley coman
13             Leon Goretzka             leon goretzka
14                Leroy Sané                leroy sane
15           Lucas Hernández           lucas hernandez
16              Manuel Neuer              manuel neuer
17           Marcel Sabitzer           marcel sabitzer
18                Mathys Tel                mathys tel
19          Matthijs de Ligt          matthijs de ligt
20         Noussair Mazraoui         noussair mazraoui
21               Paul Wanner               paul wanner
22          Ryan Gravenberch          ryan gravenberch
23                Sadio Mané                sadio mane
24              Serge Gnabry              serge gnabry
25              Sven Ulreich              sven ulreich
26             Thomas Müller             thomas muller
27               Yann Sommer               yann sommer

============================================================
  FC Schalke 04  —  SF sin salario:

         player  minutesPlayed
0     Keke Topp             19
1  Malick Thiaw            270
2     Sidi Sané             24

  CG plantilla completa:

                    player             player_norm
0                Alex Král               alex kral
1       Alexander Schwolow      alexander schwolow
2             Andreas Ivan            andreas ivan
3           Cédric Brunner          cedric brunner
4              Danny Latza             danny latza
5         Dominick Drexler        dominick drexler
6             Éder Balanta            eder balanta
7           Florent Mollet          florent mollet
8            Florian Flick           florian flick
9       Henning Matriciani      henning matriciani
10          Ibrahima Cissé          ibrahima cisse
11             Jere Uronen             jere uronen
12          Jordan Larsson          jordan larsson
13         Justin Heekeren         justin heekeren
14           Kenan Karaman           kenan karaman
15        Kerim Calhanoglu        kerim calhanoglu
16              Leo Greiml              leo greiml
17         Marcin Kaminski         marcin kaminski
18           Marius Bülter           marius bulter
19            Maya Yoshida            maya yoshida
20            Mehmet Aydin            mehmet aydin
21            Michael Frey            michael frey
22          Michael Langer          michael langer
23             Moritz Jenz             moritz jenz
24        Nassim Boujellab        nassim boujellab
25            Niklas Tauer            niklas tauer
26           Ralf Fährmann           ralf fahrmann
27         Rodrigo Zalazar         rodrigo zalazar
28        Sebastian Polter        sebastian polter
29       Sepp van den Berg       sepp van den berg
30           Simon Terodde           simon terodde
31         Soichiro Kozuki         soichiro kozuki
32          Thomas Ouwejan          thomas ouwejan
33              Tim Skarke              tim skarke
34  Timothée Kolodziejczak  timothee kolodziejczak
35             Tobias Mohr             tobias mohr
36               Tom Krauß                tom krau

============================================================
  Hertha BSC  —  SF sin salario:

           player  minutesPlayed
0    Ibrahim Maza             70
1  Pascal Klemens             90
2      Tony Rölke             19
3     Veit Stange             11

  CG plantilla completa:

                    player             player_norm
0            Agustín Rogel           agustin rogel
1            Chidera Ejuke           chidera ejuke
2              Davie Selke             davie selke
3          Derry Scherhant         derry scherhant
4       Deyovaisio Zeefuik      deyovaisio zeefuik
5           Dodi Lukébakio          dodi lukebakio
6             Dong-jun Lee            dong jun lee
7           Filip Uremovic          filip uremovic
8    Florian Niederlechner   florian niederlechner
9              Ivan Sunjic             ivan sunjic
10       Jean-Paul Boëtius       jean paul boetius
11          Jessic Ngankam          jessic ngankam
12            Jonjoe Kenny            jonjoe kenny
13     Julian Eitschberger     julian eitschberger
14            Kelian Nsona            kelian nsona
15    Kevin-Prince Boateng    kevin prince boateng
16           Linus Gechter           linus gechter
17           Lucas Tousart           lucas tousart
18           Lukas Ullrich           lukas ullrich
19       Marc Oliver Kempf       marc oliver kempf
20           Marco Richter           marco richter
21           Márton Dárdai           marton dardai
22     Marvin Plattenhardt     marvin plattenhardt
23  Maximilian Mittelstädt  maximilian mittelstadt
24         Myziane Maolida         myziane maolida
25      Oliver Christensen      oliver christensen
26           Peter Pekarik           peter pekarik
27           Rune Jarstein           rune jarstein
28          Stevan Jovetic          stevan jovetic
29             Suat Serdar             suat serdar
30             Tjark Ernst             tjark ernst
31           Tolga Cigerci           tolga cigerci
32         Vladimir Darida         vladimir darida
33          Wilfried Kanga          wilfried kanga

============================================================
  RB Leipzig  —  SF sin salario:

              player  minutesPlayed
0  Alexander Sørloth             13

  CG plantilla completa:

                player         player_norm
0         Abdou Diallo        abdou diallo
1       Amadou Haidara      amadou haidara
2          André Silva         andre silva
3    Benjamin Henrichs   benjamin henrichs
4          Caden Clark         caden clark
5   Christopher Nkunku  christopher nkunku
6            Dani Olmo           dani olmo
7           David Raum          david raum
8   Dominik Szoboszlai  dominik szoboszlai
9        Emil Forsberg       emil forsberg
10          Hugo Novoa          hugo novoa
11      Janis Blaswich      janis blaswich
12      Jonas Nickisch      jonas nickisch
13      Josko Gvardiol      josko gvardiol
14         Kevin Kampl         kevin kampl
15       Konrad Laimer       konrad laimer
16   Lukas Klostermann   lukas klostermann
17  Marcel Halstenberg  marcel halstenberg
18     Mohamed Simakan     mohamed simakan
19        Örjan Nyland        orjan nyland
20         Oskar Preil         oskar preil
21       Péter Gulácsi       peter gulacsi
22         Sanoussy Ba         sanoussy ba
23       Timo Schlieck       timo schlieck
24         Timo Werner         timo werner
25         Willi Orbán         willi orban
26      Xaver Schlager      xaver schlager
27      Yussuf Poulsen      yussuf poulsen

============================================================
  TSG Hoffenheim  —  SF sin salario:

              player  minutesPlayed
0  Diadié Samassékou             34
1    Joshua Quarshie              1
2       Stefan Posch             19

  CG plantilla completa:

                   player            player_norm
0         Andrej Kramaric        andrej kramaric
1                Angeliño               angelino
2          Angelo Stiller         angelo stiller
3         Benjamin Hübner        benjamin hubner
4   Christoph Baumgartner  christoph baumgartner
5           Dennis Geiger          dennis geiger
6        Eduardo Quaresma       eduardo quaresma
7          Ermin Bicakcic         ermin bicakcic
8         Finn Ole Becker        finn ole becker
9          Fisnik Asllani         fisnik asllani
10       Georginio Rutter       georginio rutter
11         Grischa Prömel         grischa promel
12            Ihlas Bebou            ihlas bebou
13     Jacob Bruun Larsen     jacob bruun larsen
14    John Anthony Brooks    john anthony brooks
15             Justin Che             justin che
16         Kasper Dolberg         kasper dolberg
17         Kevin Akpoguma         kevin akpoguma
18             Kevin Vogt             kevin vogt
19           Luca Philipp           luca philipp
20         Muhammed Damar         muhammed damar
21           Munas Dabbur           munas dabbur
22            Nahuel Noll            nahuel noll
23         Oliver Baumann         oliver baumann
24             Ozan Kabak             ozan kabak
25        Pavel Kaderabek        pavel kaderabek
26         Philipp Pentke         philipp pentke
27            Robert Skov            robert skov
28         Sebastian Rudy         sebastian rudy
29          Stanley Nsoki          stanley nsoki
30         Thomas Delaney         thomas delaney
31            Tom Bischof            tom bischof
32           Umut Tohumcu           umut tohumcu

============================================================
  VfB Stuttgart  —  SF sin salario:

            player  minutesPlayed
0     Clinton Mola             14
1  Darko Churlinov             26
2   Saša Kalajdžić            235
3            Silas           2010

  CG plantilla completa:

                     player              player_norm
0                 Alou Kuol                alou kuol
1           Antonis Aidonis          antonis aidonis
2            Atakan Karazor           atakan karazor
3                Borna Sosa               borna sosa
4             Chris Führich            chris fuhrich
5          Dan-Axel Zagadou         dan axel zagadou
6               Enzo Millot              enzo millot
7            Fabian Bredlow           fabian bredlow
8            Florian Müller           florian muller
9            Florian Schock           florian schock
10          Genki Haraguchi          genki haraguchi
11                 Gil Dias                 gil dias
12               Hiroki Ito               hiroki ito
13           Josha Vagnoman           josha vagnoman
14          Juan José Perea          juan jose perea
15  Konstantinos Mavropanos  konstantinos mavropanos
16            Laurin Ulrich            laurin ulrich
17            Lilian Egloff            lilian egloff
18            Luca Pfeiffer            luca pfeiffer
19         Naouirou Ahamada         naouirou ahamada
20           Nikolas Nartey           nikolas nartey
21               Ömer Beyaz               omer beyaz
22           Pascal Stenzel           pascal stenzel
23          Serhou Guirassy          serhou guirassy
24     Silas Katompa Mvumpa     silas katompa mvumpa
25         Tanguy Coulibaly         tanguy coulibaly
26        Thomas Kastanaras        thomas kastanaras
27              Tiago Tomás              tiago tomas
28           Waldemar Anton           waldemar anton
29              Wataru Endo              wataru endo

============================================================
  VfL Wolfsburg  —  SF sin salario:

          player  minutesPlayed
0  Aster Vranckx             13
1   Lukáš Ambros             16

  CG plantilla completa:

                player         player_norm
0       Bartol Franjic      bartol franjic
1    Dzenan Pejcinovic   dzenan pejcinovic
2         Felix Nmecha        felix nmecha
3       Jakub Kaminski      jakub kaminski
4    Jérôme Roussillon   jerome roussillon
5           Jonas Wind          jonas wind
6        Josip Brekalo       josip brekalo
7    Josuha Guilavogui   josuha guilavogui
8        Kevin Paredes       kevin paredes
9       Kilian Fischer      kilian fischer
10       Koen Casteels       koen casteels
11    Luca Waldschmidt    luca waldschmidt
12        Lukas Nmecha        lukas nmecha
13    Mattias Svanberg    mattias svanberg
14           Max Kruse           max kruse
15     Maxence Lacroix     maxence lacroix
16   Maximilian Arnold   maximilian arnold
17  Maximilian Philipp  maximilian philipp
18    Micky van de Ven    micky van de ven
19       Nicolas Cozza       nicolas cozza
20      Niklas Klinger      niklas klinger
21       Omar Marmoush       omar marmoush
22      Patrick Wimmer      patrick wimmer
23        Paulo Otávio        paulo otavio
24        Pavao Pervan        pavao pervan
25     Philipp Schulze     philipp schulze
26          Ridle Baku          ridle baku
27  Sebastiaan Bornauw  sebastiaan bornauw
28    Yannick Gerhardt    yannick gerhardt

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('silas', 'vfb stuttgart'): ('silas katompa mvumpa', 'vfb stuttgart'),
    ('iago borduchi','fc augsburg'):('iago',('fc augsburg'))
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 2

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: silas (vfb stuttgart) → silas katompa mvumpa (vfb stuttgart)
✅ Match manual aplicado: iago borduchi (fc augsburg) → iago (fc augsburg)

Tras matches manuales: 481/506 (95.1%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_germany_2223.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_germany_2223.csv
   Jugadores totales:  506
   Con salario:        481
   Sin salario (NaN):  25
   Columnas:           121