# 03 · Join Sofascore + Capology — Germany Bundesliga 21/22

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2021/22 de Bundesliga alemana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_germany_2122.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_germany_2122.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  511 jugadores | 116 columnas
Capology:   569 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   1 fc koln
   1 fc union berlin
   1 fsv mainz 05
   bayer 04 leverkusen
   borussia m gladbach
   fc augsburg
   fc bayern munchen
   hertha bsc
   rb leipzig
   sc freiburg
   spvgg greuther furth
   tsg hoffenheim
   vfb stuttgart
   vfl bochum 1848
   vfl wolfsburg

En Capology pero no en Sofascore:
   augsburg
   bayer leverkusen
   bayern munich
   bochum
   freiburg
   furth
   hertha berlin
   hoffenheim
   koln
   leipzig
   mainz
   monchengladbach
   stuttgart
   union berlin
   wolfsburg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [7]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'augsburg':'fc augsburg',
            'bayer leverkusen':'bayer 04 leverkusen',
            'bayern munich':'fc bayern munchen',
            'bochum':'vfl bochum 1848',
            'freiburg':'sc freiburg',
            'furth':'spvgg greuther furth',
            'hertha berlin':'hertha bsc',
            'hoffenheim':'tsg hoffenheim',
            'koln':'1 fc koln',
            'leipzig':'rb leipzig',
            'mainz':'1 fsv mainz 05',
            'monchengladbach':'borussia m gladbach',
            'stuttgart':'vfb stuttgart',
            'union berlin':'1 fc union berlin',
            'wolfsburg':'vfl wolfsburg'                          
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [8]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 460/511 (90.0%)
Sin emparejar: 51

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [9]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          9
Revisión media    (0.75 ≤ score < 0.90):   11
Revisión estricta (0.50 ≤ score < 0.75):   17
Revisión muy est. (score < 0.50):           14

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [10]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf                 team               cg_match  score
16  Vasilis Lampropoulos      VfL Bochum 1848  vasilios lampropoulos  0.976
13    Alfreð Finnbogason          FC Augsburg     alfred finnbogason  0.971
9       Jesper Lindstrøm  Eintracht Frankfurt       jesper lindstrom  0.968
11       Rafał Gikiewicz          FC Augsburg        rafal gikiewicz  0.966
12       Frederik Rønnow   1. FC Union Berlin        frederik ronnow  0.966
34        Bartosz Białek        VfL Wolfsburg         bartosz bialek  0.963
31        Levin Öztunalı   1. FC Union Berlin         levin oztunali  0.963
0            Evan Ndicka  Eintracht Frankfurt           evan n dicka  0.957
7       Niko Giesselmann   1. FC Union Berlin         niko gieelmann  0.933

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [11]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
26,Noah Joel Sarenren Bazee,FC Augsburg,noah sarenren bazee,0.884
23,Joseph Scally,Borussia M'gladbach,joe scally,0.870
48,Lars Sidney Raebiger,RB Leipzig,sidney raebiger,0.857
22,Anderson-Lenda Lucoqui,1. FSV Mainz 05,anderson lucoqui,0.842
25,Hans Nunoo Sarpei,SpVgg Greuther Fürth,nunoo sarpei,0.828
21,Gian-Luca Itter,SpVgg Greuther Fürth,luca itter,0.800
10,Leandro Barreiro,1. FSV Mainz 05,leandro barreiro martins,0.800
38,Fredrik André Bjørkan,Hertha BSC,fredrik bjorkan,0.800
30,Matondo-Merveille Papela,1. FSV Mainz 05,merveille papela,0.800
1,Stefan Ortega,Arminia Bielefeld,stefan ortega moreno,0.788
33,Ömer Faruk Beyaz,VfB Stuttgart,omer beyaz,0.769

In [12]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 11 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [13]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf                 team             cg_match  score
3           John Brooks        VfL Wolfsburg  john anthony brooks  0.733
42       Thomas Delaney    Borussia Dortmund       thomas meunier  0.714
20          Jeff Chabot           1. FC Köln        julian chabot  0.667
46      Immanuel Pherai    Borussia Dortmund        manuel akanji  0.643
47      Vincent Vermeij          SC Freiburg       vincenzo grifo  0.621
19    Luca Wollschläger           Hertha BSC        lucas tousart  0.600
40          Cimo Röcker           Hertha BSC        marco richter  0.583
8          Rafael Borré  Eintracht Frankfurt         santos borre  0.583
35        Matej Maglica        VfB Stuttgart      mateo klimowicz  0.571
4             Manu Koné  Borussia M'gladbach         kouadio kone  0.571
36  Julian Eitschberger           Hertha BSC        linus gechter  0.562
2         Iago Borduchi          FC Augsburg        niklas dorsch  0.538
43     Stephan Fürstner      1. FSV Mainz 05          stefan bell  0.519
27       Marten Winkler           Hertha BSC        marco richter  0.519
44      Nick Proschwitz       TSG Hoffenheim         stefan posch  0.519
50        Romario Rösch      1. FSV Mainz 05          anton stach  0.500
17        Jamie Gittens    Borussia Dortmund          axel witsel  0.500

In [15]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['john brooks',
                    'jeff chabot',
                    'rafael borre',
                    'manu kone'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 4

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [16]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf               team              cg_match  score
29           Marcel Lotka         Hertha BSC     marc oliver kempf  0.483
49             Lion Semić  Borussia Dortmund           nico schulz  0.476
14     Mike van der Hoorn  Arminia Bielefeld  stefan ortega moreno  0.474
5               Tom Rothe  Borussia Dortmund         tobias raschl  0.455
41       Javairô Dilrosun         Hertha BSC       vladimir darida  0.452
6           Josip Brekalo      VfL Wolfsburg        dodi lukebakio  0.444
18          Matheus Cunha         Hertha BSC   marvin plattenhardt  0.438
15        Lennard Maloney  Borussia Dortmund              emre can  0.435
37  Antonios Papadopoulos  Borussia Dortmund      dan axel zagadou  0.432
39                  Silas      VfB Stuttgart        nikolas nartey  0.421
28        Gabriel Vidović  FC Bayern München             marc roca  0.417
24         Hee-Chan Hwang         RB Leipzig       mohamed simakan  0.414
32    Baptiste Santamaria        SC Freiburg      christian gunter  0.400
45           Umut Tohumcu     TSG Hoffenheim       mijat gacinovic  0.370

In [17]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [18]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 484/511 (94.7%)
Sin salario:     27

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [19]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 27

,player,team,minutesPlayed,appearances,goals,assists
0,Stephan Fürstner,1. FSV Mainz 05,11,1,0,0
1,Romario Rösch,1. FSV Mainz 05,1,1,0,0
2,Mike van der Hoorn,Arminia Bielefeld,13,1,0,0
3,Jamie Gittens,Borussia Dortmund,133,4,0,0
4,Tom Rothe,Borussia Dortmund,99,2,1,0
5,Antonios Papadopoulos,Borussia Dortmund,20,2,0,0
6,Thomas Delaney,Borussia Dortmund,17,1,0,0
7,Lennard Maloney,Borussia Dortmund,12,2,0,0
8,Lion Semić,Borussia Dortmund,2,1,0,0
9,Immanuel Pherai,Borussia Dortmund,1,1,0,0
10,Iago Borduchi,FC Augsburg,2178,28,2,5
11,Gabriel Vidović,FC Bayern München,33,3,0,0
12,Marcel Lotka,Hertha BSC,884,10,0,0
13,Javairô Dilrosun,Hertha BSC,137,2,0,0
14,Matheus Cunha,Hertha BSC,65,1,0,1
15,Julian Eitschberger,Hertha BSC,45,1,0,0
16,Marten Winkler,Hertha BSC,25,1,0,0
17,Cimo Röcker,Hertha BSC,21,1,0,0
18,Luca Wollschläger,Hertha BSC,14,2,0,0
19,Hee-Chan Hwang,RB Leipzig,47,2,0,0
20,Baptiste Santamaria,SC Freiburg,20,1,0,0
21,Vincent Vermeij,SC Freiburg,2,1,0,0
22,Nick Proschwitz,TSG Hoffenheim,26,1,0,0
23,Umut Tohumcu,TSG Hoffenheim,4,1,0,0
24,Silas,VfB Stuttgart,276,9,0,0
25,Matej Maglica,VfB Stuttgart,11,1,0,0
26,Josip Brekalo,VfL Wolfsburg,20,1,0,1

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [20]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  1. FSV Mainz 05  —  SF sin salario:

             player  minutesPlayed
0     Romario Rösch              1
1  Stephan Fürstner             11

  CG plantilla completa:

                      player               player_norm
0               Aarón Martín              aaron martin
1                Ádám Szalai               adam szalai
2             Alexander Hack            alexander hack
3           Anderson Lucoqui          anderson lucoqui
4                Anton Stach               anton stach
5           Daniel Brosinski          daniel brosinski
6               David Nemeth              david nemeth
7            Delano Burgzorg           delano burgzorg
8               Dominik Kohr              dominik kohr
9                Finn Dahmen               finn dahmen
10              Jae-sung Lee              jae sung lee
11         Jean-Paul Boëtius         jean paul boetius
12        Jeremiah St. Juste         jeremiah st juste
13         Jonathan Burkardt         jonathan burkardt
14             Karim Onisiwo             karim onisiwo
15              Kevin Stöger              kevin stoger
16                Lasse Rieß                 lasse rie
17  Leandro Barreiro Martins  leandro barreiro martins
18         Marcus Ingvartsen         marcus ingvartsen
19          Marius Liesegang          marius liesegang
20          Merveille Papela          merveille papela
21           Moussa Niakhaté           moussa niakhate
22              Niklas Tauer              niklas tauer
23                Omer Hanin                omer hanin
24                Paul Nebel                paul nebel
25             Robin Zentner             robin zentner
26             Silvan Widmer             silvan widmer
27               Stefan Bell               stefan bell

============================================================
  Arminia Bielefeld  —  SF sin salario:

               player  minutesPlayed
0  Mike van der Hoorn             13

  CG plantilla completa:

                   player            player_norm
0       Alessandro Schöpf      alessandro schopf
1             Amos Pieper            amos pieper
2          Andrés Andrade         andres andrade
3             Arne Schulz            arne schulz
4             Bryan Lasme            bryan lasme
5              Burak Ince             burak ince
6          Cédric Brunner         cedric brunner
7     Edimilson Fernandes    edimilson fernandes
8             Fabian Klos            fabian klos
9            Fabian Kunze           fabian kunze
10         Florian Krüger         florian kruger
11           George Bello           george bello
12         Gonzalo Castro         gonzalo castro
13        Guilherme Ramos        guilherme ramos
14  Jacob Barrett Laursen  jacob barrett laursen
15            Janni Serra            janni serra
16         Joakim Nilsson         joakim nilsson
17       Lennart Czyborra       lennart czyborra
18          Manuel Prietl          manuel prietl
19         Masaya Okugawa         masaya okugawa
20       Nathan de Medina       nathan de medina
21         Patrick Wimmer         patrick wimmer
22             Robin Hack             robin hack
23   Sebastian Vasiliadis   sebastian vasiliadis
24   Stefan Ortega Moreno   stefan ortega moreno
25        Stefanos Kapino        stefanos kapino
26       Vladislav Cherny       vladislav cherny

============================================================
  Borussia Dortmund  —  SF sin salario:

                  player  minutesPlayed
0  Antonios Papadopoulos             20
1        Immanuel Pherai              1
2          Jamie Gittens            133
3        Lennard Maloney             12
4             Lion Semić              2
5         Thomas Delaney             17
6              Tom Rothe             99

  CG plantilla completa:

                player         player_norm
0     Abdoulaye Kamara    abdoulaye kamara
1        Ansgar Knauff       ansgar knauff
2          Axel Witsel         axel witsel
3     Dan-Axel Zagadou    dan axel zagadou
4        Donyell Malen       donyell malen
5             Emre Can            emre can
6       Erling Haaland      erling haaland
7       Felix Passlack      felix passlack
8       Giovanni Reyna      giovanni reyna
9         Gregor Kobel        gregor kobel
10     Jude Bellingham     jude bellingham
11       Julian Brandt       julian brandt
12       Luca Unbehaun       luca unbehaun
13      Mahmoud Dahoud      mahmoud dahoud
14       Manuel Akanji       manuel akanji
15    Marcel Schmelzer    marcel schmelzer
16          Marco Reus          marco reus
17     Marin Pongracic     marin pongracic
18         Marius Wolf         marius wolf
19         Marwin Hitz         marwin hitz
20   Mateu Morey Bauzà   mateu morey bauza
21        Mats Hummels        mats hummels
22         Nico Schulz         nico schulz
23   Raphaël Guerreiro   raphael guerreiro
24             Reinier             reinier
25         Roman Bürki         roman burki
26  Soumaïla Coulibaly  soumaila coulibaly
27      Stefan Drljaca      stefan drljaca
28      Steffen Tigges      steffen tigges
29      Thomas Meunier      thomas meunier
30      Thorgan Hazard      thorgan hazard
31       Tobias Raschl       tobias raschl
32   Youssoufa Moukoko   youssoufa moukoko

============================================================
  FC Augsburg  —  SF sin salario:

          player  minutesPlayed
0  Iago Borduchi           2178

  CG plantilla completa:

                   player            player_norm
0      Alfred Finnbogason     alfred finnbogason
1             Andi Zeqiri            andi zeqiri
2              André Hahn             andre hahn
3              Arne Maier             arne maier
4           Carlos Gruezo          carlos gruezo
5        Daniel Caligiuri       daniel caligiuri
6            Daniel Klein           daniel klein
7          Felix Uduokhai         felix uduokhai
8   Florian Niederlechner  florian niederlechner
9        Frederik Winther       frederik winther
10         Fredrik Jensen         fredrik jensen
11                   Iago                   iago
12            Jan Moravek            jan moravek
13     Jeffrey Gouweleeuw     jeffrey gouweleeuw
14          Lasse Günther          lasse gunther
15          Mads Pedersen          mads pedersen
16    Michael Gregoritsch    michael gregoritsch
17          Niklas Dorsch          niklas dorsch
18    Noah Sarenren Bazee    noah sarenren bazee
19        Rafal Gikiewicz        rafal gikiewicz
20     Raphael Framberger     raphael framberger
21           Reece Oxford           reece oxford
22           Ricardo Pepi           ricardo pepi
23           Robert Gumny           robert gumny
24           Rubén Vargas           ruben vargas
25         Sergio Córdova         sergio cordova
26             Tim Civeja             tim civeja
27          Tobias Strobl          tobias strobl
28           Tomas Koubek           tomas koubek

============================================================
  FC Bayern München  —  SF sin salario:

            player  minutesPlayed
0  Gabriel Vidović             33

  CG plantilla completa:

                      player               player_norm
0            Alphonso Davies           alphonso davies
1            Benjamin Pavard           benjamin pavard
2                 Bouna Sarr                bouna sarr
3          Christian Früchtl         christian fruchtl
4           Corentin Tolisso          corentin tolisso
5            Dayot Upamecano           dayot upamecano
6   Eric Maxim Choupo-Moting  eric maxim choupo moting
7              Jamal Musiala             jamal musiala
8             Joshua Kimmich            joshua kimmich
9             Josip Stanisic            josip stanisic
10            Kingsley Coman            kingsley coman
11             Leon Goretzka             leon goretzka
12                Leroy Sané                leroy sane
13              Lucas Copado              lucas copado
14           Lucas Hernández           lucas hernandez
15             Malik Tillman             malik tillman
16              Manuel Neuer              manuel neuer
17                 Marc Roca                 marc roca
18           Marcel Sabitzer           marcel sabitzer
19          Michaël Cuisance          michael cuisance
20               Niklas Süle               niklas sule
21             Omar Richards             omar richards
22               Paul Wanner               paul wanner
23        Robert Lewandowski        robert lewandowski
24              Serge Gnabry              serge gnabry
25              Sven Ulreich              sven ulreich
26            Tanguy Nianzou            tanguy nianzou
27             Thomas Müller             thomas muller

============================================================
  Hertha BSC  —  SF sin salario:

                player  minutesPlayed
0          Cimo Röcker             21
1     Javairô Dilrosun            137
2  Julian Eitschberger             45
3    Luca Wollschläger             14
4         Marcel Lotka            884
5       Marten Winkler             25
6        Matheus Cunha             65

  CG plantilla completa:

                    player             player_norm
0       Alexander Schwolow      alexander schwolow
1               Anton Kade              anton kade
2              Davie Selke             davie selke
3           Dedryck Boyata          dedryck boyata
4      Dennis Jastrzembski     dennis jastrzembski
5       Deyovaisio Zeefuik      deyovaisio zeefuik
6             Dong-jun Lee            dong jun lee
7          Fredrik Björkan         fredrik bjorkan
8           Ishak Belfodil          ishak belfodil
9        Jonas Michelbrink       jonas michelbrink
10      Jordan Torunarigha      jordan torunarigha
11      Jurgen Ekkelenkamp      jurgen ekkelenkamp
12            Kelian Nsona            kelian nsona
13    Kevin-Prince Boateng    kevin prince boateng
14        Krzysztof Piatek        krzysztof piatek
15           Linus Gechter           linus gechter
16           Lucas Tousart           lucas tousart
17           Lukas Klünter           lukas klunter
18       Marc Oliver Kempf       marc oliver kempf
19           Marco Richter           marco richter
20           Márton Dárdai           marton dardai
21     Marvin Plattenhardt     marvin plattenhardt
22  Maximilian Mittelstädt  maximilian mittelstadt
23         Myziane Maolida         myziane maolida
24            Niklas Stark            niklas stark
25             Nils Körber             nils korber
26      Oliver Christensen      oliver christensen
27           Peter Pekarik           peter pekarik
28           Rune Jarstein           rune jarstein
29       Ruwen Werthmüller       ruwen werthmuller
30      Santiago Ascacíbar      santiago ascacibar
31          Stevan Jovetic          stevan jovetic
32             Suat Serdar             suat serdar
33         Vladimir Darida         vladimir darida

============================================================
  RB Leipzig  —  SF sin salario:

           player  minutesPlayed
0  Hee-Chan Hwang             47

  CG plantilla completa:

                player         player_norm
0       Amadou Haidara      amadou haidara
1          André Silva         andre silva
2             Angeliño            angelino
3         Ben Klefisch        ben klefisch
4    Benjamin Henrichs   benjamin henrichs
5        Brian Brobbey       brian brobbey
6          Caden Clark         caden clark
7   Christopher Nkunku  christopher nkunku
8            Dani Olmo           dani olmo
9   Dominik Szoboszlai  dominik szoboszlai
10       Emil Forsberg       emil forsberg
11     Fabian Eutinger     fabian eutinger
12          Hugo Novoa          hugo novoa
13        Ilaix Moriba        ilaix moriba
14         Joscha Wosz         joscha wosz
15      Josep Martínez      josep martinez
16      Josko Gvardiol      josko gvardiol
17         Kevin Kampl         kevin kampl
18       Konrad Laimer       konrad laimer
19   Lukas Klostermann   lukas klostermann
20  Marcel Halstenberg  marcel halstenberg
21    Marcelo Saracchi    marcelo saracchi
22     Mohamed Simakan     mohamed simakan
23       Nordi Mukiele       nordi mukiele
24       Péter Gulácsi       peter gulacsi
25   Philipp Tschauner   philipp tschauner
26     Sidney Raebiger     sidney raebiger
27      Solomon Bonnah      solomon bonnah
28         Tyler Adams         tyler adams
29         Willi Orbán         willi orban
30      Yussuf Poulsen      yussuf poulsen

============================================================
  SC Freiburg  —  SF sin salario:

                player  minutesPlayed
0  Baptiste Santamaria             20
1      Vincent Vermeij              2

  CG plantilla completa:

                  player           player_norm
0        Benjamin Uphoff       benjamin uphoff
1       Christian Günter      christian gunter
2       Dominique Heintz      dominique heintz
3      Ermedin Demirovic     ermedin demirovic
4            Hugo Siquet           hugo siquet
5          Janik Haberer         janik haberer
6        Jonathan Schmid       jonathan schmid
7    Keven Schlotterbeck   keven schlotterbeck
8           Kevin Schade          kevin schade
9      Kiliann Sildillia     kiliann sildillia
10      Kimberly Ezekwem      kimberly ezekwem
11           Lucas Höler           lucas holer
12          Lukas Kübler          lukas kubler
13          Manuel Gulde          manuel gulde
14          Mark Flekken          mark flekken
15  Maximilian Eggestein  maximilian eggestein
16    Nico Schlotterbeck    nico schlotterbeck
17        Nicolas Höfler        nicolas hofler
18         Nils Petersen         nils petersen
19        Nishan Burkart        nishan burkart
20          Noah Atubolu          noah atubolu
21        Noah Weißhaupt         noah weihaupt
22      Philipp Lienhart      philipp lienhart
23         Roland Sallai         roland sallai
24        Vincenzo Grifo        vincenzo grifo
25       Woo-yeong Jeong       woo yeong jeong
26         Yannik Keitel         yannik keitel

============================================================
  TSG Hoffenheim  —  SF sin salario:

            player  minutesPlayed
0  Nick Proschwitz             26
1     Umut Tohumcu              4

  CG plantilla completa:

                   player            player_norm
0         Andrej Kramaric        andrej kramaric
1          Angelo Stiller         angelo stiller
2         Benjamin Hübner        benjamin hubner
3          Chris Richards         chris richards
4   Christoph Baumgartner  christoph baumgartner
5              David Raum             david raum
6           Dennis Geiger          dennis geiger
7       Diadié Samassékou      diadie samassekou
8          Ermin Bicakcic         ermin bicakcic
9          Fisnik Asllani         fisnik asllani
10     Florian Grillitsch     florian grillitsch
11       Georginio Rutter       georginio rutter
12       Havard Nordtveit       havard nordtveit
13            Ihlas Bebou            ihlas bebou
14     Jacob Bruun Larsen     jacob bruun larsen
15          Joshua Brenet          joshua brenet
16             Justin Che             justin che
17            Kasim Adams            kasim adams
18         Kevin Akpoguma         kevin akpoguma
19             Kevin Vogt             kevin vogt
20           Luca Philipp           luca philipp
21             Marco John             marco john
22        Melayro Bogarde        melayro bogarde
23        Mijat Gacinovic        mijat gacinovic
24           Munas Dabbur           munas dabbur
25            Nahuel Noll            nahuel noll
26         Oliver Baumann         oliver baumann
27        Pavel Kaderabek        pavel kaderabek
28         Philipp Pentke         philipp pentke
29            Robert Skov            robert skov
30         Sargis Adamyan         sargis adamyan
31         Sebastian Rudy         sebastian rudy
32           Stefan Posch           stefan posch
33            Tom Bischof            tom bischof

============================================================
  VfB Stuttgart  —  SF sin salario:

          player  minutesPlayed
0  Matej Maglica             11
1          Silas            276

  CG plantilla completa:

                     player              player_norm
0             Alexis Tibidi            alexis tibidi
1            Atakan Karazor           atakan karazor
2                Borna Sosa               borna sosa
3             Chris Führich            chris fuhrich
4              Clinton Mola             clinton mola
5             Daniel Didavi            daniel didavi
6               Enzo Millot              enzo millot
7               Erik Thommy              erik thommy
8            Fabian Bredlow           fabian bredlow
9            Florian Müller           florian muller
10           Florian Schock           florian schock
11      Hamadi Al Ghaddioui      hamadi al ghaddioui
12               Hiroki Ito               hiroki ito
13  Konstantinos Mavropanos  konstantinos mavropanos
14            Lilian Egloff            lilian egloff
15        Marc Oliver Kempf        marc oliver kempf
16          Mateo Klimowicz          mateo klimowicz
17           Mohamed Sankoh           mohamed sankoh
18               Momo Cissé               momo cisse
19         Naouirou Ahamada         naouirou ahamada
20           Nikolas Nartey           nikolas nartey
21            Omar Marmoush            omar marmoush
22               Ömer Beyaz               omer beyaz
23             Orel Mangala             orel mangala
24           Pascal Stenzel           pascal stenzel
25          Philipp Förster          philipp forster
26          Philipp Klement          philipp klement
27          Roberto Massimo          roberto massimo
28           Sasa Kalajdzic           sasa kalajdzic
29     Silas Katompa Mvumpa     silas katompa mvumpa
30         Tanguy Coulibaly         tanguy coulibaly
31              Tiago Tomás              tiago tomas
32             Wahid Faghir             wahid faghir
33           Waldemar Anton           waldemar anton
34              Wataru Endo              wataru endo

============================================================
  VfL Wolfsburg  —  SF sin salario:

          player  minutesPlayed
0  Josip Brekalo             20

  CG plantilla completa:

                     player              player_norm
0             Admir Mehmedi            admir mehmedi
1   Anselmo García MacNulty  anselmo garcia macnulty
2             Aster Vranckx            aster vranckx
3            Bartosz Bialek           bartosz bialek
4            Daniel Ginczek           daniel ginczek
5            Dodi Lukébakio           dodi lukebakio
6              Felix Nmecha             felix nmecha
7               Jannis Lang              jannis lang
8         Jérôme Roussillon        jerome roussillon
9       John Anthony Brooks      john anthony brooks
10               Jonas Wind               jonas wind
11        Josuha Guilavogui        josuha guilavogui
12              Kevin Mbabu              kevin mbabu
13            Kevin Paredes            kevin paredes
14            Koen Casteels            koen casteels
15         Luca Waldschmidt         luca waldschmidt
16             Lukas Nmecha             lukas nmecha
17         Marvin Stefaniak         marvin stefaniak
18                Max Kruse                max kruse
19          Maxence Lacroix          maxence lacroix
20        Maximilian Arnold        maximilian arnold
21       Maximilian Philipp       maximilian philipp
22         Micky van de Ven         micky van de ven
23           Niklas Klinger           niklas klinger
24             Paulo Otávio             paulo otavio
25             Pavao Pervan             pavao pervan
26          Philipp Schulze          philipp schulze
27           Renato Steffen           renato steffen
28               Ridle Baku               ridle baku
29       Sebastiaan Bornauw       sebastiaan bornauw
30                  William                  william
31            Wout Weghorst            wout weghorst
32           Xaver Schlager           xaver schlager
33         Yannick Gerhardt         yannick gerhardt

In [21]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('silas', 'vfb stuttgart'): ('silas katompa mvumpa', 'vfb stuttgart'),
    ('iago borduchi','fc augsburg'):('iago',('fc augsburg'))
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 2

In [22]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: silas (vfb stuttgart) → silas katompa mvumpa (vfb stuttgart)
✅ Match manual aplicado: iago borduchi (fc augsburg) → iago (fc augsburg)

Tras matches manuales: 486/511 (95.1%)

In [23]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [24]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_germany_2122.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_germany_2122.csv
   Jugadores totales:  511
   Con salario:        486
   Sin salario (NaN):  25
   Columnas:           121