# 03 · Join Sofascore + Capology — Germany Bundesliga 25/26 (snapshot 20260428)

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2025/26 de la Bundesliga alemana**.

⚠️ **Nota sobre el snapshot:** la temporada 25/26 está aún en curso. Se trabaja con
una foto fija de Sofascore (`df_germany_2526_snapshot_20260428.csv`). Este notebook
deberá reejecutarse con los datos definitivos cuando finalice la liga, generando
entonces el master sin sufijo de fecha (`master_germany_2526.csv`).

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_germany_2526_snapshot_20260428.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_germany_2526.csv').copy()

print(f'Sofascore (snapshot):  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:              {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore (snapshot):  494 jugadores | 117 columnas
Capology:              556 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   1 fc heidenheim
   1 fc koln
   1 fc union berlin
   1 fsv mainz 05
   bayer 04 leverkusen
   borussia m gladbach
   fc augsburg
   fc bayern munchen
   fc st pauli
   hamburger sv
   rb leipzig
   sc freiburg
   sv werder bremen
   tsg hoffenheim
   vfb stuttgart
   vfl wolfsburg

En Capology pero no en Sofascore:
   augsburg
   bayer leverkusen
   bayern munich
   freiburg
   hamburg
   heidenheim
   hoffenheim
   koln
   leipzig
   mainz
   monchengladbach
   st pauli
   stuttgart
   union berlin
   werder bremen
   wolfsburg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'augsburg':'fc augsburg',
            'bayer leverkusen':'bayer 04 leverkusen',
            'bayern munich':'fc bayern munchen',
            'freiburg':'sc freiburg',
            'hamburg':'hamburger sv',
            'heidenheim':'1 fc heidenheim',
            'hoffenheim':'tsg hoffenheim',
            'koln':'1 fc koln',
            'leipzig':'rb leipzig',
            'mainz':'1 fsv mainz 05',
            'monchengladbach':'borussia m gladbach',
            'st pauli':'fc st pauli',
            'stuttgart':'vfb stuttgart',
            'union berlin':'1 fc union berlin',
            'werder bremen':'sv werder bremen',
            'wolfsburg':'vfl wolfsburg'
            

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 441/494 (89.3%)
Sin emparejar: 53

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          4
Revisión media    (0.75 ≤ score < 0.90):   8
Revisión estricta (0.50 ≤ score < 0.75):   21
Revisión muy est. (score < 0.50):           20

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf                 team           cg_match  score
12  Yannick Engelhardt  Borussia M'gladbach  yannik engelhardt  0.971
28      Albert Grønbæk         Hamburger SV     albert grnbaek  0.923
21        Joakim Mæhle        VfL Wolfsburg      joakim maehle  0.917
25         Lasse Riess      1. FSV Mainz 05          lasse rie  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                    player_sf              team                cg_match  score
9           Jan Uwe Thielmann        1. FC Köln           jan thielmann  0.867
20       Victor Okoh Boniface  SV Werder Bremen         victor boniface  0.857
4            Daniel Fernandes      Hamburger SV  daniel heuer fernandes  0.842
0                 Dan Zagadou     VfB Stuttgart        dan axel zagadou  0.815
45        Jonas Adjei Adjetey     VfL Wolfsburg           jonas adjetey  0.812
26     Maximilian Rosenfelder       SC Freiburg         max rosenfelder  0.811
10  Ísak Bergmann Jóhannesson        1. FC Köln        isak johannesson  0.780
37         Omar Haktab Traore  1. FC Heidenheim             omar traore  0.759

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 8 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf                 team          cg_match  score
5           Jeff Chabot        VfB Stuttgart     julian chabot  0.667
34  Tom Alexander Rothe   1. FC Union Berlin         tom rothe  0.643
3           Kim Min-jae    FC Bayern München       min jae kim  0.636
36        Aiman Dardari          FC Augsburg     fabian rieder  0.615
24         David Daiber    FC Bayern München     konrad laimer  0.560
46         Aurelio Buta  Eintracht Frankfurt     aurele amenda  0.560
23     Jonah Kusi-Asare    FC Bayern München     jamal musiala  0.552
35          Emir Sahiti         Hamburger SV       miro muheim  0.545
15           Arne Maier          FC Augsburg      felix meiser  0.545
41        Cenny Neumann           1. FC Köln     jan thielmann  0.538
51        Tobias Weigel     1. FC Heidenheim     thomas keller  0.538
39         Linus Guther   1. FC Union Berlin       livan burcu  0.522
47       Cassiano Kiala    FC Bayern München     jamal musiala  0.519
49        Mathis Albert    Borussia Dortmund   marcel sabitzer  0.500
31       Maycon Cardozo    FC Bayern München    bryan zaragoza  0.500
22        Jonas Meffert         Hamburger SV       omar megeed  0.500
42       Nick Woltemade        VfB Stuttgart    nikolas nartey  0.500
29     Rouven Tarnutzer          SC Freiburg  christian gunter  0.500
18         Vaclav Cerny        VfL Wolfsburg      pavao pervan  0.500
2       Aarón Anselmino    Borussia Dortmund     karim adeyemi  0.500
11            Luca Netz  Borussia M'gladbach       rocco reitz  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['jeff chabot',
                    'tom alexander rothe',
                    'kim min jae'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 3

### 7.4 Revisión muy estricta (score < 0.50)

Candidatos con muy baja similitud. Por defecto ninguno se acepta.
Añadir a `ACCEPT_VERY_LOW_FUZZY` los que se confirmen manualmente.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf                 team                cg_match  score
27     Guilherme Ramos         Hamburger SV  daniel heuer fernandes  0.486
6        Luca Reggiani    Borussia Dortmund        silas ostrzinski  0.483
33    Oladapo Afolayan         FC St. Pauli           adam dzwigala  0.483
13      Samuele Inacio    Borussia Dortmund         ramy bensebaini  0.483
40         Merlin Röhl          SC Freiburg      maximilian philipp  0.483
43         Xavi Simons           RB Leipzig      andrija maksimovic  0.483
48  Isak Hansen Aarøen     SV Werder Bremen            niklas stark  0.483
52         Kevin Kampl           RB Leipzig              david raum  0.476
7          Pascal Groß    Borussia Dortmund             salih ozcan  0.476
19               Silas      1. FSV Mainz 05            niklas tauer  0.471
1          Leo Scienza     1. FC Heidenheim         stefan schimmer  0.462
17         Loïs Openda           RB Leipzig         assan ouedraogo  0.462
14        Oscar Fraulo  Borussia M'gladbach          tomas cvancara  0.462
32         Timo Werner           RB Leipzig             viggo gebel  0.455
38          Deniz Ofli    FC Bayern München            sven ulreich  0.455
16      Piero Hincapié  Bayer 04 Leverkusen           patrik schick  0.444
50       Erblin Osmani    FC Bayern München          josip stanisic  0.444
30       Tim Schnitzer          FC Augsburg          cedric zesiger  0.444
8     Charles Herrmann  Borussia M'gladbach        grant leon ranos  0.438
44  Aboubaka Soumahoro         Hamburger SV            warmed omari  0.400

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 456/494 (92.3%)
Sin salario:     38

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 38

,player,team,minutesPlayed,appearances,goals,assists
0,Leo Scienza,1. FC Heidenheim,180,2,1,0
1,Tobias Weigel,1. FC Heidenheim,1,1,0,0
2,Cenny Neumann,1. FC Köln,83,2,0,0
3,Linus Guther,1. FC Union Berlin,14,1,0,0
4,Silas,1. FSV Mainz 05,342,8,1,0
5,Piero Hincapié,Bayer 04 Leverkusen,90,1,0,0
6,Pascal Groß,Borussia Dortmund,618,11,0,1
7,Aarón Anselmino,Borussia Dortmund,368,6,1,0
8,Luca Reggiani,Borussia Dortmund,245,5,1,0
9,Samuele Inacio,Borussia Dortmund,134,4,0,0
10,Mathis Albert,Borussia Dortmund,1,1,0,0
11,Luca Netz,Borussia M'gladbach,943,15,0,2
12,Oscar Fraulo,Borussia M'gladbach,55,4,1,0
13,Charles Herrmann,Borussia M'gladbach,10,1,0,1
14,Aurelio Buta,Eintracht Frankfurt,151,4,0,0
15,Aiman Dardari,FC Augsburg,35,3,0,0
16,Arne Maier,FC Augsburg,15,1,0,0
17,Tim Schnitzer,FC Augsburg,11,1,0,0
18,Maycon Cardozo,FC Bayern München,32,2,0,0
19,David Daiber,FC Bayern München,27,2,0,0
20,Jonah Kusi-Asare,FC Bayern München,10,1,0,0
21,Deniz Ofli,FC Bayern München,8,1,0,0
22,Erblin Osmani,FC Bayern München,3,1,0,0
23,Cassiano Kiala,FC Bayern München,1,1,0,0
24,Oladapo Afolayan,FC St. Pauli,155,7,0,0
25,Jonas Meffert,Hamburger SV,151,4,0,0
26,Aboubaka Soumahoro,Hamburger SV,141,4,0,0
27,Emir Sahiti,Hamburger SV,122,2,0,0
28,Guilherme Ramos,Hamburger SV,78,8,0,0
29,Xavi Simons,RB Leipzig,90,1,0,0
30,Loïs Openda,RB Leipzig,55,2,0,0
31,Timo Werner,RB Leipzig,13,3,0,0
32,Kevin Kampl,RB Leipzig,3,3,0,0
33,Merlin Röhl,SC Freiburg,65,2,0,0
34,Rouven Tarnutzer,SC Freiburg,11,1,0,0
35,Isak Hansen Aarøen,SV Werder Bremen,1,1,0,0
36,Nick Woltemade,VfB Stuttgart,90,1,0,0
37,Vaclav Cerny,VfL Wolfsburg,46,2,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  1. FC Heidenheim  —  SF sin salario:

          player  minutesPlayed
0    Leo Scienza            180
1  Tobias Weigel              1

  CG plantilla completa:

                player         player_norm
0           Adam Kölle          adam kolle
1          Adrian Beck         adrian beck
2   Arijon Ibrahimovic  arijon ibrahimovic
3      Benedikt Gimber     benedikt gimber
4      Budu Zivzivadze     budu zivzivadze
5     Christian Conteh    christian conteh
6          Diant Ramaj         diant ramaj
7          Eren Dinkçi         eren dinkci
8         Frank Feller        frank feller
9       Hennes Behrens      hennes behrens
10       Jan Schöppner       jan schoppner
11    Jonas Föhrenbach    jonas fohrenbach
12      Julian Niehues      julian niehues
13        Kevin Müller        kevin muller
14      Leart Paqarada      leart paqarada
15   Leonidas Stergiou   leonidas stergiou
16         Luca Kerber         luca kerber
17        Marnon Busch        marnon busch
18    Marvin Pieringer    marvin pieringer
19      Mathias Honsak      mathias honsak
20     Mikkel Kaufmann     mikkel kaufmann
21     Nick Rothweiler     nick rothweiler
22       Niklas Dorsch       niklas dorsch
23         Omar Traoré         omar traore
24      Patrick Mainka      patrick mainka
25     Paul Tschernuth     paul tschernuth
26      Sirlord Conteh      sirlord conteh
27     Stefan Schimmer     stefan schimmer
28       Thomas Keller       thomas keller
29      Tim Siersleben      tim siersleben
30       Yannik Wagner       yannik wagner

============================================================
  1. FC Köln  —  SF sin salario:

          player  minutesPlayed
0  Cenny Neumann             83

  CG plantilla completa:

                   player            player_norm
0   Alessio Castro-Montes  alessio castro montes
1            Cenk Özkacar           cenk ozkacar
2       Denis Huseinbasic      denis huseinbasic
3        Dominique Heintz       dominique heintz
4            Emin Kujovic           emin kujovic
5             Eric Martel            eric martel
6       Fayssal Harchaoui      fayssal harchaoui
7           Felipe Chávez          felipe chavez
8           Florian Kainz          florian kainz
9           Fynn Schenten          fynn schenten
10       Ísak Jóhannesson       isak johannesson
11   Jahmai Simpson-Pusey   jahmai simpson pusey
12         Jakub Kaminski         jakub kaminski
13          Jan Thielmann          jan thielmann
14           Joël Schmied           joel schmied
15      Jusuf Gazibegovic      jusuf gazibegovic
16        Kristoffer Lund        kristoffer lund
17           Linton Maina           linton maina
18            Luca Kilian            luca kilian
19       Luca Waldschmidt       luca waldschmidt
20          Malek El Mala          malek el mala
21          Marius Bülter          marius bulter
22         Marvin Schwäbe         marvin schwabe
23       Matthias Köbbing       matthias kobbing
24            Ragnar Ache            ragnar ache
25       Rav van den Berg       rav van den berg
26      Ron-Robert Zieler      ron robert zieler
27           Said El Mala           said el mala
28   Sebastian Sebulonsen   sebastian sebulonsen
29            Timo Hübers            timo hubers
30              Tom Krauß               tom krau
31       Youssoupha Niang       youssoupha niang

============================================================
  1. FC Union Berlin  —  SF sin salario:

         player  minutesPlayed
0  Linus Guther             14

  CG plantilla completa:

                 player          player_norm
0             Alex Král            alex kral
1      Aljoscha Kemlein     aljoscha kemlein
2        András Schäfer       andras schafer
3           Andrej Ilic          andrej ilic
4       Andrik Markgraf      andrik markgraf
5            Carl Klaus           carl klaus
6   Christopher Trimmel  christopher trimmel
7        Danilho Doekhi       danilho doekhi
8            David Preu           david preu
9          Derrick Köhn         derrick kohn
10          Diogo Leite          diogo leite
11      Dmytro Bogdanov      dmytro bogdanov
12      Frederik Rönnow      frederik ronnow
13          Ilyas Ansah          ilyas ansah
14        Janik Haberer        janik haberer
15      Josip Juranovic      josip juranovic
16     Leopold Querfeld     leopold querfeld
17          Livan Burcu          livan burcu
18       Marin Ljubicic       marin ljubicic
19          Matheo Raab          matheo raab
20         Oliver Burke         oliver burke
21         Rani Khedira         rani khedira
22          Robert Skov          robert skov
23        Stanley Nsoki        stanley nsoki
24           Tim Skarke           tim skarke
25            Tom Rothe            tom rothe
26      Woo-yeong Jeong      woo yeong jeong

============================================================
  1. FSV Mainz 05  —  SF sin salario:

  player  minutesPlayed
0  Silas            342

  CG plantilla completa:

                  player           player_norm
0   Andreas Hanche-Olsen  andreas hanche olsen
1           Anthony Caci          anthony caci
2           Armindo Sieb          armindo sieb
3          Arnaud Nordin         arnaud nordin
4            Ben Bobzien           ben bobzien
5    Benedict Hollerbach   benedict hollerbach
6            Daniel Batz           daniel batz
7         Daniel Gleiber        daniel gleiber
8         Danny da Costa        danny da costa
9           Dominik Kohr          dominik kohr
10     Fabio Moreno Fell     fabio moreno fell
11          Jae-sung Lee          jae sung lee
12       Kacper Potulski       kacper potulski
13           Kaishu Sano           kaishu sano
14             Kasey Bos             kasey bos
15            Lasse Rieß             lasse rie
16       Lennard Maloney       lennard maloney
17             Maxim Dal             maxim dal
18         Maxim Leitsch         maxim leitsch
19          Nadiem Amiri          nadiem amiri
20         Nelson Weiper         nelson weiper
21          Niklas Tauer          niklas tauer
22   Nikolas Veratschnig   nikolas veratschnig
23            Paul Nebel            paul nebel
24         Phillip Tietz         phillip tietz
25        Phillipp Mwene        phillipp mwene
26         Robin Zentner         robin zentner
27       Sheraldo Becker       sheraldo becker
28  Silas Katompa Mvumpa  silas katompa mvumpa
29         Silvan Widmer         silvan widmer
30         Sota Kawasaki         sota kawasaki
31           Stefan Bell           stefan bell
32          Stefan Posch          stefan posch
33        William Bøving         william bving

============================================================
  Bayer 04 Leverkusen  —  SF sin salario:

           player  minutesPlayed
0  Piero Hincapié             90

  CG plantilla completa:

                player         player_norm
0         Aleix García        aleix garcia
1   Alejandro Grimaldo  alejandro grimaldo
2               Arthur              arthur
3            Axel Tape           axel tape
4     Christian Kofane    christian kofane
5    Claudio Echeverri   claudio echeverri
6       Edmond Tapsoba      edmond tapsoba
7   Eliesse Ben Seghir  eliesse ben seghir
8          Ernest Poku         ernest poku
9    Exequiel Palacios   exequiel palacios
10  Ezequiel Fernández  ezequiel fernandez
11        Ibrahim Maza        ibrahim maza
12         Issa Traoré         issa traore
13      Janis Blaswich      janis blaswich
14      Jarell Quansah      jarell quansah
15    Jeanuël Belocian    jeanuel belocian
16       Jonas Hofmann       jonas hofmann
17         Jonas Omlin         jonas omlin
18           Loïc Badé           loic bade
19       Lucas Vázquez       lucas vazquez
20       Malik Tillman       malik tillman
21        Mark Flekken        mark flekken
22      Martin Terrier      martin terrier
23  Montrell Culbreath  montrell culbreath
24        Nathan Tella        nathan tella
25         Niklas Lomb         niklas lomb
26       Patrik Schick       patrik schick
27      Robert Andrich      robert andrich
28         Tim Oermann         tim oermann
29     Victor Boniface     victor boniface

============================================================
  Borussia Dortmund  —  SF sin salario:

            player  minutesPlayed
0  Aarón Anselmino            368
1    Luca Reggiani            245
2    Mathis Albert              1
3      Pascal Groß            618
4   Samuele Inacio            134

  CG plantilla completa:

                player         player_norm
0      Alexander Meyer     alexander meyer
1       Almugera Kabar      almugera kabar
2   Carney Chukwuemeka  carney chukwuemeka
3      Daniel Svensson     daniel svensson
4             Emre Can            emre can
5          Fábio Silva         fabio silva
6         Felix Nmecha        felix nmecha
7         Filippo Mane        filippo mane
8         Gregor Kobel        gregor kobel
9      Jobe Bellingham     jobe bellingham
10       Julian Brandt       julian brandt
11      Julian Ryerson      julian ryerson
12   Julien Duranville   julien duranville
13       Karim Adeyemi       karim adeyemi
14     Marcel Sabitzer     marcel sabitzer
15    Maximilian Beier    maximilian beier
16  Nico Schlotterbeck  nico schlotterbeck
17         Niklas Süle         niklas sule
18      Patrick Drewes      patrick drewes
19     Ramy Bensebaini     ramy bensebaini
20         Salih Özcan         salih ozcan
21     Serhou Guirassy     serhou guirassy
22    Silas Ostrzinski    silas ostrzinski
23      Waldemar Anton      waldemar anton
24           Yan Couto           yan couto

============================================================
  Borussia M'gladbach  —  SF sin salario:

             player  minutesPlayed
0  Charles Herrmann             10
1         Luca Netz            943
2      Oscar Fraulo             55

  CG plantilla completa:

                   player            player_norm
0             Alejo Sarco            alejo sarco
1         Fabio Chiarodia        fabio chiarodia
2         Florian Neuhaus        florian neuhaus
3          Franck Honorat         franck honorat
4          Giovanni Reyna         giovanni reyna
5        Grant-Leon Ranos       grant leon ranos
6         Haris Tabakovic        haris tabakovic
7              Hugo Bolin             hugo bolin
8          Jan Olschowsky         jan olschowsky
9              Jan Urbich             jan urbich
10           Jens Castrop           jens castrop
11             Joe Scally             joe scally
12            Jonas Omlin            jonas omlin
13             Kevin Diks             kevin diks
14           Kevin Stöger           kevin stoger
15             Kota Takai             kota takai
16          Lukas Ullrich          lukas ullrich
17       Marvin Friedrich       marvin friedrich
18         Moritz Nicolas         moritz nicolas
19        Nathan N'Goumou        nathan n goumou
20            Nico Elvedi            nico elvedi
21          Niklas Swider          niklas swider
22         Philipp Sander         philipp sander
23             Robin Hack             robin hack
24            Rocco Reitz            rocco reitz
25          Shuto Machino          shuto machino
26  Tiago Pereira Cardoso  tiago pereira cardoso
27        Tim Kleindienst        tim kleindienst
28          Tobias Sippel          tobias sippel
29         Tomas Cvancara         tomas cvancara
30             Wael Mohya             wael mohya
31      Yannik Engelhardt      yannik engelhardt

============================================================
  Eintracht Frankfurt  —  SF sin salario:

         player  minutesPlayed
0  Aurelio Buta            151

  CG plantilla completa:

                         player                  player_norm
0                 Amil Siljevic                amil siljevic
1                 Ansgar Knauff                ansgar knauff
2             Arnaud Kalimuendo            arnaud kalimuendo
3                 Arthur Theate                arthur theate
4                 Aurèle Amenda                aurele amenda
5   Ayoube Amaimouni-Echghouyab  ayoube amaimouni echghouyab
6                      Can Uzun                     can uzun
7                    Elias Baum                   elias baum
8                 Ellyes Skhiri                ellyes skhiri
9                     Elye Wahi                    elye wahi
10                 Farès Chaïbi                 fares chaibi
11                 Hugo Larsson                 hugo larsson
12           Jean-Mattéo Bahoya           jean matteo bahoya
13                   Jens Grahl                   jens grahl
14               Jessic Ngankam               jessic ngankam
15            Jonathan Burkardt            jonathan burkardt
16                  Kauã Santos                  kaua santos
17                 Keita Kosugi                 keita kosugi
18                  Love Arrhov                  love arrhov
19               Mahmoud Dahoud               mahmoud dahoud
20                  Mario Götze                  mario gotze
21             Michael Zetterer             michael zetterer
22              Michy Batshuayi              michy batshuayi
23              Nathaniel Brown              nathaniel brown
24               Nnamdi Collins               nnamdi collins
25                Oscar Højlund                 oscar hjlund
26            Rasmus Kristensen            rasmus kristensen
27                   Ritsu Doan                   ritsu doan
28                   Robin Koch                   robin koch
29             Timothy Chandler             timothy chandler
30            Younes Ebnoutalib            younes ebnoutalib

============================================================
  FC Augsburg  —  SF sin salario:

          player  minutesPlayed
0  Aiman Dardari             35
1     Arne Maier             15
2  Tim Schnitzer             11

  CG plantilla completa:

                   player            player_norm
0   Alexis Claude-Maurice  alexis claude maurice
1              Anton Kade             anton kade
2           Arthur Chaves          arthur chaves
3          Cédric Zesiger         cedric zesiger
4       Chrislain Matsima      chrislain matsima
5            Daniel Klein           daniel klein
6    Dimitrios Giannoulis   dimitrios giannoulis
7              Elias Saad             elias saad
8         Elvis Rexhbecaj        elvis rexhbecaj
9           Fabian Rieder          fabian rieder
10           Felix Meiser           felix meiser
11            Finn Dahmen            finn dahmen
12      Han-Noah Massengo      han noah massengo
13          Ismaël Gharbi          ismael gharbi
14     Jeffrey Gouweleeuw     jeffrey gouweleeuw
15    Keven Schlotterbeck    keven schlotterbeck
16        Kristijan Jakic        kristijan jakic
17          Mads Pedersen          mads pedersen
18      Mahmut Kücüksahin      mahmut kucuksahin
19            Marius Wolf            marius wolf
20             Mert Kömür             mert komur
21    Michael Gregoritsch    michael gregoritsch
22      Nediljko Labrovic      nediljko labrovic
23          Noahkai Banks          noahkai banks
24            Oliver Sorg            oliver sorg
25        Robin Fellhauer        robin fellhauer
26        Rodrigo Ribeiro        rodrigo ribeiro
27         Samuel Essende         samuel essende
28           Steve Mounié           steve mounie
29         Uchenna Ogundu         uchenna ogundu
30          Yannik Keitel          yannik keitel
31         Yusuf Kabadayi         yusuf kabadayi

============================================================
  FC Bayern München  —  SF sin salario:

             player  minutesPlayed
0    Cassiano Kiala              1
1      David Daiber             27
2        Deniz Ofli              8
3     Erblin Osmani              3
4  Jonah Kusi-Asare             10
5    Maycon Cardozo             32

  CG plantilla completa:

                 player          player_norm
0   Aleksandar Pavlovic  aleksandar pavlovic
1       Alexander Nübel      alexander nubel
2       Alphonso Davies      alphonso davies
3    Arijon Ibrahimovic   arijon ibrahimovic
4    Bara Sapoko Ndiaye   bara sapoko ndiaye
5        Bryan Zaragoza       bryan zaragoza
6       Dayot Upamecano      dayot upamecano
7            Harry Kane           harry kane
8            Hiroki Ito           hiroki ito
9         Jamal Musiala        jamal musiala
10        João Palhinha        joao palhinha
11          Jonas Urbig          jonas urbig
12         Jonathan Tah         jonathan tah
13       Joshua Kimmich       joshua kimmich
14       Josip Stanisic       josip stanisic
15        Konrad Laimer        konrad laimer
16         Lennart Karl         lennart karl
17        Leon Goretzka        leon goretzka
18          Leon Klanac          leon klanac
19            Luis Díaz            luis diaz
20         Manuel Neuer         manuel neuer
21        Michael Olise        michael olise
22          Min-jae Kim          min jae kim
23      Nicolas Jackson      nicolas jackson
24    Raphaël Guerreiro    raphael guerreiro
25           Sacha Boey           sacha boey
26         Serge Gnabry         serge gnabry
27         Sven Ulreich         sven ulreich
28       Tarek Buchmann       tarek buchmann
29          Tom Bischof          tom bischof
30          Wisdom Mike          wisdom mike

============================================================
  FC St. Pauli  —  SF sin salario:

             player  minutesPlayed
0  Oladapo Afolayan            155

  CG plantilla completa:

                  player           player_norm
0        Abdoulie Ceesay       abdoulie ceesay
1          Adam Dzwigala         adam dzwigala
2     Andréas Hountondji    andreas hountondji
3        Arkadiusz Pyrka       arkadiusz pyrka
4               Ben Voll              ben voll
5        Connor Metcalfe       connor metcalfe
6           Danel Sinani          danel sinani
7           David Nemeth          david nemeth
8            Emil Gazdov           emil gazdov
9             Eric Smith            eric smith
10           Fin Stevens           fin stevens
11            Hauke Wahl            hauke wahl
12        Jackson Irvine        jackson irvine
13           James Sands           james sands
14       Jannik Robatsch       jannik robatsch
15     Joel Chima Fujita     joel chima fujita
16            Karol Mets            karol mets
17           Lars Ritzka           lars ritzka
18           Louis Oppie           louis oppie
19      Manolis Saliakas      manolis saliakas
20         Martijn Kaars         martijn kaars
21        Marwin Schmitz        marwin schmitz
22  Mathias Pereira Lage  mathias pereira lage
23     Mathias Rasmussen     mathias rasmussen
24          Nick Schmidt          nick schmidt
25         Nikola Vasilj         nikola vasilj
26      Ricky-Jade Jones      ricky jade jones
27           Simon Spari           simon spari
28           Taichi Hara           taichi hara
29           Tomoya Ando           tomoya ando

============================================================
  Hamburger SV  —  SF sin salario:

               player  minutesPlayed
0  Aboubaka Soumahoro            141
1         Emir Sahiti            122
2     Guilherme Ramos             78
3       Jonas Meffert            151

  CG plantilla completa:

                           player                    player_norm
0                 Albert Grønbaek                 albert grnbaek
1            Albert Sambi Lokonga           albert sambi lokonga
2      Alexander Røssing-Lelesiit      alexander rssing lelesiit
3                    Bakery Jatta                   bakery jatta
4                    Damion Downs                   damion downs
5                  Daniel Elfadli                 daniel elfadli
6          Daniel Heuer Fernandes         daniel heuer fernandes
7                   Daniel Peretz                  daniel peretz
8                     Fábio Baldé                    fabio balde
9                    Fábio Vieira                   fabio vieira
10                Fernando Dickes                fernando dickes
11          Giorgi Gocholeishvili          giorgi gocholeishvili
12                 Hannes Hermann                 hannes hermann
13                Immanuel Pherai                immanuel pherai
14                 Jean-Luc Dompé                 jean luc dompe
15             Jordan Torunarigha             jordan torunarigha
16                    Louis Lemke                    louis lemke
17                  Luka Vuskovic                  luka vuskovic
18                    Miro Muheim                    miro muheim
19                Nicolai Remberg                nicolai remberg
20                Nicolás Capaldo                nicolas capaldo
21                Noah Katterbach                noah katterbach
22                    Omar Megeed                    omar megeed
23                    Otto Stange                    otto stange
24                   Philip Otele                   philip otele
25  Ransford-Yeboah Königsdörffer  ransford yeboah konigsdorffer
26                 Rayan Philippe                 rayan philippe
27                 Robert Glatzel                 robert glatzel
28                 Sander Tangvik                 sander tangvik
29                  Shafiq Nandja                  shafiq nandja
30                   Warmed Omari                   warmed omari
31           William Mikelbrencis           william mikelbrencis
32                 Yussuf Poulsen                 yussuf poulsen

============================================================
  RB Leipzig  —  SF sin salario:

        player  minutesPlayed
0  Kevin Kampl              3
1  Loïs Openda             55
2  Timo Werner             13
3  Xavi Simons             90

  CG plantilla completa:

                    player             player_norm
0       Andrija Maksimovic      andrija maksimovic
1             Antonio Nusa            antonio nusa
2          Assan Ouédraogo         assan ouedraogo
3           Ayodele Thomas          ayodele thomas
4        Benjamin Henrichs       benjamin henrichs
5             Brajan Gruda            brajan gruda
6          Castello Lukeba         castello lukeba
7    Christoph Baumgartner   christoph baumgartner
8            Conrad Harder           conrad harder
9               David Raum              david raum
10  El Chadaille Bitshiabu  el chadaille bitshiabu
11        Ezechiel Banzuzi        ezechiel banzuzi
12          Johan Bakayoko          johan bakayoko
13         Jonathan Norbye         jonathan norbye
14    Joyeux Masanka Bungi    joyeux masanka bungi
15       Kosta Nedeljkovic       kosta nedeljkovic
16        Leopold Zingerle        leopold zingerle
17       Lukas Klostermann       lukas klostermann
18     Maarten Vandevoordt     maarten vandevoordt
19           Max Finkgräfe           max finkgrafe
20         Nicolas Seiwald         nicolas seiwald
21           Péter Gulácsi           peter gulacsi
22              Ridle Baku              ridle baku
23                  Rômulo                  romulo
24            Samba Konaté            samba konate
25            Suleman Sani            suleman sani
26            Tidiam Gomis            tidiam gomis
27             Viggo Gebel             viggo gebel
28             Willi Orbán             willi orban
29          Xaver Schlager          xaver schlager
30            Yan Diomande            yan diomande

============================================================
  SC Freiburg  —  SF sin salario:

             player  minutesPlayed
0       Merlin Röhl             65
1  Rouven Tarnutzer             11

  CG plantilla completa:

                  player           player_norm
0           Anthony Jung          anthony jung
1            Bruno Ogbus           bruno ogbus
2       Christian Günter      christian gunter
3          Cyriaque Irié         cyriaque irie
4     Daniel-Kofi Kyereh    daniel kofi kyereh
5        Derry Scherhant       derry scherhant
6            Eren Dinkçi           eren dinkci
7         Florian Müller        florian muller
8         Igor Matanovic        igor matanovic
9       Jan-Niklas Beste      jan niklas beste
10           Jannik Huth           jannik huth
11        Johan Manzambi        johan manzambi
12         Jordy Makengo         jordy makengo
13          Junior Adamu          junior adamu
14           Lucas Höler           lucas holer
15          Lukas Kübler          lukas kubler
16       Matthias Ginter       matthias ginter
17       Max Rosenfelder       max rosenfelder
18  Maximilian Eggestein  maximilian eggestein
19    Maximilian Philipp    maximilian philipp
20        Nicolas Höfler        nicolas hofler
21          Noah Atubolu          noah atubolu
22     Patrick Osterhage     patrick osterhage
23      Philipp Lienhart      philipp lienhart
24          Philipp Treu          philipp treu
25        Vincenzo Grifo        vincenzo grifo
26          Yuito Suzuki          yuito suzuki

============================================================
  SV Werder Bremen  —  SF sin salario:

               player  minutesPlayed
0  Isak Hansen Aarøen              1

  CG plantilla completa:

                  player           player_norm
0            Amos Pieper           amos pieper
1        Cameron Puertas       cameron puertas
2              Felix Agu             felix agu
3          Isaac Schmidt         isaac schmidt
4             Jens Stage            jens stage
5        Jovan Milosevic       jovan milosevic
6        Julián Malatini       julian malatini
7         Justin Njinmah        justin njinmah
8        Karim Coulibaly       karim coulibaly
9              Karl Hein             karl hein
10             Keke Topp             keke topp
11  Leonardo Bittencourt  leonardo bittencourt
12          Marco Friedl          marco friedl
13           Marco Grüll           marco grull
14          Markus Kolke          markus kolke
15      Maximilian Wöber      maximilian wober
16       Mick Schmetgens       mick schmetgens
17          Mio Backhaus          mio backhaus
18       Mitchell Weiser       mitchell weiser
19          Niklas Stark          niklas stark
20         Olivier Deman         olivier deman
21         Patrice Covic         patrice covic
22         Romano Schmid         romano schmid
23           Salim Musah           salim musah
24       Samuel Mbangula       samuel mbangula
25           Senne Lynen           senne lynen
26         Skelly Alvero         skelly alvero
27      Stefan Smarkalev      stefan smarkalev
28       Victor Boniface       victor boniface
29           Wesley Adeh           wesley adeh
30     Yukinari Sugawara     yukinari sugawara

============================================================
  VfB Stuttgart  —  SF sin salario:

           player  minutesPlayed
0  Nick Woltemade             90

  CG plantilla completa:

                    player             player_norm
0          Alexander Nübel         alexander nubel
1          Ameen Al-Dakhil         ameen al dakhil
2           Angelo Stiller          angelo stiller
3           Atakan Karazor          atakan karazor
4       Badredine Bouanani      badredine bouanani
5       Bilal El Khannouss      bilal el khannouss
6             Chema Andrés            chema andres
7            Chris Führich           chris fuhrich
8         Dan-Axel Zagadou        dan axel zagadou
9              Deniz Undav             deniz undav
10       Ermedin Demirovic       ermedin demirovic
11          Fabian Bredlow          fabian bredlow
12            Finn Jeltsch            finn jeltsch
13       Florian Hellstern       florian hellstern
14          Jamie Leweling          jamie leweling
15          Jeremy Arévalo          jeremy arevalo
16          Josha Vagnoman          josha vagnoman
17           Julian Chabot           julian chabot
18            Justin Diehl            justin diehl
19         Lazar Jovanovic         lazar jovanovic
20         Lorenz Assignon         lorenz assignon
21             Luca Jaquez             luca jaquez
22  Maximilian Mittelstädt  maximilian mittelstadt
23           Mirza Catovic           mirza catovic
24          Nikolas Nartey          nikolas nartey
25            Noah Darvich            noah darvich
26          Pascal Stenzel          pascal stenzel
27          Ramon Hendriks          ramon hendriks
28          Stefan Drljaca          stefan drljaca
29             Tiago Tomás             tiago tomas
30           Yannik Keitel           yannik keitel

============================================================
  VfL Wolfsburg  —  SF sin salario:

         player  minutesPlayed
0  Vaclav Cerny             46

  CG plantilla completa:

                      player               player_norm
0              Aaron Zehnter             aaron zehnter
1                Adam Daghim               adam daghim
2         Andreas Skov Olsen        andreas skov olsen
3              Aster Vranckx             aster vranckx
4               Bence Dárdai              bence dardai
5          Christian Eriksen         christian eriksen
6                    Cleiton                   cleiton
7                Denis Vavro               denis vavro
8          Dzenan Pejcinovic         dzenan pejcinovic
9            Jakub Zielinski           jakub zielinski
10                Jan Bürger                jan burger
11          Jeanuël Belocian          jeanuel belocian
12              Jenson Seelt              jenson seelt
13          Jesper Lindstrøm           jesper lindstrm
14             Joakim Maehle             joakim maehle
15             Jonas Adjetey             jonas adjetey
16                Jonas Wind                jonas wind
17             Kamil Grabara             kamil grabara
18             Kento Shiogai             kento shiogai
19             Kevin Paredes             kevin paredes
20            Kilian Fischer            kilian fischer
21  Konstantinos Koulierakis  konstantinos koulierakis
22               Lovro Majer               lovro majer
23             Marius Müller             marius muller
24          Mattias Svanberg          mattias svanberg
25         Maximilian Arnold         maximilian arnold
26            Mohamed Amoura            mohamed amoura
27               Moritz Jenz               moritz jenz
28            Patrick Wimmer            patrick wimmer
29              Pavao Pervan              pavao pervan
30            Pharell Hensel            pharell hensel
31                   Rogério                   rogerio
32              Saël Kumbedi              sael kumbedi
33            Vinicius Souza            vinicius souza
34          Yannick Gerhardt          yannick gerhardt

In [25]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('silas', '1 fsv mainz 05'): ('silas katompa mvumpa', '1 fsv mainz 05')
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [26]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: silas (1 fsv mainz 05) → silas katompa mvumpa (1 fsv mainz 05)

Tras matches manuales: 457/494 (92.5%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

⚠️ Nombre con sufijo `_snapshot_20260428` para diferenciar del master definitivo
que se generará al cierre de la temporada (`master_germany_2526.csv`).

In [27]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_germany_2526_snapshot_20260428.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_germany_2526_snapshot_20260428.csv
   Jugadores totales:  494
   Con salario:        457
   Sin salario (NaN):  37
   Columnas:           122