# 03 · Join Sofascore + Capology — Germany Bundesliga 23/24

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2023/24 de Bundesliga alemana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_germany_2324.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_germany_2324.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  494 jugadores | 116 columnas
Capology:   557 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   1 fc heidenheim
   1 fc koln
   1 fc union berlin
   1 fsv mainz 05
   bayer 04 leverkusen
   borussia m gladbach
   darmstadt 98
   fc augsburg
   fc bayern munchen
   rb leipzig
   sc freiburg
   sv werder bremen
   tsg hoffenheim
   vfb stuttgart
   vfl bochum 1848
   vfl wolfsburg

En Capology pero no en Sofascore:
   augsburg
   bayer leverkusen
   bayern munich
   bochum
   darmstadt
   freiburg
   heidenheim
   hoffenheim
   koln
   leipzig
   mainz
   monchengladbach
   stuttgart
   union berlin
   werder bremen
   wolfsburg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'augsburg':'fc augsburg',
            'bayer leverkusen':'bayer 04 leverkusen',
            'bayern munich':'fc bayern munchen',
            'bochum':'vfl bochum 1848',
            'darmstadt':'darmstadt 98',
            'freiburg':'sc freiburg',
            'heidenheim':'1 fc heidenheim',
            'hoffenheim':'tsg hoffenheim',
            'koln':'1 fc koln',
            'leipzig':'rb leipzig',
            'mainz':'1 fsv mainz 05',
            'monchengladbach':'borussia m gladbach',
            'stuttgart':'vfb stuttgart',
            'union berlin':'1 fc union berlin',
            'werder bremen':'sv werder bremen',
            'wolfsburg':'vfl wolfsburg'                          
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 446/494 (90.3%)
Sin emparejar: 48

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          3
Revisión media    (0.75 ≤ score < 0.90):   8
Revisión estricta (0.50 ≤ score < 0.75):   24
Revisión muy est. (score < 0.50):           13

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

          player_sf                team         cg_match  score
2   Frederik Rønnow  1. FC Union Berlin  frederik ronnow  0.966
30   Stanley N'Soki      TSG Hoffenheim    stanley nsoki  0.963
9      Joakim Mæhle       VfL Wolfsburg    joakim maehle  0.917

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
23,Joseph Scally,Borussia M'gladbach,joe scally,0.870
1,Victor Okoh Boniface,Bayer 04 Leverkusen,victor boniface,0.857
10,Jamie Gittens,Borussia Dortmund,jamie bynoe gittens,0.812
5,Leandro Barreiro,1. FSV Mainz 05,leandro barreiro martins,0.800
35,Matondo-Merveille Papela,1. FSV Mainz 05,merveille papela,0.800
6,Mateu Morey,Borussia Dortmund,mateu morey bauza,0.786
21,Dion Drena Beljo,FC Augsburg,dion beljo,0.769
24,Haktab Omar Traore,1. FC Heidenheim,omar traore,0.759

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 8 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf                 team              cg_match  score
14          John Brooks       TSG Hoffenheim   john anthony brooks  0.733
37   Maximilian Breunig          SC Freiburg  maximilian eggestein  0.684
4           Jeff Chabot           1. FC Köln         julian chabot  0.667
40         Oliver Burke     SV Werder Bremen         olivier deman  0.640
0        Miloš Pantović   1. FC Union Berlin       josip juranovic  0.621
8    Junior Dina Ebimbe  Eintracht Frankfurt           eric ebimbe  0.621
13                Silas        VfB Stuttgart              gil dias  0.615
15         Rafael Borré     SV Werder Bremen          santos borre  0.583
12            Manu Koné  Borussia M'gladbach          kouadio kone  0.571
3          Kjell Wätjen    Borussia Dortmund         donyell malen  0.560
16       Anwar El Ghazi      1. FSV Mainz 05           daniel batz  0.560
28        Marcus Müller      1. FSV Mainz 05         marco richter  0.538
7         Iago Borduchi          FC Augsburg         niklas dorsch  0.538
39           Ilia Gruev     SV Werder Bremen             felix agu  0.526
33         Simon Zoller      VfL Bochum 1848           tim oermann  0.522
26       Lovro Zvonarek    FC Bayern München         leon goretzka  0.519
34        Fabian Rudlin          SC Freiburg        florian muller  0.519
17        Frans Krätzig    FC Bayern München        bryan zaragoza  0.519
11         Samuel Bamba    Borussia Dortmund      abdoulaye kamara  0.500
27     Marko Mladenović  Eintracht Frankfurt          marcel wenig  0.500
22  Matteo Pérez Vinlöf    FC Bayern München         daniel peretz  0.500
41        Bennit Bröger        VfL Wolfsburg               rogerio  0.500
19         Hendry Blank    Borussia Dortmund              emre can  0.500
36           Borna Sosa        VfB Stuttgart        florian schock  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['john brooks',
                    'jeff chabot',
                    'junior dina ebimbe',
                    'rafael borre',
                    'manu kone'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 5

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf                 team           cg_match  score
46          Joel Imasuen     SV Werder Bremen      olivier deman  0.480
38           Asaf Arania         Darmstadt 98     bartol franjic  0.480
18      Ryan Gravenberch    FC Bayern München     bryan zaragoza  0.467
32        Thorgan Hazard    Borussia Dortmund  mateu morey bauza  0.452
29     Randal Kolo Muani  Eintracht Frankfurt     sasa kalajdzic  0.452
25           Tim Drexler       TSG Hoffenheim   maximilian beier  0.444
31      Jesper Lindstrøm  Eintracht Frankfurt  jens petter hauge  0.438
44            Nuha Jatta           RB Leipzig     amadou haidara  0.417
45     Mahmut Kücüksahin          FC Augsburg       tomas koubek  0.414
42   Jonathan Asp Jensen    FC Bayern München         harry kane  0.414
20  Samuele Di Benedetto        VfB Stuttgart     mahmoud dahoud  0.412
47    Kofi Jeremy Amoako        VfL Wolfsburg      joakim maehle  0.387
43       Jonathan Norbye           RB Leipzig  benjamin henrichs  0.375

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 462/494 (93.5%)
Sin salario:     32

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 32

,player,team,minutesPlayed,appearances,goals,assists
0,Miloš Pantović,1. FC Union Berlin,14,1,1,0
1,Anwar El Ghazi,1. FSV Mainz 05,51,3,0,1
2,Marcus Müller,1. FSV Mainz 05,17,1,0,0
3,Kjell Wätjen,Borussia Dortmund,104,2,0,1
4,Samuel Bamba,Borussia Dortmund,45,2,0,0
5,Hendry Blank,Borussia Dortmund,45,1,0,0
6,Thorgan Hazard,Borussia Dortmund,13,1,0,0
7,Asaf Arania,Darmstadt 98,10,1,0,0
8,Randal Kolo Muani,Eintracht Frankfurt,155,2,1,0
9,Jesper Lindstrøm,Eintracht Frankfurt,84,1,0,0
10,Marko Mladenović,Eintracht Frankfurt,9,1,0,0
11,Iago Borduchi,FC Augsburg,1622,23,1,1
12,Mahmut Kücüksahin,FC Augsburg,1,1,0,0
13,Lovro Zvonarek,FC Bayern München,163,5,1,0
14,Frans Krätzig,FC Bayern München,52,4,0,0
15,Matteo Pérez Vinlöf,FC Bayern München,15,1,0,0
16,Ryan Gravenberch,FC Bayern München,9,1,0,0
17,Jonathan Asp Jensen,FC Bayern München,1,1,0,0
18,Jonathan Norbye,RB Leipzig,1,1,0,0
19,Nuha Jatta,RB Leipzig,1,1,0,0
20,Maximilian Breunig,SC Freiburg,18,2,0,0
21,Fabian Rudlin,SC Freiburg,10,1,0,0
22,Oliver Burke,SV Werder Bremen,31,1,0,0
23,Ilia Gruev,SV Werder Bremen,11,1,0,0
24,Joel Imasuen,SV Werder Bremen,1,1,0,0
25,Tim Drexler,TSG Hoffenheim,573,8,0,0
26,Silas,VfB Stuttgart,909,27,5,2
27,Borna Sosa,VfB Stuttgart,44,2,0,0
28,Samuele Di Benedetto,VfB Stuttgart,12,1,0,0
29,Simon Zoller,VfL Bochum 1848,45,1,0,0
30,Bennit Bröger,VfL Wolfsburg,10,1,0,0
31,Kofi Jeremy Amoako,VfL Wolfsburg,2,2,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  1. FC Union Berlin  —  SF sin salario:

           player  minutesPlayed
0  Miloš Pantović             14

  CG plantilla completa:

                 player          player_norm
0        Aïssa Laïdouni       aissa laidouni
1             Alex Kral            alex kral
2    Alexander Schwolow   alexander schwolow
3      Aljoscha Kemlein     aljoscha kemlein
4        András Schäfer       andras schafer
5   Benedict Hollerbach  benedict hollerbach
6      Brenden Aaronson     brenden aaronson
7           Chris Bedia          chris bedia
8   Christopher Trimmel  christopher trimmel
9        Danilho Doekhi       danilho doekhi
10   David Datro Fofana   david datro fofana
11          Diogo Leite          diogo leite
12      Frederik Rönnow      frederik ronnow
13           Jakob Busk           jakob busk
14        Janik Haberer        janik haberer
15    Jérôme Roussillon    jerome roussillon
16      Josip Juranovic      josip juranovic
17        Kevin Behrens        kevin behrens
18           Kevin Vogt           kevin vogt
19        Kevin Volland        kevin volland
20         Laurenz Dehl         laurenz dehl
21     Leonardo Bonucci     leonardo bonucci
22        Lucas Tousart        lucas tousart
23      Mikkel Kaufmann      mikkel kaufmann
24      Noah Engelbreth      noah engelbreth
25         Paul Jaeckel         paul jaeckel
26         Rani Khedira         rani khedira
27         Robin Gosens         robin gosens
28         Robin Knoche         robin knoche
29      Sheraldo Becker      sheraldo becker
30         Yannic Stein         yannic stein
31      Yorbe Vertessen      yorbe vertessen

============================================================
  1. FSV Mainz 05  —  SF sin salario:

           player  minutesPlayed
0  Anwar El Ghazi             51
1   Marcus Müller             17

  CG plantilla completa:

                      player               player_norm
0       Andreas Hanche-Olsen      andreas hanche olsen
1               Anthony Caci              anthony caci
2               Aymen Barkok              aymen barkok
3               Brajan Gruda              brajan gruda
4                Daniel Batz               daniel batz
5             Danny da Costa            danny da costa
6            David Mamutovic           david mamutovic
7               Dominik Kohr              dominik kohr
8        Edimilson Fernandes       edimilson fernandes
9              Eniss Shabani             eniss shabani
10              Jae-sung Lee              jae sung lee
11            Jessic Ngankam            jessic ngankam
12         Jonathan Burkardt         jonathan burkardt
13         Josuha Guilavogui         josuha guilavogui
14             Karim Onisiwo             karim onisiwo
15                Lasse Rieß                 lasse rie
16  Leandro Barreiro Martins  leandro barreiro martins
17           Ludovic Ajorque           ludovic ajorque
18             Marco Richter             marco richter
19             Maxim Leitsch             maxim leitsch
20          Merveille Papela          merveille papela
21              Nadiem Amiri              nadiem amiri
22             Nelson Weiper             nelson weiper
23            Philipp Schulz            philipp schulz
24            Phillipp Mwene            phillipp mwene
25             Robin Zentner             robin zentner
26         Sepp van den Berg         sepp van den berg
27             Silvan Widmer             silvan widmer
28               Stefan Bell               stefan bell
29                 Tom Krauß                  tom krau

============================================================
  Borussia Dortmund  —  SF sin salario:

           player  minutesPlayed
0    Hendry Blank             45
1    Kjell Wätjen            104
2    Samuel Bamba             45
3  Thorgan Hazard             13

  CG plantilla completa:

                   player            player_norm
0        Abdoulaye Kamara       abdoulaye kamara
1         Alexander Meyer        alexander meyer
2   Antonios Papadopoulos  antonios papadopoulos
3           Donyell Malen          donyell malen
4                Emre Can               emre can
5            Felix Nmecha           felix nmecha
6          Giovanni Reyna         giovanni reyna
7            Gregor Kobel           gregor kobel
8             Ian Maatsen            ian maatsen
9            Jadon Sancho           jadon sancho
10    Jamie Bynoe-Gittens    jamie bynoe gittens
11          Julian Brandt          julian brandt
12         Julian Ryerson         julian ryerson
13      Julien Duranville      julien duranville
14          Karim Adeyemi          karim adeyemi
15           Marcel Lotka           marcel lotka
16        Marcel Sabitzer        marcel sabitzer
17             Marco Reus             marco reus
18            Marius Wolf            marius wolf
19      Mateu Morey Bauzà      mateu morey bauza
20           Mats Hummels           mats hummels
21        Niclas Füllkrug        niclas fullkrug
22     Nico Schlotterbeck     nico schlotterbeck
23            Niklas Süle            niklas sule
24           Ole Pohlmann           ole pohlmann
25          Paris Brunner          paris brunner
26        Ramy Bensebaini        ramy bensebaini
27            Salih Özcan            salih ozcan
28       Sébastien Haller       sebastien haller
29       Silas Ostrzinski       silas ostrzinski
30         Thomas Meunier         thomas meunier
31      Youssoufa Moukoko      youssoufa moukoko

============================================================
  Darmstadt 98  —  SF sin salario:

        player  minutesPlayed
0  Asaf Arania             10

  CG plantilla completa:

                  player           player_norm
0           Aaron Seydel          aaron seydel
1       Alexander Brunst      alexander brunst
2         Andreas Müller        andreas muller
3         Bartol Franjic        bartol franjic
4           Braydon Manu          braydon manu
5       Christoph Klarer      christoph klarer
6   Christoph Zimmermann  christoph zimmermann
7         Clemens Riedel        clemens riedel
8             Emir Karic            emir karic
9         Fabian Holland        fabian holland
10     Fabian Nürnberger     fabian nurnberger
11   Fabian Schnellhardt   fabian schnellhardt
12       Fabio Torsiello       fabio torsiello
13     Filip Stojilkovic     filip stojilkovic
14        Frank Ronstadt        frank ronstadt
15         Fraser Hornby         fraser hornby
16       Gerrit Holtmann       gerrit holtmann
17         Jannik Müller         jannik muller
18        Julian Justvan        julian justvan
19         Klaus Gjasula         klaus gjasula
20         Luca Pfeiffer         luca pfeiffer
21        Marcel Schuhen        marcel schuhen
22         Marvin Mehlem         marvin mehlem
23         Matej Maglica         matej maglica
24        Mathias Honsak        mathias honsak
25        Matthias Bader        matthias bader
26             Max Wendt             max wendt
27        Morten Behrens        morten behrens
28     Oscar Vilhelmsson     oscar vilhelmsson
29      Sebastian Polter      sebastian polter
30      Thomas Isherwood      thomas isherwood
31            Tim Skarke            tim skarke
32          Tobias Kempe          tobias kempe

============================================================
  Eintracht Frankfurt  —  SF sin salario:

              player  minutesPlayed
0   Jesper Lindstrøm             84
1   Marko Mladenović              9
2  Randal Kolo Muani            155

  CG plantilla completa:

                player         player_norm
0        Ansgar Knauff       ansgar knauff
1         Aurélio Buta        aurelio buta
2         Dario Gebuhr        dario gebuhr
3       Davis Bautista      davis bautista
4    Donny van de Beek   donny van de beek
5           Elias Baum          elias baum
6        Ellyes Skhiri       ellyes skhiri
7          Éric Ebimbe         eric ebimbe
8         Farès Chaïbi        fares chaibi
9      Harpreet Ghotra     harpreet ghotra
10      Hrvoje Smolcic      hrvoje smolcic
11        Hugo Ekitiké        hugo ekitike
12        Hugo Larsson        hugo larsson
13  Jean-Mattéo Bahoya  jean matteo bahoya
14          Jens Grahl          jens grahl
15   Jens Petter Hauge   jens petter hauge
16      Jessic Ngankam      jessic ngankam
17         Kauã Santos         kaua santos
18         Kevin Trapp         kevin trapp
19     Kristijan Jakic     kristijan jakic
20        Lucas Alario        lucas alario
21       Makoto Hasebe       makoto hasebe
22        Marcel Wenig        marcel wenig
23         Mario Götze         mario gotze
24         Mehdi Loune         mehdi loune
25         Nacho Ferri         nacho ferri
26      Niels Nkounkou      niels nkounkou
27      Nnamdi Collins      nnamdi collins
28         Noel Futkeu         noel futkeu
29       Omar Marmoush       omar marmoush
30     Paxten Aaronson     paxten aaronson
31         Philipp Max         philipp max
32          Robin Koch          robin koch
33      Sasa Kalajdzic      sasa kalajdzic
34      Sebastian Rode      sebastian rode
35     Sidney Raebiger     sidney raebiger
36        Simon Simoni        simon simoni
37    Timothy Chandler    timothy chandler
38                Tuta                tuta
39       Willian Pacho       willian pacho

============================================================
  FC Augsburg  —  SF sin salario:

              player  minutesPlayed
0      Iago Borduchi           1622
1  Mahmut Kücüksahin              1

  CG plantilla completa:

                player         player_norm
0        Aaron Zehnter       aaron zehnter
1          Arne Engels         arne engels
2           Arne Maier          arne maier
3         David Colina        david colina
4           Dion Beljo          dion beljo
5      Elvis Rexhbecaj     elvis rexhbecaj
6    Ermedin Demirovic   ermedin demirovic
7       Felix Uduokhai      felix uduokhai
8          Finn Dahmen         finn dahmen
9     Frederik Winther    frederik winther
10      Fredrik Jensen      fredrik jensen
11                Iago                iago
12       Irvin Cardona       irvin cardona
13     Japhet Tanganga     japhet tanganga
14  Jeffrey Gouweleeuw  jeffrey gouweleeuw
15         Kevin Mbabu         kevin mbabu
16     Kristijan Jakic     kristijan jakic
17       Mads Pedersen       mads pedersen
18        Marcel Lubik        marcel lubik
19      Masaya Okugawa      masaya okugawa
20    Maximilian Bauer    maximilian bauer
21          Mert Kömür          mert komur
22     Nathanaël Mbuku     nathanael mbuku
23       Niklas Dorsch       niklas dorsch
24     Patric Pfeiffer     patric pfeiffer
25            Pep Biel            pep biel
26       Phillip Tietz       phillip tietz
27  Raphael Framberger  raphael framberger
28        Reece Oxford        reece oxford
29        Robert Gumny        robert gumny
30        Rubén Vargas        ruben vargas
31         Sven Michel         sven michel
32      Tim Breithaupt      tim breithaupt
33        Tomas Koubek        tomas koubek

============================================================
  FC Bayern München  —  SF sin salario:

                player  minutesPlayed
0        Frans Krätzig             52
1  Jonathan Asp Jensen              1
2       Lovro Zvonarek            163
3  Matteo Pérez Vinlöf             15
4     Ryan Gravenberch              9

  CG plantilla completa:

                      player               player_norm
0        Aleksandar Pavlovic       aleksandar pavlovic
1            Alexander Nübel           alexander nubel
2            Alphonso Davies           alphonso davies
3                 Bouna Sarr                bouna sarr
4             Bryan Zaragoza            bryan zaragoza
5              Daniel Peretz             daniel peretz
6            Dayot Upamecano           dayot upamecano
7                  Eric Dier                 eric dier
8   Eric Maxim Choupo-Moting  eric maxim choupo moting
9                 Harry Kane                harry kane
10             Jamal Musiala             jamal musiala
11            Joshua Kimmich            joshua kimmich
12            Kingsley Coman            kingsley coman
13             Konrad Laimer             konrad laimer
14             Leon Goretzka             leon goretzka
15                Leroy Sané                leroy sane
16              Manuel Neuer              manuel neuer
17                Mathys Tel                mathys tel
18          Matthijs de Ligt          matthijs de ligt
19               Min-jae Kim               min jae kim
20         Noussair Mazraoui         noussair mazraoui
21         Raphaël Guerreiro         raphael guerreiro
22                Sacha Boey                sacha boey
23              Serge Gnabry              serge gnabry
24              Sven Ulreich              sven ulreich
25            Tarek Buchmann            tarek buchmann
26             Thomas Müller             thomas muller
27        Tom Ritzy Hülsmann        tom ritzy hulsmann

============================================================
  RB Leipzig  —  SF sin salario:

            player  minutesPlayed
0  Jonathan Norbye              1
1       Nuha Jatta              1

  CG plantilla completa:

                    player             player_norm
0           Amadou Haidara          amadou haidara
1        Benjamin Henrichs       benjamin henrichs
2           Benjamin Sesko          benjamin sesko
3          Castello Lukeba         castello lukeba
4    Christoph Baumgartner   christoph baumgartner
5         Christopher Lenz        christopher lenz
6                Dani Olmo               dani olmo
7               David Raum              david raum
8   El Chadaille Bitshiabu  el chadaille bitshiabu
9              Eljif Elmas             eljif elmas
10           Emil Forsberg           emil forsberg
11          Fábio Carvalho          fabio carvalho
12            Ilaix Moriba            ilaix moriba
13          Janis Blaswich          janis blaswich
14             Kevin Kampl             kevin kampl
15        Leopold Zingerle        leopold zingerle
16             Loïs Openda             lois openda
17       Lukas Klostermann       lukas klostermann
18         Mohamed Simakan         mohamed simakan
19         Nicolas Seiwald         nicolas seiwald
20           Péter Gulácsi           peter gulacsi
21              Tim Köhler              tim kohler
22           Timo Schlieck           timo schlieck
23             Timo Werner             timo werner
24             Willi Orbán             willi orban
25          Xaver Schlager          xaver schlager
26             Xavi Simons             xavi simons
27          Yussuf Poulsen          yussuf poulsen

============================================================
  SC Freiburg  —  SF sin salario:

               player  minutesPlayed
0       Fabian Rudlin             10
1  Maximilian Breunig             18

  CG plantilla completa:

                  player           player_norm
0          Attila Szalai         attila szalai
1        Benjamin Uphoff       benjamin uphoff
2       Christian Günter      christian gunter
3     Daniel-Kofi Kyereh    daniel kofi kyereh
4        Florent Muslija       florent muslija
5         Florian Müller        florian muller
6          Jordy Makengo         jordy makengo
7           Junior Adamu          junior adamu
8        Kenneth Schmidt       kenneth schmidt
9      Kiliann Sildillia     kiliann sildillia
10           Lucas Höler           lucas holer
11          Lukas Kübler          lukas kubler
12          Manuel Gulde          manuel gulde
13       Matthias Ginter       matthias ginter
14       Max Rosenfelder       max rosenfelder
15  Maximilian Eggestein  maximilian eggestein
16    Maximilian Philipp    maximilian philipp
17           Merlin Röhl           merlin rohl
18   Michael Gregoritsch   michael gregoritsch
19        Nicolas Höfler        nicolas hofler
20          Noah Atubolu          noah atubolu
21        Noah Weißhaupt         noah weihaupt
22      Philipp Lienhart      philipp lienhart
23            Ritsu Doan            ritsu doan
24         Roland Sallai         roland sallai
25        Vincenzo Grifo        vincenzo grifo
26         Yannik Keitel         yannik keitel

============================================================
  SV Werder Bremen  —  SF sin salario:

         player  minutesPlayed
0    Ilia Gruev             11
1  Joel Imasuen              1
2  Oliver Burke             31

  CG plantilla completa:

                        player                 player_norm
0                  Amos Pieper                 amos pieper
1                 Anthony Jung                anthony jung
2               Christian Groß               christian gro
3               Dawid Kownacki              dawid kownacki
4   Eduardo Dos Santos Haesler  eduardo dos santos haesler
5                    Felix Agu                   felix agu
6           Isak Hansen-Aarøen           isak hansen aaren
7                   Jens Stage                  jens stage
8                Jiri Pavlenka               jiri pavlenka
9              Julián Malatini             julian malatini
10              Justin Njinmah              justin njinmah
11                  Leon Opitz                  leon opitz
12        Leonardo Bittencourt        leonardo bittencourt
13                Marco Friedl                marco friedl
14              Marvin Ducksch              marvin ducksch
15            Michael Zetterer            michael zetterer
16             Milos Veljkovic             milos veljkovic
17             Mitchell Weiser             mitchell weiser
18                  Naby Keïta                  naby keita
19              Nick Woltemade              nick woltemade
20                Nicolai Rapp                nicolai rapp
21                Niklas Stark                niklas stark
22               Olivier Deman               olivier deman
23               Romano Schmid               romano schmid
24                Santos Borré                santos borre
25                 Senne Lynen                 senne lynen
26               Skelly Alvero               skelly alvero

============================================================
  TSG Hoffenheim  —  SF sin salario:

        player  minutesPlayed
0  Tim Drexler            573

  CG plantilla completa:

                 player          player_norm
0       Andrej Kramaric      andrej kramaric
1           Anton Stach          anton stach
2         Attila Szalai        attila szalai
3         Bambasé Conté        bambase conte
4         David Jurásek        david jurasek
5         Dennis Geiger        dennis geiger
6     Diadié Samassékou    diadie samassekou
7       Finn Ole Becker      finn ole becker
8    Florian Grillitsch   florian grillitsch
9        Grischa Prömel       grischa promel
10          Ihlas Bebou          ihlas bebou
11  John Anthony Brooks  john anthony brooks
12      Joshua Quarshie      joshua quarshie
13       Julian Justvan       julian justvan
14          Kasim Adams          kasim adams
15       Kevin Akpoguma       kevin akpoguma
16           Kevin Vogt           kevin vogt
17         Luca Philipp         luca philipp
18           Marco John           marco john
19        Marius Bülter        marius bulter
20        Max Moerstedt        max moerstedt
21     Maximilian Beier     maximilian beier
22       Mergim Berisha       mergim berisha
23          Nahuel Noll          nahuel noll
24       Oliver Baumann       oliver baumann
25           Ozan Kabak           ozan kabak
26      Pavel Kaderabek      pavel kaderabek
27          Robert Skov          robert skov
28        Stanley Nsoki        stanley nsoki
29          Tom Bischof          tom bischof
30         Umut Tohumcu         umut tohumcu
31        Wout Weghorst        wout weghorst

============================================================
  VfB Stuttgart  —  SF sin salario:

                 player  minutesPlayed
0            Borna Sosa             44
1  Samuele Di Benedetto             12
2                 Silas            909

  CG plantilla completa:

                    player             player_norm
0          Alexander Nübel         alexander nubel
1           Angelo Stiller          angelo stiller
2          Anthony Rouault         anthony rouault
3           Atakan Karazor          atakan karazor
4            Chris Führich           chris fuhrich
5         Dan-Axel Zagadou        dan axel zagadou
6              Deniz Undav             deniz undav
7            Dennis Seimen           dennis seimen
8              Enzo Millot             enzo millot
9           Fabian Bredlow          fabian bredlow
10          Florian Schock          florian schock
11         Genki Haraguchi         genki haraguchi
12                Gil Dias                gil dias
13              Hiroki Ito              hiroki ito
14          Jamie Leweling          jamie leweling
15          Josha Vagnoman          josha vagnoman
16         Jovan Milosevic         jovan milosevic
17           Laurin Ulrich           laurin ulrich
18       Leonidas Stergiou       leonidas stergiou
19           Lilian Egloff           lilian egloff
20            Luca Raimund            luca raimund
21          Mahmoud Dahoud          mahmoud dahoud
22  Maximilian Mittelstädt  maximilian mittelstadt
23          Nikolas Nartey          nikolas nartey
24          Pascal Stenzel          pascal stenzel
25         Roberto Massimo         roberto massimo
26         Serhou Guirassy         serhou guirassy
27    Silas Katompa Mvumpa    silas katompa mvumpa
28       Thomas Kastanaras       thomas kastanaras
29          Waldemar Anton          waldemar anton
30         Woo-yeong Jeong         woo yeong jeong

============================================================
  VfL Bochum 1848  —  SF sin salario:

         player  minutesPlayed
0  Simon Zoller             45

  CG plantilla completa:

                     player              player_norm
0                Agon Elezi               agon elezi
1             Andreas Luthe            andreas luthe
2           Anthony Losilla          anthony losilla
3                  Bernardo                 bernardo
4   Christopher Antwi-Adjei  christopher antwi adjei
5           Cristian Gamboa          cristian gamboa
6             Danilo Soares            danilo soares
7             Erhan Masovic            erhan masovic
8            Felix Passlack           felix passlack
9         Gonçalo Paciência        goncalo paciencia
10              Ivan Ordets              ivan ordets
11          Jordi Osei-Tutu          jordi osei tutu
12      Keven Schlotterbeck      keven schlotterbeck
13             Kevin Stöger             kevin stoger
14           Lukas Daschner           lukas daschner
15              Lys Mousset              lys mousset
16           Manuel Riemann           manuel riemann
17            Mats Pannewig            mats pannewig
18               Matus Bero               matus bero
19        Maximilian Wittek        maximilian wittek
20            Michael Esser            michael esser
21           Mohammed Tolba           mohammed tolba
22    Moritz-Broni Kwarteng    moritz broni kwarteng
23       Moritz Broschinski       moritz broschinski
24           Moritz Römling           moritz romling
25            Niclas Thiede            niclas thiede
26              Noah Loosli              noah loosli
27        Patrick Osterhage        patrick osterhage
28          Philipp Förster          philipp forster
29          Philipp Hofmann          philipp hofmann
30             Takuma Asano             takuma asano
31              Tim Oermann              tim oermann

============================================================
  VfL Wolfsburg  —  SF sin salario:

               player  minutesPlayed
0       Bennit Bröger             10
1  Kofi Jeremy Amoako              2

  CG plantilla completa:

                player         player_norm
0            Amin Sarr           amin sarr
1        Aster Vranckx       aster vranckx
2       Cédric Zesiger      cedric zesiger
3    Dzenan Pejcinovic   dzenan pejcinovic
4          Felix Lange         felix lange
5       Jakub Kaminski      jakub kaminski
6        Joakim Maehle       joakim maehle
7           Jonas Wind          jonas wind
8        Kevin Behrens       kevin behrens
9        Kevin Paredes       kevin paredes
10      Kilian Fischer      kilian fischer
11       Koen Casteels       koen casteels
12         Lovro Majer         lovro majer
13        Lukas Nmecha        lukas nmecha
14    Mattias Svanberg    mattias svanberg
15     Maxence Lacroix     maxence lacroix
16   Maximilian Arnold   maximilian arnold
17         Moritz Jenz         moritz jenz
18       Nicolas Cozza       nicolas cozza
19      Niklas Klinger      niklas klinger
20      Patrick Wimmer      patrick wimmer
21        Pavao Pervan        pavao pervan
22     Philipp Schulze     philipp schulze
23          Ridle Baku          ridle baku
24             Rogério             rogerio
25  Sebastiaan Bornauw  sebastiaan bornauw
26         Tiago Tomás         tiago tomas
27      Ulysses Llanez      ulysses llanez
28        Vaclav Cerny        vaclav cerny
29    Yannick Gerhardt    yannick gerhardt

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('silas', 'vfb stuttgart'): ('silas katompa mvumpa', 'vfb stuttgart'),
    ('iago borduchi','fc augsburg'):('iago',('fc augsburg'))
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 2

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: silas (vfb stuttgart) → silas katompa mvumpa (vfb stuttgart)
✅ Match manual aplicado: iago borduchi (fc augsburg) → iago (fc augsburg)

Tras matches manuales: 464/494 (93.9%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_germany_2324.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_germany_2324.csv
   Jugadores totales:  494
   Con salario:        464
   Sin salario (NaN):  30
   Columnas:           121