# 03 · Join Sofascore + Capology — Germany Bundesliga 20/21

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2020/21 de Bundesliga alemana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_germany_2021.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_germany_2021.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  496 jugadores | 116 columnas
Capology:   552 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   1 fc koln
   1 fc union berlin
   1 fsv mainz 05
   bayer 04 leverkusen
   borussia m gladbach
   fc augsburg
   fc bayern munchen
   fc schalke 04
   hertha bsc
   holstein kiel
   rb leipzig
   sc freiburg
   sv werder bremen
   tsg hoffenheim
   vfb stuttgart
   vfl wolfsburg

En Capology pero no en Sofascore:
   augsburg
   bayer leverkusen
   bayern munich
   freiburg
   hertha berlin
   hoffenheim
   koln
   leipzig
   mainz
   monchengladbach
   schalke 04
   stuttgart
   union berlin
   werder bremen
   wolfsburg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'augsburg':'fc augsburg',
            'bayer leverkusen':'bayer 04 leverkusen',
            'bayern munich':'fc bayern munchen',
            'freiburg':'sc freiburg',
            'hertha berlin':'hertha bsc',
            'hoffenheim':'tsg hoffenheim',
            'koln':'1 fc koln',
            'leipzig':'rb leipzig',
            'mainz':'1 fsv mainz 05',
            'monchengladbach':'borussia m gladbach',
            'schalke 04':'fc schalke 04',
            'stuttgart':'vfb stuttgart',
            'union berlin':'1 fc union berlin',
            'werder bremen':'sv werder bremen',
            'wolfsburg':'vfl wolfsburg'                          
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 445/496 (89.7%)
Sin emparejar: 51

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          12
Revisión media    (0.75 ≤ score < 0.90):   9
Revisión estricta (0.50 ≤ score < 0.75):   17
Revisión muy est. (score < 0.50):           12

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf                 team            cg_match  score
29  Alfreð Finnbogason          FC Augsburg  alfred finnbogason  0.971
7    Alexander Sørloth           RB Leipzig   alexander sorloth  0.970
19    Dimitris Limnios           1. FC Köln   dimitrios limnios  0.970
35   Frederik Sørensen           1. FC Köln   frederik sorensen  0.970
8      Frederik Rønnow        FC Schalke 04     frederik ronnow  0.966
5      Rafał Gikiewicz          FC Augsburg     rafal gikiewicz  0.966
16     Łukasz Piszczek    Borussia Dortmund     lukasz piszczek  0.966
14      Bartosz Białek        VfL Wolfsburg      bartosz bialek  0.963
13      Levin Öztunalı      1. FSV Mainz 05      levin oztunali  0.963
0       Elias Boerdner  Eintracht Frankfurt       elias bordner  0.963
11         Evan Ndicka  Eintracht Frankfurt        evan n dicka  0.957
23    Niko Giesselmann   1. FC Union Berlin      niko gieelmann  0.933

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
43,Noah Joel Sarenren Bazee,FC Augsburg,noah sarenren bazee,0.884
32,Jan Luca Schuler,FC Schalke 04,luca schuler,0.857
15,Anderson-Lenda Lucoqui,Arminia Bielefeld,anderson lucoqui,0.842
22,Jóan Edmundsson,Arminia Bielefeld,joan simun edmundsson,0.833
48,Matondo-Merveille Papela,1. FSV Mainz 05,merveille papela,0.800
9,Leandro Barreiro,1. FSV Mainz 05,leandro barreiro martins,0.800
4,Stefan Ortega,Arminia Bielefeld,stefan ortega moreno,0.788
12,Mateu Morey,Borussia Dortmund,mateu morey bauza,0.786
18,Pierre Kunde,1. FSV Mainz 05,pierre kunde malong,0.774

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 9 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf               team              cg_match  score
6          John Brooks      VfL Wolfsburg   john anthony brooks  0.733
28  Johannes Eggestein   SV Werder Bremen  maximilian eggestein  0.632
21           Victor Sá      VfL Wolfsburg           joao victor  0.600
17      Joshua Zirkzee  FC Bayern München        joshua kimmich  0.571
49        Mikail Maden      FC Schalke 04        michael langer  0.538
44       Jonas Dirkner         Hertha BSC         lukas klunter  0.538
31   Philipp Bargfrede   SV Werder Bremen            ilia gruev  0.519
24      Nishan Burkart        SC Freiburg         janik haberer  0.519
27       Florian Flick      FC Schalke 04        kilian ludewig  0.519
46      Marten Winkler         Hertha BSC         omar alderete  0.519
30  Henning Matriciani      FC Schalke 04         levent mercan  0.516
33   Christopher Scott  FC Bayern München        chris richards  0.516
1       Josip Stanišić  FC Bayern München        joshua kimmich  0.500
42    Michaël Cuisance  FC Bayern München          manuel neuer  0.500
36      Mohamed Sankoh      VfB Stuttgart        maxime awoudja  0.500
39       Davy Klaassen   SV Werder Bremen           davie selke  0.500
20        Mehmet Aydın      FC Schalke 04         levent mercan  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['john brooks',
                    'victor sa'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 2

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

            player_sf                 team              cg_match  score
3       Blendi Idrizi        FC Schalke 04          benito raman  0.480
10      Iago Borduchi          FC Augsburg          dion berisha  0.480
34   Dennis Borkowski           RB Leipzig             dani olmo  0.480
47  Vasilios Pavlidis        FC Schalke 04     goncalo paciencia  0.471
37    Emrehan Gedikli  Bayer 04 Leverkusen          demarai gray  0.444
40    Anthony Modeste           1. FC Köln     ron robert zieler  0.438
26     Tolu Arokodare           1. FC Köln             timo horn  0.435
25  Jonas Michelbrink           Hertha BSC      javairo dilrosun  0.424
41        Eren Dinkçi     SV Werder Bremen         romano schmid  0.417
38      Jimmy Kaparos        FC Schalke 04           timo becker  0.417
45       Lukas Petkov          FC Augsburg          laszlo benes  0.417
2               Silas        VfB Stuttgart  silas katompa mvumpa  0.400

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = ['silas'

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 1

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 469/496 (94.6%)
Sin salario:     27

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 27

,player,team,minutesPlayed,appearances,goals,assists
0,Anthony Modeste,1. FC Köln,215,8,0,0
1,Tolu Arokodare,1. FC Köln,114,10,0,0
2,Emrehan Gedikli,Bayer 04 Leverkusen,24,1,0,0
3,Iago Borduchi,FC Augsburg,1564,18,1,1
4,Lukas Petkov,FC Augsburg,3,1,0,0
5,Joshua Zirkzee,FC Bayern München,92,3,0,0
6,Josip Stanišić,FC Bayern München,90,1,0,0
7,Christopher Scott,FC Bayern München,32,2,0,0
8,Michaël Cuisance,FC Bayern München,18,1,0,0
9,Mehmet Aydın,FC Schalke 04,501,6,0,0
10,Florian Flick,FC Schalke 04,360,4,1,0
11,Blendi Idrizi,FC Schalke 04,241,3,1,0
12,Henning Matriciani,FC Schalke 04,23,1,0,0
13,Jimmy Kaparos,FC Schalke 04,17,1,0,0
14,Mikail Maden,FC Schalke 04,5,1,0,0
15,Vasilios Pavlidis,FC Schalke 04,1,1,0,0
16,Jonas Michelbrink,Hertha BSC,37,2,0,0
17,Jonas Dirkner,Hertha BSC,15,1,0,0
18,Marten Winkler,Hertha BSC,1,1,0,0
19,Joshua Mees,Holstein Kiel,10,1,0,0
20,Dennis Borkowski,RB Leipzig,10,2,0,0
21,Nishan Burkart,SC Freiburg,14,1,0,0
22,Davy Klaassen,SV Werder Bremen,225,3,0,0
23,Eren Dinkçi,SV Werder Bremen,124,8,1,0
24,Johannes Eggestein,SV Werder Bremen,31,2,0,0
25,Philipp Bargfrede,SV Werder Bremen,26,1,0,0
26,Mohamed Sankoh,VfB Stuttgart,16,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  1. FC Köln  —  SF sin salario:

            player  minutesPlayed
0  Anthony Modeste            215
1   Tolu Arokodare            114

  CG plantilla completa:

                 player          player_norm
0         Benno Schmitz        benno schmitz
1     Christian Clemens    christian clemens
2     Dimitrios Limnios    dimitrios limnios
3      Dominick Drexler     dominick drexler
4         Ellyes Skhiri        ellyes skhiri
5       Elvis Rexhbecaj      elvis rexhbecaj
6       Emmanuel Dennis      emmanuel dennis
7         Florian Kainz        florian kainz
8     Frederik Sörensen    frederik sorensen
9         Ismail Jakobs        ismail jakobs
10        Jan Thielmann        jan thielmann
11          Jannes Horn          jannes horn
12         Jens Castrop         jens castrop
13         João Queirós         joao queiros
14         Jonas Hector         jonas hector
15           Jorge Meré           jorge mere
16         Julian Krahl         julian krahl
17    Kingsley Ehizibue    kingsley ehizibue
18          Marco Höger          marco hoger
19          Marius Wolf          marius wolf
20          Marvin Obuz          marvin obuz
21            Max Meyer            max meyer
22      Noah Katterbach      noah katterbach
23          Ondrej Duda          ondrej duda
24       Rafael Czichos       rafael czichos
25       Robert Voloder       robert voloder
26    Ron-Robert Zieler    ron robert zieler
27          Salih Özcan          salih ozcan
28  Sava-Arangel Cestic  sava arangel cestic
29   Sebastiaan Bornauw   sebastiaan bornauw
30  Sebastian Andersson  sebastian andersson
31         Tim Lemperle         tim lemperle
32            Timo Horn            timo horn

============================================================
  Bayer 04 Leverkusen  —  SF sin salario:

            player  minutesPlayed
0  Emrehan Gedikli             24

  CG plantilla completa:

                   player            player_norm
0     Aleksandar Dragovic    aleksandar dragovic
1             Cem Türkmen            cem turkmen
2        Charles Aránguiz       charles aranguiz
3        Daley Sinkgraven       daley sinkgraven
4            Demarai Gray           demarai gray
5          Edmond Tapsoba         edmond tapsoba
6       Exequiel Palacios      exequiel palacios
7           Florian Wirtz          florian wirtz
8        Jeremie Frimpong       jeremie frimpong
9            Jonathan Tah           jonathan tah
10  Julian Baumgartlinger  julian baumgartlinger
11        Karim Bellarabi        karim bellarabi
12         Kerem Demirbay         kerem demirbay
13            Lars Bender            lars bender
14          Lennart Grill          lennart grill
15            Leon Bailey            leon bailey
16           Lucas Alario           lucas alario
17         Lukas Hradecky         lukas hradecky
18        Mitchell Weiser        mitchell weiser
19           Moussa Diaby           moussa diaby
20           Nadiem Amiri           nadiem amiri
21            Niklas Lomb            niklas lomb
22          Patrik Schick          patrik schick
23               Paulinho               paulinho
24             Samed Onur             samed onur
25         Santiago Arias         santiago arias
26            Sven Bender            sven bender
27    Timothy Fosu-Mensah    timothy fosu mensah
28             Tin Jedvaj             tin jedvaj
29                Wendell                wendell

============================================================
  FC Augsburg  —  SF sin salario:

          player  minutesPlayed
0  Iago Borduchi           1564
1   Lukas Petkov              3

  CG plantilla completa:

                   player            player_norm
0      Alfred Finnbogason     alfred finnbogason
1              André Hahn             andre hahn
2         Benjamin Leneis        benjamin leneis
3           Carlos Gruezo          carlos gruezo
4        Daniel Caligiuri       daniel caligiuri
5            Dion Berisha           dion berisha
6             Felix Götze            felix gotze
7          Felix Uduokhai         felix uduokhai
8   Florian Niederlechner  florian niederlechner
9          Fredrik Jensen         fredrik jensen
10                   Iago                   iago
11            Jan Morávek            jan moravek
12     Jeffrey Gouweleeuw     jeffrey gouweleeuw
13        Julian Schieber        julian schieber
14           Lászlo Bénes           laszlo benes
15          Mads Pedersen          mads pedersen
16          Marco Richter          marco richter
17            Marek Suchy            marek suchy
18    Michael Gregoritsch    michael gregoritsch
19    Noah Sarenren Bazee    noah sarenren bazee
20        Rafal Gikiewicz        rafal gikiewicz
21           Rani Khedira           rani khedira
22     Raphael Framberger     raphael framberger
23           Reece Oxford           reece oxford
24           Robert Gumny           robert gumny
25           Ruben Vargas           ruben vargas
26             Tim Civeja             tim civeja
27          Tobias Strobl          tobias strobl
28           Tomas Koubek           tomas koubek

============================================================
  FC Bayern München  —  SF sin salario:

              player  minutesPlayed
0  Christopher Scott             32
1     Joshua Zirkzee             92
2     Josip Stanišić             90
3   Michaël Cuisance             18

  CG plantilla completa:

                      player               player_norm
0            Alexander Nübel           alexander nubel
1            Alphonso Davies           alphonso davies
2             Angelo Stiller            angelo stiller
3            Benjamin Pavard           benjamin pavard
4                 Bouna Sarr                bouna sarr
5           Bright Arrey-Mbi          bright arrey mbi
6             Chris Richards            chris richards
7           Corentin Tolisso          corentin tolisso
8           Daniels Ontuzans          daniels ontuzans
9                David Alaba               david alaba
10             Douglas Costa             douglas costa
11  Eric Maxim Choupo-Moting  eric maxim choupo moting
12             Jamal Musiala             jamal musiala
13             Javi Martínez             javi martinez
14            Jérôme Boateng            jerome boateng
15            Joshua Kimmich            joshua kimmich
16            Kingsley Coman            kingsley coman
17               Leon Dajaku               leon dajaku
18             Leon Goretzka             leon goretzka
19                Leroy Sané                leroy sane
20           Lucas Hernández           lucas hernandez
21              Manuel Neuer              manuel neuer
22                 Marc Roca                 marc roca
23               Niklas Süle               niklas sule
24        Robert Lewandowski        robert lewandowski
25      Ron-Thorben Hoffmann      ron thorben hoffmann
26              Serge Gnabry              serge gnabry
27            Tanguy Nianzou            tanguy nianzou
28             Thomas Müller             thomas muller
29              Tiago Dantas              tiago dantas

============================================================
  FC Schalke 04  —  SF sin salario:

               player  minutesPlayed
0       Blendi Idrizi            241
1       Florian Flick            360
2  Henning Matriciani             23
3       Jimmy Kaparos             17
4        Mehmet Aydın            501
5        Mikail Maden              5
6   Vasilios Pavlidis              1

  CG plantilla completa:

                 player          player_norm
0          Ahmed Kutucu         ahmed kutucu
1     Alessandro Schöpf    alessandro schopf
2           Amine Harit          amine harit
3       Bastian Oczipka      bastian oczipka
4          Benito Raman         benito raman
5    Benjamin Stambouli   benjamin stambouli
6          Can Bozdogan         can bozdogan
7       Frederik Rönnow      frederik ronnow
8     Gonçalo Paciência    goncalo paciencia
9          Hamza Mendyl         hamza mendyl
10     Kerim Calhanoglu     kerim calhanoglu
11       Kilian Ludewig       kilian ludewig
12  Klaas-Jan Huntelaar  klaas jan huntelaar
13        Levent Mercan        levent mercan
14         Luca Schuler         luca schuler
15         Malick Thiaw         malick thiaw
16             Mark Uth             mark uth
17      Matija Nastasic      matija nastasic
18        Matthew Hoppe        matthew hoppe
19       Michael Langer       michael langer
20       Nabil Bentaleb       nabil bentaleb
21     Nassim Boujellab     nassim boujellab
22        Nick Taitague        nick taitague
23       Omar Mascarell       omar mascarell
24           Ozan Kabak           ozan kabak
25        Rabbi Matondo        rabbi matondo
26        Ralf Fährmann        ralf fahrmann
27           Salif Sané           salif sane
28       Sead Kolasinac       sead kolasinac
29     Shkodran Mustafi     shkodran mustafi
30     Steven Skrzybski     steven skrzybski
31          Suat Serdar          suat serdar
32          Timo Becker          timo becker
33       Vedad Ibisevic       vedad ibisevic
34              William              william

============================================================
  Hertha BSC  —  SF sin salario:

              player  minutesPlayed
0      Jonas Dirkner             15
1  Jonas Michelbrink             37
2     Marten Winkler              1

  CG plantilla completa:

                    player             player_norm
0       Alexander Schwolow      alexander schwolow
1           Daishawn Redan          daishawn redan
2           Dedryck Boyata          dedryck boyata
3       Deyovaisio Zeefuik      deyovaisio zeefuik
4           Dodi Lukebakio          dodi lukebakio
5             Eduard Löwen            eduard lowen
6         Javairô Dilrosun        javairo dilrosun
7           Jessic Ngankam          jessic ngankam
8             Jhon Córdoba            jhon cordoba
9       Jordan Torunarigha      jordan torunarigha
10        Krzysztof Piatek        krzysztof piatek
11               Luca Netz               luca netz
12           Lucas Tousart           lucas tousart
13           Lukas Klünter           lukas klunter
14           Márton Dárdai           marton dardai
15     Marvin Plattenhardt     marvin plattenhardt
16           Matheus Cunha           matheus cunha
17           Mathew Leckie           mathew leckie
18        Mattéo Guendouzi        matteo guendouzi
19  Maximilian Mittelstädt  maximilian mittelstadt
20        Nemanja Radonjic        nemanja radonjic
21            Niklas Stark            niklas stark
22             Nils Körber             nils korber
23           Omar Alderete           omar alderete
24           Peter Pekarik           peter pekarik
25           Rune Jarstein           rune jarstein
26            Sami Khedira            sami khedira
27      Santiago Ascacíbar      santiago ascacibar
28         Vladimir Darida         vladimir darida

============================================================
  Holstein Kiel  —  SF sin salario:

        player  minutesPlayed
0  Joshua Mees             10

  CG plantilla completa:

Empty DataFrame
Columns: [player, player_norm]
Index: []

============================================================
  RB Leipzig  —  SF sin salario:

             player  minutesPlayed
0  Dennis Borkowski             10

  CG plantilla completa:

                player         player_norm
0    Alexander Sörloth   alexander sorloth
1       Amadou Haidara      amadou haidara
2             Angeliño            angelino
3    Benjamin Henrichs   benjamin henrichs
4   Christopher Nkunku  christopher nkunku
5            Dani Olmo           dani olmo
6      Dayot Upamecano     dayot upamecano
7   Dominik Szoboszlai  dominik szoboszlai
8        Emil Forsberg       emil forsberg
9     Fabrice Hartmann    fabrice hartmann
10      Hee-chan Hwang      hee chan hwang
11     Ibrahima Konaté     ibrahima konate
12         Joscha Wosz         joscha wosz
13      Josep Martínez      josep martinez
14     Justin Kluivert     justin kluivert
15         Kevin Kampl         kevin kampl
16       Konrad Laimer       konrad laimer
17     Lazar Samardzic     lazar samardzic
18   Lukas Klostermann   lukas klostermann
19  Marcel Halstenberg  marcel halstenberg
20     Marcel Sabitzer     marcel sabitzer
21       Nordi Mukiele       nordi mukiele
22       Péter Gulácsi       peter gulacsi
23   Philipp Tschauner   philipp tschauner
24       Tim Schreiber       tim schreiber
25         Tyler Adams         tyler adams
26         Willi Orban         willi orban
27      Yussuf Poulsen      yussuf poulsen

============================================================
  SC Freiburg  —  SF sin salario:

           player  minutesPlayed
0  Nishan Burkart             14

  CG plantilla completa:

                 player          player_norm
0          Amir Abrashi         amir abrashi
1   Baptiste Santamaria  baptiste santamaria
2       Benjamin Uphoff      benjamin uphoff
3       Carlo Boukhalfa      carlo boukhalfa
4       Chang-hoon Kwon      chang hoon kwon
5      Christian Günter     christian gunter
6      Dominique Heintz     dominique heintz
7     Ermedin Demirovic    ermedin demirovic
8        Florian Müller       florian muller
9              Guus Til             guus til
10        Janik Haberer        janik haberer
11      Jonathan Schmid      jonathan schmid
12  Keven Schlotterbeck  keven schlotterbeck
13      Lino Tempelmann      lino tempelmann
14           Luca Itter           luca itter
15          Lucas Höler          lucas holer
16         Lukas Kübler         lukas kubler
17         Manuel Gulde         manuel gulde
18         Mark Flekken         mark flekken
19        Niclas Thiede        niclas thiede
20       Nicolas Höfler       nicolas hofler
21        Nils Petersen        nils petersen
22     Philipp Lienhart     philipp lienhart
23        Roland Sallai        roland sallai
24       Vincenzo Grifo       vincenzo grifo
25      Woo-yeong Jeong      woo yeong jeong
26        Yannik Keitel        yannik keitel

============================================================
  SV Werder Bremen  —  SF sin salario:

               player  minutesPlayed
0       Davy Klaassen            225
1         Eren Dinkçi            124
2  Johannes Eggestein             31
3   Philipp Bargfrede             26

  CG plantilla completa:

                        player                 player_norm
0               Christian Groß               christian gro
1                  Davie Selke                 davie selke
2   Eduardo Dos Santos Haesler  eduardo dos santos haesler
3                    Felix Agu                   felix agu
4                   Ilia Gruev                  ilia gruev
5             Jean Manuel Mbom            jean manuel mbom
6                Jiri Pavlenka               jiri pavlenka
7                 Josh Sargent                josh sargent
8                Kevin Möhwald               kevin mohwald
9         Leonardo Bittencourt        leonardo bittencourt
10         Ludwig Augustinsson         ludwig augustinsson
11                Marco Friedl                marco friedl
12        Maximilian Eggestein        maximilian eggestein
13            Michael Zetterer            michael zetterer
14             Milos Veljkovic             milos veljkovic
15               Milot Rashica               milot rashica
16              Nick Woltemade              nick woltemade
17             Niclas Füllkrug             niclas fullkrug
18            Niklas Moisander            niklas moisander
19                 Ömer Toprak                 omer toprak
20           Oscar Schönfelder           oscar schonfelder
21               Patrick Erras               patrick erras
22               Romano Schmid               romano schmid
23             Stefanos Kapino             stefanos kapino
24                Tahith Chong                tahith chong
25      Theodor Gebre Selassie      theodor gebre selassie
26                  Yuya Osako                  yuya osako

============================================================
  VfB Stuttgart  —  SF sin salario:

           player  minutesPlayed
0  Mohamed Sankoh             16

  CG plantilla completa:

                     player              player_norm
0                    Aílton                   ailton
1           Antonis Aidonis          antonis aidonis
2            Atakan Karazor           atakan karazor
3                Borna Sosa               borna sosa
4              Clinton Mola             clinton mola
5             Daniel Didavi            daniel didavi
6           Darko Churlinov          darko churlinov
7               Erik Thommy              erik thommy
8            Fabian Bredlow           fabian bredlow
9            Gonzalo Castro           gonzalo castro
10             Gregor Kobel             gregor kobel
11      Hamadi Al Ghaddioui      hamadi al ghaddioui
12               Jens Grahl               jens grahl
13  Konstantinos Mavropanos  konstantinos mavropanos
14            Lilian Egloff            lilian egloff
15                Luca Mack                luca mack
16        Marc Oliver Kempf        marc oliver kempf
17          Marcin Kaminski          marcin kaminski
18          Mateo Klimowicz          mateo klimowicz
19           Maxime Awoudja           maxime awoudja
20               Momo Cissé               momo cisse
21         Naouirou Ahamada         naouirou ahamada
22         Nicolás González         nicolas gonzalez
23             Orel Mangala             orel mangala
24           Pascal Stenzel           pascal stenzel
25          Philipp Förster          philipp forster
26          Philipp Klement          philipp klement
27          Roberto Massimo          roberto massimo
28           Sasa Kalajdzic           sasa kalajdzic
29     Silas Katompa Mvumpa     silas katompa mvumpa
30         Tanguy Coulibaly         tanguy coulibaly
31           Waldemar Anton           waldemar anton
32              Wataru Endo              wataru endo

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('iago borduchi','fc augsburg'):('iago',('fc augsburg'))
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: iago borduchi (fc augsburg) → iago (fc augsburg)

Tras matches manuales: 470/496 (94.8%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_germany_2021.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_germany_2021.csv
   Jugadores totales:  496
   Con salario:        470
   Sin salario (NaN):  26
   Columnas:           121