# 03 · Join Sofascore + Capology — Germany Bundesliga 24/25

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2024/25 de Bundesliga alemana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_germany_2425.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_germany_2425.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  481 jugadores | 116 columnas
Capology:   566 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   1 fc heidenheim
   1 fc union berlin
   1 fsv mainz 05
   bayer 04 leverkusen
   borussia m gladbach
   fc augsburg
   fc bayern munchen
   fc st pauli
   rb leipzig
   sc freiburg
   sv werder bremen
   tsg hoffenheim
   vfb stuttgart
   vfl bochum 1848
   vfl wolfsburg

En Capology pero no en Sofascore:
   augsburg
   bayer leverkusen
   bayern munich
   bochum
   freiburg
   heidenheim
   hoffenheim
   leipzig
   mainz
   monchengladbach
   st pauli
   stuttgart
   union berlin
   werder bremen
   wolfsburg

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'augsburg':'fc augsburg',
            'bayer leverkusen':'bayer 04 leverkusen',
            'bayern munich':'fc bayern munchen',
            'bochum':'vfl bochum 1848',
            'freiburg':'sc freiburg',
            'heidenheim':'1 fc heidenheim',
            'hoffenheim':'tsg hoffenheim',
            'leipzig':'rb leipzig',
            'mainz':'1 fsv mainz 05',
            'monchengladbach':'borussia m gladbach',
            'st pauli':'fc st pauli',
            'stuttgart':'vfb stuttgart',
            'union berlin':'1 fc union berlin',
            'werder bremen':'sv werder bremen',
            'wolfsburg':'vfl wolfsburg'
            
            
            

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 453/481 (94.2%)
Sin emparejar: 28

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          6
Revisión media    (0.75 ≤ score < 0.90):   5
Revisión estricta (0.50 ≤ score < 0.75):   9
Revisión muy est. (score < 0.50):           8

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

           player_sf                team           cg_match  score
4    Frederik Rønnow  1. FC Union Berlin    frederik ronnow  0.966
20    Stanley N'Soki      TSG Hoffenheim      stanley nsoki  0.963
17     Adam Dźwigała        FC St. Pauli      adam dzwigala  0.960
8       Joakim Mæhle       VfL Wolfsburg      joakim maehle  0.917
9   Giorgos Masouras     VfL Bochum 1848  georgios masouras  0.909
2        Lasse Riess     1. FSV Mainz 05          lasse rie  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf                 team             cg_match  score
16         Joseph Scally  Borussia M'gladbach           joe scally  0.870
7   Victor Okoh Boniface  Bayer 04 Leverkusen      victor boniface  0.857
5          Jamie Gittens    Borussia Dortmund  jamie bynoe gittens  0.812
10     Andu Yobel Kelati        Holstein Kiel          andu kelati  0.786
15    Haktab Omar Traore     1. FC Heidenheim          omar traore  0.759

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 5 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf                 team                 cg_match  score
18       Mads Roerslev        VfL Wolfsburg  mads roerslev rasmussen  0.722
14          Gift Orban       TSG Hoffenheim      gift emmanuel orban  0.690
6          Jeff Chabot        VfB Stuttgart            julian chabot  0.667
12  Junior Dina Ebimbe  Eintracht Frankfurt              eric ebimbe  0.621
23         Arne Engels          FC Augsburg               arne maier  0.571
27    Jonah Kusi-Asare    FC Bayern München            jamal musiala  0.552
11       Roland Sallai          SC Freiburg        kiliann sildillia  0.533
3       Hennes Behrens       TSG Hoffenheim            dennis geiger  0.519
25   Kacper Kościerski      VfL Bochum 1848       moritz broschinski  0.514

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mads roerslev',
                    'gift orban',
                    'jeff chabot',
                    'junior dina ebimbe',


]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 4

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf                 team                cg_match  score
1         Mohamed Simakan           RB Leipzig          amadou haidara  0.483
21           Yannik Lührs    Borussia Dortmund               yan couto  0.476
26             Faik Sakar           RB Leipzig            antonio nusa  0.455
24            Ayman Azhil    Borussia Dortmund        maximilian beier  0.444
13           Robin Gosens   1. FC Union Berlin         yorbe vertessen  0.444
19             Noah Pesch  Borussia M'gladbach  yvandro borges sanches  0.438
22          Paul Hennrich       TSG Hoffenheim         pavel kaderabek  0.429
0   Tiago Pereira Cardoso  Borussia M'gladbach          moritz nicolas  0.400

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 468/481 (97.3%)
Sin salario:     13

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 13

,player,team,minutesPlayed,appearances,goals,assists
0,Robin Gosens,1. FC Union Berlin,90,1,0,0
1,Yannik Lührs,Borussia Dortmund,130,3,0,0
2,Ayman Azhil,Borussia Dortmund,23,1,0,0
3,Tiago Pereira Cardoso,Borussia M'gladbach,379,5,0,0
4,Noah Pesch,Borussia M'gladbach,9,1,0,0
5,Arne Engels,FC Augsburg,80,1,0,0
6,Jonah Kusi-Asare,FC Bayern München,2,1,0,0
7,Mohamed Simakan,RB Leipzig,55,1,0,0
8,Faik Sakar,RB Leipzig,1,1,0,0
9,Roland Sallai,SC Freiburg,44,2,0,0
10,Hennes Behrens,TSG Hoffenheim,28,1,0,0
11,Paul Hennrich,TSG Hoffenheim,11,1,0,0
12,Kacper Kościerski,VfL Bochum 1848,6,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  1. FC Union Berlin  —  SF sin salario:

         player  minutesPlayed
0  Robin Gosens             90

  CG plantilla completa:

                 player          player_norm
0    Alexander Schwolow   alexander schwolow
1      Aljoscha Kemlein     aljoscha kemlein
2        András Schäfer       andras schafer
3           Andrej Ilic          andrej ilic
4   Benedict Hollerbach  benedict hollerbach
5            Carl Klaus           carl klaus
6   Christopher Trimmel  christopher trimmel
7        Danilho Doekhi       danilho doekhi
8            David Preu           david preu
9           Diogo Leite          diogo leite
10      Frederik Rönnow      frederik ronnow
11         Ivan Prtajin         ivan prtajin
12        Janik Haberer        janik haberer
13    Jérôme Roussillon    jerome roussillon
14    Jordan Siebatcheu    jordan siebatcheu
15      Josip Juranovic      josip juranovic
16           Kevin Vogt           kevin vogt
17        Kevin Volland        kevin volland
18         László Bénes         laszlo benes
19     Leopold Querfeld     leopold querfeld
20        Lucas Tousart        lucas tousart
21       Marin Ljubicic       marin ljubicic
22  Oluwaseun Ogbemudia  oluwaseun ogbemudia
23         Rani Khedira         rani khedira
24          Robert Skov          robert skov
25           Tim Skarke           tim skarke
26            Tom Rothe            tom rothe
27      Woo-yeong Jeong      woo yeong jeong
28         Yannic Stein         yannic stein
29      Yorbe Vertessen      yorbe vertessen

============================================================
  Borussia Dortmund  —  SF sin salario:

         player  minutesPlayed
0   Ayman Azhil             23
1  Yannik Lührs            130

  CG plantilla completa:

                 player          player_norm
0       Alexander Meyer      alexander meyer
1        Almugera Kabar       almugera kabar
2    Carney Chukwuemeka   carney chukwuemeka
3         Cole Campbell        cole campbell
4       Daniel Svensson      daniel svensson
5         Donyell Malen        donyell malen
6              Emre Can             emre can
7          Felix Nmecha         felix nmecha
8          Filippo Mané         filippo mane
9        Giovanni Reyna       giovanni reyna
10         Gregor Kobel         gregor kobel
11  Jamie Bynoe-Gittens  jamie bynoe gittens
12        Julian Brandt        julian brandt
13       Julian Ryerson       julian ryerson
14    Julien Duranville    julien duranville
15        Karim Adeyemi        karim adeyemi
16         Kjell Wätjen         kjell watjen
17         Marcel Lotka         marcel lotka
18      Marcel Sabitzer      marcel sabitzer
19     Maximilian Beier     maximilian beier
20   Nico Schlotterbeck   nico schlotterbeck
21          Niklas Süle          niklas sule
22          Pascal Groß           pascal gro
23      Ramy Bensebaini      ramy bensebaini
24          Salih Özcan          salih ozcan
25     Sébastien Haller     sebastien haller
26      Serhou Guirassy      serhou guirassy
27     Silas Ostrzinski     silas ostrzinski
28   Soumaïla Coulibaly   soumaila coulibaly
29       Waldemar Anton       waldemar anton
30            Yan Couto            yan couto
31    Youssoufa Moukoko    youssoufa moukoko

============================================================
  Borussia M'gladbach  —  SF sin salario:

                  player  minutesPlayed
0             Noah Pesch              9
1  Tiago Pereira Cardoso            379

  CG plantilla completa:

                    player             player_norm
0            Alassane Pléa           alassane plea
1         Charles Herrmann        charles herrmann
2          Fabio Chiarodia         fabio chiarodia
3          Florian Neuhaus         florian neuhaus
4           Franck Honorat          franck honorat
5         Grant-Leon Ranos        grant leon ranos
6           Jan Olschowsky          jan olschowsky
7               Joe Scally              joe scally
8              Jonas Omlin             jonas omlin
9             Julian Weigl            julian weigl
10            Kevin Stöger            kevin stoger
11              Ko Itakura              ko itakura
12               Luca Netz               luca netz
13           Lukas Ullrich           lukas ullrich
14        Marvin Friedrich        marvin friedrich
15          Moritz Nicolas          moritz nicolas
16         Nathan N'Goumou         nathan n goumou
17             Nico Elvedi             nico elvedi
18           Niklas Swider           niklas swider
19          Philipp Sander          philipp sander
20              Robin Hack              robin hack
21             Rocco Reitz             rocco reitz
22             Shio Fukuda             shio fukuda
23           Stefan Lainer           stefan lainer
24         Tim Kleindienst         tim kleindienst
25           Tobias Sippel           tobias sippel
26          Tomas Cvancara          tomas cvancara
27  Yvandro Borges Sanches  yvandro borges sanches

============================================================
  FC Augsburg  —  SF sin salario:

        player  minutesPlayed
0  Arne Engels             80

  CG plantilla completa:

                   player            player_norm
0   Alexis Claude-Maurice  alexis claude maurice
1              Arne Maier             arne maier
2          Cédric Zesiger         cedric zesiger
3       Chrislain Matsima      chrislain matsima
4            Daniel Klein           daniel klein
5    Dimitrios Giannoulis   dimitrios giannoulis
6         Elvis Rexhbecaj        elvis rexhbecaj
7             Finn Dahmen            finn dahmen
8            Frank Onyeka           frank onyeka
9          Fredrik Jensen         fredrik jensen
10        Henri Koudossou        henri koudossou
11     Jeffrey Gouweleeuw     jeffrey gouweleeuw
12    Keven Schlotterbeck    keven schlotterbeck
13        Kristijan Jakic        kristijan jakic
14          Mads Pedersen          mads pedersen
15      Mahmut Kücüksahin      mahmut kucuksahin
16            Marius Wolf            marius wolf
17         Masaya Okugawa         masaya okugawa
18       Maximilian Bauer       maximilian bauer
19         Mergim Berisha         mergim berisha
20             Mert Kömür             mert komur
21        Nathanaël Mbuku        nathanael mbuku
22      Nediljko Labrovic      nediljko labrovic
23          Noahkai Banks          noahkai banks
24          Phillip Tietz          phillip tietz
25           Reece Oxford           reece oxford
26           Robert Gumny           robert gumny
27           Rubén Vargas           ruben vargas
28         Samuel Essende         samuel essende
29           Steve Mounié           steve mounie
30         Tim Breithaupt         tim breithaupt
31         Yusuf Kabadayi         yusuf kabadayi

============================================================
  FC Bayern München  —  SF sin salario:

             player  minutesPlayed
0  Jonah Kusi-Asare              2

  CG plantilla completa:

                 player          player_norm
0            Adam Aznou           adam aznou
1   Aleksandar Pavlovic  aleksandar pavlovic
2       Alexander Nübel      alexander nubel
3       Alphonso Davies      alphonso davies
4    Arijon Ibrahimovic   arijon ibrahimovic
5        Bryan Zaragoza       bryan zaragoza
6         Daniel Peretz        daniel peretz
7       Dayot Upamecano      dayot upamecano
8             Eric Dier            eric dier
9       Gabriel Vidovic      gabriel vidovic
10           Harry Kane           harry kane
11           Hiroki Ito           hiroki ito
12        Jamal Musiala        jamal musiala
13        João Palhinha        joao palhinha
14          Jonas Urbig          jonas urbig
15       Joshua Kimmich       joshua kimmich
16       Josip Stanisic       josip stanisic
17       Kingsley Coman       kingsley coman
18        Konrad Laimer        konrad laimer
19        Leon Goretzka        leon goretzka
20           Leroy Sané           leroy sane
21         Manuel Neuer         manuel neuer
22           Mathys Tel           mathys tel
23        Michael Olise        michael olise
24          Min-jae Kim          min jae kim
25    Nestory Irankunda    nestory irankunda
26     Noël Aséko Nkili     noel aseko nkili
27    Raphaël Guerreiro    raphael guerreiro
28           Sacha Boey           sacha boey
29         Serge Gnabry         serge gnabry
30         Sven Ulreich         sven ulreich
31       Tarek Buchmann       tarek buchmann
32        Thomas Müller        thomas muller

============================================================
  RB Leipzig  —  SF sin salario:

            player  minutesPlayed
0       Faik Sakar              1
1  Mohamed Simakan             55

  CG plantilla completa:

                    player             player_norm
0           Amadou Haidara          amadou haidara
1              André Silva             andre silva
2             Antonio Nusa            antonio nusa
3         Arthur Vermeeren        arthur vermeeren
4          Assan Ouédraogo         assan ouedraogo
5        Benjamin Henrichs       benjamin henrichs
6           Benjamin Sesko          benjamin sesko
7          Castello Lukeba         castello lukeba
8    Christoph Baumgartner   christoph baumgartner
9               David Raum              david raum
10  El Chadaille Bitshiabu  el chadaille bitshiabu
11             Eljif Elmas             eljif elmas
12             Kevin Kampl             kevin kampl
13       Kosta Nedeljkovic       kosta nedeljkovic
14        Leopold Zingerle        leopold zingerle
15             Loïs Openda             lois openda
16       Lukas Klostermann       lukas klostermann
17    Lutsharel Geertruida    lutsharel geertruida
18     Maarten Vandevoordt     maarten vandevoordt
19         Nicolas Seiwald         nicolas seiwald
20           Péter Gulácsi           peter gulacsi
21              Ridle Baku              ridle baku
22            Tidiam Gomis            tidiam gomis
23             Viggo Gebel             viggo gebel
24             Willi Orbán             willi orban
25          Xaver Schlager          xaver schlager
26             Xavi Simons             xavi simons
27          Yussuf Poulsen          yussuf poulsen

============================================================
  SC Freiburg  —  SF sin salario:

          player  minutesPlayed
0  Roland Sallai             44

  CG plantilla completa:

                  player           player_norm
0            Bruno Ogbus           bruno ogbus
1       Christian Günter      christian gunter
2     Daniel-Kofi Kyereh    daniel kofi kyereh
3            Eren Dinkçi           eren dinkci
4        Florent Muslija       florent muslija
5         Florian Müller        florian muller
6       Jan-Niklas Beste      jan niklas beste
7            Jannik Huth           jannik huth
8         Johan Manzambi        johan manzambi
9          Jordy Makengo         jordy makengo
10          Junior Adamu          junior adamu
11       Kenneth Schmidt       kenneth schmidt
12     Kiliann Sildillia     kiliann sildillia
13           Lucas Höler           lucas holer
14          Lukas Kübler          lukas kubler
15          Manuel Gulde          manuel gulde
16       Matthias Ginter       matthias ginter
17       Max Rosenfelder       max rosenfelder
18  Maximilian Eggestein  maximilian eggestein
19    Maximilian Philipp    maximilian philipp
20           Merlin Röhl           merlin rohl
21   Michael Gregoritsch   michael gregoritsch
22        Nicolas Höfler        nicolas hofler
23          Noah Atubolu          noah atubolu
24        Noah Weißhaupt         noah weihaupt
25     Patrick Osterhage     patrick osterhage
26      Philipp Lienhart      philipp lienhart
27            Ritsu Doan            ritsu doan
28        Vincenzo Grifo        vincenzo grifo

============================================================
  TSG Hoffenheim  —  SF sin salario:

           player  minutesPlayed
0  Hennes Behrens             28
1   Paul Hennrich             11

  CG plantilla completa:

                 player          player_norm
0           Adam Hlozek          adam hlozek
1       Alexander Prass      alexander prass
2       Andrej Kramaric      andrej kramaric
3           Anton Stach          anton stach
4         Arthur Chaves        arthur chaves
5         Attila Szalai        attila szalai
6       Bazoumana Touré      bazoumana toure
7      Christopher Lenz     christopher lenz
8         David Jurásek        david jurasek
9           David Mokwa          david mokwa
10        Dennis Geiger        dennis geiger
11    Diadié Samassékou    diadie samassekou
12     Erencan Yardımcı       erencan yardmc
13      Finn Ole Becker      finn ole becker
14   Florian Grillitsch   florian grillitsch
15     Florian Micheler     florian micheler
16  Gift Emmanuel Orban  gift emmanuel orban
17       Grischa Prömel       grischa promel
18      Haris Tabakovic      haris tabakovic
19          Ihlas Bebou          ihlas bebou
20   Jacob Bruun Larsen   jacob bruun larsen
21           Jakob Busk           jakob busk
22       Kevin Akpoguma       kevin akpoguma
23         Leo Østigård          leo stigard
24         Luca Philipp         luca philipp
25      Lúkas Petersson      lukas petersson
26           Marco John           marco john
27        Marius Bülter        marius bulter
28        Max Moerstedt        max moerstedt
29       Mergim Berisha       mergim berisha
30       Oliver Baumann       oliver baumann
31           Ozan Kabak           ozan kabak
32      Pavel Kaderabek      pavel kaderabek
33         Robin Hranac         robin hranac
34        Stanley Nsoki        stanley nsoki
35          Tim Drexler          tim drexler
36          Tom Bischof          tom bischof
37         Umut Tohumcu         umut tohumcu
38     Valentin Gendrey     valentin gendrey

============================================================
  VfL Bochum 1848  —  SF sin salario:

              player  minutesPlayed
0  Kacper Kościerski              6

  CG plantilla completa:

                   player            player_norm
0              Agon Elezi             agon elezi
1             Aliou Baldé            aliou balde
2         Anthony Losilla        anthony losilla
3                Bernardo               bernardo
4         Cristian Gamboa        cristian gamboa
5             Dani de Wit            dani de wit
6           Erhan Masovic          erhan masovic
7          Felix Passlack         felix passlack
8       Georgios Masouras      georgios masouras
9         Gerrit Holtmann        gerrit holtmann
10       Ibrahima Sissoko       ibrahima sissoko
11            Ivan Ordets            ivan ordets
12            Jakov Medic            jakov medic
13           Koji Miyoshi           koji miyoshi
14         Lennart Koerdt         lennart koerdt
15         Lukas Daschner         lukas daschner
16         Manuel Riemann         manuel riemann
17          Mats Pannewig          mats pannewig
18             Matus Bero             matus bero
19      Maximilian Wittek      maximilian wittek
20         Mohammed Tolba         mohammed tolba
21  Moritz-Broni Kwarteng  moritz broni kwarteng
22     Moritz Broschinski     moritz broschinski
23            Myron Boadu            myron boadu
24            Niklas Jahn            niklas jahn
25            Noah Loosli            noah loosli
26         Patrick Drewes         patrick drewes
27             Paul Grave             paul grave
28        Philipp Hofmann        philipp hofmann
29           Samuel Bamba           samuel bamba
30            Tim Oermann            tim oermann
31              Timo Horn              timo horn
32              Tom Krauß               tom krau

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 468/481 (97.3%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_germany_2425.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_germany_2425.csv
   Jugadores totales:  481
   Con salario:        468
   Sin salario (NaN):  13
   Columnas:           121