# 03 · Join Sofascore + Capology — Italy Serie A 21/22

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2021/22 de Serie A italiana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_italy_2122.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_italy_2122.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  609 jugadores | 116 columnas
Capology:   660 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   inter
   milan

En Capology pero no en Sofascore:
   ac milan
   inter milan

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'ac milan':'milan',
            'inter milan':'inter'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 542/609 (89.0%)
Sin emparejar: 67

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          12
Revisión media    (0.75 ≤ score < 0.90):   4
Revisión estricta (0.50 ≤ score < 0.75):   29
Revisión muy est. (score < 0.50):           22

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf           team              cg_match  score
48  Bartłomiej Drągowski     Fiorentina  bartlomiej dragowski  0.974
29    Albert Guðmundsson          Genoa    albert gudmundsson  0.971
47     Paweł Jaroszyński    Salernitana     pawel jaroszynski  0.970
51      Arnór Sigurðsson        Venezia      arnor sigurdsson  0.968
18      Paweł Dawidowicz  Hellas Verona      pawel dawidowicz  0.968
1       Łukasz Skorupski        Bologna      lukasz skorupski  0.968
34          Leo Østigård          Genoa          leo ostigard  0.957
9      Aleksei Miranchuk       Atalanta     aleksey miranchuk  0.941
14         Filip Đuričić       Sassuolo        filip djuricic  0.923
35          Joakim Mæhle       Atalanta         joakim maehle  0.917
2            Milan Đurić    Salernitana          milan djuric  0.909
6             Simon Kjær          Milan           simon kjaer  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

            player_sf      team                 cg_match  score
17    Salvador Ferrer    Spezia             salva ferrer  0.889
66  Giorgio Cittadini  Atalanta         giorgio scalvini  0.788
39     Andrea Favilli     Genoa          andrea masiello  0.759
8      Wilfried Singo    Torino  wilfried stephane singo  0.757

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['giorgio cittadini',
                      'andrea favilli'

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 2 | Excluidos: 2

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf         team               cg_match  score
5        João Pedro Galvão     Cagliari             joao pedro  0.741
61        Nicola Bagnolini      Bologna         nicola sansone  0.733
0      Riccardo Stivanello      Bologna      riccardo orsolini  0.667
28             Jeff Chabot    Sampdoria          julian chabot  0.667
3           Frank Anguissa       Napoli   andre zambo anguissa  0.647
33    Francesco Di Mariano      Venezia        francesco forte  0.629
44        Alessandro Russo  Salernitana          antonio russo  0.621
19            Cedric Gondo  Salernitana     federico bonazzoli  0.600
24          Niklas Pyyhtiä      Bologna          nicolas viola  0.593
32          Mattia Zanotti        Inter          matias vecino  0.593
55          Martin Palumbo     Juventus          adrien rabiot  0.593
65            Matías Soulé     Juventus           mattia perin  0.583
53    Christos Kourfalidis     Cagliari        christian oliva  0.571
7               Igor Júlio   Fiorentina                   igor  0.571
25  Hilmir Rafn Mikaelsson      Venezia  ottar magnus karlsson  0.558
13           Samir Caetano      Udinese                  samir  0.556
49           Mario Perrone  Salernitana          diego perotti  0.538
16        Gianluca Gaetano       Napoli         andrea petagna  0.533
37          Simone Pafundi      Udinese       manuel gasparini  0.533
21           Fabio Miretti     Juventus             kaio jorge  0.522
15           Stefano Okaka      Udinese             jan kubala  0.522
27          Martín Cáceres     Cagliari          simone aresti  0.519
20        Cristian Volpato         Roma        bryan cristante  0.516
62       Filippo Distefano   Fiorentina         louis munteanu  0.516
50              Marley Aké     Juventus             moise kean  0.500
46             Samuel Mráz       Spezia      aurelien nguiamba  0.500
38          Ebenezer Annan      Bologna     federico santander  0.500
12            Andrei Moțoc  Salernitana       andrea schiavone  0.500
54            Luca Vignali       Spezia           kelvin amian  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['joao pedro galvao',
                    'jeff chabot',
                    'frank anguissa',
                    'igor julio',
                    'samir caetano'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 5

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf           team             cg_match  score
42     Tommaso De Nipoti       Atalanta     marco sportiello  0.485
40       Nicolas Galazzi        Venezia   pasquale mazzocchi  0.485
64        Riccardo Pinzi        Udinese      marco ballarini  0.483
31   Filippo Terracciano  Hellas Verona  federico ceccherini  0.474
57     Giovanni Crociata         Empoli    guglielmo vicario  0.471
58      Antonio Raimondo        Bologna   gianmarco cangiano  0.471
56     Samuel Di Carmine  Hellas Verona        adrien tameze  0.467
36     Cristiano Ronaldo       Juventus        juan cuadrado  0.467
30       Kacper Urbański        Bologna      francesco bardi  0.467
52          Patrick Leal        Venezia       mattia caldara  0.462
22         Diego Coppola  Hellas Verona        fabio depaoli  0.462
23           Aleš Matějů        Venezia      francesco forte  0.462
60  Dimitrios Keramitsis           Roma          pietro boer  0.452
11     Takehiro Tomiyasu        Bologna       kevin bonifazi  0.452
10       Moustapha Cissé       Atalanta         josip ilicic  0.444
43  Julian Kristoffersen    Salernitana         luca ranieri  0.438
45           Sam Lammers       Atalanta         remo freuler  0.435
41              Issa Bah        Venezia      michael svoboda  0.435
26       Alassane Sidibe       Atalanta        hans hateboer  0.429
4            Wisdom Amey        Bologna    nicolas dominguez  0.429
59          Luigi Samele       Sassuolo     giacomo satalino  0.429
63           Luca Stanga          Milan        sandro tonali  0.417

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 561/609 (92.1%)
Sin salario:     48

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 48

,player,team,minutesPlayed,appearances,goals,assists
0,Sam Lammers,Atalanta,44,2,0,0
1,Moustapha Cissé,Atalanta,41,3,1,0
2,Alassane Sidibe,Atalanta,9,1,0,0
3,Tommaso De Nipoti,Atalanta,9,1,0,0
4,Giorgio Cittadini,Atalanta,2,2,0,0
5,Antonio Raimondo,Bologna,75,1,0,0
6,Wisdom Amey,Bologna,72,1,0,0
7,Riccardo Stivanello,Bologna,45,1,0,0
8,Kacper Urbański,Bologna,45,1,0,0
9,Ebenezer Annan,Bologna,24,1,0,0
10,Niklas Pyyhtiä,Bologna,18,1,0,0
11,Takehiro Tomiyasu,Bologna,9,1,0,0
12,Nicola Bagnolini,Bologna,2,1,0,0
13,Martín Cáceres,Cagliari,833,14,1,1
14,Christos Kourfalidis,Cagliari,25,2,0,0
15,Giovanni Crociata,Empoli,14,1,0,0
16,Filippo Distefano,Fiorentina,1,1,0,0
17,Andrea Favilli,Genoa,36,1,0,0
18,Diego Coppola,Hellas Verona,249,4,0,0
19,Samuel Di Carmine,Hellas Verona,35,1,0,0
20,Filippo Terracciano,Hellas Verona,10,1,0,0
21,Mattia Zanotti,Inter,8,1,0,0
22,Fabio Miretti,Juventus,322,6,0,0
23,Marley Aké,Juventus,77,4,0,0
24,Cristiano Ronaldo,Juventus,31,1,0,0
25,Martin Palumbo,Juventus,12,1,0,0
26,Matías Soulé,Juventus,4,2,0,0
27,Luca Stanga,Milan,2,1,0,0
28,Gianluca Gaetano,Napoli,19,2,0,0
29,Cristian Volpato,Roma,42,3,1,0
30,Dimitrios Keramitsis,Roma,1,1,0,0
31,Cedric Gondo,Salernitana,704,14,1,0
32,Andrei Moțoc,Salernitana,90,1,0,0
33,Alessandro Russo,Salernitana,28,1,0,0
34,Mario Perrone,Salernitana,13,1,0,0
35,Julian Kristoffersen,Salernitana,9,1,0,0
36,Luigi Samele,Sassuolo,3,2,0,1
37,Luca Vignali,Spezia,91,2,0,0
38,Samuel Mráz,Spezia,52,2,0,0
39,Simone Pafundi,Udinese,22,1,0,0
40,Stefano Okaka,Udinese,20,2,0,1
41,Riccardo Pinzi,Udinese,1,1,0,0
42,Aleš Matějů,Venezia,730,9,0,1
43,Francesco Di Mariano,Venezia,63,1,0,0
44,Hilmir Rafn Mikaelsson,Venezia,17,1,0,0
45,Nicolas Galazzi,Venezia,17,1,0,0
46,Issa Bah,Venezia,9,1,0,0
47,Patrick Leal,Venezia,9,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Atalanta  —  SF sin salario:

              player  minutesPlayed
0    Alassane Sidibe              9
1  Giorgio Cittadini              2
2    Moustapha Cissé             41
3        Sam Lammers             44
4  Tommaso De Nipoti              9

  CG plantilla completa:

                player         player_norm
0    Aleksey Miranchuk   aleksey miranchuk
1       Berat Djimsiti      berat djimsiti
2        Bryan Cabezas       bryan cabezas
3    Davide Zappacosta   davide zappacosta
4         Duván Zapata        duvan zapata
5   Federico Mattiello  federico mattiello
6      Francesco Rossi     francesco rossi
7     Giorgio Scalvini    giorgio scalvini
8    Giuseppe Pezzella   giuseppe pezzella
9        Hans Hateboer       hans hateboer
10        Jérémie Boga        jeremie boga
11       Joakim Maehle       joakim maehle
12  José Luis Palomino  jose luis palomino
13        Josip Ilicic        josip ilicic
14          Juan Musso          juan musso
15         Luis Muriel         luis muriel
16    Marco Sportiello    marco sportiello
17       Mario Pasalic       mario pasalic
18      Marten de Roon      marten de roon
19       Matteo Lovato       matteo lovato
20      Matteo Pessina      matteo pessina
21       Merih Demiral       merih demiral
22        Rafael Tolói        rafael toloi
23        Remo Freuler        remo freuler
24     Roberto Piccoli     roberto piccoli
25        Robin Gosens        robin gosens
26  Ruslan Malinovskyi  ruslan malinovskyi
27    Teun Koopmeiners    teun koopmeiners
28    Valentin Mihaila    valentin mihaila

============================================================
  Bologna  —  SF sin salario:

                player  minutesPlayed
0     Antonio Raimondo             75
1       Ebenezer Annan             24
2      Kacper Urbański             45
3     Nicola Bagnolini              2
4       Niklas Pyyhtiä             18
5  Riccardo Stivanello             45
6    Takehiro Tomiyasu              9
7          Wisdom Amey             72

  CG plantilla completa:

                  player           player_norm
0           Aaron Hickey          aaron hickey
1         Adama Soumaoro        adama soumaoro
2     Andreas Skov Olsen    andreas skov olsen
3          Arthur Theate         arthur theate
4           Denso Kasius          denso kasius
5       Diego Falcinelli      diego falcinelli
6        Emanuel Vignato       emanuel vignato
7     Federico Santander    federico santander
8        Francesco Bardi       francesco bardi
9         Gabriele Corbo        gabriele corbo
10            Gary Medel            gary medel
11    Gianmarco Cangiano    gianmarco cangiano
12        Ibrahima Mbaye        ibrahima mbaye
13        Jerdy Schouten        jerdy schouten
14        Kevin Bonifazi        kevin bonifazi
15      Kingsley Michael      kingsley michael
16  Lorenzo De Silvestri  lorenzo de silvestri
17            Luis Binks            luis binks
18            Luis Rojas            luis rojas
19      Lukasz Skorupski      lukasz skorupski
20           Marco Molla           marco molla
21      Marko Arnautovic      marko arnautovic
22      Mattias Svanberg      mattias svanberg
23      Michel Aebischer      michel aebischer
24        Mitchell Dijks        mitchell dijks
25           Musa Barrow           musa barrow
26           Musa Juwara           musa juwara
27        Nicola Sansone        nicola sansone
28     Nicolás Domínguez     nicolas dominguez
29         Nicolas Viola         nicolas viola
30     Riccardo Orsolini     riccardo orsolini
31       Roberto Soriano       roberto soriano
32  Sydney van Hooijdonk  sydney van hooijdonk

============================================================
  Cagliari  —  SF sin salario:

                 player  minutesPlayed
0  Christos Kourfalidis             25
1        Martín Cáceres            833

  CG plantilla completa:

                     player              player_norm
0                Adam Obert               adam obert
1            Alberto Grassi           alberto grassi
2         Alessandro Deiola        alessandro deiola
3            Alessio Cragno           alessio cragno
4            Andrea Carboni           andrea carboni
5           Boris Radunović          boris radunovic
6   Charalampos Lykogiannis  charalampos lykogiannis
7           Christian Oliva          christian oliva
8                   Dalbert                  dalbert
9               Damir Ceter              damir ceter
10          Daniele Baselli          daniele baselli
11             Diego Farias             diego farias
12              Diego Godín              diego godin
13        Edoardo Goldaniga        edoardo goldaniga
14           Gabriele Zappa           gabriele zappa
15           Gastón Pereiro           gaston pereiro
16           Giorgio Altare           giorgio altare
17               João Pedro               joao pedro
18              Keita Baldé              keita balde
19          Kevin Strootman          kevin strootman
20       Leonardo Pavoletti       leonardo pavoletti
21          Luca Ceppitelli          luca ceppitelli
22            Luca Gagliano            luca gagliano
23                Marko Rog                marko rog
24            Matteo Lovato            matteo lovato
25           Nahitan Nández           nahitan nandez
26             Paolo Faragò             paolo farago
27          Raoul Bellanova          raoul bellanova
28             Razvan Marin             razvan marin
29       Riccardo Ladinetti       riccardo ladinetti
30    Sebastian Walukiewicz    sebastian walukiewicz
31            Simone Aresti            simone aresti

============================================================
  Empoli  —  SF sin salario:

              player  minutesPlayed
0  Giovanni Crociata             14

  CG plantilla completa:

                   player            player_norm
0        Andrea La Mantia       andrea la mantia
1        Andrea Pinamonti       andrea pinamonti
2          Ardian Ismajli         ardian ismajli
3          Emmanuel Ekong         emmanuel ekong
4          Fabiano Parisi         fabiano parisi
5   Federico Di Francesco  federico di francesco
6      Filippo Bandinelli     filippo bandinelli
7       Guglielmo Vicario      guglielmo vicario
8          Iwo Kaczmarski         iwo kaczmarski
9           Jacopo Furlan          jacopo furlan
10       Kristjan Asllani       kristjan asllani
11             Leo Stulac             leo stulac
12       Leonardo Mancuso       leonardo mancuso
13         Liam Henderson         liam henderson
14        Liberato Cacace        liberato cacace
15        Lorenzo Tonelli        lorenzo tonelli
16          Marco Benassi          marco benassi
17            Mattia Viti            mattia viti
18          Nedim Bajrami          nedim bajrami
19           Nicolas Haas           nicolas haas
20        Patrick Cutrone        patrick cutrone
21       Petar Stojanovic       petar stojanovic
22      Riccardo Fiamozzi      riccardo fiamozzi
23     Riccardo Marchizza     riccardo marchizza
24           Samir Ujkani           samir ujkani
25        Samuele Damiani        samuele damiani
26          Samuele Ricci          samuele ricci
27     Sebastiano Luperto     sebastiano luperto
28       Simone Romagnoli       simone romagnoli
29       Szymon Zurkowski       szymon zurkowski
30       Tommaso Baldanzi       tommaso baldanzi
31          Valerio Verre          valerio verre

============================================================
  Fiorentina  —  SF sin salario:

              player  minutesPlayed
0  Filippo Distefano              1

  CG plantilla completa:

                   player            player_norm
0           Aleksa Terzic          aleksa terzic
1       Aleksandr Kokorin      aleksandr kokorin
2       Alessandro Bianco      alessandro bianco
3           Alfred Duncan          alfred duncan
4        Álvaro Odriozola       alvaro odriozola
5          Antonio Rosati         antonio rosati
6           Arthur Cabral          arthur cabral
7    Bartlomiej Dragowski   bartlomiej dragowski
8       Cristiano Biraghi      cristiano biraghi
9          Dusan Vlahovic         dusan vlahovic
10           Erick Pulgar           erick pulgar
11    Federico Brancolini    federico brancolini
12    Gaetano Castrovilli    gaetano castrovilli
13    Giacomo Bonaventura    giacomo bonaventura
14                   Igor                   igor
15         Jonathan Ikoné         jonathan ikone
16          José Callejón          jose callejon
17       Krzysztof Piatek       krzysztof piatek
18         Lorenzo Venuti         lorenzo venuti
19         Louis Munteanu         louis munteanu
20  Lucas Martínez Quarta  lucas martinez quarta
21         Lucas Torreira         lucas torreira
22          Marco Benassi          marco benassi
23        Matija Nastasic        matija nastasic
24     Michele Cerofolini     michele cerofolini
25       Nicolás González       nicolas gonzalez
26      Nikola Milenkovic      nikola milenkovic
27     Pietro Terracciano     pietro terracciano
28      Riccardo Saponara      riccardo saponara
29        Riccardo Sottil        riccardo sottil
30         Sofyan Amrabat         sofyan amrabat
31          Youssef Maleh          youssef maleh

============================================================
  Genoa  —  SF sin salario:

           player  minutesPlayed
0  Andrea Favilli             36

  CG plantilla completa:

                player         player_norm
0      Abdoulaye Touré     abdoulaye toure
1        Adrian Semper       adrian semper
2   Albert Gudmundsson  albert gudmundsson
3     Aleksander Buksa    aleksander buksa
4      Andrea Cambiaso     andrea cambiaso
5      Andrea Masiello     andrea masiello
6         Caleb Ekuban        caleb ekuban
7      Davide Biraschi     davide biraschi
8    Domenico Criscito   domenico criscito
9   Federico Marchetti  federico marchetti
10      Felipe Caicedo      felipe caicedo
11    Filippo Melegoni    filippo melegoni
12      Flavio Bianchi      flavio bianchi
13   Francesco Cassata   francesco cassata
14        Goran Pandev        goran pandev
15             Hernani             hernani
16    Ivan Radovanovic    ivan radovanovic
17       Johan Vásquez       johan vasquez
18       Kelvin Yeboah       kelvin yeboah
19       Laurens Serpe       laurens serpe
20    Lennart Czyborra    lennart czyborra
21        Leo Östigard        leo ostigard
22  Lorenzo Andrenacci  lorenzo andrenacci
23    Manolo Portanova    manolo portanova
24         Mattia Bani         mattia bani
25       Mattia Destro       mattia destro
26        Milan Badelj        milan badelj
27       Mohamed Fares       mohamed fares
28     Morten Frendrup     morten frendrup
29        Nadiem Amiri        nadiem amiri
30      Nicolò Rovella      nicolo rovella
31   Nikola Maksimovic   nikola maksimovic
32      Pablo Galdames      pablo galdames
33     Paolo Ghiglione     paolo ghiglione
34  Riccardo Calafiori  riccardo calafiori
35     Roberto Piccoli     roberto piccoli
36    Salvatore Sirigu    salvatore sirigu
37        Silvan Hefti        silvan hefti
38     Stefano Sabelli     stefano sabelli
39     Stefano Sturaro     stefano sturaro
40       Valon Behrami       valon behrami
41        Yayah Kallon        yayah kallon
42    Zinho Vanheusden    zinho vanheusden

============================================================
  Hellas Verona  —  SF sin salario:

                player  minutesPlayed
0        Diego Coppola            249
1  Filippo Terracciano             10
2    Samuel Di Carmine             35

  CG plantilla completa:

                 player          player_norm
0         Adrien Tamèze        adrien tameze
1    Alessandro Berardi   alessandro berardi
2         Antonin Barak        antonin barak
3       Antonino Ragusa      antonino ragusa
4          Bogdan Jocic         bogdan jocic
5          Bosko Sutalo         bosko sutalo
6          Daniel Bessa         daniel bessa
7         Darko Lazovic        darko lazovic
8        Davide Faraoni       davide faraoni
9         Fabio Depaoli        fabio depaoli
10  Federico Ceccherini  federico ceccherini
11  Giangiacomo Magnani  giangiacomo magnani
12     Gianluca Caprari     gianluca caprari
13    Gianluca Frabotta    gianluca frabotta
14     Giovanni Simeone     giovanni simeone
15            Ivan Ilic            ivan ilic
16          Ivor Pandur          ivor pandur
17        Kevin Lasagna        kevin lasagna
18          Kevin Rüegg          kevin ruegg
19         Koray Günter         koray gunter
20      Lorenzo Montipò      lorenzo montipo
21        Martin Hongla        martin hongla
22    Mateusz Praszelik    mateusz praszelik
23   Matteo Cancellieri   matteo cancellieri
24        Mattia Chiesa        mattia chiesa
25           Mert Cetin           mert cetin
26        Miguel Veloso        miguel veloso
27        Nicolò Casale        nicolo casale
28       Nikola Kalinic       nikola kalinic
29    Panagiotis Retsos    panagiotis retsos
30     Pawel Dawidowicz     pawel dawidowicz

============================================================
  Inter  —  SF sin salario:

           player  minutesPlayed
0  Mattia Zanotti              8

  CG plantilla completa:

                 player          player_norm
0    Aleksandar Kolarov   aleksandar kolarov
1    Alessandro Bastoni   alessandro bastoni
2           Alex Cordaz          alex cordaz
3        Alexis Sánchez       alexis sanchez
4      Andrea Ranocchia     andrea ranocchia
5          Arturo Vidal         arturo vidal
6     Christian Eriksen    christian eriksen
7     Danilo D'Ambrosio    danilo d ambrosio
8       Denzel Dumfries      denzel dumfries
9            Edin Dzeko           edin dzeko
10      Facundo Colidio      facundo colidio
11     Federico Dimarco     federico dimarco
12       Felipe Caicedo       felipe caicedo
13       Gabriel Brazão       gabriel brazao
14     Hakan Calhanoglu     hakan calhanoglu
15           Ionut Radu           ionut radu
16         Ivan Perisic         ivan perisic
17       Joaquín Correa       joaquin correa
18     Lautaro Martínez     lautaro martinez
19     Marcelo Brozovic     marcelo brozovic
20      Martín Satriano      martin satriano
21        Matías Vecino        matias vecino
22       Matteo Darmian       matteo darmian
23       Milan Skriniar       milan skriniar
24       Nicolò Barella       nicolo barella
25  Roberto Gagliardini  roberto gagliardini
26         Robin Gosens         robin gosens
27     Samir Handanovic     samir handanovic
28       Stefan de Vrij       stefan de vrij
29        Stefano Sensi        stefano sensi

============================================================
  Juventus  —  SF sin salario:

              player  minutesPlayed
0  Cristiano Ronaldo             31
1      Fabio Miretti            322
2         Marley Aké             77
3     Martin Palumbo             12
4       Matías Soulé              4

  CG plantilla completa:

                   player            player_norm
0            Aaron Ramsey           aaron ramsey
1           Adrien Rabiot          adrien rabiot
2             Alex Sandro            alex sandro
3           Álvaro Morata          alvaro morata
4                  Arthur                 arthur
5         Carlo Pinsoglio        carlo pinsoglio
6          Daniele Rugani         daniele rugani
7                  Danilo                 danilo
8        Dejan Kulusevski       dejan kulusevski
9           Denis Zakaria          denis zakaria
10         Dusan Vlahovic         dusan vlahovic
11  Federico Bernardeschi  federico bernardeschi
12        Federico Chiesa        federico chiesa
13      Giorgio Chiellini      giorgio chiellini
14          Juan Cuadrado          juan cuadrado
15             Kaio Jorge             kaio jorge
16       Leonardo Bonucci       leonardo bonucci
17        Luca Pellegrini        luca pellegrini
18       Manuel Locatelli       manuel locatelli
19       Matthijs de Ligt       matthijs de ligt
20      Mattia De Sciglio      mattia de sciglio
21           Mattia Perin           mattia perin
22             Moise Kean             moise kean
23           Paulo Dybala           paulo dybala
24      Rodrigo Bentancur      rodrigo bentancur
25        Weston McKennie        weston mckennie
26      Wojciech Szczesny      wojciech szczesny

============================================================
  Milan  —  SF sin salario:

        player  minutesPlayed
0  Luca Stanga              2

  CG plantilla completa:

                 player          player_norm
0   Alessandro Florenzi  alessandro florenzi
1   Alessandro Plizzari  alessandro plizzari
2     Alessio Romagnoli    alessio romagnoli
3   Alexis Saelemaekers  alexis saelemaekers
4          Andrea Conti         andrea conti
5            Ante Rebic           ante rebic
6       Antonio Mirante      antonio mirante
7           Brahim Díaz          brahim diaz
8    Ciprian Tatarusanu   ciprian tatarusanu
9        Daniel Maldini       daniel maldini
10      Davide Calabria      davide calabria
11        Fikayo Tomori        fikayo tomori
12     Fodé Ballo-Touré     fode ballo toure
13        Franck Kessié        franck kessie
14      Ismaël Bennacer      ismael bennacer
15       Junior Messias       junior messias
16        Marko Lazetic        marko lazetic
17        Matteo Gabbia        matteo gabbia
18         Mike Maignan         mike maignan
19       Olivier Giroud       olivier giroud
20        Pierre Kalulu        pierre kalulu
21      Pietro Pellegri      pietro pellegri
22          Rade Krunic          rade krunic
23          Rafael Leão          rafael leao
24      Samu Castillejo      samu castillejo
25        Sandro Tonali        sandro tonali
26          Simon Kjaer          simon kjaer
27       Theo Hernández       theo hernandez
28     Tiemoué Bakayoko     tiemoue bakayoko
29   Zlatan Ibrahimovic   zlatan ibrahimovic

============================================================
  Napoli  —  SF sin salario:

             player  minutesPlayed
0  Gianluca Gaetano             19

  CG plantilla completa:

                  player           player_norm
0             Adam Ounas            adam ounas
1      Alessandro Zanoli     alessandro zanoli
2             Alex Meret            alex meret
3          Amir Rrahmani         amir rrahmani
4   André Zambo Anguissa  andre zambo anguissa
5         Andrea Petagna        andrea petagna
6          Axel Tuanzebe         axel tuanzebe
7           David Ospina          david ospina
8        Davide Marfella       davide marfella
9            Diego Demme           diego demme
10         Dries Mertens         dries mertens
11           Eljif Elmas           eljif elmas
12           Fabián Ruiz           fabian ruiz
13        Faouzi Ghoulam        faouzi ghoulam
14         Filippo Costa         filippo costa
15   Giovanni Di Lorenzo   giovanni di lorenzo
16        Hirving Lozano        hirving lozano
17            Juan Jesus            juan jesus
18     Kalidou Koulibaly     kalidou koulibaly
19         Kévin Malcuit         kevin malcuit
20  Konstantinos Manolas  konstantinos manolas
21       Lorenzo Insigne       lorenzo insigne
22             Mário Rui             mario rui
23       Matteo Politano       matteo politano
24       Piotr Zielinski       piotr zielinski
25     Stanislav Lobotka     stanislav lobotka
26        Victor Osimhen        victor osimhen

============================================================
  Roma  —  SF sin salario:

                 player  minutesPlayed
0      Cristian Volpato             42
1  Dimitrios Keramitsis              1

  CG plantilla completa:

                    player             player_norm
0   Ainsley Maitland-Niles  ainsley maitland niles
1         Alessio Riccardi        alessio riccardi
2           Amadou Diawara          amadou diawara
3            Borja Mayoral           borja mayoral
4          Bryan Cristante         bryan cristante
5           Bryan Reynolds          bryan reynolds
6             Carles Pérez            carles perez
7           Chris Smalling          chris smalling
8            Daniel Fuzato           daniel fuzato
9            Davide Santon           davide santon
10           Ebrima Darboe           ebrima darboe
11            Edoardo Bove            edoardo bove
12        Eldor Shomurodov        eldor shomurodov
13          Federico Fazio          federico fazio
14        Felix Afena-Gyan        felix afena gyan
15           Filippo Tripi           filippo tripi
16        Gianluca Mancini        gianluca mancini
17          Gonzalo Villar          gonzalo villar
18      Henrikh Mkhitaryan      henrikh mkhitaryan
19         Jordan Veretout         jordan veretout
20     Leonardo Spinazzola     leonardo spinazzola
21      Lorenzo Pellegrini      lorenzo pellegrini
22         Marash Kumbulla         marash kumbulla
23             Matías Viña             matias vina
24         Nicola Zalewski         nicola zalewski
25          Nicolò Zaniolo          nicolo zaniolo
26             Pietro Boer             pietro boer
27      Riccardo Calafiori      riccardo calafiori
28           Rick Karsdorp           rick karsdorp
29            Roger Ibañez            roger ibanez
30            Rui Patrício            rui patricio
31         Sérgio Oliveira         sergio oliveira
32     Stephan El Shaarawy     stephan el shaarawy
33           Steven Nzonzi           steven nzonzi
34           Tammy Abraham           tammy abraham

============================================================
  Salernitana  —  SF sin salario:

                 player  minutesPlayed
0      Alessandro Russo             28
1          Andrei Moțoc             90
2          Cedric Gondo            704
3  Julian Kristoffersen              9
4         Mario Perrone             13

  CG plantilla completa:

                  player           player_norm
0       Andrea Schiavone      andrea schiavone
1          Antonio Russo         antonio russo
2          Diego Perotti         diego perotti
3                Éderson               ederson
4        Edoardo Vergani       edoardo vergani
5           Emil Bohinen          emil bohinen
6     Federico Bonazzoli    federico bonazzoli
7         Federico Fazio        federico fazio
8    Filippo Delli Carri   filippo delli carri
9   Francesco Di Tacchio  francesco di tacchio
10         Franck Ribéry         franck ribery
11       Frédéric Veseli       frederic veseli
12     Grigoris Kastanos     grigoris kastanos
13       Guido Guerrieri       guido guerrieri
14      Ivan Radovanovic      ivan radovanovic
15     Jacopo De Matteis     jacopo de matteis
16              Joel Obi              joel obi
17     Lassana Coulibaly     lassana coulibaly
18      Leonardo Capezzi      leonardo capezzi
19          Luca Ranieri          luca ranieri
20            Luigi Sepe            luigi sepe
21           Luka Bogdan           luka bogdan
22           Lys Mousset           lys mousset
23     Mamadou Coulibaly     mamadou coulibaly
24        Matteo Ruggeri        matteo ruggeri
25                Mikael                mikael
26          Milan Djuric          milan djuric
27          Nadir Zortea          nadir zortea
28       Norbert Gyomber       norbert gyomber
29    Pasquale Mazzocchi    pasquale mazzocchi
30     Pawel Jaroszynski     pawel jaroszynski
31         Radu Dragusin         radu dragusin
32             Ramzi Aya             ramzi aya
33     Riccardo Gagliolo     riccardo gagliolo
34       Sedrick Kalombo       sedrick kalombo
35          Simone Verdi          simone verdi
36                  Simy                  simy
37     Stefan Strandberg     stefan strandberg
38             Vid Belec             vid belec
39     Vincenzo Fiorillo     vincenzo fiorillo
40        Wajdi Kechrida        wajdi kechrida

============================================================
  Sassuolo  —  SF sin salario:

         player  minutesPlayed
0  Luigi Samele              3

  CG plantilla completa:

                    player             player_norm
0            Abdou Harroui           abdou harroui
1          Andrea Consigli         andrea consigli
2              Brian Oddei             brian oddei
3          Davide Frattesi         davide frattesi
4         Domenico Berardi        domenico berardi
5        Edoardo Goldaniga       edoardo goldaniga
6     Emil Konradsen Ceide    emil konradsen ceide
7          Federico Peluso         federico peluso
8           Filip Djuricic          filip djuricic
9          Filippo Romagna         filippo romagna
10    Francesco Magnanelli    francesco magnanelli
11  Georgios Kyriakopoulos  georgios kyriakopoulos
12       Giacomo Raspadori       giacomo raspadori
13        Giacomo Satalino        giacomo satalino
14      Gian Marco Ferrari      gian marco ferrari
15         Gianluca Pegolo         gianluca pegolo
16       Gianluca Scamacca       gianluca scamacca
17         Grégoire Defrel         gregoire defrel
18     Hamed Junior Traorè     hamed junior traore
19            Jérémie Boga            jeremie boga
20           Jeremy Toljan           jeremy toljan
21              Kaan Ayhan              kaan ayhan
22        Matheus Henrique        matheus henrique
23            Maxime López            maxime lopez
24             Mert Müldür             mert muldur
25   Nicolás Schiappacasse   nicolas schiappacasse
26            Pedro Obiang            pedro obiang
27         Riccardo Ciervo         riccardo ciervo
28                 Rogério                 rogerio
29                    Ruan                    ruan
30          Vlad Chiriches          vlad chiriches

============================================================
  Spezia  —  SF sin salario:

         player  minutesPlayed
0  Luca Vignali             91
1   Samuel Mráz             52

  CG plantilla completa:

                player         player_norm
0           Aimar Sher          aimar sher
1       Arkadiusz Reca      arkadiusz reca
2    Aurélien Nguiamba   aurelien nguiamba
3        Daniele Verde       daniele verde
4        David Strelec       david strelec
5         Diego Zuppel        diego zuppel
6   Dimitrios Nikolaou  dimitrios nikolaou
7        Ebrima Colley       ebrima colley
8        Eddie Salcedo       eddie salcedo
9       Emmanuel Gyasi      emmanuel gyasi
10     Giulio Maggiore     giulio maggiore
11       Ivan Provedel       ivan provedel
12         Jacopo Sala         jacopo sala
13        Jakub Kiwior        jakub kiwior
14       Janis Antiste       janis antiste
15         Jeroen Zoet         jeroen zoet
16        Kelvin Amian        kelvin amian
17       Kevin Agudelo       kevin agudelo
18            Léo Sena            leo sena
19        M'Bala Nzola        m bala nzola
20        Martin Erlic        martin erlic
21      Mehdi Bourabia      mehdi bourabia
22      Niccolò Pietra      niccolo pietra
23      Nicolò Bertola      nicolo bertola
24         Petar Zovko         petar zovko
25       Petko Hristov       petko hristov
26           Rey Manaj           rey manaj
27        Salva Ferrer        salva ferrer
28      Simone Bastoni      simone bastoni
29      Suf Podgoreanu      suf podgoreanu
30    Viktor Kovalenko    viktor kovalenko

============================================================
  Udinese  —  SF sin salario:

           player  minutesPlayed
0  Riccardo Pinzi              1
1  Simone Pafundi             22
2   Stefano Okaka             20

  CG plantilla completa:

                 player          player_norm
0      Antonio Santurro     antonio santurro
1                  Beto                 beto
2         Bram Nuytinck        bram nuytinck
3         Brandon Soppy        brandon soppy
4       Daniele Padelli      daniele padelli
5        Destiny Udogie       destiny udogie
6   Fernando Forestieri  fernando forestieri
7        Filip Benkovic       filip benkovic
8       Gerard Deulofeu      gerard deulofeu
9      Ignacio Pussetto     ignacio pussetto
10    Ilija Nestorovski    ilija nestorovski
11        Isaac Success        isaac success
12           Jan Kubala           jan kubala
13  Jean-Victor Makengo  jean victor makengo
14  Jens Stryger Larsen  jens stryger larsen
15      Lazar Samardzic      lazar samardzic
16    Lukasz Teodorczyk    lukasz teodorczyk
17     Manuel Gasparini     manuel gasparini
18      Marco Ballarini      marco ballarini
19      Marco Silvestri      marco silvestri
20     Marvin Zeegelaar     marvin zeegelaar
21          Mato Jajalo          mato jajalo
22        Nahuel Molina        nahuel molina
23         Nehuén Pérez         nehuen perez
24           Pablo Marí           pablo mari
25          Petar Micin          petar micin
26      Roberto Pereyra      roberto pereyra
27        Rodrigo Becão        rodrigo becao
28                Samir                samir
29    Sebastien De Maio    sebastien de maio
30        Tolgay Arslan        tolgay arslan
31               Walace               walace

============================================================
  Venezia  —  SF sin salario:

                   player  minutesPlayed
0             Aleš Matějů            730
1    Francesco Di Mariano             63
2  Hilmir Rafn Mikaelsson             17
3                Issa Bah              9
4         Nicolas Galazzi             17
5            Patrick Leal              9

  CG plantilla completa:

                     player              player_norm
0      Antonio Junior Vacca     antonio junior vacca
1          Arnór Sigurdsson         arnor sigurdsson
2   Bjarki Steinn Bjarkason  bjarki steinn bjarkason
3           Bruno Bertinato          bruno bertinato
4         Cristian Molinaro        cristian molinaro
5              Daan Heymans             daan heymans
6             David Okereke            david okereke
7             David Schnegg            david schnegg
8            Dennis Johnsen           dennis johnsen
9             Domen Crnigoj            domen crnigoj
10               Dor Peretz               dor peretz
11             Ethan Ampadu             ethan ampadu
12             Filippo Neri             filippo neri
13          Francesco Forte          francesco forte
14           Gianluca Busio           gianluca busio
15         Gianmarco Zigoni         gianmarco zigoni
16              Jacopo Dezi              jacopo dezi
17        Jean-Pierre Nsame        jean pierre nsame
18      Lauri Ala-Myllymäki      lauri ala myllymaki
19          Luca Fiordilino          luca fiordilino
20           Luca Lezzerini           luca lezzerini
21             Marco Modolo             marco modolo
22             Mattia Aramu             mattia aramu
23           Mattia Caldara           mattia caldara
24       Maximilian Ullmann       maximilian ullmann
25         Michaël Cuisance         michael cuisance
26          Michael Svoboda          michael svoboda
27                     Nani                     nani
28             Niki Mäenpää             niki maenpaa
29    Óttar Magnús Karlsson    ottar magnus karlsson
30       Pasquale Mazzocchi       pasquale mazzocchi
31         Pietro Ceccaroni         pietro ceccaroni
32         Riccardo Bocalon         riccardo bocalon
33         Riccardo Pigozzo         riccardo pigozzo
34          Ridgeciano Haps          ridgeciano haps
35            Sergio Romero            sergio romero
36            Sofian Kiyine            sofian kiyine
37          Tanner Tessmann          tanner tessmann
38             Thomas Henry             thomas henry
39           Tyronne Ebuehi           tyronne ebuehi

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 561/609 (92.1%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_italy_2122.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_italy_2122.csv
   Jugadores totales:  609
   Con salario:        561
   Sin salario (NaN):  48
   Columnas:           121