# 03 · Join Sofascore + Capology — Italy Serie A 24/25

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2024/25 de Serie A italiana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_italy_2425.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_italy_2425.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  599 jugadores | 116 columnas
Capology:   700 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   inter
   milan

En Capology pero no en Sofascore:
   ac milan
   inter milan

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [7]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'inter milan':'inter',
            'ac milan':'milan'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [8]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 543/599 (90.7%)
Sin emparejar: 56

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [9]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          10
Revisión media    (0.75 ≤ score < 0.90):   8
Revisión estricta (0.50 ≤ score < 0.75):   21
Revisión muy est. (score < 0.50):           17

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [10]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf           team                cg_match  score
12     Albert Guðmundsson     Fiorentina      albert gudmundsson  0.971
5         Enrico Delprato          Parma        enrico del prato  0.968
16       Łukasz Skorupski        Bologna        lukasz skorupski  0.968
3             Evan Ndicka           Roma            evan n dicka  0.957
15  Þórir Jóhann Helgason          Lecce  thorir johann helgason  0.952
29            Konan N'Dri          Lecce              konan ndri  0.952
24              Lior Kasa          Genoa              lior kassa  0.947
30      Christian Gytkjær        Venezia      christian gytkjaer  0.941
39             Dani Silva  Hellas Verona            daniel silva  0.909
8             Milan Đurić          Parma            milan djuric  0.909

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [11]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                  player_sf           team                  cg_match  score
13         Faustino Anjorin         Empoli              tino anjorin  0.857
40  Dailon Rocha Livramento  Hellas Verona         dailon livramento  0.850
17        Mikael Ellertsson        Venezia   mikael egill ellertsson  0.850
18             Michel Adopo       Cagliari        michel ndary adopo  0.800
25       Cheick Oumar Condé        Venezia              cheick conde  0.800
6              Yann Bisseck          Inter        yann aurel bisseck  0.800
42          Marcus Pedersen         Torino  marcus holmgren pedersen  0.769
45            Mathias Løvik          Parma      mathias fjrtoft lvik  0.750

In [12]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 8 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [13]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf        team              cg_match  score
4    Mario Gila Fuentes       Lazio            mario gila  0.714
54        Lorenzo Tosto      Empoli       lorenzo colombo  0.714
2         Emerson Royal       Milan               emerson  0.700
35         Jacopo Bacci      Empoli        jacopo fazzini  0.692
19       Tommaso Rubino  Fiorentina    tommaso martinelli  0.688
1        Frank Anguissa      Napoli  andre zambo anguissa  0.647
47    Davide Bartesaghi       Milan       davide calabria  0.625
55        Nicola Pintus    Cagliari         nicolas viola  0.615
0            Juan Musso    Atalanta         juan cuadrado  0.609
26        Ismael Konate      Empoli        emmanuel ekong  0.593
34         Nunzio Lella     Venezia       antonio candela  0.593
7             Manu Koné        Roma          kouadio kone  0.571
49          Diego Pugno    Juventus        daniele rugani  0.560
50  Maat Daniel Caprini  Fiorentina        danilo cataldi  0.545
22       Federico Cassa    Atalanta         mario pasalic  0.519
48     Petar Stojanović      Empoli          saba sazonov  0.500
9     Lorenzo Venturino       Genoa       morten frendrup  0.500
27    Francesco Camarda       Milan       davide calabria  0.500
11      Mattia Liberali       Milan         matteo gabbia  0.500
10       Sofyan Amrabat  Fiorentina    rolando mandragora  0.500
23      Alberto Manzoni    Atalanta     marco brescianini  0.500

In [14]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mario gila fuentes',
                    'emerson royal',
                    'frank anguissa',
                    'manu kone'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 4

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [15]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf      team             cg_match  score
21     Alessio Cacciamani    Torino      alberto paleari  0.485
28         Sergiu Perciun    Torino      alberto paleari  0.483
53      Oliver Abildgaard      Como         alieu fadera  0.483
31         Walid Cheddira    Napoli          david neres  0.480
33         Luka Topalović     Inter     marko arnautovic  0.467
52  Aaron Ciammaglichella    Torino            ivan ilic  0.467
46       Nicholas Pierini   Venezia       alessio zerbin  0.467
41       Valentin Gendrey     Lecce       antonino gallo  0.467
36         Vanja Vlahović  Atalanta         rafael toloi  0.462
20        Lorenzo Anghelè  Juventus     nicolas gonzalez  0.452
14           Nehuén Pérez   Udinese      daniele padelli  0.444
37       Viktor Kovalenko    Empoli     christian kouame  0.438
38      Tommaso Gabellini    Torino      gvidas gineitis  0.438
51     Thomas Campaniello    Empoli       emmanuel ekong  0.438
32         Mitchel Bakker  Atalanta       marten de roon  0.429
44    Bob Murphy Omoregbe     Milan          noah okafor  0.400
43       Francesco Caputo    Empoli  sebastiano esposito  0.400

In [16]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [17]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 565/599 (94.3%)
Sin salario:     34

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [18]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 34

,player,team,minutesPlayed,appearances,goals,assists
0,Juan Musso,Atalanta,90,1,0,0
1,Vanja Vlahović,Atalanta,57,3,0,0
2,Federico Cassa,Atalanta,23,2,0,0
3,Mitchel Bakker,Atalanta,21,1,0,0
4,Alberto Manzoni,Atalanta,14,1,0,0
5,Nicola Pintus,Cagliari,3,1,0,0
6,Oliver Abildgaard,Como,7,1,0,0
7,Ismael Konate,Empoli,136,12,0,1
8,Viktor Kovalenko,Empoli,78,6,0,0
9,Jacopo Bacci,Empoli,29,3,0,0
10,Thomas Campaniello,Empoli,28,3,0,0
11,Francesco Caputo,Empoli,10,1,0,0
12,Petar Stojanović,Empoli,9,1,0,0
13,Lorenzo Tosto,Empoli,1,1,0,0
14,Sofyan Amrabat,Fiorentina,180,2,0,0
15,Maat Daniel Caprini,Fiorentina,15,2,0,0
16,Tommaso Rubino,Fiorentina,13,1,0,0
17,Lorenzo Venturino,Genoa,163,6,2,0
18,Luka Topalović,Inter,10,1,0,0
19,Diego Pugno,Juventus,10,1,0,0
20,Lorenzo Anghelè,Juventus,9,1,0,0
21,Valentin Gendrey,Lecce,180,2,0,0
22,Francesco Camarda,Milan,214,10,0,0
23,Davide Bartesaghi,Milan,123,4,0,0
24,Mattia Liberali,Milan,62,1,0,0
25,Bob Murphy Omoregbe,Milan,9,1,0,0
26,Walid Cheddira,Napoli,11,1,0,0
27,Sergiu Perciun,Torino,148,5,0,0
28,Alessio Cacciamani,Torino,29,2,0,0
29,Tommaso Gabellini,Torino,9,1,0,0
30,Aaron Ciammaglichella,Torino,1,1,0,0
31,Nehuén Pérez,Udinese,180,2,0,0
32,Nicholas Pierini,Venezia,82,2,0,0
33,Nunzio Lella,Venezia,8,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [19]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Atalanta  —  SF sin salario:

            player  minutesPlayed
0  Alberto Manzoni             14
1   Federico Cassa             23
2       Juan Musso             90
3   Mitchel Bakker             21
4   Vanja Vlahović             57

  CG plantilla completa:

                  player           player_norm
0        Ademola Lookman       ademola lookman
1            Ben Godfrey           ben godfrey
2         Berat Djimsiti        berat djimsiti
3          Brandon Soppy         brandon soppy
4   Charles De Ketelaere  charles de ketelaere
5         Daniel Maldini        daniel maldini
6      Davide Zappacosta     davide zappacosta
7                Éderson               ederson
8         El Bilal Touré        el bilal toure
9        Francesco Rossi       francesco rossi
10     Gianluca Scamacca     gianluca scamacca
11      Giorgio Scalvini      giorgio scalvini
12      Ibrahim Sulemana      ibrahim sulemana
13             Isak Hien             isak hien
14         Juan Cuadrado         juan cuadrado
15       Lazar Samardžić       lazar samardzic
16     Marco Brescianini     marco brescianini
17     Marco Carnesecchi     marco carnesecchi
18        Marco Palestra        marco palestra
19         Mario Pasalic         mario pasalic
20        Marten de Roon        marten de roon
21         Mateo Retegui         mateo retegui
22        Matteo Ruggeri        matteo ruggeri
23        Nicolò Zaniolo        nicolo zaniolo
24      Odilon Kossounou      odilon kossounou
25          Rafael Tolói          rafael toloi
26       Raoul Bellanova       raoul bellanova
27          Rui Patrício          rui patricio
28        Sead Kolasinac        sead kolasinac
29          Stefan Posch          stefan posch

============================================================
  Cagliari  —  SF sin salario:

          player  minutesPlayed
0  Nicola Pintus              3

  CG plantilla completa:

                player         player_norm
0           Adam Obert          adam obert
1          Alen Sherri         alen sherri
2    Alessandro Deiola   alessandro deiola
3    Antoine Makoumbou   antoine makoumbou
4         Elia Caprile        elia caprile
5       Florinel Coman      florinel coman
6       Gabriele Zappa      gabriele zappa
7     Gianluca Gaetano    gianluca gaetano
8    Gianluca Lapadula   gianluca lapadula
9      Giuseppe Ciocci     giuseppe ciocci
10        Jakub Jankto        jakub jankto
11  José Luis Palomino  jose luis palomino
12  Kingstone Mutandwa  kingstone mutandwa
13  Leonardo Pavoletti  leonardo pavoletti
14    Mateusz Wieteska    mateusz wieteska
15        Matteo Prati        matteo prati
16       Mattia Felici       mattia felici
17  Michel Ndary Adopo  michel ndary adopo
18        Nadir Zortea        nadir zortea
19       Nicolas Viola       nicolas viola
20          Paulo Azzi          paulo azzi
21        Răzvan Marin        razvan marin
22     Roberto Piccoli     roberto piccoli
23  Sebastiano Luperto  sebastiano luperto
24      Simone Scuffet      simone scuffet
25     Tommaso Augello     tommaso augello
26          Yerry Mina          yerry mina
27        Zito Luvumbo        zito luvumbo

============================================================
  Como  —  SF sin salario:

              player  minutesPlayed
0  Oliver Abildgaard              7

  CG plantilla completa:

                    player             player_norm
0            Alberto Cerri           alberto cerri
1          Alberto Dossena         alberto dossena
2           Alberto Moreno          alberto moreno
3   Alessandro Gabrielloni  alessandro gabrielloni
4           Alessio Iovine          alessio iovine
5               Álex Valle              alex valle
6                Ali Jasim               ali jasim
7             Alieu Fadera            alieu fadera
8      Anastasios Douvikas     anastasios douvikas
9           Andrea Belotti          andrea belotti
10             Assane Diao             assane diao
11       Ben Lhassine Kone       ben lhassine kone
12         Daniele Baselli         daniele baselli
13               Dele Alli               dele alli
14       Edoardo Goldaniga       edoardo goldaniga
15             Emil Audero             emil audero
16          Federico Barba          federico barba
17            Fellipe Jack            fellipe jack
18       Gabriel Strefezza       gabriel strefezza
19      Giuseppe Mazzaglia      giuseppe mazzaglia
20   Ignace Van der Brempt   ignace van der brempt
21               Iván Azón               ivan azon
22            Ivan Smolcic            ivan smolcic
23              Jean Butez              jean butez
24          Jonathan Ikoné          jonathan ikone
25         Luca Mazzitelli         luca mazzitelli
26          Lucas Da Cunha          lucas da cunha
27       Marc Oliver Kempf       marc oliver kempf
28              Marco Sala              marco sala
29      Matthias Braunöder      matthias braunoder
30          Mauro Vigorito          mauro vigorito
31        Maxence Caqueret        maxence caqueret
32          Máximo Perrone          maximo perrone
33          Mërgim Vojvoda          mergim vojvoda
34           Moutir Chajia           moutir chajia
35                Naj Razi                naj razi
36                Nico Paz                nico paz
37         Patrick Cutrone         patrick cutrone
38              Pepe Reina              pepe reina
39           Peter Kovacik           peter kovacik
40         Pierre Bolchini         pierre bolchini
41          Raphaël Varane          raphael varane
42           Sergi Roberto           sergi roberto
43            Simone Verdi            simone verdi
44       Yannik Engelhardt       yannik engelhardt

============================================================
  Empoli  —  SF sin salario:

               player  minutesPlayed
0    Francesco Caputo             10
1       Ismael Konate            136
2        Jacopo Bacci             29
3       Lorenzo Tosto              1
4    Petar Stojanović              9
5  Thomas Campaniello             28
6    Viktor Kovalenko             78

  CG plantilla completa:

                 player          player_norm
0        Alberto Grassi       alberto grassi
1        Ardian Ismajli       ardian ismajli
2      Christian Kouamé     christian kouame
3         Devis Vásquez        devis vasquez
4        Emmanuel Ekong       emmanuel ekong
5        Emmanuel Gyasi       emmanuel gyasi
6   Federico Brancolini  federico brancolini
7     Giuseppe Pezzella    giuseppe pezzella
8        Jacopo Fazzini       jacopo fazzini
9       Jacopo Seghetti      jacopo seghetti
10        Junior Sambia        junior sambia
11       Liam Henderson       liam henderson
12      Liberato Cacace      liberato cacace
13      Lorenzo Colombo      lorenzo colombo
14    Luca Belardinelli    luca belardinelli
15      Luca Marianucci      luca marianucci
16      Marco Silvestri      marco silvestri
17    Mattia De Sciglio    mattia de sciglio
18          Mattia Viti          mattia viti
19         Nicolas Haas         nicolas haas
20        Ola Solbakken        ola solbakken
21      Pietro Pellegri      pietro pellegri
22     Saba Goglichidze     saba goglichidze
23         Saba Sazonov         saba sazonov
24      Samuele Perisan      samuele perisan
25  Sebastiano Esposito  sebastiano esposito
26     Szymon Żurkowski     szymon zurkowski
27         Tino Anjorin         tino anjorin
28       Tyronne Ebuehi       tyronne ebuehi
29        Youssef Maleh        youssef maleh

============================================================
  Fiorentina  —  SF sin salario:

                player  minutesPlayed
0  Maat Daniel Caprini             15
1       Sofyan Amrabat            180
2       Tommaso Rubino             13

  CG plantilla completa:

                   player            player_norm
0       Abdelhamid Sabiri      abdelhamid sabiri
1      Albert Gudmundsson     albert gudmundsson
2         Amir Richardson        amir richardson
3          Andrea Colpani         andrea colpani
4           Antonín Barák          antonin barak
5              Cher Ndour             cher ndour
6        Christian Kouamé       christian kouame
7       Cristiano Biraghi      cristiano biraghi
8          Danilo Cataldi         danilo cataldi
9            David de Gea           david de gea
10                   Dodô                   dodo
11           Edoardo Bove           edoardo bove
12         Fabiano Parisi         fabiano parisi
13         Gino Infantino         gino infantino
14         Jonathan Ikoné         jonathan ikone
15          Josip Brekalo          josip brekalo
16           Luca Ranieri           luca ranieri
17          Lucas Beltrán          lucas beltran
18  Lucas Martínez Quarta  lucas martinez quarta
19        Marin Pongračić        marin pongracic
20          Matías Moreno          matias moreno
21     Michael Folorunsho     michael folorunsho
22         Michael Kayode         michael kayode
23             Moise Kean             moise kean
24         Nicolò Fagioli         nicolo fagioli
25         Nicolò Zaniolo         nicolo zaniolo
26     Oliver Christensen     oliver christensen
27             Pablo Marí             pablo mari
28         Pietro Comuzzo         pietro comuzzo
29     Pietro Terracciano     pietro terracciano
30        Riccardo Sottil        riccardo sottil
31           Robin Gosens           robin gosens
32     Rolando Mandragora     rolando mandragora
33     Tommaso Martinelli     tommaso martinelli
34            Yacine Adli            yacine adli

============================================================
  Genoa  —  SF sin salario:

              player  minutesPlayed
0  Lorenzo Venturino            163

  CG plantilla completa:

                    player             player_norm
0             Aarón Martín            aaron martin
1            Alan Matturro           alan matturro
2   Alessandro Marcandalli  alessandro marcandalli
3     Alessandro Vogliacco    alessandro vogliacco
4        Alessandro Zanoli       alessandro zanoli
5         Andrea Pinamonti        andrea pinamonti
6        Benjamin Siegrist       benjamin siegrist
7      Brooke Norton-Cuffy     brooke norton cuffy
8             Caleb Ekuban            caleb ekuban
9        Daniele Sommariva       daniele sommariva
10            David Ankeye            david ankeye
11            Emil Bohinen            emil bohinen
12           Fabio Miretti           fabio miretti
13      Federico Accornero      federico accornero
14        Filippo Melegoni        filippo melegoni
15             Franz Stolz             franz stolz
16          Gastón Pereiro          gaston pereiro
17           Honest Ahanor           honest ahanor
18             Hugo Cuenca             hugo cuenca
19              Jean Onana              jean onana
20            Jeff Ekhator            jeff ekhator
21           Johan Vásquez           johan vasquez
22          Junior Messias          junior messias
23          Koni De Winter          koni de winter
24              Lior Kassa              lior kassa
25        Manolo Portanova        manolo portanova
26         Mario Balotelli         mario balotelli
27             Marko Pajac             marko pajac
28             Mattia Bani             mattia bani
29           Maxwel Cornet           maxwel cornet
30            Milan Badelj            milan badelj
31         Morten Frendrup         morten frendrup
32          Morten Thorsby          morten thorsby
33            Nicola Leali            nicola leali
34         Patrizio Masini         patrizio masini
35       Pierluigi Gollini       pierluigi gollini
36      Ruslan Malinovskyi      ruslan malinovskyi
37          Sebastian Otoa          sebastian otoa
38         Stefano Sabelli         stefano sabelli
39                 Vitinha                 vitinha

============================================================
  Inter  —  SF sin salario:

           player  minutesPlayed
0  Luka Topalović             10

  CG plantilla completa:

                 player          player_norm
0    Alessandro Bastoni   alessandro bastoni
1       Benjamin Pavard      benjamin pavard
2        Carlos Augusto       carlos augusto
3       Davide Frattesi      davide frattesi
4       Denzel Dumfries      denzel dumfries
5         Eddie Salcedo        eddie salcedo
6      Federico Dimarco     federico dimarco
7      Francesco Acerbi     francesco acerbi
8      Hakan Çalhanoğlu     hakan calhanoglu
9    Henrikh Mkhitaryan   henrikh mkhitaryan
10           Ionut Radu           ionut radu
11       Joaquín Correa       joaquin correa
12       Josep Martínez       josep martinez
13     Kristjan Asllani     kristjan asllani
14     Lautaro Martínez     lautaro martinez
15        Marcus Thuram        marcus thuram
16     Marko Arnautovic     marko arnautovic
17       Matteo Darmian       matteo darmian
18         Mehdi Taremi         mehdi taremi
19      Nicola Zalewski      nicola zalewski
20       Nicolò Barella       nicolo barella
21      Piotr Zieliński      piotr zielinski
22  Raffaele Di Gennaro  raffaele di gennaro
23       Stefan de Vrij       stefan de vrij
24       Tajon Buchanan       tajon buchanan
25       Tomás Palacios       tomas palacios
26     Valentín Carboni     valentin carboni
27   Yann Aurel Bisseck   yann aurel bisseck
28          Yann Sommer          yann sommer

============================================================
  Juventus  —  SF sin salario:

            player  minutesPlayed
0      Diego Pugno             10
1  Lorenzo Anghelè              9

  CG plantilla completa:

                 player          player_norm
0         Alberto Costa        alberto costa
1       Andrea Cambiaso      andrea cambiaso
2       Arkadiusz Milik      arkadiusz milik
3                Arthur               arthur
4                Bremer               bremer
5       Carlo Pinsoglio      carlo pinsoglio
6        Daniele Rugani       daniele rugani
7                Danilo               danilo
8          Douglas Luiz         douglas luiz
9        Dušan Vlahović       dusan vlahovic
10        Fabio Miretti        fabio miretti
11       Federico Gatti       federico gatti
12  Francisco Conceição  francisco conceicao
13          Jonas Rouhi          jonas rouhi
14           Juan Cabal           juan cabal
15         Kenan Yıldız           kenan yldz
16      Khéphren Thuram      khephren thuram
17          Lloyd Kelly          lloyd kelly
18     Manuel Locatelli     manuel locatelli
19         Mattia Perin         mattia perin
20  Michele Di Gregorio  michele di gregorio
21     Nicolás González     nicolas gonzalez
22       Nicolò Fagioli       nicolo fagioli
23        Nicolò Savona        nicolo savona
24           Paul Pogba           paul pogba
25        Pierre Kalulu        pierre kalulu
26    Randal Kolo Muani    randal kolo muani
27         Renato Veiga         renato veiga
28      Samuel Mbangula      samuel mbangula
29     Teun Koopmeiners     teun koopmeiners
30          Tiago Djaló          tiago djalo
31         Timothy Weah         timothy weah
32       Vasilije Adžić       vasilije adzic
33      Weston McKennie      weston mckennie

============================================================
  Lecce  —  SF sin salario:

             player  minutesPlayed
0  Valentin Gendrey            180

  CG plantilla completa:

                      player               player_norm
0           Alexandru Borbei          alexandru borbei
1               Andy Pelmard              andy pelmard
2                 Ante Rebić                ante rebic
3             Antonino Gallo            antonino gallo
4          Balthazar Pierret         balthazar pierret
5          Christian Früchtl         christian fruchtl
6               Danilo Veiga              danilo veiga
7                 Dario Daka                dario daka
8                Ed McJannet               ed mcjannet
9               Elijah Scott              elijah scott
10      Federico Baschirotto      federico baschirotto
11         Filip Marchwinski         filip marchwinski
12         Frédéric Guilbert         frederic guilbert
13                 Gaby Jean                 gaby jean
14               Hamza Rafia               hamza rafia
15            Jasper Samooja            jasper samooja
16           Jeppe Corfitzen           jeppe corfitzen
17           Jesper Karlsson           jesper karlsson
18             Joan González             joan gonzalez
19  Joel Voelkerling Persson  joel voelkerling persson
20            Kevin Bonifazi            kevin bonifazi
21           Kialonda Gaspar           kialonda gaspar
22               Konan N’Dri                konan ndri
23              Lameck Banda              lameck banda
24         Lassana Coulibaly         lassana coulibaly
25                 Luis Hasa                 luis hasa
26                Marco Sala                marco sala
27             Medon Berisha             medon berisha
28              Mohamed Kaba              mohamed kaba
29            Nicola Sansone            nicola sansone
30           Nikola Krstović           nikola krstovic
31             Patrick Dorgu             patrick dorgu
32             Rareș Burnete             rares burnete
33                Rémi Oudin                remi oudin
34         Santiago Pierotti         santiago pierotti
35        Sebastian Esposito        sebastian esposito
36              Tete Morente              tete morente
37    Thórir Jóhann Helgason    thorir johann helgason
38             Tiago Gabriel             tiago gabriel
39               Vernon Addo               vernon addo
40         Wladimiro Falcone         wladimiro falcone
41            Ylber Ramadani            ylber ramadani

============================================================
  Milan  —  SF sin salario:

                player  minutesPlayed
0  Bob Murphy Omoregbe              9
1    Davide Bartesaghi            123
2    Francesco Camarda            214
3      Mattia Liberali             62

  CG plantilla completa:

                 player          player_norm
0   Alessandro Florenzi  alessandro florenzi
1          Álex Jiménez         alex jimenez
2         Álvaro Morata        alvaro morata
3     Christian Pulisic    christian pulisic
4       Davide Calabria      davide calabria
5               Emerson              emerson
6         Fikayo Tomori        fikayo tomori
7   Filippo Terracciano  filippo terracciano
8       Ismaël Bennacer      ismael bennacer
9            João Félix           joao felix
10         Kevin Zeroli         kevin zeroli
11          Kyle Walker          kyle walker
12     Lorenzo Torriani     lorenzo torriani
13           Luka Jović           luka jovic
14         Malick Thiaw         malick thiaw
15     Marco Sportiello     marco sportiello
16        Matteo Gabbia        matteo gabbia
17         Mike Maignan         mike maignan
18          Noah Okafor          noah okafor
19        Pierre Kalulu        pierre kalulu
20          Rafael Leão          rafael leao
21      Riccardo Sottil      riccardo sottil
22   Ruben Loftus-Cheek   ruben loftus cheek
23     Samuel Chukwueze     samuel chukwueze
24     Santiago Gimenez     santiago gimenez
25   Strahinja Pavlović   strahinja pavlovic
26        Tammy Abraham        tammy abraham
27       Theo Hernández       theo hernandez
28    Tijjani Reijnders    tijjani reijnders
29         Warren Bondo         warren bondo
30      Youssouf Fofana      youssouf fofana
31          Yunus Musah          yunus musah

============================================================
  Napoli  —  SF sin salario:

           player  minutesPlayed
0  Walid Cheddira             11

  CG plantilla completa:

                   player            player_norm
0   Alessandro Buongiorno  alessandro buongiorno
1          Alessio Zerbin         alessio zerbin
2              Alex Meret             alex meret
3           Amir Rrahmani          amir rrahmani
4    André Zambo Anguissa   andre zambo anguissa
5           Billy Gilmour          billy gilmour
6            Claudio Turi           claudio turi
7            Cyril Ngonge           cyril ngonge
8             David Neres            david neres
9            Elia Caprile           elia caprile
10      Giacomo Raspadori      giacomo raspadori
11    Giovanni Di Lorenzo    giovanni di lorenzo
12       Giovanni Simeone       giovanni simeone
13           Jens Cajuste           jens cajuste
14       Jesper Lindstrøm        jesper lindstrm
15             Juan Jesus             juan jesus
16  Khvicha Kvaratskhelia  khvicha kvaratskhelia
17    Leonardo Spinazzola    leonardo spinazzola
18              Luis Hasa              luis hasa
19              Mário Rui              mario rui
20        Mathías Olivera        mathias olivera
21        Matteo Politano        matteo politano
22     Michael Folorunsho     michael folorunsho
23         Nikita Contini         nikita contini
24            Noah Okafor            noah okafor
25     Pasquale Mazzocchi     pasquale mazzocchi
26         Philip Billing         philip billing
27             Rafa Marín             rafa marin
28          Romelu Lukaku          romelu lukaku
29        Scott McTominay        scott mctominay
30         Simone Scuffet         simone scuffet
31      Stanislav Lobotka      stanislav lobotka
32         Victor Osimhen         victor osimhen

============================================================
  Torino  —  SF sin salario:

                  player  minutesPlayed
0  Aaron Ciammaglichella              1
1     Alessio Cacciamani             29
2         Sergiu Perciun            148
3      Tommaso Gabellini              9

  CG plantilla completa:

                      player               player_norm
0                Adam Masina               adam masina
1              Adrien Tamèze             adrien tameze
2            Alberto Paleari           alberto paleari
3                Ali Dembélé               ali dembele
4                 Alieu Njie                alieu njie
5               Amine Salama              amine salama
6    Ange Caumenan N'Guessan   ange caumenan n guessan
7         Antonio Donnarumma        antonio donnarumma
8           Antonio Sanabria          antonio sanabria
9                 Borna Sosa                borna sosa
10              Brian Bayeye              brian bayeye
11            Cesare Casadei            cesare casadei
12                 Ché Adams                 che adams
13       Côme Bianay Balcot        come bianay balcot
14         Cristiano Biraghi         cristiano biraghi
15              Duván Zapata              duvan zapata
16               Eljif Elmas               eljif elmas
17            Emirhan İlkhan            emirhan ilkhan
18         Guillermo Maripán         guillermo maripan
19           Gvidas Gineitis           gvidas gineitis
20                 Ivan Ilić                 ivan ilic
21             Karol Linetty             karol linetty
22  Marcus Holmgren Pedersen  marcus holmgren pedersen
23            Mërgim Vojvoda            mergim vojvoda
24          Nemanja Radonjić          nemanja radonjic
25             Nikola Vlašić             nikola vlasic
26              Perr Schuurs              perr schuurs
27             Samuele Ricci             samuele ricci
28                 Saúl Coco                 saul coco
29     Sebastian Walukiewicz     sebastian walukiewicz
30          Valentino Lazaro          valentino lazaro
31    Vanja Milinković-Savić    vanja milinkovic savic
32              Yann Karamoh              yann karamoh
33               Zanos Savva               zanos savva

============================================================
  Udinese  —  SF sin salario:

         player  minutesPlayed
0  Nehuén Pérez            180

  CG plantilla completa:

                    player             player_norm
0           Alexis Sánchez          alexis sanchez
1              Arthur Atta             arthur atta
2            Axel Guessand           axel guessand
3                  Brenner                 brenner
4       Christian Kabasele      christian kabasele
5           Damián Pizarro          damian pizarro
6          Daniele Padelli         daniele padelli
7            David Pejičić           david pejicic
8            Edoardo Piana           edoardo piana
9              Enzo Ebosse             enzo ebosse
10         Florian Thauvin         florian thauvin
11         Gerard Deulofeu         gerard deulofeu
12          Hassane Kamara          hassane kamara
13              Iker Bravo              iker bravo
14              Jaka Bijol              jaka bijol
15          James Abankwah          james abankwah
16        Jesper Karlström        jesper karlstrom
17           Jordan Zemura           jordan zemura
18      Jurgen Ekkelenkamp      jurgen ekkelenkamp
19            Keinan Davis            keinan davis
20       Kingsley Ehizibue       kingsley ehizibue
21       Lautaro Giannetti       lautaro giannetti
22           Lorenzo Lucca           lorenzo lucca
23            Maduka Okoye            maduka okoye
24           Martín Payero           martin payero
25            Matteo Palma            matteo palma
26            Oier Zarraga            oier zarraga
27             Oumar Solet             oumar solet
28             Răzvan Sava             razvan sava
29             Rui Modesto             rui modesto
30            Sandi Lovrić            sandi lovric
31           Sekou Diawara           sekou diawara
32          Simone Pafundi          simone pafundi
33  Souleymane Isaak Touré  souleymane isaak toure
34       Thomas Kristensen       thomas kristensen

============================================================
  Venezia  —  SF sin salario:

             player  minutesPlayed
0  Nicholas Pierini             82
1      Nunzio Lella              8

  CG plantilla completa:

                     player              player_norm
0    Alessandro Marcandalli   alessandro marcandalli
1            Alessio Zerbin           alessio zerbin
2             Alfred Duncan            alfred duncan
3           Antonio Candela          antonio candela
4          Antonio Raimondo         antonio raimondo
5   Bjarki Steinn Bjarkason  bjarki steinn bjarkason
6           Bruno Bertinato          bruno bertinato
7              Cheick Condé             cheick conde
8        Christian Gytkjaer       christian gytkjaer
9               Daniel Fila              daniel fila
10            Domen Crnigoj            domen crnigoj
11               Fali Candé               fali cande
12          Filip Stankovic          filip stankovic
13             Filippo Neri             filippo neri
14        Francesco Zampano        francesco zampano
15           Franco Carboni           franco carboni
16        Gaetano Oristanio        gaetano oristanio
17           Gianluca Busio           gianluca busio
18           Giorgio Altare           giorgio altare
19  Hans Nicolussi Caviglia  hans nicolussi caviglia
20               Ionut Radu               ionut radu
21             Issa Doumbia             issa doumbia
22                Jay Idzes                jay idzes
23            Jesse Joronen            jesse joronen
24          Joel Pohjanpalo          joel pohjanpalo
25        Joël Schingtienne        joel schingtienne
26              John Yeboah              john yeboah
27               Kike Pérez               kike perez
28          Luca Fiordilino          luca fiordilino
29    Magnus Kofod Andersen    magnus kofod andersen
30             Marin Šverko             marin sverko
31            Matteo Grandi            matteo grandi
32          Michael Svoboda          michael svoboda
33  Mikael Egill Ellertsson  mikael egill ellertsson
34              Mirko Marić              mirko maric
35           Richie Sagrado           richie sagrado
36          Ridgeciano Haps          ridgeciano haps
37           Saad El Haddad           saad el haddad

In [20]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [21]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 565/599 (94.3%)

In [22]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [23]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_italy_2425.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_italy_2425.csv
   Jugadores totales:  599
   Con salario:        565
   Sin salario (NaN):  34
   Columnas:           121