# 03 · Join Sofascore + Capology — Italy Serie A 25/26 (snapshot 20260428)

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2025/26 de la Serie A italiana**.

⚠️ **Nota sobre el snapshot:** la temporada 25/26 está aún en curso. Se trabaja con
una foto fija de Sofascore (`df_italy_2526_snapshot_20260428.csv`). Este notebook
deberá reejecutarse con los datos definitivos cuando finalice la liga, generando
entonces el master sin sufijo de fecha (`master_italy_2526.csv`).

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_italy_2526_snapshot_20260428.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_italy_2526.csv').copy()

print(f'Sofascore (snapshot):  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:              {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore (snapshot):  561 jugadores | 117 columnas
Capology:              607 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   inter
   milan

En Capology pero no en Sofascore:
   ac milan
   inter milan

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'ac milan':'milan',
            'inter milan':'inter'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 487/561 (86.8%)
Sin emparejar: 74

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          12
Revisión media    (0.75 ≤ score < 0.90):   9
Revisión estricta (0.50 ≤ score < 0.75):   35
Revisión muy est. (score < 0.50):           18

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf        team                cg_match  score
0         Benjamin Pavard       Inter         benjamin pavard  1.000
1        Samuel Chukwueze       Milan        samuel chukwueze  1.000
41           Álex Jiménez       Milan            alex jimenez  1.000
20     Albert Guðmundsson  Fiorentina      albert gudmundsson  0.971
14       Łukasz Skorupski     Bologna        lukasz skorupski  0.968
21        Enrico Delprato       Parma        enrico del prato  0.968
12         Jan Ziółkowski        Roma          jan ziolkowski  0.963
9             Evan Ndicka        Roma            evan n dicka  0.957
50  Þórir Jóhann Helgason       Lecce  thorir johann helgason  0.952
47         Rafael Obrador      Torino            rafa obrador  0.923
52     Benjamin Cremaschi       Parma         benja cremaschi  0.909
17            Milan Đurić   Cremonese            milan djuric  0.909

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf      team                  cg_match  score
32      Mikael Ellertsson     Genoa   mikael egill ellertsson  0.850
40        Kostas Tsimikas      Roma     konstantinos tsimikas  0.833
63  Henrik Wendel Meister      Pisa            henrik meister  0.800
16             Ange Bonny     Inter           ange yoan bonny  0.800
2            Yann Bisseck     Inter        yann aurel bisseck  0.800
29           Michel Adopo  Cagliari        michel ndary adopo  0.800
68    Alessandro Di Pardo  Cagliari         alessandro deiola  0.778
37    Nicolas-Gerrit Kühn      Como              nicolas kuhn  0.774
54        Marcus Pedersen    Torino  marcus holmgren pedersen  0.769

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['alessandro di pardo'

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 8 | Excluidos: 1

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf           team                cg_match  score
7            Marc Kempf           Como       marc oliver kempf  0.741
22         Andrea Ghion       Sassuolo        andrea pinamonti  0.714
30    Adrian Benedyczak          Parma          adrian bernabe  0.710
34  Moatasem Al-Musrati  Hellas Verona              al musrati  0.690
53           Gift Orban  Hellas Verona     gift emmanuel orban  0.690
38             Sulemana       Cagliari        ibrahim sulemana  0.667
46      Nicolae Stanciu          Genoa            nicola leali  0.667
15    Alexsandro Amorim          Genoa  alessandro marcandalli  0.667
8        Frank Anguissa         Napoli    andre zambo anguissa  0.647
64       Matteo Lavelli          Inter          matteo darmian  0.643
48      Mateus Lusuardi           Pisa            marius marin  0.593
45           Pablo Mari     Fiorentina          fabiano parisi  0.583
3             Manu Koné           Roma            kouadio kone  0.571
24        Matias Vecino          Lazio         mattia zaccagni  0.571
58        Mathias Løvik          Parma           matija frigan  0.560
69          Adam Masina         Torino          ardian ismajli  0.560
26    Balthazar Pierret          Lecce            matias perez  0.552
4           Suzuki Zion          Parma             zion suzuki  0.545
11     Kristjan Asllani         Torino       cristiano biraghi  0.545
5      Mattéo Guendouzi          Lazio      matteo cancellieri  0.529
39          N'Dri Konan          Lecce            sadik fofana  0.522
62          Leon Bailey           Roma            paulo dybala  0.522
42  Daniel Mikołajewski          Parma           mandela keita  0.516
6            Paul Mendy       Cagliari              yael trepy  0.500
71     Andrea Le Borgne           Como            adrian lahdo  0.500
55  Dachi Lordkipanidze      Cremonese           david okereke  0.500
44       Nicolò Cavuoti       Cagliari      leonardo pavoletti  0.500
61  Christ-Owen Kouassi          Lecce       christian fruchtl  0.500
35           Edin Džeko     Fiorentina              eman kospo  0.500
25       Albert Grønbæk          Genoa        valentin carboni  0.500
19       Franco Vazquez      Cremonese      federico bonazzoli  0.500
23     Nicolás González       Juventus            douglas luiz  0.500
13       Yellu Santiago  Hellas Verona              al musrati  0.500
33         Mohamed Kaba          Lecce            lameck banda  0.500
51        Antonio Arena           Roma             robinio vaz  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['marc kempf',
                    'moatasem al musrati',
                    'gift orban',
                    'sulemana',
                    'frank anguissa',
                    'manu kone',
                    'suzuki zion'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 7

### 7.4 Revisión muy estricta (score < 0.50)

Candidatos con muy baja similitud. Por defecto ninguno se acepta.
Añadir a `ACCEPT_VERY_LOW_FUZZY` los que se confirmen manualmente.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf           team             cg_match  score
18        Ademola Lookman       Atalanta   kamaldeen sulemana  0.485
49          Ioan Vermesan  Hellas Verona         martin frese  0.480
28                Hernani          Parma       franco carboni  0.476
43            Olaf Gorter          Lecce           oumar ngom  0.476
10   Valentín Castellanos          Lazio   alessio furlanetto  0.474
56      Alessandro Romano           Roma    lorenzo venturino  0.471
65           Louis Buffon           Pisa       rosen bozhinov  0.462
66          Tomás Esteves           Pisa        calvin stengs  0.462
70             Tjaš Begić          Parma     sascha britschgi  0.462
60      Giovanni Bonfanti           Pisa   simone canestrelli  0.457
67          Ciro Immobile        Bologna       tommaso pobega  0.444
27      Grigoris Kastanos  Hellas Verona      giacomo toniolo  0.438
73           Cas Odenthal       Sassuolo     nicholas pierini  0.429
36       Saba Goglichidze        Udinese         sandi lovric  0.429
31         Dennis Johnsen      Cremonese  federico ceccherini  0.424
72     Joi Xheto Nuredini          Genoa          seydou fini  0.414
57  Cheveyo Mul-Balentien          Milan      ismael bennacer  0.389
59           Tete Morente          Lecce         corrie ndaba  0.333

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 511/561 (91.1%)
Sin salario:     50

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 50

,player,team,minutesPlayed,appearances,goals,assists
0,Ademola Lookman,Atalanta,797,12,2,0
1,Ciro Immobile,Bologna,191,6,0,0
2,Paul Mendy,Cagliari,133,5,2,0
3,Alessandro Di Pardo,Cagliari,60,3,0,0
4,Nicolò Cavuoti,Cagliari,52,4,0,0
5,Andrea Le Borgne,Como,1,1,0,0
6,Franco Vazquez,Cremonese,529,15,1,2
7,Dennis Johnsen,Cremonese,390,11,1,1
8,Dachi Lordkipanidze,Cremonese,28,1,0,0
9,Pablo Mari,Fiorentina,809,11,0,0
10,Edin Džeko,Fiorentina,250,11,0,0
11,Alexsandro Amorim,Genoa,252,7,0,0
12,Nicolae Stanciu,Genoa,191,4,0,0
13,Albert Grønbæk,Genoa,107,4,0,0
14,Joi Xheto Nuredini,Genoa,1,1,0,0
15,Ioan Vermesan,Hellas Verona,64,3,0,0
16,Grigoris Kastanos,Hellas Verona,59,6,0,0
17,Yellu Santiago,Hellas Verona,11,2,0,0
18,Benjamin Pavard,Inter,90,1,0,0
19,Matteo Lavelli,Inter,12,1,0,0
20,Nicolás González,Juventus,24,2,0,0
21,Mattéo Guendouzi,Lazio,1430,16,2,1
22,Valentín Castellanos,Lazio,694,11,2,3
23,Matias Vecino,Lazio,605,13,0,1
24,Tete Morente,Lecce,859,16,0,0
25,Mohamed Kaba,Lecce,646,15,0,0
26,N'Dri Konan,Lecce,495,24,2,0
27,Christ-Owen Kouassi,Lecce,228,4,0,0
28,Balthazar Pierret,Lecce,32,3,0,0
29,Olaf Gorter,Lecce,27,2,0,0
30,Álex Jiménez,Milan,45,1,0,0
31,Samuel Chukwueze,Milan,25,1,0,0
32,Cheveyo Mul-Balentien,Milan,9,2,0,0
33,Adrian Benedyczak,Parma,486,14,1,1
34,Mathias Løvik,Parma,479,9,0,0
35,Hernani,Parma,69,4,0,0
36,Daniel Mikołajewski,Parma,18,1,0,0
37,Tjaš Begić,Parma,1,1,0,0
38,Giovanni Bonfanti,Pisa,495,9,0,0
39,Mateus Lusuardi,Pisa,199,3,0,0
40,Louis Buffon,Pisa,36,4,0,0
41,Tomás Esteves,Pisa,13,1,0,0
42,Leon Bailey,Roma,182,7,0,0
43,Antonio Arena,Roma,25,2,0,0
44,Alessandro Romano,Roma,10,2,0,0
45,Andrea Ghion,Sassuolo,9,1,0,0
46,Cas Odenthal,Sassuolo,1,1,0,0
47,Kristjan Asllani,Torino,1135,15,0,0
48,Adam Masina,Torino,232,5,0,1
49,Saba Goglichidze,Udinese,422,8,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Atalanta  —  SF sin salario:

            player  minutesPlayed
0  Ademola Lookman            797

  CG plantilla completa:

                  player           player_norm
0            Ben Godfrey           ben godfrey
1         Berat Djimsiti        berat djimsiti
2   Charles De Ketelaere  charles de ketelaere
3         Daniel Maldini        daniel maldini
4      Davide Zappacosta     davide zappacosta
5                Éderson               ederson
6         El Bilal Touré        el bilal toure
7        Francesco Rossi       francesco rossi
8      Giacomo Raspadori     giacomo raspadori
9      Gianluca Scamacca     gianluca scamacca
10      Giorgio Scalvini      giorgio scalvini
11         Honest Ahanor         honest ahanor
12             Isak Hien             isak hien
13    Kamaldeen Sulemana    kamaldeen sulemana
14       Lazar Samardžić       lazar samardzic
15    Lorenzo Bernasconi    lorenzo bernasconi
16     Marco Brescianini     marco brescianini
17     Marco Carnesecchi     marco carnesecchi
18      Marco Sportiello      marco sportiello
19         Mario Pašalić         mario pasalic
20        Marten de Roon        marten de roon
21        Mitchel Bakker        mitchel bakker
22       Nicola Zalewski       nicola zalewski
23       Nikola Krstović       nikola krstovic
24      Odilon Kossounou      odilon kossounou
25       Raoul Bellanova       raoul bellanova
26        Sead Kolasinac        sead kolasinac
27           Yunus Musah           yunus musah

============================================================
  Bologna  —  SF sin salario:

          player  minutesPlayed
0  Ciro Immobile            191

  CG plantilla completa:

                     player              player_norm
0        Benjamín Domínguez       benjamin dominguez
1   Charalampos Lykogiannis  charalampos lykogiannis
2            Eivind Helland           eivind helland
3                 Emil Holm                emil holm
4     Federico Bernardeschi    federico bernardeschi
5         Federico Ravaglia        federico ravaglia
6          Giovanni Fabbian         giovanni fabbian
7          Ibrahim Sulemana         ibrahim sulemana
8              Jens Odgaard             jens odgaard
9           Jesper Karlsson          jesper karlsson
10              Jhon Lucumí              jhon lucumi
11               João Mário               joao mario
12             Joaquín Sosa             joaquin sosa
13            Jonathan Rowe            jonathan rowe
14             Juan Miranda             juan miranda
15           Kevin Bonifazi           kevin bonifazi
16           Lewis Ferguson           lewis ferguson
17     Lorenzo De Silvestri     lorenzo de silvestri
18         Lukasz Skorupski         lukasz skorupski
19             Martin Vitík             martin vitik
20          Massimo Pessina          massimo pessina
21             Mihajlo Ilić             mihajlo ilic
22             Nadir Zortea             nadir zortea
23         Nicolò Cambiaghi         nicolo cambiaghi
24            Nicolò Casale            nicolo casale
25              Nikola Moro              nikola moro
26             Remo Freuler             remo freuler
27        Riccardo Orsolini        riccardo orsolini
28          Santiago Castro          santiago castro
29               Simon Sohm               simon sohm
30           Thijs Dallinga           thijs dallinga
31           Tommaso Pobega           tommaso pobega
32          Torbjørn Heggem           torbjrn heggem

============================================================
  Cagliari  —  SF sin salario:

                player  minutesPlayed
0  Alessandro Di Pardo             60
1       Nicolò Cavuoti             52
2           Paul Mendy            133

  CG plantilla completa:

                 player          player_norm
0            Adam Obert           adam obert
1    Agustín Albarracín   agustin albarracin
2       Alberto Dossena      alberto dossena
3           Alen Sherri          alen sherri
4     Alessandro Deiola    alessandro deiola
5        Andrea Belotti       andrea belotti
6          Elia Caprile         elia caprile
7        Gabriele Zappa       gabriele zappa
8      Gennaro Borrelli     gennaro borrelli
9      Gianluca Gaetano     gianluca gaetano
10      Giuseppe Ciocci      giuseppe ciocci
11     Ibrahim Sulemana     ibrahim sulemana
12        Joseph Liteta        joseph liteta
13       Juan Rodríguez       juan rodriguez
14   Leonardo Pavoletti   leonardo pavoletti
15      Luca Mazzitelli      luca mazzitelli
16       Marco Palestra       marco palestra
17        Mattia Felici        mattia felici
18   Michael Folorunsho   michael folorunsho
19   Michel Ndary Adopo   michel ndary adopo
20     Othniël Raterink     othniel raterink
21        Riyad Idrissi        riyad idrissi
22  Sebastiano Esposito  sebastiano esposito
23       Semih Kılıçsoy         semih klcsoy
24           Yael Trepy           yael trepy
25           Yerry Mina           yerry mina
26             Zé Pedro             ze pedro
27         Zito Luvumbo         zito luvumbo

============================================================
  Como  —  SF sin salario:

             player  minutesPlayed
0  Andrea Le Borgne              1

  CG plantilla completa:

                   player            player_norm
0            Adrian Lahdo           adrian lahdo
1         Alberto Dossena        alberto dossena
2          Alberto Moreno         alberto moreno
3              Álex Valle             alex valle
4           Álvaro Morata          alvaro morata
5     Anastasios Douvikas    anastasios douvikas
6             Assane Diao            assane diao
7            Diego Carlos           diego carlos
8       Edoardo Goldaniga      edoardo goldaniga
9          Henrique Menke         henrique menke
10  Ignace Van der Brempt  ignace van der brempt
11           Ivan Smolcic           ivan smolcic
12           Jacobo Ramón           jacobo ramon
13           Jayden Addai           jayden addai
14             Jean Butez             jean butez
15        Jesús Rodríguez        jesus rodriguez
16         Lucas Da Cunha         lucas da cunha
17      Marc Oliver Kempf      marc oliver kempf
18        Martin Baturina        martin baturina
19         Mauro Vigorito         mauro vigorito
20       Maxence Caqueret       maxence caqueret
21         Máximo Perrone         maximo perrone
22         Mërgim Vojvoda         mergim vojvoda
23               Nico Paz               nico paz
24           Nicolas Kühn           nicolas kuhn
25         Nikola Cavlina         nikola cavlina
26         Noel Törnqvist         noel tornqvist
27          Sergi Roberto          sergi roberto
28           Stefan Posch           stefan posch

============================================================
  Cremonese  —  SF sin salario:

                player  minutesPlayed
0  Dachi Lordkipanidze             28
1       Dennis Johnsen            390
2       Franco Vazquez            529

  CG plantilla completa:

                       player                player_norm
0              Alberto Grassi             alberto grassi
1              Alessio Zerbin             alessio zerbin
2            Antonio Sanabria           antonio sanabria
3               David Okereke              david okereke
4                 Emil Audero                emil audero
5             Faris Moumbagna            faris moumbagna
6        Federico Baschirotto       federico baschirotto
7          Federico Bonazzoli         federico bonazzoli
8         Federico Ceccherini        federico ceccherini
9         Filippo Terracciano        filippo terracciano
10           Francesco Folino           francesco folino
11          Giuseppe Pezzella          giuseppe pezzella
12                Jamie Vardy                jamie vardy
13            Jari Vandeputte            jari vandeputte
14           Jeremy Sarmiento           jeremy sarmiento
15                  Lapo Nava                  lapo nava
16         Leonardo Sernicola         leonardo sernicola
17             Manuel De Luca             manuel de luca
18            Marco Silvestri            marco silvestri
19              Martín Payero              martin payero
20          Matteo Bianchetti          matteo bianchetti
21          Michele Collocolo          michele collocolo
22               Mikayil Faye               mikayil faye
23               Milan Djuric               milan djuric
24             Morten Thorsby             morten thorsby
25  Romano Floriani Mussolini  romano floriani mussolini
26         Sebastiano Luperto         sebastiano luperto
27           Tommaso Barbieri           tommaso barbieri
28               Warren Bondo               warren bondo
29              Youssef Maleh              youssef maleh

============================================================
  Fiorentina  —  SF sin salario:

       player  minutesPlayed
0  Edin Džeko            250
1  Pablo Mari            809

  CG plantilla completa:

                player         player_norm
0    Abdelhamid Sabiri   abdelhamid sabiri
1   Albert Gudmundsson  albert gudmundsson
2      Amir Richardson     amir richardson
3           Cher Ndour          cher ndour
4     Christian Kouamé    christian kouame
5       Daniele Rugani      daniele rugani
6         David de Gea        david de gea
7                 Dodô                dodo
8         Eddy Kouadio        eddy kouadio
9           Eman Kospo          eman kospo
10      Fabiano Parisi      fabiano parisi
11    Giovanni Fabbian    giovanni fabbian
12       Jack Harrison       jack harrison
13      Jacopo Fazzini      jacopo fazzini
14      Luca Lezzerini      luca lezzerini
15        Luca Ranieri        luca ranieri
16          Luis Balbo          luis balbo
17        M'Bala Nzola        m bala nzola
18       Manor Solomon       manor solomon
19   Marco Brescianini   marco brescianini
20     Marin Pongracic     marin pongracic
21         Mattia Viti         mattia viti
22          Moise Kean          moise kean
23     Niccolò Fortini     niccolo fortini
24      Nicolò Fagioli      nicolo fagioli
25  Oliver Christensen  oliver christensen
26      Pietro Comuzzo      pietro comuzzo
27     Roberto Piccoli     roberto piccoli
28        Robin Gosens        robin gosens
29  Rolando Mandragora  rolando mandragora
30          Simon Sohm          simon sohm
31       Tariq Lamptey       tariq lamptey
32  Tommaso Martinelli  tommaso martinelli

============================================================
  Genoa  —  SF sin salario:

               player  minutesPlayed
0      Albert Grønbæk            107
1   Alexsandro Amorim            252
2  Joi Xheto Nuredini              1
3     Nicolae Stanciu            191

  CG plantilla completa:

                     player              player_norm
0              Aarón Martín             aaron martin
1    Alessandro Marcandalli   alessandro marcandalli
2                    Amorim                   amorim
3         Benjamin Siegrist        benjamin siegrist
4       Brooke Norton-Cuffy      brooke norton cuffy
5              Caleb Ekuban             caleb ekuban
6         Daniele Sommariva        daniele sommariva
7         Ernestas Lysionok        ernestas lysionok
8                Jean Onana               jean onana
9              Jeff Ekhator             jeff ekhator
10            Johan Vásquez            johan vasquez
11           Junior Messias           junior messias
12            Justin Bijlow            justin bijlow
13             Leo Østigård              leo stigard
14          Lorenzo Colombo          lorenzo colombo
15            Maxwel Cornet            maxwel cornet
16  Mikael Egill Ellertsson  mikael egill ellertsson
17          Morten Frendrup          morten frendrup
18             Nicola Leali             nicola leali
19         Nils Zätterström         nils zatterstrom
20          Patrizio Masini          patrizio masini
21       Ruslan Malinovskyi       ruslan malinovskyi
22           Sebastian Otoa           sebastian otoa
23              Seydou Fini              seydou fini
24          Stefano Sabelli          stefano sabelli
25         Tommaso Baldanzi         tommaso baldanzi
26         Valentín Carboni         valentin carboni
27                  Vitinha                  vitinha

============================================================
  Hellas Verona  —  SF sin salario:

              player  minutesPlayed
0  Grigoris Kastanos             59
1      Ioan Vermesan             64
2     Yellu Santiago             11

  CG plantilla completa:

                    player             player_norm
0            Abdou Harroui           abdou harroui
1               Al Musrati              al musrati
2                Amin Sarr               amin sarr
3       Andrias Edmundsson      andrias edmundsson
4          Antoine Bernede         antoine bernede
5      Armel Bella-Kotchap     armel bella kotchap
6            Arthur Borghi           arthur borghi
7            Cheikh Niasse           cheikh niasse
8          Daniel Mosquera         daniel mosquera
9           Daniel Oyegoke          daniel oyegoke
10        Domagoj Bradarić        domagoj bradaric
11             Enzo Ebosse             enzo ebosse
12             Fallou Cham             fallou cham
13         Giacomo Toniolo         giacomo toniolo
14     Gift Emmanuel Orban     gift emmanuel orban
15                   Isaac                   isaac
16  Jean-Daniel Akpa Akpro  jean daniel akpa akpro
17            Junior Ajayi            junior ajayi
18            Kieron Bowie            kieron bowie
19         Lorenzo Montipò         lorenzo montipo
20            Martin Frese            martin frese
21       Nicolás Valentini       nicolas valentini
22              Pol Lirola              pol lirola
23          Rafik Belghali          rafik belghali
24     Roberto Gagliardini     roberto gagliardini
25            Sandi Lovrić            sandi lovric
26          Simone Perilli          simone perilli
27             Suat Serdar             suat serdar
28        Tobias Slotsager        tobias slotsager
29            Tomas Suslov            tomas suslov
30              Unai Núñez              unai nunez
31          Victor Nelsson          victor nelsson

============================================================
  Inter  —  SF sin salario:

            player  minutesPlayed
0  Benjamin Pavard             90
1   Matteo Lavelli             12

  CG plantilla completa:

                    player             player_norm
0       Alessandro Bastoni      alessandro bastoni
1               Andy Diouf              andy diouf
2          Ange-Yoan Bonny         ange yoan bonny
3          Benjamin Pavard         benjamin pavard
4           Carlos Augusto          carlos augusto
5          Davide Frattesi         davide frattesi
6          Denzel Dumfries         denzel dumfries
7     Ebenezer Akinsanmiro    ebenezer akinsanmiro
8         Federico Dimarco        federico dimarco
9         Francesco Acerbi        francesco acerbi
10  Francesco Pio Esposito  francesco pio esposito
11          Franco Carboni          franco carboni
12        Hakan Çalhanoğlu        hakan calhanoglu
13      Henrikh Mkhitaryan      henrikh mkhitaryan
14          Josep Martínez          josep martinez
15        Kristjan Asllani        kristjan asllani
16        Lautaro Martínez        lautaro martinez
17           Luis Henrique           luis henrique
18           Manuel Akanji           manuel akanji
19           Marcus Thuram           marcus thuram
20          Matteo Darmian          matteo darmian
21          Nicolò Barella          nicolo barella
22             Petar Sučić             petar sucic
23         Piotr Zieliński         piotr zielinski
24     Raffaele Di Gennaro     raffaele di gennaro
25          Stefan de Vrij          stefan de vrij
26          Tomás Palacios          tomas palacios
27        Valentín Carboni        valentin carboni
28      Yann Aurel Bisseck      yann aurel bisseck
29             Yann Sommer             yann sommer

============================================================
  Juventus  —  SF sin salario:

             player  minutesPlayed
0  Nicolás González             24

  CG plantilla completa:

                 player          player_norm
0       Andrea Cambiaso      andrea cambiaso
1       Arkadiusz Milik      arkadiusz milik
2                Arthur               arthur
3                Bremer               bremer
4       Carlo Pinsoglio      carlo pinsoglio
5        Daniele Rugani       daniele rugani
6          Douglas Luiz         douglas luiz
7        Dušan Vlahović       dusan vlahovic
8         Edon Zhegrova        edon zhegrova
9             Emil Holm            emil holm
10        Fabio Miretti        fabio miretti
11       Federico Gatti       federico gatti
12         Filip Kostić         filip kostic
13  Francisco Conceição  francisco conceicao
14         Jérémie Boga         jeremie boga
15           João Mário           joao mario
16       Jonathan David       jonathan david
17           Juan Cabal           juan cabal
18         Kenan Yıldız           kenan yldz
19      Khéphren Thuram      khephren thuram
20          Lloyd Kelly          lloyd kelly
21          Loïs Openda          lois openda
22     Manuel Locatelli     manuel locatelli
23         Mattia Perin         mattia perin
24  Michele Di Gregorio  michele di gregorio
25        Pierre Kalulu        pierre kalulu
26     Teun Koopmeiners     teun koopmeiners
27         Timothy Weah         timothy weah
28       Vasilije Adžić       vasilije adzic
29      Weston McKennie      weston mckennie

============================================================
  Lazio  —  SF sin salario:

                 player  minutesPlayed
0         Matias Vecino            605
1      Mattéo Guendouzi           1430
2  Valentín Castellanos            694

  CG plantilla completa:

                 player          player_norm
0          Adam Marusic         adam marusic
1      Adrian Przyborek     adrian przyborek
2    Alessio Furlanetto   alessio furlanetto
3     Alessio Romagnoli    alessio romagnoli
4           Boulaye Dia          boulaye dia
5       Christos Mandas      christos mandas
6        Daniel Maldini       daniel maldini
7        Danilo Cataldi       danilo cataldi
8         Edoardo Motta        edoardo motta
9          Elseid Hysaj         elseid hysaj
10  Fisayo Dele-Bashiru  fisayo dele bashiru
11       Gustav Isaksen       gustav isaksen
12        Ivan Provedel        ivan provedel
13       Kenneth Taylor       kenneth taylor
14      Luca Pellegrini      luca pellegrini
15       Manuel Lazzari       manuel lazzari
16           Mario Gila           mario gila
17   Matteo Cancellieri   matteo cancellieri
18      Mattia Zaccagni      mattia zaccagni
19       Nicolò Rovella       nicolo rovella
20         Nuno Tavares         nuno tavares
21   Oliver Provstgaard   oliver provstgaard
22               Patric               patric
23                Pedro                pedro
24         Petar Ratkov         petar ratkov
25       Reda Belahyane       reda belahyane
26         Samuel Gigot         samuel gigot
27       Tijjani Noslin       tijjani noslin
28           Toma Bašić           toma basic

============================================================
  Lecce  —  SF sin salario:

                player  minutesPlayed
0    Balthazar Pierret             32
1  Christ-Owen Kouassi            228
2         Mohamed Kaba            646
3          N'Dri Konan            495
4          Olaf Gorter             27
5         Tete Morente            859

  CG plantilla completa:

                    player             player_norm
0                Álex Sala               alex sala
1           Antonino Gallo          antonino gallo
2        Christian Früchtl       christian fruchtl
3             Corrie Ndaba            corrie ndaba
4             Danilo Veiga            danilo veiga
5        Filip Marchwinski       filip marchwinski
6        Francesco Camarda       francesco camarda
7                Gaby Jean               gaby jean
8            Jamil Siebert           jamil siebert
9           Jasper Samooja          jasper samooja
10         Kialonda Gaspar         kialonda gaspar
11             Konan N’Dri              konan ndri
12            Lameck Banda            lameck banda
13       Lassana Coulibaly       lassana coulibaly
14            Matías Pérez            matias perez
15           Medon Berisha           medon berisha
16           Nikola Stulic           nikola stulic
17          Omri Gandelman          omri gandelman
18              Oumar Ngom              oumar ngom
19         Riccardo Sottil         riccardo sottil
20            Sadik Fofana            sadik fofana
21       Santiago Pierotti       santiago pierotti
22  Thórir Jóhann Helgason  thorir johann helgason
23           Tiago Gabriel           tiago gabriel
24          Walid Cheddira          walid cheddira
25       Wladimiro Falcone       wladimiro falcone
26          Ylber Ramadani          ylber ramadani
27           Youssef Maleh           youssef maleh

============================================================
  Milan  —  SF sin salario:

                  player  minutesPlayed
0  Cheveyo Mul-Balentien              9
1       Samuel Chukwueze             25
2           Álex Jiménez             45

  CG plantilla completa:

                 player          player_norm
0         Adrien Rabiot        adrien rabiot
1          Álex Jiménez         alex jimenez
2   Alexis Saelemaekers  alexis saelemaekers
3         Ardon Jashari        ardon jashari
4     Christian Pulisic    christian pulisic
5    Christopher Nkunku   christopher nkunku
6           David Odogu          david odogu
7     Davide Bartesaghi    davide bartesaghi
8         Fikayo Tomori        fikayo tomori
9       Ismaël Bennacer      ismael bennacer
10       Koni De Winter       koni de winter
11      Lorenzo Colombo      lorenzo colombo
12     Lorenzo Torriani     lorenzo torriani
13          Luka Modrić          luka modric
14        Matteo Gabbia        matteo gabbia
15         Mike Maignan         mike maignan
16      Niclas Füllkrug      niclas fullkrug
17     Pervis Estupiñán     pervis estupinan
18   Pietro Terracciano   pietro terracciano
19          Rafael Leão          rafael leao
20   Ruben Loftus-Cheek   ruben loftus cheek
21     Samuel Chukwueze     samuel chukwueze
22        Samuele Ricci        samuele ricci
23     Santiago Gimenez     santiago gimenez
24   Strahinja Pavlović   strahinja pavlovic
25       Tommaso Pobega       tommaso pobega
26         Warren Bondo         warren bondo
27      Youssouf Fofana      youssouf fofana
28     Zachary Athekame     zachary athekame

============================================================
  Parma  —  SF sin salario:

                player  minutesPlayed
0    Adrian Benedyczak            486
1  Daniel Mikołajewski             18
2              Hernani             69
3        Mathias Løvik            479
4           Tjaš Begić              1

  CG plantilla completa:

                     player              player_norm
0          Abdoulaye Ndiaye         abdoulaye ndiaye
1            Adrián Bernabé           adrian bernabe
2        Alessandro Circati       alessandro circati
3           Benja Cremaschi          benja cremaschi
4             Botond Balogh            botond balogh
5         Christian Ordóñez        christian ordonez
6             Edoardo Corvi            edoardo corvi
7               Elia Plicco              elia plicco
8           Emanuele Valeri          emanuele valeri
9          Enrico Del Prato         enrico del prato
10          Filippo Rinaldi          filippo rinaldi
11           Franco Carboni           franco carboni
12        Gabriel Strefezza        gabriel strefezza
13        Gaetano Oristanio        gaetano oristanio
14         Gianluca Astaldi         gianluca astaldi
15  Hans Nicolussi Caviglia  hans nicolussi caviglia
16           Jacob Ondrejka           jacob ondrejka
17          Lautaro Valenti          lautaro valenti
18            Mandela Keita            mandela keita
19           Mariano Troilo           mariano troilo
20         Mateo Pellegrino         mateo pellegrino
21            Matija Frigan            matija frigan
22           Nahuel Estévez           nahuel estevez
23            Nesta Elphege            nesta elphege
24          Oliver Sørensen           oliver srensen
25          Patrick Cutrone          patrick cutrone
26          Pontus Almqvist          pontus almqvist
27         Sascha Britschgi         sascha britschgi
28              Zion Suzuki              zion suzuki

============================================================
  Pisa  —  SF sin salario:

              player  minutesPlayed
0  Giovanni Bonfanti            495
1       Louis Buffon             36
2    Mateus Lusuardi            199
3      Tomás Esteves             13

  CG plantilla completa:

                  player           player_norm
0          Adrian Semper         adrian semper
1     Antonio Caracciolo    antonio caracciolo
2       Arturo Calabresi      arturo calabresi
3          Calvin Stengs         calvin stengs
4          Daniel Denoon         daniel denoon
5   Ebenezer Akinsanmiro  ebenezer akinsanmiro
6          Felipe Loyola         felipe loyola
7      Filip Stojilkovic     filip stojilkovic
8      Francesco Coppola     francesco coppola
9     Gabriele Piccinini    gabriele piccinini
10        Henrik Meister        henrik meister
11         Idrissa Touré         idrissa toure
12            İsak Vural            isak vural
13         Juan Cuadrado         juan cuadrado
14                Lorran                lorran
15          M'Bala Nzola          m bala nzola
16        Malthe Højholt         malthe hjholt
17          Marius Marin          marius marin
18        Matteo Tramoni        matteo tramoni
19           Mehdi Léris           mehdi leris
20      Michel Aebischer      michel aebischer
21               Nícolas               nicolas
22       Rafiu Durosinmi       rafiu durosinmi
23           Raúl Albiol           raul albiol
24        Rosen Bozhinov        rosen bozhinov
25   Samuel Iling-Junior   samuel iling junior
26        Samuele Angori        samuele angori
27    Simone Canestrelli    simone canestrelli
28        Simone Scuffet        simone scuffet
29         Stefano Moreo         stefano moreo

============================================================
  Roma  —  SF sin salario:

              player  minutesPlayed
0  Alessandro Romano             10
1      Antonio Arena             25
2        Leon Bailey            182

  CG plantilla completa:

                   player            player_norm
0                Angeliño               angelino
1            Artem Dovbyk           artem dovbyk
2         Bryan Cristante        bryan cristante
3          Bryan Zaragoza         bryan zaragoza
4        Daniele Ghilardi       daniele ghilardi
5           Devis Vásquez          devis vasquez
6           Devyne Rensch          devyne rensch
7           Donyell Malen          donyell malen
8        Eldor Shomurodov       eldor shomurodov
9           Evan Ferguson          evan ferguson
10           Evan N'Dicka           evan n dicka
11       Gianluca Mancini       gianluca mancini
12         Jan Ziolkowski         jan ziolkowski
13  Konstantinos Tsimikas  konstantinos tsimikas
14           Kouadio Koné           kouadio kone
15     Lorenzo Pellegrini     lorenzo pellegrini
16      Lorenzo Venturino      lorenzo venturino
17        Marash Kumbulla        marash kumbulla
18          Mario Hermoso          mario hermoso
19           Matías Soulé           matias soule
20            Mile Svilar            mile svilar
21        Neil El Aynaoui        neil el aynaoui
22        Niccolò Pisilli        niccolo pisilli
23           Paulo Dybala           paulo dybala
24      Pierluigi Gollini      pierluigi gollini
25       Radoslaw Zelezny       radoslaw zelezny
26        Riccardo Pagano        riccardo pagano
27            Robinio Vaz            robinio vaz
28        Saud Abdulhamid        saud abdulhamid
29    Stephan El Shaarawy    stephan el shaarawy
30       Tommaso Baldanzi       tommaso baldanzi
31                 Wesley                 wesley
32             Zeki Çelik             zeki celik

============================================================
  Sassuolo  —  SF sin salario:

         player  minutesPlayed
0  Andrea Ghion              9
1  Cas Odenthal              1

  CG plantilla completa:

                   player            player_norm
0            Alieu Fadera           alieu fadera
1        Andrea Pinamonti       andrea pinamonti
2          Arijanet Murić         arijanet muric
3        Armand Laurienté       armand lauriente
4           Aster Vranckx          aster vranckx
5        Cristian Volpato       cristian volpato
6           Daniel Boloca          daniel boloca
7           Darryl Bakola          darryl bakola
8        Domenico Berardi       domenico berardi
9         Edoardo Iannoni        edoardo iannoni
10     Edoardo Pieragnolo     edoardo pieragnolo
11             Fali Candé             fali cande
12        Filippo Romagna        filippo romagna
13       Giacomo Satalino       giacomo satalino
14          Gioele Zacchi          gioele zacchi
15            Ismaël Koné            ismael kone
16              Jay Idzes              jay idzes
17              Josh Doig              josh doig
18    Kristian Thorstvedt    kristian thorstvedt
19       Laurs Skjellerup       laurs skjellerup
20            Luca Lipani            luca lipani
21              Luca Moro              luca moro
22           M'Bala Nzola           m bala nzola
23          Nemanja Matić          nemanja matic
24       Nicholas Pierini       nicholas pierini
25           Pedro Felipe           pedro felipe
26  Sebastian Walukiewicz  sebastian walukiewicz
27         Stefano Turati         stefano turati
28      Tarik Muharemović      tarik muharemovic
29         Ulisses Garcia         ulisses garcia
30         Woyo Coulibaly         woyo coulibaly

============================================================
  Torino  —  SF sin salario:

             player  minutesPlayed
0       Adam Masina            232
1  Kristjan Asllani           1135

  CG plantilla completa:

                      player               player_norm
0              Adrien Tamèze             adrien tameze
1            Alberto Paleari           alberto paleari
2                Ali Dembélé               ali dembele
3                 Alieu Njie                alieu njie
4             Ardian Ismajli            ardian ismajli
5             Cesare Casadei            cesare casadei
6                  Ché Adams                 che adams
7          Cristiano Biraghi         cristiano biraghi
8               Cyril Ngonge              cyril ngonge
9               Duván Zapata              duvan zapata
10            Emirhan İlkhan            emirhan ilkhan
11               Enzo Ebosse               enzo ebosse
12             Franco Israel             franco israel
13          Giovanni Simeone          giovanni simeone
14         Guillermo Maripán         guillermo maripan
15           Gvidas Gineitis           gvidas gineitis
16                 Ivan Ilić                 ivan ilic
17              Lapo Siviero              lapo siviero
18           Luca Marianucci           luca marianucci
19  Marcus Holmgren Pedersen  marcus holmgren pedersen
20              Matteo Prati              matteo prati
21            Niels Nkounkou            niels nkounkou
22             Nikola Vlašić             nikola vlasic
23              Perr Schuurs              perr schuurs
24              Rafa Obrador              rafa obrador
25              Saba Sazonov              saba sazonov
26          Sandro Kulenović          sandro kulenovic
27                 Saúl Coco                 saul coco
28            Sergiu Perciun            sergiu perciun
29              Tino Anjorin              tino anjorin
30          Valentino Lazaro          valentino lazaro
31         Zakaria Aboukhlal         zakaria aboukhlal
32               Zanos Savva               zanos savva

============================================================
  Udinese  —  SF sin salario:

             player  minutesPlayed
0  Saba Goglichidze            422

  CG plantilla completa:

                  player           player_norm
0       Abdoulaye Camara      abdoulaye camara
1             Adam Buksa            adam buksa
2   Alessandro Nunziante  alessandro nunziante
3      Alessandro Zanoli     alessandro zanoli
4            Arthur Atta           arthur atta
5        Branimir Mlacic       branimir mlacic
6                Brenner               brenner
7     Christian Kabasele    christian kabasele
8        Daniele Padelli       daniele padelli
9         Hassane Kamara        hassane kamara
10         Idrissa Gueye         idrissa gueye
11            Iker Bravo            iker bravo
12      Jakub Piotrowski      jakub piotrowski
13      Jesper Karlström      jesper karlstrom
14         Jordan Zemura         jordan zemura
15          Juan Arizala          juan arizala
16    Jurgen Ekkelenkamp    jurgen ekkelenkamp
17          Keinan Davis          keinan davis
18     Kingsley Ehizibue     kingsley ehizibue
19         Lennon Miller         lennon miller
20          Maduka Okoye          maduka okoye
21          Matteo Palma          matteo palma
22        Nicolò Bertola        nicolo bertola
23        Nicolò Zaniolo        nicolo zaniolo
24          Oier Zarraga          oier zarraga
25           Oumar Solet           oumar solet
26           Răzvan Sava           razvan sava
27           Rui Modesto           rui modesto
28          Sandi Lovrić          sandi lovric
29     Thomas Kristensen     thomas kristensen
30    Vakoun Issouf Bayo    vakoun issouf bayo

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 511/561 (91.1%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

⚠️ Nombre con sufijo `_snapshot_20260428` para diferenciar del master definitivo
que se generará al cierre de la temporada (`master_italy_2526.csv`).

In [21]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_italy_2526_snapshot_20260428.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_italy_2526_snapshot_20260428.csv
   Jugadores totales:  561
   Con salario:        511
   Sin salario (NaN):  50
   Columnas:           122