# 03 · Join Sofascore + Capology — Italy Serie A 23/24

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2023/24 de Serie A italiana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_italy_2324.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_italy_2324.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  590 jugadores | 116 columnas
Capology:   659 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   inter
   milan

En Capology pero no en Sofascore:
   ac milan
   inter milan

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'ac milan':'milan',
            'inter milan':'inter'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 538/590 (91.2%)
Sin emparejar: 52

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          11
Revisión media    (0.75 ≤ score < 0.90):   3
Revisión estricta (0.50 ≤ score < 0.75):   21
Revisión muy est. (score < 0.50):           17

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf           team               cg_match  score
27  Pantelis Hatzidiakos       Cagliari  pantelis chatzidiakos  0.976
2     Albert Guðmundsson          Genoa     albert gudmundsson  0.971
16      Paweł Dawidowicz  Hellas Verona       pawel dawidowicz  0.968
9       Łukasz Skorupski        Bologna       lukasz skorupski  0.968
43      Mateusz Łęgowski    Salernitana       mateusz legowski  0.968
10           Evan Ndicka           Roma           evan n dicka  0.957
4      Aleksei Miranchuk       Atalanta      aleksey miranchuk  0.941
42        Filip Jagiełło          Genoa         filip jagiello  0.923
26            Dani Silva  Hellas Verona           daniel silva  0.909
6            Milan Đurić          Monza           milan djuric  0.909
14            Simon Kjær          Milan            simon kjaer  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

          player_sf      team                  cg_match  score
3      Yann Bisseck     Inter        yann aurel bisseck  0.800
44     Michel Adopo  Atalanta        michel ndary adopo  0.800
21  Marcus Pedersen  Sassuolo  marcus holmgren pedersen  0.769

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 3 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf         team               cg_match  score
37         Leonardo Cerri     Juventus       leonardo bonucci  0.733
5      Mario Gila Fuentes        Lazio             mario gila  0.714
38      Mamadou Coulibaly  Salernitana      lassana coulibaly  0.706
7   Federico Di Francesco        Lecce    federico brancolini  0.700
17        Andrea Ferraris        Monza         andrea carboni  0.690
35                Vivaldo      Udinese         vivaldo semedo  0.667
8          Frank Anguissa       Napoli   andre zambo anguissa  0.647
25      Davide Bartesaghi        Milan        davide calabria  0.625
41      Nicolás Domínguez      Bologna       nicola bagnolini  0.606
39          Luigi Canotto    Frosinone     pierluigi frattali  0.581
1            Nicolas Haas       Empoli       nicolo cambiaghi  0.571
40          Andrea Sodero       Empoli          mattia destro  0.538
30        Niccolò Pisilli         Roma        nicola zalewski  0.533
12  Alessandro Dellavalle       Torino  alessandro buongiorno  0.524
15            Zanos Savva       Torino       antonio sanabria  0.519
0         Davide Biraschi        Genoa           david ankeye  0.519
45       Gennaro Borrelli    Frosinone            karlo lulic  0.519
36         Liam Henderson       Empoli          mattia destro  0.519
28           Álex Jiménez        Milan    alexis saelemaekers  0.516
33          Gerardo Fusco  Salernitana        guillermo ochoa  0.500
46      Francesco Camarda        Milan        davide calabria  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mario gila fuentes',
                    'vivaldo',
                    'frank anguissa'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 3

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf           team              cg_match  score
22          Ola Solbakken           Roma      tommaso baldanzi  0.483
34             João Costa           Roma       bryan cristante  0.480
23           Simone Verdi         Torino         samuele ricci  0.480
24         Giacomo Corona         Empoli      nicolo cambiaghi  0.467
11        Jan-Carlo Simić          Milan           yacine adli  0.462
51            Justin Kumi       Sassuolo       agustin alvarez  0.462
47         Nikola Sekulov       Juventus          matias soule  0.462
18   Ebenezer Akinsanmiro          Inter       benjamin pavard  0.457
20     Kingstone Mutandwa       Cagliari     antoine makoumbou  0.457
49           Joseph Nonge       Juventus            moise kean  0.455
31         Alphadjo Cissè  Hellas Verona         mattia chiesa  0.444
48          Kevin Miranda       Sassuolo        alessio cragno  0.444
13                   Beto        Udinese       roberto pereyra  0.421
29            Seydou Fini          Genoa         radu dragusin  0.417
19   Przemysław Szymiński      Frosinone            demba seck  0.414
50     Leonardo Mendicino       Atalanta      giorgio scalvini  0.412
32  Christos Papadopoulos          Genoa  alessandro vogliacco  0.390

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 555/590 (94.1%)
Sin salario:     35

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 35

,player,team,minutesPlayed,appearances,goals,assists
0,Leonardo Mendicino,Atalanta,1,1,0,0
1,Nicolás Domínguez,Bologna,101,2,0,0
2,Kingstone Mutandwa,Cagliari,52,5,1,0
3,Nicolas Haas,Empoli,90,1,0,0
4,Liam Henderson,Empoli,11,1,0,0
5,Giacomo Corona,Empoli,9,1,0,0
6,Andrea Sodero,Empoli,9,1,0,0
7,Gennaro Borrelli,Frosinone,23,1,0,0
8,Luigi Canotto,Frosinone,15,1,0,0
9,Przemysław Szymiński,Frosinone,8,1,0,0
10,Davide Biraschi,Genoa,90,1,1,0
11,Seydou Fini,Genoa,41,3,0,0
12,Christos Papadopoulos,Genoa,8,1,0,0
13,Alphadjo Cissè,Hellas Verona,11,1,0,0
14,Ebenezer Akinsanmiro,Inter,14,1,0,0
15,Joseph Nonge,Juventus,22,2,0,0
16,Leonardo Cerri,Juventus,11,1,0,0
17,Nikola Sekulov,Juventus,10,1,0,0
18,Federico Di Francesco,Lecce,21,2,1,0
19,Jan-Carlo Simić,Milan,143,4,1,0
20,Davide Bartesaghi,Milan,90,6,0,0
21,Álex Jiménez,Milan,65,3,0,0
22,Francesco Camarda,Milan,26,2,0,0
23,Andrea Ferraris,Monza,9,1,0,0
24,João Costa,Roma,29,3,0,0
25,Ola Solbakken,Roma,22,1,0,0
26,Niccolò Pisilli,Roma,9,1,0,0
27,Gerardo Fusco,Salernitana,14,1,0,0
28,Mamadou Coulibaly,Salernitana,9,1,0,0
29,Kevin Miranda,Sassuolo,12,1,0,0
30,Justin Kumi,Sassuolo,3,1,0,0
31,Zanos Savva,Torino,30,2,1,0
32,Alessandro Dellavalle,Torino,14,1,0,0
33,Simone Verdi,Torino,10,1,0,0
34,Beto,Udinese,74,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Atalanta  —  SF sin salario:

               player  minutesPlayed
0  Leonardo Mendicino              1

  CG plantilla completa:

                  player           player_norm
0        Ademola Lookman       ademola lookman
1      Aleksey Miranchuk     aleksey miranchuk
2         Berat Djimsiti        berat djimsiti
3   Charles De Ketelaere  charles de ketelaere
4      Davide Zappacosta     davide zappacosta
5                Éderson               ederson
6         El Bilal Touré        el bilal toure
7              Emil Holm             emil holm
8        Francesco Rossi       francesco rossi
9      Gianluca Scamacca     gianluca scamacca
10      Giorgio Scalvini      giorgio scalvini
11     Giovanni Bonfanti     giovanni bonfanti
12         Hans Hateboer         hans hateboer
13             Isak Hien             isak hien
14    José Luis Palomino    jose luis palomino
15            Juan Musso            juan musso
16           Luis Muriel           luis muriel
17     Marco Carnesecchi     marco carnesecchi
18         Mario Pasalic         mario pasalic
19        Marten de Roon        marten de roon
20        Matteo Ruggeri        matteo ruggeri
21    Michel Ndary Adopo    michel ndary adopo
22        Mitchel Bakker        mitchel bakker
23          Nadir Zortea          nadir zortea
24          Rafael Tolói          rafael toloi
25        Sead Kolasinac        sead kolasinac
26      Teun Koopmeiners      teun koopmeiners

============================================================
  Bologna  —  SF sin salario:

              player  minutesPlayed
0  Nicolás Domínguez            101

  CG plantilla completa:

                     player              player_norm
0            Adama Soumaoro           adama soumaoro
1       Alexis Saelemaekers      alexis saelemaekers
2   Charalampos Lykogiannis  charalampos lykogiannis
3                 Dan Ndoye                dan ndoye
4         Federico Ravaglia        federico ravaglia
5          Giovanni Fabbian         giovanni fabbian
6              Jens Odgaard             jens odgaard
7           Jesper Karlsson          jesper karlsson
8               Jhon Lucumí              jhon lucumi
9              Joaquín Sosa             joaquin sosa
10           Joshua Zirkzee           joshua zirkzee
11          Kacper Urbanski          kacper urbanski
12           Kevin Bonifazi           kevin bonifazi
13           Lewis Ferguson           lewis ferguson
14     Lorenzo De Silvestri     lorenzo de silvestri
15         Lukasz Skorupski         lukasz skorupski
16         Michel Aebischer         michel aebischer
17             Mihajlo Ilic             mihajlo ilic
18              Musa Barrow              musa barrow
19         Nicola Bagnolini         nicola bagnolini
20              Nikola Moro              nikola moro
21       Oussama El Azzouzi       oussama el azzouzi
22             Remo Freuler             remo freuler
23       Riccardo Calafiori       riccardo calafiori
24        Riccardo Orsolini        riccardo orsolini
25              Sam Beukema              sam beukema
26          Santiago Castro          santiago castro
27             Stefan Posch             stefan posch
28     Sydney van Hooijdonk     sydney van hooijdonk
29          Tommaso Corazza          tommaso corazza
30       Victor Kristiansen       victor kristiansen

============================================================
  Cagliari  —  SF sin salario:

               player  minutesPlayed
0  Kingstone Mutandwa             52

  CG plantilla completa:

                   player            player_norm
0              Adam Obert             adam obert
1         Alberto Dossena        alberto dossena
2       Alessandro Deiola      alessandro deiola
3     Alessandro Di Pardo    alessandro di pardo
4          Andrea Petagna         andrea petagna
5       Antoine Makoumbou      antoine makoumbou
6         Boris Radunović        boris radunovic
7       Edoardo Goldaniga      edoardo goldaniga
8        Eldor Shomurodov       eldor shomurodov
9         Elio Capradossi        elio capradossi
10         Gabriele Zappa         gabriele zappa
11      Gaetano Oristanio      gaetano oristanio
12         Gastón Pereiro         gaston pereiro
13       Gianluca Gaetano       gianluca gaetano
14      Gianluca Lapadula      gianluca lapadula
15       Ibrahim Sulemana       ibrahim sulemana
16         Jacopo Desogus         jacopo desogus
17           Jakub Jankto           jakub jankto
18     Leonardo Pavoletti     leonardo pavoletti
19          Marco Mancosu          marco mancosu
20              Marko Rog              marko rog
21       Mateusz Wieteska       mateusz wieteska
22           Matteo Prati           matteo prati
23         Nahitan Nández         nahitan nandez
24          Nicolas Viola          nicolas viola
25  Pantelis Chatzidiakos  pantelis chatzidiakos
26             Paulo Azzi             paulo azzi
27          Simone Aresti          simone aresti
28         Simone Scuffet         simone scuffet
29        Tommaso Augello        tommaso augello
30             Yerry Mina             yerry mina
31           Zito Luvumbo           zito luvumbo

============================================================
  Empoli  —  SF sin salario:

           player  minutesPlayed
0   Andrea Sodero              9
1  Giacomo Corona              9
2  Liam Henderson             11
3    Nicolas Haas             90

  CG plantilla completa:

                   player            player_norm
0           Alberto Cerri          alberto cerri
1          Alberto Grassi         alberto grassi
2          Ardian Ismajli         ardian ismajli
3     Bartosz Bereszynski    bartosz bereszynski
4          Daniel Maldini         daniel maldini
5            Elia Caprile           elia caprile
6          Emmanuel Ekong         emmanuel ekong
7          Emmanuel Gyasi         emmanuel gyasi
8           Etrit Berisha          etrit berisha
9       Filippo Ranocchia      filippo ranocchia
10       Francesco Caputo       francesco caputo
11       Gabriele Guarino       gabriele guarino
12      Giuseppe Pezzella      giuseppe pezzella
13         Jacopo Fazzini         jacopo fazzini
14        Liberato Cacace        liberato cacace
15        Lorenzo Tonelli        lorenzo tonelli
16         Lovro Stubljar         lovro stubljar
17      Luca Belardinelli      luca belardinelli
18           M'Baye Niang           m baye niang
19     Matteo Cancellieri     matteo cancellieri
20          Mattia Destro          mattia destro
21       Nicolò Cambiaghi       nicolo cambiaghi
22           Răzvan Marin           razvan marin
23       Saba Goglichidze       saba goglichidze
24        Samuele Perisan        samuele perisan
25  Sebastian Walukiewicz  sebastian walukiewicz
26     Sebastiano Luperto     sebastiano luperto
27         Simone Bastoni         simone bastoni
28         Stiven Shpendi         stiven shpendi
29       Szymon Zurkowski       szymon zurkowski
30       Tommaso Baldanzi       tommaso baldanzi
31         Tyronne Ebuehi         tyronne ebuehi
32       Viktor Kovalenko       viktor kovalenko
33          Youssef Maleh          youssef maleh

============================================================
  Frosinone  —  SF sin salario:

                 player  minutesPlayed
0      Gennaro Borrelli             23
1         Luigi Canotto             15
2  Przemysław Szymiński              8

  CG plantilla completa:

                   player            player_norm
0           Abdou Harroui          abdou harroui
1           Anthony Oyono          anthony oyono
2      Arijon Ibrahimovic     arijon ibrahimovic
3             Caleb Okoli            caleb okoli
4            Daniel Macej           daniel macej
5              Demba Seck             demba seck
6         Emanuele Valeri        emanuele valeri
7        Enzo Barrenechea       enzo barrenechea
8         Farès Ghedjemis        fares ghedjemis
9         Francesco Gelli        francesco gelli
10       Giorgi Kvernadze       giorgi kvernadze
11          Giuseppe Caso          giuseppe caso
12       Ilario Monterisi       ilario monterisi
13             İsak Vural             isak vural
14             Jaime Báez             jaime baez
15             Kaio Jorge             kaio jorge
16            Karlo Lulic            karlo lulic
17         Kevin Bonifazi         kevin bonifazi
18         Luca Garritano         luca garritano
19        Luca Mazzitelli        luca mazzitelli
20      Marco Brescianini      marco brescianini
21            Marvin Cuni            marvin cuni
22        Mateus Lusuardi        mateus lusuardi
23           Matías Soulé           matias soule
24  Matjaz Kamensek-Pahic  matjaz kamensek pahic
25         Mehdi Bourabia         mehdi bourabia
26     Michele Cerofolini     michele cerofolini
27           Nadir Zortea           nadir zortea
28     Pierluigi Frattali     pierluigi frattali
29             Pol Lirola             pol lirola
30                Reinier                reinier
31     Riccardo Marchizza     riccardo marchizza
32           Sergio Kalaj           sergio kalaj
33       Simone Romagnoli       simone romagnoli
34       Soufiane Bidaoui       soufiane bidaoui
35         Stefano Turati         stefano turati
36         Walid Cheddira         walid cheddira

============================================================
  Genoa  —  SF sin salario:

                  player  minutesPlayed
0  Christos Papadopoulos              8
1        Davide Biraschi             90
2            Seydou Fini             41

  CG plantilla completa:

                  player           player_norm
0           Aarón Martín          aaron martin
1          Alan Matturro         alan matturro
2     Albert Gudmundsson    albert gudmundsson
3   Alessandro Vogliacco  alessandro vogliacco
4           Berkan Kutlu          berkan kutlu
5           Caleb Ekuban          caleb ekuban
6      Daniele Sommariva     daniele sommariva
7           David Ankeye          david ankeye
8            Djed Spence           djed spence
9           Emil Bohinen          emil bohinen
10        Filip Jagiello        filip jagiello
11           Franz Stolz           franz stolz
12         George Puscas         george puscas
13     Giorgio Cittadini     giorgio cittadini
14         Johan Vásquez         johan vasquez
15        Josep Martínez        josep martinez
16        Junior Messias        junior messias
17       Kevin Strootman       kevin strootman
18        Koni De Winter        koni de winter
19       Léandre Kuavita       leandre kuavita
20         Mateo Retegui         mateo retegui
21           Mattia Bani           mattia bani
22          Milan Badelj          milan badelj
23       Morten Frendrup       morten frendrup
24        Morten Thorsby        morten thorsby
25          Nicola Leali          nicola leali
26        Pablo Galdames        pablo galdames
27         Radu Dragusin         radu dragusin
28       Ridgeciano Haps       ridgeciano haps
29    Ruslan Malinovskyi    ruslan malinovskyi
30          Silvan Hefti          silvan hefti
31        Simone Calvani        simone calvani
32       Stefano Sabelli       stefano sabelli
33               Vitinha               vitinha

============================================================
  Hellas Verona  —  SF sin salario:

           player  minutesPlayed
0  Alphadjo Cissè             11

  CG plantilla completa:

                 player          player_norm
0         Ajdin Hrustic        ajdin hrustic
1    Alessandro Berardi   alessandro berardi
2          Bruno Amione         bruno amione
3               Charlys              charlys
4          Cyril Ngonge         cyril ngonge
5          Daniel Silva         daniel silva
6         Darko Lazović        darko lazovic
7        Davide Faraoni       davide faraoni
8         Diego Coppola        diego coppola
9         Elayis Tavsan        elayis tavsan
10      Fabien Centonze      fabien centonze
11   Federico Bonazzoli   federico bonazzoli
12  Filippo Terracciano  filippo terracciano
13  Giangiacomo Magnani  giangiacomo magnani
14            Isak Hien            isak hien
15   Jackson Tchatchoua   jackson tchatchoua
16         Jayden Braaf         jayden braaf
17         Jordi Mboula         jordi mboula
18             Joselito             joselito
19            Josh Doig            josh doig
20           Juan Cabal           juan cabal
21     Juan Manuel Cruz     juan manuel cruz
22      Karol Świderski      karol swiderski
23          Kevin Rüegg          kevin ruegg
24         Koray Günter         koray gunter
25      Lorenzo Montipò      lorenzo montipo
26        Martin Hongla        martin hongla
27        Mattia Chiesa        mattia chiesa
28   Michael Folorunsho   michael folorunsho
29         Milan Djuric         milan djuric
30          Ondrej Duda          ondrej duda
31     Pawel Dawidowicz     pawel dawidowicz
32       Reda Belahyane       reda belahyane
33    Riccardo Saponara    riccardo saponara
34        Rúben Vinagre        ruben vinagre
35       Simone Perilli       simone perilli
36      Stefan Mitrovic      stefan mitrovic
37          Suat Serdar          suat serdar
38         Thomas Henry         thomas henry
39       Tijjani Noslin       tijjani noslin
40         Tomas Suslov         tomas suslov
41         Yayah Kallon         yayah kallon

============================================================
  Inter  —  SF sin salario:

                 player  minutesPlayed
0  Ebenezer Akinsanmiro             14

  CG plantilla completa:

                 player          player_norm
0    Alessandro Bastoni   alessandro bastoni
1        Alexis Sánchez       alexis sanchez
2       Benjamin Pavard      benjamin pavard
3        Carlos Augusto       carlos augusto
4       Davide Frattesi      davide frattesi
5         Davy Klaassen        davy klaassen
6       Denzel Dumfries      denzel dumfries
7           Emil Audero          emil audero
8      Federico Dimarco     federico dimarco
9      Francesco Acerbi     francesco acerbi
10     Hakan Çalhanoğlu     hakan calhanoglu
11   Henrikh Mkhitaryan   henrikh mkhitaryan
12       Joaquín Correa       joaquin correa
13        Juan Cuadrado        juan cuadrado
14     Kristjan Asllani     kristjan asllani
15     Lautaro Martínez     lautaro martinez
16        Lucien Agoume        lucien agoume
17        Marcus Thuram        marcus thuram
18     Marko Arnautovic     marko arnautovic
19       Matteo Darmian       matteo darmian
20       Nicolò Barella       nicolo barella
21  Raffaele Di Gennaro  raffaele di gennaro
22       Stefan de Vrij       stefan de vrij
23        Stefano Sensi        stefano sensi
24       Tajon Buchanan       tajon buchanan
25   Yann Aurel Bisseck   yann aurel bisseck
26          Yann Sommer          yann sommer

============================================================
  Juventus  —  SF sin salario:

           player  minutesPlayed
0    Joseph Nonge             22
1  Leonardo Cerri             11
2  Nikola Sekulov             10

  CG plantilla completa:

                     player              player_norm
0             Adrien Rabiot            adrien rabiot
1               Alex Sandro              alex sandro
2           Andrea Cambiaso          andrea cambiaso
3           Arkadiusz Milik          arkadiusz milik
4                    Arthur                   arthur
5                    Bremer                   bremer
6           Carlo Pinsoglio          carlo pinsoglio
7            Carlos Alcaraz           carlos alcaraz
8            Daniele Rugani           daniele rugani
9                    Danilo                   danilo
10           Dusan Vlahovic           dusan vlahovic
11            Fabio Miretti            fabio miretti
12         Facundo González         facundo gonzalez
13          Federico Chiesa          federico chiesa
14           Federico Gatti           federico gatti
15             Filip Kostic             filip kostic
16  Hans Nicolussi Caviglia  hans nicolussi caviglia
17               Kaio Jorge               kaio jorge
18             Kenan Yıldız               kenan yldz
19         Leonardo Bonucci         leonardo bonucci
20         Manuel Locatelli         manuel locatelli
21             Matías Soulé             matias soule
22        Mattia De Sciglio        mattia de sciglio
23             Mattia Perin             mattia perin
24               Moise Kean               moise kean
25           Nicolò Fagioli           nicolo fagioli
26               Paul Pogba               paul pogba
27      Samuel Iling-Junior      samuel iling junior
28              Tiago Djaló              tiago djalo
29             Timothy Weah             timothy weah
30          Weston McKennie          weston mckennie
31        Wojciech Szczesny        wojciech szczesny

============================================================
  Lecce  —  SF sin salario:

                  player  minutesPlayed
0  Federico Di Francesco             21

  CG plantilla completa:

                  player           player_norm
0            Ahmed Touba           ahmed touba
1       Alexandru Borbei      alexandru borbei
2            Alexis Blin           alexis blin
3         Antonino Gallo        antonino gallo
4           Daniel Samek          daniel samek
5   Federico Baschirotto  federico baschirotto
6    Federico Brancolini   federico brancolini
7      Gabriel Strefezza     gabriel strefezza
8      Giacomo Faticanti     giacomo faticanti
9            Hamza Rafia           hamza rafia
10        Jasper Samooja        jasper samooja
11       Jeppe Corfitzen       jeppe corfitzen
12         Joan González         joan gonzalez
13      Kastriot Dermaku      kastriot dermaku
14          Lameck Banda          lameck banda
15        Lorenzo Venuti        lorenzo venuti
16     Marcin Listkowski     marcin listkowski
17       Marin Pongracic       marin pongracic
18         Medon Berisha         medon berisha
19          Mohamed Kaba          mohamed kaba
20        Nicola Sansone        nicola sansone
21       Nikola Krstovic       nikola krstovic
22         Patrick Dorgu         patrick dorgu
23       Pontus Almqvist       pontus almqvist
24         Rareș Burnete         rares burnete
25            Rémi Oudin            remi oudin
26       Roberto Piccoli       roberto piccoli
27     Santiago Pierotti     santiago pierotti
28      Valentin Gendrey      valentin gendrey
29     Wladimiro Falcone     wladimiro falcone
30        Ylber Ramadani        ylber ramadani
31     Zinedin Smajlovic     zinedin smajlovic

============================================================
  Milan  —  SF sin salario:

              player  minutesPlayed
0  Davide Bartesaghi             90
1  Francesco Camarda             26
2    Jan-Carlo Simić            143
3       Álex Jiménez             65

  CG plantilla completa:

                 player          player_norm
0   Alessandro Florenzi  alessandro florenzi
1   Alexis Saelemaekers  alexis saelemaekers
2       Antonio Mirante      antonio mirante
3          Chaka Traorè         chaka traore
4     Christian Pulisic    christian pulisic
5       Davide Calabria      davide calabria
6         Fikayo Tomori        fikayo tomori
7   Filippo Terracciano  filippo terracciano
8       Ismaël Bennacer      ismael bennacer
9          Kevin Zeroli         kevin zeroli
10            Lapo Nava            lapo nava
11           Luka Jovic           luka jovic
12          Luka Romero          luka romero
13         Malick Thiaw         malick thiaw
14     Marco Pellegrino     marco pellegrino
15     Marco Sportiello     marco sportiello
16        Matteo Gabbia        matteo gabbia
17       Mattia Caldara       mattia caldara
18         Mike Maignan         mike maignan
19          Noah Okafor          noah okafor
20       Olivier Giroud       olivier giroud
21        Pierre Kalulu        pierre kalulu
22          Rade Krunic          rade krunic
23          Rafael Leão          rafael leao
24   Ruben Loftus-Cheek   ruben loftus cheek
25     Samuel Chukwueze     samuel chukwueze
26          Simon Kjaer          simon kjaer
27       Theo Hernández       theo hernandez
28    Tijjani Reijnders    tijjani reijnders
29       Tommaso Pobega       tommaso pobega
30          Yacine Adli          yacine adli
31          Yunus Musah          yunus musah

============================================================
  Monza  —  SF sin salario:

            player  minutesPlayed
0  Andrea Ferraris              9

  CG plantilla completa:

                    player             player_norm
0    Alessandro Sorrentino   alessandro sorrentino
1           Alessio Zerbin          alessio zerbin
2           Andrea Carboni          andrea carboni
3           Andrea Colpani          andrea colpani
4        Armando Anastasio       armando anastasio
5             Armando Izzo            armando izzo
6           Daniel Maldini          daniel maldini
7        Danilo D'Ambrosio       danilo d ambrosio
8                Dany Mota               dany mota
9          Davide Bettella         davide bettella
10         Eugenio Lamanna         eugenio lamanna
11          Franco Carboni          franco carboni
12  Georgios Kyriakopoulos  georgios kyriakopoulos
13        Gianluca Caprari        gianluca caprari
14       Giorgio Cittadini       giorgio cittadini
15           Giulio Donati           giulio donati
16  Jean-Daniel Akpa Akpro  jean daniel akpa akpro
17             José Machín             jose machin
18         Lorenzo Colombo         lorenzo colombo
19          Luca Caldirola          luca caldirola
20          Matija Popovic          matija popovic
21          Matteo Pessina          matteo pessina
22     Michele Di Gregorio     michele di gregorio
23            Milan Djuric            milan djuric
24             Mirko Maric             mirko maric
25              Pablo Marí              pablo mari
26              Papu Gómez              papu gomez
27         Patrick Ciurria         patrick ciurria
28           Pedro Pereira           pedro pereira
29     Roberto Gagliardini     roberto gagliardini
30      Samuele Birindelli      samuele birindelli
31         Samuele Vignato         samuele vignato
32            Stefano Gori            stefano gori
33        Valentín Carboni        valentin carboni
34            Warren Bondo            warren bondo

============================================================
  Roma  —  SF sin salario:

            player  minutesPlayed
0       João Costa             29
1  Niccolò Pisilli              9
2    Ola Solbakken             22

  CG plantilla completa:

                 player          player_norm
0        Andrea Belotti       andrea belotti
1              Angeliño             angelino
2       Bryan Cristante      bryan cristante
3        Chris Smalling       chris smalling
4          Dean Huijsen         dean huijsen
5        Diego Llorente       diego llorente
6          Edoardo Bove         edoardo bove
7      Eldor Shomurodov     eldor shomurodov
8          Evan N'Dicka         evan n dicka
9      Gianluca Mancini     gianluca mancini
10        Houssem Aouar        houssem aouar
11      Leandro Paredes      leandro paredes
12  Leonardo Spinazzola  leonardo spinazzola
13   Lorenzo Pellegrini   lorenzo pellegrini
14      Marash Kumbulla      marash kumbulla
15          Matías Viña          matias vina
16          Mile Svilar          mile svilar
17      Nicola Zalewski      nicola zalewski
18         Paulo Dybala         paulo dybala
19          Pietro Boer          pietro boer
20    Rasmus Kristensen    rasmus kristensen
21       Renato Sanches       renato sanches
22      Riccardo Pagano      riccardo pagano
23        Rick Karsdorp        rick karsdorp
24        Romelu Lukaku        romelu lukaku
25         Rui Patrício         rui patricio
26        Sardar Azmoun        sardar azmoun
27  Stephan El Shaarawy  stephan el shaarawy
28        Tammy Abraham        tammy abraham
29     Tommaso Baldanzi     tommaso baldanzi
30           Zeki Çelik           zeki celik

============================================================
  Salernitana  —  SF sin salario:

              player  minutesPlayed
0      Gerardo Fusco             14
1  Mamadou Coulibaly              9

  CG plantilla completa:

                     player              player_norm
0         Agustín Martegani        agustin martegani
1         Alessandro Zanoli        alessandro zanoli
2              Andres Sfait             andres sfait
3          Antonio Candreva         antonio candreva
4             Benoît Costil            benoit costil
5               Boulaye Dia              boulaye dia
6    Chukwubuikem Ikwuemesi   chukwubuikem ikwuemesi
7            Diego Valencia           diego valencia
8          Domagoj Bradaric         domagoj bradaric
9               Dylan Bronn              dylan bronn
10          Emanuel Vignato          emanuel vignato
11             Emil Bohinen             emil bohinen
12             Erik Botheim             erik botheim
13           Federico Fazio           federico fazio
14         Flavius Daniliuc         flavius daniliuc
15          Giulio Maggiore          giulio maggiore
16        Grigoris Kastanos        grigoris kastanos
17          Guillermo Ochoa          guillermo ochoa
18               Iron Gomis               iron gomis
19           Jérôme Boateng           jerome boateng
20            Jovane Cabral            jovane cabral
21            Junior Sambia            junior sambia
22     Konstantinos Manolas     konstantinos manolas
23        Lassana Coulibaly        lassana coulibaly
24           Lorenzo Pirola           lorenzo pirola
25            Loum Tchaouna            loum tchaouna
26         Marco Pellegrino         marco pellegrino
27         Mateusz Legowski         mateusz legowski
28            Matteo Lovato            matteo lovato
29                   Mikael                   mikael
30         Niccolò Pierozzi         niccolo pierozzi
31          Norbert Gyomber          norbert gyomber
32         Pasquale Allocca         pasquale allocca
33       Pasquale Mazzocchi       pasquale mazzocchi
34            Shon Weissman            shon weissman
35                     Simy                     simy
36               Toma Basic               toma basic
37  Triantafyllos Pasalidis  triantafyllos pasalidis
38         Trivante Stewart         trivante stewart
39        Vincenzo Fiorillo        vincenzo fiorillo

============================================================
  Sassuolo  —  SF sin salario:

          player  minutesPlayed
0    Justin Kumi              3
1  Kevin Miranda             12

  CG plantilla completa:

                      player               player_norm
0            Agustín Álvarez           agustin alvarez
1             Alessio Cragno            alessio cragno
2            Andrea Consigli           andrea consigli
3           Andrea Pinamonti          andrea pinamonti
4           Armand Laurienté          armand lauriente
5           Cristian Volpato          cristian volpato
6              Daniel Boloca             daniel boloca
7           Domenico Berardi          domenico berardi
8       Emil Konradsen Ceide      emil konradsen ceide
9            Filippo Missori           filippo missori
10        Gian Marco Ferrari        gian marco ferrari
11           Gianluca Pegolo           gianluca pegolo
12           Grégoire Defrel           gregoire defrel
13             Jeremy Toljan             jeremy toljan
14                 Josh Doig                 josh doig
15       Kristian Thorstvedt       kristian thorstvedt
16               Luca Lipani               luca lipani
17           Marash Kumbulla           marash kumbulla
18  Marcus Holmgren Pedersen  marcus holmgren pedersen
19              Martin Erlic              martin erlic
20          Matheus Henrique          matheus henrique
21               Matías Viña               matias vina
22               Mattia Viti               mattia viti
23             Nedim Bajrami             nedim bajrami
24              Pedro Obiang              pedro obiang
25           Riccardo Ciervo           riccardo ciervo
26                      Ruan                      ruan
27           Samu Castillejo           samu castillejo
28        Samuele Mulattieri        samuele mulattieri
29                Uros Racic                uros racic

============================================================
  Torino  —  SF sin salario:

                  player  minutesPlayed
0  Alessandro Dellavalle             14
1           Simone Verdi             10
2            Zanos Savva             30

  CG plantilla completa:

                     player              player_norm
0               Adam Masina              adam masina
1             Adrien Tamèze            adrien tameze
2     Alessandro Buongiorno    alessandro buongiorno
3   Ange Caumenan N'Guessan  ange caumenan n guessan
4          Antonio Sanabria         antonio sanabria
5             Brandon Soppy            brandon soppy
6             David Okereke            david okereke
7                David Zima               david zima
8                Demba Seck               demba seck
9              Duván Zapata             duvan zapata
10          Gvidas Gineitis          gvidas gineitis
11                Ivan Ilic                ivan ilic
12            Karol Linetty            karol linetty
13             Koffi Djidji             koffi djidji
14             Luca Gemello             luca gemello
15            Matteo Lovato            matteo lovato
16           Mërgim Vojvoda           mergim vojvoda
17               Mihai Popa               mihai popa
18         Nemanja Radonjic         nemanja radonjic
19            Nikola Vlašić            nikola vlasic
20             Perr Schuurs             perr schuurs
21          Pietro Passador          pietro passador
22          Pietro Pellegri          pietro pellegri
23          Raoul Bellanova          raoul bellanova
24        Ricardo Rodríguez        ricardo rodriguez
25             Saba Sazonov             saba sazonov
26            Samuele Ricci            samuele ricci
27               Uros Kabic               uros kabic
28         Valentino Lazaro         valentino lazaro
29   Vanja Milinkovic-Savic   vanja milinkovic savic
30             Yann Karamoh             yann karamoh

============================================================
  Udinese  —  SF sin salario:

  player  minutesPlayed
0   Beto             74

  CG plantilla completa:

                player         player_norm
0          Adam Masina         adam masina
1       Antonio Tikvic      antonio tikvic
2        Axel Guessand       axel guessand
3              Brenner             brenner
4   Christian Kabasele  christian kabasele
5      Daniele Padelli     daniele padelli
6        David Pejičić       david pejicic
7       Domingos Quina      domingos quina
8          Enzo Ebosse         enzo ebosse
9       Etienne Camara      etienne camara
10       Festy Ebosele       festy ebosele
11     Florian Thauvin     florian thauvin
12     Gerard Deulofeu     gerard deulofeu
13      Hassane Kamara      hassane kamara
14       Isaac Success       isaac success
15          Jaka Bijol          jaka bijol
16      James Abankwah      james abankwah
17       João Ferreira       joao ferreira
18       Jordan Zemura       jordan zemura
19        Keinan Davis        keinan davis
20   Kingsley Ehizibue   kingsley ehizibue
21   Lautaro Giannetti   lautaro giannetti
22     Lazar Samardžić     lazar samardzic
23       Lorenzo Lucca       lorenzo lucca
24        Maduka Okoye        maduka okoye
25     Marco Ballarini     marco ballarini
26     Marco Silvestri     marco silvestri
27          Marley Aké          marley ake
28       Martín Payero       martin payero
29        Nehuén Pérez        nehuen perez
30        Oier Zarraga        oier zarraga
31     Roberto Pereyra     roberto pereyra
32        Sandi Lovric        sandi lovric
33       Sekou Diawara       sekou diawara
34      Simone Pafundi      simone pafundi
35   Thomas Kristensen   thomas kristensen
36      Vivaldo Semedo      vivaldo semedo
37              Walace              walace

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 555/590 (94.1%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_italy_2324.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_italy_2324.csv
   Jugadores totales:  590
   Con salario:        555
   Sin salario (NaN):  35
   Columnas:           121