# 03 · Join Sofascore + Capology — Italy Serie A 20/21

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2020/21 de Serie A italiana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_italy_2021.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_italy_2021.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  596 jugadores | 116 columnas
Capology:   652 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   inter
   milan

En Capology pero no en Sofascore:
   ac milan
   inter milan

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'ac milan':'milan',
            'inter milan':'inter'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 546/598 (91.3%)
Sin emparejar: 52

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          8
Revisión media    (0.75 ≤ score < 0.90):   3
Revisión estricta (0.50 ≤ score < 0.75):   24
Revisión muy est. (score < 0.50):           17

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf           team              cg_match  score
17  Bartłomiej Drągowski     Fiorentina  bartlomiej dragowski  0.974
6       Łukasz Skorupski        Bologna      lukasz skorupski  0.968
14      Paweł Dawidowicz  Hellas Verona      pawel dawidowicz  0.968
3      Aleksei Miranchuk       Atalanta     aleksey miranchuk  0.941
26      Andrey Gălăbinov         Spezia      andrej galabinov  0.938
10         Filip Đuričić       Sassuolo        filip djuricic  0.923
18          Joakim Mæhle       Atalanta         joakim maehle  0.917
0             Simon Kjær          Milan           simon kjaer  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

           player_sf     team                 cg_match  score
15   Salvador Ferrer   Spezia             salva ferrer  0.889
27  Andri Baldursson  Bologna  andri fannar baldursson  0.821
19    Wilfried Singo   Torino  wilfried stephane singo  0.757

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 3 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf        team               cg_match  score
1     João Pedro Galvão    Cagliari             joao pedro  0.741
36      Antonio Palumbo   Sampdoria     antonino la gumina  0.667
31    Mattia De Sciglio    Juventus       matthijs de ligt  0.667
7           Jeff Chabot      Spezia          julian chabot  0.667
2       Nicola Zalewski        Roma         nicolo zaniolo  0.621
12        Marco Bertini       Lazio             marco alia  0.609
29         Edoardo Bove        Roma            pietro boer  0.609
13  Alessandro Di Pardo    Juventus            alex sandro  0.600
25      Mattia Pagliuca     Bologna       mattias svanberg  0.581
20           Igor Júlio  Fiorentina                   igor  0.571
9         Samir Caetano     Udinese                  samir  0.556
4        Nicolò Fagioli    Juventus        carlo pinsoglio  0.552
8      Kastriot Dermaku       Parma         gaston brugman  0.533
45     Antonio Raimondo     Bologna         valentin antov  0.533
30        Félix Correia    Juventus  federico bernardeschi  0.529
40        Drissa Camara       Parma             dennis man  0.522
51        Amadou Diambo   Benevento             bryan dabo  0.522
37         Yayah Kallon       Genoa        andrea masiello  0.519
43         Chaka Traorè       Parma        andrea adorante  0.519
46       Giacomo Vrioni    Juventus      giorgio chiellini  0.516
11          Ryder Matos     Udinese          rodrigo becao  0.500
38       Álex Berenguer      Torino                 bremer  0.500
16        Ebrima Darboe        Roma            pietro boer  0.500
22       Kwadwo Asamoah    Cagliari             adam ounas  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['joao pedro galvao',
                    'jeff chabot',
                    'igor julio',
                    'samir caetano'
                    

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 4

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf           team            cg_match  score
24       Lubomir Tupta  Hellas Verona        luigi vitale  0.480
32       Omar Khailoti        Bologna   takehiro tomiyasu  0.467
44     Kacper Urbański        Bologna     edoardo vergani  0.467
23     Justin Kluivert           Roma     jordan veretout  0.467
34       Douglas Costa       Juventus   gianluca frabotta  0.467
5       Antonio Cioffi         Napoli   nikola maksimovic  0.452
50      Isaac Karamoko       Sassuolo   giacomo raspadori  0.452
35        Simone Rabbi        Bologna     sebastian breza  0.444
42           Raúl Moro          Lazio      joaquin correa  0.435
48    Emmanuel Gyabuaa       Atalanta        duvan zapata  0.429
47         Wisdom Amey        Bologna   nicolas dominguez  0.429
49    Davide Ghislandi       Atalanta   pierluigi gollini  0.424
39     Augustus Kargbo        Crotone  aristoteles romero  0.424
33       Philip Yeboah  Hellas Verona    nicola borghetto  0.414
21  Steeve-Mike Eyango          Genoa       giuseppe caso  0.387
28      Kiril Despodov       Cagliari   alessandro deiola  0.387
41    Márk Kosznovszky          Parma    marcello gazzola  0.375

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 565/602 (93.9%)
Sin salario:     37

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 37

,player,team,minutesPlayed,appearances,goals,assists
0,Davide Ghislandi,Atalanta,5,1,0,0
1,Emmanuel Gyabuaa,Atalanta,1,1,0,0
2,Amadou Diambo,Benevento,2,1,0,0
3,Simone Rabbi,Bologna,43,4,0,1
4,Omar Khailoti,Bologna,27,1,0,0
5,Mattia Pagliuca,Bologna,12,1,0,0
6,Kacper Urbański,Bologna,1,1,0,0
7,Antonio Raimondo,Bologna,1,1,0,0
8,Wisdom Amey,Bologna,1,1,0,0
9,Kwadwo Asamoah,Cagliari,221,9,0,0
10,Kiril Despodov,Cagliari,10,1,0,0
11,Augustus Kargbo,Crotone,32,1,0,0
12,Steeve-Mike Eyango,Genoa,51,3,0,1
13,Yayah Kallon,Genoa,45,1,0,0
14,Philip Yeboah,Hellas Verona,12,1,0,0
15,Lubomir Tupta,Hellas Verona,8,1,0,0
16,Douglas Costa,Juventus,40,2,0,0
17,Mattia De Sciglio,Juventus,23,1,0,0
18,Nicolò Fagioli,Juventus,20,1,0,0
19,Alessandro Di Pardo,Juventus,17,4,0,0
20,Félix Correia,Juventus,12,1,0,0
21,Giacomo Vrioni,Juventus,1,1,0,0
22,Raúl Moro,Lazio,10,1,0,0
23,Marco Bertini,Lazio,8,1,0,0
24,Antonio Cioffi,Napoli,11,1,0,0
25,Kastriot Dermaku,Parma,99,2,0,0
26,Márk Kosznovszky,Parma,90,1,0,0
27,Chaka Traorè,Parma,28,3,0,0
28,Drissa Camara,Parma,14,1,0,0
29,Ebrima Darboe,Roma,326,5,0,0
30,Justin Kluivert,Roma,12,1,0,0
31,Nicola Zalewski,Roma,10,1,0,1
32,Edoardo Bove,Roma,10,1,0,0
33,Antonio Palumbo,Sampdoria,11,1,0,0
34,Isaac Karamoko,Sassuolo,1,1,0,0
35,Álex Berenguer,Torino,133,2,0,0
36,Ryder Matos,Udinese,12,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Atalanta  —  SF sin salario:

             player  minutesPlayed
0  Davide Ghislandi              5
1  Emmanuel Gyabuaa              1

  CG plantilla completa:

                player         player_norm
0    Aleksey Miranchuk   aleksey miranchuk
1          Amad Diallo         amad diallo
2       Berat Djimsiti      berat djimsiti
3      Boris Radunović     boris radunovic
4         Bosko Sutalo        bosko sutalo
5      Cristian Romero     cristian romero
6    Cristiano Piccini   cristiano piccini
7         Duván Zapata        duvan zapata
8        Fabio Depaoli       fabio depaoli
9      Francesco Rossi     francesco rossi
10       Hans Hateboer       hans hateboer
11       Joakim Maehle       joakim maehle
12        Johan Mojica        johan mojica
13  José Luis Palomino  jose luis palomino
14        Josip Ilicic        josip ilicic
15         Luis Muriel         luis muriel
16   Marco Carnesecchi   marco carnesecchi
17    Marco Sportiello    marco sportiello
18       Mario Pasalic       mario pasalic
19      Marten de Roon      marten de roon
20      Matteo Pessina      matteo pessina
21      Matteo Ruggeri      matteo ruggeri
22      Mattia Caldara      mattia caldara
23          Papu Gómez          papu gomez
24   Pierluigi Gollini   pierluigi gollini
25        Rafael Tolói        rafael toloi
26        Remo Freuler        remo freuler
27        Robin Gosens        robin gosens
28  Ruslan Malinovskyi  ruslan malinovskyi
29         Sam Lammers         sam lammers
30    Viktor Kovalenko    viktor kovalenko

============================================================
  Benevento  —  SF sin salario:

          player  minutesPlayed
0  Amadou Diambo              2

  CG plantilla completa:

                    player             player_norm
0           Abdallah Basit          abdallah basit
1             Adolfo Gaich            adolfo gaich
2          Alessandro Tuia         alessandro tuia
3             Andrés Tello            andres tello
4             Artur Ionita            artur ionita
5               Bryan Dabo              bryan dabo
6         Christian Maggio        christian maggio
7        Christian Pastina       christian pastina
8              Daam Foulon             daam foulon
9           Davide Masella          davide masella
10           Fabio Depaoli           fabio depaoli
11          Federico Barba          federico barba
12        Gabriele Moncini        gabriele moncini
13         Gaetano Letizia         gaetano letizia
14        Gianluca Caprari        gianluca caprari
15       Gianluca Lapadula       gianluca lapadula
16       Giuseppe Di Serio       giuseppe di serio
17             Iago Falque             iago falque
18          Igor Lucatelli          igor lucatelli
19              Kamil Glik              kamil glik
20       Lorenzo Del Pinto       lorenzo del pinto
21         Lorenzo Montipò         lorenzo montipo
22              Luca Antei              luca antei
23          Luca Caldirola          luca caldirola
24               Marco Sau               marco sau
25           Massimo Volta           massimo volta
26           Nicolas Viola           nicolas viola
27       Nicolò Manfredini       nicolo manfredini
28  Pasquale Schiattarella  pasquale schiattarella
29        Perparim Hetemaj        perparim hetemaj
30      Pier Graziano Gori      pier graziano gori
31        Riccardo Improta        riccardo improta
32         Roberto Insigne         roberto insigne
33           Siriki Sanogo           siriki sanogo

============================================================
  Bologna  —  SF sin salario:

             player  minutesPlayed
0  Antonio Raimondo              1
1   Kacper Urbański              1
2   Mattia Pagliuca             12
3     Omar Khailoti             27
4      Simone Rabbi             43
5       Wisdom Amey              1

  CG plantilla completa:

                     player              player_norm
0              Aaron Hickey             aaron hickey
1            Adama Soumaoro           adama soumaoro
2               Andrea Poli              andrea poli
3        Andreas Skov Olsen       andreas skov olsen
4   Andri Fannar Baldursson  andri fannar baldursson
5           Angelo da Costa          angelo da costa
6          Arturo Calabresi         arturo calabresi
7                    Danilo                   danilo
8           Edoardo Vergani          edoardo vergani
9           Emanuel Vignato          emanuel vignato
10        Federico Ravaglia        federico ravaglia
11       Federico Santander       federico santander
12               Gary Medel               gary medel
13           Ibrahima Mbaye           ibrahima mbaye
14           Jerdy Schouten           jerdy schouten
15         Kingsley Michael         kingsley michael
16     Lorenzo De Silvestri     lorenzo de silvestri
17         Lukasz Skorupski         lukasz skorupski
18         Mattias Svanberg         mattias svanberg
19           Mitchell Dijks           mitchell dijks
20              Musa Barrow              musa barrow
21              Musa Juwara              musa juwara
22               Nehuén Paz               nehuen paz
23           Nicola Sansone           nicola sansone
24        Nicolás Domínguez        nicolas dominguez
25             Paolo Faragò             paolo farago
26        Riccardo Orsolini        riccardo orsolini
27          Roberto Soriano          roberto soriano
28          Rodrigo Palacio          rodrigo palacio
29          Sebastian Breza          sebastian breza
30          Stefano Denswil          stefano denswil
31        Takehiro Tomiyasu        takehiro tomiyasu
32           Valentin Antov           valentin antov

============================================================
  Cagliari  —  SF sin salario:

           player  minutesPlayed
0  Kiril Despodov             10
1  Kwadwo Asamoah            221

  CG plantilla completa:

                     player              player_norm
0                Adam Ounas               adam ounas
1             Alberto Cerri            alberto cerri
2         Alessandro Deiola        alessandro deiola
3    Alessandro Tripaldelli   alessandro tripaldelli
4            Alessio Cragno           alessio cragno
5             Alfred Duncan            alfred duncan
6            Andrea Carboni           andrea carboni
7          Arturo Calabresi         arturo calabresi
8   Charalampos Lykogiannis  charalampos lykogiannis
9           Christian Oliva          christian oliva
10          Daniele Ragatzu          daniele ragatzu
11           Daniele Rugani           daniele rugani
12              Diego Godín              diego godin
13           Fabio Pisacane           fabio pisacane
14        Fabrizio Caligara        fabrizio caligara
15           Filip Bradaric           filip bradaric
16           Gabriele Zappa           gabriele zappa
17           Gastón Pereiro           gaston pereiro
18         Giovanni Simeone         giovanni simeone
19        Guglielmo Vicario        guglielmo vicario
20               João Pedro               joao pedro
21       Leonardo Pavoletti       leonardo pavoletti
22          Luca Ceppitelli          luca ceppitelli
23              Marko Pajac              marko pajac
24                Marko Rog                marko rog
25           Matteo Tramoni           matteo tramoni
26           Nahitan Nández           nahitan nandez
27             Paolo Faragò             paolo farago
28         Radja Nainggolan         radja nainggolan
29            Ragnar Klavan            ragnar klavan
30             Razvan Marin             razvan marin
31          Riccardo Sottil          riccardo sottil
32    Sebastian Walukiewicz    sebastian walukiewicz
33            Simone Aresti            simone aresti
34             Simone Pinna             simone pinna
35             Valter Birsa             valter birsa
36             Zito Luvumbo             zito luvumbo

============================================================
  Crotone  —  SF sin salario:

            player  minutesPlayed
0  Augustus Kargbo             32

  CG plantilla completa:

                 player          player_norm
0            Adam Ounas           adam ounas
1          Ahmad Benali         ahmad benali
2           Alex Cordaz          alex cordaz
3        Andrea Rispoli       andrea rispoli
4      Antonio Mazzotta     antonio mazzotta
5    Aristóteles Romero   aristoteles romero
6        Arkadiusz Reca       arkadiusz reca
7          Denis Dragus         denis dragus
8      Eduardo Henrique     eduardo henrique
9      Emmanuel Rivière     emmanuel riviere
10  Francesco D'Alterio  francesco d alterio
11    Gian Marco Crespi    gian marco crespi
12    Giovanni Crociata    giovanni crociata
13       Giuseppe Cuomo       giuseppe cuomo
14   Jacopo Petriccione   jacopo petriccione
15       Junior Messias       junior messias
16         Koffi Djidji         koffi djidji
17    Lisandro Magallán    lisandro magallan
18        Luca Cigarini        luca cigarini
19         Luca Marrone         luca marrone
20       Luca Siligardi       luca siligardi
21           Luis Rojas           luis rojas
22          Marco Festa          marco festa
23    Mattia Mustacchio    mattia mustacchio
24          Milos Vulic          milos vulic
25    Niccolò Zanellato    niccolo zanellato
26        Pedro Pereira        pedro pereira
27     Salvatore Molina     salvatore molina
28    Samuel Di Carmine    samuel di carmine
29   Sebastiano Luperto   sebastiano luperto
30                 Simy                 simy
31      Tomislav Gomelt      tomislav gomelt
32     Vladimir Golemic     vladimir golemic

============================================================
  Genoa  —  SF sin salario:

               player  minutesPlayed
0  Steeve-Mike Eyango             51
1        Yayah Kallon             45

  CG plantilla completa:

                player         player_norm
0      Alberto Paleari     alberto paleari
1      Andrea Masiello     andrea masiello
2    Claudiu Micovschi   claudiu micovschi
3      Cristián Zapata     cristian zapata
4         Darian Males        darian males
5      Davide Biraschi     davide biraschi
6    Davide Zappacosta   davide zappacosta
7    Domenico Criscito   domenico criscito
8    Edoardo Goldaniga   edoardo goldaniga
9     Eldor Shomurodov    eldor shomurodov
10  Federico Marchetti  federico marchetti
11    Filippo Melegoni    filippo melegoni
12   Francesco Cassata   francesco cassata
13   Gianluca Scamacca   gianluca scamacca
14       Giuseppe Caso       giuseppe caso
15        Goran Pandev        goran pandev
16      Ivan Lakicevic      ivan lakicevic
17    Ivan Radovanovic    ivan radovanovic
18      Jérôme Onguéné      jerome onguene
19     Kevin Strootman     kevin strootman
20        Lasse Schöne        lasse schone
21    Lennart Czyborra    lennart czyborra
22     Luca Pellegrini     luca pellegrini
23       Lukas Lerager       lukas lerager
24          Lukas Zima          lukas zima
25    Manolo Portanova    manolo portanova
26         Marko Pjaca         marko pjaca
27         Mattia Bani         mattia bani
28       Mattia Destro       mattia destro
29        Mattia Perin        mattia perin
30           Miha Zajc           miha zajc
31        Milan Badelj        milan badelj
32      Nicolò Rovella      nicolo rovella
33     Paolo Ghiglione     paolo ghiglione
34         Petar Brlek         petar brlek
35     Stefano Sturaro     stefano sturaro
36       Valon Behrami       valon behrami
37   Vittorio Parigini   vittorio parigini

============================================================
  Hellas Verona  —  SF sin salario:

          player  minutesPlayed
0  Lubomir Tupta              8
1  Philip Yeboah             12

  CG plantilla completa:

                 player          player_norm
0         Adrien Tamèze        adrien tameze
1         Alan Empereur        alan empereur
2    Alessandro Berardi   alessandro berardi
3          Andrea Danzi         andrea danzi
4        Andrea Favilli       andrea favilli
5         Antonin Barak        antonin barak
6     Antonio Di Gaudio    antonio di gaudio
7          Bruno Amione         bruno amione
8          Daniel Bessa         daniel bessa
9         Darko Lazovic        darko lazovic
10       Davide Faraoni       davide faraoni
11       Destiny Udogie       destiny udogie
12        Ebrima Colley        ebrima colley
13        Eddie Salcedo        eddie salcedo
14        Emmanuel Badu        emmanuel badu
15  Federico Ceccherini  federico ceccherini
16     Federico Dimarco     federico dimarco
17  Giangiacomo Magnani  giangiacomo magnani
18            Ivan Ilic            ivan ilic
19          Ivor Pandur          ivor pandur
20         Karim Laribi         karim laribi
21        Kevin Lasagna        kevin lasagna
22          Kevin Rüegg          kevin ruegg
23         Koray Günter         koray gunter
24         Luigi Vitale         luigi vitale
25        Marco Benassi        marco benassi
26      Marco Silvestri      marco silvestri
27        Matteo Lovato        matteo lovato
28      Mattia Zaccagni      mattia zaccagni
29           Mert Cetin           mert cetin
30        Miguel Veloso        miguel veloso
31     Nicola Borghetto     nicola borghetto
32       Nikola Kalinic       nikola kalinic
33     Pawel Dawidowicz     pawel dawidowicz
34       Ronaldo Vieira       ronaldo vieira
35    Samuel Di Carmine    samuel di carmine
36      Stefano Sturaro      stefano sturaro

============================================================
  Juventus  —  SF sin salario:

                player  minutesPlayed
0  Alessandro Di Pardo             17
1        Douglas Costa             40
2        Félix Correia             12
3       Giacomo Vrioni              1
4    Mattia De Sciglio             23
5       Nicolò Fagioli             20

  CG plantilla completa:

                   player            player_norm
0            Aaron Ramsey           aaron ramsey
1           Adrien Rabiot          adrien rabiot
2             Alex Sandro            alex sandro
3           Álvaro Morata          alvaro morata
4                  Arthur                 arthur
5         Carlo Pinsoglio        carlo pinsoglio
6       Cristiano Ronaldo      cristiano ronaldo
7                  Danilo                 danilo
8        Dejan Kulusevski       dejan kulusevski
9   Federico Bernardeschi  federico bernardeschi
10        Federico Chiesa        federico chiesa
11      Gianluca Frabotta      gianluca frabotta
12       Gianluigi Buffon       gianluigi buffon
13      Giorgio Chiellini      giorgio chiellini
14          Juan Cuadrado          juan cuadrado
15       Leonardo Bonucci       leonardo bonucci
16       Matthijs de Ligt       matthijs de ligt
17          Merih Demiral          merih demiral
18           Paulo Dybala           paulo dybala
19          Radu Drăgușin          radu dragusin
20      Rodrigo Bentancur      rodrigo bentancur
21           Sami Khedira           sami khedira
22           Stefano Gori           stefano gori
23        Weston McKennie        weston mckennie
24      Wojciech Szczesny      wojciech szczesny

============================================================
  Lazio  —  SF sin salario:

          player  minutesPlayed
0  Marco Bertini              8
1      Raúl Moro             10

  CG plantilla completa:

                     player              player_norm
0            Abukar Mohamed           abukar mohamed
1              Adam Marusic             adam marusic
2           Andreas Pereira          andreas pereira
3                    Bastos                   bastos
4             Ciro Immobile            ciro immobile
5            Danilo Cataldi           danilo cataldi
6         Davide Di Gennaro        davide di gennaro
7               Denis Vavro              denis vavro
8           Djavan Anderson          djavan anderson
9            Felipe Caicedo           felipe caicedo
10         Francesco Acerbi         francesco acerbi
11        Gonzalo Escalante        gonzalo escalante
12   Jean-Daniel Akpa Akpro   jean daniel akpa akpro
13           Joaquín Correa           joaquin correa
14      Joseph Marie Minala      joseph marie minala
15              Lucas Leiva              lucas leiva
16             Luis Alberto             luis alberto
17              Luiz Felipe              luiz felipe
18               Madiu Bari               madiu bari
19           Manuel Lazzari           manuel lazzari
20               Marco Alia               marco alia
21             Marco Parolo             marco parolo
22          Mateo Musacchio          mateo musacchio
23            Mohamed Fares            mohamed fares
24            Nicolò Armini            nicolo armini
25                   Patric                   patric
26               Pepe Reina               pepe reina
27             Riza Durmisi             riza durmisi
28              Senad Lulic              senad lulic
29  Sergej Milinkovic-Savic  sergej milinkovic savic
30             Silvio Proto             silvio proto
31            Sofian Kiyine            sofian kiyine
32              Stefan Radu              stefan radu
33         Thomas Strakosha         thomas strakosha
34             Vedat Muriqi             vedat muriqi
35             Wesley Hoedt             wesley hoedt

============================================================
  Napoli  —  SF sin salario:

           player  minutesPlayed
0  Antonio Cioffi             11

  CG plantilla completa:

                  player           player_norm
0             Alex Meret            alex meret
1          Amir Rrahmani         amir rrahmani
2         Andrea Petagna        andrea petagna
3        Arkadiusz Milik       arkadiusz milik
4           David Ospina          david ospina
5            Diego Demme           diego demme
6          Dries Mertens         dries mertens
7            Eljif Elmas           eljif elmas
8           Elseid Hysaj          elseid hysaj
9            Fabián Ruiz           fabian ruiz
10        Faouzi Ghoulam        faouzi ghoulam
11     Fernando Llorente     fernando llorente
12   Giovanni Di Lorenzo   giovanni di lorenzo
13        Hirving Lozano        hirving lozano
14     Kalidou Koulibaly     kalidou koulibaly
15         Kévin Malcuit         kevin malcuit
16  Konstantinos Manolas  konstantinos manolas
17       Lorenzo Insigne       lorenzo insigne
18             Mário Rui             mario rui
19       Matteo Politano       matteo politano
20        Nikita Contini        nikita contini
21     Nikola Maksimovic     nikola maksimovic
22       Piotr Zielinski       piotr zielinski
23     Stanislav Lobotka     stanislav lobotka
24      Tiemoué Bakayoko      tiemoue bakayoko
25        Victor Osimhen        victor osimhen

============================================================
  Parma  —  SF sin salario:

             player  minutesPlayed
0      Chaka Traorè             28
1     Drissa Camara             14
2  Kastriot Dermaku             99
3  Márk Kosznovszky             90

  CG plantilla completa:

                     player              player_norm
0            Alberto Grassi           alberto grassi
1           Andrea Adorante          andrea adorante
2              Andrea Conti             andrea conti
3               Andrea Dini              andrea dini
4         Andreas Cornelius        andreas cornelius
5             Botond Balogh            botond balogh
6               Bruno Alves              bruno alves
7              Daan Dierckx             daan dierckx
8                Dennis Man               dennis man
9           Filippo Rinaldi          filippo rinaldi
10           Gastón Brugman           gaston brugman
11                 Gervinho                 gervinho
12            Giacomo Ricci            giacomo ricci
13        Giuseppe Carriero        giuseppe carriero
14        Giuseppe Pezzella        giuseppe pezzella
15           Graziano Pellè           graziano pelle
16  Hans Nicolussi Caviglia  hans nicolussi caviglia
17                  Hernani                  hernani
18              Jacopo Dezi              jacopo dezi
19            Jasmin Kurtic            jasmin kurtic
20           Joshua Zirkzee           joshua zirkzee
21            Juan Brunetta            juan brunetta
22              Juraj Kucka              juraj kucka
23          Lautaro Valenti          lautaro valenti
24               Luigi Sepe               luigi sepe
25         Marcello Gazzola         marcello gazzola
26       Matteo Scozzarella       matteo scozzarella
27              Mattia Bani              mattia bani
28          Mattia Sprocati          mattia sprocati
29              Maxime Busi              maxime busi
30            Reinaldo Radu            reinaldo radu
31        Riccardo Gagliolo        riccardo gagliolo
32          Roberto Inglese          roberto inglese
33               Simon Sohm               simon sohm
34           Simone Colombi           simone colombi
35          Simone Iacoponi          simone iacoponi
36         Valentin Mihaila         valentin mihaila
37       Vasilios Zagaritis       vasilios zagaritis
38          Vincent Laurini          vincent laurini
39            Wylan Cyprien            wylan cyprien
40             Yann Karamoh             yann karamoh
41            Yordan Osorio            yordan osorio

============================================================
  Roma  —  SF sin salario:

            player  minutesPlayed
0    Ebrima Darboe            326
1     Edoardo Bove             10
2  Justin Kluivert             12
3  Nicola Zalewski             10

  CG plantilla completa:

                 player          player_norm
0        Amadou Diawara       amadou diawara
1       Antonio Mirante      antonio mirante
2         Borja Mayoral        borja mayoral
3           Bruno Peres          bruno peres
4       Bryan Cristante      bryan cristante
5        Bryan Reynolds       bryan reynolds
6          Carles Pérez         carles perez
7        Chris Smalling       chris smalling
8         Daniel Fuzato        daniel fuzato
9         Davide Santon        davide santon
10           Edin Dzeko           edin dzeko
11       Federico Fazio       federico fazio
12     Gianluca Mancini     gianluca mancini
13       Gonzalo Villar       gonzalo villar
14   Henrikh Mkhitaryan   henrikh mkhitaryan
15       Javier Pastore       javier pastore
16      Jordan Veretout      jordan veretout
17           Juan Jesus           juan jesus
18  Leonardo Spinazzola  leonardo spinazzola
19   Lorenzo Pellegrini   lorenzo pellegrini
20      Marash Kumbulla      marash kumbulla
21       Nicolò Zaniolo       nicolo zaniolo
22            Pau López            pau lopez
23                Pedro                pedro
24          Pietro Boer          pietro boer
25   Riccardo Calafiori   riccardo calafiori
26        Rick Karsdorp        rick karsdorp
27         Roger Ibañez         roger ibanez
28       Simone Farelli       simone farelli
29  Stephan El Shaarawy  stephan el shaarawy

============================================================
  Sampdoria  —  SF sin salario:

            player  minutesPlayed
0  Antonio Palumbo             11

  CG plantilla completa:

                  player           player_norm
0           Adrien Silva          adrien silva
1            Albin Ekdal           albin ekdal
2           Alex Ferrari          alex ferrari
3     Antonino La Gumina    antonino la gumina
4       Antonio Candreva      antonio candreva
5    Bartosz Bereszynski   bartosz bereszynski
6                   Dodô                  dodo
7            Emil Audero           emil audero
8    Ernesto Torregrossa   ernesto torregrossa
9     Fabio Quagliarella    fabio quagliarella
10        Gastón Ramírez        gaston ramirez
11          Jakub Jankto          jakub jankto
12          Kaique Rocha          kaique rocha
13          Karlo Letica          karlo letica
14           Keita Baldé           keita balde
15  Kristoffer Askildsen  kristoffer askildsen
16       Lorenzo Tonelli       lorenzo tonelli
17     Manolo Gabbiadini     manolo gabbiadini
18          Maya Yoshida          maya yoshida
19           Mehdi Léris           mehdi leris
20      Mikkel Damsgaard      mikkel damsgaard
21        Morten Thorsby        morten thorsby
22       Nicola Ravaglia       nicola ravaglia
23           Omar Colley           omar colley
24       Tommaso Augello       tommaso augello
25         Valerio Verre         valerio verre
26          Vasco Regini          vasco regini

============================================================
  Sassuolo  —  SF sin salario:

           player  minutesPlayed
0  Isaac Karamoko              1

  CG plantilla completa:

                    player             player_norm
0          Andrea Consigli         andrea consigli
1              Brian Oddei             brian oddei
2         Domenico Berardi        domenico berardi
3          Federico Peluso         federico peluso
4           Federico Ricci          federico ricci
5           Filip Djuricic          filip djuricic
6          Filippo Romagna         filippo romagna
7         Francesco Caputo        francesco caputo
8     Francesco Magnanelli    francesco magnanelli
9   Georgios Kyriakopoulos  georgios kyriakopoulos
10       Giacomo Raspadori       giacomo raspadori
11      Gian Marco Ferrari      gian marco ferrari
12         Gianluca Pegolo         gianluca pegolo
13         Grégoire Defrel         gregoire defrel
14     Hamed Junior Traorè     hamed junior traore
15            Jérémie Boga            jeremie boga
16           Jeremy Toljan           jeremy toljan
17              Kaan Ayhan              kaan ayhan
18          Lukas Haraslin          lukas haraslin
19        Manuel Locatelli        manuel locatelli
20                  Marlon                  marlon
21            Maxime López            maxime lopez
22          Mehdi Bourabia          mehdi bourabia
23             Mert Müldür             mert muldur
24   Nicolás Schiappacasse   nicolas schiappacasse
25            Pedro Obiang            pedro obiang
26                 Rogério                 rogerio
27          Stefano Turati          stefano turati
28          Vlad Chiriches          vlad chiriches
29          Vlad Chiricheș          vlad chiriches

============================================================
  Torino  —  SF sin salario:

           player  minutesPlayed
0  Álex Berenguer            133

  CG plantilla completa:

                     player              player_norm
0     Alessandro Buongiorno    alessandro buongiorno
1                Amer Gojak               amer gojak
2            Andrea Belotti           andrea belotti
3            Antonio Rosati           antonio rosati
4          Antonio Sanabria         antonio sanabria
5              Armando Izzo             armando izzo
6                    Bremer                   bremer
7          Cristian Ansaldi         cristian ansaldi
8           Daniele Baselli          daniele baselli
9             Erick Ferigra            erick ferigra
10       Federico Bonazzoli       federico bonazzoli
11         Ibrahim Karamoko         ibrahim karamoko
12             Jacopo Segre             jacopo segre
13            Karol Linetty            karol linetty
14                   Lyanco                   lyanco
15           Mërgim Vojvoda           mergim vojvoda
16       Michel Ndary Adopo       michel ndary adopo
17             Nicola Murru             nicola murru
18         Nicolas N'Koulou         nicolas n koulou
19        Ricardo Rodríguez        ricardo rodriguez
20       Rolando Mandragora       rolando mandragora
21         Salvatore Sirigu         salvatore sirigu
22             Samir Ujkani             samir ujkani
23               Sasa Lukic               sasa lukic
24             Simone Edera             simone edera
25             Simone Verdi             simone verdi
26              Simone Zaza              simone zaza
27           Soualiho Meïté           soualiho meite
28             Tomás Rincón             tomas rincon
29   Vanja Milinković-Savić   vanja milinkovic savic
30         Vincenzo Millico         vincenzo millico
31  Wilfried Stephane Singo  wilfried stephane singo

============================================================
  Udinese  —  SF sin salario:

        player  minutesPlayed
0  Ryder Matos             12

  CG plantilla completa:

                 player          player_norm
0         Bram Nuytinck        bram nuytinck
1                Cristo               cristo
2         Ewandro Costa        ewandro costa
3          Felipe Vizeu         felipe vizeu
4   Fernando Forestieri  fernando forestieri
5     Fernando Llorente    fernando llorente
6       Gerard Deulofeu      gerard deulofeu
7       Hidde ter Avest      hidde ter avest
8      Ignacio Pussetto     ignacio pussetto
9     Ilija Nestorovski    ilija nestorovski
10         Jayden Braaf         jayden braaf
11  Jean-Victor Makengo  jean victor makengo
12  Jens Stryger Larsen  jens stryger larsen
13           Juan Musso           juan musso
14       Kevin Bonifazi       kevin bonifazi
15        Kevin Lasagna        kevin lasagna
16    Mamadou Coulibaly    mamadou coulibaly
17     Manuel Gasparini     manuel gasparini
18       Martin Palumbo       martin palumbo
19     Marvin Zeegelaar     marvin zeegelaar
20          Mato Jajalo          mato jajalo
21        Nahuel Molina        nahuel molina
22              Nícolas              nicolas
23          Petar Micin          petar micin
24      Roberto Pereyra      roberto pereyra
25        Rodrigo Becão        rodrigo becao
26      Rodrigo de Paul      rodrigo de paul
27   Rolando Mandragora   rolando mandragora
28                Samir                samir
29      Sebastian Prödl      sebastian prodl
30    Sebastien De Maio    sebastien de maio
31       Simone Scuffet       simone scuffet
32        Stefano Okaka        stefano okaka
33       Thomas Ouwejan       thomas ouwejan
34        Tolgay Arslan        tolgay arslan
35               Walace               walace

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 565/602 (93.9%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_italy_2021.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_italy_2021.csv
   Jugadores totales:  602
   Con salario:        565
   Sin salario (NaN):  37
   Columnas:           121