# 03 · Join Sofascore + Capology — Italy Serie A 22/23

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2022/23 de Serie A italiana**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_italy_2223.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_italy_2223.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  577 jugadores | 116 columnas
Capology:   649 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   inter
   milan

En Capology pero no en Sofascore:
   ac milan
   inter milan

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'ac milan':'milan',
            'inter milan':'inter'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 533/577 (92.4%)
Sin emparejar: 44

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          12
Revisión media    (0.75 ≤ score < 0.90):   5
Revisión estricta (0.50 ≤ score < 0.75):   15
Revisión muy est. (score < 0.50):           12

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf           team                cg_match  score
20  Przemysław Wiśniewski         Spezia   przemyslaw wisniewski  0.976
8    Bartłomiej Drągowski         Spezia    bartlomiej dragowski  0.974
14       Paweł Dawidowicz  Hellas Verona        pawel dawidowicz  0.968
4        Łukasz Skorupski        Bologna        lukasz skorupski  0.968
1            Leo Østigård         Napoli            leo ostigard  0.957
24  Þórir Jóhann Helgason          Lecce  thorir johann helgason  0.952
32      Christian Gytkjær          Monza      christian gytkjaer  0.941
3       Aleksei Miranchuk         Torino       aleksey miranchuk  0.941
17          Filip Đuričić      Sampdoria          filip djuricic  0.923
18           Joakim Mæhle       Atalanta           joakim maehle  0.917
7             Milan Đurić  Hellas Verona            milan djuric  0.909
11             Simon Kjær          Milan             simon kjaer  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

            player_sf         team                 cg_match  score
23  Antonio Iervolino  Salernitana    antonio pio iervolino  0.895
37    Salvador Ferrer       Spezia             salva ferrer  0.889
34  Mikael Ellertsson       Spezia  mikael egill ellertsson  0.850
25       Michel Adopo       Torino       michel ndary adopo  0.800
12     Wilfried Singo       Torino  wilfried stephane singo  0.757

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 5 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf        team              cg_match  score
27   Mario Gila Fuentes       Lazio            mario gila  0.714
38      Filippo Missori        Roma         filippo tripi  0.714
0      Andrea Ranocchia       Monza        andrea petagna  0.667
2        Frank Anguissa      Napoli  andre zambo anguissa  0.647
42     Mihailo Ivanović   Sampdoria      michael cuisance  0.625
41      Niccolò Pisilli        Roma        nicolo zaniolo  0.621
10           Igor Júlio  Fiorentina                  igor  0.571
16  Alberto Basso Ricci   Cremonese         marco benassi  0.562
40        Samuel Ntanda   Sampdoria        manuel de luca  0.519
6         Denis Zakaria    Juventus        angel di maria  0.519
15     Enzo Barrenechea    Juventus       leandro paredes  0.516
21   Benjamin Tahirović        Roma         nemanja matic  0.516
28      Flavio Paoletti   Sampdoria      ignacio pussetto  0.516
29    Samuel Di Carmine   Cremonese        soualiho meite  0.516
43     Herculano Nabian      Empoli          razvan marin  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mario gila fuentes',
                    'frank anguissa',
                    'igor julio'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 3

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

            player_sf           team               cg_match  score
5   Tommaso De Nipoti       Atalanta       marco sportiello  0.485
33     Niklas Pyyhtiä        Bologna            nikola moro  0.480
22     Lukáš Vorlický       Atalanta            luis muriel  0.480
13         Adam Ounas         Napoli   andre zambo anguissa  0.467
39      Franck Ribéry    Salernitana      francesco orlando  0.467
30   Jordan Majchrzak           Roma        bryan cristante  0.452
35       Jacopo Segre         Torino        pietro pellegri  0.444
19     Jesé Rodríguez      Sampdoria                   jese  0.444
36   Tommaso Barbieri       Juventus           mattia perin  0.429
31    Niccolò Cocetta        Udinese          isaac success  0.429
9   Panagiotis Retsos  Hellas Verona  alessandro cortinovis  0.421
26            Vivaldo        Udinese            mato jajalo  0.333

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = ['jese rodriguez'

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 1

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 554/577 (96.0%)
Sin salario:     23

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 23

,player,team,minutesPlayed,appearances,goals,assists
0,Lukáš Vorlický,Atalanta,26,3,0,0
1,Tommaso De Nipoti,Atalanta,10,1,0,0
2,Niklas Pyyhtiä,Bologna,107,6,0,1
3,Samuel Di Carmine,Cremonese,34,2,0,0
4,Alberto Basso Ricci,Cremonese,15,1,0,0
5,Herculano Nabian,Empoli,1,1,0,0
6,Panagiotis Retsos,Hellas Verona,122,2,0,0
7,Enzo Barrenechea,Juventus,159,3,0,0
8,Denis Zakaria,Juventus,122,2,0,0
9,Tommaso Barbieri,Juventus,114,3,0,0
10,Andrea Ranocchia,Monza,48,1,0,0
11,Adam Ounas,Napoli,24,2,0,0
12,Benjamin Tahirović,Roma,365,11,0,0
13,Filippo Missori,Roma,181,3,0,0
14,Jordan Majchrzak,Roma,13,1,0,0
15,Niccolò Pisilli,Roma,1,1,0,0
16,Franck Ribéry,Salernitana,36,1,0,0
17,Flavio Paoletti,Sampdoria,288,12,0,0
18,Mihailo Ivanović,Sampdoria,2,1,0,0
19,Samuel Ntanda,Sampdoria,1,1,0,0
20,Jacopo Segre,Torino,20,1,0,0
21,Vivaldo,Udinese,42,5,0,0
22,Niccolò Cocetta,Udinese,31,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Atalanta  —  SF sin salario:

              player  minutesPlayed
0     Lukáš Vorlický             26
1  Tommaso De Nipoti             10

  CG plantilla completa:

                player         player_norm
0      Ademola Lookman     ademola lookman
1       Berat Djimsiti      berat djimsiti
2        Brandon Soppy       brandon soppy
3          Caleb Okoli         caleb okoli
4    Davide Zappacosta   davide zappacosta
5         Duván Zapata        duvan zapata
6              Éderson             ederson
7      Francesco Rossi     francesco rossi
8     Giorgio Scalvini    giorgio scalvini
9        Hans Hateboer       hans hateboer
10        Jérémie Boga        jeremie boga
11       Joakim Maehle       joakim maehle
12  José Luis Palomino  jose luis palomino
13          Juan Musso          juan musso
14         Luis Muriel         luis muriel
15    Marco Sportiello    marco sportiello
16       Mario Pasalic       mario pasalic
17      Marten de Roon      marten de roon
18      Matteo Ruggeri      matteo ruggeri
19       Merih Demiral       merih demiral
20        Nadir Zortea        nadir zortea
21        Rafael Tolói        rafael toloi
22      Rasmus Højlund       rasmus hjlund
23  Ruslan Malinovskyi  ruslan malinovskyi
24     Simone Muratore     simone muratore
25    Teun Koopmeiners    teun koopmeiners

============================================================
  Bologna  —  SF sin salario:

           player  minutesPlayed
0  Niklas Pyyhtiä            107

  CG plantilla completa:

                     player              player_norm
0            Adama Soumaoro           adama soumaoro
1           Andrea Cambiaso          andrea cambiaso
2          Antonio Raimondo         antonio raimondo
3   Charalampos Lykogiannis  charalampos lykogiannis
4              Denso Kasius             denso kasius
5           Emanuel Vignato          emanuel vignato
6         Federico Ravaglia        federico ravaglia
7           Francesco Bardi          francesco bardi
8            Gabriele Corbo           gabriele corbo
9                Gary Medel               gary medel
10   Georgios Kyriakopoulos   georgios kyriakopoulos
11           Jerdy Schouten           jerdy schouten
12              Jhon Lucumí              jhon lucumi
13             Joaquín Sosa             joaquin sosa
14           Joshua Zirkzee           joshua zirkzee
15          Kacper Urbanski          kacper urbanski
16           Kevin Bonifazi           kevin bonifazi
17           Lewis Ferguson           lewis ferguson
18     Lorenzo De Silvestri     lorenzo de silvestri
19         Lukasz Skorupski         lukasz skorupski
20         Marko Arnautovic         marko arnautovic
21         Michel Aebischer         michel aebischer
22              Musa Barrow              musa barrow
23              Musa Juwara              musa juwara
24         Nicola Bagnolini         nicola bagnolini
25           Nicola Sansone           nicola sansone
26        Nicolás Domínguez        nicolas dominguez
27              Nikola Moro              nikola moro
28            Orji Okwonkwo            orji okwonkwo
29        Riccardo Orsolini        riccardo orsolini
30          Roberto Soriano          roberto soriano
31             Stefan Posch             stefan posch
32              Wisdom Amey              wisdom amey

============================================================
  Cremonese  —  SF sin salario:

                player  minutesPlayed
0  Alberto Basso Ricci             15
1    Samuel Di Carmine             34

  CG plantilla completa:

                 player          player_norm
0          Alex Ferrari         alex ferrari
1        Charles Pickel       charles pickel
2      Christian Acella     christian acella
3    Cristian Buonaiuto   cristian buonaiuto
4        Cyriel Dessers       cyriel dessers
5        Daniel Ciofani       daniel ciofani
6         David Okereke        david okereke
7     Dorian Ciezkowski    dorian ciezkowski
8          Emanuel Aiwu         emanuel aiwu
9       Emanuele Valeri      emanuele valeri
10     Felix Afena-Gyan     felix afena gyan
11       Frank Tsadjout       frank tsadjout
12    Giacomo Quagliata    giacomo quagliata
13        Gianluca Saro        gianluca saro
14    Gonzalo Escalante    gonzalo escalante
15           Ionut Radu           ionut radu
16          Jack Hendry          jack hendry
17           Jaime Báez           jaime baez
18        Johan Vásquez        johan vasquez
19   Leonardo Sernicola   leonardo sernicola
20     Luca Zanimacchia     luca zanimacchia
21     Luka Lochoshvili     luka lochoshvili
22        Maissa Ndiaye        maissa ndiaye
23        Marco Benassi        marco benassi
24    Marco Carnesecchi    marco carnesecchi
25    Matteo Bianchetti    matteo bianchetti
26  Michele Castagnetti  michele castagnetti
27      Mouhamadou Sarr      mouhamadou sarr
28       Pablo Galdames       pablo galdames
29      Paolo Ghiglione      paolo ghiglione
30   Santiago Ascacíbar   santiago ascacibar
31       Soualiho Meïté       soualiho meite
32     Tommaso Milanese     tommaso milanese
33       Vlad Chiriches       vlad chiriches

============================================================
  Empoli  —  SF sin salario:

             player  minutesPlayed
0  Herculano Nabian              1

  CG plantilla completa:

                    player             player_norm
0           Alberto Grassi          alberto grassi
1           Ardian Ismajli          ardian ismajli
2   Duccio Degli Innocenti  duccio degli innocenti
3          Emanuel Vignato         emanuel vignato
4           Emmanuel Ekong          emmanuel ekong
5           Fabiano Parisi          fabiano parisi
6       Filippo Bandinelli      filippo bandinelli
7         Francesco Caputo        francesco caputo
8         Gabriele Guarino        gabriele guarino
9        Guglielmo Vicario       guglielmo vicario
10          Jacopo Fazzini          jacopo fazzini
11  Jean-Daniel Akpa Akpro  jean daniel akpa akpro
12          Koni De Winter          koni de winter
13          Liam Henderson          liam henderson
14         Liberato Cacace         liberato cacace
15         Lorenzo Tonelli         lorenzo tonelli
16          Lovro Stubljar          lovro stubljar
17             Marko Pjaca             marko pjaca
18         Martín Satriano         martin satriano
19           Mattia Destro           mattia destro
20           Nedim Bajrami           nedim bajrami
21            Nicolas Haas            nicolas haas
22        Nicolò Cambiaghi        nicolo cambiaghi
23        Petar Stojanovic        petar stojanovic
24            Razvan Marin            razvan marin
25         Roberto Piccoli         roberto piccoli
26             Sam Lammers             sam lammers
27            Samir Ujkani            samir ujkani
28         Samuele Perisan         samuele perisan
29   Sebastian Walukiewicz   sebastian walukiewicz
30      Sebastiano Luperto      sebastiano luperto
31        Tommaso Baldanzi        tommaso baldanzi
32          Tyronne Ebuehi          tyronne ebuehi

============================================================
  Hellas Verona  —  SF sin salario:

              player  minutesPlayed
0  Panagiotis Retsos            122

  CG plantilla completa:

                   player            player_norm
0            Adolfo Gaich           adolfo gaich
1           Adrien Tamèze          adrien tameze
2           Ajdin Hrustic          ajdin hrustic
3      Alessandro Berardi     alessandro berardi
4   Alessandro Cortinovis  alessandro cortinovis
5            Cyril Ngonge           cyril ngonge
6           Darko Lazović          darko lazovic
7          Davide Faraoni         davide faraoni
8      Deyovaisio Zeefuik     deyovaisio zeefuik
9           Diego Coppola          diego coppola
10          Fabio Depaoli          fabio depaoli
11    Federico Ceccherini    federico ceccherini
12    Filippo Terracciano    filippo terracciano
13    Giangiacomo Magnani    giangiacomo magnani
14       Ibrahim Sulemana       ibrahim sulemana
15              Isak Hien              isak hien
16              Ivan Ilic              ivan ilic
17           Jayden Braaf           jayden braaf
18              Josh Doig              josh doig
19             Juan Cabal             juan cabal
20          Kevin Lasagna          kevin lasagna
21           Koray Günter           koray gunter
22        Lorenzo Montipò        lorenzo montipo
23          Martin Hongla          martin hongla
24      Mateusz Praszelik      mateusz praszelik
25          Mattia Chiesa          mattia chiesa
26          Miguel Veloso          miguel veloso
27           Milan Djuric           milan djuric
28      Oliver Abildgaard      oliver abildgaard
29            Ondrej Duda            ondrej duda
30       Pawel Dawidowicz       pawel dawidowicz
31        Roberto Piccoli        roberto piccoli
32         Simone Perilli         simone perilli
33           Simone Verdi           simone verdi
34           Thomas Henry           thomas henry
35           Yayah Kallon           yayah kallon

============================================================
  Juventus  —  SF sin salario:

             player  minutesPlayed
0     Denis Zakaria            122
1  Enzo Barrenechea            159
2  Tommaso Barbieri            114

  CG plantilla completa:

                 player          player_norm
0          Aaron Ramsey         aaron ramsey
1         Adrien Rabiot        adrien rabiot
2           Alex Sandro          alex sandro
3        Ángel Di María       angel di maria
4       Arkadiusz Milik      arkadiusz milik
5                Arthur               arthur
6                Bremer               bremer
7       Carlo Pinsoglio      carlo pinsoglio
8        Daniele Rugani       daniele rugani
9                Danilo               danilo
10       Dusan Vlahovic       dusan vlahovic
11        Fabio Miretti        fabio miretti
12      Federico Chiesa      federico chiesa
13       Federico Gatti       federico gatti
14         Filip Kostić         filip kostic
15        Juan Cuadrado        juan cuadrado
16           Kaio Jorge           kaio jorge
17      Leandro Paredes      leandro paredes
18     Leonardo Bonucci     leonardo bonucci
19     Manuel Locatelli     manuel locatelli
20           Marley Aké           marley ake
21         Matías Soulé         matias soule
22    Mattia De Sciglio    mattia de sciglio
23         Mattia Perin         mattia perin
24    Mohamed Ihattaren    mohamed ihattaren
25           Moise Kean           moise kean
26       Nicolò Fagioli       nicolo fagioli
27       Nicolò Rovella       nicolo rovella
28           Paul Pogba           paul pogba
29  Samuel Iling Junior  samuel iling junior
30      Weston McKennie      weston mckennie
31    Wojciech Szczesny    wojciech szczesny

============================================================
  Monza  —  SF sin salario:

             player  minutesPlayed
0  Andrea Ranocchia             48

  CG plantilla completa:

                   player            player_norm
0   Alessandro Sorrentino  alessandro sorrentino
1          Alessio Cragno         alessio cragno
2         Andrea Barberis        andrea barberis
3          Andrea Carboni         andrea carboni
4          Andrea Colpani         andrea colpani
5          Andrea Petagna         andrea petagna
6       Antonis Siatounis      antonis siatounis
7            Armando Izzo           armando izzo
8          Carlos Augusto         carlos augusto
9      Christian Gytkjaer     christian gytkjaer
10              Dany Mota              dany mota
11        Eugenio Lamanna        eugenio lamanna
12      Filippo Ranocchia      filippo ranocchia
13         Franco Carboni         franco carboni
14        Gabriel Paletta        gabriel paletta
15     Gabriele Ferrarini     gabriele ferrarini
16       Gianluca Caprari       gianluca caprari
17          Giulio Donati          giulio donati
18            José Machín            jose machin
19         Luca Caldirola         luca caldirola
20           Luca Marrone           luca marrone
21     Marco D'Alessandro     marco d alessandro
22                 Marlon                 marlon
23         Matteo Pessina         matteo pessina
24     Matteo Scozzarella     matteo scozzarella
25          Mattia Valoti          mattia valoti
26    Michele Di Gregorio    michele di gregorio
27            Mirko Maric            mirko maric
28          Nicola Rigoni          nicola rigoni
29         Nicolò Rovella         nicolo rovella
30             Pablo Marí             pablo mari
31        Patrick Ciurria        patrick ciurria
32       Salvatore Molina       salvatore molina
33     Samuele Birindelli     samuele birindelli
34        Samuele Vignato        samuele vignato
35          Stefano Sensi          stefano sensi
36         Valentin Antov         valentin antov
37           Warren Bondo           warren bondo

============================================================
  Napoli  —  SF sin salario:

       player  minutesPlayed
0  Adam Ounas             24

  CG plantilla completa:

                   player            player_norm
0       Alessandro Zanoli      alessandro zanoli
1          Alessio Zerbin         alessio zerbin
2              Alex Meret             alex meret
3           Amir Rrahmani          amir rrahmani
4    André Zambo Anguissa   andre zambo anguissa
5     Bartosz Bereszynski    bartosz bereszynski
6         Davide Marfella        davide marfella
7             Diego Demme            diego demme
8             Eljif Elmas            eljif elmas
9       Giacomo Raspadori      giacomo raspadori
10       Gianluca Gaetano       gianluca gaetano
11    Giovanni Di Lorenzo    giovanni di lorenzo
12       Giovanni Simeone       giovanni simeone
13         Hirving Lozano         hirving lozano
14         Hubert Idasiak         hubert idasiak
15             Juan Jesus             juan jesus
16          Karim Zedadka          karim zedadka
17  Khvicha Kvaratskhelia  khvicha kvaratskhelia
18           Leo Östigard           leo ostigard
19              Mário Rui              mario rui
20        Mathías Olivera        mathias olivera
21        Matteo Politano        matteo politano
22            Min-jae Kim            min jae kim
23      Pierluigi Gollini      pierluigi gollini
24        Piotr Zielinski        piotr zielinski
25       Salvatore Sirigu       salvatore sirigu
26      Stanislav Lobotka      stanislav lobotka
27        Tanguy Ndombélé        tanguy ndombele
28         Victor Osimhen         victor osimhen

============================================================
  Roma  —  SF sin salario:

               player  minutesPlayed
0  Benjamin Tahirović            365
1     Filippo Missori            181
2    Jordan Majchrzak             13
3     Niccolò Pisilli              1

  CG plantilla completa:

                 player          player_norm
0        Andrea Belotti       andrea belotti
1            Ante Coric           ante coric
2       Bryan Cristante      bryan cristante
3        Chris Smalling       chris smalling
4      Cristian Volpato     cristian volpato
5        Diego Llorente       diego llorente
6         Ebrima Darboe        ebrima darboe
7          Edoardo Bove         edoardo bove
8      Eldor Shomurodov     eldor shomurodov
9         Filippo Tripi        filippo tripi
10  Georginio Wijnaldum  georginio wijnaldum
11     Gianluca Mancini     gianluca mancini
12  Leonardo Spinazzola  leonardo spinazzola
13   Lorenzo Pellegrini   lorenzo pellegrini
14          Mady Camara          mady camara
15      Marash Kumbulla      marash kumbulla
16          Matías Viña          matias vina
17          Mile Svilar          mile svilar
18        Nemanja Matić        nemanja matic
19      Nicola Zalewski      nicola zalewski
20       Nicolò Zaniolo       nicolo zaniolo
21        Ola Solbakken        ola solbakken
22         Paulo Dybala         paulo dybala
23          Pietro Boer          pietro boer
24        Rick Karsdorp        rick karsdorp
25         Roger Ibañez         roger ibanez
26         Rui Patrício         rui patricio
27  Stephan El Shaarawy  stephan el shaarawy
28        Tammy Abraham        tammy abraham
29       William Bianda       william bianda
30           Zeki Celik           zeki celik

============================================================
  Salernitana  —  SF sin salario:

          player  minutesPlayed
0  Franck Ribéry             36

  CG plantilla completa:

                     player              player_norm
0          Alessandro Micai         alessandro micai
1              Andrei Motoc             andrei motoc
2          Antonio Candreva         antonio candreva
3     Antonio Pio Iervolino    antonio pio iervolino
4               Boulaye Dia              boulaye dia
5            Diego Valencia           diego valencia
6          Domagoj Bradaric         domagoj bradaric
7             Domen Crnigoj            domen crnigoj
8               Dylan Bronn              dylan bronn
9              Emil Bohinen             emil bohinen
10             Erik Botheim             erik botheim
11       Federico Bonazzoli       federico bonazzoli
12           Federico Fazio           federico fazio
13         Flavius Daniliuc         flavius daniliuc
14        Francesco Orlando        francesco orlando
15          Giulio Maggiore          giulio maggiore
16        Grigoris Kastanos        grigoris kastanos
17          Guillermo Ochoa          guillermo ochoa
18  Hans Nicolussi Caviglia  hans nicolussi caviglia
19         Ivan Radovanovic         ivan radovanovic
20     Julian Kristoffersen     julian kristoffersen
21            Junior Sambia            junior sambia
22         Krzysztof Piatek         krzysztof piatek
23        Lassana Coulibaly        lassana coulibaly
24         Leonardo Capezzi         leonardo capezzi
25           Lorenzo Pirola           lorenzo pirola
26               Luigi Sepe               luigi sepe
27            Matteo Lovato            matteo lovato
28          Norbert Gyomber          norbert gyomber
29       Pasquale Mazzocchi       pasquale mazzocchi
30                Sanasi Sy                sanasi sy
31            Tonny Vilhena            tonny vilhena
32        Vincenzo Fiorillo        vincenzo fiorillo
33     William Troost-Ekong     william troost ekong

============================================================
  Sampdoria  —  SF sin salario:

             player  minutesPlayed
0   Flavio Paoletti            288
1  Mihailo Ivanović              2
2     Samuel Ntanda              1

  CG plantilla completa:

                 player          player_norm
0     Abdelhamid Sabiri    abdelhamid sabiri
1     Alessandro Zanoli    alessandro zanoli
2          Alex Ferrari         alex ferrari
3          Andrea Conti         andrea conti
4   Bartosz Bereszynski  bartosz bereszynski
5         Bram Nuytinck        bram nuytinck
6          Bruno Amione         bruno amione
7     Daniele Montevago    daniele montevago
8      Elia Tantalocchi     elia tantalocchi
9           Emil Audero          emil audero
10       Emirhan Ilkhan       emirhan ilkhan
11   Fabio Quagliarella   fabio quagliarella
12       Filip Djuricic       filip djuricic
13     Francesco Caputo     francesco caputo
14         Gerard Yepes         gerard yepes
15       Gonzalo Villar       gonzalo villar
16          Harry Winks          harry winks
17     Ignacio Pussetto     ignacio pussetto
18       Jeison Murillo       jeison murillo
19                 Jesé                 jese
20         Koray Günter         koray gunter
21    Lorenzo Malagrida    lorenzo malagrida
22    Manolo Gabbiadini    manolo gabbiadini
23       Manuel De Luca       manuel de luca
24     Marios Oikonomou     marios oikonomou
25          Martin Turk          martin turk
26          Mehdi Léris          mehdi leris
27     Michaël Cuisance     michael cuisance
28         Nicola Murru         nicola murru
29      Nicola Ravaglia      nicola ravaglia
30       Nikita Contini       nikita contini
31          Omar Colley          omar colley
32       Ronaldo Vieira       ronaldo vieira
33          Sam Lammers          sam lammers
34      Simone Trimboli      simone trimboli
35      Telasco Segovia      telasco segovia
36         Tomás Rincón         tomas rincon
37      Tommaso Augello      tommaso augello
38        Valerio Verre        valerio verre

============================================================
  Torino  —  SF sin salario:

         player  minutesPlayed
0  Jacopo Segre             20

  CG plantilla completa:

                     player              player_norm
0         Aleksey Miranchuk        aleksey miranchuk
1     Alessandro Buongiorno    alessandro buongiorno
2         Andreaw Gravillon        andreaw gravillon
3          Antonio Sanabria         antonio sanabria
4              Brian Bayeye             brian bayeye
5                David Zima               david zima
6                Demba Seck               demba seck
7            Emirhan Ilkhan           emirhan ilkhan
8             Etrit Berisha            etrit berisha
9           Gvidas Gineitis          gvidas gineitis
10                Ivan Ilić                ivan ilic
11            Karol Linetty            karol linetty
12             Koffi Djidji             koffi djidji
13             Luca Gemello             luca gemello
14          Matteo Fiorenza          matteo fiorenza
15          Matthew Garbett          matthew garbett
16           Mërgim Vojvoda           mergim vojvoda
17       Michel Ndary Adopo       michel ndary adopo
18         Nemanja Radonjić         nemanja radonjic
19            Nikola Vlasic            nikola vlasic
20                 Ola Aina                 ola aina
21             Perr Schuurs             perr schuurs
22          Pietro Pellegri          pietro pellegri
23        Ricardo Rodríguez        ricardo rodriguez
24           Ronaldo Vieira           ronaldo vieira
25            Samuele Ricci            samuele ricci
26               Sasa Lukic               sasa lukic
27             Simone Edera             simone edera
28         Valentino Lazaro         valentino lazaro
29   Vanja Milinković-Savić   vanja milinkovic savic
30  Wilfried Stephane Singo  wilfried stephane singo
31             Yann Karamoh             yann karamoh

============================================================
  Udinese  —  SF sin salario:

            player  minutesPlayed
0  Niccolò Cocetta             31
1          Vivaldo             42

  CG plantilla completa:

                 player          player_norm
0           Adam Masina          adam masina
1         Axel Guessand        axel guessand
2                  Beto                 beto
3         Bram Nuytinck        bram nuytinck
4       Daniele Padelli      daniele padelli
5        Destiny Udogie       destiny udogie
6         Edoardo Piana        edoardo piana
7           Enzo Ebosse          enzo ebosse
8         Festy Ebosele        festy ebosele
9       Florian Thauvin      florian thauvin
10      Gerard Deulofeu      gerard deulofeu
11    Ilija Nestorovski    ilija nestorovski
12        Isaac Success        isaac success
13           Jaka Bijol           jaka bijol
14       James Abankwah       james abankwah
15  Jean-Victor Makengo  jean victor makengo
16    Kingsley Ehizibue    kingsley ehizibue
17      Lazar Samardzic      lazar samardzic
18        Leonardo Buta        leonardo buta
19      Marco Silvestri      marco silvestri
20     Marvin Zeegelaar     marvin zeegelaar
21          Mato Jajalo          mato jajalo
22         Nehuén Pérez         nehuen perez
23      Roberto Pereyra      roberto pereyra
24        Rodrigo Becão        rodrigo becao
25         Sandi Lovric         sandi lovric
26       Simone Pafundi       simone pafundi
27        Tolgay Arslan        tolgay arslan
28               Walace               walace

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {

}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 0

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

Tras matches manuales: 554/577 (96.0%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_italy_2223.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_italy_2223.csv
   Jugadores totales:  577
   Con salario:        554
   Sin salario (NaN):  23
   Columnas:           121