# 03 · Join Sofascore + Capology — Spain La Liga 22/23

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2022/23 de La Liga española**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_spain_2223.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_spain_2223.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  584 jugadores | 116 columnas
Capology:   543 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   girona fc
   real valladolid

En Capology pero no en Sofascore:
   girona
   valladolid

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'girona':'girona fc',
            'valladolid':'real valladolid'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 485/584 (83.0%)
Sin emparejar: 99

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          10
Revisión media    (0.75 ≤ score < 0.90):   11
Revisión estricta (0.50 ≤ score < 0.75):   50
Revisión muy est. (score < 0.50):           28

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf             team              cg_match  score
29  Jørgen Strand Larsen       Celta Vigo  jorgen strand larsen  0.974
22     Alexander Sørloth    Real Sociedad     alexander sorloth  0.970
85       Filip Jørgensen       Villarreal       filip jorgensen  0.966
6       Viktor Tsygankov        Girona FC      viktor tsyhankov  0.938
28      Javier Hernández        Girona FC        javi hernandez  0.933
37        Manuel Sánchez          Osasuna          manu sanchez  0.923
78          Juan Narváez  Real Valladolid        juanjo narvaez  0.923
14         Daniel Vivian    Athletic Club           dani vivian  0.917
10           Yéremy Pino       Villarreal           yeremi pino  0.909
30           Srđan Babić          Almería          srdjan babic  0.909

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf             team                  cg_match  score
57        Nicolás Melamed         Espanyol              nico melamed  0.889
60        Josep Chavarría   Rayo Vallecano             pep chavarria  0.857
84         Wassim Keddari         Espanyol              simo keddari  0.846
21  Abdessamad Ezzalzouli          Osasuna           abde ezzalzouli  0.833
58      Nicolás Fernández            Elche  nicolas fernandez mercau  0.829
1      José María Giménez  Atlético Madrid              jose gimenez  0.800
13         Rober González       Real Betis            edgar gonzalez  0.786
45          Mamadou Mbaye            Cádiz                momo mbaye  0.783
2          José Luis Gayà         Valencia                 jose gaya  0.783
27     Luis Javier Suárez          Almería               luis suarez  0.759
20       Álvaro Rodriguez      Real Madrid          alvaro odriozola  0.750

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['rober gonzalez',
                      'alvaro rodriguez'
]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 9 | Excluidos: 2

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                  player_sf             team           cg_match  score
38        Pathé Ismaël Ciss   Rayo Vallecano         pathe ciss  0.741
3             Jorge Pascual       Villarreal       jorge cuenca  0.720
8           Alejandro Baena       Villarreal         alex baena  0.720
53           Anthony Lozano            Cádiz     antonio blanco  0.714
18           Alexander Isak    Real Sociedad  alexander sorloth  0.710
72        Alberto del Moral       Villarreal     alberto moreno  0.710
96             Diego Mendez   Rayo Vallecano        diego lopez  0.696
32              Hugo Sotelo       Celta Vigo         hugo mallo  0.667
36         Miguel Rodríguez       Celta Vigo    oscar rodriguez  0.645
9          Fernando Medrano       Celta Vigo       fran beltran  0.643
52             Ander Martín    Real Sociedad      ander guevara  0.640
64            Mamady Diarra            Cádiz       youba diarra  0.640
87              Pablo Muñoz   Rayo Vallecano        abdul mumin  0.636
35              Iker Benito          Osasuna       kike saverio  0.609
91         Alejandro Alfaro            Elche  lisandro magallan  0.606
63           Radamel Falcao   Rayo Vallecano             falcao  0.600
12  Jose Antonio de la Rosa            Cádiz     antonio blanco  0.595
73             Fran Delgado       Real Betis    andres guardado  0.593
49            Alberto Perea            Cádiz     alvaro negredo  0.593
33            Aleix Garrido        Barcelona        eric garcia  0.583
23              Malcom Ares    Athletic Club      aitor paredes  0.583
93           Jorge Herrando          Osasuna  aridane hernandez  0.581
19               Kike Salas          Sevilla        erik lamela  0.571
11               Pablo Gavi        Barcelona               gavi  0.571
66                 Casemiro      Real Madrid      marco asensio  0.571
40           Haissem Hassan       Villarreal        aissa mandi  0.560
15            Rodri Sánchez       Real Betis              rodri  0.556
7             Carlos García            Cádiz          jose mari  0.545
67           Carlos Álvarez          Sevilla       marcos acuna  0.538
76            Fernando Niño       Villarreal      gerard moreno  0.538
81            Sekou Gassama  Real Valladolid      shon weissman  0.538
44            Carlos Martín  Atlético Madrid      alvaro morata  0.538
65           Roger Martínez         Espanyol   alvaro fernandez  0.533
90            Antonio Gomis  Atlético Madrid  antoine griezmann  0.533
80           Abner Vinícius       Real Betis              abner  0.526
68              Iván Romero          Sevilla       ivan rakitic  0.522
75              Pablo Durán       Celta Vigo       fran beltran  0.522
42              Pablo Marín    Real Sociedad       mikel merino  0.522
83           Mamadou Mbacke       Villarreal      manu morlanes  0.519
56            Ricard Artero        Girona FC     arnau martinez  0.519
4    Alvaro Aceves Catalina  Real Valladolid      alvaro aguado  0.514
34                Moi Parra           Getafe    mauro arambarri  0.500
24            Curro Sánchez          Almería        luis suarez  0.500
5              Carlos Soler         Valencia       marcos andre  0.500
17              Diego López         Valencia      nico gonzalez  0.500
25               Manu Bueno          Sevilla     tanguy nianzou  0.500
55             Alberto Mari         Valencia       marcos andre  0.500
62                Joel Roca        Girona FC        oriol romeu  0.500
43               Iker Muñoz          Osasuna         aimar oroz  0.500
41            Javier Guerra         Valencia    thierry correia  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['pathe ismael ciss',
                    'alejandro baena',
                    'radamel falcao',
                    'pablo gavi',
                    'rodri sanchez',
                    'abner vinicius'                    
]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 6

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                    player_sf             team             cg_match  score
16       Jon Ander Olasagasti    Real Sociedad    alexander sorloth  0.486
48            Francisco Mwepu            Cádiz       alfonso espino  0.483
26           Jon Magunazelaia    Real Sociedad        igor zubeldia  0.483
98              Álex Revuelta           Getafe         carles alena  0.480
69              Nabil Touaizi         Espanyol         denis suarez  0.480
46                Oscar Ureña        Girona FC       santiago bueno  0.480
86                 Fran Pérez         Valencia      cristian rivero  0.480
95                Pedro Ortiz          Sevilla       kasper dolberg  0.480
71               Javi Llabrés         Mallorca        manu morlanes  0.480
61               Diego Moreno          Osasuna        jon moncayola  0.480
39              Luca Koleosho         Espanyol         edu exposito  0.480
51                 Josep Gayá         Mallorca          jose copete  0.476
94                 Chadi Riad        Barcelona          eric garcia  0.476
79          Maximiliano Gómez         Valencia        nico gonzalez  0.467
82              Ángel Alarcón        Barcelona        ronald araujo  0.462
59             Sergio Arribas      Real Madrid         mariano diaz  0.462
54            Jon Karrikaburu    Real Sociedad     andoni zubiaurre  0.452
70         Babatunde Akinsola  Real Valladolid        martin hongla  0.452
89               Lamine Yamal        Barcelona      ousmane dembele  0.444
50              Diego Collado       Villarreal       etienne capoue  0.444
74             Roberto Arroyo  Real Valladolid        sergio asenjo  0.444
0               Félix Garreta       Real Betis      andres guardado  0.429
47       Manuel Pozo Guerrero  Real Valladolid        alvaro aguado  0.424
77               David Torres  Real Valladolid         javi sanchez  0.417
31  Pierre-Emerick Aubameyang        Barcelona      hector bellerin  0.400
92              Diego Hormigo          Sevilla         jesus corona  0.400
97          Ruben Quintanilla         Mallorca  dennis hadzikadunic  0.389
88                Pape Cheikh            Elche           pere milla  0.381

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 510/584 (87.3%)
Sin salario:     74

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [18]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 74

,player,team,minutesPlayed,appearances,goals,assists
0,Curro Sánchez,Almería,41,2,0,0
1,Malcom Ares,Athletic Club,93,8,0,0
2,Carlos Martín,Atlético Madrid,29,4,0,0
3,Antonio Gomis,Atlético Madrid,11,1,0,0
4,Ángel Alarcón,Barcelona,28,4,0,0
5,Lamine Yamal,Barcelona,11,1,0,0
6,Aleix Garrido,Barcelona,9,1,0,0
7,Pierre-Emerick Aubameyang,Barcelona,8,1,0,0
8,Chadi Riad,Barcelona,1,1,0,0
9,Miguel Rodríguez,Celta Vigo,250,7,1,1
10,Pablo Durán,Celta Vigo,50,4,0,0
11,Hugo Sotelo,Celta Vigo,16,1,0,0
12,Fernando Medrano,Celta Vigo,12,1,0,0
13,Anthony Lozano,Cádiz,1440,28,1,1
14,Mamady Diarra,Cádiz,75,2,0,0
15,Alberto Perea,Cádiz,45,1,0,0
16,Jose Antonio de la Rosa,Cádiz,44,2,0,1
17,Carlos García,Cádiz,24,1,0,1
18,Francisco Mwepu,Cádiz,20,1,0,0
19,Pape Cheikh,Elche,40,2,0,0
20,Alejandro Alfaro,Elche,14,1,0,0
21,Luca Koleosho,Espanyol,57,4,1,0
22,Roger Martínez,Espanyol,12,1,0,0
23,Nabil Touaizi,Espanyol,12,1,0,0
24,Moi Parra,Getafe,9,1,0,0
25,Álex Revuelta,Getafe,1,1,0,0
26,Ricard Artero,Girona FC,133,7,0,0
27,Oscar Ureña,Girona FC,99,3,0,0
28,Joel Roca,Girona FC,87,5,0,0
29,Josep Gayá,Mallorca,58,2,0,0
30,Javi Llabrés,Mallorca,16,1,0,0
31,Ruben Quintanilla,Mallorca,3,1,0,0
32,Diego Moreno,Osasuna,641,11,0,0
33,Iker Muñoz,Osasuna,250,8,0,0
34,Iker Benito,Osasuna,176,4,0,0
35,Jorge Herrando,Osasuna,27,1,0,0
36,Pablo Muñoz,Rayo Vallecano,11,2,0,0
37,Diego Mendez,Rayo Vallecano,1,1,0,0
38,Félix Garreta,Real Betis,90,1,0,0
39,Rober González,Real Betis,52,2,0,0
40,Fran Delgado,Real Betis,11,1,0,0
41,Álvaro Rodriguez,Real Madrid,87,6,1,1
42,Sergio Arribas,Real Madrid,17,2,0,0
43,Casemiro,Real Madrid,13,1,0,0
44,Pablo Marín,Real Sociedad,361,10,0,0
45,Alexander Isak,Real Sociedad,154,2,1,0
46,Jon Karrikaburu,Real Sociedad,102,6,0,0
47,Jon Magunazelaia,Real Sociedad,64,2,0,0
48,Jon Ander Olasagasti,Real Sociedad,63,3,0,0
49,Ander Martín,Real Sociedad,43,3,0,0
50,David Torres,Real Valladolid,381,7,0,0
51,Sekou Gassama,Real Valladolid,35,1,0,0
52,Manuel Pozo Guerrero,Real Valladolid,18,1,0,0
53,Roberto Arroyo,Real Valladolid,14,1,0,0
54,Alvaro Aceves Catalina,Real Valladolid,12,1,0,0
55,Babatunde Akinsola,Real Valladolid,10,1,0,0
56,Kike Salas,Sevilla,380,6,1,1
57,Manu Bueno,Sevilla,150,2,0,0
58,Diego Hormigo,Sevilla,45,1,0,0
59,Iván Romero,Sevilla,10,1,0,0
60,Carlos Álvarez,Sevilla,9,1,0,0
61,Pedro Ortiz,Sevilla,1,1,0,0
62,Javier Guerra,Valencia,608,10,1,0
63,Diego López,Valencia,453,10,3,1
64,Carlos Soler,Valencia,243,3,1,0
65,Fran Pérez,Valencia,146,7,0,0
66,Maximiliano Gómez,Valencia,106,3,0,0
67,Alberto Mari,Valencia,85,5,1,0
68,Haissem Hassan,Villarreal,50,2,0,0
69,Mamadou Mbacke,Villarreal,29,1,0,0
70,Fernando Niño,Villarreal,24,3,0,0
71,Diego Collado,Villarreal,17,2,0,0
72,Jorge Pascual,Villarreal,14,2,1,0
73,Alberto del Moral,Villarreal,9,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [19]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Almería  —  SF sin salario:

          player  minutesPlayed
0  Curro Sánchez             41

  CG plantilla completa:

                player         player_norm
0       Adrián Embarba      adrian embarba
1       Alejandro Pozo      alejandro pozo
2       Álex Centelles      alex centelles
3        Arnau Puigmal       arnau puigmal
4      César de la Hoz     cesar de la hoz
5                Chumi               chumi
6          Diego Fuoli         diego fuoli
7         Diego Mariño        diego marino
8          Dyego Sousa         dyego sousa
9       El Bilal Touré      el bilal toure
10   Fernando Martínez   fernando martinez
11    Fernando Pacheco    fernando pacheco
12  Francisco Portillo  francisco portillo
13      Gonzalo Melero      gonzalo melero
14          Gui Guedes          gui guedes
15   Houboulang Mendes   houboulang mendes
16       Iñigo Eguaras       inigo eguaras
17         Iván Martos         ivan martos
18        Juanjo Nieto        juanjo nieto
19               Kaiky               kaiky
20     Largie Ramazani     largie ramazani
21              Lázaro              lazaro
22       Léo Baptistão       leo baptistao
23     Lucas Robertone     lucas robertone
24         Luis Suárez         luis suarez
25   Marko Milovanovic   marko milovanovic
26    Martin Svidersky    martin svidersky
27         Rodrigo Ely         rodrigo ely
28          Samú Costa          samu costa
29       Sergio Akieme       sergio akieme
30        Srdjan Babic        srdjan babic

============================================================
  Athletic Club  —  SF sin salario:

        player  minutesPlayed
0  Malcom Ares             93

  CG plantilla completa:

                player         player_norm
0        Aitor Paredes       aitor paredes
1       Álex Berenguer      alex berenguer
2           Ander Capa          ander capa
3        Ander Herrera       ander herrera
4            Ander Iru           ander iru
5     Asier Villalibre    asier villalibre
6          Dani García         dani garcia
7          Dani Vivian         dani vivian
8       Gorka Guruzeta      gorka guruzeta
9         Iker Muniain        iker muniain
10      Iñaki Williams      inaki williams
11         Iñigo Lekue         inigo lekue
12      Iñigo Martínez      inigo martinez
13        Jon Morcillo        jon morcillo
14  Julen Agirrezabala  julen agirrezabala
15    Mikel Balenziaga    mikel balenziaga
16         Mikel Vesga         mikel vesga
17       Nico Williams       nico williams
18        Oier Zarraga        oier zarraga
19        Oihan Sancet        oihan sancet
20     Óscar de Marcos     oscar de marcos
21         Raúl García         raul garcia
22          Unai Simón          unai simon
23       Unai Vencedor       unai vencedor
24       Yeray Álvarez       yeray alvarez
25      Yuri Berchiche      yuri berchiche

============================================================
  Atlético Madrid  —  SF sin salario:

          player  minutesPlayed
0  Antonio Gomis             11
1  Carlos Martín             29

  CG plantilla completa:

                player         player_norm
0        Álvaro Morata       alvaro morata
1         Ángel Correa        angel correa
2    Antoine Griezmann   antoine griezmann
3          Axel Witsel         axel witsel
4               Felipe              felipe
5   Geoffrey Kondogbia  geoffrey kondogbia
6            Ivo Grbic           ivo grbic
7            Jan Oblak           jan oblak
8           João Félix          joao felix
9         José Giménez        jose gimenez
10                Koke                koke
11     Marcos Llorente     marcos llorente
12       Mario Hermoso       mario hermoso
13       Matheus Cunha       matheus cunha
14        Matt Doherty        matt doherty
15       Memphis Depay       memphis depay
16       Nahuel Molina       nahuel molina
17       Pablo Barrios       pablo barrios
18    Reinildo Mandava    reinildo mandava
19     Rodrigo de Paul     rodrigo de paul
20         Saúl Ñíguez         saul niguez
21     Sergio Reguilón     sergio reguilon
22        Stefan Savic        stefan savic
23        Thomas Lemar        thomas lemar
24    Yannick Carrasco    yannick carrasco

============================================================
  Barcelona  —  SF sin salario:

                      player  minutesPlayed
0              Aleix Garrido              9
1                 Chadi Riad              1
2               Lamine Yamal             11
3  Pierre-Emerick Aubameyang              8
4              Ángel Alarcón             28

  CG plantilla completa:

                   player            player_norm
0         Alejandro Balde        alejandro balde
1     Andreas Christensen    andreas christensen
2               Ansu Fati              ansu fati
3             Arnau Tenas            arnau tenas
4             Eric García            eric garcia
5           Ferran Torres          ferran torres
6           Franck Kessié          franck kessie
7         Frenkie de Jong        frenkie de jong
8                    Gavi                   gavi
9            Gerard Piqué           gerard pique
10        Héctor Bellerín        hector bellerin
11             Iñaki Peña             inaki pena
12             Jordi Alba             jordi alba
13           Jules Koundé           jules kounde
14  Marc-André ter Stegen  marc andre ter stegen
15          Marcos Alonso          marcos alonso
16     Martin Braithwaite     martin braithwaite
17          Memphis Depay          memphis depay
18        Ousmane Dembélé        ousmane dembele
19            Pablo Torre            pablo torre
20                  Pedri                  pedri
21               Raphinha               raphinha
22     Robert Lewandowski     robert lewandowski
23          Ronald Araújo          ronald araujo
24          Sergi Roberto          sergi roberto
25        Sergio Busquets        sergio busquets

============================================================
  Celta Vigo  —  SF sin salario:

             player  minutesPlayed
0  Fernando Medrano             12
1       Hugo Sotelo             16
2  Miguel Rodríguez            250
3       Pablo Durán             50

  CG plantilla completa:

                  player           player_norm
0      Agustín Marchesín     agustin marchesin
1         Augusto Solari        augusto solari
2           Carles Pérez          carles perez
3       Carlos Domínguez      carlos dominguez
4           Denis Suárez          denis suarez
5           Fran Beltrán          fran beltran
6           Franco Cervi          franco cervi
7            Gabri Veiga           gabri veiga
8      Gonçalo Paciência     goncalo paciencia
9        Haris Seferovic       haris seferovic
10            Hugo Mallo            hugo mallo
11            Iago Aspas            iago aspas
12           Iván Villar           ivan villar
13            Javi Galán            javi galan
14  Jörgen Strand Larsen  jorgen strand larsen
15          Joseph Aidoo          joseph aidoo
16         Kevin Vázquez         kevin vazquez
17      Luca de la Torre      luca de la torre
18        Óscar Mingueza        oscar mingueza
19       Óscar Rodríguez       oscar rodriguez
20          Renato Tapia          renato tapia
21            Unai Núñez            unai nunez
22      Williot Swedberg      williot swedberg

============================================================
  Cádiz  —  SF sin salario:

                    player  minutesPlayed
0            Alberto Perea             45
1           Anthony Lozano           1440
2            Carlos García             24
3          Francisco Mwepu             20
4  Jose Antonio de la Rosa             44
5            Mamady Diarra             75

  CG plantilla completa:

                 player          player_norm
0        Álex Fernández       alex fernandez
1        Alfonso Espino       alfonso espino
2        Álvaro Giménez       alvaro gimenez
3        Álvaro Negredo       alvaro negredo
4        Antonio Blanco       antonio blanco
5            Awer Mabil           awer mabil
6          Brian Ocampo         brian ocampo
7          Choco Lozano         choco lozano
8           Chris Ramos          chris ramos
9             David Gil            david gil
10                 Fali                 fali
11    Fede San Emeterio    fede san emeterio
12    Gonzalo Escalante    gonzalo escalante
13           Iván Alejo           ivan alejo
14         Iza Carcelén         iza carcelen
15     Jeremías Ledesma     jeremias ledesma
16    Jon Ander Garrido    jon ander garrido
17           Jorge Meré           jorge mere
18            José Mari            jose mari
19        Joseba Zaldua        joseba zaldua
20            Juan Cala            juan cala
21          Lucas Pérez          lucas perez
22       Luis Hernández       luis hernandez
23           Momo Mbaye           momo mbaye
24           Raúl Parra           raul parra
25          Roger Martí          roger marti
26        Rubén Alcaraz        ruben alcaraz
27        Rubén Sobrino        ruben sobrino
28  Santiago Arzamendia  santiago arzamendia
29      Sergi Guardiola      sergi guardiola
30        Théo Bongonda        theo bongonda
31        Tomás Alarcón        tomas alarcon
32         Víctor Chust         victor chust
33         Youba Diarra         youba diarra

============================================================
  Elche  —  SF sin salario:

             player  minutesPlayed
0  Alejandro Alfaro             14
1       Pape Cheikh             40

  CG plantilla completa:

                      player               player_norm
0               Álex Collado              alex collado
1                Axel Werner               axel werner
2               Carlos Clerc              carlos clerc
3             Diego González            diego gonzalez
4             Domingos Quina            domingos quina
5                Édgar Badía               edgar badia
6                  Enzo Roco                 enzo roco
7             Ezequiel Ponce            ezequiel ponce
8         Federico Fernández        federico fernandez
9                      Fidel                     fidel
10             Gerard Gumbau             gerard gumbau
11             Gonzalo Verdú             gonzalo verdu
12       Helibelton Palacios       helibelton palacios
13            Javier Pastore            javier pastore
14               John Donald               john donald
15                     Josan                     josan
16        José Ángel Carmona        jose angel carmona
17            Lautaro Blanco            lautaro blanco
18         Lisandro Magallán         lisandro magallan
19                Lucas Boyé                lucas boye
20  Nicolás Fernández Mercau  nicolas fernandez mercau
21            Omar Mascarell            omar mascarell
22               Pedro Bigas               pedro bigas
23                Pere Milla                pere milla
24                Pol Lirola                pol lirola
25               Randy Nteka               randy nteka
26                 Raúl Guti                 raul guti
27               Roger Martí               roger marti
28              Tete Morente              tete morente

============================================================
  Espanyol  —  SF sin salario:

           player  minutesPlayed
0   Luca Koleosho             57
1   Nabil Touaizi             12
2  Roger Martínez             12

  CG plantilla completa:

                   player            player_norm
0           Adrià Pedrosa          adria pedrosa
1             Aleix Vidal            aleix vidal
2        Álvaro Fernández       alvaro fernandez
3        Benjamin Lecomte       benjamin lecomte
4            Brian Oliván           brian olivan
5            César Montes           cesar montes
6              Dani Gómez             dani gomez
7            Denis Suárez           denis suarez
8            Edu Expósito           edu exposito
9         Fernando Calero        fernando calero
10       Fernando Pacheco       fernando pacheco
11             Javi Puado             javi puado
12            Joan García            joan garcia
13       José Carlos Lazo       jose carlos lazo
14           José Gragera           jose gragera
15                 Joselu                 joselu
16             Keidi Bare             keidi bare
17        Leandro Cabrera        leandro cabrera
18     Martin Braithwaite     martin braithwaite
19           Nico Melamed           nico melamed
20         Omar El Hilali         omar el hilali
21              Óscar Gil              oscar gil
22             Pol Lozano             pol lozano
23          Raúl de Tomás          raul de tomas
24  Ronaël Pierre-Gabriel  ronael pierre gabriel
25          Rubén Sánchez          ruben sanchez
26           Sergi Darder           sergi darder
27            Sergi Gómez            sergi gomez
28           Simo Keddari           simo keddari
29         Vinicius Souza         vinicius souza

============================================================
  Getafe  —  SF sin salario:

          player  minutesPlayed
0      Moi Parra              9
1  Álex Revuelta              1

  CG plantilla completa:

                player         player_norm
0        Ángel Algobia       angel algobia
1        Borja Mayoral       borja mayoral
2         Carles Aleñá        carles alena
3        Damián Suárez       damian suarez
4          David Soria         david soria
5          Diego Conde         diego conde
6                Djené               djene
7      Domingos Duarte     domingos duarte
8            Enes Ünal           enes unal
9    Fabrizio Angileri   fabrizio angileri
10      Gastón Álvarez      gaston alvarez
11      Gonzalo Villar      gonzalo villar
12          Jaime Mata          jaime mata
13        Jaime Seoane        jaime seoane
14        Jordan Amavi        jordan amavi
15       Juan Iglesias       juan iglesias
16       Juanmi Latasa       juanmi latasa
17        Kiko Casilla        kiko casilla
18          Luis Milla          luis milla
19     Mauro Arambarri     mauro arambarri
20    Munir El Haddadi    munir el haddadi
21  Nemanja Maksimović  nemanja maksimovic
22       Omar Alderete       omar alderete
23               Portu               portu
24     Stefan Mitrović     stefan mitrovic

============================================================
  Girona FC  —  SF sin salario:

          player  minutesPlayed
0      Joel Roca             87
1    Oscar Ureña             99
2  Ricard Artero            133

  CG plantilla completa:

                  player           player_norm
0           Aleix García          aleix garcia
1      Alexander Callens     alexander callens
2         Arnau Martínez        arnau martinez
3      Bernardo Espinosa     bernardo espinosa
4           Borja García          borja garcia
5       Cristhian Stuani      cristhian stuani
6            David López           david lopez
7          Ibrahima Kébé         ibrahima kebe
8            Iván Martín           ivan martin
9         Javi Hernández        javi hernandez
10           Juan Carlos           juan carlos
11                Juanpe                juanpe
12          Manu Vallejo          manu vallejo
13      Miguel Gutiérrez      miguel gutierrez
14           Oriol Romeu           oriol romeu
15       Paulo Gazzaniga       paulo gazzaniga
16         Ramón Terrats         ramon terrats
17               Reinier               reinier
18      Rodrigo Riquelme      rodrigo riquelme
19             Samu Saiz             samu saiz
20        Santiago Bueno        santiago bueno
21          Toni Fuidias          toni fuidias
22            Toni Villa            toni villa
23  Valentín Castellanos  valentin castellanos
24      Valery Fernández      valery fernandez
25      Viktor Tsyhankov      viktor tsyhankov
26             Yan Couto             yan couto
27        Yangel Herrera        yangel herrera

============================================================
  Mallorca  —  SF sin salario:

              player  minutesPlayed
0       Javi Llabrés             16
1         Josep Gayá             58
2  Ruben Quintanilla              3

  CG plantilla completa:

                     player              player_norm
0               Abdón Prats              abdon prats
1              Amath Ndiaye             amath ndiaye
2           Ángel Rodríguez          angel rodriguez
3            Antonio Raíllo           antonio raillo
4           Antonio Sánchez          antonio sanchez
5              Braian Cufré             braian cufre
6           Clément Grenier          clement grenier
7            Dani Rodríguez           dani rodriguez
8       Dennis Hadzikadunic      dennis hadzikadunic
9             Dominik Greif            dominik greif
10             Franco Russo             franco russo
11        Giovanni González        giovanni gonzalez
12             Iddrisu Baba             iddrisu baba
13  Iñigo Ruiz de Galarreta  inigo ruiz de galarreta
14              Jaume Costa              jaume costa
15              José Copete              jose copete
16              Kang-in Lee              kang in lee
17              Lago Júnior              lago junior
18                Leo Román                leo roman
19      Ludwig Augustinsson      ludwig augustinsson
20            Manu Morlanes            manu morlanes
21           Martin Valjent           martin valjent
22          Matija Nastasić          matija nastasic
23             Pablo Maffeo             pablo maffeo
24         Predrag Rajković         predrag rajkovic
25        Rodrigo Battaglia        rodrigo battaglia
26            Tino Kadewere            tino kadewere
27             Vedat Muriqi             vedat muriqi

============================================================
  Osasuna  —  SF sin salario:

           player  minutesPlayed
0    Diego Moreno            641
1     Iker Benito            176
2      Iker Muñoz            250
3  Jorge Herrando             27

  CG plantilla completa:

               player        player_norm
0     Abde Ezzalzouli    abde ezzalzouli
1          Aimar Oroz         aimar oroz
2     Aitor Fernández    aitor fernandez
3        Ante Budimir       ante budimir
4   Aridane Hernández  aridane hernandez
5         Chimy Ávila        chimy avila
6      Darko Brasanac     darko brasanac
7        David García       david garcia
8       Jon Moncayola      jon moncayola
9           Juan Cruz          juan cruz
10         Juan Pérez         juan perez
11         Kike Barja         kike barja
12        Kike García        kike garcia
13       Kike Saverio       kike saverio
14        Lucas Torró        lucas torro
15       Manu Sánchez       manu sanchez
16          Moi Gómez          moi gomez
17        Nacho Vidal        nacho vidal
18       Pablo Ibáñez       pablo ibanez
19     Roberto Torres     roberto torres
20       Rubén García       ruben garcia
21         Rubén Peña         ruben pena
22     Sergio Herrera     sergio herrera
23        Unai García        unai garcia

============================================================
  Rayo Vallecano  —  SF sin salario:

         player  minutesPlayed
0  Diego Mendez              1
1   Pablo Muñoz             11

  CG plantilla completa:

                player         player_norm
0          Abdul Mumin         abdul mumin
1     Alejandro Catena    alejandro catena
2        Álvaro García       alvaro garcia
3        Andrés Martín       andres martin
4                 Bebé                bebe
5          Diego López         diego lopez
6    Esteban Saveljich   esteban saveljich
7               Falcao              falcao
8      Florian Lejeune     florian lejeune
9          Fran García         fran garcia
10         Isi Palazón         isi palazon
11         Iván Balliu         ivan balliu
12           José Pozo           jose pozo
13     Mario Hernández     mario hernandez
14        Mario Suárez        mario suarez
15  Miguel Ángel Morro  miguel angel morro
16         Óscar Trejo         oscar trejo
17      Óscar Valentín      oscar valentin
18          Pathé Ciss          pathe ciss
19       Pep Chavarría       pep chavarria
20         Randy Nteka         randy nteka
21       Raúl de Tomás       raul de tomas
22       Salvi Sánchez       salvi sanchez
23      Santi Comesaña      santi comesana
24      Sergio Camello      sergio camello
25  Stole Dimitrievski  stole dimitrievski
26          Unai López          unai lopez

============================================================
  Real Betis  —  SF sin salario:

           player  minutesPlayed
0    Fran Delgado             11
1   Félix Garreta             90
2  Rober González             52

  CG plantilla completa:

              player       player_norm
0              Abner             abner
1       Aitor Ruibal      aitor ruibal
2        Álex Moreno       alex moreno
3    Andrés Guardado   andres guardado
4        Ayoze Pérez       ayoze perez
5     Borja Iglesias    borja iglesias
6      Claudio Bravo     claudio bravo
7        Dani Martín       dani martin
8     Edgar González    edgar gonzalez
9    Germán Pezzella   german pezzella
10   Guido Rodríguez   guido rodriguez
11           Joaquín           joaquin
12         Juan Cruz         juan cruz
13      Juan Miranda      juan miranda
14            Juanmi            juanmi
15       Loren Morón       loren moron
16       Luiz Felipe       luiz felipe
17     Luiz Henrique     luiz henrique
18    Martín Montoya    martin montoya
19       Nabil Fekir       nabil fekir
20     Paul Akouokou     paul akouokou
21             Rodri             rodri
22         Rui Silva         rui silva
23    Sergio Canales    sergio canales
24   Víctor Camarasa   victor camarasa
25       Víctor Ruiz       victor ruiz
26  William Carvalho  william carvalho
27      Willian José      willian jose
28   Youssouf Sabaly   youssouf sabaly

============================================================
  Real Madrid  —  SF sin salario:

             player  minutesPlayed
0          Casemiro             13
1    Sergio Arribas             17
2  Álvaro Rodriguez             87

  CG plantilla completa:

                 player          player_norm
0      Álvaro Odriozola     alvaro odriozola
1          Andriy Lunin         andriy lunin
2       Antonio Rüdiger      antonio rudiger
3   Aurélien Tchouameni  aurelien tchouameni
4         Dani Ceballos        dani ceballos
5       Daniel Carvajal      daniel carvajal
6           David Alaba          david alaba
7           Eden Hazard          eden hazard
8          Éder Militão         eder militao
9     Eduardo Camavinga    eduardo camavinga
10    Federico Valverde    federico valverde
11        Ferland Mendy        ferland mendy
12        Jesús Vallejo        jesus vallejo
13        Karim Benzema        karim benzema
14        Lucas Vázquez        lucas vazquez
15          Luka Modric          luka modric
16        Marco Asensio        marco asensio
17         Mariano Díaz         mariano diaz
18      Nacho Fernández      nacho fernandez
19              Rodrygo              rodrygo
20     Thibaut Courtois     thibaut courtois
21           Toni Kroos           toni kroos
22      Vinicius Junior      vinicius junior

============================================================
  Real Sociedad  —  SF sin salario:

                 player  minutesPlayed
0        Alexander Isak            154
1          Ander Martín             43
2  Jon Ander Olasagasti             63
3       Jon Karrikaburu            102
4      Jon Magunazelaia             64
5           Pablo Marín            361

  CG plantilla completa:

                player         player_norm
0          Aihen Muñoz         aihen munoz
1          Álex Remiro         alex remiro
2            Álex Sola           alex sola
3    Alexander Sörloth   alexander sorloth
4    Ander Barrenetxea   ander barrenetxea
5        Ander Guevara       ander guevara
6     Andoni Gorosabel    andoni gorosabel
7     Andoni Zubiaurre    andoni zubiaurre
8      Aritz Elustondo     aritz elustondo
9   Asier Illarramendi  asier illarramendi
10    Beñat Turrientes    benat turrientes
11        Brais Méndez        brais mendez
12    Carlos Fernández    carlos fernandez
13         David Silva         david silva
14          Diego Rico          diego rico
15       Igor Zubeldia       igor zubeldia
16         Jon Pacheco         jon pacheco
17   Martín Merquelanz   martin merquelanz
18    Martín Zubimendi    martin zubimendi
19        Mikel Merino        mikel merino
20     Mikel Oyarzabal     mikel oyarzabal
21     Mohamed-Ali Cho     mohamed ali cho
22      Robert Navarro      robert navarro
23    Robin Le Normand    robin le normand
24       Takefusa Kubo       takefusa kubo
25          Umar Sadiq          umar sadiq

============================================================
  Real Valladolid  —  SF sin salario:

                   player  minutesPlayed
0  Alvaro Aceves Catalina             12
1      Babatunde Akinsola             10
2            David Torres            381
3    Manuel Pozo Guerrero             18
4          Roberto Arroyo             14
5           Sekou Gassama             35

  CG plantilla completa:

               player        player_norm
0       Álvaro Aguado      alvaro aguado
1               Anuar              anuar
2          Cyle Larin         cyle larin
3       Darwin Machís      darwin machis
4       Gonzalo Plata      gonzalo plata
5       Iván Fresneda      ivan fresneda
6        Iván Sánchez       ivan sanchez
7        Javi Sánchez       javi sanchez
8      Jawad El Yamiq     jawad el yamiq
9   Joaquín Fernández  joaquin fernandez
10        Jordi Masip        jordi masip
11     Juanjo Narváez     juanjo narvaez
12             Kenedy             kenedy
13         Kike Pérez         kike perez
14        Lucas Olaza        lucas olaza
15         Lucas Rosa         lucas rosa
16         Luis Pérez         luis perez
17      Martin Hongla      martin hongla
18      Mickaël Malsa      mickael malsa
19             Monchu             monchu
20        Óscar Plano        oscar plano
21         Roque Mesa         roque mesa
22      Selim Amallah      selim amallah
23    Sergi Guardiola    sergi guardiola
24      Sergio Asenjo      sergio asenjo
25    Sergio Escudero    sergio escudero
26        Sergio León        sergio leon
27      Shon Weissman      shon weissman
28     Zouhair Feddal     zouhair feddal

============================================================
  Sevilla  —  SF sin salario:

           player  minutesPlayed
0  Carlos Álvarez              9
1   Diego Hormigo             45
2     Iván Romero             10
3      Kike Salas            380
4      Manu Bueno            150
5     Pedro Ortiz              1

  CG plantilla completa:

                player         player_norm
0        Adnan Januzaj       adnan januzaj
1          Alex Telles         alex telles
2                 Bono                bono
3            Bryan Gil           bryan gil
4          Erik Lamela         erik lamela
5             Fernando            fernando
6      Gonzalo Montiel     gonzalo montiel
7                 Isco                isco
8         Ivan Rakitic        ivan rakitic
9         Jesús Corona        jesus corona
10         Jesús Navas         jesus navas
11         Joan Jordán         joan jordan
12  José Ángel Carmona  jose angel carmona
13         Karim Rekik         karim rekik
14      Kasper Dolberg      kasper dolberg
15           Loïc Badé           loic bade
16       Lucas Ocampos       lucas ocampos
17              Marcão              marcao
18        Marcos Acuña        marcos acuna
19     Marko Dmitrović     marko dmitrovic
20      Nemanja Gudelj      nemanja gudelj
21       Óliver Torres       oliver torres
22          Pape Gueye          pape gueye
23          Papu Gómez          papu gomez
24            Rafa Mir            rafa mir
25                Suso                suso
26      Tanguy Nianzou      tanguy nianzou
27      Thomas Delaney      thomas delaney
28   Youssef En-Nesyri   youssef en nesyri

============================================================
  Valencia  —  SF sin salario:

              player  minutesPlayed
0       Alberto Mari             85
1       Carlos Soler            243
2        Diego López            453
3         Fran Pérez            146
4      Javier Guerra            608
5  Maximiliano Gómez            106

  CG plantilla completa:

                  player           player_norm
0          André Almeida         andre almeida
1           Cenk Özkacar          cenk ozkacar
2     Cristhian Mosquera    cristhian mosquera
3        Cristian Rivero       cristian rivero
4      Dimitri Foulquier     dimitri foulquier
5         Edinson Cavani        edinson cavani
6            Eray Cömert           eray comert
7       Gabriel Paulista      gabriel paulista
8   Giorgi Mamardashvili  giorgi mamardashvili
9              Hugo Duro             hugo duro
10        Hugo Guillamón        hugo guillamon
11         Iago Herrerín         iago herrerin
12          Ilaix Moriba          ilaix moriba
13        Jaume Doménech        jaume domenech
14         Jesús Vázquez         jesus vazquez
15             José Gayà             jose gaya
16       Justin Kluivert       justin kluivert
17          Marcos André          marcos andre
18      Mouctar Diakhaby      mouctar diakhaby
19         Nico González         nico gonzalez
20       Samu Castillejo       samu castillejo
21           Samuel Lino           samuel lino
22       Thierry Correia       thierry correia
23             Toni Lato             toni lato
24           Yunus Musah           yunus musah

============================================================
  Villarreal  —  SF sin salario:

              player  minutesPlayed
0  Alberto del Moral              9
1      Diego Collado             17
2      Fernando Niño             24
3     Haissem Hassan             50
4      Jorge Pascual             14
5     Mamadou Mbacke             29

  CG plantilla completa:

               player        player_norm
0         Aïssa Mandi        aissa mandi
1      Alberto Moreno     alberto moreno
2          Álex Baena         alex baena
3     Alfonso Pedraza    alfonso pedraza
4      Arnaut Danjuma     arnaut danjuma
5         Dani Parejo        dani parejo
6      Étienne Capoue     etienne capoue
7     Filip Jörgensen    filip jorgensen
8    Francis Coquelin   francis coquelin
9       Gerard Moreno      gerard moreno
10     Gerónimo Rulli     geronimo rulli
11   Giovani Lo Celso   giovani lo celso
12       Johan Mojica       johan mojica
13       Jorge Cuenca       jorge cuenca
14  José Luis Morales  jose luis morales
15         Juan Foyth         juan foyth
16       Kiko Femenía       kiko femenia
17      Manu Morlanes      manu morlanes
18     Manu Trigueros     manu trigueros
19    Nicolas Jackson    nicolas jackson
20         Pau Torres         pau torres
21         Pepe Reina         pepe reina
22      Ramón Terrats      ramon terrats
23        Raúl Albiol        raul albiol
24   Samuel Chukwueze   samuel chukwueze
25        Yeremi Pino        yeremi pino

In [26]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('anthony lozano', 'cadiz'): ('choco lozano', 'cadiz'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [27]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: anthony lozano (cadiz) → choco lozano (cadiz)

Tras matches manuales: 511/584 (87.5%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [28]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_spain_2223.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_spain_2223.csv
   Jugadores totales:  584
   Con salario:        511
   Sin salario (NaN):  73
   Columnas:           121