# 03 · Join Sofascore + Capology — Spain La Liga 24/25

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2024/25 de La Liga española**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [102]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [103]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [104]:
df_sf = pd.read_csv(SF_DIR / 'df_spain_2425.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_spain_2425.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  589 jugadores | 116 columnas
Capology:   551 jugadores | 9 columnas

## 4. Normalización

In [105]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [106]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   deportivo alaves
   girona fc
   real valladolid

En Capology pero no en Sofascore:
   alaves
   girona
   valladolid

### 5.2 Aplicar TEAM_MAP

In [107]:
TEAM_MAP = {
    'alaves'    : 'deportivo alaves',
    'girona'    : 'girona fc',
    'valladolid': 'real valladolid'
}

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [108]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 486/589 (82.5%)
Sin emparejar: 103

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [109]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          11
Revisión media    (0.75 ≤ score < 0.90):   12
Revisión estricta (0.50 ≤ score < 0.75):   49
Revisión muy est. (score < 0.50):           31

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [110]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

            player_sf              team           cg_match  score
6   Alexander Sørloth   Atlético Madrid  alexander sorloth  0.970
91       Rafael Bauzà          Espanyol        rafel bauza  0.957
5    Viktor Tsygankov         Girona FC   viktor tsyhankov  0.938
48   Javier Hernández           Leganés     javi hernandez  0.933
38     Manuel Sánchez  Deportivo Alavés       manu sanchez  0.923
21      Manuel Fuster        Las Palmas        manu fuster  0.917
33      Javier Guerra          Valencia        javi guerra  0.917
4       Daniel Vivian     Athletic Club        dani vivian  0.917
13        Yéremy Pino        Villarreal        yeremi pino  0.909
23       Javier Muñoz        Las Palmas         javi munoz  0.909
2           Dani Raba           Leganés        daniel raba  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [111]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf              team           cg_match  score
18        Josep Chavarría    Rayo Vallecano      pep chavarria  0.857
54           Mario Maroto   Real Valladolid       mario martin  0.833
17  Abdessamad Ezzalzouli        Real Betis    abde ezzalzouli  0.833
25      Francisco Vieites        Real Betis       fran vieites  0.828
31       Abdelkabir Abqar  Deportivo Alavés        abdel abqar  0.815
52                  Chuky   Real Valladolid              chuki  0.800
9      José María Giménez   Atlético Madrid       jose gimenez  0.800
61  Orri Steinn Óskarsson     Real Sociedad     orri oskarsson  0.800
63            Mateu Morey          Mallorca  mateu morey bauza  0.786
10         José Luis Gayà          Valencia          jose gaya  0.783
82    Abderrahman Rebbach  Deportivo Alavés       abde rebbach  0.774
49  Stanis Idumbo Muzambo           Sevilla      stanis idumbo  0.765

In [112]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [
    'mario maroto'
]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 11 | Excluidos: 1

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [113]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf             team                 cg_match  score
22       Pathé Ismaël Ciss   Rayo Vallecano               pathe ciss  0.741
39     Raúl García de Haro          Osasuna              raul garcia  0.733
26           Urko González         Espanyol  urko gonzalez de zarate  0.722
1          Alejandro Baena       Villarreal               alex baena  0.720
19          Flavien Boyomo          Osasuna              enzo boyomo  0.720
89        Arturo Rodríguez       Las Palmas         kirian rodriguez  0.688
90     José Carlo González       Las Palmas           fabio gonzalez  0.667
83             Adrián Arnu  Real Valladolid               adam aznou  0.667
0           Sergio Arribas       Real Betis           sergi altimira  0.643
53          Gonzalo García      Real Madrid              fran garcia  0.640
68            Pablo García       Real Betis            pablo fornals  0.640
57          Isra Dominguez          Sevilla              saul niguez  0.640
86     Aingeru Olabarrieta    Athletic Club  inigo ruiz de galarreta  0.619
76             Xavi Moreno  Real Valladolid             david torres  0.609
88            Dani Requena       Villarreal              dani parejo  0.609
12          Johnny Cardoso       Real Betis                   johnny  0.600
93             Raúl Chasco  Real Valladolid                raul moro  0.600
28             Ferrán Ruiz        Girona FC                abel ruiz  0.600
101           Daniel Yañez      Real Madrid          daniel carvajal  0.593
59            Iker Cordoba         Valencia          thierry correia  0.593
97             Malcom Ares    Athletic Club            aitor paredes  0.583
92           Fran González      Real Madrid              fran garcia  0.583
75         Darío Benavides          Sevilla         alvaro fernandez  0.581
16              Pablo Gavi        Barcelona                     gavi  0.571
62               Jan Salas         Mallorca             javi llabres  0.571
55              Arnau Solà       Villarreal              raul albiol  0.571
95       Leandro Antonetti          Sevilla              pedro ortiz  0.571
11          Ramón Martínez          Sevilla              pedro ortiz  0.560
43           Rodri Sánchez       Real Betis                    rodri  0.556
45            Diego Martín       Las Palmas               jaime mata  0.545
3             Yan Diomande          Leganés               yvan neyou  0.545
100     Valentin Pezzolesi       Las Palmas          alberto moleiro  0.545
58         David Arguelles           Getafe              david soria  0.538
51         Aritz Arambarri          Leganés              daniel raba  0.538
44           Nabil Aberdin           Getafe        fabrizio angileri  0.533
60            Thiago Ojeda       Villarreal              diego conde  0.522
47          Dani Rodríguez        Barcelona                dani olmo  0.522
42             Daniel Luna         Mallorca             ivan cuellar  0.522
67         Sergi Domínguez        Barcelona             fermin lopez  0.519
94            Victor Muñoz      Real Madrid          vinicius junior  0.519
40   Arkaitz Mariezkurrena    Real Sociedad          aritz elustondo  0.500
56            Iago Parente  Real Valladolid             marcos andre  0.500
64          Peter González           Getafe           peter federico  0.500
20             Nabil Fekir       Real Betis            pablo fornals  0.500
30               Fer López       Celta Vigo              iker losada  0.500
36           Sergio Vieira       Las Palmas          alberto moleiro  0.500
81           Diego Hormigo          Sevilla              pedro ortiz  0.500
99             Arnau Rafús  Real Valladolid                    anuar  0.500
65           Carlos Guirao       Real Betis              assane diao  0.500

In [114]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = [
    'pathe ismael ciss',
    'raul garcia de haro',
    'urko gonzalez',
    'alejandro baena',
    'flavien boyomo',
    'johnny cardoso',
    'pablo gavi',
    'rodri sanchez',
    'peter gonzalez'
]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 9

### 7.4 Revisión muy estricta (score < 0.50)

Candidatos con muy baja similitud. Por defecto ninguno se acepta.
Añadir a `ACCEPT_VERY_LOW_FUZZY` los que se confirmen manualmente.

In [115]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf             team              cg_match  score
34   Alvaro Garcia-Pascual          Sevilla      alvaro fernandez  0.486
87      Aboubacar Bassinga       Las Palmas           fabio silva  0.483
69        Ismael Bekhoucha           Getafe         juan berrocal  0.483
8              Iker Almena        Girona FC        yaser asprilla  0.480
37            Peio Canales    Athletic Club         aitor paredes  0.480
78            Gorka Rivera           Getafe         borja mayoral  0.480
50               Yoel Lago       Celta Vigo          joseph aidoo  0.476
71               Dani Díaz    Real Sociedad          brais mendez  0.476
98          Rodrigo Abajas         Valencia  giorgi mamardashvili  0.471
80             Nobel Mendy       Real Betis                antony  0.471
7              Angel Ortiz       Real Betis       jesus rodriguez  0.462
15           Ibrahim Alani  Real Valladolid         selim amallah  0.462
24        Abdulay Juma Bah  Real Valladolid            adam aznou  0.462
29             Adrián Niño  Atlético Madrid           samuel lino  0.455
27            Luken Beitia    Real Sociedad            luka sucic  0.455
72            David Otorbi         Valencia            dani gomez  0.455
73            Alberto Mari         Valencia            umar sadiq  0.455
70            Martín Tejón         Valencia            max aarons  0.455
66            John Patrick           Getafe            diego rico  0.455
77            Endika Buján    Athletic Club            unai nunez  0.455
85         Abdoulaye Keita           Getafe          carles alena  0.444
35              Etta Eyong       Villarreal         gerard moreno  0.435
96                Henrique  Real Valladolid                kenedy  0.429
79            Chema Andrés      Real Madrid               endrick  0.421
32              Selvi Clúa        Girona FC             abel ruiz  0.421
14            Jacobo Ramón      Real Madrid     eduardo camavinga  0.414
74            Roger Hinojo         Espanyol     roberto fernandez  0.414
102         Lorenzo Aguado      Real Madrid       antonio rudiger  0.414
41             Mateo Mejía          Sevilla        nemanja gudelj  0.400
46                 Papa Ba        Girona FC        arnaut danjuma  0.381
84    Etienne Eto'o Pineda   Rayo Vallecano     aridane hernandez  0.378

In [116]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [
    # 'player_norm'
]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [117]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 517/589 (87.8%)
Sin salario:     72

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [118]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

print(f'Total sin salario: {len(sin_salario)}')

Total sin salario: 72

In [119]:
pd.set_option('display.max_rows', None)
sin_salario

,player,team,minutesPlayed,appearances,goals,assists
0,Peio Canales,Athletic Club,259,8,0,0
1,Aingeru Olabarrieta,Athletic Club,55,1,0,0
2,Malcom Ares,Athletic Club,18,1,0,0
3,Endika Buján,Athletic Club,10,1,0,0
4,Adrián Niño,Atlético Madrid,11,1,0,0
5,Sergi Domínguez,Barcelona,173,3,0,0
6,Dani Rodríguez,Barcelona,38,1,0,0
7,Fer López,Celta Vigo,690,17,2,0
8,Yoel Lago,Celta Vigo,583,8,0,1
9,Roger Hinojo,Espanyol,8,1,0,0
10,Nabil Aberdin,Getafe,269,7,0,0
11,Abdoulaye Keita,Getafe,94,3,0,0
12,Ismael Bekhoucha,Getafe,77,5,0,0
13,John Patrick,Getafe,61,4,0,0
14,Gorka Rivera,Getafe,19,1,0,0
15,David Arguelles,Getafe,15,1,0,0
16,Selvi Clúa,Girona FC,163,4,0,0
17,Papa Ba,Girona FC,47,1,0,0
18,Iker Almena,Girona FC,46,2,0,1
19,Ferrán Ruiz,Girona FC,17,1,0,0
20,Sergio Vieira,Las Palmas,96,2,0,0
21,Diego Martín,Las Palmas,38,2,0,0
22,Arturo Rodríguez,Las Palmas,20,1,0,0
23,Valentin Pezzolesi,Las Palmas,14,1,0,0
24,Aboubacar Bassinga,Las Palmas,11,1,0,0
25,José Carlo González,Las Palmas,10,1,0,0
26,Yan Diomande,Leganés,551,10,2,1
27,Aritz Arambarri,Leganés,178,2,0,0
28,Jan Salas,Mallorca,44,4,0,0
29,Daniel Luna,Mallorca,23,2,0,0
30,Etienne Eto'o Pineda,Rayo Vallecano,44,2,0,0
31,Angel Ortiz,Real Betis,353,5,0,1
32,Nabil Fekir,Real Betis,180,2,0,1
33,Carlos Guirao,Real Betis,112,2,0,0
34,Nobel Mendy,Real Betis,107,2,0,0
35,Sergio Arribas,Real Betis,90,1,0,0
36,Pablo García,Real Betis,36,3,0,0
37,Jacobo Ramón,Real Madrid,203,3,1,0
38,Fran González,Real Madrid,90,1,0,0
39,Gonzalo García,Real Madrid,53,3,0,1
40,Victor Muñoz,Real Madrid,42,2,0,0
41,Chema Andrés,Real Madrid,13,2,0,0
42,Lorenzo Aguado,Real Madrid,4,2,0,0
43,Daniel Yañez,Real Madrid,1,1,0,0
44,Arkaitz Mariezkurrena,Real Sociedad,244,9,2,0
45,Luken Beitia,Real Sociedad,12,1,0,0
46,Dani Díaz,Real Sociedad,9,1,0,0
47,Abdulay Juma Bah,Real Valladolid,873,12,0,0
48,Henrique,Real Valladolid,354,5,0,0
49,Ibrahim Alani,Real Valladolid,159,3,0,0
50,Raúl Chasco,Real Valladolid,129,2,0,0
51,Arnau Rafús,Real Valladolid,90,1,0,0
52,Iago Parente,Real Valladolid,72,1,0,0
53,Mario Maroto,Real Valladolid,63,2,0,1
54,Adrián Arnu,Real Valladolid,53,5,0,0
55,Xavi Moreno,Real Valladolid,45,1,0,0
56,Alvaro Garcia-Pascual,Sevilla,410,8,1,0
57,Ramón Martínez,Sevilla,261,5,1,0
58,Diego Hormigo,Sevilla,38,1,0,0
59,Leandro Antonetti,Sevilla,26,2,0,0
60,Isra Dominguez,Sevilla,17,1,0,0
61,Darío Benavides,Sevilla,13,1,0,0
62,Mateo Mejía,Sevilla,10,1,0,0
63,Rodrigo Abajas,Valencia,66,1,0,0
64,Martín Tejón,Valencia,45,4,0,0
65,Iker Cordoba,Valencia,19,2,0,0
66,David Otorbi,Valencia,13,1,0,0
67,Alberto Mari,Valencia,12,1,0,0
68,Etta Eyong,Villarreal,46,4,1,0
69,Thiago Ojeda,Villarreal,13,1,0,0
70,Arnau Solà,Villarreal,12,1,0,0
71,Dani Requena,Villarreal,9,1,0,0

In [120]:
# Comparación manual por equipo: jugadores SF sin salario vs plantilla CG
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')
    
    equipo_norm  = normalize(equipo)
    cg_jugadores = df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']].sort_values('player_norm').reset_index(drop=True)
    
    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Athletic Club  —  SF sin salario:

                player  minutesPlayed
0  Aingeru Olabarrieta             55
1         Endika Buján             10
2          Malcom Ares             18
3         Peio Canales            259

  CG plantilla completa:

                     player              player_norm
0               Adama Boiro              adama boiro
1             Aitor Paredes            aitor paredes
2            Álex Berenguer           alex berenguer
3              Álex Padilla             alex padilla
4              Álvaro Djaló             alvaro djalo
5             Ander Herrera            ander herrera
6          Andoni Gorosabel         andoni gorosabel
7              Beñat Prados             benat prados
8               Dani Vivian              dani vivian
9            Gorka Guruzeta           gorka guruzeta
10           Iñaki Williams           inaki williams
11              Iñigo Lekue              inigo lekue
12  Iñigo Ruiz de Galarreta  inigo ruiz de galarreta
13            Javier Martón            javier marton
14       Julen Agirrezabala       julen agirrezabala
15           Maroan Sannadi           maroan sannadi
16         Mikel Jauregizar         mikel jauregizar
17              Mikel Vesga              mikel vesga
18             Nico Serrano             nico serrano
19            Nico Williams            nico williams
20             Oihan Sancet             oihan sancet
21          Óscar de Marcos          oscar de marcos
22               Unai Gómez               unai gomez
23               Unai Núñez               unai nunez
24               Unai Simón               unai simon
25            Yeray Álvarez            yeray alvarez
26           Yuri Berchiche           yuri berchiche

============================================================
  Atlético Madrid  —  SF sin salario:

        player  minutesPlayed
0  Adrián Niño             11

  CG plantilla completa:

               player        player_norm
0   Alexander Sörloth  alexander sorloth
1        Ángel Correa       angel correa
2   Antoine Griezmann  antoine griezmann
3         Axel Witsel        axel witsel
4        Borja Garcés       borja garces
5   César Azpilicueta  cesar azpilicueta
6     Clément Lenglet    clement lenglet
7     Conor Gallagher    conor gallagher
8    Giuliano Simeone   giuliano simeone
9           Jan Oblak          jan oblak
10         Javi Galán         javi galan
11       José Giménez       jose gimenez
12         Juan Musso         juan musso
13     Julián Alvarez     julian alvarez
14               Koke               koke
15    Marcos Llorente    marcos llorente
16      Nahuel Molina      nahuel molina
17      Pablo Barrios      pablo barrios
18   Reinildo Mandava   reinildo mandava
19   Robin Le Normand   robin le normand
20    Rodrigo De Paul    rodrigo de paul
21   Rodrigo Riquelme   rodrigo riquelme
22        Samuel Lino        samuel lino
23        Saúl Ñíguez        saul niguez
24       Thomas Lemar       thomas lemar

============================================================
  Barcelona  —  SF sin salario:

            player  minutesPlayed
0   Dani Rodríguez             38
1  Sergi Domínguez            173

  CG plantilla completa:

                   player            player_norm
0         Alejandro Balde        alejandro balde
1         Ander Astralaga        ander astralaga
2     Andreas Christensen    andreas christensen
3               Ansu Fati              ansu fati
4         Clément Lenglet        clement lenglet
5               Dani Olmo              dani olmo
6             Eric García            eric garcia
7            Fermín López           fermin lopez
8           Ferran Torres          ferran torres
9         Frenkie de Jong        frenkie de jong
10                   Gavi                   gavi
11          Gerard Martín          gerard martin
12            Héctor Fort            hector fort
13         İlkay Gündoğan         ilkay gundogan
14             Iñaki Peña             inaki pena
15         Iñigo Martínez         inigo martinez
16           Jules Koundé           jules kounde
17           Lamine Yamal           lamine yamal
18  Marc-André ter Stegen  marc andre ter stegen
19            Marc Bernal            marc bernal
20            Marc Casadó            marc casado
21            Pablo Torre            pablo torre
22            Pau Cubarsí            pau cubarsi
23             Pau Víctor             pau victor
24                  Pedri                  pedri
25               Raphinha               raphinha
26     Robert Lewandowski     robert lewandowski
27          Ronald Araujo          ronald araujo
28      Wojciech Szczesny      wojciech szczesny

============================================================
  Celta Vigo  —  SF sin salario:

      player  minutesPlayed
0  Fer López            690
1  Yoel Lago            583

  CG plantilla completa:

                 player          player_norm
0        Alfon González       alfon gonzalez
1   Anastasios Douvikas  anastasios douvikas
2        Borja Iglesias       borja iglesias
3         Carl Starfelt        carl starfelt
4      Carlos Domínguez     carlos dominguez
5      Damián Rodríguez     damian rodriguez
6          Fran Beltrán         fran beltran
7          Franco Cervi         franco cervi
8          Hugo Álvarez         hugo alvarez
9           Hugo Sotelo          hugo sotelo
10           Iago Aspas           iago aspas
11          Iker Losada          iker losada
12         Ilaix Moriba         ilaix moriba
13          Iván Villar          ivan villar
14              Jailson              jailson
15       Javi Rodríguez       javi rodriguez
16     Javier Manquillo     javier manquillo
17       Jonathan Bamba       jonathan bamba
18         Joseph Aidoo         joseph aidoo
19     Luca de la Torre     luca de la torre
20        Marcos Alonso        marcos alonso
21       Mihailo Ristic       mihailo ristic
22       Óscar Mingueza       oscar mingueza
23          Pablo Durán          pablo duran
24      Sergio Carreira      sergio carreira
25        Tadeo Allende        tadeo allende
26       Vicente Guaita       vicente guaita
27     Williot Swedberg     williot swedberg

============================================================
  Espanyol  —  SF sin salario:

         player  minutesPlayed
0  Roger Hinojo              8

  CG plantilla completa:

                     player              player_norm
0               Alejo Veliz              alejo veliz
1                 Alex Král                alex kral
2             Álvaro Aguado            alvaro aguado
3             Álvaro Tejero            alvaro tejero
4             Ángel Fortuño            angel fortuno
5              Antoniu Roca             antoniu roca
6              Brian Oliván             brian olivan
7             Carlos Romero            carlos romero
8              Edu Expósito             edu exposito
9           Fernando Calero          fernando calero
10         Fernando Pacheco         fernando pacheco
11            Irvin Cardona            irvin cardona
12               Javi Puado               javi puado
13              Joan García              joan garcia
14           Jofre Carreras           jofre carreras
15             José Gragera             jose gragera
16             Justin Smith             justin smith
17          Leandro Cabrera          leandro cabrera
18          Marash Kumbulla          marash kumbulla
19              Naci Ünüvar              naci unuvar
20           Omar El Hilali           omar el hilali
21               Omar Sadik               omar sadik
22              Pablo Ramón              pablo ramon
23               Pere Milla               pere milla
24               Pol Lozano               pol lozano
25              Rafel Bauzà              rafel bauza
26        Roberto Fernández        roberto fernandez
27            Salvi Sánchez            salvi sanchez
28              Sergi Gómez              sergi gomez
29  Urko González de Zarate  urko gonzalez de zarate
30           Walid Cheddira           walid cheddira

============================================================
  Getafe  —  SF sin salario:

             player  minutesPlayed
0   Abdoulaye Keita             94
1   David Arguelles             15
2      Gorka Rivera             19
3  Ismael Bekhoucha             77
4      John Patrick             61
5     Nabil Aberdin            269

  CG plantilla completa:

               player        player_norm
0       Alberto Risco      alberto risco
1           Álex Sola          alex sola
2          Allan Nyom         allan nyom
3    Álvaro Rodríguez   alvaro rodriguez
4     Bertuğ Yıldırım       bertug yldrm
5       Borja Mayoral      borja mayoral
6        Carles Aleñá       carles alena
7        Carles Pérez       carles perez
8    Christantus Uche   christantus uche
9       Coba da Costa      coba da costa
10        David Soria        david soria
11         Diego Rico         diego rico
12              Djené              djene
13    Domingos Duarte    domingos duarte
14  Fabrizio Angileri  fabrizio angileri
15       Jiri Letacek       jiri letacek
16        Juan Bernat        juan bernat
17      Juan Berrocal      juan berrocal
18      Juan Iglesias      juan iglesias
19             Juanmi             juanmi
20         Luis Milla         luis milla
21    Mauro Arambarri    mauro arambarri
22      Omar Alderete      omar alderete
23     Peter Federico     peter federico
24      Ramón Terrats      ramon terrats
25     Yellu Santiago     yellu santiago

============================================================
  Girona FC  —  SF sin salario:

        player  minutesPlayed
0  Ferrán Ruiz             17
1  Iker Almena             46
2      Papa Ba             47
3   Selvi Clúa            163

  CG plantilla completa:

                  player           player_norm
0              Abel Ruiz             abel ruiz
1      Alejandro Francés     alejandro frances
2         Arnau Martínez        arnau martinez
3         Arnaut Danjuma        arnaut danjuma
4                 Arthur                arthur
5          Bojan Miovski         bojan miovski
6              Bryan Gil             bryan gil
7       Cristhian Stuani      cristhian stuani
8            Daley Blind           daley blind
9            David López           david lopez
10     Donny van de Beek     donny van de beek
11      Gabriel Misehouy      gabriel misehouy
12           Iván Martín           ivan martin
13            Jhon Solís            jhon solis
14           Juan Carlos           juan carlos
15                Juanpe                juanpe
16       Ladislav Krejci       ladislav krejci
17      Miguel Gutiérrez      miguel gutierrez
18            Min-su Kim            min su kim
19           Oriol Romeu           oriol romeu
20             Pau López             pau lopez
21       Paulo Gazzaniga       paulo gazzaniga
22                 Portu                 portu
23      Viktor Tsyhankov      viktor tsyhankov
24  Vladyslav Krapyvtsov  vladyslav krapyvtsov
25        Yangel Herrera        yangel herrera
26        Yáser Asprilla        yaser asprilla

============================================================
  Las Palmas  —  SF sin salario:

                player  minutesPlayed
0   Aboubacar Bassinga             11
1     Arturo Rodríguez             20
2         Diego Martín             38
3  José Carlo González             10
4        Sergio Vieira             96
5   Valentin Pezzolesi             14

  CG plantilla completa:

              player       player_norm
0      Adnan Januzaj     adnan januzaj
1    Alberto Moleiro   alberto moleiro
2         Álex Muñoz        alex munoz
3        Alex Suárez       alex suarez
4      Álvaro Valles     alvaro valles
5       Andy Pelmard      andy pelmard
6     Benito Ramírez    benito ramirez
7   Daley Sinkgraven  daley sinkgraven
8       Dário Essugo      dario essugo
9       Dinko Horkas      dinko horkas
10     Enzo Loiodice     enzo loiodice
11    Fabio González    fabio gonzalez
12       Fábio Silva       fabio silva
13          Iván Gil          ivan gil
14        Jaime Mata        jaime mata
15  Jasper Cillessen  jasper cillessen
16        Javi Muñoz        javi munoz
17      José Campaña      jose campana
18     Juanma Herzog     juanma herzog
19  Kirian Rodríguez  kirian rodriguez
20       Manu Fuster       manu fuster
21      Marc Cardona      marc cardona
22       Marvin Park       marvin park
23       Mika Mármol       mika marmol
24   Oliver McBurnie   oliver mcburnie
25            Pejiño            pejino
26    Sandro Ramírez    sandro ramirez
27     Scott McKenna     scott mckenna
28   Stefan Bajcetic   stefan bajcetic
29       Viti Rozada       viti rozada

============================================================
  Leganés  —  SF sin salario:

            player  minutesPlayed
0  Aritz Arambarri            178
1     Yan Diomande            551

  CG plantilla completa:

                 player          player_norm
0        Adrià Altimira       adria altimira
1          Alvin Abajas         alvin abajas
2         Borna Barisic        borna barisic
3           Daniel Raba          daniel raba
4        Darko Brasanac       darko brasanac
5          Diego García         diego garcia
6                   Duk                  duk
7       Enric Franquesa      enric franquesa
8        Jackson Porozo       jackson porozo
9        Javi Hernández       javi hernandez
10          Jorge Sáenz          jorge saenz
11            Juan Cruz            juan cruz
12         Juan Soriano         juan soriano
13        Julián Chicco        julian chicco
14      Marko Dmitrovic      marko dmitrovic
15      Matija Nastasić      matija nastasic
16  Miguel de la Fuente  miguel de la fuente
17     Munir El Haddadi     munir el haddadi
18          Naim García          naim garcia
19      Óscar Rodríguez      oscar rodriguez
20         Renato Tapia         renato tapia
21        Roberto López        roberto lopez
22     Sébastien Haller     sebastien haller
23      Sergio González      sergio gonzalez
24       Seydouba Cissé       seydouba cisse
25      Valentin Rosier      valentin rosier
26           Yvan Neyou           yvan neyou

============================================================
  Mallorca  —  SF sin salario:

        player  minutesPlayed
0  Daniel Luna             23
1    Jan Salas             44

  CG plantilla completa:

                  player           player_norm
0            Abdón Prats           abdon prats
1         Antonio Raíllo        antonio raillo
2        Antonio Sánchez       antonio sanchez
3              Chiquinho             chiquinho
4             Cyle Larin            cyle larin
5         Dani Rodríguez        dani rodriguez
6            David López           david lopez
7          Dominik Greif         dominik greif
8           Iván Cuéllar          ivan cuellar
9           Javi Llabrés          javi llabres
10          Johan Mojica          johan mojica
11           José Copete           jose copete
12             Leo Román             leo roman
13         Manu Morlanes         manu morlanes
14         Marc Domènech         marc domenech
15        Martin Valjent        martin valjent
16     Mateu Morey Bauzà     mateu morey bauza
17        Omar Mascarell        omar mascarell
18          Pablo Maffeo          pablo maffeo
19        Robert Navarro        robert navarro
20            Samú Costa            samu costa
21          Sergi Darder          sergi darder
22  Siebe Van der Heyden  siebe van der heyden
23          Takuma Asano          takuma asano
24             Toni Lato             toni lato
25      Valery Fernández      valery fernandez
26          Vedat Muriqi          vedat muriqi

============================================================
  Rayo Vallecano  —  SF sin salario:

                 player  minutesPlayed
0  Etienne Eto'o Pineda             44

  CG plantilla completa:

               player        player_norm
0         Abdul Mumin        abdul mumin
1      Adrián Embarba     adrian embarba
2      Alfonso Espino     alfonso espino
3       Álvaro García      alvaro garcia
4        Andrei Rațiu       andrei ratiu
5   Aridane Hernández  aridane hernandez
6     Augusto Batalla    augusto batalla
7       Dani Cárdenas      dani cardenas
8     Florian Lejeune    florian lejeune
9       Gerard Gumbau      gerard gumbau
10        Isi Palazón        isi palazon
11        Iván Balliu        ivan balliu
12    James Rodríguez    james rodriguez
13       Joni Montiel       joni montiel
14    Jorge de Frutos    jorge de frutos
15        Oscar Trejo        oscar trejo
16     Óscar Valentín     oscar valentin
17         Pathé Ciss         pathe ciss
18         Pedro Díaz         pedro diaz
19   Pelayo Fernández   pelayo fernandez
20      Pep Chavarría      pep chavarria
21        Randy Nteka        randy nteka
22      Raúl de Tomás      raul de tomas
23    Sergi Guardiola    sergi guardiola
24     Sergio Camello     sergio camello
25         Unai López         unai lopez

============================================================
  Real Betis  —  SF sin salario:

           player  minutesPlayed
0     Angel Ortiz            353
1   Carlos Guirao            112
2     Nabil Fekir            180
3     Nobel Mendy            107
4    Pablo García             36
5  Sergio Arribas             90

  CG plantilla completa:

               player        player_norm
0     Abde Ezzalzouli    abde ezzalzouli
1              Adrián             adrian
2        Aitor Ruibal       aitor ruibal
3              Antony             antony
4         Assane Diao        assane diao
5      Cédric Bakambu     cedric bakambu
6         Chimy Ávila        chimy avila
7     Cucho Hernández    cucho hernandez
8      Diego Llorente     diego llorente
9        Fran Vieites       fran vieites
10   Giovani Lo Celso   giovani lo celso
11    Héctor Bellerín    hector bellerin
12        Iker Losada        iker losada
13               Isco               isco
14    Jesús Rodriguez    jesus rodriguez
15             Johnny             johnny
16             Juanmi             juanmi
17        Marc Bartra        marc bartra
18          Marc Roca          marc roca
19       Mateo Flores       mateo flores
20              Natan              natan
21      Pablo Fornals      pablo fornals
22  Ricardo Rodríguez  ricardo rodriguez
23              Rodri              rodri
24     Romain Perraud     romain perraud
25          Rui Silva          rui silva
26     Sergi Altimira     sergi altimira
27        Vitor Roque        vitor roque
28   William Carvalho   william carvalho
29    Youssouf Sabaly    youssouf sabaly

============================================================
  Real Madrid  —  SF sin salario:

           player  minutesPlayed
0    Chema Andrés             13
1    Daniel Yañez              1
2   Fran González             90
3  Gonzalo García             53
4    Jacobo Ramón            203
5  Lorenzo Aguado              4
6    Victor Muñoz             42

  CG plantilla completa:

                 player          player_norm
0          Andriy Lunin         andriy lunin
1       Antonio Rüdiger      antonio rudiger
2            Arda Güler           arda guler
3   Aurélien Tchouaméni  aurelien tchouameni
4           Brahim Díaz          brahim diaz
5         Dani Ceballos        dani ceballos
6       Daniel Carvajal      daniel carvajal
7           David Alaba          david alaba
8          Éder Militão         eder militao
9     Eduardo Camavinga    eduardo camavinga
10              Endrick              endrick
11    Federico Valverde    federico valverde
12        Ferland Mendy        ferland mendy
13          Fran García          fran garcia
14        Jesús Vallejo        jesus vallejo
15      Jude Bellingham      jude bellingham
16        Kylian Mbappé        kylian mbappe
17        Lucas Vázquez        lucas vazquez
18          Luka Modric          luka modric
19         Raúl Asencio         raul asencio
20              Rodrygo              rodrygo
21     Thibaut Courtois     thibaut courtois
22      Vinicius Junior      vinicius junior

============================================================
  Real Sociedad  —  SF sin salario:

                  player  minutesPlayed
0  Arkaitz Mariezkurrena            244
1              Dani Díaz              9
2           Luken Beitia             12

  CG plantilla completa:

                     player              player_norm
0               Aihen Muñoz              aihen munoz
1               Álex Remiro              alex remiro
2          Álvaro Odriozola         alvaro odriozola
3         Ander Barrenetxea        ander barrenetxea
4           Aritz Elustondo          aritz elustondo
5           Arsen Zakharyan          arsen zakharyan
6          Beñat Turrientes         benat turrientes
7              Brais Méndez             brais mendez
8             Hamari Traoré            hamari traore
9             Igor Zubeldia            igor zubeldia
10               Javi López               javi lopez
11     Jon Ander Olasagasti     jon ander olasagasti
12             Jon Aramburu             jon aramburu
13         Jon Magunazelaia         jon magunazelaia
14               Jon Martín               jon martin
15              Jon Pacheco              jon pacheco
16               Luka Sucic               luka sucic
17         Martín Zubimendi         martin zubimendi
18          Mikel Oyarzabal          mikel oyarzabal
19             Nayef Aguerd             nayef aguerd
20           Orri Óskarsson           orri oskarsson
21              Pablo Marín              pablo marin
22             Sergio Gómez             sergio gomez
23          Sheraldo Becker          sheraldo becker
24            Takefusa Kubo            takefusa kubo
25               Umar Sadiq               umar sadiq
26             Unai Marrero             unai marrero
27  Urko González de Zarate  urko gonzalez de zarate

============================================================
  Real Valladolid  —  SF sin salario:

             player  minutesPlayed
0  Abdulay Juma Bah            873
1       Adrián Arnu             53
2       Arnau Rafús             90
3          Henrique            354
4      Iago Parente             72
5     Ibrahim Alani            159
6      Mario Maroto             63
7       Raúl Chasco            129
8       Xavi Moreno             45

  CG plantilla completa:

                player         player_norm
0           Adam Aznou          adam aznou
1        Álvaro Aceves       alvaro aceves
2         Amath Ndiaye        amath ndiaye
3       André Ferreira      andre ferreira
4      Antonio Candela     antonio candela
5                Anuar               anuar
6         Cenk Özkacar        cenk ozkacar
7      César de la Hoz     cesar de la hoz
8                Chuki               chuki
9        Darwin Machís       darwin machis
10        David Torres        david torres
11         Eray Cömert         eray comert
12  Florian Grillitsch  florian grillitsch
13        Iván Sánchez        ivan sanchez
14        Javi Sánchez        javi sanchez
15        Joseph Aidoo        joseph aidoo
16       Juanmi Latasa       juanmi latasa
17           Karl Hein           karl hein
18              Kenedy              kenedy
19          Kike Pérez          kike perez
20          Lucas Rosa          lucas rosa
21          Luis Pérez          luis perez
22       Mamadou Sylla       mamadou sylla
23        Marcos André        marcos andre
24        Mario Martín        mario martin
25           Raúl Moro           raul moro
26       Selim Amallah       selim amallah
27        Stanko Juric        stanko juric
28    Tamás Nikitscher    tamas nikitscher
29     Víctor Meseguer     victor meseguer

============================================================
  Sevilla  —  SF sin salario:

                  player  minutesPlayed
0  Alvaro Garcia-Pascual            410
1        Darío Benavides             13
2          Diego Hormigo             38
3         Isra Dominguez             17
4      Leandro Antonetti             26
5            Mateo Mejía             10
6         Ramón Martínez            261

  CG plantilla completa:

                  player           player_norm
0          Adnan Januzaj         adnan januzaj
1          Adrià Pedrosa         adria pedrosa
2             Akor Adams            akor adams
3   Albert Sambi Lokonga  albert sambi lokonga
4       Álvaro Fernández      alvaro fernandez
5          Chidera Ejuke         chidera ejuke
6            Djibril Sow           djibril sow
7         Dodi Lukébakio        dodi lukebakio
8        Gonzalo Montiel       gonzalo montiel
9           Isaac Romero          isaac romero
10           Jesús Navas           jesus navas
11    José Ángel Carmona    jose angel carmona
12        Juanlu Sánchez        juanlu sanchez
13     Kelechi Iheanacho     kelechi iheanacho
14            Kike Salas            kike salas
15             Loïc Badé             loic bade
16         Lucas Ocampos         lucas ocampos
17         Lucien Agoume         lucien agoume
18            Manu Bueno            manu bueno
19                Marcão                marcao
20        Nemanja Gudelj        nemanja gudelj
21           Pedro Ortiz           pedro ortiz
22       Peque Fernández       peque fernandez
23          Ørjan Nyland           rjan nyland
24          Rubén Vargas          ruben vargas
25           Saúl Ñíguez           saul niguez
26         Stanis Idumbo         stanis idumbo
27                  Suso                  suso
28        Tanguy Nianzou        tanguy nianzou
29        Valentín Barco        valentin barco

============================================================
  Valencia  —  SF sin salario:

           player  minutesPlayed
0    Alberto Mari             12
1    David Otorbi             13
2    Iker Cordoba             19
3    Martín Tejón             45
4  Rodrigo Abajas             66

  CG plantilla completa:

                  player           player_norm
0          André Almeida         andre almeida
1          César Tárrega         cesar tarrega
2     Cristhian Mosquera    cristhian mosquera
3             Dani Gómez            dani gomez
4            Diego López           diego lopez
5      Dimitri Foulquier     dimitri foulquier
6       Enzo Barrenechea      enzo barrenechea
7             Fran Pérez            fran perez
8          Germán Valera         german valera
9   Giorgi Mamardashvili  giorgi mamardashvili
10             Hugo Duro             hugo duro
11        Hugo Guillamón        hugo guillamon
12            Iván Jaime            ivan jaime
13        Jaume Doménech        jaume domenech
14           Javi Guerra           javi guerra
15         Jesús Vázquez         jesus vazquez
16             José Gayà             jose gaya
17            Luis Rioja            luis rioja
18            Max Aarons            max aarons
19  Maximiliano Caufriez  maximiliano caufriez
20      Mouctar Diakhaby      mouctar diakhaby
21                Pepelu                pepelu
22              Rafa Mir              rafa mir
23           Sergi Canós           sergi canos
24    Stole Dimitrievski    stole dimitrievski
25       Thierry Correia       thierry correia
26            Umar Sadiq            umar sadiq
27     Yarek Gasiorowski     yarek gasiorowski

============================================================
  Villarreal  —  SF sin salario:

         player  minutesPlayed
0    Arnau Solà             12
1  Dani Requena              9
2    Etta Eyong             46
3  Thiago Ojeda             13

  CG plantilla completa:

             player      player_norm
0        Álex Baena       alex baena
1   Alfonso Pedraza  alfonso pedraza
2       Ayoze Pérez      ayoze perez
3       Dani Parejo      dani parejo
4      Denis Suárez     denis suarez
5       Diego Conde      diego conde
6       Eric Bailly      eric bailly
7     Gerard Moreno    gerard moreno
8      Iker Álvarez     iker alvarez
9    Ilias Akhomach   ilias akhomach
10      Juan Bernat      juan bernat
11       Juan Foyth       juan foyth
12     Kiko Femenía     kiko femenia
13      Logan Costa      logan costa
14      Luiz Júnior      luiz junior
15     Nicolas Pépé     nicolas pepe
16       Pape Gueye       pape gueye
17      Pau Navarro      pau navarro
18    Ramón Terrats    ramon terrats
19      Raúl Albiol      raul albiol
20   Santi Comesaña   santi comesana
21    Sergi Cardona    sergi cardona
22   Tajon Buchanan   tajon buchanan
23    Thierno Barry    thierno barry
24   Willy Kambwala   willy kambwala
25      Yeremi Pino      yeremi pino

In [121]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [122]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_spain_2425.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_spain_2425.csv
   Jugadores totales:  589
   Con salario:        517
   Sin salario (NaN):  72
   Columnas:           121