# 03 · Join Sofascore + Capology — Spain La Liga 23/24

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2023/24 de La Liga española**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [116]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [117]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [118]:
df_sf = pd.read_csv(SF_DIR / 'df_spain_2324.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_spain_2324.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  598 jugadores | 116 columnas
Capology:   556 jugadores | 9 columnas

## 4. Normalización

In [119]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [120]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   deportivo alaves
   girona fc

En Capology pero no en Sofascore:
   alaves
   girona

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [121]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'alaves':'deportivo alaves',
            'girona':'girona fc'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [122]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 489/598 (81.8%)
Sin emparejar: 109

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [123]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          8
Revisión media    (0.75 ≤ score < 0.90):   13
Revisión estricta (0.50 ≤ score < 0.75):   57
Revisión muy est. (score < 0.50):           31

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [124]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

            player_sf           team           cg_match  score
4   Alexander Sørloth     Villarreal  alexander sorloth  0.970
3    Viktor Tsygankov      Girona FC   viktor tsyhankov  0.938
39   Javier Hernández          Cádiz     javi hernandez  0.933
33     Manuel Sánchez     Celta Vigo       manu sanchez  0.923
14      Daniel Vivian  Athletic Club        dani vivian  0.917
46      Javier Guerra       Valencia        javi guerra  0.917
35       Javier Muñoz     Las Palmas         javi munoz  0.909
12        Yéremy Pino     Villarreal        yeremi pino  0.909

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [125]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf              team          cg_match  score
38        Josep Chavarría    Rayo Vallecano     pep chavarria  0.857
56  Abdessamad Ezzalzouli        Real Betis   abde ezzalzouli  0.833
1                 Savinho         Girona FC             savio  0.833
78      Ben Brereton Díaz        Villarreal      ben brereton  0.828
24       Abdelkabir Abqar  Deportivo Alavés       abdel abqar  0.815
23     José María Giménez   Atlético Madrid      jose gimenez  0.800
72         Iñaki González        Las Palmas    fabio gonzalez  0.786
15         José Luis Gayà          Valencia         jose gaya  0.783
29          Mamadou Mbaye             Cádiz        momo mbaye  0.783
54    Abderrahman Rebbach  Deportivo Alavés      abde rebbach  0.774
11     Luis Javier Suárez           Almería       luis suarez  0.759
25     Sergio Ruiz Alonso           Granada       sergio ruiz  0.759
16       Damián Rodríguez        Celta Vigo  miguel rodriguez  0.750

In [126]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['inaki gonzalez','damian rodriguez'
]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 11 | Excluidos: 2

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [127]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf              team                 cg_match  score
57     Maximiliano Gómez             Cádiz               maxi gomez  0.741
20     Pathé Ismaël Ciss    Rayo Vallecano               pathe ciss  0.741
44   Raúl García de Haro           Osasuna              raul garcia  0.733
79         Urko González     Real Sociedad  urko gonzalez de zarate  0.722
51         Jorge Pascual        Villarreal             jorge cuenca  0.720
36         Jastin García         Girona FC             aleix garcia  0.720
2        Alejandro Baena        Villarreal               alex baena  0.720
70          Alberto Soro           Granada            alberto perea  0.720
52          Jesús Corona           Sevilla              jesus navas  0.696
40       Hannibal Mejbri           Sevilla                 hannibal  0.696
98          Jorge Moreno           Osasuna           jorge herrando  0.692
60        Anthony Lozano           Almería             choco lozano  0.692
21           Marc Casadó         Barcelona            marcos alonso  0.667
65            Jon Martin     Real Sociedad              pablo marin  0.667
63         Hugo González          Valencia           pablo gozalbez  0.667
91      Mikel Jauregizar     Athletic Club              mikel vesga  0.667
13           Luiz Felipe        Real Betis            luiz henrique  0.667
55        Peter González          Valencia           pablo gozalbez  0.643
68        Gonzalo García       Real Madrid              fran garcia  0.640
47        Sergio Rodelas           Granada              sergio ruiz  0.640
58           Malcom Ares     Athletic Club                 adu ares  0.632
102    Miguel Ángel Brau           Granada             miguel rubio  0.621
85   Aingeru Olabarrieta     Athletic Club  inigo ruiz de galarreta  0.619
43         Alberto Risco            Getafe               diego rico  0.609
10        Johnny Cardoso        Real Betis                   johnny  0.600
64        Radamel Falcao    Rayo Vallecano                   falcao  0.600
18           Pablo Busto        Real Betis            pablo fornals  0.583
17           Srđan Babić           Almería           adrian embarba  0.583
100          Unai Ropero  Deportivo Alavés               javi lopez  0.571
9             Pablo Gavi         Barcelona                     gavi  0.571
81          Javier Rueda        Celta Vigo         javier manquillo  0.571
61          José Campaña        Las Palmas            sergi cardona  0.560
104          Adrià Bosch           Granada           ricard sanchez  0.560
48         Diego Hormigo           Sevilla             sergio ramos  0.560
34      Jon Magunazelaia     Real Sociedad     jon ander olasagasti  0.556
41         Rodri Sánchez        Real Betis                    rodri  0.556
32          Diego Mendez    Rayo Vallecano        aridane hernandez  0.552
49          Mario Martín       Real Madrid        eduardo camavinga  0.552
75          Jordi Martín            Getafe               jaime mata  0.545
22           Marcos Peña           Almería              marc pubill  0.545
5          Juanma Herzog        Las Palmas            julian araujo  0.538
80       Salim El Jebari   Atlético Madrid              samuel lino  0.538
108       Moussa Diakité             Cádiz             youba diarra  0.538
101        Nabil Aberdin            Getafe        fabrizio angileri  0.533
53        Abner Vinícius        Real Betis                    abner  0.526
97         Alberto Dadie     Real Sociedad               umar sadiq  0.522
99          Santi García            Getafe              david soria  0.522
27           Pablo Sáenz           Granada             bruno mendez  0.522
8           Hugo Álvarez        Celta Vigo              hugo sotelo  0.522
93         Yassin Tallal            Getafe           gaston alvarez  0.519
107     Álvaro Rodriguez       Real Madrid              luka modric  0.519
7         Jonathan Viera           Almería           adrian embarba  0.500
42            Manu Bueno           Sevilla           tanguy nianzou  0.500
96          Tomás Mendes  Deportivo Alavés         carlos benavidez  0.500
69         César Tárrega          Valencia          thierry correia  0.500
92          Abde Raihani   Atlético Madrid         gabriel paulista  0.500
45           Hector Fort         Barcelona            sergi roberto  0.500

In [128]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['maximiliano gomez',
                    'pathe ismael ciss',
                    'raul garcia de haro',
                    'urko gonzalez',
                    'alejandro baena',
                    'hannibal mejbri',
                    'anthony lozano',
                    'johnny cardoso',
                    'radamel falcao',
                    'pablo gavi',
                    'rodri sanchez',
                    'abner vinicius'
]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 12

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [129]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                     player_sf              team              cg_match  score
30   Sokratis Papastathopoulos        Real Betis              sokratis  0.485
37             Mario Domínguez          Valencia        jaume domenech  0.483
74               Victor Parada  Deportivo Alavés          nikola maras  0.480
103                Gabri Veiga        Celta Vigo        oscar mingueza  0.480
73                Gorka Rivera            Getafe         borja mayoral  0.480
66                   Yoel Lago        Celta Vigo          joseph aidoo  0.476
71                  Selvi Clúa         Girona FC           eric garcia  0.476
84                   Paco Sanz           Almería          choco lozano  0.476
76               Mamadou Sylla  Deportivo Alavés     aleksandar sedlar  0.467
88               Salvi Sánchez    Rayo Vallecano     aridane hernandez  0.467
67              Asier Osambela           Osasuna      alejandro catena  0.467
50               Rachad Fettal           Almería         ibrahima kone  0.462
28               Ricardo Visus        Real Betis         claudio bravo  0.462
89             Iñigo Arguibide           Osasuna           unai garcia  0.462
90       Marciano Sanca Tchami           Almería        adrian embarba  0.457
77         Miguel de la Fuente  Deportivo Alavés      giuliano simeone  0.457
26                Rubén Iranzo          Valencia            fran perez  0.455
94                 Xabi Huarte           Osasuna           unai garcia  0.455
6            Francisco Vieites        Real Betis        borja iglesias  0.452
82                Jeremy Jorge            Getafe       oscar rodriguez  0.444
106              Borja Vázquez             Cádiz        javi hernandez  0.444
59                Jon Aramburu     Real Sociedad  jon ander olasagasti  0.438
83                 Eneko Ortiz  Deportivo Alavés          ruben duarte  0.435
31             Milutin Osmajić             Cádiz         darwin machis  0.429
62          Joaquin Panichelli  Deportivo Alavés            ianis hagi  0.429
0          Antal Yaakobishvili         Girona FC            toni villa  0.414
19               Paul Akouokou        Real Betis          alex collado  0.400
86                  Etta Eyong             Cádiz            ivan alejo  0.400
87              Stefan Leković        Villarreal           dani parejo  0.400
95                        Bono           Sevilla           joan jordan  0.400
105               Max Svensson           Osasuna       aitor fernandez  0.370

In [130]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = ['sokratis papastathopoulos']
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 1

### 7.5 Aplicar todos los fuzzy matches aceptados

In [131]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 521/598 (87.1%)
Sin salario:     77

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [132]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 77

,player,team,minutesPlayed,appearances,goals,assists
0,Jonathan Viera,Almería,1542,21,2,4
1,Marcos Peña,Almería,439,7,0,0
2,Srđan Babić,Almería,90,1,0,0
3,Marciano Sanca Tchami,Almería,67,6,0,0
4,Paco Sanz,Almería,23,1,0,0
5,Rachad Fettal,Almería,16,1,0,0
6,Malcom Ares,Athletic Club,272,12,0,0
7,Mikel Jauregizar,Athletic Club,158,7,0,0
8,Aingeru Olabarrieta,Athletic Club,8,1,0,0
9,Salim El Jebari,Atlético Madrid,12,1,0,0
10,Abde Raihani,Atlético Madrid,9,1,0,0
11,Hector Fort,Barcelona,330,7,0,2
12,Marc Casadó,Barcelona,18,2,0,0
13,Hugo Álvarez,Celta Vigo,781,12,1,1
14,Damián Rodríguez,Celta Vigo,257,5,0,2
15,Yoel Lago,Celta Vigo,90,1,0,0
16,Javier Rueda,Celta Vigo,19,1,0,0
17,Gabri Veiga,Celta Vigo,17,1,0,0
18,Etta Eyong,Cádiz,20,1,0,0
19,Milutin Osmajić,Cádiz,13,1,0,0
20,Borja Vázquez,Cádiz,3,1,0,0
21,Moussa Diakité,Cádiz,1,1,0,0
22,Joaquin Panichelli,Deportivo Alavés,236,8,0,0
23,Miguel de la Fuente,Deportivo Alavés,85,3,0,0
24,Mamadou Sylla,Deportivo Alavés,26,2,0,0
25,Unai Ropero,Deportivo Alavés,14,1,0,0
26,Eneko Ortiz,Deportivo Alavés,13,1,0,0
27,Tomás Mendes,Deportivo Alavés,12,1,0,0
28,Victor Parada,Deportivo Alavés,9,2,0,0
29,Jordi Martín,Getafe,574,13,0,0
30,Nabil Aberdin,Getafe,180,2,0,0
31,Alberto Risco,Getafe,135,4,0,0
32,Santi García,Getafe,24,1,0,0
33,Gorka Rivera,Getafe,11,1,0,0
34,Jeremy Jorge,Getafe,10,1,0,0
35,Yassin Tallal,Getafe,8,1,0,0
36,Antal Yaakobishvili,Girona FC,60,1,0,0
37,Jastin García,Girona FC,31,3,0,0
38,Selvi Clúa,Girona FC,8,1,0,0
39,Sergio Rodelas,Granada,122,3,0,1
40,Miguel Ángel Brau,Granada,30,1,0,0
41,Adrià Bosch,Granada,25,1,0,0
42,Pablo Sáenz,Granada,18,1,0,0
43,Alberto Soro,Granada,17,1,0,0
44,Juanma Herzog,Las Palmas,291,4,2,0
45,José Campaña,Las Palmas,173,8,0,0
46,Iñaki González,Las Palmas,9,1,0,0
47,Iñigo Arguibide,Osasuna,16,1,0,0
48,Jorge Moreno,Osasuna,13,1,0,0
49,Asier Osambela,Osasuna,9,1,0,0
50,Xabi Huarte,Osasuna,8,1,0,0
51,Max Svensson,Osasuna,2,1,0,0
52,Salvi Sánchez,Rayo Vallecano,27,1,0,0
53,Diego Mendez,Rayo Vallecano,9,1,0,0
54,Luiz Felipe,Real Betis,360,4,0,0
55,Francisco Vieites,Real Betis,315,4,0,0
56,Ricardo Visus,Real Betis,165,3,0,0
57,Pablo Busto,Real Betis,52,2,0,0
58,Paul Akouokou,Real Betis,26,2,0,0
59,Gonzalo García,Real Madrid,21,2,0,0
60,Mario Martín,Real Madrid,16,2,0,0
61,Álvaro Rodriguez,Real Madrid,1,1,0,0
62,Jon Aramburu,Real Sociedad,541,11,0,0
63,Jon Magunazelaia,Real Sociedad,131,5,0,0
64,Alberto Dadie,Real Sociedad,27,1,0,0
65,Jon Martin,Real Sociedad,23,1,0,0
66,Manu Bueno,Sevilla,120,4,0,0
67,Bono,Sevilla,90,1,0,0
68,Diego Hormigo,Sevilla,36,1,0,0
69,Jesús Corona,Sevilla,16,2,0,0
70,Peter González,Valencia,646,15,0,0
71,Hugo González,Valencia,89,9,0,1
72,Mario Domínguez,Valencia,23,3,0,0
73,César Tárrega,Valencia,13,1,0,0
74,Rubén Iranzo,Valencia,10,1,0,0
75,Stefan Leković,Villarreal,28,1,0,0
76,Jorge Pascual,Villarreal,13,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [133]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Almería  —  SF sin salario:

                  player  minutesPlayed
0         Jonathan Viera           1542
1  Marciano Sanca Tchami             67
2            Marcos Peña            439
3              Paco Sanz             23
4          Rachad Fettal             16
5            Srđan Babić             90

  CG plantilla completa:

                    player             player_norm
0           Adrián Embarba          adrian embarba
1           Alejandro Pozo          alejandro pozo
2   Aleksandar Radovanović  aleksandar radovanovic
3           Álex Centelles          alex centelles
4            Arnau Puigmal           arnau puigmal
5              Bruno Langa             bruno langa
6             César Montes            cesar montes
7             Choco Lozano            choco lozano
8                    Chumi                   chumi
9             Diego Mariño            diego marino
10               Dion Lopy               dion lopy
11          Edgar González          edgar gonzalez
12       Fernando Martínez       fernando martinez
13          Gonzalo Melero          gonzalo melero
14       Houboulang Mendes       houboulang mendes
15           Ibrahima Koné           ibrahima kone
16            Iddrisu Baba            iddrisu baba
17                   Kaiky                   kaiky
18         Largie Ramazani         largie ramazani
19                  Lázaro                  lazaro
20           Léo Baptistão           leo baptistao
21         Lucas Robertone         lucas robertone
22          Luís Maximiano          luis maximiano
23             Luis Suárez             luis suarez
24             Luka Romero             luka romero
25             Marc Pubill             marc pubill
26       Marko Milovanovic       marko milovanovic
27           Sergio Akieme           sergio akieme
28          Sergio Arribas          sergio arribas

============================================================
  Athletic Club  —  SF sin salario:

                player  minutesPlayed
0  Aingeru Olabarrieta              8
1          Malcom Ares            272
2     Mikel Jauregizar            158

  CG plantilla completa:

                      player               player_norm
0                   Adu Ares                  adu ares
1              Aitor Paredes             aitor paredes
2             Álex Berenguer            alex berenguer
3              Ander Herrera             ander herrera
4           Asier Villalibre          asier villalibre
5               Beñat Prados              benat prados
6                Dani García               dani garcia
7                Dani Vivian               dani vivian
8             Gorka Guruzeta            gorka guruzeta
9               Iker Muniain              iker muniain
10  Imanol García de Albéniz  imanol garcia de albeniz
11            Iñaki Williams            inaki williams
12               Iñigo Lekue               inigo lekue
13   Iñigo Ruiz de Galarreta   inigo ruiz de galarreta
14        Julen Agirrezabala        julen agirrezabala
15               Mikel Vesga               mikel vesga
16             Nico Williams             nico williams
17              Oihan Sancet              oihan sancet
18           Óscar de Marcos           oscar de marcos
19           Peru Nolaskoain           peru nolaskoain
20               Raúl García               raul garcia
21                Unai Gómez                unai gomez
22                Unai Simón                unai simon
23             Yeray Álvarez             yeray alvarez
24            Yuri Berchiche            yuri berchiche

============================================================
  Atlético Madrid  —  SF sin salario:

            player  minutesPlayed
0     Abde Raihani              9
1  Salim El Jebari             12

  CG plantilla completa:

               player        player_norm
0       Álvaro Morata      alvaro morata
1        Ángel Correa       angel correa
2   Antoine Griezmann  antoine griezmann
3    Arthur Vermeeren   arthur vermeeren
4         Axel Witsel        axel witsel
5      Çağlar Söyüncü     caglar soyuncu
6   César Azpilicueta  cesar azpilicueta
7    Gabriel Paulista   gabriel paulista
8    Horaţiu Moldovan   horatiu moldovan
9           Ivo Grbic          ivo grbic
10          Jan Oblak          jan oblak
11         Javi Galán         javi galan
12         João Félix         joao felix
13       José Giménez       jose gimenez
14               Koke               koke
15    Marcos Llorente    marcos llorente
16       Marcos Paulo       marcos paulo
17      Mario Hermoso      mario hermoso
18      Memphis Depay      memphis depay
19      Nahuel Molina      nahuel molina
20      Pablo Barrios      pablo barrios
21   Reinildo Mandava   reinildo mandava
22    Rodrigo de Paul    rodrigo de paul
23   Rodrigo Riquelme   rodrigo riquelme
24        Samuel Lino        samuel lino
25        Saúl Ñíguez        saul niguez
26       Stefan Savic       stefan savic
27       Thomas Lemar       thomas lemar
28             Vitolo             vitolo
29   Yannick Carrasco   yannick carrasco

============================================================
  Barcelona  —  SF sin salario:

        player  minutesPlayed
0  Hector Fort            330
1  Marc Casadó             18

  CG plantilla completa:

                   player            player_norm
0         Alejandro Balde        alejandro balde
1         Ander Astralaga        ander astralaga
2     Andreas Christensen    andreas christensen
3               Ansu Fati              ansu fati
4         Clément Lenglet        clement lenglet
5            Fermín López           fermin lopez
6           Ferran Torres          ferran torres
7         Frenkie de Jong        frenkie de jong
8                    Gavi                   gavi
9          İlkay Gündoğan         ilkay gundogan
10             Iñaki Peña             inaki pena
11         Iñigo Martínez         inigo martinez
12           João Cancelo           joao cancelo
13             João Félix             joao felix
14           Jules Koundé           jules kounde
15          Julián Araujo          julian araujo
16           Lamine Yamal           lamine yamal
17  Marc-André ter Stegen  marc andre ter stegen
18              Marc Guiu              marc guiu
19          Marcos Alonso          marcos alonso
20            Oriol Romeu            oriol romeu
21            Pablo Torre            pablo torre
22            Pau Cubarsí            pau cubarsi
23                  Pedri                  pedri
24               Raphinha               raphinha
25     Robert Lewandowski     robert lewandowski
26          Ronald Araujo          ronald araujo
27          Sergi Roberto          sergi roberto
28           Sergiño Dest           sergino dest
29            Vitor Roque            vitor roque

============================================================
  Celta Vigo  —  SF sin salario:

             player  minutesPlayed
0  Damián Rodríguez            257
1       Gabri Veiga             17
2      Hugo Álvarez            781
3      Javier Rueda             19
4         Yoel Lago             90

  CG plantilla completa:

                  player          player_norm
0      Agustín Marchesín    agustin marchesin
1    Anastasios Douvikas  anastasios douvikas
2          Carl Starfelt        carl starfelt
3           Carles Pérez         carles perez
4       Carlos Domínguez     carlos dominguez
5           Carlos Dotor         carlos dotor
6           Fran Beltrán         fran beltran
7           Franco Cervi         franco cervi
8            Hugo Sotelo          hugo sotelo
9             Iago Aspas           iago aspas
10           Iván Villar          ivan villar
11               Jailson              jailson
12      Javier Manquillo     javier manquillo
13        Jonathan Bamba       jonathan bamba
14          Joseph Aidoo         joseph aidoo
15  Jørgen Strand Larsen  jrgen strand larsen
16         Kevin Vázquez        kevin vazquez
17      Luca de la Torre     luca de la torre
18          Manu Sánchez         manu sanchez
19      Miguel Rodríguez     miguel rodriguez
20        Mihailo Ristic       mihailo ristic
21        Óscar Mingueza       oscar mingueza
22          Renato Tapia         renato tapia
23         Tadeo Allende        tadeo allende
24            Unai Núñez           unai nunez
25        Vicente Guaita       vicente guaita
26      Williot Swedberg     williot swedberg

============================================================
  Cádiz  —  SF sin salario:

            player  minutesPlayed
0    Borja Vázquez              3
1       Etta Eyong             20
2  Milutin Osmajić             13
3   Moussa Diakité              1

  CG plantilla completa:

               player        player_norm
0         Aiham Ousou        aiham ousou
1      Álex Fernández     alex fernandez
2      Álvaro Negredo     alvaro negredo
3        Brian Ocampo       brian ocampo
4         Chris Ramos        chris ramos
5       Darwin Machís      darwin machis
6           David Gil          david gil
7   Diadié Samassékou  diadie samassekou
8                Fali               fali
9   Fede San Emeterio  fede san emeterio
10  Gonzalo Escalante  gonzalo escalante
11         Iván Alejo         ivan alejo
12       Iza Carcelén       iza carcelen
13     Javi Hernández     javi hernandez
14   Jeremías Ledesma   jeremias ledesma
15         Jorge Meré         jorge mere
16          José Mari          jose mari
17      Joseba Zaldua      joseba zaldua
18          Juan Cala          juan cala
19             Juanmi             juanmi
20        Lucas Pires        lucas pires
21     Luis Hernández     luis hernandez
22    Martín Calderón    martin calderon
23         Maxi Gómez         maxi gomez
24         Momo Mbaye         momo mbaye
25     Robert Navarro     robert navarro
26        Roger Martí        roger marti
27   Rominigue Kouamé   rominigue kouame
28      Rubén Alcaraz      ruben alcaraz
29      Rubén Sobrino      ruben sobrino
30    Sergi Guardiola    sergi guardiola
31       Víctor Chust       victor chust
32       Youba Diarra       youba diarra

============================================================
  Deportivo Alavés  —  SF sin salario:

                player  minutesPlayed
0          Eneko Ortiz             13
1   Joaquin Panichelli            236
2        Mamadou Sylla             26
3  Miguel de la Fuente             85
4         Tomás Mendes             12
5          Unai Ropero             14
6        Victor Parada              9

  CG plantilla completa:

               player        player_norm
0   Abdallahi Mahmoud  abdallahi mahmoud
1        Abde Rebbach       abde rebbach
2         Abdel Abqar        abdel abqar
3   Aleksandar Sedlar  aleksandar sedlar
4           Álex Sola          alex sola
5       Ander Guevara      ander guevara
6    Andoni Gorosabel   andoni gorosabel
7      Antonio Blanco     antonio blanco
8      Antonio Sivera     antonio sivera
9    Carlos Benavidez   carlos benavidez
10     Carlos Vicente     carlos vicente
11   Giuliano Simeone   giuliano simeone
12         Ianis Hagi         ianis hagi
13         Javi López         javi lopez
14        Jesús Owono        jesus owono
15         Jon Guridi         jon guridi
16    Jon Karrikaburu    jon karrikaburu
17        Kike García        kike garcia
18         Luis Rioja         luis rioja
19    Nahuel Tenaglia    nahuel tenaglia
20       Nikola Maras       nikola maras
21         Rafa Marín         rafa marin
22       Rubén Duarte       ruben duarte
23      Samu Aghehowa      samu aghehowa
24       Xeber Alkain       xeber alkain

============================================================
  Getafe  —  SF sin salario:

          player  minutesPlayed
0  Alberto Risco            135
1   Gorka Rivera             11
2   Jeremy Jorge             10
3   Jordi Martín            574
4  Nabil Aberdin            180
5   Santi García             24
6  Yassin Tallal              8

  CG plantilla completa:

                player         player_norm
0        Borja Mayoral       borja mayoral
1         Carles Aleñá        carles alena
2         Choco Lozano        choco lozano
3        Damián Suárez       damian suarez
4        Daniel Fuzato       daniel fuzato
5          David Soria         david soria
6           Diego Rico          diego rico
7                Djené               djene
8      Domingos Duarte     domingos duarte
9            Enes Ünal           enes unal
10   Fabrizio Angileri   fabrizio angileri
11      Gastón Álvarez      gaston alvarez
12        Ilaix Moriba        ilaix moriba
13          Jaime Mata          jaime mata
14  José Ángel Carmona  jose angel carmona
15       Juan Iglesias       juan iglesias
16       Juanmi Latasa       juanmi latasa
17          Luis Milla          luis milla
18     Mason Greenwood     mason greenwood
19     Mauro Arambarri     mauro arambarri
20  Nemanja Maksimovic  nemanja maksimovic
21       Omar Alderete       omar alderete
22     Óscar Rodríguez     oscar rodriguez
23     Stefan Mitrovic     stefan mitrovic
24      Yellu Santiago      yellu santiago

============================================================
  Girona FC  —  SF sin salario:

                player  minutesPlayed
0  Antal Yaakobishvili             60
1        Jastin García             31
2           Selvi Clúa              8

  CG plantilla completa:

               player        player_norm
0        Aleix García       aleix garcia
1   Alexander Callens  alexander callens
2      Arnau Martínez     arnau martinez
3        Artem Dovbyk       artem dovbyk
4   Bernardo Espinosa  bernardo espinosa
5        Borja García       borja garcia
6    Cristhian Stuani   cristhian stuani
7         Daley Blind        daley blind
8         David López        david lopez
9         Eric García        eric garcia
10     Eric Monjonell     eric monjonell
11      Ibrahima Kébé      ibrahima kebe
12        Iván Martín        ivan martin
13         Jhon Solís         jhon solis
14        Juan Carlos        juan carlos
15             Juanpe             juanpe
16   Miguel Gutiérrez   miguel gutierrez
17        Pablo Torre        pablo torre
18    Paulo Gazzaniga    paulo gazzaniga
19              Portu              portu
20              Sávio              savio
21       Toni Fuidias       toni fuidias
22         Toni Villa         toni villa
23   Valery Fernández   valery fernandez
24   Viktor Tsyhankov   viktor tsyhankov
25          Yan Couto          yan couto
26     Yangel Herrera     yangel herrera

============================================================
  Granada  —  SF sin salario:

              player  minutesPlayed
0        Adrià Bosch             25
1       Alberto Soro             17
2  Miguel Ángel Brau             30
3        Pablo Sáenz             18
4     Sergio Rodelas            122

  CG plantilla completa:

               player        player_norm
0       Alberto Perea      alberto perea
1     Álvaro Carreras    alvaro carreras
2      André Ferreira     andre ferreira
3     Antonio Puertas    antonio puertas
4     Augusto Batalla    augusto batalla
5        Bruno Méndez       bruno mendez
6      Bryan Zaragoza     bryan zaragoza
7         Carlos Neva        carlos neva
8   Facundo Pellistri  facundo pellistri
9    Faitout Maouassa   faitout maouassa
10    Famara Diédhiou    famara diedhiou
11      Gerard Gumbau      gerard gumbau
12     Gonzalo Villar     gonzalo villar
13      Ignasi Miquel      ignasi miquel
14      Jesús Vallejo      jesus vallejo
15      José Callejón      jose callejon
16      Kamil Jóźwiak      kamil jozwiak
17   Kamil Piatkowski   kamil piatkowski
18         Lucas Boyé         lucas boye
19      Marc Martínez      marc martinez
20      Martin Hongla      martin hongla
21       Matías Arezo       matias arezo
22       Miguel Rubio       miguel rubio
23        Myrto Uzuni        myrto uzuni
24    Njegos Petrovic    njegos petrovic
25      Óscar Melendo      oscar melendo
26     Raúl Fernández     raul fernandez
27      Raúl Torrente      raul torrente
28     Ricard Sánchez     ricard sanchez
29        Sergio Ruiz        sergio ruiz
30      Shon Weissman      shon weissman
31      Theo Corbeanu      theo corbeanu
32        Víctor Díaz        victor diaz
33      Wilson Manafá      wilson manafa

============================================================
  Las Palmas  —  SF sin salario:

           player  minutesPlayed
0  Iñaki González              9
1    José Campaña            173
2   Juanma Herzog            291

  CG plantilla completa:

              player       player_norm
0    Aarón Escandell   aaron escandell
1    Alberto Moleiro   alberto moleiro
2        Alex Suárez       alex suarez
3       Álvaro Lemos      alvaro lemos
4      Álvaro Valles     alvaro valles
5     Benito Ramírez    benito ramirez
6   Cristian Herrera  cristian herrera
7   Daley Sinkgraven  daley sinkgraven
8      Enzo Loiodice     enzo loiodice
9       Eric Curbelo      eric curbelo
10    Fabio González    fabio gonzalez
11        Javi Muñoz        javi munoz
12    Jonathan Viera    jonathan viera
13     Julián Araujo     julian araujo
14  Kirian Rodríguez  kirian rodriguez
15      Marc Cardona      marc cardona
16       Marvin Park       marvin park
17    Máximo Perrone    maximo perrone
18       Mika Mármol       mika marmol
19  Munir El Haddadi  munir el haddadi
20     Omenuke Mfulu     omenuke mfulu
21            Pejiño            pejino
22    Sandro Ramírez    sandro ramirez
23         Saúl Coco         saul coco
24     Sergi Cardona     sergi cardona
25         Sory Kaba         sory kaba

============================================================
  Osasuna  —  SF sin salario:

            player  minutesPlayed
0   Asier Osambela              9
1  Iñigo Arguibide             16
2     Jorge Moreno             13
3     Max Svensson              2
4      Xabi Huarte              8

  CG plantilla completa:

                player         player_norm
0           Aimar Oroz          aimar oroz
1      Aitor Fernández     aitor fernandez
2     Alejandro Catena    alejandro catena
3         Ante Budimir        ante budimir
4          Chimy Ávila         chimy avila
5       Darko Brasanac      darko brasanac
6         David García        david garcia
7           Iker Muñoz          iker munoz
8          Jesús Areso         jesus areso
9         Johan Mojica        johan mojica
10       Jon Moncayola       jon moncayola
11      Jorge Herrando      jorge herrando
12  José Manuel Arnáiz  jose manuel arnaiz
13           Juan Cruz           juan cruz
14          Kike Barja          kike barja
15         Lucas Torró         lucas torro
16           Moi Gómez           moi gomez
17         Nacho Vidal         nacho vidal
18        Pablo Ibáñez        pablo ibanez
19         Raúl García         raul garcia
20        Rubén García        ruben garcia
21          Rubén Peña          ruben pena
22      Sergio Herrera      sergio herrera
23         Unai García         unai garcia

============================================================
  Rayo Vallecano  —  SF sin salario:

          player  minutesPlayed
0   Diego Mendez              9
1  Salvi Sánchez             27

  CG plantilla completa:

                player         player_norm
0          Abdul Mumin         abdul mumin
1       Alfonso Espino      alfonso espino
2        Álvaro García       alvaro garcia
3         Andrei Rațiu        andrei ratiu
4    Aridane Hernández   aridane hernandez
5                 Bebé                bebe
6        Dani Cárdenas       dani cardenas
7               Falcao              falcao
8      Florian Lejeune     florian lejeune
9          Isi Palazón         isi palazon
10         Iván Balliu         ivan balliu
11     Jorge de Frutos     jorge de frutos
12           José Pozo           jose pozo
13          Kike Pérez          kike perez
14      Martín Pascual      martin pascual
15       Miguel Crespo       miguel crespo
16         Óscar Trejo         oscar trejo
17      Óscar Valentín      oscar valentin
18          Pathé Ciss          pathe ciss
19       Pep Chavarría       pep chavarria
20         Randy Nteka         randy nteka
21       Raúl de Tomás       raul de tomas
22      Sergio Camello      sergio camello
23  Stole Dimitrievski  stole dimitrievski
24          Unai López          unai lopez

============================================================
  Real Betis  —  SF sin salario:

              player  minutesPlayed
0  Francisco Vieites            315
1        Luiz Felipe            360
2        Pablo Busto             52
3      Paul Akouokou             26
4      Ricardo Visus            165

  CG plantilla completa:

              player       player_norm
0    Abde Ezzalzouli   abde ezzalzouli
1              Abner             abner
2       Aitor Ruibal      aitor ruibal
3       Álex Collado      alex collado
4    Andrés Guardado   andres guardado
5        Assane Diao       assane diao
6        Ayoze Pérez       ayoze perez
7     Borja Iglesias    borja iglesias
8     Cédric Bakambu    cedric bakambu
9         Chadi Riad        chadi riad
10       Chimy Ávila       chimy avila
11     Claudio Bravo     claudio bravo
12   Germán Pezzella   german pezzella
13   Guido Rodríguez   guido rodriguez
14   Héctor Bellerín   hector bellerin
15              Isco              isco
16            Johnny            johnny
17         Juan Cruz         juan cruz
18      Juan Miranda      juan miranda
19     Luiz Henrique     luiz henrique
20       Marc Bartra       marc bartra
21         Marc Roca         marc roca
22       Nabil Fekir       nabil fekir
23     Pablo Fornals     pablo fornals
24             Rodri             rodri
25         Rui Silva         rui silva
26    Sergi Altimira    sergi altimira
27          Sokratis          sokratis
28  William Carvalho  william carvalho
29      Willian José      willian jose
30   Youssouf Sabaly   youssouf sabaly

============================================================
  Real Madrid  —  SF sin salario:

             player  minutesPlayed
0    Gonzalo García             21
1      Mario Martín             16
2  Álvaro Rodriguez              1

  CG plantilla completa:

                 player          player_norm
0          Andriy Lunin         andriy lunin
1       Antonio Rüdiger      antonio rudiger
2            Arda Güler           arda guler
3   Aurélien Tchouaméni  aurelien tchouameni
4           Brahim Díaz          brahim diaz
5         Dani Ceballos        dani ceballos
6       Daniel Carvajal      daniel carvajal
7           David Alaba          david alaba
8          Éder Militão         eder militao
9     Eduardo Camavinga    eduardo camavinga
10    Federico Valverde    federico valverde
11        Ferland Mendy        ferland mendy
12          Fran García          fran garcia
13               Joselu               joselu
14      Jude Bellingham      jude bellingham
15    Kepa Arrizabalaga    kepa arrizabalaga
16        Lucas Vázquez        lucas vazquez
17          Luka Modric          luka modric
18      Nacho Fernández      nacho fernandez
19             Nico Paz             nico paz
20              Rodrygo              rodrygo
21     Thibaut Courtois     thibaut courtois
22           Toni Kroos           toni kroos
23      Vinicius Junior      vinicius junior

============================================================
  Real Sociedad  —  SF sin salario:

             player  minutesPlayed
0     Alberto Dadie             27
1      Jon Aramburu            541
2  Jon Magunazelaia            131
3        Jon Martin             23

  CG plantilla completa:

                     player              player_norm
0               Aihen Muñoz              aihen munoz
1               Álex Remiro              alex remiro
2          Álvaro Odriozola         alvaro odriozola
3         Ander Barrenetxea        ander barrenetxea
4               André Silva              andre silva
5           Aritz Elustondo          aritz elustondo
6           Arsen Zakharyan          arsen zakharyan
7          Beñat Turrientes         benat turrientes
8              Brais Méndez             brais mendez
9          Carlos Fernández         carlos fernandez
10            Hamari Traoré            hamari traore
11            Igor Zubeldia            igor zubeldia
12               Javi Galán               javi galan
13     Jon Ander Olasagasti     jon ander olasagasti
14              Jon Pacheco              jon pacheco
15           Kieran Tierney           kieran tierney
16        Martín Merquelanz        martin merquelanz
17         Martín Zubimendi         martin zubimendi
18             Mikel Merino             mikel merino
19          Mikel Oyarzabal          mikel oyarzabal
20          Mohamed-Ali Cho          mohamed ali cho
21              Pablo Marín              pablo marin
22         Robin Le Normand         robin le normand
23          Sheraldo Becker          sheraldo becker
24            Takefusa Kubo            takefusa kubo
25               Umar Sadiq               umar sadiq
26             Unai Marrero             unai marrero
27  Urko González de Zarate  urko gonzalez de zarate

============================================================
  Sevilla  —  SF sin salario:

          player  minutesPlayed
0           Bono             90
1  Diego Hormigo             36
2   Jesús Corona             16
3     Manu Bueno            120

  CG plantilla completa:

               player        player_norm
0       Adnan Januzaj      adnan januzaj
1       Adrià Pedrosa      adria pedrosa
2         Alejo Véliz        alejo veliz
3   Boubakary Soumaré  boubakary soumare
4         Djibril Sow        djibril sow
5      Dodi Lukébakio     dodi lukebakio
6         Erik Lamela        erik lamela
7    Federico Gattoni   federico gattoni
8            Fernando           fernando
9            Hannibal           hannibal
10       Isaac Romero       isaac romero
11       Ivan Rakitic       ivan rakitic
12        Jesús Navas        jesus navas
13        Joan Jordán        joan jordan
14     Juanlu Sánchez     juanlu sanchez
15         Kike Salas         kike salas
16          Loïc Badé          loic bade
17      Lucas Ocampos      lucas ocampos
18      Lucien Agoume      lucien agoume
19             Marcão             marcao
20       Marcos Acuña       marcos acuna
21       Mariano Díaz       mariano diaz
22    Marko Dmitrović    marko dmitrovic
23     Nemanja Gudelj     nemanja gudelj
24      Óliver Torres      oliver torres
25           Rafa Mir           rafa mir
26       Ørjan Nyland        rjan nyland
27       Sergio Ramos       sergio ramos
28               Suso               suso
29     Tanguy Nianzou     tanguy nianzou
30  Youssef En-Nesyri  youssef en nesyri

============================================================
  Valencia  —  SF sin salario:

            player  minutesPlayed
0    César Tárrega             13
1    Hugo González             89
2  Mario Domínguez             23
3   Peter González            646
4     Rubén Iranzo             10

  CG plantilla completa:

                  player           player_norm
0           Alberto Marí          alberto mari
1          André Almeida         andre almeida
2           Cenk Özkacar          cenk ozkacar
3     Cristhian Mosquera    cristhian mosquera
4        Cristian Rivero       cristian rivero
5            Diego López           diego lopez
6      Dimitri Foulquier     dimitri foulquier
7             Fran Pérez            fran perez
8       Gabriel Paulista      gabriel paulista
9   Giorgi Mamardashvili  giorgi mamardashvili
10             Hugo Duro             hugo duro
11        Hugo Guillamón        hugo guillamon
12        Jaume Doménech        jaume domenech
13           Javi Guerra           javi guerra
14         Jesús Vázquez         jesus vazquez
15             José Gayà             jose gaya
16      Mouctar Diakhaby      mouctar diakhaby
17        Pablo Gozálbez        pablo gozalbez
18                Pepelu                pepelu
19        Peter Federico        peter federico
20       Roman Yaremchuk       roman yaremchuk
21       Samu Castillejo       samu castillejo
22         Selim Amallah         selim amallah
23           Sergi Canós           sergi canos
24       Thierry Correia       thierry correia
25     Yarek Gasiorowski     yarek gasiorowski

============================================================
  Villarreal  —  SF sin salario:

           player  minutesPlayed
0   Jorge Pascual             13
1  Stefan Leković             28

  CG plantilla completa:

               player        player_norm
0      Adrià Altimira     adria altimira
1         Aïssa Mandi        aissa mandi
2      Alberto Moreno     alberto moreno
3          Álex Baena         alex baena
4   Alexander Sörloth  alexander sorloth
5     Alfonso Pedraza    alfonso pedraza
6      Arnaut Danjuma     arnaut danjuma
7        Ben Brereton       ben brereton
8     Bertrand Traoré    bertrand traore
9       Carlos Romero      carlos romero
10        Dani Parejo        dani parejo
11       Denis Suárez       denis suarez
12        Eric Bailly        eric bailly
13     Étienne Capoue     etienne capoue
14    Filip Jørgensen     filip jrgensen
15   Francis Coquelin   francis coquelin
16      Gerard Moreno      gerard moreno
17     Gonçalo Guedes     goncalo guedes
18     Ilias Akhomach     ilias akhomach
19       Jorge Cuenca       jorge cuenca
20  José Luis Morales  jose luis morales
21         Juan Foyth         juan foyth
22       Kiko Femenía       kiko femenia
23     Manu Trigueros     manu trigueros
24      Matteo Gabbia      matteo gabbia
25         Pepe Reina         pepe reina
26      Ramón Terrats      ramon terrats
27        Raúl Albiol        raul albiol
28     Santi Comesaña     santi comesana
29        Yeremi Pino        yeremi pino
30    Yerson Mosquera    yerson mosquera

In [134]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('jonathan viera', 'almeria') : ('jonathan viera', 'las palmas'),
    ('peter gonzalez', 'valencia'): ('peter federico', 'valencia'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 2

In [135]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: jonathan viera (almeria) → jonathan viera (las palmas)
✅ Match manual aplicado: peter gonzalez (valencia) → peter federico (valencia)

Tras matches manuales: 523/598 (87.5%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [136]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_spain_2324.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_spain_2324.csv
   Jugadores totales:  598
   Con salario:        523
   Sin salario (NaN):  75
   Columnas:           121