# 03 · Join Sofascore + Capology — Spain La Liga 25/26 (snapshot 20260428)

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2025/26 de la La Liga española**.

⚠️ **Nota sobre el snapshot:** la temporada 25/26 está aún en curso. Se trabaja con
una foto fija de Sofascore (`df_spain_2526_snapshot_20260428.csv`). Este notebook
deberá reejecutarse con los datos definitivos cuando finalice la liga, generando
entonces el master sin sufijo de fecha (`master_spain_2526.csv`).

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_spain_2526_snapshot_20260428.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_spain_2526.csv').copy()

print(f'Sofascore (snapshot):  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:              {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore (snapshot):  578 jugadores | 117 columnas
Capology:              525 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   deportivo alaves
   fc barcelona
   girona fc
   levante ud

En Capology pero no en Sofascore:
   alaves
   barcelona
   girona
   levante

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'alaves':'deportivo alaves',
            'barcelona':'fc barcelona',
            'girona':'girona fc',
            'levante':'levante ud'

}

# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 463/578 (80.1%)
Sin emparejar: 115

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          8
Revisión media    (0.75 ≤ score < 0.90):   12
Revisión estricta (0.50 ≤ score < 0.75):   52
Revisión muy est. (score < 0.50):           43

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

            player_sf             team           cg_match  score
23     Yáser Asprilla        Girona FC     yaser asprilla  1.000
14  Alexander Sørloth  Atlético Madrid  alexander sorloth  0.970
8    Viktor Tsygankov        Girona FC   viktor tsyhankov  0.938
20      Dani Carvajal      Real Madrid    daniel carvajal  0.929
60     Manuel Sánchez       Levante UD       manu sanchez  0.923
32      Javier Guerra         Valencia        javi guerra  0.917
18       Javier Rueda       Celta Vigo         javi rueda  0.909
55          Dani Raba         Valencia        daniel raba  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf              team           cg_match  score
78               Tai Abed        Levante UD           tay abed  0.875
15        Josep Chavarría    Rayo Vallecano      pep chavarria  0.857
33    Alejandro Rego Mora     Athletic Club     alejandro rego  0.848
81    Justin-Noel Kalumba          Mallorca     justin kalumba  0.848
1   Abdessamad Ezzalzouli        Real Betis    abde ezzalzouli  0.833
19      Alexander Freeman        Villarreal       alex freeman  0.828
72       Damián Rodríguez        Celta Vigo     javi rodriguez  0.800
36             Etta Eyong        Levante UD    karl etta eyong  0.800
10     Jose Maria Gimenez   Atlético Madrid       jose gimenez  0.800
17  Orri Steinn Óskarsson     Real Sociedad     orri oskarsson  0.800
61            Mateu Morey          Mallorca  mateu morey bauza  0.786
24    Abderrahman Rebbach  Deportivo Alavés       abde rebbach  0.774

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────

EXCLUDE_FROM_FUZZY = ['damian rodriguez'

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 11 | Excluidos: 1

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf              team                 cg_match  score
7        Pathé Ismaël Ciss    Rayo Vallecano               pathe ciss  0.741
22     Raúl García de Haro           Osasuna              raul garcia  0.733
80             Juan Arango         Girona FC              juan carlos  0.727
37           Urko González          Espanyol  urko gonzalez de zarate  0.722
66           Hugo González        Celta Vigo             hugo alvarez  0.720
0              Pablo Cuñat        Levante UD             pablo campos  0.696
90         Jofre Torrents       FC Barcelona            ferran torres  0.667
45               Álex Sola            Getafe             alex sancris  0.667
9           Carlos Vicente  Deportivo Alavés         carlos benavidez  0.667
34           A. J. Morales        Levante UD        jose luis morales  0.643
77                   Abdon          Mallorca              abdon prats  0.625
106      Carlos Ballestero  Deportivo Alavés             carles alena  0.621
83              Yvan Neyou            Getafe               allan nyom  0.600
12          Johnny Cardoso   Atlético Madrid                   johnny  0.600
5             Daniel Yañez       Real Madrid          daniel carvajal  0.593
62              Julio Díaz   Atlético Madrid           julian alvarez  0.583
68            Ibai Aguirre     Real Sociedad             unai marrero  0.583
69           Marco Esteban       Real Oviedo          aaron escandell  0.571
110        Ladislav Krejčí         Girona FC     vladyslav krapyvtsov  0.571
13              Pablo Gavi      FC Barcelona                     gavi  0.571
35        Calebe Gonçalves  Deportivo Alavés             carles alena  0.571
109             Mikel Goti     Real Sociedad          mikel oyarzabal  0.560
74          Dani Rodriguez          Mallorca              david lopez  0.560
42           Djene Dakonam            Getafe                    djene  0.556
107          Rayane Belaid   Atlético Madrid                jan oblak  0.545
30             Hugo Burcio        Celta Vigo              hugo sotelo  0.545
71             Nacho Pérez        Levante UD              paco cortes  0.545
79                  Alemão    Rayo Vallecano         alexandre alemao  0.545
25            Javier Boñar   Atlético Madrid               alex baena  0.545
51          César Palacios       Real Madrid             raul asencio  0.538
67          Ivan Corralejo        Real Betis         giovani lo celso  0.533
87           Dani Martinez   Atlético Madrid        antoine griezmann  0.533
114      Lander Astiazaran     Real Sociedad        ander barrenetxea  0.529
26       Víctor Valdepeñas       Real Madrid        federico valverde  0.529
112             Dani Pérez        Real Betis                pau lopez  0.526
44            Alex Sanchez             Elche              aleix febas  0.522
105         Andrés Antañón        Celta Vigo            marcos alonso  0.519
73         José Luis Pérez            Getafe             luis vazquez  0.519
46         Jairo Izquierdo             Elche         alejandro iturbe  0.516
53         Jano Monserrate   Atlético Madrid         giuliano simeone  0.516
85           Bojan Miovski         Girona FC              juan carlos  0.500
98          Ramón Martínez           Sevilla           juanlu sanchez  0.500
84          Toni Fernández      FC Barcelona               inaki pena  0.500
111  Arkaitz Mariezkurrena     Real Sociedad          aritz elustondo  0.500
99           Javi Morcillo   Atlético Madrid              marc pubill  0.500
65   Gorka Carrera Zarranz     Real Sociedad          arsen zakharyan  0.500
57          Dro Fernández      FC Barcelona          alejandro balde  0.500
88           Sergio Lozano        Levante UD              iker losada  0.500
47           Borja Sánchez       Real Oviedo          rahim alhassane  0.500
41             Abdel Rahim       Real Oviedo            alberto reina  0.500
31           David Jiménez       Real Madrid              david alaba  0.500
93            Asier Hierro     Athletic Club             nico serrano  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['pathe ismael ciss',
                    'raul garcia de haro',
                    'urko gonzalez',
                    'pablo cunat',
                    'a j morales',
                    'abdon',
                    'johnny cardoso',
                    'pablo gavi',
                    'djene dakonam',
                    'alemao'
                    

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 10

### 7.4 Revisión muy estricta (score < 0.50)

Candidatos con muy baja similitud. Por defecto ninguno se acepta.
Añadir a `ACCEPT_VERY_LOW_FUZZY` los que se confirmen manualmente.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf              team                cg_match  score
52      Manuel Ángel Morán       Real Madrid     aurelien tchouameni  0.486
16           Manor Solomon        Villarreal        santiago mourino  0.483
96           Jorge Cabello        Levante UD            roger brugue  0.480
91           Moussa Diarra  Deportivo Alavés            mariano diaz  0.480
54           Marc Domenech          Mallorca            mateo joseph  0.480
97            Pablo Agudín       Real Oviedo           alberto reina  0.480
6           Adrià Altimira        Villarreal             arnau tenas  0.480
29            Rubén Iranzo          Valencia           lucas beltran  0.480
27             Job Ochieng     Real Sociedad              jon martin  0.476
48             Xavi Espart      FC Barcelona              inaki pena  0.476
76              Jhon Solís         Girona FC             juan carlos  0.476
86               Dani Díaz     Real Sociedad            brais mendez  0.476
102             Hugo Lopez        Villarreal             ayoze perez  0.476
104             Ali Houary             Elche             aleix febas  0.476
89            Jorge Montes            Getafe                   djene  0.471
103   Thiago Pitarch Pinar       Real Madrid          gonzalo garcia  0.471
58      Alejandro Mestanza            Getafe            alex sancris  0.467
75       Giacomo Raspadori   Atlético Madrid           thiago almada  0.467
92            Dawda Camara         Girona FC          arnau martinez  0.462
63           Tomás Marqués      FC Barcelona           ronald araujo  0.462
59           Renzo Saravia          Valencia           cesar tarrega  0.462
94        Pelayo Fernández    Rayo Vallecano              pedro diaz  0.462
40           Miguel Sierra           Sevilla           gabriel suazo  0.462
101           Luken Beitia     Real Sociedad              luka sucic  0.455
39         Conor Gallagher   Atlético Madrid        nicolas gonzalez  0.452
43          Salomón Rondón       Real Oviedo       brandon domingues  0.452
11          Bryan Zaragoza        Celta Vigo           ferran jutgla  0.444
64            Diego Aguado       Real Madrid         daniel carvajal  0.444
82             Eder Garcia     Athletic Club        mikel jauregizar  0.444
21                   Pacha    Rayo Vallecano           pep chavarria  0.444
2         Christantus Uche            Getafe        ismael bekhoucha  0.438
4              Yéremy Pino        Villarreal            alex freeman  0.435
28              Omar Falah       Real Oviedo           santi cazorla  0.435
50           Josip Brekalo       Real Oviedo              javi lopez  0.435
113        Lander Pinillos  Deportivo Alavés           ander guevara  0.429
38     Mourad El Ghezouani             Elche          grady diangana  0.424
56       Goduine Koyalipou        Levante UD            diego pampin  0.414
70          Hugo Solozábal            Getafe         mauro arambarri  0.414
3           Dodi Lukebakio           Sevilla    odysseas vlachodimos  0.412
49           Jorge Cestero       Real Madrid  trent alexander arnold  0.400
95   Stanis Idumbo Muzambo           Sevilla          tanguy nianzou  0.400
108         Diego Morcillo  Deportivo Alavés             ville koski  0.400
100           Taufik Seidu   Atlético Madrid        giuliano simeone  0.357

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 491/578 (84.9%)
Sin salario:     87

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 87

,player,team,minutesPlayed,appearances,goals,assists
0,Eder Garcia,Athletic Club,36,2,0,0
1,Asier Hierro,Athletic Club,33,1,0,0
2,Conor Gallagher,Atlético Madrid,665,19,2,0
3,Giacomo Raspadori,Atlético Madrid,250,12,0,1
4,Julio Díaz,Atlético Madrid,221,3,0,1
5,Javier Boñar,Atlético Madrid,180,2,1,0
6,Dani Martinez,Atlético Madrid,90,1,0,0
7,Rayane Belaid,Atlético Madrid,71,1,0,0
8,Javi Morcillo,Atlético Madrid,48,2,0,0
9,Jano Monserrate,Atlético Madrid,28,2,0,0
10,Taufik Seidu,Atlético Madrid,22,1,0,0
11,Bryan Zaragoza,Celta Vigo,1135,19,1,1
12,Damián Rodríguez,Celta Vigo,151,2,0,0
13,Andrés Antañón,Celta Vigo,62,2,0,0
14,Hugo Burcio,Celta Vigo,12,1,0,0
15,Hugo González,Celta Vigo,12,1,0,0
16,Carlos Vicente,Deportivo Alavés,1256,21,5,0
17,Calebe Gonçalves,Deportivo Alavés,764,19,0,0
18,Moussa Diarra,Deportivo Alavés,219,3,0,0
19,Carlos Ballestero,Deportivo Alavés,9,1,0,0
20,Diego Morcillo,Deportivo Alavés,9,1,0,0
21,Lander Pinillos,Deportivo Alavés,1,1,0,0
22,Ali Houary,Elche,125,2,0,0
23,Mourad El Ghezouani,Elche,50,2,0,0
24,Jairo Izquierdo,Elche,25,1,0,0
25,Alex Sanchez,Elche,14,1,0,1
26,Xavi Espart,FC Barcelona,91,2,0,0
27,Dro Fernández,FC Barcelona,90,4,0,0
28,Jofre Torrents,FC Barcelona,47,3,0,0
29,Toni Fernández,FC Barcelona,45,1,0,0
30,Tomás Marqués,FC Barcelona,9,1,0,0
31,Christantus Uche,Getafe,270,3,1,1
32,Alejandro Mestanza,Getafe,79,3,0,0
33,Yvan Neyou,Getafe,73,5,0,0
34,Jorge Montes,Getafe,26,1,0,0
35,José Luis Pérez,Getafe,20,2,0,0
36,Álex Sola,Getafe,12,1,0,0
37,Hugo Solozábal,Getafe,10,1,0,0
38,Yáser Asprilla,Girona FC,605,15,0,0
39,Jhon Solís,Girona FC,384,12,0,0
40,Ladislav Krejčí,Girona FC,180,2,0,0
41,Dawda Camara,Girona FC,71,2,0,0
42,Bojan Miovski,Girona FC,44,1,0,0
43,Juan Arango,Girona FC,19,2,0,0
44,Jorge Cabello,Levante UD,364,5,0,0
45,Goduine Koyalipou,Levante UD,239,11,1,0
46,Nacho Pérez,Levante UD,80,2,0,0
47,Sergio Lozano,Levante UD,11,1,0,0
48,Marc Domenech,Mallorca,217,7,0,1
49,Dani Rodriguez,Mallorca,67,2,0,0
50,Pacha,Rayo Vallecano,1214,25,2,0
51,Pelayo Fernández,Rayo Vallecano,45,1,0,0
52,Ivan Corralejo,Real Betis,14,1,0,0
53,Dani Pérez,Real Betis,1,1,0,0
54,Thiago Pitarch Pinar,Real Madrid,363,6,0,0
55,Manuel Ángel Morán,Real Madrid,95,4,0,0
56,Víctor Valdepeñas,Real Madrid,78,1,0,0
57,David Jiménez,Real Madrid,77,2,0,0
58,César Palacios,Real Madrid,51,2,0,0
59,Daniel Yañez,Real Madrid,32,1,0,1
60,Diego Aguado,Real Madrid,29,1,0,0
61,Jorge Cestero,Real Madrid,12,2,0,0
62,Abdel Rahim,Real Oviedo,1526,24,0,0
63,Salomón Rondón,Real Oviedo,1037,16,2,0
64,Josip Brekalo,Real Oviedo,483,14,0,0
65,Pablo Agudín,Real Oviedo,82,6,0,0
66,Marco Esteban,Real Oviedo,45,1,0,0
67,Omar Falah,Real Oviedo,13,1,0,0
68,Borja Sánchez,Real Oviedo,13,1,0,0
69,Mikel Goti,Real Sociedad,81,4,0,0
70,Job Ochieng,Real Sociedad,25,1,0,0
71,Dani Díaz,Real Sociedad,17,1,0,0
72,Luken Beitia,Real Sociedad,14,1,0,0
73,Gorka Carrera Zarranz,Real Sociedad,13,1,0,0
74,Ibai Aguirre,Real Sociedad,10,1,0,0
75,Arkaitz Mariezkurrena,Real Sociedad,1,1,0,0
76,Lander Astiazaran,Real Sociedad,1,1,0,0
77,Dodi Lukebakio,Sevilla,180,2,1,0
78,Ramón Martínez,Sevilla,100,2,0,0
79,Miguel Sierra,Sevilla,63,4,0,0
80,Stanis Idumbo Muzambo,Sevilla,45,1,0,0
81,Renzo Saravia,Valencia,150,2,0,0
82,Rubén Iranzo,Valencia,12,1,0,0
83,Yéremy Pino,Villarreal,160,2,0,1
84,Manor Solomon,Villarreal,153,6,1,1
85,Hugo Lopez,Villarreal,55,2,0,0
86,Adrià Altimira,Villarreal,8,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Athletic Club  —  SF sin salario:

         player  minutesPlayed
0  Asier Hierro             33
1   Eder Garcia             36

  CG plantilla completa:

                     player              player_norm
0               Adama Boiro              adama boiro
1             Aitor Paredes            aitor paredes
2            Alejandro Rego           alejandro rego
3            Álex Berenguer           alex berenguer
4              Álex Padilla             alex padilla
5          Andoni Gorosabel         andoni gorosabel
6           Aymeric Laporte          aymeric laporte
7              Beñat Prados             benat prados
8               Dani Vivian              dani vivian
9            Gorka Guruzeta           gorka guruzeta
10           Iñaki Williams           inaki williams
11              Iñigo Lekue              inigo lekue
12  Iñigo Ruiz de Galarreta  inigo ruiz de galarreta
13              Jesús Areso              jesus areso
14           Maroan Sannadi           maroan sannadi
15         Mikel Jauregizar         mikel jauregizar
16              Mikel Vesga              mikel vesga
17             Nico Serrano             nico serrano
18            Nico Williams            nico williams
19             Oihan Sancet             oihan sancet
20           Robert Navarro           robert navarro
21           Selton Sánchez           selton sanchez
22              Unai Egiluz              unai egiluz
23               Unai Gómez               unai gomez
24               Unai Simón               unai simon
25               Urko Izeta               urko izeta
26            Yeray Álvarez            yeray alvarez
27           Yuri Berchiche           yuri berchiche

============================================================
  Atlético Madrid  —  SF sin salario:

              player  minutesPlayed
0    Conor Gallagher            665
1      Dani Martinez             90
2  Giacomo Raspadori            250
3    Jano Monserrate             28
4      Javi Morcillo             48
5       Javier Boñar            180
6         Julio Díaz            221
7      Rayane Belaid             71
8       Taufik Seidu             22

  CG plantilla completa:

               player        player_norm
0     Ademola Lookman    ademola lookman
1          Álex Baena         alex baena
2   Alexander Sörloth  alexander sorloth
3   Antoine Griezmann  antoine griezmann
4     Clément Lenglet    clement lenglet
5        Dávid Hancko       david hancko
6    Giuliano Simeone   giuliano simeone
7           Jan Oblak          jan oblak
8              Johnny             johnny
9        José Giménez       jose gimenez
10         Juan Musso         juan musso
11     Julián Alvarez     julian alvarez
12               Koke               koke
13        Marc Pubill        marc pubill
14    Marcos Llorente    marcos llorente
15     Matteo Ruggeri     matteo ruggeri
16      Nahuel Molina      nahuel molina
17   Nicolás González   nicolas gonzalez
18        Obed Vargas        obed vargas
19      Pablo Barrios      pablo barrios
20   Robin Le Normand   robin le normand
21    Rodrigo Mendoza    rodrigo mendoza
22      Thiago Almada      thiago almada
23       Thomas Lemar       thomas lemar

============================================================
  Celta Vigo  —  SF sin salario:

             player  minutesPlayed
0    Andrés Antañón             62
1    Bryan Zaragoza           1135
2  Damián Rodríguez            151
3       Hugo Burcio             12
4     Hugo González             12

  CG plantilla completa:

                 player          player_norm
0          Álvaro Núñez         alvaro nunez
1        Borja Iglesias       borja iglesias
2         Carl Starfelt        carl starfelt
3      Carlos Domínguez     carlos dominguez
4             Fer López            fer lopez
5         Ferran Jutglà        ferran jutgla
6          Franco Cervi         franco cervi
7          Hugo Álvarez         hugo alvarez
8           Hugo Sotelo          hugo sotelo
9            Iago Aspas           iago aspas
10         Ilaix Moriba         ilaix moriba
11           Ionut Radu           ionut radu
12          Iván Villar          ivan villar
13       Javi Rodríguez       javi rodriguez
14           Javi Rueda           javi rueda
15  Jones El-Abdellaoui  jones el abdellaoui
16         Joseph Aidoo         joseph aidoo
17       Manu Fernández       manu fernandez
18           Marc Vidal           marc vidal
19        Marcos Alonso        marcos alonso
20        Matías Vecino        matias vecino
21         Miguel Román         miguel roman
22       Mihailo Ristic       mihailo ristic
23       Óscar Mingueza       oscar mingueza
24          Pablo Durán          pablo duran
25      Sergio Carreira      sergio carreira
26     Williot Swedberg     williot swedberg
27            Yoel Lago            yoel lago

============================================================
  Deportivo Alavés  —  SF sin salario:

              player  minutesPlayed
0   Calebe Gonçalves            764
1  Carlos Ballestero              9
2     Carlos Vicente           1256
3     Diego Morcillo              9
4    Lander Pinillos              1
5      Moussa Diarra            219

  CG plantilla completa:

              player       player_norm
0       Abde Rebbach      abde rebbach
1        Aitor Mañas       aitor manas
2      Ander Guevara     ander guevara
3        Ángel Pérez       angel perez
4     Antonio Blanco    antonio blanco
5     Antonio Sivera    antonio sivera
6             Calebe            calebe
7       Carles Aleñá      carles alena
8   Carlos Benavidez  carlos benavidez
9       Denis Suárez      denis suarez
10    Facundo Garcés    facundo garces
11   Ibrahim Diabate   ibrahim diabate
12        Jon Guridi        jon guridi
13       Jon Pacheco       jon pacheco
14        Jonny Otto        jonny otto
15        Lucas Boyé        lucas boye
16      Mariano Díaz      mariano diaz
17   Nahuel Tenaglia   nahuel tenaglia
18      Nikola Maras      nikola maras
19      Pablo Ibáñez      pablo ibanez
20    Raúl Fernández    raul fernandez
21     Toni Martínez     toni martinez
22     Victor Parada     victor parada
23       Ville Koski       ville koski
24  Youssef Enríquez  youssef enriquez

============================================================
  Elche  —  SF sin salario:

                player  minutesPlayed
0         Alex Sanchez             14
1           Ali Houary            125
2      Jairo Izquierdo             25
3  Mourad El Ghezouani             50

  CG plantilla completa:

               player        player_norm
0         Adam Boayar        adam boayar
1       Adrià Pedrosa      adria pedrosa
2         Aleix Febas        aleix febas
3    Alejandro Iturbe   alejandro iturbe
4    Álvaro Rodríguez   alvaro rodriguez
5         André Silva        andre silva
6         Bambo Diaby        bambo diaby
7        Buba Sangaré       buba sangare
8   David Affengruber  david affengruber
9    Federico Redondo   federico redondo
10      Germán Valera      german valera
11     Gonzalo Villar     gonzalo villar
12     Grady Diangana     grady diangana
13        Héctor Fort        hector fort
14         Iñaki Peña         inaki pena
15        John Donald        john donald
16              Josan              josan
17         Léo Pétrot         leo petrot
18       Lucas Cepeda       lucas cepeda
19        Marc Aguado        marc aguado
20        Martim Neto        martim neto
21      Matías Dituro      matias dituro
22        Pedro Bigas        pedro bigas
23           Rafa Mir           rafa mir
24       Tete Morente       tete morente
25       Víctor Chust       victor chust
26      Yago Santiago      yago santiago

============================================================
  FC Barcelona  —  SF sin salario:

            player  minutesPlayed
0   Dro Fernández             90
1  Jofre Torrents              47
2    Tomás Marqués              9
3   Toni Fernández             45
4      Xavi Espart             91

  CG plantilla completa:

                   player            player_norm
0         Alejandro Balde        alejandro balde
1     Andreas Christensen    andreas christensen
2               Ansu Fati              ansu fati
3               Dani Olmo              dani olmo
4             Eric García            eric garcia
5            Fermín López           fermin lopez
6           Ferran Torres          ferran torres
7         Frenkie de Jong        frenkie de jong
8                    Gavi                   gavi
9           Gerard Martín          gerard martin
10             Iñaki Peña             inaki pena
11            Joan García            joan garcia
12           João Cancelo           joao cancelo
13           Jules Koundé           jules kounde
14           Lamine Yamal           lamine yamal
15  Marc-André ter Stegen  marc andre ter stegen
16            Marc Bernal            marc bernal
17            Marc Casadó            marc casado
18        Marcus Rashford        marcus rashford
19            Pau Cubarsí            pau cubarsi
20                  Pedri                  pedri
21               Raphinha               raphinha
22     Robert Lewandowski     robert lewandowski
23          Ronald Araujo          ronald araujo
24         Roony Bardghji         roony bardghji
25      Wojciech Szczęsny      wojciech szczesny

============================================================
  Getafe  —  SF sin salario:

               player  minutesPlayed
0  Alejandro Mestanza             79
1    Christantus Uche            270
2      Hugo Solozábal             10
3        Jorge Montes             26
4     José Luis Pérez             20
5          Yvan Neyou             73
6           Álex Sola             12

  CG plantilla completa:

                player         player_norm
0          Abdel Abqar         abdel abqar
1           Abu Kamara          abu kamara
2          Adrián Liso         adrian liso
3         Álex Sancris        alex sancris
4           Allan Nyom          allan nyom
5        Borja Mayoral       borja mayoral
6        Coba da Costa       coba da costa
7          David Soria         david soria
8             Davinchi            davinchi
9           Diego Rico          diego rico
10               Djené               djene
11     Domingos Duarte     domingos duarte
12    Ismael Bekhoucha    ismael bekhoucha
13          Javi Muñoz          javi munoz
14        Jiri Letacek        jiri letacek
15       Juan Berrocal       juan berrocal
16       Juan Iglesias       juan iglesias
17              Juanmi              juanmi
18        Kiko Femenía        kiko femenia
19          Luis Milla          luis milla
20        Luis Vázquez        luis vazquez
21        Mario Martín        mario martin
22     Martín Satriano     martin satriano
23     Mauro Arambarri     mauro arambarri
24   Sebastián Boselli   sebastian boselli
25  Veljko Birmancevic  veljko birmancevic
26         Zaid Romero         zaid romero

============================================================
  Girona FC  —  SF sin salario:

            player  minutesPlayed
0    Bojan Miovski             44
1     Dawda Camara             71
2       Jhon Solís            384
3      Juan Arango             19
4  Ladislav Krejčí            180
5   Yáser Asprilla            605

  CG plantilla completa:

                   player            player_norm
0               Abel Ruiz              abel ruiz
1       Alejandro Francés      alejandro frances
2             Álex Moreno            alex moreno
3          Arnau Martínez         arnau martinez
4             Axel Witsel            axel witsel
5         Azzedine Ounahi        azzedine ounahi
6               Bryan Gil              bryan gil
7       Claudio Echeverri      claudio echeverri
8        Cristhian Stuani       cristhian stuani
9             Daley Blind            daley blind
10            David López            david lopez
11      Donny van de Beek      donny van de beek
12           Fran Beltrán           fran beltran
13            Hugo Rincón            hugo rincon
14            Iván Martín            ivan martin
15              Joel Roca              joel roca
16            Juan Carlos            juan carlos
17          Lass Kourouma          lass kourouma
18  Marc-André ter Stegen  marc andre ter stegen
19        Paulo Gazzaniga        paulo gazzaniga
20                  Portu                  portu
21           Thomas Lemar           thomas lemar
22       Viktor Tsyhankov       viktor tsyhankov
23             Vitor Reis             vitor reis
24   Vladyslav Krapyvtsov   vladyslav krapyvtsov
25        Vladyslav Vanat        vladyslav vanat
26         Yáser Asprilla         yaser asprilla

============================================================
  Levante UD  —  SF sin salario:

              player  minutesPlayed
0  Goduine Koyalipou            239
1      Jorge Cabello            364
2        Nacho Pérez             80
3      Sergio Lozano             11

  CG plantilla completa:

                  player           player_norm
0    Adrián de la Fuente   adrian de la fuente
1          Alan Matturro         alan matturro
2         Carlos Álvarez        carlos alvarez
3            Carlos Espí           carlos espi
4           Diego Pampín          diego pampin
5            Iker Losada           iker losada
6            Iván Romero           ivan romero
7          Jeremy Toljan         jeremy toljan
8   Jon Ander Olasagasti  jon ander olasagasti
9      José Luis Morales     jose luis morales
10          Kareem Tunde          kareem tunde
11       Karl Etta Eyong       karl etta eyong
12        Kervin Arriaga        kervin arriaga
13          Manu Sánchez          manu sanchez
14           Mathew Ryan           mathew ryan
15         Matías Moreno         matias moreno
16             Oriol Rey             oriol rey
17          Pablo Campos          pablo campos
18        Pablo Martínez        pablo martinez
19           Paco Cortés           paco cortes
20          Roger Brugué          roger brugue
21              Tay Abed              tay abed
22         Ugo Raghouber         ugo raghouber
23        Unai Elgezabal        unai elgezabal
24         Unai Vencedor         unai vencedor
25         Víctor García         victor garcia

============================================================
  Mallorca  —  SF sin salario:

           player  minutesPlayed
0  Dani Rodriguez             67
1   Marc Domenech            217

  CG plantilla completa:

               player        player_norm
0         Abdón Prats        abdon prats
1      Antonio Raíllo     antonio raillo
2     Antonio Sánchez    antonio sanchez
3         Daniel Luna        daniel luna
4         David López        david lopez
5        Iván Cuéllar       ivan cuellar
6           Jan Salas          jan salas
7         Jan Virgili        jan virgili
8        Javi Llabrés       javi llabres
9        Johan Mojica       johan mojica
10     Justin Kalumba     justin kalumba
11          Leo Román          leo roman
12    Lucas Bergström    lucas bergstrom
13      Manu Morlanes      manu morlanes
14    Marash Kumbulla    marash kumbulla
15     Martin Valjent     martin valjent
16       Mateo Joseph       mateo joseph
17  Mateu Morey Bauzà  mateu morey bauza
18     Omar Mascarell     omar mascarell
19       Pablo Maffeo       pablo maffeo
20        Pablo Torre        pablo torre
21         Samú Costa         samu costa
22       Sergi Darder       sergi darder
23       Takuma Asano       takuma asano
24          Toni Lato          toni lato
25       Vedat Muriqi       vedat muriqi
26       Zito Luvumbo       zito luvumbo

============================================================
  Rayo Vallecano  —  SF sin salario:

             player  minutesPlayed
0             Pacha           1214
1  Pelayo Fernández             45

  CG plantilla completa:

              player       player_norm
0        Abdul Mumin       abdul mumin
1   Alexandre Alemão  alexandre alemao
2     Alfonso Espino    alfonso espino
3      Álvaro García     alvaro garcia
4       Andrei Rațiu      andrei ratiu
5    Augusto Batalla   augusto batalla
6      Carlos Martín     carlos martin
7      Dani Cárdenas     dani cardenas
8    Florian Lejeune   florian lejeune
9         Fran Pérez        fran perez
10     Gerard Gumbau     gerard gumbau
11    Ilias Akhomach    ilias akhomach
12       Isi Palazón       isi palazon
13       Iván Balliu       ivan balliu
14   Jorge de Frutos   jorge de frutos
15  Jozhua Vertrouwd  jozhua vertrouwd
16       Luiz Felipe       luiz felipe
17       Nobel Mendy       nobel mendy
18       Óscar Trejo       oscar trejo
19    Óscar Valentín    oscar valentin
20        Pathé Ciss        pathe ciss
21        Pedro Díaz        pedro diaz
22     Pep Chavarría     pep chavarria
23       Randy Nteka       randy nteka
24      Samu Becerra      samu becerra
25    Sergio Camello    sergio camello
26        Unai López        unai lopez

============================================================
  Real Betis  —  SF sin salario:

           player  minutesPlayed
0      Dani Pérez              1
1  Ivan Corralejo             14

  CG plantilla completa:

               player        player_norm
0     Abde Ezzalzouli    abde ezzalzouli
1              Adrián             adrian
2        Aitor Ruibal       aitor ruibal
3      Álvaro Fidalgo     alvaro fidalgo
4       Álvaro Valles      alvaro valles
5         Ángel Ortiz        angel ortiz
6              Antony             antony
7      Cédric Bakambu     cedric bakambu
8         Chimy Ávila        chimy avila
9     Cucho Hernández    cucho hernandez
10     Diego Llorente     diego llorente
11   Giovani Lo Celso   giovani lo celso
12    Héctor Bellerín    hector bellerin
13               Isco               isco
14       Junior Firpo       junior firpo
15        Marc Bartra        marc bartra
16          Marc Roca          marc roca
17              Natan              natan
18      Nelson Deossa      nelson deossa
19      Pablo Fornals      pablo fornals
20       Pablo García       pablo garcia
21          Pau López          pau lopez
22  Ricardo Rodríguez  ricardo rodriguez
23   Rodrigo Riquelme   rodrigo riquelme
24     Sergi Altimira     sergi altimira
25     Sofyan Amrabat     sofyan amrabat
26     Valentín Gómez     valentin gomez

============================================================
  Real Madrid  —  SF sin salario:

                 player  minutesPlayed
0        César Palacios             51
1          Daniel Yañez             32
2         David Jiménez             77
3          Diego Aguado             29
4         Jorge Cestero             12
5    Manuel Ángel Morán             95
6  Thiago Pitarch Pinar            363
7     Víctor Valdepeñas             78

  CG plantilla completa:

                    player             player_norm
0          Álvaro Carreras         alvaro carreras
1             Andriy Lunin            andriy lunin
2          Antonio Rüdiger         antonio rudiger
3               Arda Güler              arda guler
4      Aurélien Tchouaméni     aurelien tchouameni
5              Brahim Díaz             brahim diaz
6            Dani Ceballos           dani ceballos
7          Daniel Carvajal         daniel carvajal
8              David Alaba             david alaba
9             Dean Huijsen            dean huijsen
10            Éder Militão            eder militao
11       Eduardo Camavinga       eduardo camavinga
12                 Endrick                 endrick
13       Federico Valverde       federico valverde
14           Ferland Mendy           ferland mendy
15             Fran García             fran garcia
16           Fran González           fran gonzalez
17      Franco Mastantuono      franco mastantuono
18          Gonzalo García          gonzalo garcia
19         Jude Bellingham         jude bellingham
20           Kylian Mbappé           kylian mbappe
21            Raúl Asencio            raul asencio
22                 Rodrygo                 rodrygo
23        Thibaut Courtois        thibaut courtois
24  Trent Alexander-Arnold  trent alexander arnold
25         Vinicius Junior         vinicius junior

============================================================
  Real Oviedo  —  SF sin salario:

           player  minutesPlayed
0     Abdel Rahim           1526
1   Borja Sánchez             13
2   Josip Brekalo            483
3   Marco Esteban             45
4      Omar Falah             13
5    Pablo Agudín             82
6  Salomón Rondón           1037

  CG plantilla completa:

                 player          player_norm
0       Aarón Escandell      aaron escandell
1         Alberto Reina        alberto reina
2            Álex Forés           alex fores
3     Brandon Dominguès    brandon domingues
4            Dani Calvo           dani calvo
5           David Carmo          david carmo
6          David Costas         david costas
7           Eric Bailly          eric bailly
8        Federico Viñas       federico vinas
9        Haissem Hassan       haissem hassan
10     Horațiu Moldovan     horatiu moldovan
11         Ilyas Chaira         ilyas chaira
12           Javi López           javi lopez
13           Kwasi Sibo           kwasi sibo
14   Leander Dendoncker   leander dendoncker
15        Lucas Ahijado        lucas ahijado
16            Luka Ilic            luka ilic
17          Nacho Vidal          nacho vidal
18      Nicolás Fonseca      nicolas fonseca
19          Oier Luengo          oier luengo
20          Ovie Ejaria          ovie ejaria
21      Rahim Alhassane      rahim alhassane
22        Santi Cazorla        santi cazorla
23  Santiago Colombatto  santiago colombatto
24        Thiago Borbas        thiago borbas
25     Thiago Fernández     thiago fernandez

============================================================
  Real Sociedad  —  SF sin salario:

                  player  minutesPlayed
0  Arkaitz Mariezkurrena              1
1              Dani Díaz             17
2  Gorka Carrera Zarranz             13
3           Ibai Aguirre             10
4            Job Ochieng             25
5      Lander Astiazaran              1
6           Luken Beitia             14
7             Mikel Goti             81

  CG plantilla completa:

               player        player_norm
0         Aihen Muñoz        aihen munoz
1         Álex Remiro        alex remiro
2    Álvaro Odriozola   alvaro odriozola
3   Ander Barrenetxea  ander barrenetxea
4     Aritz Elustondo    aritz elustondo
5     Arsen Zakharyan    arsen zakharyan
6    Beñat Turrientes   benat turrientes
7        Brais Méndez       brais mendez
8        Carlos Soler       carlos soler
9     Duje Caleta-Car    duje caleta car
10     Gonçalo Guedes     goncalo guedes
11      Igor Zubeldia      igor zubeldia
12       Jon Aramburu       jon aramburu
13   Jon Gorrotxategi   jon gorrotxategi
14    Jon Karrikaburu    jon karrikaburu
15         Jon Martín         jon martin
16         Luka Sucic         luka sucic
17    Mikel Oyarzabal    mikel oyarzabal
18     Orri Óskarsson     orri oskarsson
19        Pablo Marín        pablo marin
20       Sergio Gómez       sergio gomez
21      Takefusa Kubo      takefusa kubo
22       Unai Marrero       unai marrero
23             Wesley             wesley
24     Yangel Herrera     yangel herrera

============================================================
  Sevilla  —  SF sin salario:

                  player  minutesPlayed
0         Dodi Lukebakio            180
1          Miguel Sierra             63
2         Ramón Martínez            100
3  Stanis Idumbo Muzambo             45

  CG plantilla completa:

                  player           player_norm
0          Adnan Januzaj         adnan januzaj
1             Akor Adams            akor adams
2         Alexis Sánchez        alexis sanchez
3         Alfon González        alfon gonzalez
4         Andrés Castrín        andres castrin
5          Batista Mendy         batista mendy
6      César Azpilicueta     cesar azpilicueta
7          Chidera Ejuke         chidera ejuke
8            Djibril Sow           djibril sow
9          Fábio Cardoso         fabio cardoso
10      Federico Gattoni      federico gattoni
11         Gabriel Suazo         gabriel suazo
12          Isaac Romero          isaac romero
13           Joan Jordán           joan jordan
14    José Ángel Carmona    jose angel carmona
15        Juanlu Sánchez        juanlu sanchez
16            Kike Salas            kike salas
17         Lucien Agoume         lucien agoume
18            Manu Bueno            manu bueno
19                Marcão                marcao
20           Neal Maupay           neal maupay
21        Nemanja Gudelj        nemanja gudelj
22  Odysseas Vlachodimos  odysseas vlachodimos
23                   Oso                   oso
24       Peque Fernández       peque fernandez
25          Ørjan Nyland           rjan nyland
26          Rubén Vargas          ruben vargas
27        Tanguy Nianzou        tanguy nianzou

============================================================
  Valencia  —  SF sin salario:

          player  minutesPlayed
0  Renzo Saravia            150
1   Rubén Iranzo             12

  CG plantilla completa:

                 player          player_norm
0         André Almeida        andre almeida
1        Arnaut Danjuma       arnaut danjuma
2   Baptiste Santamaria  baptiste santamaria
3         César Tárrega        cesar tarrega
4       Cristian Rivero      cristian rivero
5           Daniel Raba          daniel raba
6           Diego López          diego lopez
7     Dimitri Foulquier    dimitri foulquier
8           Eray Cömert          eray comert
9         Filip Ugrinic        filip ugrinic
10      Guido Rodríguez      guido rodriguez
11            Hugo Duro            hugo duro
12          Javi Guerra          javi guerra
13        Jesús Vázquez        jesus vazquez
14          José Copete          jose copete
15            José Gayà            jose gaya
16   Julen Agirrezabala   julen agirrezabala
17      Largie Ramazani      largie ramazani
18        Lucas Beltrán        lucas beltran
19           Luis Rioja           luis rioja
20     Mouctar Diakhaby     mouctar diakhaby
21               Pepelu               pepelu
22   Stole Dimitrievski   stole dimitrievski
23      Thierry Correia      thierry correia
24           Umar Sadiq           umar sadiq
25           Unai Núñez           unai nunez

============================================================
  Villarreal  —  SF sin salario:

           player  minutesPlayed
0  Adrià Altimira              8
1      Hugo Lopez             55
2   Manor Solomon            153
3     Yéremy Pino            160

  CG plantilla completa:

                player         player_norm
0      Alberto Moleiro     alberto moleiro
1         Alex Freeman        alex freeman
2       Alfon González      alfon gonzalez
3      Alfonso Pedraza     alfonso pedraza
4          Arnau Tenas         arnau tenas
5          Ayoze Pérez         ayoze perez
6         Carlos Macià        carlos macia
7          Dani Parejo         dani parejo
8          Diego Conde         diego conde
9   Georges Mikautadze  georges mikautadze
10       Gerard Moreno       gerard moreno
11          Juan Foyth          juan foyth
12         Logan Costa         logan costa
13         Luiz Júnior         luiz junior
14        Nicolas Pépé        nicolas pepe
15          Pape Gueye          pape gueye
16         Pau Cabanes         pau cabanes
17         Pau Navarro         pau navarro
18          Rafa Marín          rafa marin
19        Renato Veiga        renato veiga
20      Santi Comesaña      santi comesana
21    Santiago Mouriño    santiago mourino
22       Sergi Cardona       sergi cardona
23      Tajon Buchanan      tajon buchanan
24      Tani Oluwaseyi      tani oluwaseyi
25       Thomas Partey       thomas partey
26      Willy Kambwala      willy kambwala

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('pacha',       'rayo vallecano'): ('alfonso espino',  'rayo vallecano'),
    ('abdel rahim', 'real oviedo')   : ('rahim alhassane', 'real oviedo'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 2

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: pacha (rayo vallecano) → alfonso espino (rayo vallecano)
✅ Match manual aplicado: abdel rahim (real oviedo) → rahim alhassane (real oviedo)

Tras matches manuales: 493/578 (85.3%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

⚠️ Nombre con sufijo `_snapshot_20260428` para diferenciar del master definitivo
que se generará al cierre de la temporada (`master_spain_2526.csv`).

In [21]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_spain_2526_snapshot_20260428.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_spain_2526_snapshot_20260428.csv
   Jugadores totales:  578
   Con salario:        493
   Sin salario (NaN):  85
   Columnas:           122