# 03 · Join Sofascore + Capology — Spain La Liga 21/22

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2021/22 de La Liga española**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_spain_2122.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_spain_2122.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  604 jugadores | 116 columnas
Capology:   572 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   deportivo alaves
   levante ud

En Capology pero no en Sofascore:
   alaves
   levante

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'alaves':'deportivo alaves',
            'levante':'levante ud'

}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 508/604 (84.1%)
Sin emparejar: 96

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          9
Revisión media    (0.75 ≤ score < 0.90):   12
Revisión estricta (0.50 ≤ score < 0.75):   44
Revisión muy est. (score < 0.50):           31

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

            player_sf           team           cg_match  score
41  Alexander Sørloth  Real Sociedad  alexander sorloth  0.970
43       Rober Ibáñez        Osasuna      robert ibanez  0.960
19       Jens Jønsson          Cádiz       jens jonsson  0.957
84   Javier Ontiveros        Osasuna     javi ontiveros  0.933
38     Manuel Sánchez        Osasuna       manu sanchez  0.923
9       Daniel Vivian  Athletic Club        dani vivian  0.917
14        Yéremy Pino     Villarreal        yeremi pino  0.909
75        Javier Díaz        Sevilla          javi diaz  0.900
45          Dani Raba        Granada        daniel raba  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf              team           cg_match  score
55        Nicolás Melamed          Espanyol       nico melamed  0.889
18         Matthew Miazga  Deportivo Alavés        matt miazga  0.880
10  Abdessamad Ezzalzouli         Barcelona    abde ezzalzouli  0.833
44       José Juan Macías            Getafe        jose macias  0.815
28        Florentino Luís            Getafe         florentino  0.800
5      José María Giménez   Atlético Madrid       jose gimenez  0.800
53      Alejandro Asensio    Rayo Vallecano   alejandro catena  0.788
25         José Luis Gayà          Valencia          jose gaya  0.783
62       Álex Petxarroman     Athletic Club         alex petxa  0.769
39          Fernando Niño          Mallorca           fer nino  0.762
16     Luis Javier Suárez           Granada        luis suarez  0.759
50        Alejandro Primo        Levante UD  alejandro cantero  0.750

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['alejandro asensio',
                      'alejandro primo'
]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 10 | Excluidos: 2

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf              team           cg_match  score
26     Pathé Ismaël Ciss    Rayo Vallecano         pathe ciss  0.741
21     Maximiliano Gómez          Valencia         maxi gomez  0.741
70          Ivan Barbero           Osasuna            barbero  0.737
22        Anthony Lozano             Cádiz       choco lozano  0.692
82    Cristhian Mosquera          Valencia    cristian rivero  0.667
68        Álvaro Aguirre    Rayo Vallecano      alvaro garcia  0.667
92           Hugo Sotelo        Celta Vigo         hugo mallo  0.667
78       Mario Domínguez          Valencia         maxi gomez  0.640
57          Ander Martín     Real Sociedad      ander guevara  0.640
31          Hugo Álvarez        Celta Vigo         hugo mallo  0.636
65          Tomás Mendes  Deportivo Alavés         tomas pina  0.636
34           Gori Gracia          Espanyol        joan garcia  0.636
36             Álex Sola     Real Sociedad  alexander sorloth  0.615
2            John Donald             Elche       johan mojica  0.609
93          Victor Gómez          Espanyol        sergi gomez  0.609
20        Radamel Falcao    Rayo Vallecano             falcao  0.600
86         Sergio Barcia           Granada     santiago arias  0.593
11     Rafinha Alcântara     Real Sociedad            rafinha  0.583
52    Mario Gila Fuentes       Real Madrid      marco asensio  0.581
51            Unai Dufur           Osasuna        unai garcia  0.571
67           Unai Ropero  Deportivo Alavés         javi lopez  0.571
17            Pablo Gavi         Barcelona               gavi  0.571
27         Rodri Sánchez        Real Betis       diego lainez  0.560
1         Jofre Carreras          Espanyol    leandro cabrera  0.552
6           Jon Bautista     Real Sociedad         jon guridi  0.545
66   Daniel Villahermosa          Espanyol     yangel herrera  0.545
63            Omar Faraj        Levante UD       oscar duarte  0.545
71         Germán Valera     Real Sociedad      ander guevara  0.538
30    José Ángel Carmona           Sevilla       jesus corona  0.533
79            Raúl Parra             Cádiz      ruben alcaraz  0.522
46          Javi Llabrés          Mallorca        joan sastre  0.522
8          José Calderón        Real Betis     sergio canales  0.519
13        Antonio Blanco       Real Madrid      dani ceballos  0.519
81          Javi Serrano   Atlético Madrid   yannick carrasco  0.500
29         Carlos Martín   Atlético Madrid    marcos llorente  0.500
15      Marcelo Saracchi        Levante UD       carlos clerc  0.500
42       Clément Grenier          Mallorca      dominik greif  0.500
47         Juanmi Latasa       Real Madrid        david alaba  0.500
32           Jesús Owono  Deportivo Alavés              jason  0.500
58                Wu Lei          Espanyol             lei wu  0.500
49  Carlo Adriano García        Villarreal       mario gaspar  0.500
88      Giuliano Simeone   Atlético Madrid       jose gimenez  0.500
59            Marc Tenas  Deportivo Alavés         tomas pina  0.500
94         Adrián Butzke           Granada    domingos duarte  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['pathe ismael ciss',
                    'maximiliano gomez',
                    'ivan barbero',
                    'anthony lozano',
                    'radamel falcao',
                    'rafinha alcantara',
                    'pablo gavi',
                    'wu lei'
]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 8

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf              team            cg_match  score
48        Alexandru Țîrlea  Deportivo Alavés       mamadou sylla  0.483
64         Estanis Pedrola         Barcelona          inaki pena  0.480
83            Pedro Benito             Cádiz       ruben sobrino  0.480
74          Juanlu Sánchez           Sevilla         joan jordan  0.480
54          Peter González       Real Madrid         gareth bale  0.480
76           Cristo Romero     Real Sociedad        mikel merino  0.480
61             Gabri Veiga        Celta Vigo          javi galan  0.476
73             Iker Benito           Osasuna          kike barja  0.476
77     Álvaro Sanz Catalán         Barcelona     alejandro balde  0.471
90     Raúl García de Haro        Real Betis     andres guardado  0.471
95       Valentino Fattore           Sevilla       oliver torres  0.467
33           Sergio Santos       Real Madrid       marco asensio  0.462
12          Marc Cucurella            Getafe        jorge cuenca  0.462
7              Pedro Ortiz           Sevilla     oscar rodriguez  0.462
69           Emerson Royal         Barcelona       sergio aguero  0.462
89           Luca Koleosho          Espanyol       manu morlanes  0.462
60           Naïs Djouahra     Real Sociedad       adnan januzaj  0.462
80          Yellu Santiago          Valencia        helder costa  0.462
4              Saúl Ñíguez   Atlético Madrid         luis suarez  0.455
37         Nicolas Jackson        Villarreal    giovani lo celso  0.452
72  Amankwaa Akurugu Koffi            Getafe  nemanja maksimovic  0.450
85            Rubén Iranzo          Valencia     cristian rivero  0.444
24          Lluís Recasens          Espanyol       manu morlanes  0.444
91             Mika Mármol         Barcelona        adama traore  0.435
35             Luismi Cruz           Sevilla        jesus corona  0.435
0             Kike Hermoso        Real Betis         joel robles  0.435
23           Rubén Sánchez          Espanyol     fernando calero  0.429
56       Alberto Rodríguez  Deportivo Alavés        ruben duarte  0.414
40           Jesús Vázquez          Valencia        manu vallejo  0.400
3           Ilias Akhomach         Barcelona   philippe coutinho  0.387
87              Josep Gayá          Mallorca         joan sastre  0.381

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 535/604 (88.6%)
Sin salario:     69

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 69

,player,team,minutesPlayed,appearances,goals,assists
0,Saúl Ñíguez,Atlético Madrid,200,3,0,1
1,Javi Serrano,Atlético Madrid,69,5,0,0
2,Carlos Martín,Atlético Madrid,8,1,0,0
3,Giuliano Simeone,Atlético Madrid,1,1,0,0
4,Ilias Akhomach,Barcelona,125,2,0,0
5,Emerson Royal,Barcelona,90,3,0,0
6,Álvaro Sanz Catalán,Barcelona,27,2,0,0
7,Estanis Pedrola,Barcelona,10,1,0,0
8,Mika Mármol,Barcelona,1,1,0,0
9,Gabri Veiga,Celta Vigo,126,7,0,0
10,Hugo Álvarez,Celta Vigo,10,1,0,0
11,Hugo Sotelo,Celta Vigo,1,1,0,0
12,Raúl Parra,Cádiz,88,2,0,0
13,Pedro Benito,Cádiz,30,1,0,0
14,Alberto Rodríguez,Deportivo Alavés,241,5,0,0
15,Jesús Owono,Deportivo Alavés,90,1,0,0
16,Marc Tenas,Deportivo Alavés,51,3,0,0
17,Alexandru Țîrlea,Deportivo Alavés,14,1,0,0
18,Unai Ropero,Deportivo Alavés,11,1,0,0
19,Tomás Mendes,Deportivo Alavés,8,1,0,0
20,John Donald,Elche,180,2,0,0
21,Rubén Sánchez,Espanyol,148,4,0,1
22,Lluís Recasens,Espanyol,45,1,0,0
23,Daniel Villahermosa,Espanyol,22,1,0,0
24,Jofre Carreras,Espanyol,17,3,0,1
25,Gori Gracia,Espanyol,8,1,0,0
26,Victor Gómez,Espanyol,3,1,0,0
27,Luca Koleosho,Espanyol,1,1,0,0
28,Amankwaa Akurugu Koffi,Getafe,84,3,0,1
29,Marc Cucurella,Getafe,22,1,0,0
30,Sergio Barcia,Granada,77,1,0,0
31,Adrián Butzke,Granada,1,1,0,0
32,Marcelo Saracchi,Levante UD,186,4,0,1
33,Alejandro Primo,Levante UD,90,1,0,0
34,Omar Faraj,Levante UD,9,1,0,0
35,Javi Llabrés,Mallorca,135,5,0,0
36,Clément Grenier,Mallorca,70,5,1,0
37,Josep Gayá,Mallorca,59,1,0,0
38,Iker Benito,Osasuna,116,4,0,0
39,Unai Dufur,Osasuna,90,1,0,0
40,Alejandro Asensio,Rayo Vallecano,12,2,0,0
41,Álvaro Aguirre,Rayo Vallecano,8,1,0,0
42,Rodri Sánchez,Real Betis,886,21,1,2
43,Kike Hermoso,Real Betis,90,1,1,0
44,José Calderón,Real Betis,64,1,0,0
45,Raúl García de Haro,Real Betis,1,1,0,0
46,Peter González,Real Madrid,37,3,0,0
47,Antonio Blanco,Real Madrid,30,1,0,0
48,Mario Gila Fuentes,Real Madrid,23,2,0,0
49,Sergio Santos,Real Madrid,10,1,0,0
50,Juanmi Latasa,Real Madrid,9,1,0,0
51,Naïs Djouahra,Real Sociedad,209,7,0,0
52,Ander Martín,Real Sociedad,108,5,0,0
53,Germán Valera,Real Sociedad,53,3,0,0
54,Jon Bautista,Real Sociedad,45,1,0,0
55,Álex Sola,Real Sociedad,39,2,0,0
56,Cristo Romero,Real Sociedad,16,1,0,0
57,José Ángel Carmona,Sevilla,23,1,0,0
58,Pedro Ortiz,Sevilla,12,1,0,0
59,Luismi Cruz,Sevilla,12,2,0,0
60,Juanlu Sánchez,Sevilla,11,1,0,0
61,Valentino Fattore,Sevilla,1,1,0,0
62,Jesús Vázquez,Valencia,819,15,0,0
63,Cristhian Mosquera,Valencia,220,6,0,0
64,Rubén Iranzo,Valencia,134,4,0,0
65,Yellu Santiago,Valencia,81,3,0,0
66,Mario Domínguez,Valencia,23,2,0,0
67,Nicolas Jackson,Villarreal,162,9,0,0
68,Carlo Adriano García,Villarreal,9,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Atlético Madrid  —  SF sin salario:

             player  minutesPlayed
0     Carlos Martín              8
1  Giuliano Simeone              1
2      Javi Serrano             69
3       Saúl Ñíguez            200

  CG plantilla completa:

                player         player_norm
0         Ángel Correa        angel correa
1    Antoine Griezmann   antoine griezmann
2     Benjamin Lecomte    benjamin lecomte
3          Daniel Wass         daniel wass
4               Felipe              felipe
5    Francisco Montero   francisco montero
6   Geoffrey Kondogbia  geoffrey kondogbia
7       Héctor Herrera      hector herrera
8        Ivan Saponjic       ivan saponjic
9            Jan Oblak           jan oblak
10          João Félix          joao felix
11        José Giménez        jose gimenez
12     Kieran Trippier     kieran trippier
13                Koke                koke
14         Luis Suárez         luis suarez
15     Marcos Llorente     marcos llorente
16       Mario Hermoso       mario hermoso
17       Matheus Cunha       matheus cunha
18    Reinildo Mandava    reinildo mandava
19          Renan Lodi          renan lodi
20     Rodrigo de Paul     rodrigo de paul
21       Sime Vrsaljko       sime vrsaljko
22        Stefan Savic        stefan savic
23        Thomas Lemar        thomas lemar
24    Yannick Carrasco    yannick carrasco

============================================================
  Barcelona  —  SF sin salario:

                player  minutesPlayed
0        Emerson Royal             90
1      Estanis Pedrola             10
2       Ilias Akhomach            125
3          Mika Mármol              1
4  Álvaro Sanz Catalán             27

  CG plantilla completa:

                       player                player_norm
0             Abde Ezzalzouli            abde ezzalzouli
1                Adama Traoré               adama traore
2             Alejandro Balde            alejandro balde
3                Álex Collado               alex collado
4                   Ansu Fati                  ansu fati
5             Clément Lenglet            clement lenglet
6                  Dani Alves                 dani alves
7                 Eric García                eric garcia
8               Ferran Jutglà              ferran jutgla
9               Ferran Torres              ferran torres
10            Frenkie de Jong            frenkie de jong
11                       Gavi                       gavi
12               Gerard Piqué               gerard pique
13                 Iñaki Peña                 inaki pena
14                 Jordi Alba                 jordi alba
15               Luuk de Jong               luuk de jong
16      Marc-André ter Stegen      marc andre ter stegen
17         Martin Braithwaite         martin braithwaite
18              Memphis Depay              memphis depay
19               Moussa Wagué               moussa wague
20                       Neto                       neto
21              Nico González              nico gonzalez
22             Óscar Mingueza             oscar mingueza
23            Ousmane Dembélé            ousmane dembele
24                      Pedri                      pedri
25          Philippe Coutinho          philippe coutinho
26  Pierre-Emerick Aubameyang  pierre emerick aubameyang
27                 Riqui Puig                 riqui puig
28              Ronald Araújo              ronald araujo
29              Samuel Umtiti              samuel umtiti
30              Sergi Roberto              sergi roberto
31               Sergiño Dest               sergino dest
32              Sergio Agüero              sergio aguero
33            Sergio Busquets            sergio busquets
34                Yusuf Demir                yusuf demir

============================================================
  Celta Vigo  —  SF sin salario:

         player  minutesPlayed
0   Gabri Veiga            126
1   Hugo Sotelo              1
2  Hugo Álvarez             10

  CG plantilla completa:

              player       player_norm
0     Augusto Solari    augusto solari
1       Brais Méndez      brais mendez
2   Carlos Domínguez  carlos dominguez
3       Denis Suárez      denis suarez
4       Fran Beltrán      fran beltran
5       Franco Cervi      franco cervi
6         Hugo Mallo        hugo mallo
7         Iago Aspas        iago aspas
8         Javi Galán        javi galan
9     Jeison Murillo    jeison murillo
10       José Fontán       jose fontan
11      Joseph Aidoo      joseph aidoo
12     Kevin Vázquez     kevin vazquez
13     Matías Dituro     matias dituro
14      Miguel Baeza      miguel baeza
15     Néstor Araújo     nestor araujo
16            Nolito            nolito
17      Okay Yokuslu      okay yokuslu
18    Orbelín Pineda    orbelin pineda
19      Renato Tapia      renato tapia
20      Rubén Blanco      ruben blanco
21        Santi Mina        santi mina
22   Thiago Galhardo   thiago galhardo

============================================================
  Cádiz  —  SF sin salario:

         player  minutesPlayed
0  Pedro Benito             30
1    Raúl Parra             88

  CG plantilla completa:

                 player          player_norm
0         Alberto Perea        alberto perea
1        Álex Fernández       alex fernandez
2        Alfonso Espino       alfonso espino
3        Álvaro Bastida       alvaro bastida
4        Álvaro Jiménez       alvaro jimenez
5        Álvaro Negredo       alvaro negredo
6          Carlos Akapo         carlos akapo
7          Choco Lozano         choco lozano
8             David Gil            david gil
9                  Fali                 fali
10    Fede San Emeterio    fede san emeterio
11       Filip Malbasic       filip malbasic
12        Florin Andone        florin andone
13           Iván Alejo           ivan alejo
14         Ivan Chapela         ivan chapela
15         Iza Carcelén         iza carcelen
16         Jens Jönsson         jens jonsson
17     Jeremías Ledesma     jeremias ledesma
18    Jon Ander Garrido    jon ander garrido
19            José Mari            jose mari
20            Juan Cala            juan cala
21          Lucas Pérez          lucas perez
22       Luis Hernández       luis hernandez
23         Marcos Mauro         marcos mauro
24      Martín Calderón      martin calderon
25      Milutin Osmajic      milutin osmajic
26      Oussama Idrissi      oussama idrissi
27        Rubén Alcaraz        ruben alcaraz
28        Rubén Sobrino        ruben sobrino
29        Salvi Sánchez        salvi sanchez
30  Santiago Arzamendia  santiago arzamendia
31        Tomás Alarcón        tomas alarcon
32     Varazdat Haroyan     varazdat haroyan
33         Víctor Chust         victor chust

============================================================
  Deportivo Alavés  —  SF sin salario:

              player  minutesPlayed
0  Alberto Rodríguez            241
1   Alexandru Țîrlea             14
2        Jesús Owono             90
3         Marc Tenas             51
4       Tomás Mendes              8
5        Unai Ropero             11

  CG plantilla completa:

                   player            player_norm
0          Antonio Sivera         antonio sivera
1            Edgar Méndez           edgar mendez
2       Facundo Pellistri      facundo pellistri
3        Fernando Pacheco       fernando pacheco
4         Florian Lejeune        florian lejeune
5       Gonzalo Escalante      gonzalo escalante
6             Iván Martín            ivan martin
7                   Jason                  jason
8              Javi López             javi lopez
9           John Guidetti          john guidetti
10                 Joselu                 joselu
11             Luis Rioja             luis rioja
12           Mamadou Loum           mamadou loum
13          Mamadou Sylla          mamadou sylla
14            Manu García            manu garcia
15           Manu Vallejo           manu vallejo
16  Martín Aguirregabiria  martin aguirregabiria
17            Matt Miazga            matt miazga
18    Miguel de la Fuente    miguel de la fuente
19        Nahuel Tenaglia        nahuel tenaglia
20              Pere Pons              pere pons
21           Rubén Duarte           ruben duarte
22            Saúl García            saul garcia
23                  Tachi                  tachi
24             Tomás Pina             tomas pina
25              Toni Moya              toni moya
26       Víctor Laguardia       victor laguardia
27           Ximo Navarro           ximo navarro

============================================================
  Elche  —  SF sin salario:

        player  minutesPlayed
0  John Donald            180

  CG plantilla completa:

                 player          player_norm
0      Antonio Barragán     antonio barragan
1       Darío Benedetto      dario benedetto
2        Diego González       diego gonzalez
3           Édgar Badía          edgar badia
4             Enzo Roco            enzo roco
5        Ezequiel Ponce       ezequiel ponce
6                 Fidel                fidel
7         Gerard Gumbau        gerard gumbau
8         Gonzalo Verdú        gonzalo verdu
9        Guido Carrillo       guido carrillo
10  Helibelton Palacios  helibelton palacios
11         Iván Marcone         ivan marcone
12       Javier Pastore       javier pastore
13         Johan Mojica         johan mojica
14                Josan                josan
15               Josema               josema
16           Kike Pérez           kike perez
17         Kiko Casilla         kiko casilla
18           Lucas Boyé           lucas boye
19          Lucas Olaza          lucas olaza
20          Lucas Pérez          lucas perez
21       Omar Mascarell       omar mascarell
22         Pablo Piatti         pablo piatti
23          Pedro Bigas          pedro bigas
24           Pere Milla           pere milla
25            Raúl Guti            raul guti
26         Tete Morente         tete morente

============================================================
  Espanyol  —  SF sin salario:

                player  minutesPlayed
0  Daniel Villahermosa             22
1          Gori Gracia              8
2       Jofre Carreras             17
3       Lluís Recasens             45
4        Luca Koleosho              1
5        Rubén Sánchez            148
6         Victor Gómez              3

  CG plantilla completa:

             player      player_norm
0     Adrià Pedrosa    adria pedrosa
1    Adrián Embarba   adrian embarba
2       Aleix Vidal      aleix vidal
3    Álvaro Vadillo   alvaro vadillo
4       David López      david lopez
5        Dídac Vilà       didac vila
6       Diego López      diego lopez
7   Fernando Calero  fernando calero
8       Fran Mérida      fran merida
9        Javi Puado       javi puado
10      Joan García      joan garcia
11       Keidi Bare       keidi bare
12    Landry Dimata    landry dimata
13  Leandro Cabrera  leandro cabrera
14           Lei Wu           lei wu
15      Loren Morón      loren moron
16    Manu Morlanes    manu morlanes
17         Miguelón         miguelon
18     Nico Melamed     nico melamed
19    Oier Olazábal    oier olazabal
20        Óscar Gil        oscar gil
21    Óscar Melendo    oscar melendo
22    Raúl de Tomás    raul de tomas
23     Sergi Darder     sergi darder
24      Sergi Gómez      sergi gomez
25    Tonny Vilhena    tonny vilhena
26   Yangel Herrera   yangel herrera

============================================================
  Getafe  —  SF sin salario:

                   player  minutesPlayed
0  Amankwaa Akurugu Koffi             84
1          Marc Cucurella             22

  CG plantilla completa:

                player         player_norm
0           Allan Nyom          allan nyom
1        Borja Mayoral       borja mayoral
2         Carles Aleñá        carles alena
3                Chema               chema
4        Damián Suárez       damian suarez
5         Darío Poveda        dario poveda
6          David Soria         david soria
7          David Timor         david timor
8          Diego Conde         diego conde
9                Djené               djene
10           Enes Ünal           enes unal
11        Erick Cabaco        erick cabaco
12          Florentino          florentino
13      Gastón Álvarez      gaston alvarez
14      Gonzalo Villar      gonzalo villar
15          Jaime Mata          jaime mata
16        Jakub Jankto        jakub jankto
17      Jonathan Silva      jonathan silva
18        Jorge Cuenca        jorge cuenca
19         José Macías         jose macias
20      Josete Miranda      josete miranda
21       Juan Iglesias       juan iglesias
22     Mathías Olivera     mathias olivera
23     Mauro Arambarri     mauro arambarri
24  Nemanja Maksimovic  nemanja maksimovic
25        Okay Yokuslu        okay yokuslu
26     Óscar Rodríguez     oscar rodriguez
27         Rubén Yáñez         ruben yanez
28      Sandro Ramírez      sandro ramirez
29     Stefan Mitrovic     stefan mitrovic
30              Vitolo              vitolo

============================================================
  Granada  —  SF sin salario:

          player  minutesPlayed
0  Adrián Butzke              1
1  Sergio Barcia             77

  CG plantilla completa:

             player      player_norm
0   Aarón Escandell  aaron escandell
1      Alberto Soro     alberto soro
2      Álex Collado     alex collado
3     Ángel Montoro    angel montoro
4   Antonio Puertas  antonio puertas
5      Carlos Bacca     carlos bacca
6       Carlos Neva      carlos neva
7       Daniel Raba      daniel raba
8     Darwin Machís    darwin machis
9   Domingos Duarte  domingos duarte
10   Germán Sánchez   german sanchez
11        Isma Ruiz        isma ruiz
12       João Costa       joao costa
13     Jorge Molina     jorge molina
14       Luis Abram       luis abram
15   Luís Maximiano   luis maximiano
16       Luis Milla       luis milla
17      Luis Suárez      luis suarez
18     Matías Arezo     matias arezo
19  Maxime Gonalons  maxime gonalons
20           Monchu           monchu
21      Myrto Uzuni      myrto uzuni
22    Neyder Lozano    neyder lozano
23  Njegos Petrovic  njegos petrovic
24     Pepe Sánchez     pepe sanchez
25            Quini            quini
26    Raúl Torrente    raul torrente
27    Rubén Rochina    ruben rochina
28   Santiago Arias   santiago arias
29  Sergio Escudero  sergio escudero
30      Víctor Díaz      victor diaz
31        Yan Eteki        yan eteki

============================================================
  Levante UD  —  SF sin salario:

             player  minutesPlayed
0   Alejandro Primo             90
1  Marcelo Saracchi            186
2        Omar Faraj              9

  CG plantilla completa:

               player        player_norm
0     Aitor Fernández    aitor fernandez
1   Alejandro Cantero  alejandro cantero
2          Álex Blesa         alex blesa
3        Carlos Clerc       carlos clerc
4                Coke               coke
5       Dani Cárdenas      dani cardenas
6          Dani Gómez         dani gomez
7         Enis Bardhi        enis bardhi
8     Enric Franquesa    enric franquesa
9      Gonzalo Melero     gonzalo melero
10            Hernâni            hernani
11    Jorge de Frutos    jorge de frutos
12      Jorge Miramón      jorge miramon
13       José Campaña       jose campana
14  José Luis Morales  jose luis morales
15        Marc Pubill        marc pubill
16     Martín Cáceres     martin caceres
17      Mickaël Malsa      mickael malsa
18     Nemanja Radoja     nemanja radoja
19    Nikola Vukcevic    nikola vukcevic
20       Óscar Duarte       oscar duarte
21     Pablo Martínez     pablo martinez
22             Pepelu             pepelu
23         Rober Pier         rober pier
24    Roberto Soldado    roberto soldado
25        Roger Martí        roger marti
26         Rúben Vezo         ruben vezo
27     Sergio Postigo     sergio postigo
28   Shkodran Mustafi   shkodran mustafi
29                Son                son

============================================================
  Mallorca  —  SF sin salario:

            player  minutesPlayed
0  Clément Grenier             70
1     Javi Llabrés            135
2       Josep Gayá             59

  CG plantilla completa:

                     player              player_norm
0               Abdón Prats              abdon prats
1               Aleix Febas              aleix febas
2         Aleksandar Sedlar        aleksandar sedlar
3              Amath Ndiaye             amath ndiaye
4           Ángel Rodríguez          angel rodriguez
5            Antonio Raíllo           antonio raillo
6           Antonio Sánchez          antonio sanchez
7              Brian Oliván             brian olivan
8            Dani Rodríguez           dani rodriguez
9             Dominik Greif            dominik greif
10                 Fer Niño                 fer nino
11             Franco Russo             franco russo
12        Giovanni González        giovanni gonzalez
13             Iddrisu Baba             iddrisu baba
14  Iñigo Ruiz de Galarreta  inigo ruiz de galarreta
15              Jaume Costa              jaume costa
16              Joan Sastre              joan sastre
17             Jordi Mboula             jordi mboula
18              Kang-in Lee              kang in lee
19              Lago Júnior              lago junior
20                Leo Román                leo roman
21             Manolo Reina             manolo reina
22           Martin Valjent           martin valjent
23            Matthew Hoppe            matthew hoppe
24             Pablo Maffeo             pablo maffeo
25        Rodrigo Battaglia        rodrigo battaglia
26            Salva Sevilla            salva sevilla
27              Sergio Rico              sergio rico
28            Takefusa Kubo            takefusa kubo
29             Vedat Muriqi             vedat muriqi

============================================================
  Osasuna  —  SF sin salario:

        player  minutesPlayed
0  Iker Benito            116
1   Unai Dufur             90

  CG plantilla completa:

               player        player_norm
0        Ante Budimir       ante budimir
1   Aridane Hernández  aridane hernandez
2             Barbero            barbero
3         Chimy Ávila        chimy avila
4      Darko Brasanac     darko brasanac
5        David García       david garcia
6         Iñigo Pérez        inigo perez
7          Jaume Grau         jaume grau
8       Javi Martínez      javi martinez
9      Javi Ontiveros     javi ontiveros
10        Jesús Areso        jesus areso
11      Jon Moncayola      jon moncayola
12      Jonás Ramalho      jonas ramalho
13         José Ángel         jose angel
14          Juan Cruz          juan cruz
15         Juan Pérez         juan perez
16         Kike Barja         kike barja
17        Kike García        kike garcia
18        Lucas Torró        lucas torro
19       Manu Sánchez       manu sanchez
20        Nacho Vidal        nacho vidal
21               Oier               oier
22      Robert Ibáñez      robert ibanez
23     Roberto Torres     roberto torres
24       Rubén García       ruben garcia
25     Sergio Herrera     sergio herrera
26        Unai García        unai garcia

============================================================
  Rayo Vallecano  —  SF sin salario:

              player  minutesPlayed
0  Alejandro Asensio             12
1     Álvaro Aguirre              8

  CG plantilla completa:

                player         player_norm
0     Alejandro Catena    alejandro catena
1        Álvaro García       alvaro garcia
2        Andrés Martín       andres martin
3                 Bebé                bebe
4    Esteban Saveljich   esteban saveljich
5               Falcao              falcao
6          Fran García         fran garcia
7          Isi Palazón         isi palazon
8          Iván Balliu         ivan balliu
9            José Pozo           jose pozo
10     Kévin Rodrigues     kevin rodrigues
11         Luca Zidane         luca zidane
12       Mamadou Sylla       mamadou sylla
13     Mario Hernández     mario hernandez
14        Mario Suárez        mario suarez
15   Martín Merquelanz   martin merquelanz
16        Nikola Maras        nikola maras
17         Óscar Trejo         oscar trejo
18      Óscar Valentín      oscar valentin
19          Pathé Ciss          pathe ciss
20         Randy Nteka         randy nteka
21      Santi Comesaña      santi comesana
22     Sergi Guardiola     sergi guardiola
23       Sergio Moreno       sergio moreno
24  Stole Dimitrievski  stole dimitrievski
25          Unai López          unai lopez
26        Yacine Qasmi        yacine qasmi

============================================================
  Real Betis  —  SF sin salario:

                player  minutesPlayed
0        José Calderón             64
1         Kike Hermoso             90
2  Raúl García de Haro              1
3        Rodri Sánchez            886

  CG plantilla completa:

              player       player_norm
0       Aitor Ruibal      aitor ruibal
1        Álex Moreno       alex moreno
2    Andrés Guardado   andres guardado
3     Borja Iglesias    borja iglesias
4      Claudio Bravo     claudio bravo
5     Cristian Tello    cristian tello
6       Diego Lainez      diego lainez
7     Edgar González    edgar gonzalez
8    Germán Pezzella   german pezzella
9    Guido Rodríguez   guido rodriguez
10   Héctor Bellerín   hector bellerin
11           Joaquín           joaquin
12       Joel Robles       joel robles
13      Juan Miranda      juan miranda
14            Juanmi            juanmi
15       Marc Bartra       marc bartra
16    Martín Montoya    martin montoya
17       Nabil Fekir       nabil fekir
18     Paul Akouokou     paul akouokou
19    Rober González    rober gonzalez
20             Rodri             rodri
21         Rui Silva         rui silva
22    Sergio Canales    sergio canales
23   Víctor Camarasa   victor camarasa
24       Víctor Ruiz       victor ruiz
25  William Carvalho  william carvalho
26      Willian José      willian jose
27   Youssouf Sabaly   youssouf sabaly

============================================================
  Real Madrid  —  SF sin salario:

               player  minutesPlayed
0      Antonio Blanco             30
1       Juanmi Latasa              9
2  Mario Gila Fuentes             23
3      Peter González             37
4       Sergio Santos             10

  CG plantilla completa:

               player        player_norm
0        Andriy Lunin       andriy lunin
1            Casemiro           casemiro
2       Dani Ceballos      dani ceballos
3     Daniel Carvajal    daniel carvajal
4         David Alaba        david alaba
5         Eden Hazard        eden hazard
6        Éder Militão       eder militao
7   Eduardo Camavinga  eduardo camavinga
8   Federico Valverde  federico valverde
9       Ferland Mendy      ferland mendy
10        Gareth Bale        gareth bale
11               Isco               isco
12      Jesús Vallejo      jesus vallejo
13      Karim Benzema      karim benzema
14      Lucas Vázquez      lucas vazquez
15         Luka Jovic         luka jovic
16        Luka Modric        luka modric
17            Marcelo            marcelo
18      Marco Asensio      marco asensio
19       Mariano Díaz       mariano diaz
20   Miguel Gutiérrez   miguel gutierrez
21    Nacho Fernández    nacho fernandez
22            Rodrygo            rodrygo
23   Thibaut Courtois   thibaut courtois
24         Toni Kroos         toni kroos
25    Vinicius Junior    vinicius junior

============================================================
  Real Sociedad  —  SF sin salario:

          player  minutesPlayed
0   Ander Martín            108
1  Cristo Romero             16
2  Germán Valera             53
3   Jon Bautista             45
4  Naïs Djouahra            209
5      Álex Sola             39

  CG plantilla completa:

                player         player_norm
0        Adnan Januzaj       adnan januzaj
1          Aihen Muñoz         aihen munoz
2          Álex Remiro         alex remiro
3       Alexander Isak      alexander isak
4    Alexander Sörloth   alexander sorloth
5    Ander Barrenetxea   ander barrenetxea
6        Ander Guevara       ander guevara
7     Andoni Gorosabel    andoni gorosabel
8      Aritz Elustondo     aritz elustondo
9   Asier Illarramendi  asier illarramendi
10    Beñat Turrientes    benat turrientes
11    Carlos Fernández    carlos fernandez
12         David Silva         david silva
13          Diego Rico          diego rico
14       Igor Zubeldia       igor zubeldia
15          Jon Guridi          jon guridi
16         Jon Pacheco         jon pacheco
17       Joseba Zaldua       joseba zaldua
18        Julen Lobete        julen lobete
19    Martín Zubimendi    martin zubimendi
20         Mathew Ryan         mathew ryan
21        Mikel Merino        mikel merino
22     Mikel Oyarzabal     mikel oyarzabal
23       Nacho Monreal       nacho monreal
24               Portu               portu
25             Rafinha             rafinha
26      Robert Navarro      robert navarro
27    Robin Le Normand    robin le normand

============================================================
  Sevilla  —  SF sin salario:

               player  minutesPlayed
0  José Ángel Carmona             23
1      Juanlu Sánchez             11
2         Luismi Cruz             12
3         Pedro Ortiz             12
4   Valentino Fattore              1

  CG plantilla completa:

                 player          player_norm
0       Anthony Martial      anthony martial
1                  Bono                 bono
2          Diego Carlos         diego carlos
3           Erik Lamela          erik lamela
4              Fernando             fernando
5       Gonzalo Montiel      gonzalo montiel
6        Ibrahim Amadou       ibrahim amadou
7          Ivan Rakitic         ivan rakitic
8           Iván Romero          ivan romero
9             Javi Díaz            javi diaz
10         Jesús Corona         jesus corona
11          Jesús Navas          jesus navas
12          Joan Jordán          joan jordan
13        Joris Gnagnon        joris gnagnon
14         Jules Koundé         jules kounde
15          Karim Rekik          karim rekik
16        Lucas Ocampos        lucas ocampos
17  Ludwig Augustinsson  ludwig augustinsson
18         Marcos Acuña         marcos acuna
19      Marko Dmitrovic      marko dmitrovic
20     Munir El Haddadi     munir el haddadi
21       Nemanja Gudelj       nemanja gudelj
22        Óliver Torres        oliver torres
23      Óscar Rodríguez      oscar rodriguez
24      Oussama Idrissi      oussama idrissi
25           Papu Gómez           papu gomez
26             Rafa Mir             rafa mir
27                 Suso                 suso
28       Thomas Delaney       thomas delaney
29    Youssef En-Nesyri    youssef en nesyri

============================================================
  Valencia  —  SF sin salario:

               player  minutesPlayed
0  Cristhian Mosquera            220
1       Jesús Vázquez            819
2     Mario Domínguez             23
3        Rubén Iranzo            134
4      Yellu Santiago             81

  CG plantilla completa:

                  player           player_norm
0            Álex Blanco           alex blanco
1              Bryan Gil             bryan gil
2           Carlos Soler          carlos soler
3        Cristian Rivero       cristian rivero
4      Cristiano Piccini     cristiano piccini
5            Daniel Wass           daniel wass
6        Denis Cheryshev       denis cheryshev
7      Dimitri Foulquier     dimitri foulquier
8            Eray Cömert           eray comert
9       Gabriel Paulista      gabriel paulista
10  Giorgi Mamardashvili  giorgi mamardashvili
11        Gonçalo Guedes        goncalo guedes
12          Hélder Costa          helder costa
13             Hugo Duro             hugo duro
14        Hugo Guillamón        hugo guillamon
15          Ilaix Moriba          ilaix moriba
16                 Jason                 jason
17      Jasper Cillessen      jasper cillessen
18        Jaume Doménech        jaume domenech
19             José Gayà             jose gaya
20        Koba Koindredi        koba koindredi
21          Manu Vallejo          manu vallejo
22          Marcos André          marcos andre
23            Maxi Gómez            maxi gomez
24      Mouctar Diakhaby      mouctar diakhaby
25         Omar Alderete         omar alderete
26       Thierry Correia       thierry correia
27             Toni Lato             toni lato
28            Uros Racic            uros racic
29           Yunus Musah           yunus musah

============================================================
  Villarreal  —  SF sin salario:

                 player  minutesPlayed
0  Carlo Adriano García              9
1       Nicolas Jackson            162

  CG plantilla completa:

              player       player_norm
0        Aïssa Mandi       aissa mandi
1     Alberto Moreno    alberto moreno
2    Alfonso Pedraza   alfonso pedraza
3     Arnaut Danjuma    arnaut danjuma
4        Boulaye Dia       boulaye dia
5        Dani Parejo       dani parejo
6        Daniel Raba       daniel raba
7     Étienne Capoue    etienne capoue
8   Francis Coquelin  francis coquelin
9      Gerard Moreno     gerard moreno
10    Gerónimo Rulli    geronimo rulli
11  Giovani Lo Celso  giovani lo celso
12        Juan Foyth        juan foyth
13    Manu Trigueros    manu trigueros
14      Mario Gaspar      mario gaspar
15         Moi Gómez         moi gomez
16    Nikita Iosifov    nikita iosifov
17      Paco Alcácer      paco alcacer
18        Pau Torres        pau torres
19  Pervis Estupiñán  pervis estupinan
20       Raúl Albiol       raul albiol
21        Rubén Peña        ruben pena
22  Samuel Chukwueze  samuel chukwueze
23      Serge Aurier      serge aurier
24     Sergio Asenjo     sergio asenjo
25    Vicente Iborra    vicente iborra
26       Yeremi Pino       yeremi pino

In [23]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('rodri sanchez', 'real betis'): ('rodri', 'real betis'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [24]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: rodri sanchez (real betis) → rodri (real betis)

Tras matches manuales: 536/604 (88.7%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [25]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_spain_2122.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_spain_2122.csv
   Jugadores totales:  604
   Con salario:        536
   Sin salario (NaN):  68
   Columnas:           121