# 03 · Join Sofascore + Capology — Spain La Liga 20/21

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2020/21 de La Liga española**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_spain_2021.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_spain_2021.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  571 jugadores | 116 columnas
Capology:   545 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   deportivo alaves
   levante ud
   real valladolid

En Capology pero no en Sofascore:
   alaves
   levante
   valladolid

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'alaves':'deportivo alaves',
            'levante':'levante ud',
            'valladolid':'real valladolid'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 476/571 (83.4%)
Sin emparejar: 95

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          6
Revisión media    (0.75 ≤ score < 0.90):   10
Revisión estricta (0.50 ≤ score < 0.75):   52
Revisión muy est. (score < 0.50):           27

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

           player_sf         team         cg_match  score
28   Martin Ødegaard  Real Madrid  martin odegaard  0.966
24      Jens Jønsson        Cádiz     jens jonsson  0.957
15  Javier Ontiveros       Huesca   javi ontiveros  0.933
39    Manuel Sánchez      Osasuna     manu sanchez  0.923
16       Yéremy Pino   Villarreal      yeremi pino  0.909
48         Dani Raba   Villarreal      daniel raba  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

             player_sf             team          cg_match  score
34       Nico Williams    Athletic Club    inaki williams  0.815
76         Juan Carlos           Huesca  juan carlos real  0.815
7   José María Giménez  Atlético Madrid      jose gimenez  0.800
68   Waldo Rubio Marín  Real Valladolid       waldo rubio  0.786
17      José Luis Gayà         Valencia         jose gaya  0.783
36      Sergio Arribas      Real Madrid      sergio ramos  0.769
49       Fernando Niño       Villarreal          fer nino  0.762
82           Marc Baró            Cádiz      marcos mauro  0.762
25  Luis Javier Suárez          Granada       luis suarez  0.759
88                Koke       Levante UD              coke  0.750

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['nico williams',
                      'sergio arribas',
                      'marc baro'

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 7 | Excluidos: 3

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

              player_sf              team           cg_match  score
8     Maximiliano Gómez          Valencia         maxi gomez  0.741
1         Thomas Partey   Atlético Madrid       thomas lemar  0.720
27      Alejandro Baena        Villarreal         alex baena  0.720
52              Alberto             Cádiz      alberto perea  0.700
9         Emerson Royal        Real Betis            emerson  0.700
26       Papakouli Diop             Eibar          pape diop  0.696
41       Anthony Lozano             Cádiz       choco lozano  0.692
71       Ricard Sánchez   Atlético Madrid       manu sanchez  0.692
42      Sergio Carreira        Celta Vigo     sergio alvarez  0.690
90          Hugo Sotelo        Celta Vigo         hugo mallo  0.667
92          Álex Millán        Villarreal         alex baena  0.667
22        Javi Martínez           Osasuna     ruben martinez  0.667
5      Jonathan Carmona             Elche       johan mojica  0.643
66          Unai Arieta             Eibar     anaitz arbilla  0.640
91        Sergio Cubero             Eibar       sergi enrich  0.640
43      Roberto Jiménez   Real Valladolid            roberto  0.636
0         Ángel Jiménez           Granada      angel montoro  0.615
30          Marvin Park       Real Madrid    martin odegaard  0.615
74          John Donald             Elche       johan mojica  0.609
75          Javi Moyano   Real Valladolid       javi sanchez  0.609
64         Sergi García  Deportivo Alavés        manu garcia  0.609
35         Miguel Rubio   Real Valladolid        waldo rubio  0.609
69          Álex Martín             Cádiz          jose mari  0.600
93        Sergio Benito   Real Valladolid            roberto  0.600
70       Robert Navarro     Real Sociedad      roberto lopez  0.593
37    Francisco Trincão         Barcelona            trincao  0.583
63         Álvaro Bravo           Granada       alberto soro  0.583
62       Álvaro Bastida             Cádiz     alvaro negredo  0.571
86       Guillem Molina          Valencia     hugo guillamon  0.571
56               Quique             Eibar    quique gonzalez  0.571
50        Rodri Sánchez        Real Betis       diego lainez  0.560
55        Joaquín Muñoz            Huesca       damian musto  0.560
6                 Róber             Eibar      roberto olabe  0.556
59          Jose Fontán        Celta Vigo        jorge saenz  0.545
73        Daniel Plomer           Granada      angel montoro  0.538
67         Marc Cardona           Osasuna            brandon  0.526
29         Kuki Zalazar   Real Valladolid        lucas olaza  0.522
57           Dani Gómez        Levante UD      dani cardenas  0.522
72           Alex Blesa        Levante UD      mickael malsa  0.522
14        Juan Iglesias            Getafe     ante palaversa  0.519
77        Sabit Abdulai            Getafe     abdoulay diaby  0.519
47         Pablo Piatti             Elche    paulo gazzaniga  0.519
10        Álvaro Tejero             Eibar     alejandro pozo  0.519
2        Diego Llorente     Real Sociedad  ander barrenetxea  0.516
11       Antonio Blanco       Real Madrid         toni kroos  0.500
21     Carlos Domínguez        Celta Vigo       aaron martin  0.500
65       Josete Miranda            Getafe         jaime mata  0.500
40            Hugo Duro       Real Madrid            rodrygo  0.500
60     Facundo Ferreyra        Celta Vigo       fran beltran  0.500
38  Helibelton Palacios             Elche      jeison lucumi  0.500
45    Alberto Rodríguez  Deportivo Alavés        rodrigo ely  0.500
81            Isma Ruiz           Granada        luis suarez  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['maximiliano gomez',
                    'alejandro baena',
                    'alberto',
                    'emerson royal',
                    'papakouli diop',
                    'anthony lozano',
                    'roberto jimenez',
                    'francisco trincao',
                    'quique'
]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 9

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                     player_sf              team            cg_match  score
85             Aritz Arambarri     Real Sociedad  asier illarramendi  0.485
46              Miguel Atienza             Eibar     quique gonzalez  0.483
13            Vicente Esquerdo          Valencia       kevin gameiro  0.483
51               Urko González     Real Sociedad    carlos fernandez  0.483
61             Stephane Keller  Deportivo Alavés      jota peleteiro  0.483
44           Álejandro Cantero        Levante UD        carlos clerc  0.483
78              Koba Koindredi          Valencia         kang in lee  0.480
4                Sergio Barcia           Granada        adrian marin  0.480
31                   Oriol Rey   Real Valladolid        marcos andre  0.476
87                Eñaut Mendia             Eibar      paulo oliveira  0.462
20                Manuel Nieto             Cádiz      alvaro negredo  0.462
12                Ilaix Moriba         Barcelona          jordi alba  0.455
32                 Mamor Niang            Getafe         david soria  0.455
84      Amankwaa Akurugu Koffi            Getafe  nemanja maksimovic  0.450
33               Kingsley Fobi           Granada      domingos quina  0.444
83               Borja Mayoral       Real Madrid      raphael varane  0.444
80             Lautaro De León        Celta Vigo        aaron martin  0.444
58            Jordan Holsgrove        Celta Vigo         jorge saenz  0.444
53  Juan Ignacio Brunet Bordin           Granada     antonio puertas  0.439
94                 Ramón Folch             Elche        johan mojica  0.435
18                 Jon Pacheco     Real Sociedad        jon bautista  0.435
3                 Víctor Chust       Real Madrid    thibaut courtois  0.429
19              Alfon González        Celta Vigo      sergio alvarez  0.429
89                  Unai Dufur             Eibar      anaitz arbilla  0.417
54        Giorgi Kochorashvili        Levante UD      sergio postigo  0.412
23            Miguel Gutiérrez       Real Madrid     vinicius junior  0.387
79                John Patrick            Getafe      ante palaversa  0.385

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 498/571 (87.2%)
Sin salario:     73

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 73

,player,team,minutesPlayed,appearances,goals,assists
0,Nico Williams,Athletic Club,55,2,0,0
1,Thomas Partey,Atlético Madrid,199,3,0,0
2,Ricard Sánchez,Atlético Madrid,29,1,0,0
3,Ilaix Moriba,Barcelona,538,14,1,2
4,Jose Fontán,Celta Vigo,660,14,0,0
5,Carlos Domínguez,Celta Vigo,360,4,0,0
6,Facundo Ferreyra,Celta Vigo,313,13,1,0
7,Sergio Carreira,Celta Vigo,261,3,1,0
8,Jordan Holsgrove,Celta Vigo,141,5,0,0
9,Alfon González,Celta Vigo,32,2,0,0
10,Lautaro De León,Celta Vigo,13,1,0,0
11,Hugo Sotelo,Celta Vigo,1,1,0,0
12,Álex Martín,Cádiz,98,2,0,0
13,Marc Baró,Cádiz,90,1,0,0
14,Álvaro Bastida,Cádiz,34,1,0,0
15,Manuel Nieto,Cádiz,17,2,0,0
16,Alberto Rodríguez,Deportivo Alavés,847,12,0,0
17,Sergi García,Deportivo Alavés,16,2,0,0
18,Stephane Keller,Deportivo Alavés,15,1,0,0
19,Róber,Eibar,1138,15,0,2
20,Miguel Atienza,Eibar,837,12,0,0
21,Álvaro Tejero,Eibar,109,2,0,0
22,Unai Dufur,Eibar,63,1,0,0
23,Eñaut Mendia,Eibar,62,1,0,0
24,Unai Arieta,Eibar,50,4,0,0
25,Sergio Cubero,Eibar,1,1,0,0
26,Helibelton Palacios,Elche,746,11,0,0
27,Pablo Piatti,Elche,359,9,0,0
28,Jonathan Carmona,Elche,74,1,0,0
29,John Donald,Elche,55,2,0,0
30,Ramón Folch,Elche,1,1,0,0
31,Juan Iglesias,Getafe,614,10,0,0
32,John Patrick,Getafe,72,6,0,0
33,Sabit Abdulai,Getafe,62,3,0,0
34,Amankwaa Akurugu Koffi,Getafe,45,1,0,0
35,Josete Miranda,Getafe,28,4,0,0
36,Mamor Niang,Getafe,21,1,0,0
37,Ángel Jiménez,Granada,90,1,0,0
38,Sergio Barcia,Granada,90,1,0,0
39,Isma Ruiz,Granada,67,1,0,0
40,Kingsley Fobi,Granada,45,1,0,0
41,Daniel Plomer,Granada,45,1,0,0
42,Juan Ignacio Brunet Bordin,Granada,24,2,0,0
43,Álvaro Bravo,Granada,14,1,0,0
44,Joaquín Muñoz,Huesca,47,3,0,0
45,Dani Gómez,Levante UD,1664,34,2,2
46,Álejandro Cantero,Levante UD,239,4,0,0
47,Giorgi Kochorashvili,Levante UD,22,3,0,0
48,Alex Blesa,Levante UD,10,1,0,0
49,Javi Martínez,Osasuna,470,13,1,1
50,Marc Cardona,Osasuna,50,3,0,0
51,Rodri Sánchez,Real Betis,538,15,0,0
52,Miguel Gutiérrez,Real Madrid,314,6,0,1
53,Antonio Blanco,Real Madrid,218,4,0,0
54,Marvin Park,Real Madrid,132,4,0,1
55,Sergio Arribas,Real Madrid,131,8,0,0
56,Víctor Chust,Real Madrid,94,2,0,0
57,Hugo Duro,Real Madrid,53,2,0,0
58,Borja Mayoral,Real Madrid,21,2,0,0
59,Diego Llorente,Real Sociedad,90,1,0,0
60,Urko González,Real Sociedad,46,2,0,0
61,Robert Navarro,Real Sociedad,34,1,0,0
62,Jon Pacheco,Real Sociedad,31,1,0,0
63,Aritz Arambarri,Real Sociedad,25,1,0,0
64,Miguel Rubio,Real Valladolid,135,2,0,0
65,Javi Moyano,Real Valladolid,104,2,0,0
66,Kuki Zalazar,Real Valladolid,28,2,0,1
67,Oriol Rey,Real Valladolid,14,1,0,0
68,Sergio Benito,Real Valladolid,1,1,0,0
69,Vicente Esquerdo,Valencia,233,4,0,0
70,Guillem Molina,Valencia,153,2,0,0
71,Koba Koindredi,Valencia,20,2,0,0
72,Álex Millán,Villarreal,1,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Athletic Club  —  SF sin salario:

          player  minutesPlayed
0  Nico Williams             55

  CG plantilla completa:

              player       player_norm
0     Álex Berenguer    alex berenguer
1         Ander Capa        ander capa
2   Asier Villalibre  asier villalibre
3        Dani García       dani garcia
4      Iago Herrerín     iago herrerin
5         Ibai Gómez        ibai gomez
6       Iker Muniain      iker muniain
7     Iñaki Williams    inaki williams
8      Iñigo Córdoba     inigo cordoba
9        Iñigo Lekue       inigo lekue
10    Iñigo Martínez    inigo martinez
11     Iñigo Vicente     inigo vicente
12     Jokin Ezkieta     jokin ezkieta
13      Jon Morcillo      jon morcillo
14       Kenan Kodro       kenan kodro
15  Mikel Balenziaga  mikel balenziaga
16       Mikel Vesga       mikel vesga
17      Oier Zarraga      oier zarraga
18      Oihan Sancet      oihan sancet
19   Óscar de Marcos   oscar de marcos
20   Peru Nolaskoain   peru nolaskoain
21       Raúl García       raul garcia
22        Unai López        unai lopez
23        Unai Núñez        unai nunez
24        Unai Simón        unai simon
25     Unai Vencedor     unai vencedor
26     Yeray Álvarez     yeray alvarez
27    Yuri Berchiche    yuri berchiche

============================================================
  Atlético Madrid  —  SF sin salario:

           player  minutesPlayed
0  Ricard Sánchez             29
1   Thomas Partey            199

  CG plantilla completa:

                player         player_norm
0         Ángel Correa        angel correa
1          Diego Costa         diego costa
2               Felipe              felipe
3   Geoffrey Kondogbia  geoffrey kondogbia
4       Héctor Herrera      hector herrera
5            Ivo Grbic           ivo grbic
6            Jan Oblak           jan oblak
7           João Félix          joao felix
8         José Giménez        jose gimenez
9      Kieran Trippier     kieran trippier
10                Koke                koke
11      Lucas Torreira      lucas torreira
12         Luis Suárez         luis suarez
13        Manu Sánchez        manu sanchez
14     Marcos Llorente     marcos llorente
15       Mario Hermoso       mario hermoso
16    Miguel San Román    miguel san roman
17      Moussa Dembélé      moussa dembele
18          Renan Lodi          renan lodi
19         Saúl Ñíguez         saul niguez
20       Sime Vrsaljko       sime vrsaljko
21        Stefan Savic        stefan savic
22        Thomas Lemar        thomas lemar
23              Vitolo              vitolo
24    Yannick Carrasco    yannick carrasco

============================================================
  Barcelona  —  SF sin salario:

         player  minutesPlayed
0  Ilaix Moriba            538

  CG plantilla completa:

                   player            player_norm
0               Ansu Fati              ansu fati
1       Antoine Griezmann      antoine griezmann
2             Arnau Tenas            arnau tenas
3            Carles Aleñá           carles alena
4         Clément Lenglet        clement lenglet
5         Frenkie de Jong        frenkie de jong
6            Gerard Piqué           gerard pique
7              Iñaki Peña             inaki pena
8              Jordi Alba             jordi alba
9            Júnior Firpo           junior firpo
10    Konrad de la Fuente    konrad de la fuente
11           Lionel Messi           lionel messi
12  Marc-André ter Stegen  marc andre ter stegen
13     Martin Braithwaite     martin braithwaite
14      Matheus Fernandes      matheus fernandes
15         Miralem Pjanic         miralem pjanic
16           Moussa Wagué           moussa wague
17                   Neto                   neto
18         Óscar Mingueza         oscar mingueza
19        Ousmane Dembélé        ousmane dembele
20                  Pedri                  pedri
21      Philippe Coutinho      philippe coutinho
22             Riqui Puig             riqui puig
23          Ronald Araújo          ronald araujo
24          Samuel Umtiti          samuel umtiti
25      Santi Ramos Mingo      santi ramos mingo
26          Sergi Roberto          sergi roberto
27           Sergiño Dest           sergino dest
28        Sergio Busquets        sergio busquets
29                Trincão                trincao

============================================================
  Celta Vigo  —  SF sin salario:

             player  minutesPlayed
0    Alfon González             32
1  Carlos Domínguez            360
2  Facundo Ferreyra            313
3       Hugo Sotelo              1
4  Jordan Holsgrove            141
5       Jose Fontán            660
6   Lautaro De León             13
7   Sergio Carreira            261

  CG plantilla completa:

              player       player_norm
0       Aarón Martín      aaron martin
1     Augusto Solari    augusto solari
2       Brais Méndez      brais mendez
3       David Costas      david costas
4        David Juncà       david junca
5       Denis Suárez      denis suarez
6           Emre Mor          emre mor
7       Fran Beltrán      fran beltran
8        Gabri Veiga       gabri veiga
9         Hugo Mallo        hugo mallo
10        Iago Aspas        iago aspas
11       Iván Villar       ivan villar
12    Jeison Murillo    jeison murillo
13       Jorge Sáenz       jorge saenz
14      Joseph Aidoo      joseph aidoo
15     Kevin Vázquez     kevin vazquez
16       Lucas Olaza       lucas olaza
17      Miguel Baeza      miguel baeza
18  Miguel Rodríguez  miguel rodriguez
19     Néstor Araújo     nestor araujo
20            Nolito            nolito
21      Okay Yokuslu      okay yokuslu
22      Renato Tapia      renato tapia
23      Rubén Blanco      ruben blanco
24        Santi Mina        santi mina
25    Sergio Álvarez    sergio alvarez

============================================================
  Cádiz  —  SF sin salario:

           player  minutesPlayed
0    Manuel Nieto             17
1       Marc Baró             90
2     Álex Martín             98
3  Álvaro Bastida             34

  CG plantilla completa:

               player        player_norm
0       Alberto Perea      alberto perea
1      Álex Fernández     alex fernandez
2      Alfonso Espino     alfonso espino
3      Álvaro Giménez     alvaro gimenez
4      Álvaro Negredo     alvaro negredo
5   Augusto Fernández  augusto fernandez
6      Bobby Adekanye     bobby adekanye
7        Carlos Akapo       carlos akapo
8        Choco Lozano       choco lozano
9           David Gil          david gil
10               Fali               fali
11     Filip Malbašić     filip malbasic
12         Iván Alejo         ivan alejo
13      Ivan Saponjic      ivan saponjic
14       Iza Carcelén       iza carcelen
15    Jairo Izquierdo    jairo izquierdo
16       Jens Jönsson       jens jonsson
17   Jeremías Ledesma   jeremias ledesma
18  Jon Ander Garrido  jon ander garrido
19        Jorge Pombo        jorge pombo
20          José Mari          jose mari
21          Juan Cala          juan cala
22     Luismi Quezada     luismi quezada
23       Marcos Mauro       marcos mauro
24          Nano Mesa          nano mesa
25       Pedro Alcalá       pedro alcala
26      Rubén Sobrino      ruben sobrino
27      Salvi Sánchez      salvi sanchez
28    Sergio González    sergio gonzalez
29       Yann Bodiger       yann bodiger

============================================================
  Deportivo Alavés  —  SF sin salario:

              player  minutesPlayed
0  Alberto Rodríguez            847
1       Sergi García             16
2    Stephane Keller             15

  CG plantilla completa:

                   player            player_norm
0       Abdallahi Mahmoud      abdallahi mahmoud
1            Adrián Marín           adrian marin
2          Antonio Sivera         antonio sivera
3             Borja Sainz            borja sainz
4                  Burgui                 burgui
5               Deyverson              deyverson
6            Edgar Méndez           edgar mendez
7       Facundo Pellistri      facundo pellistri
8        Fernando Pacheco       fernando pacheco
9         Florian Lejeune        florian lejeune
10          Iñigo Córdoba          inigo cordoba
11             Javi López             javi lopez
12          John Guidetti          john guidetti
13                 Joselu                 joselu
14         Jota Peleteiro         jota peleteiro
15            Lucas Pérez            lucas perez
16             Luis Rioja             luis rioja
17            Manu García            manu garcia
18  Martín Aguirregabiria  martin aguirregabiria
19              Pere Pons              pere pons
20      Rodrigo Battaglia      rodrigo battaglia
21            Rodrigo Ely            rodrigo ely
22           Rubén Duarte           ruben duarte
23                  Tachi                  tachi
24             Tomás Pina             tomas pina
25          Tomás Tavares          tomas tavares
26       Víctor Laguardia       victor laguardia
27           Ximo Navarro           ximo navarro

============================================================
  Eibar  —  SF sin salario:

           player  minutesPlayed
0    Eñaut Mendia             62
1  Miguel Atienza            837
2           Róber           1138
3   Sergio Cubero              1
4     Unai Arieta             50
5      Unai Dufur             63
6   Álvaro Tejero            109

  CG plantilla completa:

                   player            player_norm
0            Aleix García           aleix garcia
1          Alejandro Pozo         alejandro pozo
2          Anaitz Arbilla         anaitz arbilla
3               Bryan Gil              bryan gil
4          Damian Kadzior         damian kadzior
5            Edu Expósito           edu exposito
6          Esteban Burgos         esteban burgos
7              José Ángel             jose angel
8   José Antonio Martínez  jose antonio martinez
9         Kévin Rodrigues        kevin rodrigues
10            Kike García            kike garcia
11        Marko Dmitrovic        marko dmitrovic
12              Pape Diop              pape diop
13         Paulo Oliveira         paulo oliveira
14            Pedro Bigas            pedro bigas
15             Pedro León             pedro leon
16        Quique González        quique gonzalez
17            Rafa Soares            rafa soares
18                  Recio                  recio
19         Roberto Correa         roberto correa
20          Roberto Olabe          roberto olabe
21           Sergi Enrich           sergi enrich
22         Sergio Álvarez         sergio alvarez
23           Takashi Inui           takashi inui
24         Yoel Rodríguez         yoel rodriguez
25         Yoshinori Muto         yoshinori muto

============================================================
  Elche  —  SF sin salario:

                player  minutesPlayed
0  Helibelton Palacios            746
1          John Donald             55
2     Jonathan Carmona             74
3         Pablo Piatti            359
4          Ramón Folch              1

  CG plantilla completa:

               player        player_norm
0    Antonio Barragán   antonio barragan
1          Dani Calvo         dani calvo
2      Diego González     diego gonzalez
3     Diego Rodríguez    diego rodriguez
4         Edgar Badia        edgar badia
5     Emiliano Rigoni    emiliano rigoni
6               Fidel              fidel
7       Gonzalo Verdú      gonzalo verdu
8      Guido Carrillo     guido carrillo
9        Iván Marcone       ivan marcone
10      Jeison Lucumí      jeison lucumi
11       Johan Mojica       johan mojica
12              Josan              josan
13             Josema             josema
14  Juan Sánchez Miño  juan sanchez mino
15         Lucas Boyé         lucas boye
16             Luismi             luismi
17   Miguel Cifuentes   miguel cifuentes
18               Nino               nino
19      Omenuke Mfulu      omenuke mfulu
20    Paulo Gazzaniga    paulo gazzaniga
21         Pere Milla         pere milla
22          Raúl Guti          raul guti
23       Tete Morente       tete morente
24   Víctor Rodríguez   victor rodriguez
25      Youssouf Koné      youssouf kone

============================================================
  Getafe  —  SF sin salario:

                   player  minutesPlayed
0  Amankwaa Akurugu Koffi             45
1            John Patrick             72
2          Josete Miranda             28
3           Juan Iglesias            614
4             Mamor Niang             21
5           Sabit Abdulai             62

  CG plantilla completa:

                player         player_norm
0       Abdoulay Diaby      abdoulay diaby
1           Allan Nyom          allan nyom
2      Ángel Rodríguez     angel rodriguez
3       Ante Palaversa      ante palaversa
4         Carles Aleñá        carles alena
5                Chema               chema
6      Cucho Hernández     cucho hernandez
7        Damián Suárez       damian suarez
8         Darío Poveda        dario poveda
9          David Soria         david soria
10         David Timor         david timor
11               Djené               djene
12           Enes Ünal           enes unal
13        Erick Cabaco        erick cabaco
14  Francisco Portillo  francisco portillo
15          Jaime Mata          jaime mata
16  Leandro Chichizola  leandro chichizola
17      Marc Cucurella      marc cucurella
18     Mathías Olivera     mathias olivera
19     Mauro Arambarri     mauro arambarri
20  Nemanja Maksimovic  nemanja maksimovic
21         Rubén Yáñez         ruben yanez
22     Soufiane Chakla     soufiane chakla
23       Takefusa Kubo       takefusa kubo
24      Víctor Mollejo      victor mollejo
25      Xabier Etxeita      xabier etxeita

============================================================
  Granada  —  SF sin salario:

                       player  minutesPlayed
0               Daniel Plomer             45
1                   Isma Ruiz             67
2  Juan Ignacio Brunet Bordin             24
3               Kingsley Fobi             45
4               Sergio Barcia             90
5                Álvaro Bravo             14
6               Ángel Jiménez             90

  CG plantilla completa:

               player        player_norm
0     Aarón Escandell    aaron escandell
1        Adrián Marín       adrian marin
2        Alberto Soro       alberto soro
3       Ángel Montoro      angel montoro
4     Antonio Puertas    antonio puertas
5         Carlos Neva        carlos neva
6       Darwin Machís      darwin machis
7   Dimitri Foulquier  dimitri foulquier
8     Domingos Duarte    domingos duarte
9      Domingos Quina     domingos quina
10          Fede Vico          fede vico
11     Germán Sánchez     german sanchez
12      Jesús Vallejo      jesus vallejo
13       Jorge Molina       jorge molina
14             Kenedy             kenedy
15         Luis Milla         luis milla
16        Luis Suárez        luis suarez
17    Maxime Gonalons    maxime gonalons
18       Nehuén Pérez       nehuen perez
19      Neyder Lozano      neyder lozano
20       Pepe Sánchez       pepe sanchez
21              Quini              quini
22        Ramon Azeez        ramon azeez
23    Roberto Soldado    roberto soldado
24          Rui Silva          rui silva
25        Víctor Díaz        victor diaz
26          Yan Eteki          yan eteki
27     Yangel Herrera     yangel herrera

============================================================
  Huesca  —  SF sin salario:

          player  minutesPlayed
0  Joaquín Muñoz             47

  CG plantilla completa:

               player        player_norm
0    Álvaro Fernández   alvaro fernandez
1    Andrés Fernández   andres fernandez
2      Antonio Valera     antonio valera
3        Borja García       borja garcia
4        Damián Musto       damian musto
5       Dani Escriche      dani escriche
6      David Ferreiro     david ferreiro
7         Denis Vavro        denis vavro
8    Dimitrios Siovas   dimitrios siovas
9   Eugeni Valderrama  eugeni valderrama
10       Gastón Silva       gaston silva
11    Idrissa Doumbia    idrissa doumbia
12       Jaime Seoane       jaime seoane
13         Javi Galán         javi galan
14     Javi Ontiveros     javi ontiveros
15       Jorge Pulido       jorge pulido
16   Juan Carlos Real   juan carlos real
17    Kelechi Nwakali    kelechi nwakali
18           Luisinho           luisinho
19         Mikel Rico         mikel rico
20        Pablo Insua        pablo insua
21       Pablo Maffeo       pablo maffeo
22        Pedro López        pedro lopez
23     Pedro Mosquera     pedro mosquera
24           Rafa Mir           rafa mir
25     Sandro Ramírez     sandro ramirez
26       Sergio Gómez       sergio gomez
27     Shinji Okazaki     shinji okazaki

============================================================
  Levante UD  —  SF sin salario:

                 player  minutesPlayed
0            Alex Blesa             10
1            Dani Gómez           1664
2  Giorgi Kochorashvili             22
3     Álejandro Cantero            239

  CG plantilla completa:

               player        player_norm
0     Aitor Fernández    aitor fernandez
1        Carlos Clerc       carlos clerc
2     Cheick Doukouré    cheick doukoure
3                Coke               coke
4       Dani Cárdenas      dani cardenas
5      Edgar Sevikyan     edgar sevikyan
6         Enis Bardhi        enis bardhi
7      Gonzalo Melero     gonzalo melero
8     Jorge de Frutos    jorge de frutos
9       Jorge Miramón      jorge miramon
10       José Campaña       jose campana
11  José Luis Morales  jose luis morales
12         Koke Vegas         koke vegas
13      Mickaël Malsa      mickael malsa
14     Nemanja Radoja     nemanja radoja
15    Nikola Vukcevic    nikola vukcevic
16       Óscar Duarte       oscar duarte
17         Rober Pier         rober pier
18        Roger Martí        roger marti
19      Rubén Rochina      ruben rochina
20         Rúben Vezo         ruben vezo
21        Sergio León        sergio leon
22     Sergio Postigo     sergio postigo
23                Son                son
24               Toño               tono

============================================================
  Osasuna  —  SF sin salario:

          player  minutesPlayed
0  Javi Martínez            470
1   Marc Cardona             50

  CG plantilla completa:

               player        player_norm
0        Adrián López       adrian lopez
1        Ante Budimir       ante budimir
2   Aridane Hernández  aridane hernandez
3             Brandon            brandon
4         Chimy Ávila        chimy avila
5      Darko Brasanac     darko brasanac
6        David García       david garcia
7       Enric Gallego      enric gallego
8   Facundo Roncaglia  facundo roncaglia
9         Iñigo Pérez        inigo perez
10      Jon Moncayola      jon moncayola
11      Jonás Ramalho      jonas ramalho
12   Jonathan Calleri   jonathan calleri
13               Jony               jony
14          Juan Cruz          juan cruz
15         Juan Pérez         juan perez
16         Kike Barja         kike barja
17        Lucas Torró        lucas torro
18       Manu Sánchez       manu sanchez
19        Nacho Vidal        nacho vidal
20               Oier               oier
21         Raúl Navas         raul navas
22     Roberto Torres     roberto torres
23       Rubén García       ruben garcia
24     Rubén Martínez     ruben martinez
25     Sergio Herrera     sergio herrera
26        Unai García        unai garcia

============================================================
  Real Betis  —  SF sin salario:

          player  minutesPlayed
0  Rodri Sánchez            538

  CG plantilla completa:

              player       player_norm
0        Aïssa Mandi       aissa mandi
1       Aitor Ruibal      aitor ruibal
2        Álex Moreno       alex moreno
3    Andrés Guardado   andres guardado
4   Antonio Sanabria  antonio sanabria
5     Borja Iglesias    borja iglesias
6      Claudio Bravo     claudio bravo
7     Cristian Tello    cristian tello
8        Dani Martín       dani martin
9       Diego Lainez      diego lainez
10           Emerson           emerson
11   Guido Rodríguez   guido rodriguez
12           Joaquín           joaquin
13       Joel Robles       joel robles
14      Juan Miranda      juan miranda
15            Juanmi            juanmi
16       Loren Morón       loren moron
17       Marc Bartra       marc bartra
18    Martín Montoya    martin montoya
19       Nabil Fekir       nabil fekir
20     Paul Akouokou     paul akouokou
21             Rodri             rodri
22    Sergio Canales    sergio canales
23            Sidnei            sidnei
24   Víctor Camarasa   victor camarasa
25       Víctor Ruiz       victor ruiz
26  William Carvalho  william carvalho
27      Yassin Fekir      yassin fekir

============================================================
  Real Madrid  —  SF sin salario:

             player  minutesPlayed
0    Antonio Blanco            218
1     Borja Mayoral             21
2         Hugo Duro             53
3       Marvin Park            132
4  Miguel Gutiérrez            314
5    Sergio Arribas            131
6      Víctor Chust             94

  CG plantilla completa:

               player        player_norm
0    Álvaro Odriozola   alvaro odriozola
1        Andriy Lunin       andriy lunin
2            Casemiro           casemiro
3     Daniel Carvajal    daniel carvajal
4         Eden Hazard        eden hazard
5        Éder Militão       eder militao
6   Federico Valverde  federico valverde
7       Ferland Mendy      ferland mendy
8                Isco               isco
9       Karim Benzema      karim benzema
10      Lucas Vázquez      lucas vazquez
11         Luka Jovic         luka jovic
12        Luka Modric        luka modric
13            Marcelo            marcelo
14      Marco Asensio      marco asensio
15       Mariano Díaz       mariano diaz
16    Martin Ödegaard    martin odegaard
17    Nacho Fernández    nacho fernandez
18     Raphaël Varane     raphael varane
19            Rodrygo            rodrygo
20       Sergio Ramos       sergio ramos
21   Thibaut Courtois   thibaut courtois
22         Toni Kroos         toni kroos
23    Vinícius Júnior    vinicius junior

============================================================
  Real Sociedad  —  SF sin salario:

            player  minutesPlayed
0  Aritz Arambarri             25
1   Diego Llorente             90
2      Jon Pacheco             31
3   Robert Navarro             34
4    Urko González             46

  CG plantilla completa:

                player         player_norm
0        Adnan Januzaj       adnan januzaj
1          Aihen Muñoz         aihen munoz
2          Álex Remiro         alex remiro
3            Alex Sola           alex sola
4       Alexander Isak      alexander isak
5    Ander Barrenetxea   ander barrenetxea
6        Ander Guevara       ander guevara
7     Andoni Gorosabel    andoni gorosabel
8      Aritz Elustondo     aritz elustondo
9   Asier Illarramendi  asier illarramendi
10    Carlos Fernández    carlos fernandez
11         David Silva         david silva
12       Igor Zubeldia       igor zubeldia
13        Jon Bautista        jon bautista
14          Jon Guridi          jon guridi
15       Joseba Zaldua       joseba zaldua
16       Luca Sangalli       luca sangalli
17   Martín Merquelanz   martin merquelanz
18    Martín Zubimendi    martin zubimendi
19   Miguel Ángel Moyá   miguel angel moya
20        Mikel Merino        mikel merino
21     Mikel Oyarzabal     mikel oyarzabal
22       Modibo Sagnan       modibo sagnan
23       Nacho Monreal       nacho monreal
24               Portu               portu
25       Roberto López       roberto lopez
26    Robin Le Normand    robin le normand
27        Willian José        willian jose

============================================================
  Real Valladolid  —  SF sin salario:

          player  minutesPlayed
0    Javi Moyano            104
1   Kuki Zalazar             28
2   Miguel Rubio            135
3      Oriol Rey             14
4  Sergio Benito              1

  CG plantilla completa:

               player        player_norm
0      Bruno González     bruno gonzalez
1     Fabián Orellana    fabian orellana
2   Fede San Emeterio  fede san emeterio
3        Javi Sánchez       javi sanchez
4      Jawad El Yamiq     jawad el yamiq
5   Joaquín Fernández  joaquin fernandez
6         Jordi Masip        jordi masip
7                Jota               jota
8         Kenan Kodro        kenan kodro
9          Kike Pérez         kike perez
10        Kiko Olivas        kiko olivas
11        Lucas Olaza        lucas olaza
12         Luis Pérez         luis perez
13       Marcos André       marcos andre
14     Míchel Herrero     michel herrero
15     Nacho Martínez     nacho martinez
16        Óscar Plano        oscar plano
17      Pablo Hervías      pablo hervias
18       Raúl Carnero       raul carnero
19            Roberto            roberto
20         Roque Mesa         roque mesa
21      Rubén Alcaraz      ruben alcaraz
22        Saidy Janko        saidy janko
23    Sergi Guardiola    sergi guardiola
24      Shon Weissman      shon weissman
25       Stiven Plaza       stiven plaza
26         Toni Villa         toni villa
27        Waldo Rubio        waldo rubio

============================================================
  Valencia  —  SF sin salario:

             player  minutesPlayed
0    Guillem Molina            153
1    Koba Koindredi             20
2  Vicente Esquerdo            233

  CG plantilla completa:

                player         player_norm
0          Álex Blanco         alex blanco
1         Carlos Soler        carlos soler
2      Christian Oliva     christian oliva
3      Cristian Rivero     cristian rivero
4    Cristiano Piccini   cristiano piccini
5          Daniel Wass         daniel wass
6      Denis Cheryshev     denis cheryshev
7     Eliaquim Mangala    eliaquim mangala
8                Ferro               ferro
9     Gabriel Paulista    gabriel paulista
10  Geoffrey Kondogbia  geoffrey kondogbia
11      Gonçalo Guedes      goncalo guedes
12      Hugo Guillamón      hugo guillamon
13               Jason               jason
14    Jasper Cillessen    jasper cillessen
15      Jaume Doménech      jaume domenech
16           José Gayà           jose gaya
17         Kang-in Lee         kang in lee
18       Kévin Gameiro       kevin gameiro
19        Manu Vallejo        manu vallejo
20          Maxi Gómez          maxi gomez
21    Mouctar Diakhaby    mouctar diakhaby
22     Patrick Cutrone     patrick cutrone
23       Rubén Sobrino       ruben sobrino
24     Thierry Correia     thierry correia
25           Toni Lato           toni lato
26          Uros Racic          uros racic
27         Yunus Musah         yunus musah

============================================================
  Villarreal  —  SF sin salario:

        player  minutesPlayed
0  Álex Millán              1

  CG plantilla completa:

               player        player_norm
0      Alberto Moreno     alberto moreno
1          Álex Baena         alex baena
2     Alfonso Pedraza    alfonso pedraza
3        Carlos Bacca       carlos bacca
4         Dani Parejo        dani parejo
5         Daniel Raba        daniel raba
6      Étienne Capoue     etienne capoue
7            Fer Niño           fer nino
8    Francis Coquelin   francis coquelin
9       Gerard Moreno      gerard moreno
10     Gerónimo Rulli     geronimo rulli
11        Jaume Costa        jaume costa
12         Juan Foyth         juan foyth
13     Manu Trigueros     manu trigueros
14       Mario Gaspar       mario gaspar
15          Moi Gómez          moi gomez
16       Paco Alcácer       paco alcacer
17         Pau Torres         pau torres
18   Pervis Estupiñán   pervis estupinan
19  Ramiro Funes Mori  ramiro funes mori
20        Raúl Albiol        raul albiol
21         Rubén Peña         ruben pena
22   Samuel Chukwueze   samuel chukwueze
23   Santiago Cáseres   santiago caseres
24      Sergio Asenjo      sergio asenjo
25    Soufiane Chakla    soufiane chakla
26      Takefusa Kubo      takefusa kubo
27     Vicente Iborra     vicente iborra
28        Yeremi Pino        yeremi pino

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('rodri sanchez', 'real betis'): ('rodri', 'real betis'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: rodri sanchez (real betis) → rodri (real betis)

Tras matches manuales: 499/571 (87.4%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [21]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_spain_2021.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_spain_2021.csv
   Jugadores totales:  571
   Con salario:        499
   Sin salario (NaN):  72
   Columnas:           121