# 03 · Join Sofascore + Capology — Turkiye Super Lig 25/26 (snapshot 20260428)

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2025/26 de la Süper Lig turca**.

⚠️ **Nota sobre el snapshot:** la temporada 25/26 está aún en curso. Se trabaja con
una foto fija de Sofascore (`df_turkey_2526_snapshot_20260428.csv`). Este notebook
deberá reejecutarse con los datos definitivos cuando finalice la liga, generando
entonces el master sin sufijo de fecha (`master_turkey_2526.csv`).

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_turkey_2526_snapshot_20260428.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_turkey_2526.csv').copy()

print(f'Sofascore (snapshot):  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:              {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore (snapshot):  547 jugadores | 117 columnas
Capology:              526 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   basaksehir fk
   besiktas jk
   fatih karagumruk
   gaziantep fk
   genclerbirligi
   kasmpasa

En Capology pero no en Sofascore:
   basaksehir
   besiktas
   gaziantep bb
   genclerbirligi sk
   karagumrukspor
   kasimpasa

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [7]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'basaksehir':'basaksehir fk',
            'besiktas':'besiktas jk',
            'gaziantep bb':'gaziantep fk',
            'genclerbirligi sk':'genclerbirligi',
            'karagumrukspor':'fatih karagumruk',
            'kasimpasa':'kasmpasa'


}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [8]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 394/547 (72.0%)
Sin emparejar: 153

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [9]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          24
Revisión media    (0.75 ≤ score < 0.90):   20
Revisión estricta (0.50 ≤ score < 0.75):   53
Revisión muy est. (score < 0.50):           56

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [10]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf              team             cg_match  score
44         Sofyan Amrabat        Fenerbahçe       sofyan amrabat  1.000
81      Dominik Livaković        Fenerbahçe    dominik livakovic  1.000
3     Abdulkerim Bardakci       Galatasaray   abdulkerim bardakc  0.973
9       Ertugrul Taskiran        Alanyaspor     ertugrul taskran  0.970
22       Kacper Kozłowski      Gaziantep FK     kacper kozlowski  0.968
26        Dimitris Goutas    Gençlerbirliği     dimitrios goutas  0.968
47        Georgi Dzhikiya       Antalyaspor     georgiy dzhikiya  0.968
73       Mateusz Łęgowski          Eyüpspor     mateusz legowski  0.968
66       Taylan Antalyali   Çaykur Rizespor      taylan antalyal  0.968
35       Jakub Kałuziński     Başakşehir FK     jakub kaluzinski  0.968
57       Talha Sariarslan       Kayserispor      talha sararslan  0.968
148       Kerem Kayaarasi       Antalyaspor       kerem kayaaras  0.966
10          Samet Akaydın   Çaykur Rizespor        samet akaydin  0.960
49          Nazim Sangare      Gaziantep FK         nazm sangare  0.960
75          Firatcan Üzüm    Gençlerbirliği         fratcan uzum  0.960
25          Ramzi Safouri       Antalyaspor         ramzi safuri  0.960
107          Meschak Elia        Alanyaspor        meschack elia  0.960
11          Bilal Bayazit       Kayserispor         bilal bayazt  0.960
65           Taskin Ilter          Eyüpspor          taskn ilter  0.957
53           Amine Cherni           Göztepe          amin cherni  0.957
133  Tarik Bugra Kalpakli  Fatih Karagümrük   tark bugra kalpakl  0.947
72     Husniddin Aliqulov   Çaykur Rizespor  khusniddin alikulov  0.919
93          Baris Kalayci  Fatih Karagümrük          bars kalayc  0.917
41            Emre Kilinc        Samsunspor            emre klnc  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [11]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

,player_sf,team,cg_match,score
36,Bahadır Han Güngördü,Konyaspor,bahadr gungordu,0.882
58,Anfernee Jamal Dijksteel,Kocaelispor,anfernee dijksteel,0.857
31,Serginho,Fatih Karagümrük,sergio,0.857
43,Ege Yildirim,Göztepe,ege yldrm,0.857
136,Deniz Eren Dönmezer,Kayserispor,deniz donmezer,0.848
28,Baran Ali Gezek,Eyüpspor,baran gezek,0.846
132,Taylan Utku Aydın,Kasımpaşa,taylan aydn,0.815
103,Habib Gueye,Kasımpaşa,pape habib gueye,0.815
38,Kamil Corekci,Kasımpaşa,kamil ahmet corekci,0.812
77,Tayyip Talha Sanuç,Gaziantep FK,tayyip sanuc,0.800
40,Kartal Kayra Yılmaz,Beşiktaş JK,kartal ylmaz,0.800
20,Berat Ayberk Özdemir,Başakşehir FK,berat ozdemir,0.788
51,Ali Diabaté,Samsunspor,ali badra diabate,0.786
67,Hasan Yakub İlçin,Antalyaspor,yakub ilcin,0.786
152,Mücahit Ibrahimoglu,Konyaspor,melih ibrahimoglu,0.778
23,Wilfried Singo,Galatasaray,wilfried stephane singo,0.757
76,Josafat Mendes,Samsunspor,joe mendes,0.750
90,Mathias Løvik,Trabzonspor,mathias fjrtoft lvik,0.750
14,Ruan,Göztepe,juan,0.750
105,Adama Malouda Traoré,Gençlerbirliği,adama traore,0.750

In [12]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['ruan'

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 19 | Excluidos: 1

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [13]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                   player_sf              team                 cg_match  score
59              Amir Murillo       Beşiktaş JK          michael murillo  0.741
27               Eren Elmalı       Galatasaray        evren eren elmali  0.741
96         Mehmet Eray Özbek       Kayserispor               eray ozbek  0.741
78               Burak Bozan      Gaziantep FK      mustafa burak bozan  0.733
54    Muhammet Tunahan Taşçı         Konyaspor             tunahan tasc  0.727
62          Ismail Esat Buga         Konyaspor                esat buga  0.720
7         Barış Alper Yılmaz       Galatasaray             baris yilmaz  0.714
2                 Rafa Silva       Beşiktaş JK               jota silva  0.700
100  Gidado Victor Ntino-Emo      Gaziantep FK  victor ntino emo gidado  0.696
86             Michał Nalepa    Gençlerbirliği             emirhan unal  0.667
63                 Jo Jin-ho         Konyaspor                jin ho jo  0.667
12               Peter Etebo    Gençlerbirliği         oghenekaro etebo  0.667
113            Soner Aydoğdu        Samsunspor              soner gonul  0.667
102     Seyfettin Anıl Yaşar          Eyüpspor                anl yasar  0.643
126                 Frimpong         Kasımpaşa        godfried frimpong  0.640
34                     Allan           Göztepe              allan godoi  0.625
140         Oleksandr Syrota       Kocaelispor     aleksandar jovanovic  0.611
118              Kaan Akyazı         Konyaspor            rayyan baniya  0.609
74               Ryan Mendes       Kocaelispor                can keles  0.600
91           Sinan Osmanoğlu    Gençlerbirliği          ensar kemaloglu  0.600
1                   Emersonn           Göztepe                janderson  0.588
87             Serdar Saatçı       Trabzonspor             stefan savic  0.583
108             Danylo Sikan       Trabzonspor             boran baskan  0.583
82                Berke Özer          Eyüpspor          bedirhan ozyurt  0.560
119             Melih Bostan         Konyaspor        melih ibrahimoglu  0.552
79              Cem Üstündag         Kasımpaşa               cenk tosun  0.545
33             Halil Akbunar          Eyüpspor                anl yasar  0.545
45             David Jurásek       Beşiktaş JK            devis vasquez  0.538
16         Jesurun Rak-Sakyi   Çaykur Rizespor            emir ortakaya  0.533
115             Dilhan Demir    Gençlerbirliği       abdullah sahindere  0.533
50              Atakan Mujde         Kasımpaşa              taylan aydn  0.522
127             Gokhan Akkan    Gençlerbirliği              cihan canak  0.522
94            Tarkan Serbest       Kocaelispor                can keles  0.522
144             Arif Kocaman       Kayserispor              carlos mane  0.522
135       Aaron Appindangoyé       Kocaelispor                dan agyei  0.519
122           Salem Bouajila           Göztepe            malcom bokele  0.519
61           Ousmane Diabate    Gençlerbirliği            moussa kyabou  0.500
150               Mete Demir          Eyüpspor               umut meras  0.500
17             Alassane Ndao         Konyaspor          sander svendsen  0.500
15                João Mário       Beşiktaş JK               al musrati  0.500
18                Jhon Durán        Fenerbahçe           anthony musaba  0.500
48            Jonas Svensson       Beşiktaş JK               jota silva  0.500
55           Danijel Aleksić         Konyaspor            josip calusic  0.500
52       Sebastian Szymański        Fenerbahçe        mert hakan yandas  0.500
70               Ahmed Ildız           Göztepe           guilherme luiz  0.500
88             Jure Balkovec  Fatih Karagümrük          furkan beklevic  0.500
71            Atakan Çankaya  Fatih Karagümrük       tark bugra kalpakl  0.500
114         Ömer Faruk Beyaz     Başakşehir FK         omer ali sahiner  0.500
147                Samu Sáiz          Eyüpspor              umut keseci  0.500
146           Haydar Karataş        Fenerbahçe           sofyan amrabat  0.500
109            Ismaila Manga          Eyüpspor              talha ulvan  0.500
97               Cihat Celik       Kocaelispor                can keles  0.500
98                 Yaw Ackah       Kayserispor              kayra cihan  0.500

In [14]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['amir murillo',
                    'eren elmal',
                    'mehmet eray ozbek',
                    'burak bozan',
                    'muhammet tunahan tasc',
                    'ismail esat buga',
                    'bars alper ylmaz',
                    'gidado victor ntino emo',
                    'jo jin ho',
                    'peter etebo',
                    'seyfettin anl yasar',
                    'frimpong',
                    'allan'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 13

### 7.4 Revisión muy estricta (score < 0.50)

Candidatos con muy baja similitud. Por defecto ninguno se acepta.
Añadir a `ACCEPT_VERY_LOW_FUZZY` los que se confirmen manualmente.

In [15]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                   player_sf              team             cg_match  score
24        David Datro Fofana  Fatih Karagümrük      davide biraschi  0.485
149           Ali Demirbilek       Antalyaspor      berkay topdemir  0.483
46             Enver Kulašin      Gaziantep FK     kacper kozlowski  0.483
141              Gideon Jung       Kayserispor       german onugkha  0.480
106           Tomáš Čvančara       Antalyaspor          kagan arcan  0.480
142              Yusuf Demir       Galatasaray       lucas torreira  0.480
19          Demir Ege Tıknaz       Beşiktaş JK           emir yasar  0.480
21              Robin Yalcin          Eyüpspor        dorin rotariu  0.480
101         Ogulcan Caglayan       Kocaelispor            dan agyei  0.480
112               Andre Gray  Fatih Karagümrük      davide biraschi  0.480
32       Ruan Pereira Duarte        Alanyaspor          bruno viana  0.467
30               Nany Dimata        Samsunspor  irfan can egribayat  0.467
60      Serkan Emrecan Terzi       Beşiktaş JK           al musrati  0.467
124         Emmanuel Boateng      Gaziantep FK       salem m bakata  0.467
131         Mesut Can Tunalı       Kocaelispor          samet yalcn  0.462
5           Gabriel Paulista       Beşiktaş JK           al musrati  0.462
89             Jhon Espinoza         Kasımpaşa        jim allevinah  0.462
64      Marius Mouandilmadji        Samsunspor               marius  0.462
84             Alper Demirol  Fatih Karagümrük        daniele verde  0.462
42             Tammy Abraham       Beşiktaş JK        milot rashica  0.462
129  Muhammed-Cham Saračević       Trabzonspor         stefan savic  0.457
128        Marius Tresor Doh  Fatih Karagümrük   matias kranevitter  0.457
4                Güray Vural       Antalyaspor          kagan arcan  0.455
39               Svit Sešlar          Eyüpspor          taskn ilter  0.455
123             Mamadou Fall         Kasımpaşa           adem arous  0.455
68               Hwang Ui-Jo        Alanyaspor          ui jo hwang  0.455
13          Sokratis Dioudis      Gaziantep FK      kevin rodrigues  0.452
8                  Enzo Roco  Fatih Karagümrük            ivo grbic  0.444
138               Arda Ozyar       Kocaelispor    serhat oztasdelen  0.444
111            Andraž Šporar        Alanyaspor       baran mogultay  0.444
85                  Abdou Sy          Eyüpspor           arda yavuz  0.444
110            Serdar Gürler          Eyüpspor       jerome onguene  0.444
116            Batista Mendy       Trabzonspor       taha emre ince  0.444
29      Juan Santos da Silva           Göztepe         furkan malak  0.438
37         Youssef En-Nesyri        Fenerbahçe      yigit efe demir  0.438
125       Muzaffer Utku Eriş         Konyaspor       marko jevtovic  0.438
99               Mert Yilmaz       Antalyaspor         soner dikmen  0.435
0               Deniz Dilmen     Başakşehir FK          davie selke  0.435
121               Ali Karimi       Kayserispor        denis makarov  0.435
56              Badou Ndiaye      Gaziantep FK          arda kzldag  0.435
80            Uchenna Ogundu        Alanyaspor       buluthan bulut  0.429
120      Poyraz Efe Yıldırım       Antalyaspor         ramzi safuri  0.429
143         Ömer Faruk Gümüş  Fatih Karagümrük         tugbey akgun  0.429
137        Berk Can Yildizli         Kasımpaşa     berkay muratoglu  0.424
139     Nikoloz Ugrekhelidze  Fatih Karagümrük        daniele verde  0.424
117              Aaron Opoku       Kayserispor        furkan soyalp  0.417
134              Mirza Cihan      Gaziantep FK        drissa camara  0.417
130              Daniel Popa    Gençlerbirliği        franco tongya  0.417
145          Alexander Djiku        Fenerbahçe       caglar soyuncu  0.414
6              Yusuf Akçiçek        Fenerbahçe    irfan can kahveci  0.400
95            Vaclav Jurecka   Çaykur Rizespor          casper hjer  0.400
69                Mame Thiam          Eyüpspor           umut meras  0.400
151           Tibet Durakcay           Göztepe          furkan bayr  0.400
83                 Rob Nizet      Gaziantep FK         ogun ozcicek  0.381
104             Polat Yaldır        Samsunspor           zeki yavru  0.381
92             Kevin Csoboth    Gençlerbirliği     oghenekaro etebo  0.345

In [16]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = ['marius mouandilmadji',
                         'hwang ui jo'

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 2

### 7.5 Aplicar todos los fuzzy matches aceptados

In [17]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 450/547 (82.3%)
Sin salario:     97

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [18]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 97

,player,team,minutesPlayed,appearances,goals,assists
0,Ruan Pereira Duarte,Alanyaspor,2072,26,1,1
1,Uchenna Ogundu,Alanyaspor,993,17,2,1
2,Andraž Šporar,Alanyaspor,165,2,0,0
3,Tomáš Čvančara,Antalyaspor,533,11,1,0
4,Güray Vural,Antalyaspor,277,4,2,0
5,Poyraz Efe Yıldırım,Antalyaspor,180,10,0,0
6,Mert Yilmaz,Antalyaspor,36,3,0,0
7,Ali Demirbilek,Antalyaspor,1,1,0,0
8,Deniz Dilmen,Başakşehir FK,90,1,0,0
9,Ömer Faruk Beyaz,Başakşehir FK,30,3,0,0
10,Tammy Abraham,Beşiktaş JK,1258,18,7,1
11,Gabriel Paulista,Beşiktaş JK,865,10,0,1
12,Rafa Silva,Beşiktaş JK,820,10,5,1
13,David Jurásek,Beşiktaş JK,637,10,0,0
14,Jonas Svensson,Beşiktaş JK,353,5,0,0
15,Demir Ege Tıknaz,Beşiktaş JK,321,10,0,1
16,João Mário,Beşiktaş JK,105,2,0,0
17,Serkan Emrecan Terzi,Beşiktaş JK,20,1,0,0
18,Robin Yalcin,Eyüpspor,1631,19,0,0
19,Serdar Gürler,Eyüpspor,1288,17,0,0
20,Mame Thiam,Eyüpspor,1182,14,2,0
21,Svit Sešlar,Eyüpspor,564,10,1,1
22,Halil Akbunar,Eyüpspor,513,12,2,0
23,Berke Özer,Eyüpspor,90,1,0,0
24,Abdou Sy,Eyüpspor,26,3,0,0
25,Ismaila Manga,Eyüpspor,26,3,0,0
26,Samu Sáiz,Eyüpspor,1,1,0,0
27,Mete Demir,Eyüpspor,1,1,0,0
28,Atakan Çankaya,Fatih Karagümrük,1530,17,1,1
29,Jure Balkovec,Fatih Karagümrük,1513,17,0,0
30,Marius Tresor Doh,Fatih Karagümrük,1024,17,0,0
31,David Datro Fofana,Fatih Karagümrük,983,13,6,0
32,Enzo Roco,Fatih Karagümrük,576,7,0,0
33,Andre Gray,Fatih Karagümrük,539,12,0,0
34,Nikoloz Ugrekhelidze,Fatih Karagümrük,187,4,0,0
35,Alper Demirol,Fatih Karagümrük,82,3,0,0
36,Ömer Faruk Gümüş,Fatih Karagümrük,72,2,0,0
37,Youssef En-Nesyri,Fenerbahçe,1008,16,7,0
38,Jhon Durán,Fenerbahçe,543,10,3,2
39,Sebastian Szymański,Fenerbahçe,446,14,1,0
40,Sofyan Amrabat,Fenerbahçe,102,2,0,0
41,Yusuf Akçiçek,Fenerbahçe,90,1,0,0
42,Dominik Livaković,Fenerbahçe,90,1,0,0
43,Alexander Djiku,Fenerbahçe,1,1,0,0
44,Haydar Karataş,Fenerbahçe,1,1,0,0
45,Yusuf Demir,Galatasaray,28,1,0,0
46,Emmanuel Boateng,Gaziantep FK,466,11,1,0
47,Badou Ndiaye,Gaziantep FK,431,12,0,1
48,Enver Kulašin,Gaziantep FK,132,5,0,0
49,Sokratis Dioudis,Gaziantep FK,23,1,0,0
50,Mirza Cihan,Gaziantep FK,23,3,0,0
51,Rob Nizet,Gaziantep FK,20,2,0,0
52,Gokhan Akkan,Gençlerbirliği,360,4,0,0
53,Michał Nalepa,Gençlerbirliği,262,3,0,0
54,Dilhan Demir,Gençlerbirliği,106,6,0,0
55,Ousmane Diabate,Gençlerbirliği,90,1,0,0
56,Sinan Osmanoğlu,Gençlerbirliği,72,7,0,0
57,Daniel Popa,Gençlerbirliği,68,1,0,0
58,Kevin Csoboth,Gençlerbirliği,52,5,0,0
59,Juan Santos da Silva,Göztepe,2320,29,10,4
60,Emersonn,Göztepe,124,3,1,0
61,Ruan,Göztepe,114,2,0,0
62,Ahmed Ildız,Göztepe,63,7,0,0
63,Salem Bouajila,Göztepe,20,4,0,0
64,Tibet Durakcay,Göztepe,1,1,0,0
65,Mamadou Fall,Kasımpaşa,1181,20,0,0
66,Cem Üstündag,Kasımpaşa,949,18,0,0
67,Jhon Espinoza,Kasımpaşa,558,10,0,0
68,Atakan Mujde,Kasımpaşa,167,6,0,1
69,Berk Can Yildizli,Kasımpaşa,11,1,0,0
70,Aaron Opoku,Kayserispor,1235,19,0,2
71,Gideon Jung,Kayserispor,305,4,0,0
72,Arif Kocaman,Kayserispor,228,5,0,0
73,Yaw Ackah,Kayserispor,185,3,0,0
74,Ali Karimi,Kayserispor,39,2,0,0
75,Oleksandr Syrota,Kocaelispor,372,6,0,0
76,Aaron Appindangoyé,Kocaelispor,315,4,0,0
77,Ryan Mendes,Kocaelispor,273,4,0,0
78,Tarkan Serbest,Kocaelispor,244,6,0,0
79,Ogulcan Caglayan,Kocaelispor,196,4,0,0
80,Mesut Can Tunalı,Kocaelispor,45,1,0,0
81,Arda Ozyar,Kocaelispor,20,1,0,0
82,Cihat Celik,Kocaelispor,19,2,0,0
83,Alassane Ndao,Konyaspor,798,11,2,3
84,Danijel Aleksić,Konyaspor,198,3,1,0
85,Muzaffer Utku Eriş,Konyaspor,157,3,0,0
86,Melih Bostan,Konyaspor,122,10,0,0
87,Kaan Akyazı,Konyaspor,34,5,0,0
88,Nany Dimata,Samsunspor,132,2,0,0
89,Soner Aydoğdu,Samsunspor,113,8,0,0
90,Polat Yaldır,Samsunspor,108,6,0,0
91,Danylo Sikan,Trabzonspor,251,13,1,0
92,Serdar Saatçı,Trabzonspor,185,3,0,0
93,Batista Mendy,Trabzonspor,56,2,0,0
94,Muhammed-Cham Saračević,Trabzonspor,11,1,0,0
95,Jesurun Rak-Sakyi,Çaykur Rizespor,817,11,4,1
96,Vaclav Jurecka,Çaykur Rizespor,479,12,1,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [19]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Alanyaspor  —  SF sin salario:

                player  minutesPlayed
0        Andraž Šporar            165
1  Ruan Pereira Duarte           2072
2       Uchenna Ogundu            993

  CG plantilla completa:

                 player          player_norm
0        Baran Moğultay       baran mogultay
1         Batuhan Yavuz        batuhan yavuz
2           Bruno Viana          bruno viana
3        Buluthan Bulut       buluthan bulut
4         Efecan Karaca        efecan karaca
5           Enes Keskin          enes keskin
6     Ertuğrul Taşkıran     ertugrul taskran
7           Fatih Aksoy          fatih aksoy
8           Fidan Aliti          fidan aliti
9   Florent Hadergjonaj  florent hadergjonaj
10        Gaius Makouta        gaius makouta
11         Güven Yalçın          guven yalcn
12           Ianis Hagi           ianis hagi
13         İbrahim Kaya         ibrahim kaya
14          İzzet Çelik          izzet celik
15              Maestro              maestro
16        Meschack Elia        meschack elia
17      Nicolas Janvier      nicolas janvier
18            Nuno Lima            nuno lima
19         Paulo Victor         paulo victor
20                 Ruan                 ruan
21         Steve Mounié         steve mounie
22          Ui-jo Hwang          ui jo hwang
23           Ümit Akdağ           umit akdag
24  Yusuf Can Karademir  yusuf can karademir
25        Yusuf Özdemir        yusuf ozdemir

============================================================
  Antalyaspor  —  SF sin salario:

                player  minutesPlayed
0       Ali Demirbilek              1
1          Güray Vural            277
2          Mert Yilmaz             36
3  Poyraz Efe Yıldırım            180
4       Tomáš Čvančara            533

  CG plantilla completa:

                  player           player_norm
0        Abdülkadir Ömür       abdulkadir omur
1       Abdullah Yiğiter      abdullah yigiter
2           Bachir Gueye          bachir gueye
3         Bahadır Öztürk         bahadr ozturk
4        Berkay Topdemir       berkay topdemir
5         Bünyamin Balcı         bunyamin balc
6            Dario Saric           dario saric
7          Doğukan Sinik         dogukan sinik
8            Ege İzmirli           ege izmirli
9     Ensar Buğra Tivsiz    ensar bugra tivsiz
10     Erdoğan Yeşilyurt     erdogan yesilyurt
11      Georgiy Dzhikiya      georgiy dzhikiya
12       Hüseyin Türkmen       huseyin turkmen
13         Jesper Ceesay         jesper ceesay
14         Julián Cuesta         julian cuesta
15          Kağan Arıcan           kagan arcan
16          Kenneth Paal          kenneth paal
17       Kerem Kayaarası        kerem kayaaras
18     Lautaro Giannetti     lautaro giannetti
19          Nikola Storm          nikola storm
20          Ramzi Safuri          ramzi safuri
21         Samet Karakoç         samet karakoc
22         Samuel Ballet         samuel ballet
23  Sander van de Streek  sander van de streek
24          Soner Dikmen          soner dikmen
25           Veysel Sarı            veysel sar
26           Yakub İlçin           yakub ilcin
27            Yohan Boli            yohan boli

============================================================
  Başakşehir FK  —  SF sin salario:

             player  minutesPlayed
0      Deniz Dilmen             90
1  Ömer Faruk Beyaz             30

  CG plantilla completa:

                 player          player_norm
0   Abbosbek Fayzullaev  abbosbek fayzullaev
1           Amine Harit          amine harit
2         Berat Özdemir        berat ozdemir
3          Berkay Aslan         berkay aslan
4       Bertuğ Yıldırım         bertug yldrm
5     Christopher Operi    christopher operi
6           Davie Selke          davie selke
7         Doğan Alemdar        dogan alemdar
8      Eldor Shomurodov     eldor shomurodov
9         Festy Ebosele        festy ebosele
10        Hamza Güreler        hamza gureler
11           Ivan Brnic           ivan brnic
12     Jakub Kaluzinski     jakub kaluzinski
13         Jerome Opoku         jerome opoku
14     Kazımcan Karataş      kazmcan karatas
15           Léo Duarte           leo duarte
16         Luca Stancic         luca stancic
17        Miguel Crespo        miguel crespo
18    Muhammed Şengezer    muhammed sengezer
19        Nuno Da Costa        nuno da costa
20        Olivier Kemen        olivier kemen
21     Ömer Ali Şahiner     omer ali sahiner
22           Onur Bulut           onur bulut
23           Onur Ergün           onur ergun
24         Ousseynou Ba         ousseynou ba
25           Umut Güneş           umut gunes
26       Volkan Babacan       volkan babacan
27           Yusuf Sarı            yusuf sar

============================================================
  Beşiktaş JK  —  SF sin salario:

                 player  minutesPlayed
0         David Jurásek            637
1      Demir Ege Tıknaz            321
2      Gabriel Paulista            865
3        Jonas Svensson            353
4            João Mário            105
5            Rafa Silva            820
6  Serkan Emrecan Terzi             20
7         Tammy Abraham           1258

  CG plantilla completa:

               player        player_norm
0          Al Musrati         al musrati
1        Cengiz Ünder       cengiz under
2       Devis Vásquez      devis vasquez
3        Devrim Şahin       devrim sahin
4      El Bilal Touré     el bilal toure
5          Emir Yaşar         emir yasar
6       Emirhan Topçu      emirhan topcu
7    Emmanuel Agbadou   emmanuel agbadou
8         Emre Bilgin        emre bilgin
9    Ersin Destanoğlu   ersin destanoglu
10     Felix Uduokhai     felix uduokhai
11     Gökhan Sazdağı      gokhan sazdag
12       Hyeon-gyu Oh       hyeon gyu oh
13         Jean Onana         jean onana
14         Jota Silva         jota silva
15     Junior Olaitan     junior olaitan
16      Kartal Yılmaz       kartal ylmaz
17   Kristjan Asllani   kristjan asllani
18    Michael Murillo    michael murillo
19      Milot Rashica      milot rashica
20  Mustafa Hekimoğlu  mustafa hekimoglu
21        Necip Uysal        necip uysal
22        Orkun Kökçü        orkun kokcu
23      Rıdvan Yılmaz        rdvan ylmaz
24         Salih Uçan         salih ucan
25       Taylan Bulut       taylan bulut
26        Tiago Djaló        tiago djalo
27       Vaclav Cerny       vaclav cerny
28      Wilfred Ndidi      wilfred ndidi
29        Yasin Özcan        yasin ozcan

============================================================
  Eyüpspor  —  SF sin salario:

          player  minutesPlayed
0       Abdou Sy             26
1     Berke Özer             90
2  Halil Akbunar            513
3  Ismaila Manga             26
4     Mame Thiam           1182
5     Mete Demir              1
6   Robin Yalcin           1631
7      Samu Sáiz              1
8  Serdar Gürler           1288
9    Svit Sešlar            564

  CG plantilla completa:

                    player             player_norm
0             Ángel Torres            angel torres
1               Anıl Yaşar               anl yasar
2               Arda Yavuz              arda yavuz
3              Baran Gezek             baran gezek
4          Bedirhan Özyurt         bedirhan ozyurt
5                 Calegari                calegari
6   Charles-André Raux-Yao  charles andre raux yao
7             Christ Sadia            christ sadia
8               Denis Radu              denis radu
9            Dorin Rotariu           dorin rotariu
10             Emre Akbaba             emre akbaba
11           Gilbert Mendy           gilbert mendy
12           Jankat Yılmaz            jankat ylmaz
13          Jérôme Onguéné          jerome onguene
14            Lenny Pintor            lenny pintor
15            Luccas Claro            luccas claro
16           Marcos Felipe           marcos felipe
17        Mateusz Legowski        mateusz legowski
18        Metehan Altunbaş        metehan altunbas
19    Mustafa Yiğit Durmaz    mustafa yigit durmaz
20            Prince Ampem            prince ampem
21             Talha Ülvan             talha ulvan
22        Taras Stepanenko        taras stepanenko
23            Taşkın İlter             taskn ilter
24              Umut Bozok              umut bozok
25             Umut Keseci             umut keseci
26              Umut Meraş              umut meras

============================================================
  Fatih Karagümrük  —  SF sin salario:

                 player  minutesPlayed
0         Alper Demirol             82
1            Andre Gray            539
2        Atakan Çankaya           1530
3    David Datro Fofana            983
4             Enzo Roco            576
5         Jure Balkovec           1513
6     Marius Tresor Doh           1024
7  Nikoloz Ugrekhelidze            187
8      Ömer Faruk Gümüş             72

  CG plantilla completa:

                     player              player_norm
0   Abdul Kader Moussa Kone  abdul kader moussa kone
1              Ahmed Traore             ahmed traore
2               Ahmet Sivri              ahmet sivri
3          Anıl Yiğit Çınar           anl yigit cnar
4             Barış Kalaycı              bars kalayc
5              Bartuğ Elmaz             bartug elmaz
6              Berkay Özcan             berkay ozcan
7            Berke Can Evli           berke can evli
8              Burhan Ersoy             burhan ersoy
9          Çağtay Kurukalıp          cagtay kurukalp
10           Daniel Johnson           daniel johnson
11            Daniele Verde            daniele verde
12          Davide Biraschi          davide biraschi
13            Fatih Kurucuk            fatih kurucuk
14         Filip Mladenovic         filip mladenovic
15          Furkan Bekleviç          furkan beklevic
16          Igor Lichnovsky          igor lichnovsky
17                Ivo Grbic                ivo grbic
18             João Camacho             joao camacho
19             Kerem Yandal             kerem yandal
20       Matías Kranevitter       matias kranevitter
21        Muhammed Kadıoğlu         muhammed kadoglu
22           Ricardo Esgaio           ricardo esgaio
23              Sam Larsson              sam larsson
24                   Sergio                   sergio
25            Shavy Babicka            shavy babicka
26     Tarık Buğra Kalpaklı       tark bugra kalpakl
27              Tiago Çukur              tiago cukur
28             Tuğbey Akgün             tugbey akgun
29               Yaya Onogo               yaya onogo

============================================================
  Fenerbahçe  —  SF sin salario:

                player  minutesPlayed
0      Alexander Djiku              1
1    Dominik Livaković             90
2       Haydar Karataş              1
3           Jhon Durán            543
4  Sebastian Szymański            446
5       Sofyan Amrabat            102
6    Youssef En-Nesyri           1008
7        Yusuf Akçiçek             90

  CG plantilla completa:

                player         player_norm
0      Abdou Aziz Fall     abdou aziz fall
1       Anthony Musaba      anthony musaba
2         Archie Brown        archie brown
3         Bartuğ Elmaz        bartug elmaz
4       Çağlar Söyüncü      caglar soyuncu
5         Cengiz Ünder        cengiz under
6         Diego Carlos        diego carlos
7    Dominik Livakovic   dominik livakovic
8        Dorgeles Nene       dorgeles nene
9              Ederson             ederson
10       Edson Álvarez       edson alvarez
11            Emre Mor            emre mor
12   Engin Can Biterge   engin can biterge
13                Fred                fred
14   İrfan Can Kahveci   irfan can kahveci
15       İsmail Yüksek       ismail yuksek
16  Jayden Oosterwolde  jayden oosterwolde
17    Kerem Aktürkoğlu    kerem akturkoglu
18       Levent Mercan       levent mercan
19       Marco Asensio       marco asensio
20    Mattéo Guendouzi    matteo guendouzi
21          Mert Günok          mert gunok
22   Mert Hakan Yandaş   mert hakan yandas
23         Mert Müldür         mert muldur
24      Milan Škriniar      milan skriniar
25        N'Golo Kanté        n golo kante
26       Nélson Semedo       nelson semedo
27          Oğuz Aydın           oguz aydn
28       Rodrigo Becão       rodrigo becao
29       Sidiki Chérif       sidiki cherif
30      Sofyan Amrabat      sofyan amrabat
31             Talisca             talisca
32         Tarık Çetin          tark cetin
33     Yiğit Efe Demir     yigit efe demir

============================================================
  Galatasaray  —  SF sin salario:

        player  minutesPlayed
0  Yusuf Demir             28

  CG plantilla completa:

                     player              player_norm
0       Abdülkerim Bardakcı       abdulkerim bardakc
1              Ahmed Kutucu             ahmed kutucu
2                Arda Ünyay               arda unyay
3             Armando Güner            armando guner
4              Baris Yilmaz             baris yilmaz
5               Batuhan Şen              batuhan sen
6          Davinson Sánchez         davinson sanchez
7           Enes Emre Büyük          enes emre buyuk
8         Evren Eren Elmali        evren eren elmali
9              Gabriel Sara             gabriel sara
10          Gökdeniz Gürpüz          gokdeniz gurpuz
11             Günay Güvenç             gunay guvenc
12           İlkay Gündoğan           ilkay gundogan
13            Ismail Jakobs            ismail jakobs
14               Kaan Ayhan               kaan ayhan
15               Leroy Sané               leroy sane
16           Lucas Torreira           lucas torreira
17             Mario Lemina             mario lemina
18             Mauro Icardi             mauro icardi
19          Metehan Baltacı           metehan baltac
20           Nicolò Zaniolo           nicolo zaniolo
21                 Noa Lang                 noa lang
22             Renato Nhaga             renato nhaga
23            Roland Sallai            roland sallai
24               Sacha Boey               sacha boey
25            Uğurcan Çakır             ugurcan cakr
26           Victor Nelsson           victor nelsson
27           Victor Osimhen           victor osimhen
28  Wilfried Stephane Singo  wilfried stephane singo
29           Yáser Asprilla           yaser asprilla
30              Yunus Akgün              yunus akgun

============================================================
  Gaziantep FK  —  SF sin salario:

             player  minutesPlayed
0      Badou Ndiaye            431
1  Emmanuel Boateng            466
2     Enver Kulašin            132
3       Mirza Cihan             23
4         Rob Nizet             20
5  Sokratis Dioudis             23

  CG plantilla completa:

                     player              player_norm
0           Alexandru Maxim          alexandru maxim
1          Ali Mevran Ablak         ali mevran ablak
2           Ali Osman Kalın           ali osman kaln
3             Arda Kızıldağ              arda kzldag
4       Christopher Lungoyi      christopher lungoyi
5             Deian Sorescu            deian sorescu
6              Denis Drăguș             denis dragus
7             Drissa Camara            drissa camara
8            Juninho Bacuna           juninho bacuna
9          Kacper Kozlowski         kacper kozlowski
10          Karamba Gassama          karamba gassama
11          Kévin Rodrigues          kevin rodrigues
12               Luis Pérez               luis perez
13          Melih Kabasakal          melih kabasakal
14             Mohamed Bayo             mohamed bayo
15         Muhammet Akmelek         muhammet akmelek
16      Mustafa Burak Bozan      mustafa burak bozan
17             Myenty Abena             myenty abena
18            Nazım Sangaré             nazm sangare
19            Nihad Mujakic            nihad mujakic
20             Ogün Özçiçek             ogun ozcicek
21           Salem M'Bakata           salem m bakata
22             Tayyip Sanuc             tayyip sanuc
23  Victor Ntino-Emo Gidado  victor ntino emo gidado
24           Yusuf Kabadayi           yusuf kabadayi
25             Zafer Görgen             zafer gorgen

============================================================
  Gençlerbirliği  —  SF sin salario:

            player  minutesPlayed
0      Daniel Popa             68
1     Dilhan Demir            106
2     Gokhan Akkan            360
3    Kevin Csoboth             52
4    Michał Nalepa            262
5  Ousmane Diabate             90
6  Sinan Osmanoğlu             72

  CG plantilla completa:

                player         player_norm
0   Abdullah Şahindere  abdullah sahindere
1    Abdurrahim Dursun   abdurrahim dursun
2         Adama Traoré        adama traore
3     Arda Çağan Çelik    arda cagan celik
4           Ayaz Özcan          ayaz ozcan
5   Berk Deniz Çukurcu  berk deniz cukurcu
6          Cihan Çanak         cihan canak
7      Dal Varesanovic     dal varesanovic
8     Dimitrios Goutas    dimitrios goutas
9          Ebrar Aydın          ebrar aydn
10        Emirhan Ünal        emirhan unal
11     Ensar Kemaloğlu     ensar kemaloglu
12      Erhan Erentürk      erhan erenturk
13       Franco Tongya       franco tongya
14       Fıratcan Üzüm        fratcan uzum
15       Göktan Gürpüz       goktan gurpuz
16      Henry Onyekuru      henry onyekuru
17        M'Baye Niang        m baye niang
18      Matej Hanousek      matej hanousek
19   Metehan Mimaroğlu   metehan mimaroglu
20       Moussa Kyabou       moussa kyabou
21    Oghenekaro Etebo    oghenekaro etebo
22       Oğulcan Ülgün       ogulcan ulgun
23       Pedro Pereira       pedro pereira
24       Ricardo Velho       ricardo velho
25          Samed Onur          samed onur
26         Sékou Koïta         sekou koita
27           Thalisson           thalisson
28    Tom Dele-Bashiru    tom dele bashiru
29      Umut İslamoğlu      umut islamoglu
30   Yiğit Hamza Aydar   yigit hamza aydar
31           Zan Zuzek           zan zuzek

============================================================
  Göztepe  —  SF sin salario:

                 player  minutesPlayed
0           Ahmed Ildız             63
1              Emersonn            124
2  Juan Santos da Silva           2320
3                  Ruan            114
4        Salem Bouajila             20
5        Tibet Durakcay              1

  CG plantilla completa:

               player      player_norm
0      Alexis Antunes   alexis antunes
1         Allan Godói      allan godoi
2         Amin Cherni      amin cherni
3      Anthony Dennis   anthony dennis
4       Arda Kurtulan    arda kurtulan
5     Efkan Bekiroğlu  efkan bekiroglu
6        Ege Yıldırım        ege yldrm
7   Ekrem Kılıçarslan  ekrem klcarslan
8       Filip Krastev    filip krastev
9        Furkan Bayır      furkan bayr
10       Furkan Malak     furkan malak
11     Guilherme Luiz   guilherme luiz
12            Héliton          heliton
13      Ibrahim Sabra    ibrahim sabra
14     İsmail Köybaşı    ismail koybas
15          Janderson        janderson
16                Jeh              jeh
17               Juan             juan
18      Malcom Bokele    malcom bokele
19        Mateusz Lis      mateusz lis
20     Musah Mohammed   musah mohammed
21        Nevzat Üzel      nevzat uzel
22    Novatus Miroshi  novatus miroshi
23        Ogün Bayrak      ogun bayrak
24           Rhaldney         rhaldney
25       Şamil Öztürk     samil ozturk
26    Taha Altıkardeş   taha altkardes
27   Uğur Kaan Yıldız   ugur kaan yldz

============================================================
  Kasımpaşa  —  SF sin salario:

              player  minutesPlayed
0       Atakan Mujde            167
1  Berk Can Yildizli             11
2       Cem Üstündag            949
3      Jhon Espinoza            558
4       Mamadou Fall           1181

  CG plantilla completa:

                     player              player_norm
0                Adem Arous               adem arous
1         Adrian Benedyczak        adrian benedyczak
2        Ahmet Taha Dağbaşı        ahmet taha dagbas
3            Ali Emre Yanar           ali emre yanar
4             Ali Yavuz Kol            ali yavuz kol
5        Andreas Gianniotis       andreas gianniotis
6   Andri Fannar Baldursson  andri fannar baldursson
7             Attila Szalai            attila szalai
8          Berkay Muratoğlu         berkay muratoglu
9            Burak Gültekin           burak gultekin
10                     Cafú                     cafu
11               Cenk Tosun               cenk tosun
12            Cláudio Winck            claudio winck
13             Ege Albayrak             ege albayrak
14            Emre Taşdemir            emre tasdemir
15          Erdem Çetinkaya          erdem cetinkaya
16               Eyüp Aydın                eyup aydn
17         Fousseni Diabaté         fousseni diabate
18        Godfried Frimpong        godfried frimpong
19       Haris Hajradinovic       haris hajradinovic
20        İrfan Can Kahveci        irfan can kahveci
21            Jim Allevinah            jim allevinah
22      Kamil Ahmet Çörekçi      kamil ahmet corekci
23           Kerem Demirbay           kerem demirbay
24      Kubilay Kanatsızkuş       kubilay kanatszkus
25      Mortadha Ben Ouanes      mortadha ben ouanes
26           Nicholas Opoku           nicholas opoku
27         Pape Habib Guèye         pape habib gueye
28            Rodrigo Becão            rodrigo becao
29             Şant Kazancı              sant kazanc
30             Taylan Aydın              taylan aydn
31             Yusuf Barası              yusuf baras

============================================================
  Kayserispor  —  SF sin salario:

         player  minutesPlayed
0   Aaron Opoku           1235
1    Ali Karimi             39
2  Arif Kocaman            228
3   Gideon Jung            305
4     Yaw Ackah            185

  CG plantilla completa:

                   player            player_norm
0        Abdulsamet Burak       abdulsamet burak
1           Bilal Bayazıt           bilal bayazt
2           Burak Kapacak          burak kapacak
3             Carlos Mané            carlos mane
4           Denis Makarov          denis makarov
5          Deniz Dönmezer         deniz donmezer
6          Dorukhan Toköz         dorukhan tokoz
7              Eray Özbek             eray ozbek
8            Fedor Chalov           fedor chalov
9           Furkan Soyalp          furkan soyalp
10         German Onugkha         german onugkha
11          Görkem Sağlam          gorkem saglam
12            Indrit Tuci            indrit tuci
13          Jadel Katongo          jadel katongo
14            João Mendes            joao mendes
15          Joshua Brenet          joshua brenet
16            Kayra Cihan            kayra cihan
17           László Bénes           laszlo benes
18          Lionel Carole          lionel carole
19         Majid Hosseini         majid hosseini
20         Miguel Cardoso         miguel cardoso
21       Nurettin Korkmaz       nurettin korkmaz
22           Onurcan Piri           onurcan piri
23        Ramazan Civelek        ramazan civelek
24             Sam Mather             sam mather
25            Semih Güler            semih guler
26        Stefano Denswil        stefano denswil
27       Talha Sarıarslan        talha sararslan
28      Yiğit Emre Çeltik      yigit emre celtik
29  Youssef Aït Bennasser  youssef ait bennasser

============================================================
  Kocaelispor  —  SF sin salario:

               player  minutesPlayed
0  Aaron Appindangoyé            315
1          Arda Ozyar             20
2         Cihat Celik             19
3    Mesut Can Tunalı             45
4    Ogulcan Caglayan            196
5    Oleksandr Syrota            372
6         Ryan Mendes            273
7      Tarkan Serbest            244

  CG plantilla completa:

                  player           player_norm
0             Ahmet Oğuz            ahmet oguz
1            Ahmet Sağat           ahmet sagat
2   Aleksandar Jovanovic  aleksandar jovanovic
3     Anfernee Dijksteel    anfernee dijksteel
4          Botond Balogh         botond balogh
5         Bruno Petkovic        bruno petkovic
6              Can Keleş             can keles
7              Dan Agyei             dan agyei
8        Darko Churlinov       darko churlinov
9           Furkan Gedik          furkan gedik
10     Gökhan Değirmenci     gokhan degirmenci
11           Habib Keïta           habib keita
12        Hrvoje Smolcic        hrvoje smolcic
13          Joseph Nonge          joseph nonge
14         Karol Linetty         karol linetty
15      Mahamadou Susoho      mahamadou susoho
16      Massadio Haïdara      massadio haidara
17      Mateusz Wieteska      mateusz wieteska
18        Muharrem Cinan        muharrem cinan
19       Rigoberto Rivas       rigoberto rivas
20          Samet Yalçın           samet yalcn
21         Serdar Dursun         serdar dursun
22     Serhat Öztaşdelen     serhat oztasdelen
23                  Show                  show
24         Tayfur Bingöl         tayfur bingol

============================================================
  Konyaspor  —  SF sin salario:

               player  minutesPlayed
0       Alassane Ndao            798
1     Danijel Aleksić            198
2         Kaan Akyazı             34
3        Melih Bostan            122
4  Muzaffer Utku Eriş            157

  CG plantilla completa:

               player        player_norm
0        Adamo Nagalo       adamo nagalo
1       Adil Demirbağ      adil demirbag
2         Arif Boşluk        arif bosluk
3    Bahadır Güngördü    bahadr gungordu
4        Berkan Kutlu       berkan kutlu
5         Blaz Kramer        blaz kramer
6         Deniz Ertaş        deniz ertas
7         Deniz Türüç        deniz turuc
8     Diogo Gonçalves    diogo goncalves
9        Egemen Aydın        egemen aydn
10        Enis Bardhi        enis bardhi
11          Esat Buğa          esat buga
12          Guilherme          guilherme
13     Jackson Muleka     jackson muleka
14          Jin-ho Jo          jin ho jo
15      Josip Calusic      josip calusic
16     Kazeem Olaigbe     kazeem olaigbe
17  Marius Ștefănescu  marius stefanescu
18     Marko Jevtovic     marko jevtovic
19  Melih İbrahimoğlu  melih ibrahimoglu
20      Morten Bjørlo       morten bjrlo
21           Pedrinho           pedrinho
22      Rayyan Baniya      rayyan baniya
23   Riechedly Bazoer   riechedly bazoer
24    Sander Svendsen    sander svendsen
25      Tunahan Taşçı       tunahan tasc
26         Ufuk Akyol         ufuk akyol
27    Uğurcan Yazğılı      ugurcan yazgl
28       Yasir Subaşı        yasir subas
29    Yhoan Andzouana    yhoan andzouana

============================================================
  Samsunspor  —  SF sin salario:

          player  minutesPlayed
0    Nany Dimata            132
1   Polat Yaldır            108
2  Soner Aydoğdu            113

  CG plantilla completa:

                 player          player_norm
0          Afonso Sousa         afonso sousa
1     Ali Badra Diabaté    ali badra diabate
2       Alper Efe Pazar      alper efe pazar
3     Antoine Makoumbou    antoine makoumbou
4           Arbnor Muja          arbnor muja
5        Bedirhan Çetin       bedirhan cetin
6           Carlo Holse          carlo holse
7          Celil Yüksel         celil yuksel
8         Cherif Ndiaye        cherif ndiaye
9         Ebrima Ceesay        ebrima ceesay
10      Efe Berat Törüz      efe berat toruz
11      Efe Yiğit Üstün      efe yigit ustun
12        Elayis Tavsan        elayis tavsan
13          Emre Kılınç            emre klnc
14           Enes Albak           enes albak
15      Eyüp Değirmenci      eyup degirmenci
16         Franck Atoen         franck atoen
17  İrfan Can Eğribayat  irfan can egribayat
18      Jaurès Assoumou      jaures assoumou
19           Joe Mendes           joe mendes
20        Logi Tómasson        logi tomasson
21        Lubomir Satka        lubomir satka
22               Marius               marius
23   Muhammet Özbaskıcı     muhammet ozbaskc
24           Okan Kocuk           okan kocuk
25       Olivier Ntcham       olivier ntcham
26   Rick van Drongelen   rick van drongelen
27        Saikuba Jarju        saikuba jarju
28          Soner Gönül          soner gonul
29        Tahsin Bülbül        tahsin bulbul
30     Tanguy Coulibaly     tanguy coulibaly
31      Toni Borevković      toni borevkovic
32         Yalçın Kayan          yalcn kayan
33      Yunus Emre Çift      yunus emre cift
34           Zeki Yavru           zeki yavru

============================================================
  Trabzonspor  —  SF sin salario:

                    player  minutesPlayed
0            Batista Mendy             56
1             Danylo Sikan            251
2  Muhammed-Cham Saračević             11
3            Serdar Saatçı            185

  CG plantilla completa:

                    player           player_norm
0           Ahmet Yıldırım           ahmet yldrm
1              André Onana           andre onana
2         Anthony Nwakaeme      anthony nwakaeme
3              Arda Öztürk           arda ozturk
4          Arseniy Batagov       arseniy batagov
5      Benjamin Bouchouari   benjamin bouchouari
6             Boran Başkan          boran baskan
7          Chibuike Nwaiwu       chibuike nwaiwu
8        Christ Inao Oulaï     christ inao oulai
9              Cihan Çanak           cihan canak
10              Edin Visca            edin visca
11             Ernest Muci           ernest muci
12          Erol Can Çolak        erol can colak
13          Felipe Augusto        felipe augusto
14          Kazeem Olaigbe        kazeem olaigbe
15  Mathias Fjørtoft Løvik  mathias fjrtoft lvik
16      Mustafa Eskihellaç    mustafa eskihellac
17            Okay Yokuşlu          okay yokuslu
18        Oleksandr Zubkov      oleksandr zubkov
19       Onuralp Çakıroğlu      onuralp cakroglu
20        Onuralp Çevikkan      onuralp cevikkan
21              Ozan Tufan            ozan tufan
22            Paul Onuachu          paul onuachu
23        Salih Malkoçoğlu      salih malkocoglu
24            Stefan Savic          stefan savic
25          Taha Emre İnce        taha emre ince
26    Tim Jabol-Folcarelli  tim jabol folcarelli
27              Umut Nayir            umut nayir
28             Wagner Pina           wagner pina

============================================================
  Çaykur Rizespor  —  SF sin salario:

              player  minutesPlayed
0  Jesurun Rak-Sakyi            817
1     Vaclav Jurecka            479

  CG plantilla completa:

                  player           player_norm
0         Adedire Mebude        adedire mebude
1               Ali Sowe              ali sowe
2           Altin Zeqiri          altin zeqiri
3           Attila Mocsi          attila mocsi
4           Casper Højer           casper hjer
5              Efe Doğan             efe dogan
6          Emir Ortakaya         emir ortakaya
7          Emrecan Bulut         emrecan bulut
8         Erdem Canpolat        erdem canpolat
9       Frantzdy Pierrot      frantzdy pierrot
10           Furkan Orak           furkan orak
11  Giannis Papanikolaou  giannis papanikolaou
12      Halil Dervişoğlu      halil dervisoglu
13      Ibrahim Olawoyin      ibrahim olawoyin
14   Khusniddin Alikulov   khusniddin alikulov
15         Loide Augusto         loide augusto
16           Mithat Pala           mithat pala
17         Modibo Sagnan         modibo sagnan
18    Muhamed Buljubasic    muhamed buljubasic
19            Qazim Laci            qazim laci
20         Samet Akaydin         samet akaydin
21            Taha Şahin            taha sahin
22      Taylan Antalyalı       taylan antalyal
23      Valentin Mihăilă      valentin mihaila
24          Yahia Fofana          yahia fofana

In [20]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('ruan pereira duarte', 'alanyaspor'): ('ruan',  'alanyaspor'),
    ('juan santos da silva', 'goztepe')  : ('juan',  'goztepe'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 2

In [21]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: ruan pereira duarte (alanyaspor) → ruan (alanyaspor)
✅ Match manual aplicado: juan santos da silva (goztepe) → juan (goztepe)

Tras matches manuales: 452/547 (82.6%)

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

⚠️ Nombre con sufijo `_snapshot_20260428` para diferenciar del master definitivo
que se generará al cierre de la temporada (`master_turkey_2526.csv`).

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_turkey_2526_snapshot_20260428.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_turkey_2526_snapshot_20260428.csv
   Jugadores totales:  547
   Con salario:        452
   Sin salario (NaN):  95
   Columnas:           122