# 03 · Join Sofascore + Capology — Turkey Süper Lig 20/21

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2020/21 de Süper Lig turca**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [36]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [37]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [38]:
df_sf = pd.read_csv(SF_DIR / 'df_turkey_2021.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_turkey_2021.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  660 jugadores | 116 columnas
Capology:   737 jugadores | 9 columnas

## 4. Normalización

In [39]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [40]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   basaksehir fk
   besiktas jk
   erzurumspor fk
   fatih karagumruk
   gaziantep fk
   genclerbirligi
   kasmpasa
   mke ankaragucu

En Capology pero no en Sofascore:
   ankaragucu
   basaksehir
   besiktas
   erzurumspor
   gaziantep bb
   genclerbirligi sk
   karagumrukspor
   kasimpasa

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [41]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'ankaragucu':'mke ankaragucu',
            'basaksehir':'basaksehir fk',
            'besiktas':'besiktas jk',
            'erzurumspor':'erzurumspor fk',
            'gaziantep bb':'gaziantep fk',
            'genclerbirligi sk':'genclerbirligi',
            'karagumrukspor':'fatih karagumruk',
            'kasimpasa':'kasmpasa'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [42]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 538/660 (81.5%)
Sin emparejar: 122

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [43]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          59
Revisión media    (0.75 ≤ score < 0.90):   18
Revisión estricta (0.50 ≤ score < 0.75):   30
Revisión muy est. (score < 0.50):           15

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [44]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf              team                cg_match  score
59   Dimitris Chatziisaias   Çaykur Rizespor  dimitrios chatziisaias  0.977
38    Dimitris Kolovetsios       Kayserispor   dimitrios kolovetsios  0.976
56     Alexander Søderlund   Çaykur Rizespor     alexander soderlund  0.973
15     Abdülkerim Bardakcı         Konyaspor     abdulkerim bardakci  0.973
63     Kubilay Kanatsızkuş  Yeni Malatyaspor     kubilay kanatsizkus  0.973
53       Radosław Murawski       Denizlispor       radoslaw murawski  0.970
87       Mevlut Han Ekelik       Antalyaspor        mevluthan ekelik  0.970
84       Bilal Başaçıkoğlu      Gaziantep FK       bilal basacikoglu  0.970
30       Ertuğrul Taşkıran         Kasımpaşa       ertugrul taskiran  0.970
7         Taylan Antalyalı       Galatasaray        taylan antalyali  0.968
17        Şener Özbayraklı       Galatasaray        sener ozbayrakli  0.968
69        Matthieu Dossevi       Denizlispor         mathieu dossevi  0.968
100       Hüseyin Altıntaş       Denizlispor        huseyin altintas  0.968
35          İsmail Köybaşı   Çaykur Rizespor          ismail koybasi  0.963
40          Bünyamin Balcı       Antalyaspor          bunyamin balci  0.963
22          Bahadır Öztürk       Antalyaspor          bahadir ozturk  0.963
45          Daniel Łukasik    MKE Ankaragücü          daniel lukasik  0.963
37          Torgeir Børven    MKE Ankaragücü          torgeir borven  0.963
71          Ferdi Kadıoğlu        Fenerbahçe          ferdi kadioglu  0.963
113         Übeyd Adıyaman    Gençlerbirliği          ubeyd adiyaman  0.963
54          Paweł Olkowski      Gaziantep FK          pawel olkowski  0.963
9            Uğurcan Çakır       Trabzonspor           ugurcan cakir  0.960
49           Buğra Çağıran    Erzurumspor FK           bugra cagiran  0.960
6            Nazım Sangaré        Fenerbahçe           nazim sangare  0.960
73           Koray Altınay  Fatih Karagümrük           koray altinay  0.960
68           Michał Pazdan    MKE Ankaragücü           michal pazdan  0.960
24            Robin Yalçın         Sivasspor            robin yalcin  0.957
41            Mirkan Aydın         Hatayspor            mirkan aydin  0.957
44            Yalçın Kayan           Göztepe            yalcin kayan  0.957
57            Yasir Subaşı       Kayserispor            yasir subasi  0.957
72            Musa Çağıran         Konyaspor            musa cagiran  0.957
66            Güven Yalçın       Beşiktaş JK            guven yalcin  0.957
80             Ahmed Ildız  Yeni Malatyaspor             ahmed ildiz  0.952
89             Sakıb Aytaç       Denizlispor             sakib aytac  0.952
64             Sefa Yılmaz    Gençlerbirliği             sefa yilmaz  0.952
65             Orkan Çınar    MKE Ankaragücü             orkan cinar  0.952
47             Tarık Çetin   Çaykur Rizespor             tarik cetin  0.952
31             Oğuz Yılmaz       Denizlispor             oguz yilmaz  0.952
23             Veysel Sarı       Antalyaspor             veysel sari  0.952
16             Atınç Nukan           Göztepe             atinc nukan  0.952
11             Ahmet Çalık         Konyaspor             ahmet calik  0.952
51              Yusuf Sarı       Trabzonspor              yusuf sari  0.947
105     Srđan Spiridonović    Gençlerbirliği     srdjan spiridonovic  0.944
43      Cenk Ahmet Alkılıç    Erzurumspor FK      cenk ahmet alkilic  0.941
46               Efe Tatlı  Fatih Karagümrük               efe tatli  0.941
50      Hasan Ali Kaldırım     Başakşehir FK      hasan ali kaldirim  0.941
104       Mücahit Albayrak    Erzurumspor FK        mucahid albayrak  0.938
107       Harisson Manzala       Kayserispor        harrison manzala  0.938
85                Anıl Koç         Kasımpaşa                anil koc  0.933
34          Damjan Đoković   Çaykur Rizespor         damjan djokovic  0.929
19         Sadık Çiftpınar        Fenerbahçe         sadik ciftpinar  0.929
101        Embiya Ayyıldız    MKE Ankaragücü         embiya ayyildiz  0.929
20          Altay Bayındır        Fenerbahçe          altay bayindir  0.923
102           Bogdan Butko    Erzurumspor FK            bohdan butko  0.917
48           Rıdvan Yılmaz       Beşiktaş JK           ridvan yilmaz  0.917
26           Arda Kızıldağ    Gençlerbirliği           arda kizildag  0.917
36             Kerim Alıcı           Göztepe             kerim alici  0.900
25             Emre Kılınç       Galatasaray             emre kilinc  0.900
109            Berk Yıldız  Yeni Malatyaspor             berk yildiz  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [45]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                    player_sf              team           cg_match  score
1            Muammer Yıldırım         Sivasspor   muammer yildirim  0.897
98            Volkan Fındıklı         Konyaspor    volkan findikli  0.889
55             Barış Yardımcı         Konyaspor     baris yardimci  0.880
108    Sami Gokhan Altiparmak    Gençlerbirliği  gokhan altiparmak  0.872
10           Serkan Kırıntılı        Alanyaspor   serkan kirintili  0.857
39        Mbwana Ally Samatta        Fenerbahçe     mbwana samatta  0.848
4       Aaron-Salem Boupendza         Hatayspor    aaron boupendza  0.833
116       Ahmet Oytun Özdoğan        Fenerbahçe      oytun ozdogan  0.812
114       Çağlar Şahin Akbaba      Gaziantep FK      caglar akbaba  0.812
12       Berat Ayberk Özdemir       Trabzonspor      berat ozdemir  0.788
99     Mehmet Göktuğ Bakırbaş    Erzurumspor FK    goktug bakirbas  0.778
74     Mustafa Hüseyin Seyhan    Gençlerbirliği     mustafa seyhan  0.778
90        Kartal Kayra Yılmaz       Beşiktaş JK      kartal yilmaz  0.774
81   Muhammed Egemen Pehlivan  Fatih Karagümrük    egemen pehlivan  0.769
3            Mame Biram Diouf         Hatayspor         mame diouf  0.769
91           Ömer Faruk Beyaz        Fenerbahçe         omer beyaz  0.769
83      Johanna Ochieng Omolo    Erzurumspor FK      johanna omolo  0.765
61    Babajide David Akintola         Hatayspor     david akintola  0.757

In [46]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 18 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [47]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                   player_sf              team            cg_match  score
95    Muhammed Eren Kiryolcu       Denizlispor       eren kiryolcu  0.743
18               Eren Elmalı         Kasımpaşa   evren eren elmali  0.741
70         Mehmet Murat Uçar    Erzurumspor FK          murat ucar  0.741
103      Hüseyin Atakan Üner       Beşiktaş JK         atakan uner  0.733
94               Emre Karaal     Başakşehir FK         emre kaplan  0.727
52          Jefferson Junior      Gaziantep FK           jefferson  0.720
14                Campanharo       Kayserispor  gustavo campanharo  0.714
27         Guilherme Marques           Göztepe           guilherme  0.692
82     Mehmet Feyzi Yıldırım         Kasımpaşa      feyzi yildirim  0.688
111      Huseyin Furkan Uslu       Denizlispor    huseyin altintas  0.629
76              André Balada      Gaziantep FK         andre sousa  0.609
62          Amilton da Silva       Antalyaspor             amilton  0.609
13            Radamel Falcao       Galatasaray              falcao  0.600
110        Emirhan Kascioglu       Denizlispor       eren kiryolcu  0.600
32              Carlos Ponck     Başakşehir FK               ponck  0.588
78                 Bora Adam  Fatih Karagümrük        brahim darri  0.571
5    Guilherme Haubert Sityá         Konyaspor           guilherme  0.562
79         Abdurrahim Dursun       Trabzonspor     abdulkadir omur  0.562
86          Anthony Uzodimma       Kayserispor       anton maglica  0.552
77              Berat Kalkan         Kasımpaşa   ertugrul taskiran  0.552
118             Mahamadou Ba    Erzurumspor FK      armando sadiku  0.538
67               Alan Cariús         Kasımpaşa                alan  0.533
119            Alaattin Öner       Denizlispor   abdulkadir sunger  0.533
29                     Zanka        Fenerbahçe          ozan tufan  0.533
60              Nadir Çiftçi   Çaykur Rizespor         tarik cetin  0.522
106        Mehmet Ali Ulaman       Denizlispor      muhammet ozkal  0.516
121       Muhammed Arda Uzun        Alanyaspor   ahmet cagri guney  0.514
2                      Souza       Beşiktaş JK             douglas  0.500
21           Munir El Kajoui         Hatayspor               munir  0.500
75             Kevin Brobbey       Kayserispor     kevin luckassen  0.500

In [48]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['muhammed eren kiryolcu',
                    'eren elmal',
                    'mehmet murat ucar',
                    'huseyin atakan uner',
                    'jefferson junior',
                    'campanharo',
                    'guilherme marques',
                    'mehmet feyzi yldrm',
                    'amilton da silva',
                    'andre balada',
                    'radamel falcao',
                    'carlos ponck',
                    'guilherme haubert sitya',
                    'alan carius',
                    'munir el kajoui'
                    
                    

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 15

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [49]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf         team             cg_match  score
8         Kağan Moradaoğlu  Trabzonspor    bilal basacikoglu  0.485
42         Hasan Yesilyurt    Kasımpaşa       tarkan serbest  0.483
115           Emre Yildrim  Denizlispor        eren kiryolcu  0.480
112  Fatih Yiğit Şanlıtürk   Fenerbahçe  bright osayi samuel  0.462
117           Bartuğ Elmaz  Galatasaray           arda turan  0.455
0              Mario Šitum  Kayserispor          karlo muhar  0.455
28            Michael Frey   Fenerbahçe           omer beyaz  0.455
58           İsmail Yüksek   Fenerbahçe   papiss demba cisse  0.452
96            Mert Sarikus  Denizlispor      muris mesanovic  0.444
97              Umut Nayir  Beşiktaş JK        muhayer oktay  0.435
120         Ferhat Erdogan  Denizlispor       hugo rodallega  0.429
93                  Thuram    Konyaspor        paolo hurtado  0.421
33           David Pavelka    Kasımpaşa          kevin varga  0.417
92           Yusuf Özdemir   Alanyaspor     mustafa pektemek  0.414
88            Paul Mukairu  Antalyaspor       lukas podolski  0.385

In [50]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [51]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 630/660 (95.5%)
Sin salario:     30

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [52]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 30

,player,team,minutesPlayed,appearances,goals,assists
0,Yusuf Özdemir,Alanyaspor,10,1,0,0
1,Muhammed Arda Uzun,Alanyaspor,1,1,0,0
2,Paul Mukairu,Antalyaspor,135,3,0,0
3,Emre Karaal,Başakşehir FK,8,1,0,0
4,Souza,Beşiktaş JK,2880,33,2,3
5,Umut Nayir,Beşiktaş JK,28,2,0,0
6,Emirhan Kascioglu,Denizlispor,147,3,0,0
7,Emre Yildrim,Denizlispor,90,1,0,0
8,Mehmet Ali Ulaman,Denizlispor,45,1,0,0
9,Mert Sarikus,Denizlispor,8,1,0,0
10,Huseyin Furkan Uslu,Denizlispor,8,1,0,0
11,Alaattin Öner,Denizlispor,1,1,0,0
12,Ferhat Erdogan,Denizlispor,1,1,0,0
13,Mahamadou Ba,Erzurumspor FK,1,1,0,0
14,Bora Adam,Fatih Karagümrük,8,1,0,0
15,Zanka,Fenerbahçe,180,2,0,0
16,Michael Frey,Fenerbahçe,90,1,0,0
17,Fatih Yiğit Şanlıtürk,Fenerbahçe,16,2,0,0
18,İsmail Yüksek,Fenerbahçe,12,1,0,0
19,Bartuğ Elmaz,Galatasaray,1,1,0,0
20,David Pavelka,Kasımpaşa,220,4,0,0
21,Hasan Yesilyurt,Kasımpaşa,36,3,0,0
22,Berat Kalkan,Kasımpaşa,8,1,0,0
23,Kevin Brobbey,Kayserispor,539,14,0,0
24,Anthony Uzodimma,Kayserispor,153,2,0,0
25,Mario Šitum,Kayserispor,90,1,0,0
26,Thuram,Konyaspor,9,1,0,0
27,Abdurrahim Dursun,Trabzonspor,134,2,0,0
28,Kağan Moradaoğlu,Trabzonspor,90,1,0,0
29,Nadir Çiftçi,Çaykur Rizespor,25,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [53]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Alanyaspor  —  SF sin salario:

               player  minutesPlayed
0  Muhammed Arda Uzun              1
1       Yusuf Özdemir             10

  CG plantilla completa:

                  player           player_norm
0           Adam Bareiro          adam bareiro
1      Ahmet Cagri Güney     ahmet cagri guney
2            Ahmet Gülay           ahmet gulay
3           Alpay Celebi          alpay celebi
4   Anastasios Bakasetas  anastasios bakasetas
5           Berkan Kutlu          berkan kutlu
6        Ceyhun Gülselam       ceyhun gulselam
7         Damian Kadzior        damian kadzior
8               Davidson              davidson
9          Efecan Karaca         efecan karaca
10       Efkan Bekiroglu       efkan bekiroglu
11         El Mami Tetah         el mami tetah
12           Fatih Aksoy           fatih aksoy
13    François Moubandje    francois moubandje
14    Georgios Tzavellas    georgios tzavellas
15        Hasan Ayaroglu        hasan ayaroglu
16    Hasan Hüseyin Acar    hasan huseyin acar
17              Juanfran              juanfran
18        Khouma Babacar        khouma babacar
19        Manolis Siopis        manolis siopis
20              Marafona              marafona
21      Mustafa Pektemek      mustafa pektemek
22            Salih Ucan            salih ucan
23      Serkan Kirintili      serkan kirintili
24        Steven Caulker        steven caulker
25         Tayfur Bingöl         tayfur bingol
26           Ufuk Ceylan           ufuk ceylan
27            Umut Günes            umut gunes

============================================================
  Antalyaspor  —  SF sin salario:

         player  minutesPlayed
0  Paul Mukairu            135

  CG plantilla completa:

                player         player_norm
0      Adem Metin Türk     adem metin turk
1         Adis Jahovic        adis jahovic
2      Ali Eren Iyican     ali eren iyican
3              Amilton             amilton
4       Bahadir Öztürk      bahadir ozturk
5       Bünyamin Balci      bunyamin balci
6         Dever Orgill        dever orgill
7        Dogukan Özkan       dogukan ozkan
8        Dogukan Sinik       dogukan sinik
9    Enes Sancar Sahin   enes sancar sahin
10       Eren Albayrak       eren albayrak
11         Ersan Gülüm         ersan gulum
12    Fedor Kudryashov    fedor kudryashov
13       Ferhat Kaplan       ferhat kaplan
14               Fredy               fredy
15  Gökdeniz Bayrakdar  gokdeniz bayrakdar
16        Hakan Özmert        hakan ozmert
17    Jean-Armel Drolé    jean armel drole
18      Lukas Podolski      lukas podolski
19         Mert Yilmaz         mert yilmaz
20    Mevlüthan Ekelik    mevluthan ekelik
21               Naldo               naldo
22          Nuri Sahin          nuri sahin
23          Omar Imeri          omar imeri
24         Ruud Boffin         ruud boffin
25       Serdar Gürler       serdar gurler
26       Serdar Poyraz       serdar poyraz
27          Sidney Sam          sidney sam
28          Ufuk Akyol          ufuk akyol
29         Veysel Sari         veysel sari

============================================================
  Başakşehir FK  —  SF sin salario:

        player  minutesPlayed
0  Emre Karaal              8

  CG plantilla completa:

                    player             player_norm
0             Ahmet Kivanc            ahmet kivanc
1       Alexandru Epureanu      alexandru epureanu
2             Berkay Özcan            berkay ozcan
3           Boli Bolingoli          boli bolingoli
4            Cemali Sertel           cemali sertel
5          Danijel Aleksic         danijel aleksic
6                 Demba Ba                demba ba
7              Deniz Türüc             deniz turuc
8               Edin Visca              edin visca
9             Emir Senocak            emir senocak
10             Emre Kaplan             emre kaplan
11            Enes Karakus            enes karakus
12           Enzo Crivelli           enzo crivelli
13     Fredrik Gulbrandsen     fredrik gulbrandsen
14                Giuliano                giuliano
15      Hasan Ali Kaldirim      hasan ali kaldirim
16       Irfan Can Kahveci       irfan can kahveci
17          Júnior Caiçara          junior caicara
18        Junior Fernandes        junior fernandes
19              Kerim Frei              kerim frei
20              Léo Duarte              leo duarte
21         Mahmut Tekdemir         mahmut tekdemir
22           Martin Skrtel           martin skrtel
23            Mehmet Topal            mehmet topal
24              Mert Günok              mert gunok
25         Mete Kaan Demir         mete kaan demir
26  Muhammed Emin Sarikaya  muhammed emin sarikaya
27       Muhammed Sengezer       muhammed sengezer
28            Nacer Chadli            nacer chadli
29      Okechukwu Azubuike      okechukwu azubuike
30        Ömer Ali Sahiner        omer ali sahiner
31                   Ponck                   ponck
32                  Rafael                  rafael
33             Ravil Tagir             ravil tagir
34           Tolga Cigerci           tolga cigerci
35               Ugur Ucar               ugur ucar
36          Volkan Babacan          volkan babacan
37   Youssouf Ndayishimiye   youssouf ndayishimiye

============================================================
  Beşiktaş JK  —  SF sin salario:

       player  minutesPlayed
0       Souza           2880
1  Umut Nayir             28

  CG plantilla completa:

                    player             player_norm
0              Adem Ljajic             adem ljajic
1              Ajdin Hasic             ajdin hasic
2              Atakan Üner             atakan uner
3         Atiba Hutchinson        atiba hutchinson
4           Bernard Mensah          bernard mensah
5             Bilal Ceylan            bilal ceylan
6               Cenk Tosun              cenk tosun
7               Cyle Larin              cyle larin
8             Domagoj Vida            domagoj vida
9           Dorukhan Toköz          dorukhan tokoz
10                 Douglas                 douglas
11             Emre Bilgin             emre bilgin
12            Erdogan Kaya            erdogan kaya
13        Ersin Destanoglu        ersin destanoglu
14        Fabrice N'Sakala        fabrice n sakala
15       Francisco Montero       francisco montero
16  Georges-Kevin N'Koudou  georges kevin n koudou
17             Gökhan Töre             gokhan tore
18            Güven Yalcin            guven yalcin
19           Jeremain Lens           jeremain lens
20                   Josef                   josef
21           Kartal Yilmaz           kartal yilmaz
22           Muhayer Oktay           muhayer oktay
23             Necip Uysal             necip uysal
24    Nicolas Isimat-Mirin    nicolas isimat mirin
25         Oguzhan Özyakup         oguzhan ozyakup
26          Rachid Ghezzal          rachid ghezzal
27           Ridvan Yilmaz           ridvan yilmaz
28           Serdar Saatci           serdar saatci
29              Tyler Boyd              tyler boyd
30          Utku Yuvakuran          utku yuvakuran
31         Valentin Rosier         valentin rosier
32       Vincent Aboubakar       vincent aboubakar
33                Welinton                welinton

============================================================
  Denizlispor  —  SF sin salario:

                player  minutesPlayed
0        Alaattin Öner              1
1    Emirhan Kascioglu            147
2         Emre Yildrim             90
3       Ferhat Erdogan              1
4  Huseyin Furkan Uslu              8
5    Mehmet Ali Ulaman             45
6         Mert Sarikus              8

  CG plantilla completa:

               player        player_norm
0   Abdulkadir Sünger  abdulkadir sunger
1         Ahmed Yasin        ahmed yasin
2       Ali Yavuz Kol      ali yavuz kol
3       Alihan Kalkan      alihan kalkan
4        Ángelo Sagal       angelo sagal
5       Asim Aksungur      asim aksungur
6   Ayman Ben Mohamed  ayman ben mohamed
7          Cenk Gönen         cenk gonen
8   Costel Pantilimon  costel pantilimon
9       Eren Kiryolcu      eren kiryolcu
10            Fabiano            fabiano
11        Fede Varela        fede varela
12         Görkem Can         gorkem can
13         Hadi Sacko         hadi sacko
14     Hasan Ayaroglu     hasan ayaroglu
15     Hugo Rodallega     hugo rodallega
16   Hüseyin Altintas   huseyin altintas
17     Ismail Aissati     ismail aissati
18      Kubilay Aktas      kubilay aktas
19    Marvin Bakalorz    marvin bakalorz
20    Mathieu Dossevi    mathieu dossevi
21       Mix Diskerud       mix diskerud
22     Muhammet Özkal     muhammet ozkal
23    Muris Mesanovic    muris mesanovic
24      Mustafa Yumlu      mustafa yumlu
25      Neven Subotic      neven subotic
26        Oguz Yilmaz        oguz yilmaz
27       Özer Özdemir       ozer ozdemir
28          Özgür Cek          ozgur cek
29  Radoslaw Murawski  radoslaw murawski
30        Recep Niyaz        recep niyaz
31        Sakib Aytac        sakib aytac
32        Tiago Lopes        tiago lopes
33        Veton Tusha        veton tusha
34   Zakarya Bergdich   zakarya bergdich

============================================================
  Erzurumspor FK  —  SF sin salario:

         player  minutesPlayed
0  Mahamadou Ba              1

  CG plantilla completa:

                player         player_norm
0    Aatif Chahechouhe   aatif chahechouhe
1       Adolphe Teikeu      adolphe teikeu
2       Armando Sadiku      armando sadiku
3          Arturo Mina         arturo mina
4    Arvydas Novikovas   arvydas novikovas
5        Batuhan Ünsal       batuhan unsal
6         Bohdan Butko        bohdan butko
7         Brahim Darri        brahim darri
8        Bugra Cagiran       bugra cagiran
9   Cenk Ahmet Alkilic  cenk ahmet alkilic
10     Elbasan Rashani     elbasan rashani
11        Emrah Bassan        emrah bassan
12     Fabien Farnolle     fabien farnolle
13     Gabriel Obertan     gabriel obertan
14       Gökhan Kardes       gokhan kardes
15     Göktug Bakirbas     goktug bakirbas
16     Hasan Hatipoglu     hasan hatipoglu
17       Ibrahim Akdag       ibrahim akdag
18     Ibrahim Sissoko     ibrahim sissoko
19       Jakub Szumski       jakub szumski
20       Johanna Omolo       johanna omolo
21    Jugurtha Hamroun    jugurtha hamroun
22          Kaan Kanak          kaan kanak
23     Kayacan Erdogan     kayacan erdogan
24      Léo Schwechlen      leo schwechlen
25     Manuel da Costa     manuel da costa
26     Mitchell Donald     mitchell donald
27   Mostapha El Kabir   mostapha el kabir
28    Mücahid Albayrak    mucahid albayrak
29          Murat Ucar          murat ucar
30  Oltan Karakullukcu  oltan karakullukcu
31     Ömer Sismanoglu     omer sismanoglu
32         Osman Celik         osman celik
33          Özgür Sert          ozgur sert
34       Petrus Boumal       petrus boumal
35     Rashad Muhammed     rashad muhammed
36       Ricardo Gomes       ricardo gomes
37           Yaw Ackah           yaw ackah
38    Zakarya Bergdich    zakarya bergdich

============================================================
  Fatih Karagümrük  —  SF sin salario:

      player  minutesPlayed
0  Bora Adam              8

  CG plantilla completa:

                   player            player_norm
0       Aatif Chahechouhe      aatif chahechouhe
1             Aksel Aktas            aksel aktas
2           Alassane Ndao          alassane ndao
3         Alparslan Erdem        alparslan erdem
4       Andrea Bertolacci      andrea bertolacci
5           Artur Sobiech          artur sobiech
6              Aykut Özer             aykut ozer
7            Badou Ndiaye           badou ndiaye
8           Bojan Saranov          bojan saranov
9            Brahim Darri           brahim darri
10     Cristobal Jorquera     cristobal jorquera
11              Efe Tatli              efe tatli
12        Egemen Pehlivan        egemen pehlivan
13       Emiliano Viviano       emiliano viviano
14             Emre Colak             emre colak
15              Enzo Roco              enzo roco
16            Eric Lichaj            eric lichaj
17              Erik Sabo              erik sabo
18        Ervin Zukanovic        ervin zukanovic
19           Fabio Borini           fabio borini
20          Fatih Kurucuk          fatih kurucuk
21            Furkan Kara            furkan kara
22           Gastón Campi           gaston campi
23          Jeremain Lens          jeremain lens
24           Jimmy Durmaz           jimmy durmaz
25          Jure Balkovec          jure balkovec
26            Kemal Ademi            kemal ademi
27          Koray Altinay          koray altinay
28           Lucas Biglia           lucas biglia
29           Lucas Castro           lucas castro
30          Mevlüt Erdinc          mevlut erdinc
31          Murat Sarigül          murat sarigul
32    Muzaffer Cem Kablan    muzaffer cem kablan
33        Ramazan Civelek        ramazan civelek
34       Serhat Ahmetoglu       serhat ahmetoglu
35         Vato Arveladze         vato arveladze
36  Vegar Eggen Hedenstad  vegar eggen hedenstad
37         Yannis Salibur         yannis salibur
38            Yavuz Aygün            yavuz aygun
39        Yavuz Ulas Genc        yavuz ulas genc
40          Zeki Yildirim          zeki yildirim

============================================================
  Fenerbahçe  —  SF sin salario:

                  player  minutesPlayed
0  Fatih Yiğit Şanlıtürk             16
1           Michael Frey             90
2                  Zanka            180
3          İsmail Yüksek             12

  CG plantilla completa:

                 player          player_norm
0        Altay Bayindir       altay bayindir
1         Attila Szalai        attila szalai
2   Bright Osayi-Samuel  bright osayi samuel
3           Caner Erkin          caner erkin
4         Diego Perotti        diego perotti
5      Dimitrios Pelkas     dimitrios pelkas
6        Enner Valencia       enner valencia
7        Ferdi Kadioglu       ferdi kadioglu
8           Filip Novak          filip novak
9          Gökhan Gönül         gokhan gonul
10          Harun Tekin          harun tekin
11    Irfan Can Kahveci    irfan can kahveci
12            José Sosa            jose sosa
13          Kemal Ademi          kemal ademi
14         Luiz Gustavo         luiz gustavo
15           Mame Thiam           mame thiam
16     Marcel Tisserand     marcel tisserand
17       Mauricio Lemos       mauricio lemos
18       Mbwana Samatta       mbwana samatta
19    Mert Hakan Yandas    mert hakan yandas
20           Mesut Özil           mesut ozil
21          Nabil Dirar          nabil dirar
22        Nazim Sangaré        nazim sangare
23           Ömer Beyaz           omer beyaz
24        Oytun Özdogan        oytun ozdogan
25           Ozan Tufan           ozan tufan
26   Papiss Demba Cissé   papiss demba cisse
27      Sadik Ciftpinar      sadik ciftpinar
28          Serdar Aziz          serdar aziz
29          Sinan Gümüs          sinan gumus
30        Tolga Cigerci        tolga cigerci

============================================================
  Galatasaray  —  SF sin salario:

         player  minutesPlayed
0  Bartuğ Elmaz              1

  CG plantilla completa:

                  player           player_norm
0          Ali Yavuz Kol         ali yavuz kol
1             Arda Turan            arda turan
2    Christian Luyindama   christian luyindama
3         DeAndre Yedlin        deandre yedlin
4            Emin Bayram           emin bayram
5            Emre Akbaba           emre akbaba
6            Emre Kilinc           emre kilinc
7          Emre Tasdemir         emre tasdemir
8                 Falcao                falcao
9           Fatih Öztürk          fatih ozturk
10      Fernando Muslera      fernando muslera
11      Gedson Fernandes      gedson fernandes
12      Halil Dervisoglu      halil dervisoglu
13        Henry Onyekuru        henry onyekuru
14        Jesse Sekidika        jesse sekidika
15      Kerem Aktürkoglu      kerem akturkoglu
16                Marcão                marcao
17      Marcelo Saracchi      marcelo saracchi
18         Martin Linnes         martin linnes
19          Mbaye Diagne          mbaye diagne
20       Mostafa Mohamed       mostafa mohamed
21      Oghenekaro Etebo      oghenekaro etebo
22      Ogulcan Caglayan      ogulcan caglayan
23            Okan Kocuk            okan kocuk
24     Omar Elabdellaoui     omar elabdellaoui
25           Ömer Bayram           omer bayram
26            Ryan Babel            ryan babel
27             Ryan Donk             ryan donk
28      Sener Özbayrakli      sener ozbayrakli
29      Sofiane Feghouli      sofiane feghouli
30      Taylan Antalyali      taylan antalyali
31  Valentine Ozornwafor  valentine ozornwafor
32       Younès Belhanda       younes belhanda

============================================================
  Kasımpaşa  —  SF sin salario:

            player  minutesPlayed
0     Berat Kalkan              8
1    David Pavelka            220
2  Hasan Yesilyurt             36

  CG plantilla completa:

                 player          player_norm
0            Ahmet Oguz           ahmet oguz
1                  Alan                 alan
2              Anil Koc             anil koc
3          Armin Hodzic         armin hodzic
4            Aytac Kara           aytac kara
5           Azad Toptik          azad toptik
6    Bengali-Fodé Koita   bengali fode koita
7            Berk Cetin           berk cetin
8      Cagtay Kurukalip     cagtay kurukalip
9      Danny Drinkwater     danny drinkwater
10    Derrick Luckassen    derrick luckassen
11     Dogucan Haspolat     dogucan haspolat
12          Dusko Tosic          dusko tosic
13       Erdem Canpolat       erdem canpolat
14    Ertugrul Taskiran    ertugrul taskiran
15    Evren Eren Elmali    evren eren elmali
16       Feyzi Yildirim       feyzi yildirim
17  Florent Hadergjonaj  florent hadergjonaj
18       Furkan Külekci       furkan kulekci
19         Gerard Gohou         gerard gohou
20      Gilbert Koomson      gilbert koomson
21   Haris Hajradinovic   haris hajradinovic
22   Isaac Kiese Thelin   isaac kiese thelin
23      Julian Jeanvier      julian jeanvier
24          Kevin Varga          kevin varga
25  Kristijan Bistrovic  kristijan bistrovic
26         Loret Sadiku         loret sadiku
27     Mehmet Enes Sari     mehmet enes sari
28       Mickaël Tirpan       mickael tirpan
29      Oussama Haddadi      oussama haddadi
30         Ramazan Köse         ramazan kose
31       Tarkan Serbest       tarkan serbest
32         Tomas Brecka         tomas brecka
33         Yasin Dülger         yasin dulger
34        Yusuf Erdogan        yusuf erdogan

============================================================
  Kayserispor  —  SF sin salario:

             player  minutesPlayed
0  Anthony Uzodimma            153
1     Kevin Brobbey            539
2       Mario Šitum             90

  CG plantilla completa:

                   player            player_norm
0            Aaron Lennon           aaron lennon
1       Abdulkadir Tasdan      abdulkadir tasdan
2              Adem Dogan             adem dogan
3           Anton Maglica          anton maglica
4             Aziz Behich            aziz behich
5          Besard Sabovic         besard sabovic
6       Cristian Sapunaru      cristian sapunaru
7       Daniel Avramovski      daniel avramovski
8            Denis Alibec           denis alibec
9   Dimitrios Kolovetsios  dimitrios kolovetsios
10          Dogan Alemdar          dogan alemdar
11             Emre Demir             emre demir
12     Gustavo Campanharo     gustavo campanharo
13       Harrison Manzala       harrison manzala
14     Hasan Hüseyin Acar     hasan huseyin acar
15             Ilhan Depe             ilhan depe
16           Ilhan Parlak           ilhan parlak
17            Ismail Cipe            ismail cipe
18         Joseph Attamah         joseph attamah
19            Karlo Muhar            karlo muhar
20        Kevin Luckassen        kevin luckassen
21       Manuel Fernandes       manuel fernandes
22           Melih Okutan           melih okutan
23           Miguel Lopes           miguel lopes
24           Mugdat Celik           mugdat celik
25             Nehuén Paz             nehuen paz
26       Nurettin Korkmaz       nurettin korkmaz
27          Oguzhan Capar          oguzhan capar
28              Ömer Uzun              omer uzun
29         Pedro Henrique         pedro henrique
30        Ramazan Civelek        ramazan civelek
31         Silviu Lung Jr         silviu lung jr
32           Ugur Demirok           ugur demirok
33         Wilfried Kanga         wilfried kanga
34           Yasir Subasi           yasir subasi
35              Yaw Ackah              yaw ackah
36           Zoran Kvrzic           zoran kvrzic

============================================================
  Konyaspor  —  SF sin salario:

   player  minutesPlayed
0  Thuram              9

  CG plantilla completa:

                 player          player_norm
0   Abdülkerim Bardakci  abdulkerim bardakci
1         Adil Demirbag        adil demirbag
2           Ahmet Calik          ahmet calik
3       Ahmet Karademir      ahmet karademir
4          Ali Karakaya         ali karakaya
5          Alper Uludag         alper uludag
6       Amar Rahmanovic      amar rahmanovic
7   Amir Hadziahmetovic  amir hadziahmetovic
8         Artem Kravets        artem kravets
9        Baris Yardimci       baris yardimci
10       Deni Milosevic       deni milosevic
11         Dogan Gölpek         dogan golpek
12        Emre Pehlivan        emre pehlivan
13        Eray Birnican        eray birnican
14           Erdon Daci           erdon daci
15           Erten Ersu           erten ersu
16          Farouk Miya          farouk miya
17            Guilherme            guilherme
18        Ibrahim Sehic        ibrahim sehic
19      Ismaël Diomandé      ismael diomande
20         Ismail Güven         ismail guven
21       Izzet Karaboga       izzet karaboga
22       Jesse Sekidika       jesse sekidika
23      Levan Shengelia      levan shengelia
24         Marin Anicic         marin anicic
25       Marko Jevtovic       marko jevtovic
26         Musa Cagiran         musa cagiran
27          Nejc Skubic          nejc skubic
28  Oguz Kagan Güctekin  oguz kagan guctekin
29     Ömer Ali Sahiner     omer ali sahiner
30        Ozan Can Oruc        ozan can oruc
31        Paolo Hurtado        paolo hurtado
32         Samuel Eduok         samuel eduok
33           Sener Kaya           sener kaya
34     Serkan Kirintili     serkan kirintili
35     Sokol Cikalleshi     sokol cikalleshi
36         Ugur Demirok         ugur demirok
37      Volkan Findikli      volkan findikli
38         Zymer Bytyqi         zymer bytyqi

============================================================
  Trabzonspor  —  SF sin salario:

              player  minutesPlayed
0  Abdurrahim Dursun            134
1   Kağan Moradaoğlu             90

  CG plantilla completa:

                  player           player_norm
0        Abdülkadir Ömür       abdulkadir omur
1      Abdulkadir Parmak     abdulkadir parmak
2           Ahmet Canbaz          ahmet canbaz
3        Ahmetcan Kaplan       ahmetcan kaplan
4   Anastasios Bakasetas  anastasios bakasetas
5        Anders Trondsen       anders trondsen
6       Anthony Nwakaeme      anthony nwakaeme
7           Arda Akbulut          arda akbulut
8          Atakan Gündüz         atakan gunduz
9            Benik Afobe           benik afobe
10         Berat Özdemir         berat ozdemir
11     Bilal Basacikoglu     bilal basacikoglu
12          Caleb Ekuban          caleb ekuban
13               Djaniny               djaniny
14              Edgar Ié              edgar ie
15        Erce Kardesler        erce kardesler
16        Faruk Can Genc        faruk can genc
17                Flávio                flavio
18      Fousseni Diabaté      fousseni diabate
19          Gastón Campi          gaston campi
20           Hakan Yesil           hakan yesil
21       Hüseyin Türkmen       huseyin turkmen
22          João Pereira          joao pereira
23   Kamil Ahmet Cörekci   kamil ahmet corekci
24           Lewis Baker           lewis baker
25        Majid Hosseini        majid hosseini
26                Marlon                marlon
27    Muhammet Taha Tepe    muhammet taha tepe
28           Safa Kinali           safa kinali
29        Salih Kavrazli        salih kavrazli
30           Serkan Asan           serkan asan
31          Stiven Plaza          stiven plaza
32       Süleyman Cebeci       suleyman cebeci
33         Ugurcan Cakir         ugurcan cakir
34            Vitor Hugo            vitor hugo
35           Yunus Malli           yunus malli
36            Yusuf Sari            yusuf sari

============================================================
  Çaykur Rizespor  —  SF sin salario:

         player  minutesPlayed
0  Nadir Çiftçi             25

  CG plantilla completa:

                    player             player_norm
0           Abdullah Durak          abdullah durak
1               Alberk Koc              alberk koc
2      Alexander Söderlund     alexander soderlund
3               Aminu Umar              aminu umar
4          Bogachan Kazmaz         bogachan kazmaz
5           Braian Samudio          braian samudio
6          Damjan Djokovic         damjan djokovic
7            Dario Melnjak           dario melnjak
8   Dimitrios Chatziisaias  dimitrios chatziisaias
9            Dogan Erdogan           dogan erdogan
10          Dusan Jovancic          dusan jovancic
11               Emir Dede               emir dede
12            Emir Dilaver            emir dilaver
13           Emirhan Topcu           emirhan topcu
14               Erik Sabo               erik sabo
15         Fabrício Baiano         fabricio baiano
16        Fernando Andrade        fernando andrade
17        Fernando Boldrin        fernando boldrin
18          Godfred Donsah          godfred donsah
19            Gökhan Akkan            gokhan akkan
20         Ismaël Diomandé         ismael diomande
21          Ismail Köybasi          ismail koybasi
22            Kemal Rüzgar            kemal ruzgar
23         Konrad Michalak         konrad michalak
24               Loïc Rémy               loic remy
25             Milan Skoda             milan skoda
26             Mithat Pala             mithat pala
27         Montassar Talbi         montassar talbi
28            Murat Saglam            murat saglam
29         Mykola Morozyuk         mykola morozyuk
30              Onur Bulut              onur bulut
31                Selim Ay                selim ay
32             Tarik Cetin             tarik cetin
33             Tunay Torun             tunay torun
34          Yasin Pehlivan          yasin pehlivan
35          Yassine Meriah          yassine meriah
36            Zafer Görgen            zafer gorgen

In [54]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('souza', 'besiktas jk')                    : ('josef', 'besiktas jk'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [55]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: souza (besiktas jk) → josef (besiktas jk)

Tras matches manuales: 631/660 (95.6%)

In [56]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [57]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_turkey_2021.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_turkey_2021.csv
   Jugadores totales:  660
   Con salario:        631
   Sin salario (NaN):  29
   Columnas:           121