# 03 · Join Sofascore + Capology — Turkey Süper Lig 23/24

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2023/24 de Süper Lig turca**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_turkey_2324.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_turkey_2324.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  632 jugadores | 116 columnas
Capology:   731 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   basaksehir fk
   besiktas jk
   fatih karagumruk
   gaziantep fk
   kasmpasa
   mke ankaragucu

En Capology pero no en Sofascore:
   ankaragucu
   basaksehir
   besiktas
   gaziantep bb
   karagumrukspor
   kasimpasa

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'ankaragucu':'mke ankaragucu',
            'basaksehir':'basaksehir fk',
            'besiktas':'besiktas jk',
            'gaziantep bb':'gaziantep fk',
            'karagumrukspor':'fatih karagumruk',
            'kasimpasa':'kasmpasa'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 542/632 (85.8%)
Sin emparejar: 90

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          22
Revisión media    (0.75 ≤ score < 0.90):   25
Revisión estricta (0.50 ≤ score < 0.75):   31
Revisión muy est. (score < 0.50):           12

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf             team               cg_match  score
20  Bakhtiyar Zaynutdinov      Beşiktaş JK   baktiyar zaynutdinov  0.976
51   Dimitris Kolovetsios      Kayserispor  dimitrios kolovetsios  0.976
72  Ahmet Kağan Malatyalı      Kayserispor  ahmet kagan malatyali  0.976
26     Husniddin Alikulov  Çaykur Rizespor    khusniddin alikulov  0.973
52       Talha Sariarslan      Kayserispor        talha sararslan  0.968
65       Tunahan Samdanli     İstanbulspor        tunahan samdanl  0.968
89       Alperen Kuyubaşı   MKE Ankaragücü       alperen kuyubasi  0.968
27       Şener Özbayraklı    Başakşehir FK       sener ozbayrakli  0.968
13       Jakub Kałuziński      Antalyaspor       jakub kaluzinski  0.968
12        Rafał Gikiewicz   MKE Ankaragücü        rafal gikiewicz  0.966
59          Dries Saddiki        Kasımpaşa         driess saddiki  0.963
22          Renat Dadaşov        Hatayspor         renat dadashov  0.963
9         Steven​ N'Zonzi        Konyaspor          steven nzonzi  0.963
24          Samet Akaydın       Fenerbahçe          samet akaydin  0.960
3           Bilal Bayazit      Kayserispor           bilal bayazt  0.960
60          Yunus Bahadir       Alanyaspor           yunus bahadr  0.960
10           Jakub Słowik        Konyaspor           jakub slowik  0.957
31            Mert Yilmaz      Antalyaspor             mert ylmaz  0.952
45            Yunus Malli        Konyaspor             yunus mall  0.952
33       Andrej Đokanović   MKE Ankaragücü      andrej djokanovic  0.938
64          Abat Aimbetov  Adana Demirspor          abat aymbetov  0.923
11        Charis Charisis        Sivasspor     charilaos charisis  0.909

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                  player_sf             team              cg_match  score
75   Muhammet Ali Özbaskıcı       Samsunspor      muhammet ozbaskc  0.889
8      Bahadır Han Güngördü   MKE Ankaragücü       bahadr gungordu  0.882
43        Trazie Thomas Zai        Kasımpaşa         trazie thomas  0.867
1       Poyraz Efe Yıldırım      Trabzonspor          poyraz yldrm  0.857
88          Hasan Yesilyurt        Kasımpaşa  hasan emre yesilyurt  0.857
71          Muhammed Arıkan      Kayserispor   muhammed eren arkan  0.848
0             Đorđe Nikolić        Sivasspor       djordje nikolic  0.846
53          Baran Ali Gezek      Kayserispor           baran gezek  0.846
14              Engin Aksoy        Hatayspor       engin can aksoy  0.846
81        Furkan Onur Akyüz       Fenerbahçe          furkan akyuz  0.828
19              Yunus Konak        Sivasspor      yunus emre konak  0.815
55        Taylan Utku Aydın        Kasımpaşa           taylan aydn  0.815
42       Tayyip Talha Sanuç      Beşiktaş JK          tayyip sanuc  0.800
18      Kartal Kayra Yılmaz      Kayserispor          kartal ylmaz  0.800
6      Berat Ayberk Özdemir      Trabzonspor         berat ozdemir  0.788
23     Serkan Emrecan Terzi      Beşiktaş JK         emrecan terzi  0.788
40            Philippe Keny    Başakşehir FK  philippe paulin keny  0.788
44     Joher Khadim Rassoul       Pendikspor         joher rassoul  0.788
17       Recep Burak Yılmaz        Hatayspor           burak ylmaz  0.786
29        Haluk Mustafa Tan       Samsunspor           mustafa tan  0.786
82      Mehmet Şamil Öztürk      Kayserispor          samil ozturk  0.774
86        Yasin Yağız Dilek    Başakşehir FK            yagz dilek  0.769
30         Ömer Faruk Beyaz        Hatayspor            omer beyaz  0.769
25  Babajide David Akintola  Çaykur Rizespor        david akintola  0.757
28         Demir Ege Tıknaz      Beşiktaş JK             ege tknaz  0.750

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 25 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                  player_sf              team              cg_match  score
46        Mehmet Eray Özbek       Kayserispor            eray ozbek  0.741
16              Eren Elmalı       Trabzonspor     evren eren elmali  0.741
58        Tuncer Duhan Aksu         Kasımpaşa            duhan aksu  0.741
78        Maximiliano Gómez       Trabzonspor            maxi gomez  0.741
57         Yakup Arda Kılıç       Beşiktaş JK              arda klc  0.727
87    Muhammet Berkay Tekke      İstanbulspor          berkay tekke  0.727
5        Barış Alper Yılmaz       Galatasaray          baris yilmaz  0.714
4         Mahmoud Trézéguet       Trabzonspor             trezeguet  0.692
21      Mutassim Al-Musrati       Beşiktaş JK            al musrati  0.690
84       Bunyamin Cetinkaya         Kasımpaşa       erdem cetinkaya  0.667
56             Óscar Pinchi   Çaykur Rizespor                pinchi  0.667
32     Seyfettin Anıl Yaşar   Çaykur Rizespor             anl yasar  0.643
74             Baran Vardar      İstanbulspor              alp arda  0.600
83              Samet Duyur   Adana Demirspor      abdulsamet burak  0.593
70             Berat Kalkan         Kasımpaşa          erol karaman  0.583
2   Guilherme Haubert Sityá         Konyaspor             guilherme  0.562
7             Cherif Ndiaye   Adana Demirspor          badou ndiaye  0.560
61        Ali Sühan Demirel         Kasımpaşa  hasan emre yesilyurt  0.541
69                 Fahri Ay       Beşiktaş JK           eric bailly  0.526
48              Yunus Akgün       Galatasaray          gunay guvenc  0.522
54          Bertuğ Yıldırım         Hatayspor           burak ylmaz  0.522
63           Nicholas Anwan  Fatih Karagümrük         kevin lasagna  0.519
67            Eren Arda Şan      İstanbulspor        alperen caylak  0.519
85              Enes Gökcek       Kayserispor      stephane bahoken  0.519
79            Yusuf Akçiçek        Fenerbahçe           dusan tadic  0.500
39         Doğucan Haspolat       Trabzonspor          ugurcan cakr  0.500
36              Hasan Kılıç        Pendikspor       alpaslan ozturk  0.500
47   Emir Mustafa Vuruşaner      İstanbulspor    emir kaan gultekin  0.500
68           Demir Mermerci      İstanbulspor            murat eser  0.500
66                 Onur Arı         Hatayspor         oguzhan matur  0.500
41              Adem Ljajić  Fatih Karagümrük     andrea bertolacci  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['mehmet eray ozbek',
                    'eren elmal',
                    'tuncer duhan aksu',
                    'maximiliano gomez',
                    'yakup arda klc',
                    'muhammet berkay tekke',
                    'bars alper ylmaz',
                    'mahmoud trezeguet',
                    'mutassim al musrati',
                    'bunyamin cetinkaya',
                    'oscar pinchi',
                    'seyfettin anl yasar',
                    'guilherme haubert sitya'
]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 13

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf             team            cg_match  score
80   Deniz Eren Dönmezer  Adana Demirspor      stiven mendoza  0.485
38       Konrad Michalak        Konyaspor  alexandru cicaldau  0.485
15  Marius Mouandilmadji       Samsunspor           marc bola  0.483
50        Douglas Tanque       Samsunspor         mustafa tan  0.480
76        Altay Bayındır       Fenerbahçe       samet akaydin  0.480
73          Musa Çağıran        Hatayspor          nazm ozcan  0.476
34                 Souza    Başakşehir FK        ousseynou ba  0.471
77           Ahmed Touba    Başakşehir FK         mehdi abeid  0.455
37        Giorgi Beridze   MKE Ankaragücü       tolga cigerci  0.444
62    Georgios Tzavellas       Pendikspor      leandro kappel  0.438
35            Azad Demir      Beşiktaş JK          ante rebic  0.400
49                 Fredy      Antalyaspor        erkan eyibil  0.353

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 602/632 (95.3%)
Sin salario:     30

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 30

,player,team,minutesPlayed,appearances,goals,assists
0,Cherif Ndiaye,Adana Demirspor,167,2,1,1
1,Deniz Eren Dönmezer,Adana Demirspor,1,1,0,0
2,Samet Duyur,Adana Demirspor,1,1,0,0
3,Fredy,Antalyaspor,141,3,0,0
4,Souza,Başakşehir FK,407,11,0,1
5,Ahmed Touba,Başakşehir FK,57,1,0,0
6,Fahri Ay,Beşiktaş JK,91,2,0,0
7,Azad Demir,Beşiktaş JK,13,1,0,0
8,Adem Ljajić,Fatih Karagümrük,83,2,0,0
9,Nicholas Anwan,Fatih Karagümrük,26,3,0,0
10,Altay Bayındır,Fenerbahçe,90,1,0,0
11,Yusuf Akçiçek,Fenerbahçe,1,1,0,0
12,Yunus Akgün,Galatasaray,26,1,0,0
13,Bertuğ Yıldırım,Hatayspor,260,3,1,0
14,Onur Arı,Hatayspor,19,3,0,0
15,Musa Çağıran,Hatayspor,10,2,0,0
16,Ali Sühan Demirel,Kasımpaşa,11,1,0,0
17,Berat Kalkan,Kasımpaşa,11,1,0,0
18,Enes Gökcek,Kayserispor,1,1,0,0
19,Konrad Michalak,Konyaspor,227,4,0,1
20,Giorgi Beridze,MKE Ankaragücü,45,1,0,0
21,Georgios Tzavellas,Pendikspor,45,1,0,0
22,Hasan Kılıç,Pendikspor,29,1,0,0
23,Marius Mouandilmadji,Samsunspor,2080,30,9,1
24,Douglas Tanque,Samsunspor,21,1,0,0
25,Doğucan Haspolat,Trabzonspor,95,3,0,0
26,Baran Vardar,İstanbulspor,112,3,0,0
27,Eren Arda Şan,İstanbulspor,52,6,0,0
28,Demir Mermerci,İstanbulspor,16,2,0,0
29,Emir Mustafa Vuruşaner,İstanbulspor,10,2,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Adana Demirspor  —  SF sin salario:

                player  minutesPlayed
0        Cherif Ndiaye            167
1  Deniz Eren Dönmezer              1
2          Samet Duyur              1

  CG plantilla completa:

                      player               player_norm
0              Abat Aymbetov             abat aymbetov
1           Abdulsamet Burak          abdulsamet burak
2          Abdurrahim Dursun         abdurrahim dursun
3             Amir Feratovic            amir feratovic
4          Andreaw Gravillon         andreaw gravillon
5               Arbër Zeneli              arber zeneli
6               Badou Ndiaye              badou ndiaye
7         Benjamin Stambouli        benjamin stambouli
8             Breyton Fougeu            breyton fougeu
9               Burhan Ersoy              burhan ersoy
10            David Akintola            david akintola
11            Dorukhan Toköz            dorukhan tokoz
12            Edouard Michut            edouard michut
13               Emre Akbaba               emre akbaba
14               Ertac Özbir               ertac ozbir
15             Florent Shehu             florent shehu
16             Goran Karacic             goran karacic
17            Hamza Jaganjac            hamza jaganjac
18             Hijran Boyaci             hijran boyaci
19           İsmail Çokçalış            ismail cokcals
20               İzzet Çelik               izzet celik
21            Jonas Svensson            jonas svensson
22            José Rodríguez            jose rodriguez
23               Jovan Manev               jovan manev
24           Kévin Rodrigues           kevin rodrigues
25              M'Baye Niang              m baye niang
26                   Maestro                   maestro
27           Mario Balotelli           mario balotelli
28           Milad Mohammadi           milad mohammadi
29             Motez Nourani             motez nourani
30              Mustafa Kapı               mustafa kap
31              Nabil Alioui              nabil alioui
32                      Nani                      nani
33             Ozan Demirbağ             ozan demirbag
34           Pape Abou Cissé           pape abou cisse
35               Semih Güler               semih guler
36  Shahrudin Mahammadaliyev  shahrudin mahammadaliyev
37            Stiven Mendoza            stiven mendoza
38            Tayfun Aydoğan            tayfun aydogan
39             Vedat Karakuş             vedat karakus
40              Yılmaz Aktaş               ylmaz aktas
41               Youcef Atal               youcef atal
42           Younès Belhanda           younes belhanda
43              Yusuf Barası               yusuf baras
44             Yusuf Erdoğan             yusuf erdogan
45                Yusuf Sarı                 yusuf sar

============================================================
  Antalyaspor  —  SF sin salario:

  player  minutesPlayed
0  Fredy            141

  CG plantilla completa:

                  player           player_norm
0             Adam Buksa            adam buksa
1         Amar Gerxhaliu        amar gerxhaliu
2     Ataberk Dadakdeniz    ataberk dadakdeniz
3         Bahadır Öztürk         bahadr ozturk
4            Berat Pınar            berat pnar
5     Britt Assombalonga    britt assombalonga
6         Bünyamin Balcı         bunyamin balc
7            Dario Saric           dario saric
8         Deni Milosevic        deni milosevic
9          Doğukan Özkan         dogukan ozkan
10            Ege Bilsel            ege bilsel
11             Emre Uzun             emre uzun
12           Erdal Rakip           erdal rakip
13     Erdoğan Yeşilyurt     erdogan yesilyurt
14          Erkan Eyibil          erkan eyibil
15       Gerrit Holtmann       gerrit holtmann
16           Güray Vural           guray vural
17          Harun Toprak          harun toprak
18          Helton Leite          helton leite
19      Jakub Kaluzinski      jakub kaluzinski
20          Kağan Arıcan           kagan arcan
21           Mert Yılmaz            mert ylmaz
22      Mevlüthan Ekelik      mevluthan ekelik
23      Mustafa Erdilman      mustafa erdilman
24                 Naldo                 naldo
25           Ömer Toprak           omer toprak
26          Ramzi Safuri          ramzi safuri
27        Sagiv Jehezkel        sagiv jehezkel
28           Sam Larsson           sam larsson
29  Sander van de Streek  sander van de streek
30           Sinan Gümüs           sinan gumus
31            Ufuk Akyol            ufuk akyol
32           Veysel Sarı            veysel sar
33          Zymer Bytyqi          zymer bytyqi

============================================================
  Başakşehir FK  —  SF sin salario:

        player  minutesPlayed
0  Ahmed Touba             57
1        Souza            407

  CG plantilla completa:

                   player            player_norm
0           Batuhan Çelik          batuhan celik
1         Berkay Aydoğmuş        berkay aydogmus
2            Berkay Özcan           berkay ozcan
3       Burak Sefa Kavraz      burak sefa kavraz
4           Cemali Sertel          cemali sertel
5         Danijel Aleksic        danijel aleksic
6                Davidson               davidson
7            Deniz Dilmen           deniz dilmen
8             Deniz Türüç            deniz turuc
9        Dimitrios Pelkas       dimitrios pelkas
10            Eden Karzev            eden karzev
11               Edgar Ié               edgar ie
12       Efe Arda Koyuncu       efe arda koyuncu
13          Efecan Barlik          efecan barlik
14         Emirhan İlkhan         emirhan ilkhan
15        Emmanuel Dennis        emmanuel dennis
16          Eren Karaağaç          eren karaagac
17          Hamza Güreler          hamza gureler
18           Jerome Opoku           jerome opoku
19        João Figueiredo        joao figueiredo
20                  Josef                  josef
21       Krzysztof Piatek       krzysztof piatek
22             Léo Duarte             leo duarte
23             Léo Dubois             leo dubois
24             Lucas Lima             lucas lima
25        Mahmut Tekdemir        mahmut tekdemir
26            Mehdi Abeid            mehdi abeid
27  Mohamed Hassan Fofana  mohamed hassan fofana
28      Muhammed Şengezer      muhammed sengezer
29          Olivier Kemen          olivier kemen
30       Ömer Ali Şahiner       omer ali sahiner
31             Onur Ergün             onur ergun
32           Ousseynou Ba           ousseynou ba
33           Patryk Szysz           patryk szysz
34   Philippe Paulin Keny   philippe paulin keny
35       Sener Özbayrakli       sener ozbayrakli
36          Serdar Gürler          serdar gurler
37         Volkan Babacan         volkan babacan
38            Yağız Dilek             yagz dilek
39           Yusuf Yılmaz            yusuf ylmaz

============================================================
  Beşiktaş JK  —  SF sin salario:

       player  minutesPlayed
0  Azad Demir             13
1    Fahri Ay             91

  CG plantilla completa:

                     player              player_norm
0                Al-Musrati               al musrati
1   Alex Oxlade-Chamberlain  alex oxlade chamberlain
2       Amir Hadziahmetovic      amir hadziahmetovic
3                Ante Rebic               ante rebic
4                Arda Kılıç                 arda klc
5            Arthur Masuaku           arthur masuaku
6               Aytuğ Kömeç              aytug komec
7      Baktiyar Zaynutdinov     baktiyar zaynutdinov
8             Berkay Vardar            berkay vardar
9                Cenk Tosun               cenk tosun
10           Daniel Amartey           daniel amartey
11               Ege Tıknaz                ege tknaz
12          Emirhan Delibaş          emirhan delibas
13            Emrecan Bulut            emrecan bulut
14            Emrecan Terzi            emrecan terzi
15          Emrecan Uzunhan          emrecan uzunhan
16              Eric Bailly              eric bailly
17              Ernest Muci              ernest muci
18         Ersin Destanoğlu         ersin destanoglu
19         Gedson Fernandes         gedson fernandes
20             Gökhan İnler             gokhan inler
21          Göktuğ Baytekin          goktug baytekin
22           Jackson Muleka           jackson muleka
23               Jean Onana               jean onana
24              Joe Worrall              joe worrall
25           Jonas Svensson           jonas svensson
26               Mert Günok               mert gunok
27            Milot Rashica            milot rashica
28        Mustafa Hekimoğlu        mustafa hekimoglu
29              Necip Uysal              necip uysal
30              Omar Colley              omar colley
31               Onur Bulut               onur bulut
32           Rachid Ghezzal           rachid ghezzal
33               Salih Uçan               salih ucan
34           Semih Kılıçsoy             semih klcsoy
35            Tayfur Bingöl            tayfur bingol
36             Tayyip Sanuc             tayyip sanuc
37               Umut Meraş               umut meras
38           Utku Yuvakuran           utku yuvakuran
39          Valentin Rosier          valentin rosier
40        Vincent Aboubakar        vincent aboubakar

============================================================
  Fatih Karagümrük  —  SF sin salario:

           player  minutesPlayed
0     Adem Ljajić             83
1  Nicholas Anwan             26

  CG plantilla completa:

                 player          player_norm
0            Adnan Uğur           adnan ugur
1     Andrea Bertolacci    andrea bertolacci
2          Brahim Darri         brahim darri
3             Can Keles            can keles
4       Davide Biraschi      davide biraschi
5   Dimitrios Kourbelis  dimitrios kourbelis
6       Efecan Mızrakcı        efecan mzrakc
7           Emir Tintiş          emir tintis
8           Emre Bilgin          emre bilgin
9              Emre Mor             emre mor
10  Federico Ceccherini  federico ceccherini
11      Flavio Paoletti      flavio paoletti
12      Frédéric Veseli      frederic veseli
13      Furkan Bekleviç      furkan beklevic
14         Güven Yalçın          guven yalcn
15     Ibrahim Dresevic     ibrahim dresevic
16  Kerem Atakan Kesgin  kerem atakan kesgin
17        Kevin Lasagna        kevin lasagna
18         Koray Günter         koray gunter
19    Lawrence Nicholas    lawrence nicholas
20        Levent Mercan        levent mercan
21               Marcão               marcao
22        Marcus Rohdén        marcus rohden
23        Matías Dituro        matias dituro
24        Nazım Sangaré         nazm sangare
25           Ömer Ersoy           omer ersoy
26      Otabek Shukurov      otabek shukurov
27          Ryan Mendes          ryan mendes
28         Salih Dursun         salih dursun
29     Salvatore Sirigu     salvatore sirigu
30           Samed Onur           samed onur
31        Serdar Dursun        serdar dursun
32     Sofiane Feghouli     sofiane feghouli
33      Stefano Sturaro      stefano sturaro
34         Tarık Tuğyan          tark tugyan
35         Tonio Teklic         tonio teklic
36    Valentin Eysseric    valentin eysseric

============================================================
  Fenerbahçe  —  SF sin salario:

           player  minutesPlayed
0  Altay Bayındır             90
1   Yusuf Akçiçek              1

  CG plantilla completa:

                 player          player_norm
0       Alexander Djiku      alexander djiku
1          Bartug Elmaz         bartug elmaz
2   Bright Osayi-Samuel  bright osayi samuel
3        Çağlar Söyüncü       caglar soyuncu
4          Cengiz Ünder         cengiz under
5     Dominik Livakovic    dominik livakovic
6           Dusan Tadic          dusan tadic
7            Edin Dzeko           edin dzeko
8              Emre Mor             emre mor
9        Ferdi Kadıoğlu        ferdi kadoglu
10                 Fred                 fred
11         Furkan Akyüz         furkan akyuz
12  İrfan Can Eğribayat  irfan can egribayat
13    İrfan Can Kahveci    irfan can kahveci
14        İsmail Yüksek        ismail yuksek
15   Jayden Oosterwolde   jayden oosterwolde
16          Joshua King          joshua king
17     Leonardo Bonucci     leonardo bonucci
18              Lincoln              lincoln
19           Luan Peres           luan peres
20    Mert Hakan Yandaş    mert hakan yandas
21          Mert Müldür          mert muldur
22      Michy Batshuayi      michy batshuayi
23        Miguel Crespo        miguel crespo
24            Miha Zajc            miha zajc
25          Rade Krunic          rade krunic
26        Rodrigo Becão        rodrigo becao
27            Ryan Kent            ryan kent
28        Samet Akaydin        samet akaydin
29  Sebastian Szymanski  sebastian szymanski
30          Serdar Aziz          serdar aziz
31        Serdar Dursun        serdar dursun
32           Umut Nayir           umut nayir

============================================================
  Galatasaray  —  SF sin salario:

        player  minutesPlayed
0  Yunus Akgün             26

  CG plantilla completa:

                 player         player_norm
0   Abdülkerim Bardakcı  abdulkerim bardakc
1      Ali Turap Bülbül    ali turap bulbul
2         Ali Yeşilyurt       ali yesilyurt
3              Angeliño            angelino
4           Atakan Ordu         atakan ordu
5       Baran Demiroğlu     baran demiroglu
6          Baris Yilmaz        baris yilmaz
7          Berkan Kutlu        berkan kutlu
8       Carlos Vinícius     carlos vinicius
9        Cédric Bakambu      cedric bakambu
10     Davinson Sánchez    davinson sanchez
11         Derrick Köhn        derrick kohn
12        Dries Mertens       dries mertens
13            Efe Akman           efe akman
14           Eyüp Aydın           eyup aydn
15     Fernando Muslera    fernando muslera
16         Günay Güvenç        gunay guvenc
17         Hakim Ziyech        hakim ziyech
18     Halil Dervisoglu    halil dervisoglu
19          Hamza Akman         hamza akman
20        Jankat Yılmaz        jankat ylmaz
21           Kaan Ayhan          kaan ayhan
22     Kazimcan Karatas    kazimcan karatas
23     Kerem Aktürkoğlu    kerem akturkoglu
24       Kerem Demirbay      kerem demirbay
25       Lucas Torreira      lucas torreira
26         Mauro Icardi        mauro icardi
27       Nicolò Zaniolo      nicolo zaniolo
28           Sacha Boey          sacha boey
29         Serge Aurier        serge aurier
30      Sérgio Oliveira     sergio oliveira
31      Tanguy Ndombélé     tanguy ndombele
32                 Tetê                tete
33       Victor Nelsson      victor nelsson
34        Wilfried Zaha       wilfried zaha

============================================================
  Hatayspor  —  SF sin salario:

            player  minutesPlayed
0  Bertuğ Yıldırım            260
1     Musa Çağıran             10
2         Onur Arı             19

  CG plantilla completa:

                 player          player_norm
0     Abdulkadir Parmak    abdulkadir parmak
1            Ali Yıldız             ali yldz
2          Armin Hodzic         armin hodzic
3       Burak Bekaroglu      burak bekaroglu
4          Burak Yılmaz          burak ylmaz
5     Carlos Strandberg    carlos strandberg
6         Cemali Sertel        cemali sertel
7          Cengiz Demir         cengiz demir
8     Chandrel Massanga    chandrel massanga
9        Demir Sarıcalı         demir sarcal
10     Didier Lamkel Zé     didier lamkel ze
11        Doğukan Sinik        dogukan sinik
12           Emir Dadük           emir daduk
13      Engin Can Aksoy      engin can aksoy
14       Erce Kardeşler       erce kardesler
15       Faouzi Ghoulam       faouzi ghoulam
16  Fisayo Dele-Bashiru  fisayo dele bashiru
17     Giorgi Aburjania     giorgi aburjania
18        Görkem Sağlam        gorkem saglam
19  Guy-Marcelin Kilama  guy marcelin kilama
20     Halil Dervişoğlu     halil dervisoglu
21        Ibrahim Demir        ibrahim demir
22    Joelson Fernandes    joelson fernandes
23  Kamil Ahmet Çörekçi  kamil ahmet corekci
24          Kerim Alıcı            kerim alc
25      Mehdi Boudjemaa      mehdi boudjemaa
26          Nazım Özcan           nazm ozcan
27    Nikola Maksimovic    nikola maksimovic
28        Oğuzhan Matur        oguzhan matur
29           Ömer Beyaz           omer beyaz
30         Rayane Aabid         rayane aabid
31       Renat Dadashov       renat dadashov
32      Rigoberto Rivas      rigoberto rivas
33            Rui Pedro            rui pedro
34          Visar Bekaj          visar bekaj

============================================================
  Kasımpaşa  —  SF sin salario:

              player  minutesPlayed
0  Ali Sühan Demirel             11
1       Berat Kalkan             11

  CG plantilla completa:

                  player           player_norm
0            Adnan Aktaş           adnan aktas
1         Ali Emre Yanar        ali emre yanar
2     Andreas Gianniotis    andreas gianniotis
3             Aytaç Kara            aytac kara
4          Cláudio Winck         claudio winck
5         Driess Saddiki        driess saddiki
6             Duhan Aksu            duhan aksu
7          Emirhan Yiğit         emirhan yigit
8             Emre Gedik            emre gedik
9        Erdem Çetinkaya       erdem cetinkaya
10          Erol Karaman          erol karaman
11            Gökhan Gül            gokhan gul
12    Haris Hajradinovic    haris hajradinovic
13  Hasan Emre Yesilyurt  hasan emre yesilyurt
14            Iron Gomis            iron gomis
15        Jackson Porozo        jackson porozo
16           Julien Ngoy           julien ngoy
17        Kenneth Omeruo        kenneth omeruo
18          Loret Sadiku          loret sadiku
19          Mamadou Fall          mamadou fall
20           Melih Akyüz           melih akyuz
21   Mortadha Ben Ouanes   mortadha ben ouanes
22      Murat Can Yildiz      murat can yildiz
23         Nuno Da Costa         nuno da costa
24      Oğulcan Çağlayan      ogulcan caglayan
25              Rochinha              rochinha
26       Sadık Çiftpınar         sadk ciftpnar
27        Samuel Bastien        samuel bastien
28          Sarp Yavrucu          sarp yavrucu
29           Selim Dilli           selim dilli
30          Taylan Aydın           taylan aydn
31         Trazié Thomas         trazie thomas
32           Yasin Özcan           yasin ozcan

============================================================
  Kayserispor  —  SF sin salario:

        player  minutesPlayed
0  Enes Gökcek              1

  CG plantilla completa:

                   player            player_norm
0       Abdulkadir Taşdan      abdulkadir tasdan
1   Ahmet Kagan Malatyali  ahmet kagan malatyali
2              Ali Karimi             ali karimi
3        Anthony Uzodimma       anthony uzodimma
4            Arif Kocaman           arif kocaman
5        Aylton Boa Morte       aylton boa morte
6             Baran Gezek            baran gezek
7           Bilal Bayazıt           bilal bayazt
8             Carlos Mané            carlos mane
9   Dimitrios Kolovetsios  dimitrios kolovetsios
10          Duckens Nazon          duckens nazon
11             Eray Özbek             eray ozbek
12         Gökhan Sazdağı          gokhan sazdag
13     Hasan Ali Kaldırım       hasan ali kaldrm
14        Hayrullah Erkip        hayrullah erkip
15         Joseph Attamah         joseph attamah
16        Julian Jeanvier        julian jeanvier
17          Kartal Yılmaz           kartal ylmaz
18          Lionel Carole          lionel carole
19         Majid Hosseini         majid hosseini
20             Mame Thiam             mame thiam
21         Mehdi Bourabia         mehdi bourabia
22         Miguel Cardoso         miguel cardoso
23   Muhammed Eren Arıkan    muhammed eren arkan
24          Olivier Kemen          olivier kemen
25           Onurcan Piri           onurcan piri
26        Otabek Shukurov        otabek shukurov
27        Ramazan Civelek        ramazan civelek
28           Şamil Öztürk           samil ozturk
29       Stéphane Bahoken       stephane bahoken
30       Talha Sarıarslan        talha sararslan
31              Yaw Ackah              yaw ackah
32      Yiğit Emre Çeltik      yigit emre celtik

============================================================
  Konyaspor  —  SF sin salario:

            player  minutesPlayed
0  Konrad Michalak            227

  CG plantilla completa:

                   player            player_norm
0           Adil Demirbağ          adil demirbag
1              Ahmet Oğuz             ahmet oguz
2           Alassane Ndao          alassane ndao
3      Alexandru Cicâldău     alexandru cicaldau
4        Anderson Niangbo       anderson niangbo
5       Ata Berk Karababa      ata berk karababa
6     Bouly Junior Sambou    bouly junior sambou
7               Bruno Paz              bruno paz
8         Cebrail Karayel        cebrail karayel
9             Deniz Ertaş            deniz ertas
10       Emmanuel Boateng       emmanuel boateng
11        Emrehan Gedikli        emrehan gedikli
12       Filip Damjanovic       filip damjanovic
13        Francisco Calvo        francisco calvo
14            Gökhan Töre            gokhan tore
15              Guilherme              guilherme
16           Jakub Slowik           jakub slowik
17      Kahraman Demirtaş      kahraman demirtas
18             Louka Prip             louka prip
19          Marlos Moreno          marlos moreno
20  Mehmet Ali Büyüksayar  mehmet ali buyuksayar
21         Mehmet Erdoğan         mehmet erdogan
22           Metehan Mert           metehan mert
23         Muhammet Demir         muhammet demir
24        Nélson Oliveira        nelson oliveira
25               Niko Rak               niko rak
26          Oğulcan Ülgün          ogulcan ulgun
27        Paul Bernardoni        paul bernardoni
28           Robert Muric           robert muric
29       Sokol Cikalleshi       sokol cikalleshi
30           Soner Dikmen           soner dikmen
31          Steven Nzonzi          steven nzonzi
32         Teenage Hadebe         teenage hadebe
33        Uğurcan Yazğılı          ugurcan yazgl
34           Valon Ethemi           valon ethemi
35           Yasir Subaşı            yasir subas
36            Yunus Mallı             yunus mall

============================================================
  MKE Ankaragücü  —  SF sin salario:

           player  minutesPlayed
0  Giorgi Beridze             45

  CG plantilla completa:

                       player                player_norm
0           Abdurrahim Dursun          abdurrahim dursun
1                Alexis Flips               alexis flips
2            Ali Kaan Güneren           ali kaan guneren
3                    Ali Sowe                   ali sowe
4                Alper Uludağ               alper uludag
5            Alperen Kuyubasi           alperen kuyubasi
6   Anastasios Chatzigiovanis  anastasios chatzigiovanis
7           Andrej Djokanovic          andrej djokanovic
8                  Arda Kumru                 arda kumru
9                  Arda Ünyay                 arda unyay
10             Atakan Çankaya             atakan cankaya
11           Bahadır Güngördü            bahadr gungordu
12                Cem Türkmen                cem turkmen
13         Christian Bassogog         christian bassogog
14               Dogukan Kaya               dogukan kaya
15            Efkan Bekiroğlu            efkan bekiroglu
16               Enes Tepecik               enes tepecik
17              Enock Kwateng              enock kwateng
18                Ertaç Özbir                ertac ozbir
19           Federico Macheda           federico macheda
20            Garry Rodrigues            garry rodrigues
21          Hayrullah Bilazer          hayrullah bilazer
22           Kazımcan Karataş            kazmcan karatas
23             Matej Hanousek             matej hanousek
24                   Mert Can                   mert can
25                 Mert Çetin                 mert cetin
26              Nihad Mujakic              nihad mujakic
27            Olimpiu Moruţan            olimpiu morutan
28              Onur Efe Ekri              onur efe ekri
29                   Pedrinho                   pedrinho
30            Rafal Gikiewicz            rafal gikiewicz
31             Renaldo Cephas             renaldo cephas
32                 Riad Bajic                 riad bajic
33          Riccardo Saponara          riccardo saponara
34    Sirozhiddin Astanakulov    sirozhiddin astanakulov
35            Stelios Kitsiou            stelios kitsiou
36              Tolga Ciğerci              tolga cigerci
37             Uros Radakovic             uros radakovic
38          Yusuf Eren Göktas          yusuf eren goktas

============================================================
  Pendikspor  —  SF sin salario:

               player  minutesPlayed
0  Georgios Tzavellas             45
1         Hasan Kılıç             29

  CG plantilla completa:

              player      player_norm
0     Abdoulay Diaby   abdoulay diaby
1       Ahmed Hassan     ahmed hassan
2        Aias Aosman      aias aosman
3    Alpaslan Öztürk  alpaslan ozturk
4     Arnaud Lusamba   arnaud lusamba
5       Badou Ndiaye     badou ndiaye
6    Berkay Sülüngöz  berkay sulungoz
7         Burak Öğür       burak ogur
8         Efe Sayhan       efe sayhan
9          Emeka Eze        emeka eze
10     Emre Taşdemir    emre tasdemir
11      Endri Cekici     endri cekici
12       Erdem Çalık       erdem calk
13    Erdem Canpolat   erdem canpolat
14      Erdem Özgenç     erdem ozgenc
15  Erencan Yardımcı   erencan yardmc
16   Fredrik Midtsjø   fredrik midtsj
17       Gökcan Kaya      gokcan kaya
18      Görkem Bitin     gorkem bitin
19     Halil Akbunar    halil akbunar
20     Ibrahim Akdag    ibrahim akdag
21     Joher Rassoul    joher rassoul
22     Josip Vukovic    josip vukovic
23    Leandro Kappel   leandro kappel
24        Mame Thiam       mame thiam
25       Melih Güney      melih guney
26        Murat Akça       murat akca
27       Murat Akşit      murat aksit
28     Nuno Sequeira    nuno sequeira
29      Óscar Romero     oscar romero
30       Serkan Asan      serkan asan
31            Thuram           thuram
32     Umut Mert Toy    umut mert toy
33        Umut Nayir       umut nayir
34          Welinton         welinton

============================================================
  Samsunspor  —  SF sin salario:

                 player  minutesPlayed
0        Douglas Tanque             21
1  Marius Mouandilmadji           2080

  CG plantilla completa:

                   player            player_norm
0          Ali Taha Demir         ali taha demir
1             Alim Öztürk            alim ozturk
2             Arbnor Muja            arbnor muja
3          Bedirhan Çetin         bedirhan cetin
4            Benito Raman           benito raman
5            Berhan Deniz           berhan deniz
6             Carlo Holse            carlo holse
7             Emre Kılınç              emre klnc
8              Enes Albak             enes albak
9              Ercan Kara             ercan kara
10           Flavien Tait           flavien tait
11           Gaëtan Laura           gaetan laura
12            Halil Yeral            halil yeral
13          Jakub Szumski          jakub szumski
14     Kingsley Schindler     kingsley schindler
15          Landry Dimata          landry dimata
16          Lubomir Satka          lubomir satka
17              Marc Bola              marc bola
18                 Marius                 marius
19         Mickaël Tirpan         mickael tirpan
20          Moryké Fofana          moryke fofana
21       Muammer Yıldırım          muammer yldrm
22     Muhammed Gümüşkaya     muhammed gumuskaya
23     Muhammet Özbaskıcı       muhammet ozbaskc
24            Mustafa Tan            mustafa tan
25                   Nanu                   nanu
26             Okan Kocuk             okan kocuk
27         Olivier Ntcham         olivier ntcham
28            Osman Çelik            osman celik
29     Rick van Drongelen     rick van drongelen
30          Soner Aydoğdu          soner aydogdu
31            Soner Gönül            soner gonul
32             Taha Tosun             taha tosun
33       Taylan Antalyalı        taylan antalyal
34  Youssef Aït Bennasser  youssef ait bennasser
35        Yunus Emre Çift        yunus emre cift
36             Zeki Yavru             zeki yavru

============================================================
  Trabzonspor  —  SF sin salario:

             player  minutesPlayed
0  Doğucan Haspolat             95

  CG plantilla completa:

                  player           player_norm
0        Abdülkadir Ömür       abdulkadir omur
1   Anastasios Bakasetas  anastasios bakasetas
2            Arif Boşluk           arif bosluk
3          Batista Mendy         batista mendy
4          Berat Özdemir         berat ozdemir
5    Dimitrios Kourbelis   dimitrios kourbelis
6             Edin Visca            edin visca
7            Enis Bardhi           enis bardhi
8            Enis Destan           enis destan
9      Evren Eren Elmali     evren eren elmali
10        Filip Benkovic        filip benkovic
11         Göktan Gürpüz         goktan gurpuz
12       Hüseyin Türkmen       huseyin turkmen
13   Jens Stryger Larsen   jens stryger larsen
14     Joaquín Fernández     joaquin fernandez
15      Kağan Moradaoğlu      kagan moradaoglu
16             Kerem Şen             kerem sen
17            Maxi Gómez            maxi gomez
18          Mehmet Aydın           mehmet aydn
19          Mislav Orsic          mislav orsic
20    Muhammet Taha Tepe    muhammet taha tepe
21          Nicolas Pépé          nicolas pepe
22          Ognjen Bakic          ognjen bakic
23      Onuralp Çevikkan      onuralp cevikkan
24          Paul Onuachu          paul onuachu
25       Poyraz Yıldırım          poyraz yldrm
26         Rayyan Baniya         rayyan baniya
27       Stefano Denswil       stefano denswil
28       Süleyman Cebeci       suleyman cebeci
29    Taxiarchis Fountas    taxiarchis fountas
30        Thomas Meunier        thomas meunier
31          Tonio Teklic          tonio teklic
32             Trezeguet             trezeguet
33         Uğurcan Çakır          ugurcan cakr
34            Umut Bozok            umut bozok
35            Umut Güneş            umut gunes

============================================================
  İstanbulspor  —  SF sin salario:

                   player  minutesPlayed
0            Baran Vardar            112
1          Demir Mermerci             16
2  Emir Mustafa Vuruşaner             10
3           Eren Arda Şan             52

  CG plantilla completa:

                      player               player_norm
0              Alassane Ndao             alassane ndao
1                  Ali Yaşar                 ali yasar
2                   Alp Arda                  alp arda
3             Alperen Çaylak            alperen caylak
4               Bartu Kırtaş               bartu krtas
5               Berkay Tekke              berkay tekke
6               David Jensen              david jensen
7             David Sambissa            david sambissa
8            Demeaco Duhaney           demeaco duhaney
9   Djakaridja Junior Traoré  djakaridja junior traore
10              Eduart Rroca              eduart rroca
11                Egehan Gök                egehan gok
12        Emir Kaan Gültekin        emir kaan gultekin
13           Emrehan Gedikli           emrehan gedikli
14              Eslem Öztürk              eslem ozturk
15            Florian Loshaj            florian loshaj
16          Giannelli Imbula          giannelli imbula
17            Ibrahim Yilmaz            ibrahim yilmaz
18             İzzet Topatar             izzet topatar
19                   Jackson                   jackson
20               Kagan Bagis               kagan bagis
21             Kubilay Köylü             kubilay koylu
22              Mehmet Yeşil              mehmet yesil
23             Mendy Mamadou             mendy mamadou
24       Modestas Vorobjovas       modestas vorobjovas
25          Muammer Sarikaya          muammer sarikaya
26           Mücahit Serbest           mucahit serbest
27                Murat Eser                murat eser
28              Okan Erdoğan              okan erdogan
29               Özcan Şahan               ozcan sahan
30               Racine Coly               racine coly
31                Simon Deli                simon deli
32          Tunahan Şamdanlı           tunahan samdanl
33              Valon Ethemi              valon ethemi
34                Vefa Temel                vefa temel

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('marius mouandilmadji', 'samsunspor')    : ('marius', 'samsunspor')
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 1

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: marius mouandilmadji (samsunspor) → marius (samsunspor)

Tras matches manuales: 603/632 (95.4%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_turkey_2324.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_turkey_2324.csv
   Jugadores totales:  632
   Con salario:        603
   Sin salario (NaN):  29
   Columnas:           121