# 03 · Join Sofascore + Capology — Turkey Süper Lig 24/25

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2024/25 de Süper Lig turca**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_turkey_2425.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_turkey_2425.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  580 jugadores | 116 columnas
Capology:   637 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   basaksehir fk
   besiktas jk
   bodrum fk
   gaziantep fk
   kasmpasa

En Capology pero no en Sofascore:
   basaksehir
   besiktas
   bodrum
   gaziantep bb
   kasimpasa

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [7]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'basaksehir':'basaksehir fk',
            'besiktas':'besiktas jk',
            'bodrum':'bodrum fk',
            'gaziantep bb':'gaziantep fk',
            'kasimpasa':'kasmpasa'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [8]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 479/580 (82.6%)
Sin emparejar: 101

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [9]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          15
Revisión media    (0.75 ≤ score < 0.90):   24
Revisión estricta (0.50 ≤ score < 0.75):   38
Revisión muy est. (score < 0.50):           24

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [10]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf             team               cg_match  score
21  Przemysław Frankowski      Galatasaray  przemyslaw frankowski  0.976
46   Dimitris Kolovetsios      Kayserispor  dimitrios kolovetsios  0.976
47  Bakhtiyar Zaynutdinov      Beşiktaş JK   baktiyar zaynutdinov  0.976
11     Husniddin Alikulov  Çaykur Rizespor    khusniddin alikulov  0.973
53     Christophe Lungoyi     Gaziantep FK    christopher lungoyi  0.973
42       Talha Sariarslan      Kayserispor        talha sararslan  0.968
12       Kacper Kozłowski     Gaziantep FK       kacper kozlowski  0.968
10       Jakub Kałuziński      Antalyaspor       jakub kaluzinski  0.968
52          Celal Dumanli        Bodrum FK           celal dumanl  0.960
15          Bilal Bayazit      Kayserispor           bilal bayazt  0.960
29          Samet Akaydın  Çaykur Rizespor          samet akaydin  0.960
6            Jakub Słowik        Konyaspor           jakub slowik  0.957
40            Mert Yilmaz      Antalyaspor             mert ylmaz  0.952
54          Abat Aimbetov  Adana Demirspor          abat aymbetov  0.923
14        Charis Charisis        Sivasspor     charilaos charisis  0.909

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [11]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                  player_sf             team              cg_match  score
66   Muhammet Ali Özbaskıcı       Samsunspor      muhammet ozbaskc  0.889
71      Poyraz Efe Yıldırım      Trabzonspor          poyraz yldrm  0.857
20      Deniz Eren Dönmezer  Adana Demirspor        deniz donmezer  0.848
33            Đorđe Nikolić        Sivasspor       djordje nikolic  0.846
58          Baran Ali Gezek      Kayserispor           baran gezek  0.846
64    Godfrey Bitok Stephen     Gaziantep FK       godfrey stephen  0.833
89     Osman Ertuğrul Çetin       Fenerbahçe        ertugrul cetin  0.824
82        Taylan Utku Aydın        Kasımpaşa           taylan aydn  0.815
91       İzzet Furkan Malak          Göztepe          furkan malak  0.800
68       Tayyip Talha Sanuç      Beşiktaş JK          tayyip sanuc  0.800
41          Murat Uğur Eser  Adana Demirspor            murat eser  0.800
4       Kartal Kayra Yılmaz      Kayserispor          kartal ylmaz  0.800
36    Anthony Junior Dennis          Göztepe        anthony dennis  0.800
13     Berat Ayberk Özdemir    Başakşehir FK         berat ozdemir  0.788
59     Serkan Emrecan Terzi      Beşiktaş JK         emrecan terzi  0.788
39            Philippe Keny    Başakşehir FK  philippe paulin keny  0.788
94        Haluk Mustafa Tan       Samsunspor           mustafa tan  0.786
98          Yusuf Karademir       Alanyaspor         yusuf ozdemir  0.786
73              Taha Özmert      Antalyaspor     taha osman ozmert  0.786
48       Recep Burak Yılmaz        Hatayspor           burak ylmaz  0.786
56         Ömer Faruk Beyaz    Başakşehir FK            omer beyaz  0.769
62       Mehmet Talha Seker        Sivasspor           talha seker  0.759
92       Mert Furkan Bayram       Alanyaspor           mert bayram  0.759
31  Babajide David Akintola  Çaykur Rizespor        david akintola  0.757

In [12]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = ['yusuf karademir'
]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 23 | Excluidos: 1

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [13]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                  player_sf             team           cg_match  score
17              Eren Elmalı      Galatasaray  evren eren elmali  0.741
65        Mehmet Eray Özbek      Kayserispor         eray ozbek  0.741
37    Muhammed Birkan Tetik         Eyüpspor       birkan tetik  0.727
30   Muhammet Tunahan Taşçı        Konyaspor       tunahan tasc  0.727
90         Yakup Arda Kılıç      Beşiktaş JK           arda klc  0.727
5   Muhammed-Cham Saračević      Trabzonspor      muhammed cham  0.722
23         Thalisson Kelven      Antalyaspor          thalisson  0.720
3        Barış Alper Yılmaz      Galatasaray       baris yilmaz  0.714
43             Boran Başkan      Trabzonspor        serkan asan  0.696
16      Mutassim Al-Musrati      Beşiktaş JK         al musrati  0.690
95      Muhammed Sinan Kaya        Sivasspor         sinan kaya  0.690
80          Ali Osman Kalın     Gaziantep FK   ali mevran ablak  0.667
60                Berat Luş      Galatasaray       berkan kutlu  0.667
83             Armin Hodžić        Hatayspor       lamine diack  0.667
22                   Djalma          Göztepe       djalma silva  0.667
69     Seyfettin Anıl Yaşar  Çaykur Rizespor          anl yasar  0.643
63            Ersin Aydemir        Hatayspor       cengiz demir  0.640
1          Anderson Talisca       Fenerbahçe            talisca  0.609
19   Yusuf Bugra Demirkiran  Adana Demirspor        yusuf baras  0.606
51          Ali Arda Yildiz  Adana Demirspor    kadir karayigit  0.600
87              Mehmet Kaya        Konyaspor          ahmet das  0.600
86             Burak Arslan      Kayserispor    talha sararslan  0.593
85              Samet Duyur  Adana Demirspor   abdulsamet burak  0.593
77              Demir Yavuz  Adana Demirspor      ali yavuz kol  0.583
45               Sefa Gulay  Adana Demirspor        semih guler  0.571
93               Ali Tarkan       Samsunspor        halil yeral  0.571
9   Guilherme Haubert Sityá        Konyaspor          guilherme  0.562
24     Juan Santos da Silva          Göztepe       djalma silva  0.562
76                Cagan Tas     Gaziantep FK      omurcan artan  0.545
78        Berk Can Yildizli        Kasımpaşa      emirhan yigit  0.533
49           Ferdi Kadıoğlu       Fenerbahçe         edin dzeko  0.522
38              Tugay Kaçar         Eyüpspor       luccas claro  0.522
55              Kayra Cihan      Kayserispor       kartal ylmaz  0.522
75            Gokdeniz Tunc  Adana Demirspor     deniz donmezer  0.519
88              Rade Krunić       Fenerbahçe          ryan kent  0.500
35        Hasan Yakub İlçin      Antalyaspor        kagan arcan  0.500
0          Kerem Aktürkoğlu      Galatasaray       berkan kutlu  0.500
8            Jackson Muleka      Beşiktaş JK         joao mario  0.500

In [20]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['eren elmal',
                    'mehmet eray ozbek',
                    'muhammed birkan tetik',
                    'muhammet tunahan tasc',
                    'yakup arda klc',
                    'muhammed cham saracevic',
                    'thalisson kelven',
                    'bars alper ylmaz',
                    'mutassim al musrati',
                    'muhammed sinan kaya',
                    'djalma',
                    'seyfettin anl yasar',
                    'anderson talisca'
                    
                    
                    

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 13

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [21]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf             team          cg_match  score
28   Marius Mouandilmadji       Samsunspor         marc bola  0.483
61       Sokol Cikalleshi        Konyaspor     josip calusic  0.483
99            Ismail Zobu        Hatayspor    bilal boutobba  0.480
50         José Rodríguez  Adana Demirspor       semih guler  0.480
27            Burak Çoban        Bodrum FK    gabriel obekpa  0.480
2             Svit Sešlar         Eyüpspor    huseyin maldar  0.480
18            Omar Colley      Beşiktaş JK        joao mario  0.476
34             Yusuf Inci        Kasımpaşa       yasin ozcan  0.476
57          Yigit Ali Buz        Hatayspor          ali yldz  0.476
81            Deniz Aksoy        Hatayspor        emir daduk  0.476
67        Emrehan Gedikli        Konyaspor   adem eren kabak  0.467
7            Derrick Köhn      Galatasaray    victor osimhen  0.462
97         Tibet Durakcay          Göztepe      tugbey akgun  0.462
72        Berkay Topdemir      Antalyaspor       kenan piric  0.462
25            Yucel Gurol  Adana Demirspor       semih guler  0.455
79              Ali Fidan  Adana Demirspor     ali yavuz kol  0.455
74         Taha Emre Ince      Trabzonspor     batista mendy  0.444
26      Mahmoud Trézéguet      Trabzonspor        umut gunes  0.444
70         Édouard Michut  Adana Demirspor     arda kurtulan  0.444
32           Nevzat Gezer     Gaziantep FK       semih guler  0.435
96             Yilmaz Cin        Sivasspor     tolga cigerci  0.435
84         Ali Demirbilek      Antalyaspor    deni milosevic  0.429
100          Ahmet Yilmaz  Adana Demirspor  abdulsamet burak  0.429
44        Milad Mohammadi  Adana Demirspor   kadir karayigit  0.400

In [22]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [23]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 530/580 (91.4%)
Sin salario:     50

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [24]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 50

,player,team,minutesPlayed,appearances,goals,assists
0,Milad Mohammadi,Adana Demirspor,180,2,0,0
1,Yusuf Bugra Demirkiran,Adana Demirspor,172,3,0,0
2,Édouard Michut,Adana Demirspor,169,2,0,0
3,José Rodríguez,Adana Demirspor,144,2,0,0
4,Ali Arda Yildiz,Adana Demirspor,106,2,0,0
5,Gokdeniz Tunc,Adana Demirspor,61,1,0,0
6,Demir Yavuz,Adana Demirspor,29,1,0,0
7,Sefa Gulay,Adana Demirspor,20,1,0,0
8,Ali Fidan,Adana Demirspor,17,2,0,0
9,Yucel Gurol,Adana Demirspor,12,1,0,0
10,Samet Duyur,Adana Demirspor,8,1,0,0
11,Ahmet Yilmaz,Adana Demirspor,2,2,0,0
12,Yusuf Karademir,Alanyaspor,3,1,0,0
13,Hasan Yakub İlçin,Antalyaspor,126,2,0,0
14,Berkay Topdemir,Antalyaspor,34,2,0,0
15,Ali Demirbilek,Antalyaspor,10,1,0,0
16,Omar Colley,Beşiktaş JK,180,2,0,0
17,Jackson Muleka,Beşiktaş JK,11,1,0,0
18,Burak Çoban,Bodrum FK,60,1,0,0
19,Tugay Kaçar,Eyüpspor,37,3,0,0
20,Svit Sešlar,Eyüpspor,25,2,0,1
21,Ferdi Kadıoğlu,Fenerbahçe,104,2,0,0
22,Rade Krunić,Fenerbahçe,11,1,0,0
23,Kerem Aktürkoğlu,Galatasaray,174,3,2,2
24,Derrick Köhn,Galatasaray,87,1,0,0
25,Berat Luş,Galatasaray,12,1,0,0
26,Ali Osman Kalın,Gaziantep FK,33,1,0,0
27,Nevzat Gezer,Gaziantep FK,8,1,0,0
28,Cagan Tas,Gaziantep FK,8,1,0,0
29,Juan Santos da Silva,Göztepe,1659,26,7,3
30,Tibet Durakcay,Göztepe,1,1,0,0
31,Yigit Ali Buz,Hatayspor,212,4,1,0
32,Armin Hodžić,Hatayspor,101,4,0,0
33,Deniz Aksoy,Hatayspor,37,4,0,0
34,Ersin Aydemir,Hatayspor,9,1,0,0
35,Ismail Zobu,Hatayspor,1,1,0,0
36,Yusuf Inci,Kasımpaşa,67,4,0,0
37,Berk Can Yildizli,Kasımpaşa,17,4,0,0
38,Kayra Cihan,Kayserispor,98,3,0,0
39,Burak Arslan,Kayserispor,26,1,0,0
40,Guilherme Haubert Sityá,Konyaspor,3000,34,0,8
41,Emrehan Gedikli,Konyaspor,21,2,0,0
42,Sokol Cikalleshi,Konyaspor,12,1,0,0
43,Mehmet Kaya,Konyaspor,8,1,0,0
44,Marius Mouandilmadji,Samsunspor,2502,34,10,4
45,Ali Tarkan,Samsunspor,1,1,0,0
46,Yilmaz Cin,Sivasspor,1,1,0,0
47,Mahmoud Trézéguet,Trabzonspor,90,1,0,0
48,Boran Başkan,Trabzonspor,25,1,0,0
49,Taha Emre Ince,Trabzonspor,11,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [25]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Adana Demirspor  —  SF sin salario:

                    player  minutesPlayed
0             Ahmet Yilmaz              2
1          Ali Arda Yildiz            106
2                Ali Fidan             17
3              Demir Yavuz             29
4            Gokdeniz Tunc             61
5           José Rodríguez            144
6          Milad Mohammadi            180
7              Samet Duyur              8
8               Sefa Gulay             20
9              Yucel Gurol             12
10  Yusuf Bugra Demirkiran            172
11          Édouard Michut            169

  CG plantilla completa:

               player        player_norm
0       Abat Aymbetov      abat aymbetov
1    Abdulsamet Burak   abdulsamet burak
2         Aksel Aktaş        aksel aktas
3       Ali Yavuz Kol      ali yavuz kol
4   Andreaw Gravillon  andreaw gravillon
5       Arda Kurtulan      arda kurtulan
6      Breyton Fougeu     breyton fougeu
7      Bünyamin Balat     bunyamin balat
8        Burhan Ersoy       burhan ersoy
9      Deniz Dönmezer     deniz donmezer
10      Florent Shehu      florent shehu
11        İzzet Çelik        izzet celik
12        Jovan Manev        jovan manev
13    Kadir Karayiğit    kadir karayigit
14            Maestro            maestro
15      Motez Nourani      motez nourani
16         Murat Eser         murat eser
17       Nabil Alioui       nabil alioui
18       Osman Kaynak       osman kaynak
19      Ozan Demirbağ      ozan demirbag
20     Salih Kavrazlı      salih kavrazl
21        Semih Güler        semih guler
22     Tayfun Aydoğan     tayfun aydogan
23     Tolga Kalender     tolga kalender
24      Vedat Karakuş      vedat karakus
25       Yusuf Barası        yusuf baras
26         Yusuf Sarı          yusuf sar

============================================================
  Alanyaspor  —  SF sin salario:

            player  minutesPlayed
0  Yusuf Karademir              3

  CG plantilla completa:

                 player          player_norm
0         Andraz Sporar        andraz sporar
1         Arda Usluoğlu        arda usluoglu
2         Batuhan Yavuz        batuhan yavuz
3            Bera Çeken           bera ceken
4        Buluthan Bulut       buluthan bulut
5         Efecan Karaca        efecan karaca
6          Emin Sarıgül          emin sargul
7           Enes Keskin          enes keskin
8         Eren Altıntaş         eren altntas
9     Ertuğrul Taşkıran     ertugrul taskran
10          Fatih Aksoy          fatih aksoy
11          Fidan Aliti          fidan aliti
12  Florent Hadergjonaj  florent hadergjonaj
13         Furkan Bayır          furkan bayr
14        Gaius Makouta        gaius makouta
15       Juan Christian       juan christian
16        Jure Balkovec        jure balkovec
17        Loide Augusto        loide augusto
18          Mert Bayram          mert bayram
19      Nicolas Janvier      nicolas janvier
20            Nuno Lima            nuno lima
21              Richard              richard
22           Rony Lopes           rony lopes
23        Serdar Dursun        serdar dursun
24       Sergio Córdova       sergio cordova
25        Tonny Vilhena        tonny vilhena
26          Ui-jo Hwang          ui jo hwang
27        Umut Mert Toy        umut mert toy
28        Yusuf Karagöz        yusuf karagoz
29           Yusuf Kurt           yusuf kurt
30        Yusuf Özdemir        yusuf ozdemir

============================================================
  Antalyaspor  —  SF sin salario:

              player  minutesPlayed
0     Ali Demirbilek             10
1    Berkay Topdemir             34
2  Hasan Yakub İlçin            126

  CG plantilla completa:

                  player           player_norm
0       Abdullah Yiğiter      abdullah yigiter
1      Abdurrahim Dursun     abdurrahim dursun
2           Adolfo Gaich          adolfo gaich
3         Amar Gerxhaliu        amar gerxhaliu
4        Andros Townsend       andros townsend
5         Bahadır Öztürk         bahadr ozturk
6         Braian Samudio        braian samudio
7         Bünyamin Balcı         bunyamin balc
8           Burak İngenç          burak ingenc
9         Deni Milosevic        deni milosevic
10         Doğukan Özkan         dogukan ozkan
11        Efecan Gülerce        efecan gulerce
12             Emre Uzun             emre uzun
13       Emrecan Uzunhan       emrecan uzunhan
14           Erdal Rakip           erdal rakip
15     Erdoğan Yeşilyurt     erdogan yesilyurt
16           Güray Vural           guray vural
17          Harun Toprak          harun toprak
18      Jakub Kaluzinski      jakub kaluzinski
19          Kağan Arıcan           kagan arcan
20           Kenan Piric           kenan piric
21           Mert Yılmaz            mert ylmaz
22      Mevlüthan Ekelik      mevluthan ekelik
23        Moussa Djenepo        moussa djenepo
24  Oleksandr Petrusenko  oleksandr petrusenko
25          Ramzi Safuri          ramzi safuri
26           Sam Larsson           sam larsson
27  Sander van de Streek  sander van de streek
28          Soner Dikmen          soner dikmen
29     Taha Osman Özmert     taha osman ozmert
30             Thalisson             thalisson
31           Veysel Sarı            veysel sar

============================================================
  Beşiktaş JK  —  SF sin salario:

           player  minutesPlayed
0  Jackson Muleka             11
1     Omar Colley            180

  CG plantilla completa:

                     player              player_norm
0                Al Musrati               al musrati
1   Alex Oxlade-Chamberlain  alex oxlade chamberlain
2       Amir Hadziahmetovic      amir hadziahmetovic
3         Arda Berk Özüarap        arda berk ozuarap
4                Arda Kılıç                 arda klc
5            Arthur Masuaku           arthur masuaku
6      Baktiyar Zaynutdinov     baktiyar zaynutdinov
7                 Can Keleş                can keles
8                Cher Ndour               cher ndour
9             Ciro Immobile            ciro immobile
10             Élan Ricardo             elan ricardo
11               Emir Yaşar               emir yasar
12            Emirhan Topçu            emirhan topcu
13            Emrecan Terzi            emrecan terzi
14              Ernest Muci              ernest muci
15         Ersin Destanoğlu         ersin destanoglu
16                 Fahri Ay                 fahri ay
17           Felix Uduokhai           felix uduokhai
18         Gabriel Paulista         gabriel paulista
19         Gedson Fernandes         gedson fernandes
20          Göktuğ Baytekin          goktug baytekin
21               Jean Onana               jean onana
22               João Mário               joao mario
23           Jonas Svensson           jonas svensson
24              Keny Arroyo              keny arroyo
25               Mert Günok               mert gunok
26            Milot Rashica            milot rashica
27        Mustafa Hekimoğlu        mustafa hekimoglu
28              Necip Uysal              necip uysal
29               Onur Bulut               onur bulut
30               Rafa Silva               rafa silva
31               Salih Uçan               salih ucan
32           Semih Kılıçsoy             semih klcsoy
33             Tayyip Sanuc             tayyip sanuc

============================================================
  Bodrum FK  —  SF sin salario:

        player  minutesPlayed
0  Burak Çoban             60

  CG plantilla completa:

                player         player_norm
0          Ahmet Aslan         ahmet aslan
1          Ali Aytemur         ali aytemur
2         Arlind Ajeti        arlind ajeti
3          Bilal Güven         bilal guven
4        Celal Dumanlı        celal dumanl
5             Cenk Şen            cenk sen
6   Christophe Hérelle  christophe herelle
7          Diogo Sousa         diogo sousa
8           Ege Bilsel          ege bilsel
9          Enes Öğrüce         enes ogruce
10         Enis Bardhi         enis bardhi
11      Erkan Değişmez      erkan degismez
12               Fredy               fredy
13      Gabriel Obekpa      gabriel obekpa
14       George Pușcaș       george puscas
15  Gökdeniz Bayrakdar  gokdeniz bayrakdar
16        Gökhan Akkan        gokhan akkan
17          Haqi Osman          haqi osman
18      Jonathan Okita      jonathan okita
19          Kenan Özer          kenan ozer
20       Kerem Ersunar       kerem ersunar
21    Murat Sipahioğlu    murat sipahioglu
22      Musah Mohammed      musah mohammed
23    Mustafa Erdilman    mustafa erdilman
24       Oğulcan Başol       ogulcan basol
25     Ondrej Celustka     ondrej celustka
26        Pedro Brazão        pedro brazao
27     Rüzgar Adıyaman      ruzgar adyaman
28        Samet Yalçın         samet yalcn
29    Süleyman Özdamar    suleyman ozdamar
30      Taulant Seferi      taulant seferi
31    Taylan Antalyalı     taylan antalyal
32     Tunahan Akpınar      tunahan akpnar
33        Üzeyir Ergün        uzeyir ergun
34      Yusuf Sertkaya      yusuf sertkaya
35    Zdravko Dimitrov    zdravko dimitrov

============================================================
  Eyüpspor  —  SF sin salario:

        player  minutesPlayed
0  Svit Sešlar             25
1  Tugay Kaçar             37

  CG plantilla completa:

                       player                player_norm
0            Abdülkadir Aydın            abdulkadir aydn
1                Ahmed Kutucu               ahmed kutucu
2                  Alp Köseer                 alp koseer
3   Anastasios Chatzigiovanis  anastasios chatzigiovanis
4                  Berke Özer                 berke ozer
5                Birkan Tetik               birkan tetik
6                 Caner Erkin                caner erkin
7              Dorukhan Toköz             dorukhan tokoz
8                 Emre Akbaba                emre akbaba
9                    Emre Mor                   emre mor
10                Erdem Çalık                 erdem calk
11                Erdem Gökçe                erdem gokce
12            Fredrik Midtsjø             fredrik midtsj
13               Gianni Bruno               gianni bruno
14              Halil Akbunar              halil akbunar
15                Hamza Akman                hamza akman
16             Hüseyin Maldar             huseyin maldar
17           İsmail Can Fidan           ismail can fidan
18              Jonjo Shelvey              jonjo shelvey
19                 Léo Dubois                 leo dubois
20               Luccas Claro               luccas claro
21                 Mame Thiam                 mame thiam
22            Melih Kabasakal            melih kabasakal
23         Mustafa Eren Damar         mustafa eren damar
24               Prince Ampem               prince ampem
25                Recep Niyaz                recep niyaz
26               Robin Yalçın                robin yalcn
27                 Rúben Vezo                 ruben vezo
28                  Samu Saiz                  samu saiz
29                Sinan Gümüş                sinan gumus
30           Taras Stepanenko           taras stepanenko
31               Taşkın İlter                taskn ilter
32              Tayfur Bingöl              tayfur bingol
33                 Umut Bozok                 umut bozok
34                 Umut Meraş                 umut meras
35               Yalçın Kayan                yalcn kayan

============================================================
  Fenerbahçe  —  SF sin salario:

           player  minutesPlayed
0  Ferdi Kadıoğlu            104
1     Rade Krunić             11

  CG plantilla completa:

                 player          player_norm
0       Alexander Djiku      alexander djiku
1   Allan Saint-Maximin  allan saint maximin
2          Bartuğ Elmaz         bartug elmaz
3   Bright Osayi-Samuel  bright osayi samuel
4         Burak Kapacak        burak kapacak
5        Çağlar Söyüncü       caglar soyuncu
6          Cengiz Ünder         cengiz under
7            Cenk Tosun           cenk tosun
8          Diego Carlos         diego carlos
9     Dominik Livakovic    dominik livakovic
10          Dusan Tadic          dusan tadic
11           Edin Dzeko           edin dzeko
12       Ertuğrul Çetin       ertugrul cetin
13         Filip Kostić         filip kostic
14                 Fred                 fred
15  İrfan Can Eğribayat  irfan can egribayat
16    İrfan Can Kahveci    irfan can kahveci
17        İsmail Yüksek        ismail yuksek
18   Jayden Oosterwolde   jayden oosterwolde
19        Levent Mercan        levent mercan
20    Mert Hakan Yandaş    mert hakan yandas
21          Mert Müldür          mert muldur
22       Milan Skriniar       milan skriniar
23       Ognjen Mimovic       ognjen mimovic
24           Oğuz Aydın            oguz aydn
25        Rodrigo Becão        rodrigo becao
26            Ryan Kent            ryan kent
27        Samet Akaydin        samet akaydin
28  Sebastian Szymański  sebastian szymanski
29          Serdar Aziz          serdar aziz
30       Sofyan Amrabat       sofyan amrabat
31              Talisca              talisca
32    Youssef En-Nesyri    youssef en nesyri
33        Yusuf Akçiçek        yusuf akcicek

============================================================
  Galatasaray  —  SF sin salario:

             player  minutesPlayed
0         Berat Luş             12
1      Derrick Köhn             87
2  Kerem Aktürkoğlu            174

  CG plantilla completa:

                   player            player_norm
0     Abdülkerim Bardakcı     abdulkerim bardakc
1            Ahmed Kutucu           ahmed kutucu
2           Ali Yeşilyurt          ali yesilyurt
3           Álvaro Morata          alvaro morata
4              Arda Ünyay             arda unyay
5             Atakan Ordu            atakan ordu
6            Baris Yilmaz           baris yilmaz
7             Batuhan Şen            batuhan sen
8            Berkan Kutlu           berkan kutlu
9           Carlos Cuesta          carlos cuesta
10       Davinson Sánchez       davinson sanchez
11          Dries Mertens          dries mertens
12              Efe Akman              efe akman
13           Elias Jelert           elias jelert
14      Evren Eren Elmali      evren eren elmali
15             Eyüp Aydın              eyup aydn
16       Fernando Muslera       fernando muslera
17           Gabriel Sara           gabriel sara
18        Gökdeniz Gürpüz        gokdeniz gurpuz
19           Günay Güvenç           gunay guvenc
20           Hakim Ziyech           hakim ziyech
21          Ismail Jakobs          ismail jakobs
22          Jankat Yılmaz           jankat ylmaz
23             Kaan Ayhan             kaan ayhan
24         Kerem Demirbay         kerem demirbay
25         Lucas Torreira         lucas torreira
26           Mario Lemina           mario lemina
27           Mauro Icardi           mauro icardi
28        Metehan Baltacı         metehan baltac
29        Michy Batshuayi        michy batshuayi
30  Przemyslaw Frankowski  przemyslaw frankowski
31          Roland Sallai          roland sallai
32         Victor Nelsson         victor nelsson
33         Victor Osimhen         victor osimhen
34          Wilfried Zaha          wilfried zaha
35            Yunus Akgün            yunus akgun
36            Yusuf Demir            yusuf demir

============================================================
  Gaziantep FK  —  SF sin salario:

            player  minutesPlayed
0  Ali Osman Kalın             33
1        Cagan Tas              8
2     Nevzat Gezer              8

  CG plantilla completa:

                 player          player_norm
0       Alexandru Maxim      alexandru maxim
1      Ali Mevran Ablak     ali mevran ablak
2            Anel Husic           anel husic
3         Arda Kızıldağ          arda kzldag
4          Badou Ndiaye         badou ndiaye
5       Bahadır Gölgeli       bahadr golgeli
6           Bruno Viana          bruno viana
7     Burak Enes Yıkıcı       burak enes ykc
8   Christopher Lungoyi  christopher lungoyi
9        Cyril Mandouki       cyril mandouki
10        David Okereke        david okereke
11        Deian Sorescu        deian sorescu
12     Emmanuel Boateng     emmanuel boateng
13        Emre Taşdemir        emre tasdemir
14        Enric Saborit        enric saborit
15           Eren Cakir           eren cakir
16         Eren Erdoğan         eren erdogan
17       Ertuğrul Ersoy       ertugrul ersoy
18        Furkan Soyalp        furkan soyalp
19      Godfrey Stephen      godfrey stephen
20          Halil Bağcı           halil bagc
21     Halil Dervişoğlu     halil dervisoglu
22        İlker Karakaş        ilker karakas
23          İzzet Erdal          izzet erdal
24     Kacper Kozlowski     kacper kozlowski
25          Kenan Kodro          kenan kodro
26        Mehmet Kuzucu        mehmet kuzucu
27          Mirza Cihan          mirza cihan
28   Muhammed Gümüşkaya   muhammed gumuskaya
29  Mustafa Burak Bozan  mustafa burak bozan
30   Mustafa Eskihellaç   mustafa eskihellac
31         Ogün Özçiçek         ogun ozcicek
32        Ömürcan Artan        omurcan artan
33       Quentin Daubin       quentin daubin
34       Salem M'Bakata       salem m bakata
35          Semih Güler          semih guler
36     Sokratis Dioudis     sokratis dioudis

============================================================
  Göztepe  —  SF sin salario:

                 player  minutesPlayed
0  Juan Santos da Silva           1659
1        Tibet Durakcay              1

  CG plantilla completa:

                 player         player_norm
0           Ahmed Ildız          ahmed ildz
1        Anthony Dennis      anthony dennis
2          Arda Özçimen        arda ozcimen
3    David Datro Fofana  david datro fofana
4         David Tijanic       david tijanic
5          Djalma Silva        djalma silva
6         Doğan Erdoğan       dogan erdogan
7          Ege Yıldırım           ege yldrm
8              Emersonn            emersonn
9        Emir Enes Araz      emir enes araz
10       Emircan Seçgin      emircan secgin
11         Furkan Bayır         furkan bayr
12         Furkan Malak        furkan malak
13              Héliton             heliton
14          Isaac Solet         isaac solet
15       İsmail Köybaşı       ismail koybas
16                 Juan                juan
17         Koray Günter        koray gunter
18  Kubilay Kanatsızkuş  kubilay kanatszkus
19        Kuryu Matsuki       kuryu matsuki
20        Lasse Nielsen       lasse nielsen
21        Malcom Bokele       malcom bokele
22          Mateusz Lis         mateusz lis
23        Nazım Sangaré        nazm sangare
24      Novatus Miroshi     novatus miroshi
25          Ogün Bayrak         ogun bayrak
26               Rômulo              romulo
27      Taha Altıkardeş      taha altkardes
28         Tuğbey Akgün        tugbey akgun
29          Victor Hugo         victor hugo
30         Yalçın Kayan         yalcn kayan
31         Yiğit Yıldız          yigit yldz

============================================================
  Hatayspor  —  SF sin salario:

          player  minutesPlayed
0   Armin Hodžić            101
1    Deniz Aksoy             37
2  Ersin Aydemir              9
3    Ismail Zobu              1
4  Yigit Ali Buz            212

  CG plantilla completa:

                 player          player_norm
0     Abdulkadir Parmak    abdulkadir parmak
1            Ali Yıldız             ali yldz
2           Baran Sarka          baran sarka
3      Berkay İrşad Göç     berkay irsad goc
4        Bilal Boutobba       bilal boutobba
5          Burak Yılmaz          burak ylmaz
6     Carlos Strandberg    carlos strandberg
7         Cemali Sertel        cemali sertel
8          Cengiz Demir         cengiz demir
9     Chandrel Massanga    chandrel massanga
10       Demir Sarıcalı         demir sarcal
11           Emir Dadük           emir daduk
12       Erce Kardeşler       erce kardesler
13      Francisco Calvo      francisco calvo
14      Funsho Bamgboye      funsho bamgboye
15        Görkem Sağlam        gorkem saglam
16  Guy-Marcelin Kilama  guy marcelin kilama
17    Joelson Fernandes    joelson fernandes
18   Jonathan Okoronkwo   jonathan okoronkwo
19  Kamil Ahmet Çörekçi  kamil ahmet corekci
20          Kerim Alıcı            kerim alc
21         Lamine Diack         lamine diack
22        Oğuzhan Matur        oguzhan matur
23      Rigoberto Rivas      rigoberto rivas
24            Rui Pedro            rui pedro
25       Selimcan Temel       selimcan temel
26    Vincent Aboubakar    vincent aboubakar
27          Visar Bekaj          visar bekaj

============================================================
  Kasımpaşa  —  SF sin salario:

              player  minutesPlayed
0  Berk Can Yildizli             17
1         Yusuf Inci             67

  CG plantilla completa:

                 player          player_norm
0           Adnan Aktaş          adnan aktas
1           Ali Demirel          ali demirel
2        Ali Emre Yanar       ali emre yanar
3    Andreas Gianniotis   andreas gianniotis
4         Antonín Barák        antonin barak
5          Atakan Müjde         atakan mujde
6            Aytaç Kara           aytac kara
7          Berat Kalkan         berat kalkan
8                  Cafú                 cafu
9             Can Keleş            can keles
10        Cláudio Winck        claudio winck
11       Driess Saddiki       driess saddiki
12         Ege Albayrak         ege albayrak
13        Emirhan Yiğit        emirhan yigit
14      Erdem Çetinkaya      erdem cetinkaya
15           Gökhan Gül           gokhan gul
16   Haris Hajradinovic   haris hajradinovic
17        Jhon Espinoza        jhon espinoza
18        Josip Brekalo        josip brekalo
19     Kamil Piatkowski     kamil piatkowski
20       Kenneth Omeruo       kenneth omeruo
21      Kévin Rodrigues      kevin rodrigues
22         Loret Sadiku         loret sadiku
23         Mamadou Fall         mamadou fall
24  Mortadha Ben Ouanes  mortadha ben ouanes
25       Nicholas Opoku       nicholas opoku
26        Nuno Da Costa        nuno da costa
27      Sadık Çiftpınar        sadk ciftpnar
28         Şant Kazancı          sant kazanc
29         Sarp Yavrucu         sarp yavrucu
30          Sinan Alkaş          sinan alkas
31          Sinan Bolat          sinan bolat
32         Taylan Aydın          taylan aydn
33         Yaman Suakar         yaman suakar
34          Yasin Özcan          yasin ozcan
35        Yunus Atakaya        yunus atakaya

============================================================
  Kayserispor  —  SF sin salario:

         player  minutesPlayed
0  Burak Arslan             26
1   Kayra Cihan             98

  CG plantilla completa:

                   player            player_norm
0              Ali Karimi             ali karimi
1        Anthony Uzodimma       anthony uzodimma
2            Arif Kocaman           arif kocaman
3        Aylton Boa Morte       aylton boa morte
4             Baran Gezek            baran gezek
5           Batuhan Özgan          batuhan ozgan
6           Bilal Bayazıt           bilal bayazt
7            Bilal Ceylan           bilal ceylan
8             Carlos Mané            carlos mane
9   Dimitrios Kolovetsios  dimitrios kolovetsios
10          Duckens Nazon          duckens nazon
11             Eray Özbek             eray ozbek
12         Gökhan Sazdağı          gokhan sazdag
13     Hasan Ali Kaldırım       hasan ali kaldrm
14         Joseph Attamah         joseph attamah
15        Julian Jeanvier        julian jeanvier
16          Kartal Yılmaz           kartal ylmaz
17          Lionel Carole          lionel carole
18         Majid Hosseini         majid hosseini
19         Mehdi Bourabia         mehdi bourabia
20         Miguel Cardoso         miguel cardoso
21       Nurettin Korkmaz       nurettin korkmaz
22           Onurcan Piri           onurcan piri
23        Ramazan Civelek        ramazan civelek
24           Şamil Öztürk           samil ozturk
25       Stéphane Bahoken       stephane bahoken
26       Talha Sarıarslan        talha sararslan
27              Yaw Ackah              yaw ackah

============================================================
  Konyaspor  —  SF sin salario:

                    player  minutesPlayed
0          Emrehan Gedikli             21
1  Guilherme Haubert Sityá           3000
2              Mehmet Kaya              8
3         Sokol Cikalleshi             12

  CG plantilla completa:

                  player           player_norm
0     Abdurrahman Üresin    abdurrahman uresin
1        Adem Eren Kabak       adem eren kabak
2          Adil Demirbağ         adil demirbag
3              Ahmet Daş             ahmet das
4          Alassane Ndao         alassane ndao
5            Blaz Kramer           blaz kramer
6        Danijel Aleksic       danijel aleksic
7            Deniz Ertaş           deniz ertas
8           Egemen Aydın           egemen aydn
9       Emmanuel Boateng      emmanuel boateng
10      Filip Damjanovic      filip damjanovic
11             Guilherme             guilherme
12         Hamidou Keyta         hamidou keyta
13          Jakub Slowik          jakub slowik
14         Josip Calusic         josip calusic
15           Kaan Akyazı            kaan akyaz
16            Louka Prip            louka prip
17        Marko Jevtovic        marko jevtovic
18          Melih Bostan          melih bostan
19     Melih İbrahimoğlu     melih ibrahimoglu
20         Morten Bjørlo          morten bjrlo
21              Niko Rak              niko rak
22  Nikola Boranijasevic  nikola boranijasevic
23         Oğulcan Ülgün         ogulcan ulgun
24              Pedrinho              pedrinho
25         Rıdvan Dönmez          rdvan donmez
26      Riechedly Bazoer      riechedly bazoer
27        Semih Kocatürk        semih kocaturk
28         Tunahan Taşçı          tunahan tasc
29            Ufuk Akyol            ufuk akyol
30       Uğurcan Yazğılı         ugurcan yazgl
31            Umut Nayir            umut nayir
32          Yasir Subaşı           yasir subas
33           Yavuz Aygün           yavuz aygun
34         Yusuf Erdoğan         yusuf erdogan

============================================================
  Samsunspor  —  SF sin salario:

                 player  minutesPlayed
0            Ali Tarkan              1
1  Marius Mouandilmadji           2502

  CG plantilla completa:

                   player            player_norm
0         Alper Efe Pazar        alper efe pazar
1             Arbnor Muja            arbnor muja
2          Bedirhan Çetin         bedirhan cetin
3            Berhan Deniz           berhan deniz
4             Carlo Holse            carlo holse
5            Celil Yüksel           celil yuksel
6         Efe Berat Törüz        efe berat toruz
7             Elano Yegen            elano yegen
8             Emre Kılınç              emre klnc
9              Enes Albak             enes albak
10             Ercan Kara             ercan kara
11           Flavien Tait           flavien tait
12           Gaëtan Laura           gaetan laura
13            Halil Yeral            halil yeral
14     Kingsley Schindler     kingsley schindler
15          Landry Dimata          landry dimata
16          Lubomir Satka          lubomir satka
17              Marc Bola              marc bola
18                 Marius                 marius
19            Moussa Guel            moussa guel
20       Muammer Yıldırım          muammer yldrm
21     Muhammet Özbaskıcı       muhammet ozbaskc
22            Mustafa Tan            mustafa tan
23                   Nanu                   nanu
24             Okan Kocuk             okan kocuk
25         Olivier Ntcham         olivier ntcham
26     Rick van Drongelen     rick van drongelen
27          Soner Aydoğdu          soner aydogdu
28            Soner Gönül            soner gonul
29             Taha Tosun             taha tosun
30  Youssef Aït Bennasser  youssef ait bennasser
31        Yunus Emre Çift        yunus emre cift
32             Zeki Yavru             zeki yavru

============================================================
  Sivasspor  —  SF sin salario:

       player  minutesPlayed
0  Yilmaz Cin              1

  CG plantilla completa:

                  player           player_norm
0   Achilleas Poungouras  achilleas poungouras
1        Alaaddin Okumuş       alaaddin okumus
2         Alex Pritchard        alex pritchard
3        Ali Şaşal Vural       ali sasal vural
4     Azizbek Turgunboev    azizbek turgunboev
5       Bekir Turaç Böke      bekir turac boke
6     Bengali-Fodé Koita    bengali fode koita
7     Charilaos Charisis    charilaos charisis
8        Djordje Nikolic       djordje nikolic
9        Efkan Bekiroğlu       efkan bekiroglu
10      Emirhan Başyiğit      emirhan basyigit
11          Emrah Başsan          emrah bassan
12            Emre Gökay            emre gokay
13           Erdem Güleç           erdem gulec
14          Eymen Yurdcu          eymen yurdcu
15       Garry Rodrigues       garry rodrigues
16        Hüseyin Arslan        huseyin arslan
17         Jan Bieganski         jan bieganski
18           Kaan Sarman           kaan sarman
19           Keita Baldé           keita balde
20       Mehmet Albayrak       mehmet albayrak
21          Murat Paluli          murat paluli
22   Noah Sonko Sundberg   noah sonko sundberg
23         Oğuzhan Aksoy         oguzhan aksoy
24         Özkan Yiğiter         ozkan yigiter
25         Queensy Menig         queensy menig
26             Rey Manaj             rey manaj
27          Samba Camara          samba camara
28    Samuel Moutoussamy    samuel moutoussamy
29            Sinan Kaya            sinan kaya
30           Talha Şeker           talha seker
31         Tolga Ciğerci         tolga cigerci
32           Uğur Çiftçi           ugur ciftci
33        Uros Radakovic        uros radakovic
34          Veljko Simic          veljko simic
35            Ziya Erdal            ziya erdal

============================================================
  Trabzonspor  —  SF sin salario:

              player  minutesPlayed
0       Boran Başkan             25
1  Mahmoud Trézéguet             90
2     Taha Emre Ince             11

  CG plantilla completa:

                  player           player_norm
0         Ahmet Yıldırım           ahmet yldrm
1       Ali Şahin Yılmaz       ali sahin ylmaz
2       Anthony Nwakaeme      anthony nwakaeme
3            Arif Boşluk           arif bosluk
4        Arseniy Batagov       arseniy batagov
5          Batista Mendy         batista mendy
6          Borna Barisic         borna barisic
7            Cihan Çanak           cihan canak
8           Danylo Sikan          danylo sikan
9           Denis Drăguș          denis dragus
10            Edin Visca            edin visca
11           Enis Bardhi           enis bardhi
12           Enis Destan           enis destan
13     Evren Eren Elmali     evren eren elmali
14       Hüseyin Türkmen       huseyin turkmen
15        John Lundstram        john lundstram
16          Mislav Orsic          mislav orsic
17         Muhammed Cham         muhammed cham
18    Muhammet Taha Tepe    muhammet taha tepe
19    Mustafa Eskihellaç    mustafa eskihellac
20          Okay Yokuşlu          okay yokuslu
21      Oleksandr Zubkov      oleksandr zubkov
22      Onuralp Çevikkan      onuralp cevikkan
23            Ozan Tufan            ozan tufan
24        Pedro Malheiro        pedro malheiro
25       Poyraz Yıldırım          poyraz yldrm
26      Salih Malkoçoğlu      salih malkocoglu
27         Serdar Saatçı          serdar saatc
28           Serkan Asan           serkan asan
29           Simon Banza           simon banza
30          Stefan Savic          stefan savic
31       Stefano Denswil       stefano denswil
32  Tim Jabol-Folcarelli  tim jabol folcarelli
33         Uğurcan Çakır          ugurcan cakr
34            Umut Bozok            umut bozok
35            Umut Güneş            umut gunes

In [28]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('juan santos da silva', 'goztepe')       : ('juan', 'goztepe'),
    ('guilherme haubert sitya', 'konyaspor')  : ('guilherme', 'konyaspor'),
    ('marius mouandilmadji', 'samsunspor')    : ('marius', 'samsunspor'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 3

In [29]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: juan santos da silva (goztepe) → juan (goztepe)
✅ Match manual aplicado: guilherme haubert sitya (konyaspor) → guilherme (konyaspor)
✅ Match manual aplicado: marius mouandilmadji (samsunspor) → marius (samsunspor)

Tras matches manuales: 533/580 (91.9%)

In [30]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [31]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_turkey_2425.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_turkey_2425.csv
   Jugadores totales:  580
   Con salario:        533
   Sin salario (NaN):  47
   Columnas:           121