# 03 · Join Sofascore + Capology — Turkey Süper Lig 21/22

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2021/22 de Süper Lig turca**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_turkey_2122.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_turkey_2122.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  635 jugadores | 116 columnas
Capology:   692 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   altay
   basaksehir fk
   besiktas jk
   fatih karagumruk
   gaziantep fk
   kasmpasa

En Capology pero no en Sofascore:
   altay sk
   basaksehir
   besiktas
   gaziantep bb
   karagumrukspor
   kasimpasa

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'altay sk':'altay',
            'basaksehir':'basaksehir fk',
            'besiktas':'besiktas jk',
            'gaziantep bb':'gaziantep fk',
            'karagumrukspor':'fatih karagumruk',
            'kasimpasa':'kasmpasa'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 475/635 (74.8%)
Sin emparejar: 160

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          55
Revisión media    (0.75 ≤ score < 0.90):   16
Revisión estricta (0.50 ≤ score < 0.75):   59
Revisión muy est. (score < 0.50):           30

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf              team               cg_match  score
79   Dimitris Kolovetsios       Kayserispor  dimitrios kolovetsios  0.976
6     Abdülkerim Bardakcı         Konyaspor    abdulkerim bardakci  0.973
78    Kubilay Kanatsızkuş   Çaykur Rizespor    kubilay kanatsizkus  0.973
116   Mert Miraç Altıntaş  Yeni Malatyaspor    mert mirac altintas  0.973
58      Ertuğrul Taşkıran         Kasımpaşa      ertugrul taskiran  0.970
62      Nicolai Jørgensen         Kasımpaşa      nicolai jorgensen  0.970
83       Şener Özbayraklı     Başakşehir FK       sener ozbayrakli  0.968
13        Dimitris Goutas         Sivasspor       dimitrios goutas  0.968
74       Taylan Antalyalı       Galatasaray       taylan antalyali  0.968
51       Çağtay Kurukalıp        Fenerbahçe       cagtay kurukalip  0.968
91       Kazımcan Karataş             Altay       kazimcan karatas  0.968
132      Efe Can Saçıkara           Göztepe       efe can sacikara  0.968
130       Ege Özkayımoğlu           Göztepe        ege ozkayimoglu  0.966
52        İsmail Çokçalış   Adana Demirspor        ismail cokcalis  0.966
11         Ferdi Kadıoğlu        Fenerbahçe         ferdi kadioglu  0.963
50         Paweł Olkowski      Gaziantep FK         pawel olkowski  0.963
75         Bahadır Öztürk       Antalyaspor         bahadir ozturk  0.963
84         Gökhan Sazdağı       Kayserispor         gokhan sazdagi  0.963
63         Bünyamin Balcı       Antalyaspor         bunyamin balci  0.963
100        İsmail Köybaşı       Trabzonspor         ismail koybasi  0.963
117        Torgeir Børven      Gaziantep FK         torgeir borven  0.963
129         Koray Altınay         Sivasspor          koray altinay  0.960
7           Samet Akaydın   Adana Demirspor          samet akaydin  0.960
5           Uğurcan Çakır       Trabzonspor          ugurcan cakir  0.960
59          Didier N'Dong  Yeni Malatyaspor           didier ndong  0.960
33          Nazım Sangaré        Fenerbahçe          nazim sangare  0.960
42          Buğra Çağıran  Yeni Malatyaspor          bugra cagiran  0.960
88          Serdar Saatçı       Beşiktaş JK          serdar saatci  0.960
35           Güven Yalçın       Beşiktaş JK           guven yalcin  0.957
32           Furkan Bayır        Alanyaspor           furkan bayir  0.957
138          Mustafa Kapı   Adana Demirspor           mustafa kapi  0.957
95           Musa Çağıran         Konyaspor           musa cagiran  0.957
86           Tarık Çamdal   Adana Demirspor           tarik camdal  0.957
90           Yalçın Kayan           Göztepe           yalcin kayan  0.957
76           Yasir Subaşı       Kayserispor           yasir subasi  0.957
3             Ahmet Çalık         Konyaspor            ahmet calik  0.952
118           Sakıb Aytaç         Kasımpaşa            sakib aytac  0.952
20            Atınç Nukan           Göztepe            atinc nukan  0.952
106           Sefa Yılmaz         Sivasspor            sefa yilmaz  0.952
26            Veysel Sarı       Antalyaspor            veysel sari  0.952
17            Tarık Çetin   Çaykur Rizespor            tarik cetin  0.952
120           Ahmed Ildız        Alanyaspor            ahmed ildiz  0.952
30             Yusuf Sarı   Çaykur Rizespor             yusuf sari  0.947
15             Oğuz Aydın        Alanyaspor             oguz aydin  0.947
24     Hasan Ali Kaldırım     Başakşehir FK     hasan ali kaldirim  0.941
131             Efe Tatlı  Fatih Karagümrük              efe tatli  0.941
18      Ekrem Kılıçarslan      Gaziantep FK      ekrem kilicarslan  0.938
40       Erencan Yardımcı        Alanyaspor       erencan yardimci  0.933
25        Sadık Çiftpınar  Yeni Malatyaspor        sadik ciftpinar  0.929
80        Uğurcan Yazğılı         Konyaspor        ugurcan yazgili  0.929
10         Altay Bayındır        Fenerbahçe         altay bayindir  0.923
110         Emre Satılmış         Sivasspor          emre satilmis  0.917
36          Rıdvan Yılmaz       Beşiktaş JK          ridvan yilmaz  0.917
53            Emre Kılınç       Galatasaray            emre kilinc  0.900
98            Kerim Alıcı           Göztepe            kerim alici  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                    player_sf              team          cg_match  score
37           Muammer Yıldırım         Sivasspor  muammer yildirim  0.897
54            Bertuğ Yıldırım         Hatayspor   bertug yildirim  0.889
99             Barış Yardımcı         Konyaspor    baris yardimci  0.880
19           Serkan Kırıntılı        Alanyaspor  serkan kirintili  0.857
44                   Serginho       Giresunspor            sergio  0.857
133          Işık Kaan Arslan       Galatasaray       kaan arslan  0.846
126      Osman Ertuğrul Çetin        Fenerbahçe    ertugrul cetin  0.824
77       Houssameddine Ghacha       Antalyaspor    houssam ghacha  0.824
144      Ahmet Eyüp Türkaslan  Yeni Malatyaspor    eyup turkaslan  0.824
22   Magomed Shapi Suleymanov       Giresunspor  shapi suleymanov  0.800
31         Tayyip Talha Sanuç   Adana Demirspor      tayyip sanuc  0.800
45       Berat Ayberk Özdemir       Trabzonspor     berat ozdemir  0.788
60       Joher Khadim Rassoul   Adana Demirspor     joher rassoul  0.788
154  Muhammed Egemen Pehlivan  Fatih Karagümrük   egemen pehlivan  0.769
12           Mame Biram Diouf         Hatayspor        mame diouf  0.769
101   Babajide David Akintola   Adana Demirspor    david akintola  0.757

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 16 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                    player_sf              team             cg_match  score
56                Eren Elmalı         Kasımpaşa    evren eren elmali  0.741
64      Daouda Karamoko Bamba             Altay         daouda bamba  0.727
23                  Serge Aka             Altay     serge arnaud aka  0.720
55           Jefferson Junior      Gaziantep FK            jefferson  0.720
39                 Campanharo       Kayserispor   gustavo campanharo  0.714
102        Barış Alper Yılmaz       Galatasaray         baris yilmaz  0.714
92             Mickael Tirpan         Kasımpaşa       michal travnik  0.714
85   Joseph William Champness       Giresunspor        joe champness  0.703
152               Kaan Onaran         Sivasspor         hakan arslan  0.696
158               Kaan Yilmaz       Giresunspor         fatih yilmaz  0.696
4           Mahmoud Trézéguet     Başakşehir FK            trezeguet  0.692
140     Mehmet Feyzi Yıldırım         Kasımpaşa       feyzi yildirim  0.688
82        Philip Awuku Gameli  Yeni Malatyaspor  philip gameli awuku  0.684
109         Bahattin Demircan  Fatih Karagümrük       berke demircan  0.645
153               Yunus Toplu           Göztepe          yusuf talum  0.636
73                 Aytaç Kara           Göztepe         yalcin kayan  0.636
135              Furkan Kütük       Giresunspor           okan kocuk  0.636
27            Mahmoud Kahraba         Hatayspor              kahraba  0.636
81        Çağan Kayra Erciyas        Alanyaspor        efecan karaca  0.625
157            Atalay Çayırlı           Göztepe       atakan cankaya  0.615
61                Erdem Ozcan             Altay         eren erdogan  0.609
105          Amilton da Silva         Konyaspor              amilton  0.609
151                Emre Nizam       Giresunspor        emre tasdemir  0.609
94       Harun Elyesa Akaydın         Kasımpaşa          harun tekin  0.600
159            Muhammed Ergin         Sivasspor     muammer yildirim  0.600
113              Firat Arslan           Göztepe      dino arslanagic  0.593
97               Carlos Ponck   Çaykur Rizespor                ponck  0.588
103               Berat Yaman  Yeni Malatyaspor        bugra cagiran  0.583
121                Umut Taniş  Yeni Malatyaspor          murat aksit  0.571
48           Efe Arda Koyuncu     Başakşehir FK         enes karakus  0.571
1     Guilherme Haubert Sityá         Konyaspor            guilherme  0.562
124           Kerem Altunışık  Yeni Malatyaspor  mert mirac altintas  0.562
46              Talha Karatas       Kayserispor         ilhan parlak  0.560
134             Mahsun Çapkan   Çaykur Rizespor         gokhan akkan  0.560
21            Munir El Kajoui         Hatayspor       ayoub el kaabi  0.552
156            Halit Çokyaşar         Sivasspor      ali sasal vural  0.552
38                 Awer Mabil         Kasımpaşa         rayane aabid  0.545
112              Tugay Gündem             Altay           tolga unlu  0.545
123                Erdon Daci         Konyaspor         marin anicic  0.545
137              Kasim Kosker       Giresunspor           okan kocuk  0.545
111                Erşan Yaşa  Yeni Malatyaspor         rayane aabid  0.545
0              Jackson Muleka         Kasımpaşa         yasin dulger  0.538
96              Moussa Konaté         Sivasspor    mustapha yatabare  0.533
125      Metin Caner Akbayrak       Giresunspor       erol can akdag  0.529
68                  Eray Akar         Hatayspor           emre colak  0.526
136         Emircan Bayrakdar  Yeni Malatyaspor           semih kaya  0.519
128              Efe Sarıkaya             Altay     serge arnaud aka  0.519
41             Damjan Đoković   Adana Demirspor       arijanet muric  0.519
147             Doğan Alemdar       Kayserispor       gokhan sazdagi  0.519
47           Mustafa Erdilman       Antalyaspor          mert yilmaz  0.519
28             Radamel Falcao       Galatasaray    omar elabdellaoui  0.516
141             Burak Efe Yaz  Yeni Malatyaspor          berk yildiz  0.500
66               Zoran Kvržić       Kayserispor     mario gavranovic  0.500
14                      Souza       Beşiktaş JK              douglas  0.500
16               Erick Pulgar       Galatasaray         berkan kutlu  0.500
115             Walter Bwalya  Yeni Malatyaspor              wallace  0.500
93               Metehan Ünal  Yeni Malatyaspor             taha gur  0.500
65             Jocelyn Janneh       Kayserispor           cenk gonen  0.500
104                Berat Mert  Yeni Malatyaspor           kenan ozer  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['eren elmal',
                    'daouda karamoko bamba',
                    'serge aka',
                    'jefferson junior',
                    'campanharo',
                    'bars alper ylmaz',
                    'joseph william champness',
                    'mahmoud trezeguet',
                    'mehmet feyzi yldrm',
                    'philip awuku gameli',
                    'bahattin demircan',
                    'mahmoud kahraba',
                    'amilton da silva',
                    'carlos ponck',
                    'guilherme haubert sitya'
                    
                    

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 15

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

               player_sf              team             cg_match  score
155        Soner Özdemir   Çaykur Rizespor     gedson fernandes  0.483
149   İzzet Furkan Malak           Göztepe          berkan emir  0.483
143         Emir Dilaver   Çaykur Rizespor        cemali sertel  0.480
67           Engin Aksoy         Hatayspor           eren fansa  0.476
87            Semih Kaya       Galatasaray          omer bayram  0.476
70         Cengizhan Sen           Göztepe        beykan simsek  0.462
49     Hijran Ali Boyaci   Adana Demirspor   benjamin stambouli  0.457
107          Tunay Torun         Kasımpaşa          harun tekin  0.455
69           Ethem Balcı       Kayserispor         emrah bassan  0.455
114            Baris Gun       Giresunspor        doganay aygun  0.455
146            Şahin Dik       Giresunspor        alperen aydin  0.455
43   Mbwana Ally Samatta        Fenerbahçe         murat saglam  0.452
9         Yassine Benzia         Hatayspor    dylan saint louis  0.452
29              Onur Efe             Altay           ozan ozenc  0.444
57       Hayrullah Erkip       Kayserispor         ilhan parlak  0.444
145     Anıl Yiğit Çınar       Giresunspor        tolgahan acar  0.444
150    Mehmet Eray Özbek       Kayserispor           emre demir  0.444
89    Muhammed Gümüşkaya       Giresunspor   souleymane doukara  0.444
71           Emirhan Tak         Sivasspor     dimitrios goutas  0.444
108      Mehmet Albayrak         Sivasspor         samba camara  0.444
34           Nabil Dirar         Kasımpaşa         rayane aabid  0.435
72    Papiss Demba Cissé   Çaykur Rizespor      yannick bolasie  0.424
148           Yiğit Ulaş  Yeni Malatyaspor       eyup turkaslan  0.417
139         Barış Başdaş  Yeni Malatyaspor        bugra cagiran  0.417
127     Gustavo Assunção       Galatasaray  christian luyindama  0.400
8               Pa Dibba   Adana Demirspor         alper uludag  0.400
119          Sinan Gümüş       Antalyaspor      sherel floranus  0.385
122            Loïc Rémy   Adana Demirspor         lucas castro  0.381
142          Enes Savucu  Yeni Malatyaspor           adem buyuk  0.381
2            Efe Tecimer   Çaykur Rizespor     sebastian holmen  0.370

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 0

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 561/635 (88.3%)
Sin salario:     74

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 74

,player,team,minutesPlayed,appearances,goals,assists
0,Damjan Đoković,Adana Demirspor,1750,30,4,0
1,Loïc Rémy,Adana Demirspor,295,10,0,0
2,Hijran Ali Boyaci,Adana Demirspor,18,1,0,0
3,Pa Dibba,Adana Demirspor,14,1,0,0
4,Çağan Kayra Erciyas,Alanyaspor,54,3,0,0
5,Efe Sarıkaya,Altay,91,2,0,0
6,Erdem Ozcan,Altay,79,3,0,0
7,Onur Efe,Altay,9,1,0,0
8,Tugay Gündem,Altay,8,1,0,0
9,Sinan Gümüş,Antalyaspor,118,6,0,0
10,Mustafa Erdilman,Antalyaspor,12,1,0,0
11,Efe Arda Koyuncu,Başakşehir FK,90,1,0,0
12,Souza,Beşiktaş JK,2607,32,5,0
13,Mbwana Ally Samatta,Fenerbahçe,162,3,0,0
14,Semih Kaya,Galatasaray,1954,24,0,0
15,Erick Pulgar,Galatasaray,602,11,0,0
16,Gustavo Assunção,Galatasaray,135,2,0,0
17,Radamel Falcao,Galatasaray,10,1,0,0
18,Muhammed Gümüşkaya,Giresunspor,1196,25,2,1
19,Furkan Kütük,Giresunspor,90,1,0,0
20,Anıl Yiğit Çınar,Giresunspor,90,1,0,0
21,Baris Gun,Giresunspor,59,1,0,0
22,Metin Caner Akbayrak,Giresunspor,54,1,0,0
23,Şahin Dik,Giresunspor,36,1,0,0
24,Kasim Kosker,Giresunspor,31,1,0,0
25,Emre Nizam,Giresunspor,1,1,0,0
26,Kaan Yilmaz,Giresunspor,1,1,0,0
27,Aytaç Kara,Göztepe,599,13,0,1
28,İzzet Furkan Malak,Göztepe,21,3,0,0
29,Cengizhan Sen,Göztepe,8,1,0,0
30,Firat Arslan,Göztepe,8,1,0,0
31,Yunus Toplu,Göztepe,1,1,0,0
32,Atalay Çayırlı,Göztepe,1,1,0,0
33,Munir El Kajoui,Hatayspor,3060,34,0,0
34,Yassine Benzia,Hatayspor,762,12,2,1
35,Eray Akar,Hatayspor,22,1,0,0
36,Engin Aksoy,Hatayspor,8,1,0,0
37,Jackson Muleka,Kasımpaşa,1062,14,12,4
38,Tunay Torun,Kasımpaşa,456,21,0,2
39,Awer Mabil,Kasımpaşa,395,11,2,1
40,Nabil Dirar,Kasımpaşa,265,6,0,0
41,Harun Elyesa Akaydın,Kasımpaşa,45,1,0,0
42,Mickael Tirpan,Kasımpaşa,9,1,0,0
43,Hayrullah Erkip,Kayserispor,111,3,1,0
44,Zoran Kvržić,Kayserispor,90,1,0,0
45,Doğan Alemdar,Kayserispor,90,1,0,0
46,Talha Karatas,Kayserispor,45,1,0,1
47,Ethem Balcı,Kayserispor,21,1,0,0
48,Jocelyn Janneh,Kayserispor,13,1,0,0
49,Mehmet Eray Özbek,Kayserispor,3,1,0,0
50,Erdon Daci,Konyaspor,12,1,0,0
51,Moussa Konaté,Sivasspor,245,12,0,0
52,Mehmet Albayrak,Sivasspor,61,1,0,0
53,Emirhan Tak,Sivasspor,29,1,0,0
54,Muhammed Ergin,Sivasspor,2,2,0,0
55,Kaan Onaran,Sivasspor,1,1,0,0
56,Halit Çokyaşar,Sivasspor,1,1,0,0
57,Barış Başdaş,Yeni Malatyaspor,517,9,0,0
58,Umut Taniş,Yeni Malatyaspor,201,6,0,0
59,Yiğit Ulaş,Yeni Malatyaspor,136,3,0,0
60,Walter Bwalya,Yeni Malatyaspor,132,8,0,0
61,Berat Yaman,Yeni Malatyaspor,112,3,0,0
62,Burak Efe Yaz,Yeni Malatyaspor,58,2,0,0
63,Kerem Altunışık,Yeni Malatyaspor,57,1,0,0
64,Berat Mert,Yeni Malatyaspor,34,3,0,0
65,Metehan Ünal,Yeni Malatyaspor,22,1,0,0
66,Enes Savucu,Yeni Malatyaspor,12,1,0,0
67,Erşan Yaşa,Yeni Malatyaspor,10,1,0,0
68,Emircan Bayrakdar,Yeni Malatyaspor,10,1,0,0
69,Papiss Demba Cissé,Çaykur Rizespor,647,14,2,2
70,Efe Tecimer,Çaykur Rizespor,33,3,0,0
71,Emir Dilaver,Çaykur Rizespor,24,2,0,0
72,Mahsun Çapkan,Çaykur Rizespor,8,1,0,0
73,Soner Özdemir,Çaykur Rizespor,2,1,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Adana Demirspor  —  SF sin salario:

              player  minutesPlayed
0     Damjan Đoković           1750
1  Hijran Ali Boyaci             18
2          Loïc Rémy            295
3           Pa Dibba             14

  CG plantilla completa:

                player         player_norm
0         Alper Uludag        alper uludag
1       Arijanet Muric      arijanet muric
2   Benjamin Stambouli  benjamin stambouli
3     Birkir Bjarnason    birkir bjarnason
4   Britt Assombalonga  britt assombalonga
5       David Akintola      david akintola
6         Emrecan Uzun        emrecan uzun
7        Erhun Öztümer       erhun oztumer
8         Erkam Develi        erkam develi
9        Ferhat Kaplan       ferhat kaplan
10        Francis Ezeh        francis ezeh
11        Gökhan Inler        gokhan inler
12           Isa Güler           isa guler
13     Ismail Cokcalis     ismail cokcalis
14         Izzet Celik         izzet celik
15       Joher Rassoul       joher rassoul
16      Jonas Svensson      jonas svensson
17          Kaan Kanak          kaan kanak
18        Lucas Castro        lucas castro
19     Mario Balotelli     mario balotelli
20       Matías Vargas       matias vargas
21   Metehan Mimaroglu   metehan mimaroglu
22        Mustafa Kapi        mustafa kapi
23       Samet Akaydin       samet akaydin
24     Sedat Sahintürk     sedat sahinturk
25         Semih Güler         semih guler
26          Simon Deli          simon deli
27          Sinan Kurt          sinan kurt
28        Tarik Camdal        tarik camdal
29        Tayyip Sanuc        tayyip sanuc
30       Vedat Karakus       vedat karakus
31     Younès Belhanda     younes belhanda
32         Yunus Akgün         yunus akgun

============================================================
  Alanyaspor  —  SF sin salario:

                player  minutesPlayed
0  Çağan Kayra Erciyas             54

  CG plantilla completa:

                   player            player_norm
0             Ahmed Ildiz            ahmed ildiz
1             Ahmet Gülay            ahmet gulay
2          Buluthan Bulut         buluthan bulut
3        Chidozie Awaziem       chidozie awaziem
4          Cristian Borja         cristian borja
5         Daniel Candeias        daniel candeias
6                Davidson               davidson
7           Efecan Karaca          efecan karaca
8         Efkan Bekiroglu        efkan bekiroglu
9           El Mami Tetah          el mami tetah
10        Emirhan Aydogan        emirhan aydogan
11            Emre Akbaba            emre akbaba
12       Erencan Yardimci       erencan yardimci
13        Famara Diédhiou        famara diedhiou
14            Fatih Aksoy            fatih aksoy
15        Firat Cakiroglu        firat cakiroglu
16           Furkan Bayir           furkan bayir
17  Hasan Can Yalcintekin  hasan can yalcintekin
18         Hasan Emiroglu         hasan emiroglu
19           Ismail Zehir           ismail zehir
20            João Novais            joao novais
21               Juanfran               juanfran
22         Khouma Babacar         khouma babacar
23              Leroy Fer              leroy fer
24               Marafona               marafona
25            Miha Mevlja            miha mevlja
26      Nemanja Milunovic      nemanja milunovic
27             Oguz Aydin             oguz aydin
28             Rauf Öktem             rauf oktem
29       Serkan Kirintili       serkan kirintili
30          Tayfur Bingöl          tayfur bingol
31             Umut Günes             umut gunes
32            Veysel Ünal            veysel unal
33         Wilson Eduardo         wilson eduardo
34          Yusuf Karagöz          yusuf karagoz
35          Yusuf Özdemir          yusuf ozdemir

============================================================
  Altay  —  SF sin salario:

         player  minutesPlayed
0  Efe Sarıkaya             91
1   Erdem Ozcan             79
2      Onur Efe              9
3  Tugay Gündem              8

  CG plantilla completa:

                 player          player_norm
0    Ahmed Yasser Rayan   ahmed yasser rayan
1            Andre Poko           andre poko
2       Cebrail Karayel      cebrail karayel
3           Cem Özgener          cem ozgener
4         César Pinares        cesar pinares
5       Ceyhun Gülselam      ceyhun gulselam
6       Cihan Topaloglu      cihan topaloglu
7          Daouda Bamba         daouda bamba
8           Deniz Kadah          deniz kadah
9          Eren Erdogan         eren erdogan
10         Erhan Celenk         erhan celenk
11      Eric Björkander      eric bjorkander
12        Gencer Cansev        gencer cansev
13       Ibrahim Öztürk       ibrahim ozturk
14          Jasmin Scuk          jasmin scuk
15     Kazimcan Karatas     kazimcan karatas
16          Khaly Thiam          khaly thiam
17       Leandro Kappel       leandro kappel
18         Marco Paixão         marco paixao
19     Martín Rodríguez     martin rodriguez
20          Mateusz Lis          mateusz lis
21      Mohammad Naderi      mohammad naderi
22           Murat Akca           murat akca
23   Murat Berkan Demir   murat berkan demir
24  Nurettin Kücükdeniz  nurettin kucukdeniz
25           Ozan Özenc           ozan ozenc
26         Özgür Özkaya         ozgur ozkaya
27         Sefa Özdemir         sefa ozdemir
28     Serge Arnaud Aka     serge arnaud aka
29             Thaciano             thaciano
30           Tolga Ünlü           tolga unlu
31        Zeki Yildirim        zeki yildirim
32          Ziya Alkurt          ziya alkurt

============================================================
  Antalyaspor  —  SF sin salario:

             player  minutesPlayed
0  Mustafa Erdilman             12
1       Sinan Gümüş            118

  CG plantilla completa:

                player         player_norm
0        Admir Mehmedi       admir mehmedi
1        Alassane Ndao       alassane ndao
2              Amilton             amilton
3          Andrea Poli         andrea poli
4   Ataberk Dadakdeniz  ataberk dadakdeniz
5       Bahadir Öztürk      bahadir ozturk
6          Berat Pinar         berat pinar
7       Bünyamin Balci      bunyamin balci
8       Deni Milosevic      deni milosevic
9          Diogo Sousa         diogo sousa
10       Dogukan Nelik       dogukan nelik
11       Dogukan Özkan       dogukan ozkan
12       Dogukan Sinik       dogukan sinik
13       Enzo Crivelli       enzo crivelli
14       Eren Albayrak       eren albayrak
15        Erkan Eyibil        erkan eyibil
16         Ersin Zehir         ersin zehir
17    Fedor Kudryashov    fedor kudryashov
18            Fernando            fernando
19               Fredy               fredy
20  Gökdeniz Bayrakdar  gokdeniz bayrakdar
21         Güray Vural         guray vural
22         Haji Wright         haji wright
23        Hakan Özmert        hakan ozmert
24        Harun Alpsoy        harun alpsoy
25      Houssam Ghacha      houssam ghacha
26        Luiz Adriano        luiz adriano
27    Melih Enes Uygun    melih enes uygun
28         Mert Yilmaz         mert yilmaz
29               Naldo               naldo
30          Nuri Sahin          nuri sahin
31        Paul Mukairu        paul mukairu
32         Ruud Boffin         ruud boffin
33     Sherel Floranus     sherel floranus
34          Ufuk Akyol          ufuk akyol
35         Veysel Sari         veysel sari

============================================================
  Başakşehir FK  —  SF sin salario:

             player  minutesPlayed
0  Efe Arda Koyuncu             90

  CG plantilla completa:

                   player            player_norm
0            Ahmed Kutucu           ahmed kutucu
1            Ahmet Kivanc           ahmet kivanc
2      Alexandru Epureanu     alexandru epureanu
3          Alican Özfesli         alican ozfesli
4            Atabey Cicek           atabey cicek
5            Berkay Özcan           berkay ozcan
6         Danijel Aleksic        danijel aleksic
7            Deniz Dilmen           deniz dilmen
8             Deniz Türüc            deniz turuc
9              Edin Visca             edin visca
10             Emre Colak             emre colak
11            Emre Kaplan            emre kaplan
12            Emre Karaal            emre karaal
13           Enes Karakus           enes karakus
14    Fredrik Gulbrandsen    fredrik gulbrandsen
15     Hasan Ali Kaldirim     hasan ali kaldirim
16         Júnior Caiçara         junior caicara
17             Léo Duarte             leo duarte
18             Lucas Lima             lucas lima
19        Mahmut Tekdemir        mahmut tekdemir
20          Miguel Vieira          miguel vieira
21      Muhammed Sengezer      muhammed sengezer
22           Nacer Chadli           nacer chadli
23       Ömer Ali Sahiner       omer ali sahiner
24             Peter Zulj             peter zulj
25                  Pizzi                  pizzi
26                  Ponck                  ponck
27            Ravil Tagir            ravil tagir
28             Salih Ucan             salih ucan
29       Sener Özbayrakli       sener ozbayrakli
30          Serdar Gürler          serdar gurler
31          Stefano Okaka          stefano okaka
32          Tolga Cigerci          tolga cigerci
33              Trezeguet              trezeguet
34         Volkan Babacan         volkan babacan
35  Youssouf Ndayishimiye  youssouf ndayishimiye

============================================================
  Beşiktaş JK  —  SF sin salario:

  player  minutesPlayed
0  Souza           2607

  CG plantilla completa:

                    player             player_norm
0              Adem Ljajic             adem ljajic
1              Ajdin Hasic             ajdin hasic
2            Alex Teixeira           alex teixeira
3              Atakan Üner             atakan uner
4         Atiba Hutchinson        atiba hutchinson
5             Can Bozdogan            can bozdogan
6               Cyle Larin              cyle larin
7             Domagoj Vida            domagoj vida
8                  Douglas                 douglas
9               Ege Tiknaz              ege tiknaz
10         Emirhan Delibas         emirhan delibas
11          Emirhan Ilkhan          emirhan ilkhan
12             Emre Bilgin             emre bilgin
13        Ersin Destanoglu        ersin destanoglu
14        Fabrice N'Sakala        fabrice n sakala
15       Francisco Montero       francisco montero
16  Georges-Kevin N'Koudou  georges kevin n koudou
17             Gökhan Töre             gokhan tore
18         Göktug Baytekin         goktug baytekin
19            Güven Yalcin            guven yalcin
20           Jeremain Lens           jeremain lens
21                   Josef                   josef
22           Kenan Karaman           kenan karaman
23           Kerem Kalafat           kerem kalafat
24            Mehmet Topal            mehmet topal
25              Mert Günok              mert gunok
26         Michy Batshuayi         michy batshuayi
27          Miralem Pjanic          miralem pjanic
28           Muhayer Oktay           muhayer oktay
29             Necip Uysal             necip uysal
30         Oguzhan Özyakup         oguzhan ozyakup
31          Rachid Ghezzal          rachid ghezzal
32           Ridvan Yilmaz           ridvan yilmaz
33              Salih Ucan              salih ucan
34           Serdar Saatci           serdar saatci
35              Umut Meras              umut meras
36         Valentin Rosier         valentin rosier
37                Welinton                welinton

============================================================
  Fenerbahçe  —  SF sin salario:

                player  minutesPlayed
0  Mbwana Ally Samatta            162

  CG plantilla completa:

                 player          player_norm
0        Altay Bayindir       altay bayindir
1            Arda Güler           arda guler
2         Arda Kurtulan        arda kurtulan
3         Attila Szalai        attila szalai
4        Bartu Kulbilge       bartu kulbilge
5            Berke Özer           berke ozer
6   Bright Osayi-Samuel  bright osayi samuel
7         Burak Kapacak        burak kapacak
8      Cagtay Kurukalip     cagtay kurukalip
9           Diego Rossi          diego rossi
10     Dimitrios Pelkas     dimitrios pelkas
11       Enner Valencia       enner valencia
12       Ertugrul Cetin       ertugrul cetin
13      Fatih Sanlitürk      fatih sanliturk
14       Ferdi Kadioglu       ferdi kadioglu
15          Filip Novak          filip novak
16    Irfan Can Kahveci    irfan can kahveci
17            José Sosa            jose sosa
18         Luiz Gustavo         luiz gustavo
19     Marcel Tisserand     marcel tisserand
20            Max Meyer            max meyer
21       Mergim Berisha       mergim berisha
22    Mert Hakan Yandas    mert hakan yandas
23           Mesut Özil           mesut ozil
24        Miguel Crespo        miguel crespo
25            Miha Zajc            miha zajc
26          Min-jae Kim          min jae kim
27   Muhammed Gümüskaya   muhammed gumuskaya
28         Murat Saglam         murat saglam
29          Nabil Dirar          nabil dirar
30        Nazim Sangaré        nazim sangare
31           Ozan Tufan           ozan tufan
32          Serdar Aziz          serdar aziz
33        Serdar Dursun        serdar dursun
34          Sinan Gümüs          sinan gumus

============================================================
  Galatasaray  —  SF sin salario:

             player  minutesPlayed
0      Erick Pulgar            602
1  Gustavo Assunção            135
2    Radamel Falcao             10
3        Semih Kaya           1954

  CG plantilla completa:

                 player          player_norm
0    Alexandru Cicaldau   alexandru cicaldau
1       Alpaslan Öztürk      alpaslan ozturk
2            Arda Turan           arda turan
3        Atalay Babacan       atalay babacan
4            Aytac Kara           aytac kara
5       Bafétimbi Gomis      bafetimbi gomis
6          Baris Yilmaz         baris yilmaz
7          Bartug Elmaz         bartug elmaz
8          Berk Balaban         berk balaban
9          Berkan Kutlu         berkan kutlu
10  Christian Luyindama  christian luyindama
11       DeAndre Yedlin       deandre yedlin
12          Emre Kilinc          emre kilinc
13         Fatih Öztürk         fatih ozturk
14     Fernando Muslera     fernando muslera
15          Gökay Güney          gokay guney
16     Halil Dervisoglu     halil dervisoglu
17           Iñaki Peña           inaki pena
18          Ismail Cipe          ismail cipe
19          Kaan Arslan          kaan arslan
20     Kerem Aktürkoglu     kerem akturkoglu
21               Marcão               marcao
22         Mbaye Diagne         mbaye diagne
23      Mostafa Mohamed      mostafa mohamed
24     Ogulcan Caglayan     ogulcan caglayan
25      Olimpiu Morutan      olimpiu morutan
26    Omar Elabdellaoui    omar elabdellaoui
27          Ömer Bayram          omer bayram
28  Patrick van Aanholt  patrick van aanholt
29           Ryan Babel           ryan babel
30           Sacha Boey           sacha boey
31     Sofiane Feghouli     sofiane feghouli
32     Taylan Antalyali     taylan antalyali
33       Victor Nelsson       victor nelsson

============================================================
  Giresunspor  —  SF sin salario:

                 player  minutesPlayed
0      Anıl Yiğit Çınar             90
1             Baris Gun             59
2            Emre Nizam              1
3          Furkan Kütük             90
4           Kaan Yilmaz              1
5          Kasim Kosker             31
6  Metin Caner Akbayrak             54
7    Muhammed Gümüşkaya           1196
8             Şahin Dik             36

  CG plantilla completa:

                player         player_norm
0         Alexis Pérez        alexis perez
1        Alperen Aydin       alperen aydin
2           Arda Kilic          arda kilic
3          Aziz Behich         aziz behich
4         Cekdar Orhan        cekdar orhan
5            Chiquinho           chiquinho
6          Dogac Cifci         dogac cifci
7        Doganay Aygün       doganay aygun
8              Douglas             douglas
9        Emre Tasdemir       emre tasdemir
10         Erkan Anapa         erkan anapa
11      Erol Can Akdag      erol can akdag
12           Esat Mala           esat mala
13        Fatih Yilmaz        fatih yilmaz
14              Flávio              flavio
15    Fousseni Diabaté    fousseni diabate
16        Göktan Cörüt        goktan corut
17      Hamidou Traore      hamidou traore
18   Hayrullah Bilazer   hayrullah bilazer
19      Hüsamettin Tut      husamettin tut
20      Ibrahima Balde      ibrahima balde
21       Joe Champness       joe champness
22      Joey Pelupessy      joey pelupessy
23      Mamadou Diarra      mamadou diarra
24          Okan Kocuk          okan kocuk
25        Onurcan Piri        onurcan piri
26    Sergen Picinciol    sergen picinciol
27              Sergio              sergio
28    Shapi Suleymanov    shapi suleymanov
29  Souleymane Doukara  souleymane doukara
30       Tolgahan Acar       tolgahan acar
31          Umut Nayir          umut nayir
32  Younousse Sankharé  younousse sankhare
33          Zeki Yavru          zeki yavru

============================================================
  Göztepe  —  SF sin salario:

               player  minutesPlayed
0      Atalay Çayırlı              1
1          Aytaç Kara            599
2       Cengizhan Sen              8
3        Firat Arslan              8
4         Yunus Toplu              1
5  İzzet Furkan Malak             21

  CG plantilla completa:

                 player          player_norm
0          Adis Jahovic         adis jahovic
1           Altay Özkan          altay ozkan
2          Arda Özcimen         arda ozcimen
3        Atakan Cankaya       atakan cankaya
4           Atinc Nukan          atinc nukan
5        Balázs Megyeri       balazs megyeri
6           Berkan Emir          berkan emir
7         Beykan Simsek        beykan simsek
8           Brown Ideye          brown ideye
9         Cherif Ndiaye        cherif ndiaye
10        David Tijanic        david tijanic
11      Dino Arslanagic      dino arslanagic
12     Dzenan Burekovic     dzenan burekovic
13     Efe Can Sacikara     efe can sacikara
14      Ege Özkayimoglu      ege ozkayimoglu
15           Eren Bilen           eren bilen
16          Erkam Kömür          erkam komur
17      Franco Di Santo      franco di santo
18   François Moubandje   francois moubandje
19        Halil Akbunar        halil akbunar
20  Irfan Can Egribayat  irfan can egribayat
21    Kahraman Demirtas    kahraman demirtas
22          Kenan Piric          kenan piric
23          Kerim Alici          kerim alici
24       Kubilay Sönmez       kubilay sonmez
25             Lourency             lourency
26          Makana Baku          makana baku
27      Marko Mihojevic      marko mihojevic
28       Metin Yildirim       metin yildirim
29         Murat Paluli         murat paluli
30       Obinna Nwobodo       obinna nwobodo
31      Oussama Tannane      oussama tannane
32        Soner Aydogdu        soner aydogdu
33           Tibet Öniz           tibet oniz
34         Wilker Ángel         wilker angel
35         Yalcin Kayan         yalcin kayan
36          Yusuf Talum          yusuf talum

============================================================
  Hatayspor  —  SF sin salario:

            player  minutesPlayed
0      Engin Aksoy              8
1        Eray Akar             22
2  Munir El Kajoui           3060
3   Yassine Benzia            762

  CG plantilla completa:

                 player          player_norm
0      Abdullah Yigiter     abdullah yigiter
1          Adama Traoré         adama traore
2        Ayoub El Kaabi       ayoub el kaabi
3       Bertug Yildirim      bertug yildirim
4        Bülent Cevahir       bulent cevahir
5         Burak Camoglu        burak camoglu
6           Burak Öksüz          burak oksuz
7     Dylan Saint-Louis    dylan saint louis
8            Emre Colak           emre colak
9           Emre Kaplan          emre kaplan
10           Eren Fansa           eren fansa
11        Fatih Kurucuk        fatih kurucuk
12         Isaac Sackey         isaac sackey
13              Kahraba              kahraba
14  Kamil Ahmet Cörekci  kamil ahmet corekci
15           Mame Diouf           mame diouf
16      Mehdi Boudjemaa      mehdi boudjemaa
17      Mohammed Kamara      mohammed kamara
18        Muhammed Mert        muhammed mert
19                Munir                munir
20           Onur Ergün           onur ergun
21        Rúben Ribeiro        ruben ribeiro
22      Saba Lobjanidze      saba lobjanidze
23            Sadik Bas            sadik bas
24         Sam Adekugbe         sam adekugbe
25       Selimcan Temel       selimcan temel
26        Simon Falette        simon falette
27        Strahil Popov        strahil popov
28    Yavuz Bugra Boyar    yavuz bugra boyar

============================================================
  Kasımpaşa  —  SF sin salario:

                 player  minutesPlayed
0            Awer Mabil            395
1  Harun Elyesa Akaydın             45
2        Jackson Muleka           1062
3        Mickael Tirpan              9
4           Nabil Dirar            265
5           Tunay Torun            456

  CG plantilla completa:

                  player           player_norm
0            Ahmet Engin           ahmet engin
1           Anil Özcelik          anil ozcelik
2           Berat Kalkan          berat kalkan
3             Berk Cetin            berk cetin
4       Dogucan Haspolat      dogucan haspolat
5         Erdem Canpolat        erdem canpolat
6      Ertugrul Taskiran     ertugrul taskiran
7      Evren Eren Elmali     evren eren elmali
8         Feyzi Yildirim        feyzi yildirim
9    Florent Hadergjonaj   florent hadergjonaj
10    Haris Hajradinovic    haris hajradinovic
11           Harun Tekin           harun tekin
12  Hasan Emre Yesilyurt  hasan emre yesilyurt
13         Jeffrey Bruma         jeffrey bruma
14           Kevin Varga           kevin varga
15          Loret Sadiku          loret sadiku
16          Mamadou Fall          mamadou fall
17      Mehmet Enes Sari      mehmet enes sari
18        Michal Travnik        michal travnik
19   Mortadha Ben Ouanes   mortadha ben ouanes
20     Nicolai Jörgensen     nicolai jorgensen
21          Rayane Aabid          rayane aabid
22             Ryan Donk             ryan donk
23           Sakib Aytac           sakib aytac
24        Tarkan Serbest        tarkan serbest
25          Tomas Brecka          tomas brecka
26            Umut Bozok            umut bozok
27           Uros Spajic           uros spajic
28     Valentin Eysseric     valentin eysseric
29          Yasin Dülger          yasin dulger
30         Yusuf Erdogan         yusuf erdogan

============================================================
  Kayserispor  —  SF sin salario:

              player  minutesPlayed
0      Doğan Alemdar             90
1        Ethem Balcı             21
2    Hayrullah Erkip            111
3     Jocelyn Janneh             13
4  Mehmet Eray Özbek              3
5      Talha Karatas             45
6       Zoran Kvržić             90

  CG plantilla completa:

                   player            player_norm
0       Abdulkadir Parmak      abdulkadir parmak
1       Abdulkadir Tasdan      abdulkadir tasdan
2              Ali Karimi             ali karimi
3       Andrea Bertolacci      andrea bertolacci
4        Anthony Uzodimma       anthony uzodimma
5            Arif Kocaman           arif kocaman
6          Bernard Mensah         bernard mensah
7           Bilal Bayazit          bilal bayazit
8             Carlos Mané            carlos mane
9              Cenk Gönen             cenk gonen
10      Daniel Avramovski      daniel avramovski
11  Dimitrios Kolovetsios  dimitrios kolovetsios
12           Emrah Bassan           emrah bassan
13             Emre Demir             emre demir
14         Gökhan Sazdagi         gokhan sazdagi
15     Gustavo Campanharo     gustavo campanharo
16          Ibrahim Akdag          ibrahim akdag
17           Ilhan Parlak           ilhan parlak
18         Joseph Attamah         joseph attamah
19        Kevin Luckassen        kevin luckassen
20          Lionel Carole          lionel carole
21         Majid Hosseini         majid hosseini
22             Mame Thiam             mame thiam
23       Manuel Fernandes       manuel fernandes
24       Mario Gavranovic       mario gavranovic
25             Mert Cetin             mert cetin
26         Miguel Cardoso         miguel cardoso
27       Mustafa Pektemek       mustafa pektemek
28       Nurettin Korkmaz       nurettin korkmaz
29          Olivier Kemen          olivier kemen
30              Ömer Uzun              omer uzun
31             Onur Bulut             onur bulut
32        Ramazan Civelek        ramazan civelek
33         Silviu Lung Jr         silviu lung jr
34           Ugur Demirok           ugur demirok
35           Yasir Subasi           yasir subasi
36              Yaw Ackah              yaw ackah

============================================================
  Konyaspor  —  SF sin salario:

       player  minutesPlayed
0  Erdon Daci             12

  CG plantilla completa:

                 player          player_norm
0   Abdülkerim Bardakci  abdulkerim bardakci
1         Adil Demirbag        adil demirbag
2          Ahmed Hassan         ahmed hassan
3           Ahmet Calik          ahmet calik
4       Ahmet Karademir      ahmet karademir
5            Alberk Koc           alberk koc
6          Alper Uludag         alper uludag
7       Amar Rahmanovic      amar rahmanovic
8               Amilton              amilton
9   Amir Hadziahmetovic  amir hadziahmetovic
10        Artem Kravets        artem kravets
11       Baris Yardimci       baris yardimci
12      Ekrem Kayilibal      ekrem kayilibal
13        Emre Pehlivan        emre pehlivan
14         Endri Cekici         endri cekici
15        Eray Birnican        eray birnican
16           Erten Ersu           erten ersu
17            Guilherme            guilherme
18        Ibrahim Sehic        ibrahim sehic
19       Izzet Karaboga       izzet karaboga
20      Konrad Michalak      konrad michalak
21         Marin Anicic         marin anicic
22         Musa Cagiran         musa cagiran
23     Nafican Yardimci     nafican yardimci
24          Nejc Skubic          nejc skubic
25        Ogulcan Ülgün        ogulcan ulgun
26      Paul-José Mpoku      paul jose mpoku
27        Serdar Gürler        serdar gurler
28     Sokol Cikalleshi     sokol cikalleshi
29         Soner Dikmen         soner dikmen
30      Ugurcan Yazgili      ugurcan yazgili
31         Zymer Bytyqi         zymer bytyqi

============================================================
  Sivasspor  —  SF sin salario:

            player  minutesPlayed
0      Emirhan Tak             29
1   Halit Çokyaşar              1
2      Kaan Onaran              1
3  Mehmet Albayrak             61
4    Moussa Konaté            245
5   Muhammed Ergin              2

  CG plantilla completa:

                 player          player_norm
0    Aaron Appindangoyé   aaron appindangoye
1            Ahmet Oguz           ahmet oguz
2       Ali Sasal Vural      ali sasal vural
3       Caner Osmanpasa      caner osmanpasa
4      Dimitrios Goutas     dimitrios goutas
5         Emre Satilmis        emre satilmis
6     Erdogan Yesilyurt    erdogan yesilyurt
7           Fayçal Fajr          faycal fajr
8      Fredrik Ulvestad     fredrik ulvestad
9          Hakan Arslan         hakan arslan
10          Isaac Cofie          isaac cofie
11          Jorge Félix          jorge felix
12  Kerem Atakan Kesgin  kerem atakan kesgin
13        Koray Altinay        koray altinay
14           Leke James           leke james
15           Max Gradel           max gradel
16     Muammer Yildirim     muammer yildirim
17    Mustapha Yatabaré    mustapha yatabare
18   Okechukwu Azubuike   okechukwu azubuike
19    Olarenwaju Kayode    olarenwaju kayode
20        Özkan Yigiter        ozkan yigiter
21       Pedro Henrique       pedro henrique
22         Samba Camara         samba camara
23          Sefa Yilmaz          sefa yilmaz
24          Ugur Ciftci          ugur ciftci
25          Volkan Egri          volkan egri
26           Ziya Erdal           ziya erdal

============================================================
  Yeni Malatyaspor  —  SF sin salario:

               player  minutesPlayed
0        Barış Başdaş            517
1          Berat Mert             34
2         Berat Yaman            112
3       Burak Efe Yaz             58
4   Emircan Bayrakdar             10
5         Enes Savucu             12
6          Erşan Yaşa             10
7     Kerem Altunışık             57
8        Metehan Ünal             22
9          Umut Taniş            201
10      Walter Bwalya            132
11         Yiğit Ulaş            136

  CG plantilla completa:

                    player             player_norm
0         Abdulsamed Damlu        abdulsamed damlu
1               Adem Büyük              adem buyuk
2                Aly Malle               aly malle
3             Atakan Müjde            atakan mujde
4          Benjamin Tetteh         benjamin tetteh
5              Berk Yildiz             berk yildiz
6            Bugra Cagiran           bugra cagiran
7             Didier Ndong            didier ndong
8             Eric Ndizeye            eric ndizeye
9              Ertac Özbir             ertac ozbir
10          Eyüp Türkaslan          eyup turkaslan
11            Gastón Campi            gaston campi
12          Godfred Donsah          godfred donsah
13              Haqi Osman              haqi osman
14             Hasan Özkan             hasan ozkan
15     Jospin Nshimirimana     jospin nshimirimana
16             Karim Hafez             karim hafez
17              Kenan Özer              kenan ozer
18     Kubilay Kanatsizkus     kubilay kanatsizkus
19           Mehdi Zeffane           mehdi zeffane
20     Mert Mirac Altintas     mert mirac altintas
21              Mert Örnek              mert ornek
22          Mounir Chouiar          mounir chouiar
23  Muhammed Emin Sarikaya  muhammed emin sarikaya
24             Murat Aksit             murat aksit
25      Mustafa Eskihellac      mustafa eskihellac
26             Nouha Dicko             nouha dicko
27        Nuri Fatih Aydin        nuri fatih aydin
28      Okechukwu Azubuike      okechukwu azubuike
29         Oussama Haddadi         oussama haddadi
30     Philip Gameli Awuku     philip gameli awuku
31            Rayane Aabid            rayane aabid
32         Sadik Ciftpinar         sadik ciftpinar
33              Semih Kaya              semih kaya
34           Stevie Mallan           stevie mallan
35                Taha Gür                taha gur
36                 Wallace                 wallace

============================================================
  Çaykur Rizespor  —  SF sin salario:

               player  minutesPlayed
0         Efe Tecimer             33
1        Emir Dilaver             24
2       Mahsun Çapkan              8
3  Papiss Demba Cissé            647
4       Soner Özdemir              2

  CG plantilla completa:

                 player          player_norm
0            Alberk Koc           alberk koc
1           Alper Potuk          alper potuk
2            Aminu Umar           aminu umar
3            Anil Yasar           anil yasar
4            Aziz Aksoy           aziz aksoy
5            Bryan Dabo           bryan dabo
6            Can Ceylan           can ceylan
7         Cemali Sertel        cemali sertel
8       Damjan Djokovic      damjan djokovic
9          Deniz Hümmet         deniz hummet
10        Emirhan Topcu        emirhan topcu
11        Eren Albayrak        eren albayrak
12         Eren Karadag         eren karadag
13            Erik Sabo            erik sabo
14      Fabrício Baiano      fabricio baiano
15     Fernando Boldrin     fernando boldrin
16     Gedson Fernandes     gedson fernandes
17         Gökhan Akkan         gokhan akkan
18         Gökhan Gönül         gokhan gonul
19          Güvenc Usta          guvenc usta
20      Joel Pohjanpalo      joel pohjanpalo
21  Kubilay Kanatsizkus  kubilay kanatsizkus
22       Lebogang Phiri       lebogang phiri
23            Loïc Rémy            loic remy
24                Ponck                ponck
25       Ronaldo Mendes       ronaldo mendes
26     Sebastian Holmén     sebastian holmen
27             Selim Ay             selim ay
28          Tarik Cetin          tarik cetin
29           Tyler Boyd           tyler boyd
30   Ugur Can Semizoglu   ugur can semizoglu
31      Yannick Bolasie      yannick bolasie
32       Yasin Pehlivan       yasin pehlivan
33           Yusuf Sari           yusuf sari
34         Zafer Görgen         zafer gorgen

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('souza', 'besiktas jk')                    : ('josef', 'besiktas jk'),
    ('munir el kajoui', 'hatayspor')            : ('munir', 'hatayspor'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 2

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: souza (besiktas jk) → josef (besiktas jk)
✅ Match manual aplicado: munir el kajoui (hatayspor) → munir (hatayspor)

Tras matches manuales: 563/635 (88.7%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_turkey_2122.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_turkey_2122.csv
   Jugadores totales:  635
   Con salario:        563
   Sin salario (NaN):  72
   Columnas:           121