# 03 · Join Sofascore + Capology — Turkey Süper Lig 22/23

Integración de estadísticas de rendimiento (Sofascore) con datos salariales (Capology)
para la temporada **2022/23 de Süper Lig turca**.

**Flujo de matching:**
1. Normalización de nombres (tildes, mayúsculas, caracteres especiales)
2. `TEAM_MAP`: alineación manual de nombres de equipo entre fuentes
3. Merge exacto normalizado
4. Fuzzy matching en cuatro niveles:
   - Score ≥ 0.90 → aceptación automática
   - 0.75 ≤ score < 0.90 → revisión manual
   - 0.50 ≤ score < 0.75 → revisión manual estricta
   - score < 0.50 → revisión manual muy estricta
5. Revisión de jugadores sin salario
6. Guardado en `data/master/`

---

## 1. Imports y rutas

In [1]:
import pandas as pd
import unicodedata
import re
from rapidfuzz import fuzz
from pathlib import Path
from IPython.display import display

ROOT       = Path.cwd().parents[1]
SF_DIR     = ROOT / 'data' / 'processed' / 'sofascore'
CG_DIR     = ROOT / 'data' / 'processed' / 'capology'
MASTER_DIR = ROOT / 'data' / 'master'
MASTER_DIR.mkdir(parents=True, exist_ok=True)

print('✅ Rutas configuradas')
print(f'   Root:   {ROOT}')
print(f'   Master: {MASTER_DIR}')

✅ Rutas configuradas
   Root:   d:\USER\Desktop\TFM
   Master: d:\USER\Desktop\TFM\data\master

## 2. Función de normalización

In [2]:
def normalize(s):
    """
    Normaliza un string para comparación: elimina tildes, pasa a minúsculas,
    elimina caracteres especiales y espacios extra.
    """
    if pd.isna(s):
        return ''
    s = str(s)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    s = re.sub(r'[^a-z0-9\s]', ' ', s.lower().strip())
    return re.sub(r'\s+', ' ', s).strip()

print('✅ Función definida')

✅ Función definida

## 3. Carga de datos

In [3]:
df_sf = pd.read_csv(SF_DIR / 'df_turkey_2223.csv').copy()
df_cg = pd.read_csv(CG_DIR / 'cg_turkey_2223.csv').copy()

print(f'Sofascore:  {df_sf.shape[0]} jugadores | {df_sf.shape[1]} columnas')
print(f'Capology:   {df_cg.shape[0]} jugadores | {df_cg.shape[1]} columnas')

Sofascore:  588 jugadores | 116 columnas
Capology:   651 jugadores | 9 columnas

## 4. Normalización

In [4]:
df_sf['player_norm'] = df_sf['player'].apply(normalize)
df_sf['team_norm']   = df_sf['team'].apply(normalize)
df_cg['player_norm'] = df_cg['player'].apply(normalize)
df_cg['team_norm']   = df_cg['club'].apply(normalize)

print('✅ Normalización aplicada')

✅ Normalización aplicada

## 5. Alineación de equipos (TEAM_MAP)

### 5.1 Identificar discrepancias de nombres de equipo

In [5]:
solo_sf = set(df_sf['team_norm'].unique()) - set(df_cg['team_norm'].unique())
solo_cg = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())

print('En Sofascore pero no en Capology:')
for e in sorted(solo_sf): print(f'   {e}')
print()
print('En Capology pero no en Sofascore:')
for e in sorted(solo_cg): print(f'   {e}')

En Sofascore pero no en Capology:
   basaksehir fk
   besiktas jk
   fatih karagumruk
   gaziantep fk
   kasmpasa
   mke ankaragucu

En Capology pero no en Sofascore:
   ankaragucu
   basaksehir
   besiktas
   gaziantep bb
   karagumrukspor
   kasimpasa

### 5.2 Aplicar TEAM_MAP

Rellenar con las discrepancias identificadas en la celda anterior.

In [6]:
# ── Ajustar según la celda anterior ──────────────────────────
TEAM_MAP = {'ankaragucu':'mke ankaragucu',
            'basaksehir':'basaksehir fk',
            'besiktas':'besiktas jk',
            'gaziantep bb':'gaziantep fk',
            'karagumrukspor':'fatih karagumruk',
            'kasimpasa':'kasmpasa'
}
# ─────────────────────────────────────────────────────────────

df_cg['team_norm'] = df_cg['team_norm'].replace(TEAM_MAP)

diff = set(df_cg['team_norm'].unique()) - set(df_sf['team_norm'].unique())
if diff:
    print(f'⚠️  Equipos de CG aún sin match en SF: {diff}')
else:
    print('✅ Todos los equipos alineados')

✅ Todos los equipos alineados

## 6. Merge exacto normalizado

In [7]:
df_merged = df_sf.merge(
    df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
            'position', 'age', 'nationality']],
    on=['player_norm', 'team_norm'],
    how='left'
)

matched = df_merged['gross_annual_eur'].notna().sum()
total   = len(df_merged)

print(f'Merge exacto: {matched}/{total} ({matched/total:.1%})')
print(f'Sin emparejar: {total - matched}')

Merge exacto: 464/588 (78.9%)
Sin emparejar: 124

## 7. Fuzzy matching sobre los no emparejados

Se generan candidatos para todos los jugadores sin match exacto,
sin umbral mínimo, y se clasifican en cuatro niveles.

In [8]:
df_unmatched = df_merged[df_merged['gross_annual_eur'].isna()].copy()
cg_by_team   = df_cg.groupby('team_norm')['player_norm'].apply(list).to_dict()

rows = []
for _, row in df_unmatched[['player','team','player_norm','team_norm']].drop_duplicates().iterrows():
    candidates = cg_by_team.get(row['team_norm'], [])
    best_match, best_score = None, 0
    for cand in candidates:
        score = fuzz.ratio(row['player_norm'], cand) / 100
        if score > best_score:
            best_score = score
            best_match = cand
    if best_match is not None:
        rows.append({
            'player_sf'  : row['player'],
            'team'       : row['team'],
            'player_norm': row['player_norm'],
            'team_norm'  : row['team_norm'],
            'cg_match'   : best_match,
            'score'      : round(best_score, 3)
        })

df_candidates = pd.DataFrame(rows).sort_values('score', ascending=False)
auto_matches     = df_candidates[df_candidates['score'] >= 0.90].copy()
review_matches   = df_candidates[(df_candidates['score'] >= 0.75) & (df_candidates['score'] < 0.90)].copy()
low_matches      = df_candidates[(df_candidates['score'] >= 0.50) & (df_candidates['score'] < 0.75)].copy()
very_low_matches = df_candidates[df_candidates['score'] < 0.50].copy()

print(f'Auto-aceptados    (score ≥ 0.90):          {len(auto_matches)}')
print(f'Revisión media    (0.75 ≤ score < 0.90):   {len(review_matches)}')
print(f'Revisión estricta (0.50 ≤ score < 0.75):   {len(low_matches)}')
print(f'Revisión muy est. (score < 0.50):           {len(very_low_matches)}')

Auto-aceptados    (score ≥ 0.90):          41
Revisión media    (0.75 ≤ score < 0.90):   20
Revisión estricta (0.50 ≤ score < 0.75):   37
Revisión muy est. (score < 0.50):           26

### 7.1 Matches automáticos (score ≥ 0.90)

Revisar para confirmar que todos son correctos.

In [9]:
auto_matches[['player_sf', 'team', 'cg_match', 'score']]

                player_sf             team               cg_match  score
65   Dimitris Kolovetsios      Kayserispor  dimitrios kolovetsios  0.976
12    Abdülkerim Bardakcı      Galatasaray    abdulkerim bardakci  0.973
47     Efthymis Koulouris       Alanyaspor    efthymios koulouris  0.973
45      Ertuğrul Taşkıran        Kasımpaşa      ertugrul taskiran  0.970
108     Turgay Gemicibaşı        Kasımpaşa      turgay gemicibasi  0.970
29       Muammer Sarıkaya     İstanbulspor       muammer sarikaya  0.968
50       Taylan Antalyalı   MKE Ankaragücü       taylan antalyali  0.968
6         Dimitris Goutas        Sivasspor       dimitrios goutas  0.968
23       Kazımcan Karataş      Galatasaray       kazimcan karatas  0.968
63       Şener Özbayraklı    Başakşehir FK       sener ozbayrakli  0.968
69        Taha Altıkardeş      Trabzonspor        taha altikardes  0.966
48        Fredrik Midtsjø      Galatasaray        fredrik midtsjo  0.966
107       İsmail Çokçalış  Adana Demirspor        ismail cokcalis  0.966
64         Bünyamin Balcı      Antalyaspor         bunyamin balci  0.963
90         Salih Kavrazlı  Adana Demirspor         salih kavrazli  0.963
67         Gökhan Sazdağı      Kayserispor         gokhan sazdagi  0.963
7          Ferdi Kadıoğlu       Fenerbahçe         ferdi kadioglu  0.963
8           Samet Akaydın       Fenerbahçe          samet akaydin  0.960
37          Uğurcan Çakır      Trabzonspor          ugurcan cakir  0.960
92           Yasir Subaşı        Konyaspor           yasir subasi  0.957
32           Furkan Bayır       Alanyaspor           furkan bayir  0.957
57           Musa Çağıran        Hatayspor           musa cagiran  0.957
40           Robin Yalçın        Sivasspor           robin yalcin  0.957
34            Veysel Sarı      Antalyaspor            veysel sari  0.952
111           Kagan Bağış     İstanbulspor            kagan bagis  0.952
1              Yusuf Sarı  Adana Demirspor             yusuf sari  0.947
49             Oğuz Aydın       Alanyaspor             oguz aydin  0.947
99     Yaroslav Rakitskyi  Adana Demirspor     yaroslav rakitskiy  0.944
77     Hasan Ali Kaldırım   MKE Ankaragücü     hasan ali kaldirim  0.941
51              Onur Ayık     Ümraniyespor              onur ayik  0.941
66       Andrej Đokanović   MKE Ankaragücü      andrej djokanovic  0.938
58       Erencan Yardımcı       Alanyaspor       erencan yardimci  0.933
3         Sadık Çiftpınar        Kasımpaşa        sadik ciftpinar  0.929
54        Uğurcan Yazğılı        Konyaspor        ugurcan yazgili  0.929
26         Altay Bayındır       Fenerbahçe         altay bayindir  0.923
106    Mountassir Lahtimi      Trabzonspor      montasser lahtimi  0.914
24        Charis Charisis        Sivasspor     charilaos charisis  0.909
72           Yusuf Yazıcı      Trabzonspor           yusuf yazici  0.909
102           Berk Yıldız  Adana Demirspor            berk yildiz  0.900
38            Emre Kılınç   MKE Ankaragücü            emre kilinc  0.900
27            Kerim Alıcı        Hatayspor            kerim alici  0.900

### 7.2 Revisión media (0.75 ≤ score < 0.90)

Añadir a `EXCLUDE_FROM_FUZZY` el `player_norm` de los incorrectos.

In [10]:
review_matches[['player_sf', 'team', 'cg_match', 'score']]

                   player_sf             team              cg_match  score
28          Muammer Yıldırım        Sivasspor      muammer yildirim  0.897
55           Bertuğ Yıldırım      Antalyaspor       bertug yildirim  0.889
80                  Serginho      Giresunspor                sergio  0.857
52      Bahadır Han Güngördü   MKE Ankaragücü      bahadir gungordu  0.857
14          Serkan Kırıntılı     Ümraniyespor      serkan kirintili  0.857
110      Yunus Emre Mertoğlu     Ümraniyespor        yunus mertoglu  0.848
100          Baran Ali Gezek      Kayserispor           baran gezek  0.846
116              Engin Aksoy        Hatayspor       engin can aksoy  0.846
83      Houssameddine Ghacha      Antalyaspor        houssam ghacha  0.824
117      Çağan Kayra Erciyas       Alanyaspor         cagan erciyas  0.812
4         Tayyip Talha Sanuç      Beşiktaş JK          tayyip sanuc  0.800
85     Fatih Yiğit Şanlıtürk     Ümraniyespor       fatih sanliturk  0.800
71      Joher Khadim Rassoul       Alanyaspor         joher rassoul  0.788
46             Philippe Keny    Başakşehir FK  philippe paulin keny  0.788
104        Ali Sühan Demirel        Kasımpaşa           ali demirel  0.786
13       Kartal Kayra Yılmaz     Ümraniyespor         kartal yilmaz  0.774
30          Mame Biram Diouf        Konyaspor            mame diouf  0.769
78             Fabiano Souza        Kasımpaşa         fabiano silva  0.769
35        Recep Burak Yılmaz        Hatayspor          burak yilmaz  0.759
41   Babajide David Akintola  Adana Demirspor        david akintola  0.757

In [11]:
# ── Falsos positivos a excluir del nivel medio ────────────────
EXCLUDE_FROM_FUZZY = [

]
# ─────────────────────────────────────────────────────────────

review_accepted = review_matches[~review_matches['player_norm'].isin(EXCLUDE_FROM_FUZZY)]
print(f'Aceptados: {len(review_accepted)} | Excluidos: {len(EXCLUDE_FROM_FUZZY)}')

Aceptados: 20 | Excluidos: 0

### 7.3 Revisión estricta (0.50 ≤ score < 0.75)

Por defecto ninguno se acepta. Añadir a `ACCEPT_LOW_FUZZY` los correctos.

In [12]:
low_matches[['player_sf', 'team', 'cg_match', 'score']]

                   player_sf              team             cg_match  score
43    Muhammed Alperen Uysal       Antalyaspor        alperen uysal  0.743
70         Tuncer Duhan Aksu      İstanbulspor           duhan aksu  0.741
56         João Pedro Galvão        Fenerbahçe           joao pedro  0.741
36               Eren Elmalı       Trabzonspor    evren eren elmali  0.741
15         Maximiliano Gómez       Trabzonspor           maxi gomez  0.741
118    Abdullah Dijlan Aydin      İstanbulspor         dijlan aydin  0.727
39        Barış Alper Yılmaz       Galatasaray         baris yilmaz  0.714
88           Mohammed Kamara         Hatayspor        muhammed mert  0.714
16                Campanharo       Kayserispor   gustavo campanharo  0.714
2          Mahmoud Trézéguet       Trabzonspor            trezeguet  0.692
22     Mehmet Feyzi Yıldırım         Kasımpaşa       feyzi yildirim  0.688
61             Emirhan Zaman       Trabzonspor          serkan asan  0.667
84           Amar Rahmanović         Konyaspor  amir hadziahmetovic  0.647
94            Yusuf Saitoğlu      Ümraniyespor       yunus mertoglu  0.643
53                Kévin Soni   Adana Demirspor      kevin rodrigues  0.640
31                Onur Ergün      İstanbulspor         okan erdogan  0.636
103          Erdem Çetinkaya         Kasımpaşa       erdem canpolat  0.621
33               Gökhan Töre    MKE Ankaragücü         gokhan akkan  0.609
82          Amilton da Silva         Konyaspor              amilton  0.609
97           Berkay Aydoğmuş     Başakşehir FK      ayberk kaygisiz  0.600
113              Berat Eskin       Kayserispor           eray ozbek  0.571
0    Guilherme Haubert Sityá         Konyaspor            guilherme  0.562
105           Erol Can Akdag       Giresunspor          erkan anapa  0.560
120           Oğuzhan Yılmaz       Trabzonspor     dogucan haspolat  0.552
76          Ali Kaan Güneren    MKE Ankaragücü        yasin gureler  0.552
44                Simon Deli      İstanbulspor         jason lokilo  0.545
73                Arda Ünyay    MKE Ankaragücü         kaan cinkaya  0.545
96             Batuhan Arici      Ümraniyespor        antonio mrsic  0.538
123                 Mert Can    MKE Ankaragücü          mahmut akan  0.526
121        Taylan Utku Aydın         Kasımpaşa          tunay torun  0.519
42             Kenan Karaman       Beşiktaş JK       nathan redmond  0.519
79            Nicholas Anwan  Fatih Karagümrük    lawrence nicholas  0.516
59          Salih Malkoçoğlu       Trabzonspor     kagan moradaoglu  0.500
19              Nacer Chadli     Başakşehir FK     sener ozbayrakli  0.500
10               Deniz Tabak      Ümraniyespor        adel bettaieb  0.500
119          Hasan Yesilyurt         Kasımpaşa        fabiano silva  0.500
114          Gunes Guventurk      Ümraniyespor        oguz gurbulak  0.500

In [13]:
# ── Matches de score bajo confirmados manualmente ─────────────
ACCEPT_LOW_FUZZY = ['muhammed alperen uysal',
                    'tuncer duhan aksu',
                    'joao pedro galvao',
                    'eren elmal',
                    'maximiliano gomez',
                    'abdullah dijlan aydin',
                    'bars alper ylmaz',
                    'campanharo',
                    'mahmoud trezeguet',
                    'mehmet feyzi yldrm',
                    'amilton da silva',
                    'guilherme haubert sitya'

]
# ─────────────────────────────────────────────────────────────

low_accepted = low_matches[low_matches['player_norm'].isin(ACCEPT_LOW_FUZZY)]
print(f'Aceptados del nivel bajo: {len(low_accepted)}')

Aceptados del nivel bajo: 12

### 7.4 Revisión muy estricta (score < 0.50)

Por defecto ninguno se acepta. Añadir a `ACCEPT_VERY_LOW_FUZZY` los correctos.

In [14]:
very_low_matches[['player_sf', 'team', 'cg_match', 'score']]

                 player_sf             team           cg_match  score
74    Berat Ayberk Özdemir      Trabzonspor  evren eren elmali  0.486
9           Mergim Berisha       Fenerbahçe    michy batshuayi  0.483
89           Enzo Crivelli    Başakşehir FK       deniz dilmen  0.480
11          Hamidou Traoré      Giresunspor        ramon arias  0.480
18           Arda Kızıldağ   MKE Ankaragücü     abdullah durak  0.480
81          Matěj Hanousek   MKE Ankaragücü        mahmut akan  0.480
20         Mario Balotelli  Adana Demirspor         simon deli  0.480
60                Niko Rak        Konyaspor          bruno paz  0.471
5        Andreas Cornelius      Trabzonspor  evren eren elmali  0.471
101        Senghor Faustin      Giresunspor    faustin senghor  0.467
86      Alexandru Cicâldău      Galatasaray       mauro icardi  0.467
93           Recep Yemişçi        Kasımpaşa  turgay gemicibasi  0.467
25          Ertuğrul Ersoy     İstanbulspor       eduart rroca  0.462
115          Dogukan Saral     Ümraniyespor      oguz gurbulak  0.462
112          Ferhat Yazgan     İstanbulspor          ali yasar  0.455
98          Semih Kılıçsoy      Beşiktaş JK         salih ucan  0.455
62     Osman Bugra Erdogan     Ümraniyespor  metehan mimaroglu  0.444
17                   Souza      Beşiktaş JK      oguzhan akgun  0.444
68          Jesé Rodríguez   MKE Ankaragücü               jese  0.444
75          Hamza Jaganjac  Adana Demirspor      samet akaydin  0.444
122  Ahmet Kağan Malatyalı      Kayserispor       ilhan parlak  0.438
95    Ibrahim Yilmaz Cicek   MKE Ankaragücü       lamine diack  0.438
21        Sokol Cikalleshi        Konyaspor       soner dikmen  0.429
91          Torgeir Børven     Gaziantep FK    joao figueiredo  0.429
109     Beren Kucukbasarik     Ümraniyespor         berke ozer  0.429
87     Poyraz Efe Yıldırım      Trabzonspor  evren eren elmali  0.424

In [15]:
# ── Matches very low confirmados manualmente ──────────────────
ACCEPT_VERY_LOW_FUZZY = ['senghor faustin',
                         'jese rodriguez'
]
# ─────────────────────────────────────────────────────────────

very_low_accepted = very_low_matches[very_low_matches['player_norm'].isin(ACCEPT_VERY_LOW_FUZZY)]
print(f'Aceptados del nivel very low: {len(very_low_accepted)}')

Aceptados del nivel very low: 2

### 7.5 Aplicar todos los fuzzy matches aceptados

In [16]:
all_fuzzy    = pd.concat([auto_matches, review_accepted, low_accepted, very_low_accepted], ignore_index=True)
fuzzy_lookup = dict(zip(all_fuzzy['player_norm'], all_fuzzy['cg_match']))

df_merged['player_norm_fuzzy'] = df_merged.apply(
    lambda r: fuzzy_lookup.get(r['player_norm'], r['player_norm'])
    if pd.isna(r['gross_annual_eur']) else r['player_norm'],
    axis=1
)

df_final = (
    df_merged
    .drop(columns=['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality'])
    .merge(
        df_cg[['player_norm', 'team_norm', 'gross_weekly_eur', 'gross_annual_eur',
               'position', 'age', 'nationality']],
        left_on=['player_norm_fuzzy', 'team_norm'],
        right_on=['player_norm', 'team_norm'],
        how='left'
    )
    .drop(columns=['player_norm_y', 'player_norm_fuzzy'])
    .rename(columns={'player_norm_x': 'player_norm'})
)

matched_final = df_final['gross_annual_eur'].notna().sum()
print(f'Resultado final: {matched_final}/{len(df_final)} ({matched_final/len(df_final):.1%})')
print(f'Sin salario:     {len(df_final) - matched_final}')

Resultado final: 539/588 (91.7%)
Sin salario:     49

## 8. Revisión de jugadores sin salario

Ordenados por equipo y minutos jugados para identificar si alguno debería tener salario.

In [17]:
sin_salario = (
    df_final[df_final['gross_annual_eur'].isna()]
    [['player', 'team', 'minutesPlayed', 'appearances', 'goals', 'assists']]
    .sort_values(['team', 'minutesPlayed'], ascending=[True, False])
    .reset_index(drop=True)
)

pd.set_option('display.max_rows', None)
print(f'Total sin salario: {len(sin_salario)}')
display(sin_salario)
pd.reset_option('display.max_rows')

Total sin salario: 49

,player,team,minutesPlayed,appearances,goals,assists
0,Mario Balotelli,Adana Demirspor,71,2,0,0
1,Kévin Soni,Adana Demirspor,67,3,0,1
2,Hamza Jaganjac,Adana Demirspor,10,1,0,0
3,Berkay Aydoğmuş,Başakşehir FK,74,3,0,0
4,Nacer Chadli,Başakşehir FK,62,1,1,0
5,Enzo Crivelli,Başakşehir FK,17,1,0,0
6,Souza,Beşiktaş JK,828,10,1,1
7,Semih Kılıçsoy,Beşiktaş JK,56,4,0,0
8,Kenan Karaman,Beşiktaş JK,36,2,0,0
9,Nicholas Anwan,Fatih Karagümrük,526,19,0,0
10,Mergim Berisha,Fenerbahçe,16,1,1,0
11,Alexandru Cicâldău,Galatasaray,11,1,0,0
12,Torgeir Børven,Gaziantep FK,17,1,0,0
13,Hamidou Traoré,Giresunspor,270,3,0,0
14,Erol Can Akdag,Giresunspor,63,4,0,0
15,Mohammed Kamara,Hatayspor,17,1,0,0
16,Recep Yemişçi,Kasımpaşa,45,1,0,0
17,Erdem Çetinkaya,Kasımpaşa,37,2,0,0
18,Hasan Yesilyurt,Kasımpaşa,16,1,0,0
19,Taylan Utku Aydın,Kasımpaşa,4,1,0,0
20,Berat Eskin,Kayserispor,12,2,0,0
21,Ahmet Kağan Malatyalı,Kayserispor,1,1,0,0
22,Amar Rahmanović,Konyaspor,226,5,0,0
23,Sokol Cikalleshi,Konyaspor,103,2,0,0
24,Niko Rak,Konyaspor,20,1,0,0
25,Matěj Hanousek,MKE Ankaragücü,2097,31,0,0
26,Arda Kızıldağ,MKE Ankaragücü,877,15,1,1
27,Gökhan Töre,MKE Ankaragücü,140,6,1,0
28,Ali Kaan Güneren,MKE Ankaragücü,56,3,0,0
29,Arda Ünyay,MKE Ankaragücü,20,1,0,0
30,Ibrahim Yilmaz Cicek,MKE Ankaragücü,8,1,0,0
31,Mert Can,MKE Ankaragücü,3,1,0,0
32,Andreas Cornelius,Trabzonspor,345,4,1,1
33,Emirhan Zaman,Trabzonspor,74,1,0,0
34,Berat Ayberk Özdemir,Trabzonspor,11,1,0,0
35,Salih Malkoçoğlu,Trabzonspor,8,1,0,0
36,Poyraz Efe Yıldırım,Trabzonspor,8,1,0,0
37,Oğuzhan Yılmaz,Trabzonspor,1,1,0,0
38,Batuhan Arici,Ümraniyespor,103,2,0,0
39,Yusuf Saitoğlu,Ümraniyespor,85,1,0,0
40,Dogukan Saral,Ümraniyespor,40,1,0,0
41,Beren Kucukbasarik,Ümraniyespor,19,1,0,0
42,Deniz Tabak,Ümraniyespor,13,1,0,0
43,Osman Bugra Erdogan,Ümraniyespor,13,1,0,0
44,Gunes Guventurk,Ümraniyespor,12,1,0,0
45,Onur Ergün,İstanbulspor,1836,30,2,0
46,Ertuğrul Ersoy,İstanbulspor,1670,23,2,0
47,Simon Deli,İstanbulspor,706,10,0,0
48,Ferhat Yazgan,İstanbulspor,119,2,0,0

### 8.1 Comparación manual por equipo

Para cada equipo con jugadores sin salario se muestra la plantilla completa de Capology
ordenada alfabéticamente por nombre normalizado, facilitando la detección visual de matches fallidos.

In [18]:
equipos_sin_salario = sin_salario['team'].unique()

for equipo in sorted(equipos_sin_salario):
    sf_jugadores = sin_salario[sin_salario['team'] == equipo][['player', 'minutesPlayed']].sort_values('player')

    equipo_norm  = normalize(equipo)
    cg_jugadores = (
        df_cg[df_cg['team_norm'] == equipo_norm][['player', 'player_norm']]
        .sort_values('player_norm')
        .reset_index(drop=True)
    )

    print(f'\n{"="*60}')
    print(f'  {equipo}  —  SF sin salario:')
    display(sf_jugadores.reset_index(drop=True))
    print(f'  CG plantilla completa:')
    display(cg_jugadores)

============================================================
  Adana Demirspor  —  SF sin salario:

            player  minutesPlayed
0   Hamza Jaganjac             10
1       Kévin Soni             67
2  Mario Balotelli             71

  CG plantilla completa:

                 player          player_norm
0     Abdurrahim Dursun    abdurrahim dursun
1         Arda Kurtulan        arda kurtulan
2          Artem Dzyuba         artem dzyuba
3          Badou Ndiaye         badou ndiaye
4    Benjamin Stambouli   benjamin stambouli
5           Berk Yildiz          berk yildiz
6      Birkir Bjarnason     birkir bjarnason
7    Britt Assombalonga   britt assombalonga
8         Cherif Ndiaye        cherif ndiaye
9        David Akintola       david akintola
10          Emre Akbaba          emre akbaba
11         Emrecan Uzun         emrecan uzun
12        Erhun Öztümer        erhun oztumer
13          Ertac Özbir          ertac ozbir
14  Fredrik Gulbrandsen  fredrik gulbrandsen
15        Furkan Soyalp        furkan soyalp
16    Giorgi Khabuliani    giorgi khabuliani
17         Gökhan Inler         gokhan inler
18          Gökhan Töre          gokhan tore
19        Goran Karacic        goran karacic
20       Henry Onyekuru       henry onyekuru
21      Ismail Cokcalis      ismail cokcalis
22       Jonas Svensson       jonas svensson
23          Jorge Morel          jorge morel
24          Jovan Manev          jovan manev
25      Kévin Rodrigues      kevin rodrigues
26           Mert Cetin           mert cetin
27         Mustafa Kapi         mustafa kapi
28       Salih Kavrazli       salih kavrazli
29        Samet Akaydin        samet akaydin
30        Samuel Nongoh        samuel nongoh
31          Semih Güler          semih guler
32           Simon Deli           simon deli
33        Vedat Karakus        vedat karakus
34   Yaroslav Rakitskiy   yaroslav rakitskiy
35      Younès Belhanda      younes belhanda
36        Yusuf Erdogan        yusuf erdogan
37           Yusuf Sari           yusuf sari

============================================================
  Başakşehir FK  —  SF sin salario:

            player  minutesPlayed
0  Berkay Aydoğmuş             74
1    Enzo Crivelli             17
2     Nacer Chadli             62

  CG plantilla completa:

                    player             player_norm
0            Adnan Januzaj           adnan januzaj
1              Ahmed Touba             ahmed touba
2       Alexandru Epureanu      alexandru epureanu
3          Ayberk Kaygisiz         ayberk kaygisiz
4            Batuhan Celik           batuhan celik
5             Berkay Özcan            berkay ozcan
6          Bertrand Traoré         bertrand traore
7              Caner Erkin             caner erkin
8          Danijel Aleksic         danijel aleksic
9             Deniz Dilmen            deniz dilmen
10             Deniz Türüc             deniz turuc
11             Eden Karzev             eden karzev
12                Edgar Ié                edgar ie
13        Efe Arda Koyuncu        efe arda koyuncu
14           Francis Nzaba           francis nzaba
15      Hasan Ali Kaldirim      hasan ali kaldirim
16         João Figueiredo         joao figueiredo
17          Júnior Caiçara          junior caicara
18              Léo Duarte              leo duarte
19            Lucas Biglia            lucas biglia
20              Lucas Lima              lucas lima
21         Mahmut Tekdemir         mahmut tekdemir
22              Mesut Özil              mesut ozil
23          Mounir Chouiar          mounir chouiar
24       Muhammed Sengezer       muhammed sengezer
25      Muhammet Arslantas      muhammet arslantas
26      Okechukwu Azubuike      okechukwu azubuike
27        Ömer Ali Sahiner        omer ali sahiner
28            Patryk Szysz            patryk szysz
29    Philippe Paulin Keny    philippe paulin keny
30  Sekou Tidiany Bangoura  sekou tidiany bangoura
31        Sener Özbayrakli        sener ozbayrakli
32           Serdar Gürler           serdar gurler
33             Shaocong Wu             shaocong wu
34           Stefano Okaka           stefano okaka
35          Volkan Babacan          volkan babacan
36      Yagiz Efe Erataman      yagiz efe erataman
37   Youssouf Ndayishimiye   youssouf ndayishimiye

============================================================
  Beşiktaş JK  —  SF sin salario:

           player  minutesPlayed
0   Kenan Karaman             36
1  Semih Kılıçsoy             56
2           Souza            828

  CG plantilla completa:

                    player             player_norm
0          Alexandru Maxim         alexandru maxim
1      Amir Hadziahmetovic     amir hadziahmetovic
2           Arthur Masuaku          arthur masuaku
3         Atiba Hutchinson        atiba hutchinson
4            Berkay Vardar           berkay vardar
5               Cenk Tosun              cenk tosun
6                Dele Alli               dele alli
7              Emre Bilgin             emre bilgin
8          Emrecan Uzunhan         emrecan uzunhan
9         Ersin Destanoglu        ersin destanoglu
10       Francisco Montero       francisco montero
11        Gedson Fernandes        gedson fernandes
12  Georges-Kevin N'Koudou  georges kevin n koudou
13          Jackson Muleka          jackson muleka
14                   Josef                   josef
15     Kerem Atakan Kesgin     kerem atakan kesgin
16              Mert Günok              mert gunok
17          Nathan Redmond          nathan redmond
18             Necip Uysal             necip uysal
19           Oguzhan Akgün           oguzhan akgun
20             Omar Colley             omar colley
21              Onur Bulut              onur bulut
22          Rachid Ghezzal          rachid ghezzal
23            Romain Saïss            romain saiss
24              Salih Ucan              salih ucan
25           Tayfur Bingöl           tayfur bingol
26            Tayyip Sanuc            tayyip sanuc
27              Tyler Boyd              tyler boyd
28              Umut Meras              umut meras
29          Utku Yuvakuran          utku yuvakuran
30         Valentin Rosier         valentin rosier
31       Vincent Aboubakar       vincent aboubakar
32                Welinton                welinton
33           Wout Weghorst           wout weghorst

============================================================
  Fatih Karagümrük  —  SF sin salario:

           player  minutesPlayed
0  Nicholas Anwan            526

  CG plantilla completa:

                  player           player_norm
0            Adem Ljajic           adem ljajic
1             Adnan Ugur            adnan ugur
2      Andrea Bertolacci     andrea bertolacci
3            Batuhan Sen           batuhan sen
4           Brahim Darri          brahim darri
5        Bruno Rodrigues       bruno rodrigues
6        Burak Bekaroglu       burak bekaroglu
7          Burak Kapacak         burak kapacak
8            Caner Erkin           caner erkin
9   Colin Kazim-Richards  colin kazim richards
10       Davide Biraschi       davide biraschi
11         Ebrima Colley         ebrima colley
12             Efe Tatli             efe tatli
13       Efecan Mizrakci       efecan mizrakci
14      Emiliano Viviano      emiliano viviano
15           Emir Tintis           emir tintis
16          Fabio Borini          fabio borini
17          Fatih Kurnaz          fatih kurnaz
18      Ibrahim Dresevic      ibrahim dresevic
19   Jean Evrard Kouassi   jean evrard kouassi
20          Jimmy Durmaz          jimmy durmaz
21            Kerim Frei            kerim frei
22     Lawrence Nicholas     lawrence nicholas
23         Levent Mercan         levent mercan
24        Magomed Ozdoev        magomed ozdoev
25          Matteo Ricci          matteo ricci
26          Mbaye Diagne          mbaye diagne
27   Muzaffer Cem Kablan   muzaffer cem kablan
28       Otabek Shukurov       otabek shukurov
29         Rayyan Baniya         rayyan baniya
30       Saba Lobjanidze       saba lobjanidze
31          Salih Dursun          salih dursun
32            Samed Onur            samed onur
33      Sofiane Feghouli      sofiane feghouli
34        Steven Caulker        steven caulker
35         Yusuf Erdogan         yusuf erdogan

============================================================
  Fenerbahçe  —  SF sin salario:

           player  minutesPlayed
0  Mergim Berisha             16

  CG plantilla completa:

                 player          player_norm
0        Altay Bayindir       altay bayindir
1            Arda Güler           arda guler
2         Attila Szalai        attila szalai
3   Bright Osayi-Samuel  bright osayi samuel
4                 Bruma                bruma
5      Cagtay Kurukalip     cagtay kurukalip
6           Diego Rossi          diego rossi
7              Emre Mor             emre mor
8        Enner Valencia       enner valencia
9        Ertugrul Cetin       ertugrul cetin
10       Ezgjan Alioski       ezgjan alioski
11       Ferdi Kadioglu       ferdi kadioglu
12     Gustavo Henrique     gustavo henrique
13  Irfan Can Egribayat  irfan can egribayat
14    Irfan Can Kahveci    irfan can kahveci
15           Isak Vural           isak vural
16        Ismail Yüksek        ismail yuksek
17   Jayden Oosterwolde   jayden oosterwolde
18           João Pedro           joao pedro
19          Joshua King          joshua king
20              Lincoln              lincoln
21           Luan Peres           luan peres
22       Mauricio Lemos       mauricio lemos
23    Mert Hakan Yandas    mert hakan yandas
24      Michy Batshuayi      michy batshuayi
25        Miguel Crespo        miguel crespo
26            Miha Zajc            miha zajc
27        Nazim Sangaré        nazim sangare
28        Samet Akaydin        samet akaydin
29          Serdar Aziz          serdar aziz
30        Serdar Dursun        serdar dursun
31         Willian Arão         willian arao

============================================================
  Galatasaray  —  SF sin salario:

               player  minutesPlayed
0  Alexandru Cicâldău             11

  CG plantilla completa:

                 player          player_norm
0   Abdülkerim Bardakci  abdulkerim bardakci
1       Bafétimbi Gomis      bafetimbi gomis
2          Baran Aksaka         baran aksaka
3          Baris Yilmaz         baris yilmaz
4          Berkan Kutlu         berkan kutlu
5         Dries Mertens        dries mertens
6           Emin Bayram          emin bayram
7         Emre Tasdemir        emre tasdemir
8      Fernando Muslera     fernando muslera
9       Fredrik Midtsjö      fredrik midtsjo
10          Hamza Akman          hamza akman
11      Haris Seferovic      haris seferovic
12        Jankat Yilmaz        jankat yilmaz
13            Juan Mata            juan mata
14           Kaan Ayhan           kaan ayhan
15     Kazimcan Karatas     kazimcan karatas
16     Kerem Aktürkoglu     kerem akturkoglu
17           Léo Dubois           leo dubois
18       Lucas Torreira       lucas torreira
19         Mathias Ross         mathias ross
20         Mauro Icardi         mauro icardi
21      Metehan Baltaci      metehan baltaci
22        Milot Rashica        milot rashica
23       Nicolò Zaniolo       nicolo zaniolo
24           Okan Kocuk           okan kocuk
25  Patrick van Aanholt  patrick van aanholt
26           Sacha Boey           sacha boey
27         Sam Adekugbe         sam adekugbe
28      Sérgio Oliveira      sergio oliveira
29       Victor Nelsson       victor nelsson
30          Yunus Akgün          yunus akgun
31          Yusuf Demir          yusuf demir

============================================================
  Gaziantep FK  —  SF sin salario:

           player  minutesPlayed
0  Torgeir Børven             17

  CG plantilla completa:

                    player             player_norm
0        Abdulkadir Parmak       abdulkadir parmak
1         Abdulkerim Cakar        abdulkerim cakar
2         Alexander Merkel        alexander merkel
3          Alexandru Maxim         alexandru maxim
4               Alin Tosca              alin tosca
5             Ángelo Sagal            angelo sagal
6            Arda Kizildag           arda kizildag
7          Bahadir Gölgeli         bahadir golgeli
8      Berkan Küpelikilinc     berkan kupelikilinc
9               Eren Cakir              eren cakir
10              Erten Ersu              erten ersu
11          Ertugrul Ersoy          ertugrul ersoy
12           Furkan Soyalp           furkan soyalp
13            Günay Güvenc            gunay guvenc
14  Halil Ibrahim Pehlivan  halil ibrahim pehlivan
15         João Figueiredo         joao figueiredo
16          Lazar Markovic          lazar markovic
17         Luka Stankovski         luka stankovski
18          Marko Jevtovic          marko jevtovic
19          Matej Hanousek          matej hanousek
20             Mirza Cihan             mirza cihan
21     Mustafa Burak Bozan     mustafa burak bozan
22      Mustafa Eskihellac      mustafa eskihellac
23           Ömürcan Artan           omurcan artan
24         Onurhan Babuscu         onurhan babuscu
25         Papy Djilobodji         papy djilobodji
26         Stelios Kitsiou         stelios kitsiou
27           Tomas Pekhart           tomas pekhart
28            Valmir Veliu            valmir veliu

============================================================
  Giresunspor  —  SF sin salario:

           player  minutesPlayed
0  Erol Can Akdag             63
1  Hamidou Traoré            270

  CG plantilla completa:

                  player           player_norm
0           Alexis Pérez          alexis perez
1           Alper Uludag          alper uludag
2             Arda Kilic            arda kilic
3            Borja Sainz           borja sainz
4         Brandley Kuwas        brandley kuwas
5          Cihat Topatan         cihat topatan
6            Dogac Cifci           dogac cifci
7        Dogan Can Davas       dogan can davas
8          Doganay Aygün         doganay aygun
9            Erkan Anapa           erkan anapa
10        Faruk Can Genc        faruk can genc
11          Fatih Yilmaz          fatih yilmaz
12       Faustin Senghor       faustin senghor
13         Ferhat Kaplan         ferhat kaplan
14         Görkem Saglam         gorkem saglam
15     Hayrullah Bilazer     hayrullah bilazer
16      Jorman Campuzano      jorman campuzano
17           Kadir Seven           kadir seven
18             Mert Kurt             mert kurt
19     Murat Cem Akpinar     murat cem akpinar
20      Ogulcan Caglayan      ogulcan caglayan
21          Onurcan Piri          onurcan piri
22      Osman Pasa Zorlu      osman pasa zorlu
23  Rahmetullah Berisbek  rahmetullah berisbek
24           Ramón Arias           ramon arias
25            Riad Bajić            riad bajic
26          Robert Mejía          robert mejia
27      Sergen Picinciol      sergen picinciol
28                Sergio                sergio
29           Talha Ülvan           talha ulvan
30       Vukan Savicevic       vukan savicevic

============================================================
  Hatayspor  —  SF sin salario:

            player  minutesPlayed
0  Mohammed Kamara             17

  CG plantilla completa:

                 player          player_norm
0      Abdullah Yigiter     abdullah yigiter
1        Ayoub El Kaabi       ayoub el kaabi
2       Bertug Yildirim      bertug yildirim
3       Burak Bekaroglu      burak bekaroglu
4           Burak Öksüz          burak oksuz
5          Burak Yilmaz         burak yilmaz
6        Christian Atsu       christian atsu
7     Dylan Saint-Louis    dylan saint louis
8       Engin Can Aksoy      engin can aksoy
9        Erce Kardesler       erce kardesler
10       Jeremy Dudziak       jeremy dudziak
11           Kaan Kanak           kaan kanak
12  Kamil Ahmet Cörekci  kamil ahmet corekci
13          Kerim Alici          kerim alici
14           Kévin Soni           kevin soni
15          Kevin Varga          kevin varga
16          Koray Yagci          koray yagci
17      Mehdi Boudjemaa      mehdi boudjemaa
18        Muhammed Mert        muhammed mert
19         Musa Cagiran         musa cagiran
20       Ognjen Vranjes       ognjen vranjes
21           Onur Ergün           onur ergun
22         Rayane Aabid         rayane aabid
23        Rúben Ribeiro        ruben ribeiro
24      Saba Lobjanidze      saba lobjanidze
25            Sadik Bas            sadik bas
26         Sam Adekugbe         sam adekugbe
27        Sarper Caglar        sarper caglar
28       Selimcan Temel       selimcan temel
29        Simon Falette        simon falette
30    Yavuz Bugra Boyar    yavuz bugra boyar
31              Zé Luís              ze luis

============================================================
  Kasımpaşa  —  SF sin salario:

              player  minutesPlayed
0    Erdem Çetinkaya             37
1    Hasan Yesilyurt             16
2      Recep Yemişçi             45
3  Taylan Utku Aydın              4

  CG plantilla completa:

                 player          player_norm
0           Ahmet Engin          ahmet engin
1           Ali Demirel          ali demirel
2        Ali Gholizadeh       ali gholizadeh
3          Anil Özcelik         anil ozcelik
4            Aytac Kara           aytac kara
5    Bengali-Fodé Koita   bengali fode koita
6          Berat Kalkan         berat kalkan
7        Bersant Celina       bersant celina
8        Daniel Graovac       daniel graovac
9        Erdem Canpolat       erdem canpolat
10    Ertugrul Taskiran    ertugrul taskiran
11        Fabiano Silva        fabiano silva
12       Feyzi Yildirim       feyzi yildirim
13  Florent Hadergjonaj  florent hadergjonaj
14           Gökhan Gül           gokhan gul
15         Günay Güvenc         gunay guvenc
16   Haris Hajradinovic   haris hajradinovic
17        Jeffrey Bruma        jeffrey bruma
18         Mamadou Fall         mamadou fall
19     Mehmet Enes Sari     mehmet enes sari
20        Mickaël Malsa        mickael malsa
21       Mickaël Tirpan       mickael tirpan
22  Mortadha Ben Ouanes  mortadha ben ouanes
23       Mounir Chouiar       mounir chouiar
24   Mustafa Eskihellac   mustafa eskihellac
25       Oguzhan Yilmaz       oguzhan yilmaz
26      Papy Djilobodji      papy djilobodji
27       Raoul Petretta       raoul petretta
28            Ryan Donk            ryan donk
29      Sadik Ciftpinar      sadik ciftpinar
30          Selim Dilli          selim dilli
31     Stéphane Bahoken     stephane bahoken
32       Tarkan Serbest       tarkan serbest
33          Tunay Torun          tunay torun
34    Turgay Gemicibasi    turgay gemicibasi
35    Valentin Eysseric    valentin eysseric
36          Yasin Özcan          yasin ozcan
37          Yunus Malli          yunus malli

============================================================
  Kayserispor  —  SF sin salario:

                  player  minutesPlayed
0  Ahmet Kağan Malatyalı              1
1            Berat Eskin             12

  CG plantilla completa:

                   player            player_norm
0       Abdulkadir Tasdan      abdulkadir tasdan
1              Ali Karimi             ali karimi
2       Andrea Bertolacci      andrea bertolacci
3        Anthony Uzodimma       anthony uzodimma
4            Arif Kocaman           arif kocaman
5             Baran Gezek            baran gezek
6          Bernard Mensah         bernard mensah
7           Bilal Bayazit          bilal bayazit
8             Carlos Mané            carlos mane
9              Cenk Gönen             cenk gonen
10  Dimitrios Kolovetsios  dimitrios kolovetsios
11           Emrah Bassan           emrah bassan
12             Eray Özbek             eray ozbek
13         Gökhan Sazdagi         gokhan sazdagi
14     Gustavo Campanharo     gustavo campanharo
15        Hayrullah Erkip        hayrullah erkip
16           Ilhan Parlak           ilhan parlak
17         Joseph Attamah         joseph attamah
18          Lionel Carole          lionel carole
19         Majid Hosseini         majid hosseini
20             Mame Thiam             mame thiam
21       Mario Gavranovic       mario gavranovic
22         Miguel Cardoso         miguel cardoso
23   Muhammed Eren Arikan   muhammed eren arikan
24       Mustafa Pektemek       mustafa pektemek
25       Nurettin Korkmaz       nurettin korkmaz
26          Olivier Kemen          olivier kemen
27             Onur Bulut             onur bulut
28        Ramazan Civelek        ramazan civelek
29           Samil Öztürk           samil ozturk
30       Talha Sariarslan       talha sariarslan
31              Yaw Ackah              yaw ackah

============================================================
  Konyaspor  —  SF sin salario:

             player  minutesPlayed
0   Amar Rahmanović            226
1          Niko Rak             20
2  Sokol Cikalleshi            103

  CG plantilla completa:

                   player            player_norm
0           Adil Demirbag          adil demirbag
1         Ahmet Karademir        ahmet karademir
2              Ahmet Oguz             ahmet oguz
3       Alejandro Pozuelo      alejandro pozuelo
4                 Amilton                amilton
5     Amir Hadziahmetovic    amir hadziahmetovic
6     Andreas Bouchalakis    andreas bouchalakis
7          Baris Yardimci         baris yardimci
8               Bruno Paz              bruno paz
9         Cebrail Karayel        cebrail karayel
10        Domagoj Pavicic        domagoj pavicic
11           Endri Cekici           endri cekici
12         Erhan Erentürk         erhan erenturk
13        Francisco Calvo        francisco calvo
14              Guilherme              guilherme
15          Ibrahim Sehic          ibrahim sehic
16      Kahraman Demirtas      kahraman demirtas
17        Konrad Michalak        konrad michalak
18           Mahir Emreli           mahir emreli
19             Mame Diouf             mame diouf
20          Marlos Moreno          marlos moreno
21  Mehmet Ali Büyüksayar  mehmet ali buyuksayar
22         Mehmet Erdogan         mehmet erdogan
23           Metehan Mert           metehan mert
24         Muhammet Demir         muhammet demir
25          Ogulcan Ülgün          ogulcan ulgun
26           Robert Muric           robert muric
27           Soner Dikmen           soner dikmen
28           Uche Ikpeazu           uche ikpeazu
29        Ugurcan Yazgili        ugurcan yazgili
30           Yasir Subasi           yasir subasi
31           Zymer Bytyqi           zymer bytyqi

============================================================
  MKE Ankaragücü  —  SF sin salario:

                 player  minutesPlayed
0      Ali Kaan Güneren             56
1         Arda Kızıldağ            877
2            Arda Ünyay             20
3           Gökhan Töre            140
4  Ibrahim Yilmaz Cicek              8
5        Matěj Hanousek           2097
6              Mert Can              3

  CG plantilla completa:

                       player                player_norm
0              Abdullah Durak             abdullah durak
1                    Ali Sowe                   ali sowe
2             Alperen Babacan            alperen babacan
3   Anastasios Chatzigiovanis  anastasios chatzigiovanis
4           Andrej Djokanovic          andrej djokanovic
5              Atakan Cankaya             atakan cankaya
6            Bahadir Güngördü           bahadir gungordu
7          Bevic Moussiti-Oko         bevic moussiti oko
8                Dogukan Kaya               dogukan kaya
9                 Emre Kilinc                emre kilinc
10              Enock Kwateng              enock kwateng
11              Eren Derdiyok              eren derdiyok
12           Federico Macheda           federico macheda
13              Firatcan Üzüm              firatcan uzum
14              Furkan Ceylan              furkan ceylan
15              Gboly Ariyibi              gboly ariyibi
16               Ghayas Zahid               ghayas zahid
17             Giorgi Beridze             giorgi beridze
18               Gökhan Akkan               gokhan akkan
19         Hasan Ali Kaldirim         hasan ali kaldirim
20                       Jesé                       jese
21               Kaan Cinkaya               kaan cinkaya
22              Kévin Malcuit              kevin malcuit
23               Lamine Diack               lamine diack
24                Mahmut Akan                mahmut akan
25                     Marlon                     marlon
26                     Milson                     milson
27              Nihad Mujakic              nihad mujakic
28             Nurullah Aslan             nurullah aslan
29                Oguz Ceylan                oguz ceylan
30                   Pedrinho                   pedrinho
31                       Pêpê                       pepe
32             Sahverdi Cetin             sahverdi cetin
33            Sinan Osmanoglu            sinan osmanoglu
34          Sitki Ferdi Imdat          sitki ferdi imdat
35            Stelios Kitsiou            stelios kitsiou
36           Taylan Antalyali           taylan antalyali
37              Tolga Cigerci              tolga cigerci
38             Uros Radakovic             uros radakovic
39              Yasin Güreler              yasin gureler

============================================================
  Trabzonspor  —  SF sin salario:

                 player  minutesPlayed
0     Andreas Cornelius            345
1  Berat Ayberk Özdemir             11
2         Emirhan Zaman             74
3        Oğuzhan Yılmaz              1
4   Poyraz Efe Yıldırım              8
5      Salih Malkoçoğlu              8

  CG plantilla completa:

                  player           player_norm
0        Abdülkadir Ömür       abdulkadir omur
1      Abdulkadir Parmak     abdulkadir parmak
2   Anastasios Bakasetas  anastasios bakasetas
3            Arif Bosluk           arif bosluk
4            Bruno Peres           bruno peres
5                Djaniny               djaniny
6       Dogucan Haspolat      dogucan haspolat
7         Dorukhan Toköz        dorukhan tokoz
8             Edin Visca            edin visca
9        Emrehan Gedikli       emrehan gedikli
10           Enis Bardhi           enis bardhi
11     Evren Eren Elmali     evren eren elmali
12           Hakan Aydin           hakan aydin
13       Hüseyin Türkmen       huseyin turkmen
14  Jean-Philippe Gbamin  jean philippe gbamin
15   Jens Stryger Larsen   jens stryger larsen
16      Kagan Moradaoglu      kagan moradaoglu
17             Kerem Sen             kerem sen
18        Lazar Markovic        lazar markovic
19        Manolis Siopis        manolis siopis
20           Marc Bartra           marc bartra
21          Marek Hamsik          marek hamsik
22            Maxi Gómez            maxi gomez
23     Montasser Lahtimi     montasser lahtimi
24    Muhammet Taha Tepe    muhammet taha tepe
25           Naci Ünüvar           naci unuvar
26           Serkan Asan           serkan asan
27       Stefano Denswil       stefano denswil
28       Taha Altikardes       taha altikardes
29             Trezeguet             trezeguet
30         Ugurcan Cakir         ugurcan cakir
31            Umut Bozok            umut bozok
32            Vitor Hugo            vitor hugo
33         Yusuf Erdogan         yusuf erdogan
34          Yusuf Yazici          yusuf yazici

============================================================
  Ümraniyespor  —  SF sin salario:

                player  minutesPlayed
0        Batuhan Arici            103
1   Beren Kucukbasarik             19
2          Deniz Tabak             13
3        Dogukan Saral             40
4      Gunes Guventurk             12
5  Osman Bugra Erdogan             13
6       Yusuf Saitoğlu             85

  CG plantilla completa:

                    player             player_norm
0            Adel Bettaieb           adel bettaieb
1       Alexandru Epureanu      alexandru epureanu
2                  Allyson                 allyson
3               Anil Demir              anil demir
4            Antonio Mrsic           antonio mrsic
5               Berke Özer              berke ozer
6            Durel Avounou           durel avounou
7               Emre Nefiz              emre nefiz
8            Ermir Lenjani           ermir lenjani
9          Fatih Sanlitürk         fatih sanliturk
10                 Geraldo                 geraldo
11            Isaac Sackey            isaac sackey
12          Jesse Sekidika          jesse sekidika
13           Kartal Yilmaz           kartal yilmaz
14             Mert Yilmaz             mert yilmaz
15       Metehan Mimaroglu       metehan mimaroglu
16            Mustafa Eser            mustafa eser
17           Nika Gagnidze           nika gagnidze
18           Oguz Gürbulak           oguz gurbulak
19       Olarenwaju Kayode       olarenwaju kayode
20           Onur Atasayar           onur atasayar
21               Onur Ayik               onur ayik
22           Orkun Özdemir           orkun ozdemir
23            Serkan Göksu            serkan goksu
24        Serkan Kirintili        serkan kirintili
25           Strahil Popov           strahil popov
26  Tahsin Hacimustafaoglu  tahsin hacimustafaoglu
27         Tomislav Glumac         tomislav glumac
28              Umut Nayir              umut nayir
29       Valentin Gheorghe       valentin gheorghe
30      Yonathan Del Valle      yonathan del valle
31          Yunus Mertoglu          yunus mertoglu

============================================================
  İstanbulspor  —  SF sin salario:

           player  minutesPlayed
0  Ertuğrul Ersoy           1670
1   Ferhat Yazgan            119
2      Onur Ergün           1836
3      Simon Deli            706

  CG plantilla completa:

                player         player_norm
0         Adi Mehremic        adi mehremic
1         Ahmet Kivanc        ahmet kivanc
2          Aldin Cajic         aldin cajic
3            Ali Yasar           ali yasar
4             Alp Arda            alp arda
5         David Jensen        david jensen
6      Demeaco Duhaney     demeaco duhaney
7      Denis Kovacevic     denis kovacevic
8         Dijlan Aydin        dijlan aydin
9           Duhan Aksu          duhan aksu
10        Eduart Rroca        eduart rroca
11           Emeka Eze           emeka eze
12  Emir Kaan Gültekin  emir kaan gultekin
13        Eslem Öztürk        eslem ozturk
14      Florian Loshaj      florian loshaj
15      Ibrahim Yilmaz      ibrahim yilmaz
16        Jason Lokilo        jason lokilo
17      Jetmir Topalli      jetmir topalli
18         Kagan Bagis         kagan bagis
19           Kerem Sen           kerem sen
20      Kristal Abazaj      kristal abazaj
21        Mahamadou Ba        mahamadou ba
22        Mehmet Yesil        mehmet yesil
23     Melih Kabasakal     melih kabasakal
24       Michael Ologo       michael ologo
25         Mirza Cihan         mirza cihan
26    Muammer Sarikaya    muammer sarikaya
27     Mücahit Serbest     mucahit serbest
28      Oguzhan Berber      oguzhan berber
29        Okan Erdogan        okan erdogan
30       Patrick Ebert       patrick ebert
31       Raymond Owusu       raymond owusu
32        Sindrit Guri        sindrit guri
33        Valmir Veliu        valmir veliu
34        Valon Ethemi        valon ethemi
35          Vefa Temel          vefa temel
36          Yusuf Özer          yusuf ozer

In [19]:
# ── Matches manuales (nombres muy distintos o traspasos invernales) ──
# Formato: (player_norm_sf, team_norm_sf): (player_norm_cg, team_norm_cg)
MANUAL_MATCHES = {
    ('souza', 'besiktas jk')              : ('welinton', 'besiktas jk'),
    ('nicholas anwan', 'fatih karagumruk'): ('lawrence nicholas', 'fatih karagumruk'),
}
# ────────────────────────────────────────────────────────────────────
print(f'Matches manuales definidos: {len(MANUAL_MATCHES)}')

Matches manuales definidos: 2

In [20]:
# Aplicar matches manuales sobre los que siguen sin salario
for (p_sf, t_sf), (p_cg, t_cg) in MANUAL_MATCHES.items():
    mask = (df_final['player_norm'] == p_sf) & (df_final['team_norm'] == t_sf) & (df_final['gross_annual_eur'].isna())
    datos_cg = df_cg[(df_cg['player_norm'] == p_cg) & (df_cg['team_norm'] == t_cg)]
    if not datos_cg.empty and mask.any():
        for col in ['gross_weekly_eur', 'gross_annual_eur', 'position', 'age', 'nationality']:
            df_final.loc[mask, col] = datos_cg[col].values[0]
        print(f'✅ Match manual aplicado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')
    else:
        print(f'⚠️  No encontrado: {p_sf} ({t_sf}) → {p_cg} ({t_cg})')

matched_tras_manual = df_final['gross_annual_eur'].notna().sum()
print(f'\nTras matches manuales: {matched_tras_manual}/{len(df_final)} ({matched_tras_manual/len(df_final):.1%})')

✅ Match manual aplicado: souza (besiktas jk) → welinton (besiktas jk)
✅ Match manual aplicado: nicholas anwan (fatih karagumruk) → lawrence nicholas (fatih karagumruk)

Tras matches manuales: 541/588 (92.0%)

In [21]:
pd.reset_option('display.max_rows')

## 9. Guardado

Una vez revisado todo, se eliminan las columnas auxiliares y se guarda en `data/master/`.

In [22]:
df_final = df_final.drop(columns=['player_norm', 'team_norm'])

nombre_salida = 'master_turkey_2223.csv'
df_final.to_csv(MASTER_DIR / nombre_salida, index=False)

print(f'✅ Guardado: {nombre_salida}')
print(f'   Jugadores totales:  {len(df_final)}')
print(f'   Con salario:        {df_final["gross_annual_eur"].notna().sum()}')
print(f'   Sin salario (NaN):  {df_final["gross_annual_eur"].isna().sum()}')
print(f'   Columnas:           {df_final.shape[1]}')

✅ Guardado: master_turkey_2223.csv
   Jugadores totales:  588
   Con salario:        541
   Sin salario (NaN):  47
   Columnas:           121